### ISSUE TITLE
delegate_to not resolved in module

### ISSUE THREAD

**Issue by aikomastboom** [ansible/ansible#10051]
running the following task:

```
- name: "put the configuration on all dispatcher hosts"
  template: 
      src=template_name.nginx.conf
      dest=/etc/nginx/sites-available/vhostname.domainname
  delegate_to: "{{ item }}"
  with_items: "{{ dispatchers }}"
```

where dispatchers is a list of hosts e.g. ['dispatcher.local']
fails for me with:

```
fatal: [ninja.local -> dispatcher.lcoal] => Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 594, in _executor
  exec_rc = self._executor_internal(host, new_stdin)
File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 822, in _executor_internal
  complex_args=complex_args
File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1032, in _executor_internal_inner
  result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/template.py", line 94, in run
  remote_checksum = self.runner._remote_checksum(conn, tmp, dest, inject)
File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1238, in _remote_checksum
  python_interp = inject['hostvars'][inject['delegate_to']].get('ansible_python_interpreter', 'python')
File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 103, in __getitem__
  result = self.inventory.get_variables(host, vault_password=self.vault_password).copy()
File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 442, in get_variables
  raise Exception("host not found: %s" % hostname)
Exception: host not found: {{ item }}
```

It appears 'delegate_to' is resolved to correct host in https://github.com/ansible/ansible/blob/release1.8.2/lib/ansible/runner/__init__.py#L921 but not reinserted into 'inject' 

the following patch to /lib/ansible/runner/**init**.py seems to work (at least for me)

```
932            inject = delegate['inject']
+++            # set resolved delegate_to into inject so modules can call _remote_checksum
+++            inject['delegate_to'] = self.delegate_to
```

**Comment by arBmind** [comment]
Thank you... 

I just stumbled upon this bug.

I can also confirm that the patch fixes it.
Please merge.

**Comment by redbaron** [comment]
it was already fixed in trunk
