### ISSUE TITLE
Already tested playbook with su command, now results in TypeError.

### ISSUE THREAD

**Issue by raratiru** [ansible/ansible#10105]
Issue Type:
Bug Report

Ansible Version:

```
$ ansible --version
ansible 1.8.2
```

Environment:

Fedora 21

Summary:
When I try to execute a command using su, I receive a TypeError.

Steps To Reproduce:

```
$ cat ./sudo_play.yml:
- name: Test su connecting as current user
  hosts: mobile
  gather_facts: no
  tasks:
    - name: "No sudo or su"
      command: /usr/bin/whoami

    - name: "su to root"
      command: /usr/bin/whoami
      su: yes
```

```
$ cat ./inventory/hosts
[mobile]
192.168.1.12
```

```
$ cat inventory/group_vars/mobile/plain.yml

---
ansible_ssh_port: 22
ansible_ssh_user: george
```

```
$ ansible-vault view inventory/group_vars/mobile/vault.yml

---
ansible_su_pass: <english password that was working very well and did not change>
```

command:

$ ansible-playbook sudo_play.yml --ask-vault-pass -vvvv

Result:

```
PLAY [Test su connecting as current user] ************************************* 

TASK: [No sudo or su] ********************************************************* 
<192.168.1.12> ESTABLISH CONNECTION FOR USER: george
<192.168.1.12> REMOTE_MODULE command /usr/bin/whoami
<192.168.1.12> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=george -o ConnectTimeout=10 192.168.1.12 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1422318296.61-43388325281179 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1422318296.61-43388325281179 && echo $HOME/.ansible/tmp/ansible-tmp-1422318296.61-43388325281179'
<192.168.1.12> PUT /tmp/tmpN8F6T0 TO /home/george/.ansible/tmp/ansible-tmp-1422318296.61-43388325281179/command
<192.168.1.12> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=george -o ConnectTimeout=10 192.168.1.12 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/george/.ansible/tmp/ansible-tmp-1422318296.61-43388325281179/command; rm -rf /home/george/.ansible/tmp/ansible-tmp-1422318296.61-43388325281179/ >/dev/null 2>&1'
changed: [192.168.1.12] => {"changed": true, "cmd": ["/usr/bin/whoami"], "delta": "0:00:01.020576", "end": "2015-01-27 02:25:08.691834", "rc": 0, "start": "2015-01-27 02:25:07.671258", "stderr": "", "stdout": "george", "warnings": []}

TASK: [su to root] ************************************************************ 
<192.168.1.12> ESTABLISH CONNECTION FOR USER: george
<192.168.1.12> REMOTE_MODULE command /usr/bin/whoami
<192.168.1.12> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=george -o ConnectTimeout=10 192.168.1.12 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1422318308.74-206802874140947 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1422318308.74-206802874140947 && echo $HOME/.ansible/tmp/ansible-tmp-1422318308.74-206802874140947'
<192.168.1.12> PUT /tmp/tmpc4JDq2 TO /home/george/.ansible/tmp/ansible-tmp-1422318308.74-206802874140947/command
<192.168.1.12> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=george -o ConnectTimeout=10 192.168.1.12 /bin/sh -c 'su root -c "/bin/sh -c '"'"'echo SUDO-SUCCESS-kqebznlpsnzzvfrodqoyfgtnwhqexoau; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/george/.ansible/tmp/ansible-tmp-1422318308.74-206802874140947/command; rm -rf /home/george/.ansible/tmp/ansible-tmp-1422318308.74-206802874140947/ >/dev/null 2>&1'"'"'"'
fatal: [192.168.1.12] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1025, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 553, in _execute_module
    res = self._low_level_exec_command(conn, cmd, tmp, su=True, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1166, in _low_level_exec_command
    in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 337, in exec_command
    elif sudo_errput.endswith(prompt):
TypeError: endswith first arg must be str, unicode, or tuple, not NoneType


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/flyer/sudo_play.retry

192.168.1.12               : ok=1    changed=1    unreachable=1    failed=0   
```

**Comment by raratiru** [comment]
Downgrading to the previous version, solved the problem temporarily.

```
$ ansible --version
ansible 1.7.2
```

**Comment by raratiru** [comment]
Reinstalling ansible-1.8.2  seems to be working. Closing the issue.
