### ISSUE TITLE
if hosts section contains list(dict) instead of list(str), stacktrace is dumped 

### ISSUE THREAD

**Issue by feliksik** [ansible/ansible#10148]
I used a list of dicts for the hosts section -- apparently not legal. But Ansbile does not explain where in my document the error is. 

```
- name: a section I did not want to put in a role
  hosts:
    - { host: group1, var_for_context: group1var }
    - { host: group2, var_for_context: group2var }
  sudo: true
  tasks:
    - name: a test
      shell: echo "hi"
```

The result is: 

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 305, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/play.py", line 122, in __init__
    hosts = ';'.join(hosts)
TypeError: sequence item 0: expected string, dict found
```

Apparently the 'hosts' section doesn't accept a list of dicts, like the roles section does. You can argue whether this would be useful (I hoped it would, because it seemed good for my use case). 

However, Ansible should at least say where in the yaml file the structure is incorrect ( a line number). Now it's just guesswork.

**Comment by feliksik** [comment]
This is ansible 1.7.2
