### ISSUE TITLE
0.8 - make one-shot non-host loop action plugins possible (needed for pause)

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1015]

**Comment by timlnx** [comment]
My runner_pause branch (http://goo.gl/D0ZJB) has the latest copy of the pause task in it for testing.

Right now prompted pauses are (rightfully) breaking on flushing the input. For reference:

```
<tbielawa>@(deepfryer)[~/Projects/ansible] 13:38:45  (runner_pause)
$ ansible-playbook -vvv ./test.yaml              

PLAY [lnx] ********************* 

TASK: [pause] ********************* 
<redstonefoundries.com> ESTABLISH CONNECTION FOR USER: tbielawa
<redstonefoundries.com> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', u'User=tbielawa', 'redstonefoundries.com', 'mkdir -p $HOME/.ansible/tmp/ansible-1347039733.88-35512668385355 && chmod a+rx $HOME/.ansible/tmp/ansible-1347039733.88-35512668385355 && echo $HOME/.ansible/tmp/ansible-1347039733.88-35512668385355']
created 'pause' ActionModule: pause_type=prompt, duration_unit=minutes, calculated_seconds=None, prompt=[redstonefoundries.com] Press enter to continue:
(^C-c = continue early, ^C-a = abort)
fatal: [redstonefoundries.com] => Traceback (most recent call last):
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 224, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 275, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 370, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, inject)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/action_plugins/pause.py", line 96, in run
    tcflush(sys.stdin, TCIFLUSH)
error: (25, 'Inappropriate ioctl for device')
```

Timed pauses are working correctly but `KeyboardInterrupt`s are getting caught by runners `except KeyboardException:` in the `_parallel_exec` method.

**Comment by timlnx** [comment]
Working on this now. Mostly complete. Just working out something intelligent for building a `ReturnData` item for all hosts in a set.

**Comment by mpdehaan** [comment]
closing this ticket as we have the pull request, see comments on pull request -- basically I think this needs to switch to getattr and then make sure "make test" is clean and it's almost there.
