### ISSUE TITLE
0.7 setup module fails on SLES10SP3 x86_64

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1017]
Testing 0.7 tar file (`ansible 0.7`) against existing inventory: `setup` fails on Suse SLS 10 SP3 x86_64 (funnily enough it's the only one so far) with the following errors: (apologies for formatting)

```
fatal: [yyyy] => failed to parse: tcgetattr: Invalid argument
Traceback (most recent call last):
  File "/home/mensjp/.ansible/tmp/ansible-1346998450.3-240195705854548/setup", line 1010, in ?
    main()
  File "/home/mensjp/.ansible/tmp/ansible-1346998450.3-240195705854548/setup", line 732, in main
    data = run_setup(module)
  File "/home/mensjp/.ansible/tmp/ansible-1346998450.3-240195705854548/setup", line 679, in run_setu
+p
    facts = ansible_facts()
  File "/home/mensjp/.ansible/tmp/ansible-1346998450.3-240195705854548/setup", line 670, in ansible_
+facts
    facts.update(Network().populate())
  File "/home/mensjp/.ansible/tmp/ansible-1346998450.3-240195705854548/setup", line 443, in populate
    interfaces, ips = self.get_interfaces_info(ip_path, default_ipv4, default_ipv6)
  File "/home/mensjp/.ansible/tmp/ansible-1346998450.3-240195705854548/setup", line 522, in get_inte
+rfaces_info
    while '{0}_{1}'.format(iface, i) in interfaces:
AttributeError: 'str' object has no attribute 'format'
```

Commenting out the lines as to below diff solves the issue (?) and the `setup` JSON appears to be correctly populated.

```
*** /tmp/setup  Fri Sep  7 08:18:25 2012
--- ansible/ansible-0.7/library/setup   Fri Sep  7 08:18:46 2012
***************
*** 519,527 ****
                      # interface name for each address
                      if iface in interfaces:
                          i = 0
!                         while '{0}_{1}'.format(iface, i) in interfaces:
!                             i += 1
!                         iface = '{0}_{1}'.format(iface, i)

                      interfaces[iface] = {}
                      interfaces[iface]['macaddress'] = macaddress
--- 519,527 ----
                      # interface name for each address
                      if iface in interfaces:
                          i = 0
! #                       while '{0}_{1}'.format(iface, i) in interfaces:
! #                           i += 1
! #                       iface = '{0}_{1}'.format(iface, i)

                      interfaces[iface] = {}
                      interfaces[iface]['macaddress'] = macaddress
```

**Comment by mpdehaan** [comment]
What version of Python is that?

I'll accept patches to the release branch which I can cherry-pick to the
master, provided it is at least 2.4.

**Comment by mpdehaan** [comment]
tcgettattr noise should be output on stderr (so this is NOT a python version thing).   Are you possibly using an old version of the module?

**Comment by jpmens** [comment]
It's unlikely I was using an old version of the module as I'd just unpacked the (first) 0.7 tarball and was running from that.

If you can pls keep this ticket open, I'll check again. (The system is located 350kms away and it'll be Wednesday before I get there again...)

**Comment by mcodd** [comment]
I think I just ran into this too.  Missed that this was already here and submitted a new issue #1027 with pull request.  Per what I read at http://docs.python.org/library/stdtypes.html#string-methods, the str.format syntax is only valid in python >= 2.6

**Comment by mpdehaan** [comment]
Yep, this means we'll need to do 0.7.1 in the next several days.   Thanks!

**Comment by mpdehaan** [comment]
0.7.1 released today, so closing!

**Comment by jpmens** [comment]
Works with 0.7.1
