### ISSUE TITLE
Ansible 1.8.2-3 breaks aws-cli on CentOS 6

### ISSUE THREAD

**Issue by DrStrangepork** [ansible/ansible#10272]
Due to dependence on python-simplejson-2.0.9-3.1. Ansible-1.8.2-1.el6 does not have this dependency.

```
# rpm -q ansible                             # rpm -q ansible
ansible-1.8.2-1.el6.noarch                   ansible-1.8.2-3.el6.noarch
# rpm -qR ansible                            # rpm -qR ansible
/usr/bin/python                              /usr/bin/python
PyYAML                                       PyYAML
config(ansible) = 1.8.2-1.el6                config(ansible) = 1.8.2-3.el6
python(abi) = 2.6                            python(abi) = 2.6
python-crypto2.6                             python-crypto2.6
python-httplib2                              python-httplib2
python-jinja2                                python-jinja2
python-keyczar                               python-keyczar
python-paramiko                              python-paramiko
python-setuptools                            python-setuptools
rpmlib(CompressedFileNames) <= 3.0.4-1       **python-simplejson**
rpmlib(FileDigests) <= 4.6.0-1               rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1       rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1      rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(VersionedDependencies) <= 3.0.3-1     rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1                 rpmlib(VersionedDependencies) <= 3.0.3-1
                                             rpmlib(PayloadIsXz) <= 5.2-1             
```

Brand new install of CentOS 6.6:

```
# aws --version
aws-cli/1.7.9 Python/2.6.6 Linux/2.6.32-504.8.1.el6.x86_64

[root@ip-172-31-31-10 ~]# rpm -qa | grep python | sort
audit-libs-python-2.3.7-5.el6.x86_64
libselinux-python-2.0.94-5.8.el6.x86_64
libsemanage-python-2.0.43-4.2.el6.x86_64
newt-python-0.52.11-3.el6.x86_64
policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
python-2.6.6-52.el6.x86_64
python-argparse-1.2.1-2.el6.centos.noarch
python-backports-1.0-3.el6.centos.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el6.centos.noarch
python-boto-2.34.0-4.el6.noarch
python-chardet-2.0.1-1.el6.centos.noarch
python-cheetah-2.4.1-1.el6.x86_64
python-configobj-4.6.0-3.el6.noarch
python-iniparse-0.3.1-2.1.el6.noarch
python-jsonpatch-1.2-2.el6.centos.noarch
python-jsonpointer-1.0-3.el6.centos.noarch
python-libs-2.6.6-52.el6.x86_64
python-markdown-2.0.1-3.1.el6.noarch
python-oauth-1.0.1-1.el6.centos.noarch
python-ordereddict-1.1-2.el6.centos.noarch
python-pip-1.3.1-4.el6.noarch
python-prettytable-0.7.2-1.el6.centos.noarch
python-pycurl-7.19.0-8.el6.x86_64
python-pygments-1.1.1-1.el6.noarch
python-requests-1.1.0-4.el6.centos.noarch
python-rsa-3.1.1-5.el6.noarch
python-setuptools-0.6.10-3.el6.noarch
python-six-1.7.3-1.el6.centos.noarch
python-urlgrabber-3.9.1-9.el6.noarch
python-urllib3-1.5-7.el6.centos.noarch
rpm-python-4.8.0-38.el6_6.x86_64
setools-libs-python-3.3.7-4.el6.x86_64

[root@ip-172-31-31-10 ~]# pip list
argparse (1.3.0)
awscli (1.7.9)
backports.ssl-match-hostname (3.4.0.2)
bcdoc (0.12.2)
boto (2.32.1)
botocore (0.90.0)
chardet (2.0.1)
Cheetah (2.4.1)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.6.0)
distribute (0.6.10)
docutils (0.12)
iniparse (0.3.1)
jmespath (0.6.1)
jsonpatch (1.2)
jsonpointer (1.0)
Markdown (2.0.1)
oauth (1.0.1)
ordereddict (1.1)
policycoreutils-default-encoding (0.1)
prettytable (0.7.2)
pyasn1 (0.1.7)
pycurl (7.19.0)
Pygments (1.1.1)
pygpgme (0.1)
python-dateutil (2.4.0)
PyYAML (3.10)
requests (1.1.0)
rsa (3.1.2)
setools (1.0)
simplejson (3.3.0)
six (1.9.0)
urlgrabber (3.9.1)
urllib3 (1.5)
yum-metadata-parser (1.1.2)
yum-presto (0.4.4)

# yum install ansible
========================================================================================================================
 Package                            Arch                    Version                         Repository             Size
========================================================================================================================
Installing:
 ansible                            noarch                  1.8.2-3.el6                     epel                  1.5 M
Installing for dependencies:
 python-babel                       noarch                  0.9.4-5.1.el6                   base                  1.4 M
 python-crypto                      x86_64                  2.0.1-22.el6                    base                  159 k
 python-crypto2.6                   x86_64                  2.6.1-1.el6                     epel                  530 k
 python-httplib2                    noarch                  0.7.7-1.el6                     epel                   70 k
 python-jinja2                      x86_64                  2.2.1-2.el6_5                   base                  466 k
 python-keyczar                     noarch                  0.71c-1.el6                     epel                  219 k
 python-paramiko                    noarch                  1.7.5-2.1.el6                   base                  728 k
 python-pyasn1                      noarch                  0.0.12a-1.el6                   base                   70 k
 python-simplejson                  x86_64                  2.0.9-3.1.el6                   base                  126 k

Transaction Summary
========================================================================================================================
Install      10 Package(s)

# aws --version
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 50, in main
    return driver.main()
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 187, in main
    parser = self._create_parser()
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 168, in _create_parser
    command_table['help'] = self.create_help_command()
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 158, in create_help_command
    cli_data = self._get_cli_data()
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 85, in _get_cli_data
    self._cli_data = self.session.get_data('cli')
  File "/usr/lib/python2.6/site-packages/botocore/session.py", line 486, in get_data
    return self.get_component('data_loader').load_data(data_path)
  File "/usr/lib/python2.6/site-packages/botocore/loaders.py", line 43, in _wrapper
    data = func(self, orig_key, **kwargs)
  File "/usr/lib/python2.6/site-packages/botocore/loaders.py", line 203, in load_data
    return self._load_data(data_path)
  File "/usr/lib/python2.6/site-packages/botocore/loaders.py", line 216, in _load_data
    return self.file_loader.load_file(full_path)
  File "/usr/lib/python2.6/site-packages/botocore/loaders.py", line 75, in load_file
    return json.load(fp, object_pairs_hook=OrderedDict)
  File "/usr/lib64/python2.6/site-packages/simplejson/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/usr/lib64/python2.6/site-packages/simplejson/__init__.py", line 318, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'

# yum erase ansible python-simplejson
========================================================================================================================
 Package                            Arch                    Version                        Repository              Size
========================================================================================================================
Removing:
 ansible                            noarch                  1.8.2-3.el6                    @epel                  6.2 M
 python-simplejson                  x86_64                  2.0.9-3.1.el6                  @base                  437 k

Transaction Summary
========================================================================================================================
Remove        2 Package(s)

# aws --version
aws-cli/1.7.9 Python/2.6.6 Linux/2.6.32-504.8.1.el6.x86_64

# yum install yum-utils

# yumdownloader ansible
ansible-1.8.2-3.el6.noarch.rpm

# rpm -ivh --nodeps ./ansible-1.8.2-3.el6.noarch.rpm
Preparing...                ########################################### [100%]
   1:ansible                ########################################### [100%]

# aws --version
aws-cli/1.7.9 Python/2.6.6 Linux/2.6.32-504.8.1.el6.x86_64
```

**Comment by abadger** [comment]
This isn't an ansible bug but an incompatibility between the RHEL6 simplejson and the simplejson required by botocore.  I've added some options below:

#  A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- This doesn't appear to be an ansible bug but an incompatibility between the RHEL6 provided simplejson and the simplejson needed by botocore.  The best way to deal with this is likely to install the aws client and its required libraries into your home directory using pip's --user flag.   So instead of installing awscli byt doing `pip install aws-cli` do `pip install aws-cli --user`.  that will place the required libraries into ~/.local/lib/python2.6 and the programs into ~/.local/bin/ (you can add that into your PATH if you need to).

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
