### ISSUE TITLE
ec2_vol: Detaching using 'instance: None' is not working.

### ISSUE THREAD

**Issue by mtpereira** [ansible/ansible#10278]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

Mac OS X Mavericks
##### Summary:

I wanted to detach an EC2 volume, followed the documentation on http://docs.ansible.com/ec2_vol_module.html and got an error from AWS API because of the `None` on the `instance` field.
##### Steps To Reproduce:

Detaching an EC2 volume as per the documentation (http://docs.ansible.com/ec2_vol_module.html):

```
- name: detach volume
   ec2_vol:
       id: vol-xxxxxx
       region: my-aws-region
       instance: None
```
##### Expected Results:

Have the volume `vol-xxxxxx` detached and ready for use on another instance.
##### Actual Results:

```
TASK: [detach volume] ****************************************
<127.0.0.1> REMOTE_MODULE ec2_vol id=vol-xxxxxx region=my-aws-region instance=None
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615 && echo $HOME/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615']
<127.0.0.1> PUT /var/folders/zb/s_x416gj5fjgmyhjzhdl32dr0000gn/T/tmpHisZVe TO /home/user/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615/ec2_vol
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /opt/homebrew/opt/python/bin/python2.7 /home/user/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615/ec2_vol; rm -rf /home/user/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615/ >/dev/null 2>&1']

failed: [ip.compute.amazonaws.com -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615/ec2_vol", line 2192, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1424271506.99-194222936309615/ec2_vol", line 400, in main
    reservation = ec2.get_all_instances(instance_ids=instance)
  File "/opt/homebrew/lib/python2.7/site-packages/boto/ec2/connection.py", line 587, in get_all_instances
    max_results=max_results)
  File "/opt/homebrew/lib/python2.7/site-packages/boto/ec2/connection.py", line 683, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/opt/homebrew/lib/python2.7/site-packages/boto/connection.py", line 1166, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.Malformed</Code><Message>Invalid id: "None"</Message></Error></Errors><RequestID>90a23f53-8286-4f7c-8c60-6ca55c6d6198</RequestID></Response>
```

**Comment by mtpereira** [comment]
Uhm, I think I've opened this issue on the wrong project... Should I move this to ansible-modules-core?

Thank you.

**Comment by bcoca** [comment]
yes, closing this in favor of reopening in modules-core

**Comment by mtpereira** [comment]
Sorry about that. New issue opened at https://github.com/ansible/ansible-modules-core/issues/813
