### ISSUE TITLE
Issue with 'tenancy' in ec2 module of 1.8.3

### ISSUE THREAD

**Issue by tilgovi** [ansible/ansible#10286]
```
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
File "/home/tilgovi/.ansible/tmp/ansible-tmp-1424313543.05-272404152788372/ec2", line 2998, in <module>                                                                                                   
main()
File "/home/tilgovi/.ansible/tmp/ansible-tmp-1424313543.05-272404152788372/ec2", line 1203, in main
(tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2)
File "/home/tilgovi/.ansible/tmp/ansible-tmp-1424313543.05-272404152788372/ec2", line 682, in enforce_count
= create_instances(module, ec2, override_count=to_create)
File "/home/tilgovi/.ansible/tmp/ansible-tmp-1424313543.05-272404152788372/ec2", line 817, in create_instances
params['tenancy'] = tenancy
NameError: global name 'tenancy' is not defined
```

Downgrading to 1.8.2 fixed it.

**Comment by abadger** [comment]
Hi, this regression is being tracked on https://github.com/ansible/ansible-modules-core/issues/808  We are anticipating releasing a 1.8.4 with the fix for this.

**Comment by tilgovi** [comment]
Thanks! Sorry for the noise. Just getting oriented with the project layout.
