### ISSUE TITLE
devel fails with SyntaxError

### ISSUE THREAD

**Issue by anarcat** [ansible/ansible#10301]
i get this running the latest code from git here:

```
# ansible-playbook tests/test.yml -i tests/inventory
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 5, in <module>
    pkg_resources.run_script('ansible==1.8.4', 'ansible-playbook')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 326, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 266, in main
    pb.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/playbook/__init__.py", line 313, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/playbook/play.py", line 165, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/playbook/play.py", line 641, in _load_tasks
    loaded = self._load_tasks(data, mv, role_params, default_vars, included_sudo_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/playbook/play.py", line 653, in _load_tasks
    role_name=role_name
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/playbook/task.py", line 233, in __init__
    self.async_seconds = template.template_from_string(play.basedir, self.async_seconds, all_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/utils/template.py", line 329, in template_from_string
    environment.filters.update(_get_filters())
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/utils/template.py", line 52, in _get_filters
    plugins = [ x for x in utils.plugins.filter_loader.all()]
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/utils/plugins.py", line 219, in all
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.8.4-py2.7.egg/ansible/runner/filter_plugins/mathstuff.py", line 21
    from __future__ import absolute_import
SyntaxError: from __future__ imports must occur at the beginning of the file
```

i suspect this may be related to #10285, in commit c2023f6 specifically.

**Comment by bcoca** [comment]
quick fix https://github.com/ansible/ansible/commit/c587bf14884af086fbf774cbe122ba06aafbb2de  for the quick fix is in place, this should work now
