### ISSUE TITLE
Install ansible-tower error

### ISSUE THREAD

**Issue by modoojunko** [ansible/ansible#10366]
Sorry to put ansible-tower issue here ,I can not find where I can get support.

maybe you can CC this to the "tower" :)
## Install error

``` python
TASK: [packages_ubuntu | install apt repositories] **************************** 
failed: [127.0.0.1] => (item=ppa:debugmonkeys/sosreport) => {"failed": true, "item": "ppa:debugmonkeys/sosreport"}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
failed: [127.0.0.1] => (item=ppa:chris-lea/redis-server) => {"failed": true, "item": "ppa:chris-lea/redis-server"}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
failed: [127.0.0.1] => (item=ppa:chris-lea/zeromq) => {"failed": true, "item": "ppa:chris-lea/zeromq"}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
failed: [127.0.0.1] => (item=ppa:ansible/ansible) => {"failed": true, "item": "ppa:ansible/ansible"}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
```
## My testing

```
# apt-add-repository ppa:debugmonkeys/sosreport
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 128, in <module>
    ppa_info = get_ppa_info_from_lp(user, ppa_name)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 84, in get_ppa_info_from_lp
    curl.perform()
pycurl.error: (60, 'server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none')
```
## I tied

`apt-get --reinstall ca-certificates`
`update-ca-certificates`

and so many "solutions" I have tried. But no one can work .It makes me very sad.

so, please help. I use one proxy server which is deploy in US

**Comment by tgerla** [comment]
Hi, can you please send this message to support@ansible.com? They'll be able to help you there. Thanks!
