### ISSUE TITLE
#10295 may have broken `ansible-doc -l`

### ISSUE THREAD

**Issue by L2G** [ansible/ansible#10382]
I have the devel branch checked out and was having bum luck running `ansible-doc -l`, getting lots and lots of errors like this:

```
ValueError: too many values to unpack
ERROR: module a10_service_group has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/larrygilbert/work/ansible/bin/ansible-doc", line 200, in get_module_list_text
    doc, plainexamples = module_docs.get_docstring(filename)
ValueError: too many values to unpack
ERROR: module a10_virtual_server has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/larrygilbert/work/ansible/bin/ansible-doc", line 200, in get_module_list_text
    doc, plainexamples = module_docs.get_docstring(filename)
ValueError: too many values to unpack
ERROR: module acl has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/larrygilbert/work/ansible/bin/ansible-doc", line 200, in get_module_list_text
    doc, plainexamples = module_docs.get_docstring(filename)
```

I'm still rookie level with Python, so I tried to zero in on the bug with `git bisect`. Bingo. I found that reverting the changes in #10295 made `ansible-doc -l` worked as I expected.

**Comment by bcoca** [comment]
fixed through 4805fa6b0b2f77d10ad886a861fddaca84795c3d
