### ISSUE TITLE
No JSON object could be decoded when not exporting AWS credentials and using ec2 inventory script

### ISSUE THREAD

**Issue by oryband** [ansible/ansible#10422]
executing `ansible-playbook` with [ec2 inventory](https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.py) and forgetting to export credentials throws a very confusing and non-verbose Python exception. This happened to me various times, and each time I wasted 30 minutes in tracking down the source of the problem:

``` sh
# this throws an unexplainable error
$ ansible-playbook parameters...
Traceback (most recent call last):
  File "/home/ory/.virtualenvs/ubik/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ory/.virtualenvs/ubik/bin/ansible-playbook", line 160, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/home/ory/.virtualenvs/ubik/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 100, in __init__
    self.parser = InventoryDirectory(filename=host_list)
  File "/home/ory/.virtualenvs/ubik/local/lib/python2.7/site-packages/ansible/inventory/dir.py", line 56, in __init__
    parser = InventoryScript(filename=fullpath)
  File "/home/ory/.virtualenvs/ubik/local/lib/python2.7/site-packages/ansible/inventory/script.py", line 49, in __init__
    self.groups = self._parse(stderr)
  File "/home/ory/.virtualenvs/ubik/local/lib/python2.7/site-packages/ansible/inventory/script.py", line 57, in _parse
    self.raw  = utils.parse_json(self.data)
  File "/home/ory/.virtualenvs/ubik/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 551, in parse_json
    results = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

# this works
$ export AWS_ACCESS_KEY_ID=...
$ export AWS_SECRET_ACCESS_KEY=...
$ ansible-playbook parameters
```

`ansible-playbook` should return a reasonable error with a suitable explanation, and not an exception.

**Comment by abadger** [comment]
Thanks to @sgargan, #10467 has been merged.  We should be returning a reasonable error message now.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
