### ISSUE TITLE
Stack trace with 1.9 rc using Vagrant's ansible integration

### ISSUE THREAD

**Issue by hfinucane** [ansible/ansible#10434]
Ansible version: 

```
ansible 1.9.0 (detached HEAD bce4bb2ce2) last updated 2015/03/11 09:38:29 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 0206cc8133) last updated 2015/03/11 09:38:37 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 4c0b7cb55a) last updated 2015/03/11 09:38:39 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/11 09:38:40 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/03/11 09:38:42 (GMT -700)
  configured module search path = None
```

Stack trace:

```
fatal: [shared-testbox] => Traceback (most recent call last):
  File "/home/xxx/src/ansible/lib/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/xxx/src/ansible/lib/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/xxx/src/ansible/lib/ansible/runner/__init__.py", line 1026, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/xxx/src/ansible/lib/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/home/xxx/src/ansible/lib/ansible/runner/__init__.py", line 547, in _execute_module
    res = self._low_level_exec_command(conn, cmd, tmp, become=self.become, sudoable=sudoable, in_data=in_data)
  File "/home/xxx/src/ansible/lib/ansible/runner/__init__.py", line 1163, in _low_level_exec_command
    in_data=in_data)
  File "/home/xxx/src/ansible/lib/ansible/runner/connection_plugins/ssh.py", line 362, in exec_command
    (returncode, stdout, stderr) = self._communicate(p, stdin, in_data, sudoable=sudoable, prompt=prompt)
  File "/home/xxx/src/ansible/lib/ansible/runner/connection_plugins/ssh.py", line 176, in _communicate
    elif stdout.endswith("%s\r\n%s" % (incorrect_password, prompt)):
UnboundLocalError: local variable 'incorrect_password' referenced before assignment
```

**Comment by bcoca** [comment]
~~can you share how to trigger the stacktrace?~~
nvmd, found way, using sudo w/o passing a password when one is required

**Comment by MrMMorris** [comment]
Just ran into this as well. @bcoca for the latest branch changes, do I just update the branch? or do I have to run source ./hacking/env-setup again?

**Comment by hfinucane** [comment]
thanks, I can confirm it fixes the issue.

**Comment by abadger** [comment]
@MrMMorris You should be able to just update the branch.  sourcing hacking.env-setup sets PATH and PYTHONPATH environment variables that point into the checked out tree.  As long as the code in the checked out tree is what gets modified by updating the branch then you should be testing that code.
