### ISSUE TITLE
Ansible just hangs

### ISSUE THREAD

**Issue by pashinin** [ansible/ansible#10463]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.4
  configured module search path = /usr/share/ansible
##### Environment:

Ubuntu 14.10 (desktop), Ubuntu 14.04 (server)
##### Summary:

Ansible just hangs either running playbook or just gathering facts.
##### Steps To Reproduce:

Don't know what settings caused this or how to debug this problem. Some time ago it was ok.
##### Expected Results:

Does NOT hang
##### Actual Results:

It just hangs on this:

```
$ ansible -m setup 10.254.239.1 -vvvv
<10.254.239.1> 
<10.254.239.1> 
<10.254.239.1> ConnectTimeout=10 PasswordAuthentication=no KbdInteractiveAuthentication=no ControlPath=/home/xdev/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
<10.254.239.1> 
<10.254.239.1> ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1426313037.93-97762498648844/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1426313037.93-97762498648844/ >/dev/null 2>&1' KbdInteractiveAuthentication=no ControlPath=/home/xdev/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
^CTraceback (most recent call last):
  File "/usr/local/bin/ansible", line 194, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/local/bin/ansible", line 168, in run
    results = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1492, in run
    results = [ self._executor(h, None) for h in hosts ]
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1027, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 555, in _execute_module
    res = self._low_level_exec_command(conn, cmd, tmp, sudoable=sudoable, in_data=in_data)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1175, in _low_level_exec_command
    in_data=in_data)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/connection_plugins/ssh.py", line 361, in exec_command
    (returncode, stdout, stderr) = self._communicate(p, stdin, in_data, su=su, sudoable=sudoable, prompt=prompt)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/connection_plugins/ssh.py", line 158, in _communicate
    rfd, wfd, efd = select.select(rpipes, [], rpipes, 1)
KeyboardInterrupt
```

In server auth.log:

```
Mar 14 09:04:00 server sshd[1686]: pam_unix(sshd:session): session opened for user root by (uid=0)
Mar 14 09:04:00 server systemd-logind[874]: New session 12 of user root.
Mar 14 09:04:02 server sshd[1642]: Received disconnect from 10.254.239.11: 11: disconnected by user
Mar 14 09:04:02 server sshd[1642]: pam_unix(sshd:session): session closed for user root
```

**Comment by pashinin** [comment]
Similar: https://github.com/ansible/ansible/issues/10125

**Comment by pashinin** [comment]
Updated server (systemd-logind). It looks it was the problem.
