### ISSUE TITLE
Incorrect syntax for role include causes python stacktrace

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible#10497]
Following the ansible documentation for [role include](http://docs.ansible.com/playbooks_roles.html), I made a mistake in my syntax location of the `{` and it caused a python stacktrace instead of emitting an error message:

```
$ cat site.yml

---
- hosts: testserver
  user: root
  roles:
    - role: { yum_repo, repo_tag: "myrepo", repo_baseurl: "http://example.com/myrepo/x86_64/", repo_name: "custom test repo", repo_enabled: "1", repo_gpg_check: "1" }

$ ansible-playbook site.yml -i inventory.txt 
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 326, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 266, in main
    pb.run()
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 313, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 100, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 414, in _load_roles
    roles = self._build_role_dependencies(roles, [], {})
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 225, in _build_role_dependencies
    role_path,role_vars = self._get_role_path(role)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 200, in _get_role_path
    utils.path_dwim(self.basedir, os.path.join('roles', role_name)),
  File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
