### ISSUE TITLE
ansible_distribution_release returns NA on raspberry pi 2

### ISSUE THREAD

**Issue by joshuacox** [ansible/ansible#10505]
The apt sources are default out of the box NOOBS, just opened the box today, was running some playbooks on it and noticed this.  specifically it was with icinga2

```
failed: [icinga_one] => (item={'repo': u'deb http://packages.icinga.org/debian icinga-NA main'}) => {"failed": true, "item": {"repo": "deb http://packages.icinga.org/debian icinga-NA main"}, "parsed": false}
SUDO-SUCCESS-bptxjnnaojjfseqsgpqnkuwqtxwvcmno
Traceback (most recent call last):
  File "/home/pi/.ansible/tmp/ansible-tmp-1426812117.23-247808562272624/apt_repository", line 2495, in <module>
    main()
  File "/home/pi/.ansible/tmp/ansible-tmp-1426812117.23-247808562272624/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://packages.icinga.org/debian/dists/icinga-NA/main/binary-armhf/Packages  404  Not Found
, E:Some index files failed to download. They have been ignored, or old ones used instead.

failed: [icinga_one] => (item={'repo': u'deb-src http://packages.icinga.org/debian icinga-NA main'}) => {"failed": true, "item": {"repo": "deb-src http://packages.icinga.org/debian icinga-NA main"}, "parsed": fals
e}
SUDO-SUCCESS-vzwoiewopjuvbnqngnkuabbtdwowrrds
Traceback (most recent call last):
  File "/home/pi/.ansible/tmp/ansible-tmp-1426812149.47-188663706753499/apt_repository", line 2495, in <module>
    main()
  File "/home/pi/.ansible/tmp/ansible-tmp-1426812149.47-188663706753499/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://packages.icinga.org/debian/dists/icinga-NA/main/source/Sources  404  Not Found
, W:Failed to fetch http://packages.icinga.org/debian/dists/icinga-NA/main/binary-armhf/Packages  404  Not Found
, E:Some index files failed to download. They have been ignored, or old ones used instead.


FATAL: all hosts have already failed -- aborting
```

**Comment by egon0** [comment]
Same problem on Raspberry Pi 1 (plus and not plus) with plain current jessie based raspbian.

**Comment by robinro** [comment]
Part of the problem is what NOOBS is doing with generating this code. Another part is in ansible not getting the version right.

Could you please run this script
https://github.com/robinro/ansible/blob/refactor_os_version_parsing/test/units/module_utils/gen_distribution_version_testcase.py ?
It collects all the inputs that ansible uses to generate the version info and outputs it in a format I currently use to setup test cases.
I will then try to fix the version code to give the right result.

**Comment by jctanner** [comment]
The traceback in the body of this issue implies an http failure rather than anything obviously related to setup.py. Without any further detail or response from the reporter, we aren't going to be able to resolve this issue.
