### ISSUE TITLE
Display better error message on role dependency yaml syntax error

### ISSUE THREAD

**Issue by sidewinder12s** [ansible/ansible#10525]
Issue Type: Bug Report

Ansible Version: ansible 1.8.4

Environment: N/A

Summary: Improve yaml syntax error handling when using role/meta/main.yml for dependencies in a role

Right now if you have a yaml syntax error, specifically specifying a list instead of a dictionary for role dependencies it will throw a python traceback that is not immediately clear. 

Steps To Reproduce: Place this in your role/meta/main.yml

```

---
 - dependencies:
   - { role: 'roles/krb5' }
```

Expected Results: Ansible should throw an ansible yaml error for incorrect syntax in the playbook

Actual Results: Python traceback

```
==> rundeck: Running provisioner: ansible...

PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/sidewinder12s/Documents/vagrant/rundeck/.vagrant/machines/rundeck/virtualbox/private_key --user=vagrant --connection=ssh --limit='rundeck' --inventory-file=/Users/sidewinder12s/Documents/vagrant/rundeck/.vagrant/provisioners/ansible/inventory --sudo /Users/sidewinder12s/Documents/its-lab-services-ansible/linux-configuration/rundeck_test.yml

Traceback (most recent call last):

  File "/usr/local/Cellar/ansible/1.8.4_1/libexec/bin/ansible-playbook", line 326, in <module>

    sys.exit(main(sys.argv[1:]))

  File "/usr/local/Cellar/ansible/1.8.4_1/libexec/bin/ansible-playbook", line 266, in main

    pb.run()

  File "/usr/local/Cellar/ansible/1.8.4_1/libexec/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 313, in run

    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)

  File "/usr/local/Cellar/ansible/1.8.4_1/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 100, in __init__

    ds = self._load_roles(self.roles, ds)

  File "/usr/local/Cellar/ansible/1.8.4_1/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 414, in _load_roles

    roles = self._build_role_dependencies(roles, [], {})

  File "/usr/local/Cellar/ansible/1.8.4_1/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 256, in _build_role_dependencies

    dependencies = data.get('dependencies',[])

AttributeError: 'list' object has no attribute 'get'

Ansible failed to complete successfully. Any error output should be

visible above. Please fix these errors and try again.
```

**Comment by sudohippie** [comment]
:+1: 

One of my `role/meta/main.yml` had the following config leading to the above mentioned stack trace: 

```
---
- dependencies: []
```

Removing it, solved the issue. A descriptive error would be very helpful.

**Comment by bcoca** [comment]
this  is fixed in current devel and does not throw a exception anymore, you get the following error now:

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/home/bcoca/work/envs/roles/briancoca.oracle_java7/meta/main.yml': line 20, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - web
- dependencies: []
^ here
```

**Comment by sudohippie** [comment]
Thanks @bcoca
