### ISSUE TITLE
ansible 1.9.1 from homebrew on os 10.10.3 -- winrm kerberos error ...

### ISSUE THREAD

**Issue by breathe** [ansible/ansible#10740]
Attempting to connect to host using winrm (without kerberos) -- fails with kerberos related error with ansible 1.9.1 as distributed by homebrew ...

```
 ~/s/a/sts-infrastructure (master) > ansible-playbook --version
ansible-playbook 1.9.0.1
  configured module search path = None

 ~/s/a/sts-infrastructure (master) > ansible-playbook -vvvv deploy-site-windows.yml -i hosts-mf.ini
<sts-m93p-automaton.domain.com> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO sts-m93p-automaton.domain.com
<sts-m93p-automaton.domain.com> WINRM CONNECT: transport=kerberos endpoint=https://sts-m93p-automaton.domain.com:5986/wsman
fatal: [sts-m93p-automaton.domain.com] => Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 960, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/lib/python2.7/site-packages/ansible/runner/connection.py", line 52, in connect
    self.active = conn.connect()
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 147, in connect
    self.protocol = self._winrm_connect()
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 101, in _winrm_connect
    protocol.send_message('')
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/vendor/lib/python2.7/site-packages/winrm/protocol.py", line 173, in send_message
    return self.transport.send_message(message)
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/vendor/lib/python2.7/site-packages/winrm/transport.py", line 202, in send_message
    krb_ticket = KerberosTicket(self.krb_service)
  File "/usr/local/Cellar/ansible/1.9.0.1/libexec/vendor/lib/python2.7/site-packages/winrm/transport.py", line 153, in __init__
    kerberos.authGSSClientStep(krb_context, '')
GSSError: ((' Miscellaneous failure (see text)', 851968), ('No credentials cache file found', -1765328189))
```

Have connection related variables defined for members of windows-hosts group:

```
ansible_ssh_user: ansible
ansible_ssh_pass: "sometestpassword"
ansible_ssh_port: 5986
ansible_connection: winrm
```

and playbook looks like:

```
- hosts: windows-hosts
  remote_user: ansible
  tasks:
    - name: Test the ansible connection via win_ping
      action: win_ping
```

ansible is a local user on the windows host and a member of local system administrator group.

It was working before -- and still works using 1.9.0rc1 ...

```
bash-3.2$ ansible-playbook --version
ansible-playbook 1.9.0 (detached HEAD bce4bb2ce2) last updated 2015/03/17 15:12:54 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 0206cc8133) last updated 2015/03/17 15:14:54 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 4c0b7cb55a) last updated 2015/03/17 15:14:58 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/17 15:15:01 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/03/17 15:15:06 (GMT -700)
  configured module search path = None
bash-3.2$ ansible-playbook -vvvv deploy-site-windows.yml -i hosts-mf.ini 

PLAY [windows-hosts] ********************************************************** 

GATHERING FACTS *************************************************************** 
<sts-m93p-automaton.ucsd.edu> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO sts-m93p-automaton.ucsd.edu
<sts-m93p-automaton.ucsd.edu> WINRM CONNECT: transport=plaintext endpoint=https://sts-m93p-automaton.ucsd.edu:5986/wsman
<sts-m93p-automaton.ucsd.edu> REMOTE_MODULE setup
<sts-m93p-automaton.ucsd.edu> EXEC (New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1429140877.17-273271416439779").FullName | Write-Host -Separator '';
<sts-m93p-automaton.ucsd.edu> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'KABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAZQBuAHYAOgB0AGUAbQBwACAALQBOAGEAbQBlACAAIgBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQAMgA5ADEANAAwADgANwA3AC4AMQA3AC0AMgA3ADMAMgA3ADEANAAxADYANAAzADkANwA3ADkAIgApAC4ARgB1AGwAbABOAGEAbQBlACAAfAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAFMAZQBwAGEAcgBhAHQAbwByACAAJwAnADsA']
<sts-m93p-automaton.ucsd.edu> WINRM RESULT <Response code 0, out "C:\Users\ansible\App", err "">
<sts-m93p-automaton.ucsd.edu> PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpDGpwuZ TO C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpDGpwuZ to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup.ps1 (offset=0 size=2037)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpDGpwuZ to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup.ps1 (offset=2037 size=2037)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpDGpwuZ to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup.ps1 (offset=4074 size=2037)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpDGpwuZ to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup.ps1 (offset=6111 size=2037)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpDGpwuZ to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup.ps1 (offset=8148 size=1098)
<sts-m93p-automaton.ucsd.edu> PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpN8sVKX TO C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\arguments
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpN8sVKX to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\arguments (offset=0 size=2)
<sts-m93p-automaton.ucsd.edu> EXEC & C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\setup.ps1 C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\\arguments; Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140877.17-273271416439779\" -Force -Recurse;
<sts-m93p-automaton.ucsd.edu> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'JgAgAEMAOgBcAFUAcwBlAHIAcwBcAGEAbgBzAGkAYgBsAGUAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAAyADkAMQA0ADAAOAA3ADcALgAxADcALQAyADcAMwAyADcAMQA0ADEANgA0ADMAOQA3ADcAOQBcAFwAcwBlAHQAdQBwAC4AcABzADEAIABDADoAXABVAHMAZQByAHMAXABhAG4AcwBpAGIAbABlAFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXABhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQAMgA5ADEANAAwADgANwA3AC4AMQA3AC0AMgA3ADMAMgA3ADEANAAxADYANAAzADkANwA3ADkAXABcAGEAcgBnAHUAbQBlAG4AdABzADsAIABSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAiAEMAOgBcAFUAcwBlAHIAcwBcAGEAbgBzAGkAYgBsAGUAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAAyADkAMQA0ADAAOAA3ADcALgAxADcALQAyADcAMwAyADcAMQA0ADEANgA0ADMAOQA3ADcAOQBcACIAIAAtAEYAbwByAGMAZQAgAC0AUgBlAGMAdQByAHMAZQA7AA==']
<sts-m93p-automaton.ucsd.edu> WINRM RESULT <Response code 0, out "{ "changed": f", err "">
ok: [sts-m93p-automaton.ucsd.edu] => {"ansible_facts": {"ansible_distribution": "Microsoft Windows NT 6.4.9841.0", "ansible_distribution_version": "6.4.9841.0", "ansible_fqdn": "WIN-CDAE5DNO8IG", "ansible_hostname": "WIN-CDAE5DNO8IG", "ansible_interfaces": [{"default_gateway": "137.110.151.1", "dns_domain": "ucsd.edu", "interface_index": 3, "interface_name": "Intel(R) Ethernet Connection I217-LM"}], "ansible_ip_addresses": ["137.110.151.14", "fe80::20c4:5d55:7a36:4ea6"], "ansible_os_family": "Windows", "ansible_powershell_version": 5, "ansible_system": "Win32NT", "ansible_totalmem": 17179869184, "ansible_winrm_certificate_expires": "2016-04-15 16:22:23"}, "changed": false}

TASK: [Test the ansible connection via win_ping] ****************************** 
<sts-m93p-automaton.ucsd.edu> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO sts-m93p-automaton.ucsd.edu
<sts-m93p-automaton.ucsd.edu> WINRM REUSE EXISTING CONNECTION: ansible:********@sts-m93p-automaton.ucsd.edu:5986
<sts-m93p-automaton.ucsd.edu> REMOTE_MODULE win_ping
<sts-m93p-automaton.ucsd.edu> EXEC (New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1429140880.66-72091997727838").FullName | Write-Host -Separator '';
<sts-m93p-automaton.ucsd.edu> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'KABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAZQBuAHYAOgB0AGUAbQBwACAALQBOAGEAbQBlACAAIgBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQAMgA5ADEANAAwADgAOAAwAC4ANgA2AC0ANwAyADAAOQAxADkAOQA3ADcAMgA3ADgAMwA4ACIAKQAuAEYAdQBsAGwATgBhAG0AZQAgAHwAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAALQBTAGUAcABhAHIAYQB0AG8AcgAgACcAJwA7AA==']
<sts-m93p-automaton.ucsd.edu> WINRM RESULT <Response code 0, out "C:\Users\ansible\App", err "">
<sts-m93p-automaton.ucsd.edu> PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpIgKE5Q TO C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\win_ping
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpIgKE5Q to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\win_ping.ps1 (offset=0 size=2036)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpIgKE5Q to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\win_ping.ps1 (offset=2036 size=2036)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpIgKE5Q to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\win_ping.ps1 (offset=4072 size=2036)
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpIgKE5Q to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\win_ping.ps1 (offset=6108 size=425)
<sts-m93p-automaton.ucsd.edu> PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpvutKUQ TO C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\arguments
<sts-m93p-automaton.ucsd.edu> WINRM PUT /var/folders/nt/2rw6w19x6kx1hhd9h2xntp1c0000gn/T/tmpvutKUQ to C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\arguments (offset=0 size=2)
<sts-m93p-automaton.ucsd.edu> EXEC & C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\win_ping.ps1 C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\\arguments; Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1429140880.66-72091997727838\" -Force -Recurse;
<sts-m93p-automaton.ucsd.edu> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'JgAgAEMAOgBcAFUAcwBlAHIAcwBcAGEAbgBzAGkAYgBsAGUAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAAyADkAMQA0ADAAOAA4ADAALgA2ADYALQA3ADIAMAA5ADEAOQA5ADcANwAyADcAOAAzADgAXABcAHcAaQBuAF8AcABpAG4AZwAuAHAAcwAxACAAQwA6AFwAVQBzAGUAcgBzAFwAYQBuAHMAaQBiAGwAZQBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADIAOQAxADQAMAA4ADgAMAAuADYANgAtADcAMgAwADkAMQA5ADkANwA3ADIANwA4ADMAOABcAFwAYQByAGcAdQBtAGUAbgB0AHMAOwAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACIAQwA6AFwAVQBzAGUAcgBzAFwAYQBuAHMAaQBiAGwAZQBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADIAOQAxADQAMAA4ADgAMAAuADYANgAtADcAMgAwADkAMQA5ADkANwA3ADIANwA4ADMAOABcACIAIAAtAEYAbwByAGMAZQAgAC0AUgBlAGMAdQByAHMAZQA7AA==']
<sts-m93p-automaton.ucsd.edu> WINRM RESULT <Response code 0, out "{ "changed": f", err "">
ok: [sts-m93p-automaton.ucsd.edu] => {"changed": false, "ping": "pong"}

PLAY RECAP ******************************************************************** 
sts-m93p-automaton.ucsd.edu : ok=2    changed=0    unreachable=0    failed=0   
```

Is this an issue with ansible or the homebrew package?  It looks me like there might be a problem with the way that ansible is failing over to plaintext auth after a kerberos auth attempt fails ...

**Comment by cchurch** [comment]
I've fixed this issue on devel via #10664, has not (yet?) been cherry-picked back to 1.9.

**Comment by bcomnes** [comment]
Ran into this tonight.  I'm fairly unfamiliar with windows remote execution.  Any workarounds documented anywhere?

**Comment by bcomnes** [comment]
I locally [patched](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#patches) the ansible formula with https://patch-diff.githubusercontent.com/raw/ansible/ansible/pull/10664.patch which seemed to make things work again.

**Comment by breathe** [comment]
Anybody know if a fix for this made it into the 1.9.1 release just announced today?  Release notes from that release:
- Fixed a bug related to Kerberos auth when using winrm with a domain account.

Which doesn't sound like this bug but maybe an overlapping fix ...?

**Comment by ssbarnea** [comment]
I am facing the same problem here and I am wondering if it is possible to connect to windows hosts using  domain account from a non windows host (like OS X in our case). Connecting to the same machine works with non-domain accounts.

```
nibbler:ansible sorins$ ansible -vvv winadmin.do.example.com -m win_ping
<winadmin.do.example.com> ESTABLISH WINRM CONNECTION FOR USER:  on PORT 5985 TO winadmin.do.example.com
winadmin.do.example.com | FAILED => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 968, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/connection.py", line 52, in connect
    self.active = conn.connect()
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 140, in connect
    self.protocol = self._winrm_connect()
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 96, in _winrm_connect
    protocol.send_message('')
  File "/usr/local/lib/python2.7/site-packages/winrm/protocol.py", line 193, in send_message
    return self.transport.send_message(message)
  File "/usr/local/lib/python2.7/site-packages/winrm/transport.py", line 269, in send_message
    krb_ticket = KerberosTicket(self.krb_service)
  File "/usr/local/lib/python2.7/site-packages/winrm/transport.py", line 205, in __init__
    kerberos.authGSSClientStep(krb_context, '')
GSSError: ((' Miscellaneous failure (see text)', 851968), ('No credentials cache file found', -1765328189))

nibbler:ansible sorins$ ansible -vvv winadmin.do.example.com -m win_ping
<winadmin.do.example.com> ESTABLISH WINRM CONNECTION FOR USER: svcacct_scale on PORT 5985 TO winadmin.do.example.com
winadmin.do.example.com | FAILED => 500 WinRMTransport. [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
```

When I specify the user using the domain notation it seems that it fails to pick the username correction. Do you observe that the username is missing at the first example, that was the one where I used `svcacct_scale@example` or `svcacct_scale@example.com` as the documentation is not clear if you are supposed to use the FQDN domain name or only she short form. Tried both, same result.

**Comment by ssbarnea** [comment]
BTW, the problems seems not to specific to ansible version as I do have latest release 1.9.4 and my OS X version is 10.11.1

**Comment by rasebo** [comment]
Same here, the only difference being that I have OS X 10.11.2.

**Comment by jctanner** [comment]
Per @cchurch, this should have been resolved by https://github.com/ansible/ansible/pull/10664
