### ISSUE TITLE
setup module fails if PATH is not set on target host

### ISSUE THREAD

**Issue by SleeplessAnnoyedNerd** [ansible/ansible#1075]
Hi,

sure, it's rather odd that environment variable PATH is not set, but such things can happen. :)

$ ansible --version
ansible 0.8 (devel b8c4bb9e6e) last updated 2012/09/22 16:27:29 (GMT +200)

$ ansible ahost -m setup
vz117 | FAILED => failed to parse: some garbage output

Traceback (most recent call last):
  File "/var/tmp/ansible-1348324167.94-77734321202780/setup", line 1145, in ?
    main()
  File "/var/tmp/ansible-1348324167.94-77734321202780/setup", line 845, in main
    data = run_setup(module)
  File "/var/tmp/ansible-1348324167.94-77734321202780/setup", line 792, in run_setup
    facts = ansible_facts()
  File "/var/tmp/ansible-1348324167.94-77734321202780/setup", line 783, in ansible_facts
    facts.update(Network().populate())
  File "/var/tmp/ansible-1348324167.94-77734321202780/setup", line 494, in populate
    ip_path = module.get_bin_path('ip')
  File "/var/tmp/ansible-1348324167.94-77734321202780/setup", line 1070, in get_bin_path
    paths += os.environ.get('PATH').split(':')
AttributeError: 'NoneType' object has no attribute 'split'

The fix is rather easy it seems:

diff --git a/lib/ansible/module_common.py b/lib/ansible/module_common.py
index e95dd0d..32bba60 100644
--- a/lib/ansible/module_common.py
+++ b/lib/ansible/module_common.py
@@ -239,7 +239,7 @@ class AnsibleModule(object):
         for d in opt_dirs:
             if d is not None and os.path.exists(d):
                 paths.append(d)
-        paths += os.environ.get('PATH').split(':')
-        paths += os.environ.get('PATH', '').split(':')
       bin_path = None
       # mangle PATH to include /sbin dirs
       for p in sbin_paths:

At least now it works for me for this odd host. (Using ssh for ssh connection; Debian 4.0; Dropbear 0.48.)

-- Dietmar.

**Comment by SleeplessAnnoyedNerd** [comment]
Superseded by Issue #1076

**Comment by mpdehaan** [comment]
Ok thx, will review in the next few days.

-- Michael
