### ISSUE TITLE
ec2_group fails if security group already exists

### ISSUE THREAD

**Issue by bubylou** [ansible/ansible#10753]
#### Issue Type

Bug Report
#### Version

ansible 1.7.2, ansible 1.9.0.1 , and ansible 2.0.0
#### Environment

From: Debian Jessie 64bit
To: Ubuntu 14.04 AMI 64bit
#### Summary

I was trying to run a playbook that include a task that sets up a ec2 security group but it fails if the security group already exists. If it does not exist then the task completes but once you run it again, since the security group now exists, it will fail.
#### Steps to Reproduce

Run a playbook with the following task when the security group already exists.

```
- name: Set security group
      ec2_group:
        name: ssm
        description: ssm
        region: us-east-1
        rules:
        - proto: tcp 
          from_port: 22
          to_port: 22
          cidr_ip: 65.25.38.40/0
        - proto: udp
          from_port: 27015
          to_port: 27015
          cidr_ip: 0.0.0.0/0
        rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
```
#### Expected Results

If the security group already exists and has the same rules as the task then the task should complete with no changes.
#### Actual Results

```
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/buby/.ansible/tmp/ansible-tmp-1429217851.07-152169898899354/ec2_group", line 2187, in <module>
    main()
  File "/home/buby/.ansible/tmp/ansible-tmp-1429217851.07-152169898899354/ec2_group", line 302, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 3191, in authorize_security_group
    params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 0.0.0.0/0, TCP, from port: 22, to port: 22, ALLOW" already exists</Message></Error></Errors><RequestID>7203445c-b509-4425-a6fa-7a65bac1408b</RequestID></Response>


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/buby/launch.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by unixunion** [comment]
I found the same thing, but if you lock down the cidr a little and specify from_port and to_port, it works as advertized.

im not sure why you had: 65.25.38.40/0 since thats a bit conflictive in subnet masking. 

```
- name: Set security group
  connection: local
  hosts: 127.0.0.1
  tasks:
  - local_action:
      module: ec2_group
      name: ssm
      description: ssm
      region: eu-central-1
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 65.25.38.40/32
        - proto: udp
          from_port: 27015
          to_port: 27015
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          from_port: all
          to_port: all
          cidr_ip: 0.0.0.0/0
```

/K

**Comment by bubylou** [comment]
Adding the from and to ports worked for me as well. Thank you for the fix and for catching my subnet mask.

**Comment by rainmanh** [comment]
Hi

I am having identical problem with the following:
``````
ec2_security_groups_test:
    - sg_name: test-grup
      sg_description: test-group
      vpc_id: "vpc-XXXXXX"
      region: "{{ region }}"
      sg_rules:
       - proto: 50
         from_port: -1
         to_port: -1
         cidr_ip: 12.12.12.12/32
       - proto: 50
         from_port: -1
         to_port: -1
         cidr_ip: 13.13.13.13/32
       - proto: 50
         from_port: -1
         to_port: -1
         group_name: test-group

````````
it will work on the 1st run, but on the second I will have:
``````
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 12.12.12.12/32, protocol: 50, ALLOW" already exists</Message></Error></Errors><RequestID>e890595b-9609-4c31-a611-87da7b5de7ae</RequestID></Response>


```
I have tried specifying Ports, also "-1".. Nothing seems to work.
If I say TCP or UDP it works fine, but when I specify a numeric port as above I got the issue:

Any possible workaround?
