### ISSUE TITLE
Bug when installing pip package from github repo

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10766]
**Issue Type:**

Bug Report

**Ansible Version:**

```
ansible 2.0.0 (devel f4172fb9da) last updated 2015/04/17 19:17:00 (GMT -1000)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/17 19:17:35 (GMT -1000)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/17 19:17:58 (GMT -1000)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/17 19:18:21 (GMT -1000)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/17 19:18:42 (GMT -1000)
  configured module search path = None
```

**Environment:**

OSX 10.10.1

**Summary:**

Pip module does not play very nice when installing package from source repo

**Steps To Reproduce:**

```
- name: install latest ansible from master
  pip:
    name: 'git://github.com/ansible/ansible.git@devel#egg=ansible'
    state: latest
```

**Expected Results:**

The latest version of the pip package is installed

**Actual Results:**

``` yaml
TASK: [ install latest ansible from master] *************************
failed: [52.4.115.43] => {"cmd": "/usr/local/bin/pip install -U git://github.com/ansible/ansible.git@devel#egg=ansible", "failed": true}
Collecting ansible from git://github.com/ansible/ansible.git@devel#egg=ansible
  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 765, in unpack_url
      unpack_vcs_link(link, location, only_download)
    File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 468, in unpack_vcs_link
      vcs_backend.unpack(location)
    File "/usr/local/lib/python2.7/dist-packages/pip/vcs/__init__.py", line 282, in unpack
      self.obtain(location)
    File "/usr/local/lib/python2.7/dist-packages/pip/vcs/git.py", line 108, in obtain
      url, rev = self.get_url_rev()
    File "/usr/local/lib/python2.7/dist-packages/pip/vcs/git.py", line 203, in get_url_rev
      url, rev = super(Git, self).get_url_rev()
    File "/usr/local/lib/python2.7/dist-packages/pip/vcs/__init__.py", line 147, in get_url_rev
      assert '+' in self.url, error_message % self.url
  AssertionError: Sorry, 'git://github.com/ansible/ansible.git@devel#egg=ansible' is a malformed VCS url. The format is <vcs>+<protocol>://<url>, e.g. svn+http://myrepo/svn/MyApp#egg=MyApp
```

**Comment by MrMMorris** [comment]
**Workaround:**

``` yaml
- name: install latest ansible from master
  pip:
    name: '-e git://github.com/ansible/ansible.git@devel#egg=ansible'
    state: latest
```

**Comment by sivel** [comment]
The initial error message tells you what the problem is:

```
Sorry, 'git://github.com/ansible/ansible.git@devel#egg=ansible' is a malformed VCS url. The format is <vcs>+<protocol>://<url>, e.g. svn+http://myrepo/svn/MyApp#egg=MyApp
```

You provided pip with an invalid URL, by not telling it that the URL uses `git`

It should be `git+git://github.com/ansible/ansible.git@devel#egg=ansible`

Notice that the url is prepended with `git+` to tell pip that it should use git to download the repository.

**Comment by MrMMorris** [comment]
yep! apologies for my blindness!
