### ISSUE TITLE
Casting a variable to bool is not working as expected

### ISSUE THREAD

**Issue by metmajer** [ansible/ansible#10785]
Given the following playbook, I'd expect the casts {{ var | bool }} to return a boolean value (True | False). With 1.8.1 and 1.9.0.1 this is not the case:

**Playbook**

```

---
- hosts: all
  vars:
    do_it: false
  tasks:
    - set_fact: 
        envelope:
          do_it: "{{ do_it | bool }}"
    - debug: var=envelope

    - debug: msg="{{ "False" | bool }}"
```

**Output**

```
TASK: [debug var=envelope] **************************************************** 
ok: [localhost] => {
    "var": {
        "envelope": {
            "do_it": "False"
        }
    }
}

TASK: [debug msg="False"] ***************************************************** 
ok: [localhost] => {
    "msg": "False"
}
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

A short answer is that so this returns a boolean which is then quoted as a string, so do_it become a string do_it: "{{ do_it | bool }}" you might want to try:
do_it: !!bool "{{ do_it }}" 
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by metmajer** [comment]
Bocca,

thanks for pointing me to the alternative sources. Nevertheless, for the sake of completeness: how is !!bool supposed to help me in a playbook?

Thanks for clarifying! Martin

**Comment by bcoca** [comment]
it is a yamlism that casts variables, which is the current problem you are having, yaml is casting the var as a string due to the quotes.

**Comment by metmajer** [comment]
Thanks for the heads up. Still, I can't make your suggestion work:

**Playbook**

```
---
- hosts: all
  vars:
    do_it: false
  tasks:
    - set_fact: 
        envelope:
          do_it: !!bool "{{ do_it }}"
    - debug: var=envelope
```

**Output**

```
$ ansible-playbook test-playbook.yml 
SSH password: 
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 209, in main
    force_handlers=options.force_handlers,
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 180, in __init__
    (self.playbook, self.play_basedirs) = self._load_playbook_from_file(playbook, vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 257, in _load_playbook_from_file
    playbook_data = utils.parse_yaml_from_file(path, vault_password=self.vault_password)
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 778, in parse_yaml_from_file
    return parse_yaml(data, path_hint=path)
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 602, in parse_yaml
    loaded = yaml.load(data, Loader=Loader)
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 225, in construct_yaml_bool
    return self.bool_values[value.lower()]
KeyError: u'{{ do_it }}'
```

Seems like yaml catches it before {{ do_it }} gets replaced.

**Comment by raags** [comment]
@metmajer you can use the key=value form for set_fact to get around this :

```
set_fact: foo={{cli_foo|default(false|bool)}}
```

**Comment by metmajer** [comment]
Thanks @raags!
