### ISSUE TITLE
include_vars bug while using with_first_found

### ISSUE THREAD

**Issue by unixunion** [ansible/ansible#10858]
Hi,

I have a use-case where I am using ec2.py as `inventory`, and my roles call a config_loader.yml which trues to load a YAML matching app_name, then just environment name. And I get quite a crazy error when the contents of my variables are "simple" e.g. "http://foobar" works, but just "foobar" throws

```
(py27)bash-3.2$ ansible-playbook -i testing app.yml -e name=myenvironment -e version=1.0.0-1 -e app_name=app1 -vvv
Traceback (most recent call last):
  File "/Users/keghol/py27/bin/ansible-playbook", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/keghol/py27/bin/ansible-playbook", line 156, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 100, in __init__
    self.parser = InventoryDirectory(filename=host_list)
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/dir.py", line 54, in __init__
    parser = InventoryDirectory(filename=fullpath)
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/dir.py", line 58, in __init__
    parser = InventoryParser(filename=fullpath)
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/ini.py", line 43, in __init__
    self._parse()
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/ini.py", line 47, in _parse
    self._parse_base_groups()
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/ini.py", line 140, in _parse_base_groups
    host = Host(name=hn, port=port)
  File "/Users/keghol/py27/lib/python2.7/site-packages/ansible/inventory/host.py", line 32, in __init__
    self.set_variable('ansible_ssh_port', int(port))
ValueError: invalid literal for int() with base 10: 'fobar'
```

I have made a example of the bug here: https://github.com/unixunion/ansible_bug

My structure:

```
.
├── README.md
├── app.yml
├── roles
│   └── app1
│       └── tasks
│           └── main.yml
├── tasks
│   └── config_loader.yml
└── testing
    ├── inventory <-- ec2.py
    └── vars
        ├── app1.yml
        └── app2.yml
```

But it seems to stem from the contents of my variables.  Details for reproducing are in my repo.

/K

**Comment by jimi-c** [comment]
Testing this out on devel, and the main issue doesn't appear to exist anymore, however I have noted that we do not currently allow role names to be templated, so I'll keep this open for now.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

The above commit addresses the one remaining issue here of role names not being templated, so closing this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
