### ISSUE TITLE
Fact cache (jsonfile) exception

### ISSUE THREAD

**Issue by coryrwagner** [ansible/ansible#10883]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
ansible 1.9.1
  configured module search path = /usr/share/ansible
Same issue occurred with 1.9.0.1
##### Environment:

SLES 11 SP3
##### Summary:

I was running a playbook, I hit Ctrl-C to stop it and now I'm getting a "No JSON object could be decoded" error whenever I try to execute a playbook or module. The inventory appears to by OK, because I can list hosts. Any playbook that requires variable prompts for them before failing.
##### Steps To Reproduce:

Run any playbook or module, like "ansible localhost -m ping" or "ansible-playbook playbooks/common.yml"
##### Expected Results:

Any playbook I try to run fails with the message below.
##### Actual Results:

```
ansible localhost -m ping
localhost | FAILED => Traceback (most recent call last):
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/runner/__init__.py", line 664, in _executor_internal
    inject = self.get_inject_vars(host)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/runner/__init__.py", line 607, in get_inject_vars
    combined_cache = self.get_combined_cache()
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/runner/__init__.py", line 602, in get_combined_cache
    combined_cache = self.setup_cache.copy()
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/cache/__init__.py", line 54, in copy
    return dict([(k, v) for (k, v) in self.iteritems()])
  File "/usr/lib64/python2.6/_abcoll.py", line 357, in iteritems
    yield (key, self[key])
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/cache/__init__.py", line 35, in __getitem__
    return self._plugin.get(key)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.9.1-py2.6.egg/ansible/cache/jsonfile.py", line 65, in get
    value = json.load(f)
  File "/usr/lib64/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by coryrwagner** [comment]
I used strace to see what Ansible was doing and I noticed that it was loading the facts from cache right before throwing the error, so I removed all of the cache files and that resolved the issue. One of the cache files must have gotten corrupted and wasn't able to be parsed. (We are using fact caching by setting a path for fact_caching_connection in ansible.cfg.) An error message would certainly be more appropriate for this issue than this generic python error.

**Comment by bcoca** [comment]
this is still a bug, it should issue a warning and consider that fact as 'not in cache'

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
