### ISSUE TITLE
verbosity options broken

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#1088]
Regression seems to have been introduced in 04c535b1e99b45a5ea718ecb40c740f12b1fec35

Probably need to add 'ok_or_changed' to the format options

```
$ ansible-playbook -v ./test.yaml

PLAY [lnx] *********************

TASK: [command ls /] *********************
fatal: [redstonefoundries.com] => Traceback (most recent call last):
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 221, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 270, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 396, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/home/tbielawa/Projects/ansible/lib/ansible/callbacks.py", line 332, in on_ok
    msg = "%s: [%s] => %s" % (host, utils.jsonify(host_result2))
TypeError: not enough arguments for format string

fatal: [oldscri.be] => Traceback (most recent call last):
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 221, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 270, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 396, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/home/tbielawa/Projects/ansible/lib/ansible/callbacks.py", line 332, in on_ok
    msg = "%s: [%s] => %s" % (host, utils.jsonify(host_result2))
TypeError: not enough arguments for format string

fatal: [lnx.cx] => Traceback (most recent call last):
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 221, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 270, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/tbielawa/Projects/ansible/lib/ansible/runner/__init__.py", line 396, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/home/tbielawa/Projects/ansible/lib/ansible/callbacks.py", line 332, in on_ok
    msg = "%s: [%s] => %s" % (host, utils.jsonify(host_result2))
TypeError: not enough arguments for format string


TASK: [pause seconds=10] *********************
no hosts matched or remaining


TASK: [command ls /] *********************
no hosts matched or remaining


PLAY RECAP *********************
lnx.cx                         : ok=0    changed=0    unreachable=1    failed=0
oldscri.be                     : ok=0    changed=0    unreachable=1    failed=0
redstonefoundries.com          : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by mpdehaan** [comment]
fixed various things
