### ISSUE TITLE
Traceback in 'file' module

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#10933]
Issue Type: Bug Report

Ansible Version: 1.8.2

Environment: Mac OS X 10.10.1 "Yosemite"

Summary: YAML traceback with 'file' module

Steps To Reproduce:

```
  - name: Create deployment.properties
    file: path=/Library/Application\ Support/Oracle/Java/Deployment/deployment.properties
          state=touch
          mode=0644
          owner=root
          group=wheel
```

Expected Results:

File should be created as expected (I think this is due to my escaped space, bug report is over traceback output as opposed to functionality)

Actual Results:

```
TASK: [Create deployment.properties] ****************************************** 
changed: [quad]
Traceback (most recent call last):
  File "/opt/local/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/local/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 347, in run
    if not self._run_play(play):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 740, in _run_play
    if not self._run_task(play, task, False):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 474, in _run_task
    self.callbacks.on_task_start(template(play.basedir, name, task.module_vars, lookup_fatal=False, filter_fatal=False), is_handler)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/callbacks.py", line 606, in on_task_start
    name = utils.to_bytes(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/__init__.py", line 1284, in to_bytes
    return value.encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by sivel** [comment]
Does this error still occur in ansible 1.9.1?

**Comment by jnojr** [comment]
I was just coming back to update... I updated my ansible to 1.9.0.1 (latest version in MacPorts) and this one went away :-)

Thanks!
