### ISSUE TITLE
paramiko establishes SSH connection for action plugins

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#10997]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.9.1 (detached HEAD b47d1d7e69) last updated 2015/05/12 16:27:04 (GMT -500)`
##### Ansible Configuration:

N/A
##### Environment:

Control: Mac OS X
Managed: N/A
##### Summary:

When using paramiko as the connection type, ansible will attempt to establish an SSH connection for an action plugin even when not necessary, such as in the example of using `set_fact`
##### Steps To Reproduce:

``` yaml

---
- hosts: all
  gather_facts: false
  tasks:
    - set_fact: foo=bar
    - set_fact: baz=qux
```

```
ansible-playbook -i some.nonexistent.host, -c paramiko -vvvv set_fact.yml
```
##### Expected Results:

```
PLAY [all] ********************************************************************

TASK: [set_fact foo=bar] ******************************************************
<some.nonexistent.host> ESTABLISH CONNECTION FOR USER: sivel
ok: [some.nonexistent.host] => {"ansible_facts": {"foo": "bar"}}

TASK: [set_fact baz=qux] ******************************************************
<some.nonexistent.host> ESTABLISH CONNECTION FOR USER: sivel
ok: [some.nonexistent.host] => {"ansible_facts": {"baz": "qux"}}

PLAY RECAP ********************************************************************
some.nonexistent.host            : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

There is also a traceback, but the cause is due to a SSH connection failure.  There is no such exception in `v2_final` however paramiko still attempts to establish an SSH connection

``````
PLAY [all] ********************************************************************

TASK: [set_fact foo=bar] ******************************************************
<some.nonexistent.host> ESTABLISH CONNECTION FOR USER: sivel on PORT 22 TO some.nonexistent.host
fatal: [some.nonexistent.host] => Traceback (most recent call last):
  File "/Users/sivel/python_venvs/ansibledev/ansible/lib/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/sivel/python_venvs/ansibledev/ansible/lib/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/sivel/python_venvs/ansibledev/ansible/lib/ansible/runner/__init__.py", line 979, in _executor_internal_inner
    except errors.AnsibleConnectionFailed, e:
AttributeError: 'module' object has no attribute 'AnsibleConnectionFailed'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/sivel/set_fact.retry

some.nonexistent.host      : ok=0    changed=0    unreachable=1    failed=0```
``````

**Comment by sivel** [comment]
Forgot to mention.  Specifying `-c ssh` on the command line works as expected, where no SSH connection is attempted.

**Comment by bcoca** [comment]
actually, this has been reported with ssh also, except it does not produce a traceback (i suspect connection plugins are being access prematurely)

**Comment by sivel** [comment]
I cannot confirm that problem with `ssh`, only `paramiko`.

It seems that the problem comes from the `connect` method of `Connection` for `paramiko` actually attempting to connect to the host, whereas for `ssh` the `connect` method only sets up the arguments for the ssh command and does attempt a connection at that point.

The following change seems to resolve the problem with paramiko:

``` patch
diff --git a/lib/ansible/runner/connection_plugins/paramiko_ssh.py b/lib/ansible/runner/connection_plugins/paramiko_ssh.py
index 8eaf97c..32cdec3 100644
--- a/lib/ansible/runner/connection_plugins/paramiko_ssh.py
+++ b/lib/ansible/runner/connection_plugins/paramiko_ssh.py
@@ -132,11 +132,6 @@ class Connection(object):
         return "%s__%s__" % (self.host, self.user)

     def connect(self):
-        cache_key = self._cache_key()
-        if cache_key in SSH_CONNECTION_CACHE:
-            self.ssh = SSH_CONNECTION_CACHE[cache_key]
-        else:
-            self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
         return self

     def _connect_uncached(self):
@@ -189,6 +184,11 @@ class Connection(object):

     def exec_command(self, cmd, tmp_path, become_user=None, sudoable=False, executable='/bin/sh', in_data=None):
         ''' run a command on the remote host '''
+        cache_key = self._cache_key()
+        if cache_key in SSH_CONNECTION_CACHE:
+            self.ssh = SSH_CONNECTION_CACHE[cache_key]
+        else:
+            self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()

         if self.runner.become and sudoable and self.runner.become_method not in self.become_methods_supported:
             raise errors.AnsibleError("Internal Error: this module does not support running commands via %s" % self.runner.become_method)
@@ -415,5 +415,8 @@ class Connection(object):
                 pass
             fcntl.lockf(KEY_LOCK, fcntl.LOCK_UN)

-        self.ssh.close()
+        try:
+            self.ssh.close()
+        except AttributeError:
+            pass
```

**Comment by sivel** [comment]
But I agree, moving the call to connect later may be the better solution

**Comment by sivel** [comment]
So, I just played around with this a little in the `v2_final` branch.  Instead of an explicit call to `_connect`, I created a decorator that would perform the connection.  That way we perform a just in time connection for the operation that is about be performed.

Take a look at https://github.com/ansible/ansible/compare/v2_final...sivel:jit-connect and let me know what you think

**Comment by jimi-c** [comment]
Since we have merged the above in, this should be corrected and we'll close this issue.

Thanks!
