### ISSUE TITLE
bower_module thrown an error if bower_components dir already exists

### ISSUE THREAD

**Issue by bocharsky-bw** [ansible/ansible#11016]
I run next task in my playbook:

``` yaml
    - name: install bower vendor dependencies
      bower: path="/path/to/project" state=latest
```

And if `bower_components` dir not exists in `/path/to/project`, it download all dependencies and works fine, but if I run this task again, I get a next error:

```
< TASK: install bower vendor dependencies >
<transformation.server.ndv.net.ua> ESTABLISH CONNECTION FOR USER: srvadmin
<transformation.server.ndv.net.ua> REMOTE_MODULE bower path="/var/www/sites/transformation/web" state=latest
<transformation.server.ndv.net.ua> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/victor/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=srvadmin -o ConnectTimeout=10 transformation.server.ndv.net.ua /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340 && echo $HOME/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340'
<transformation.server.ndv.net.ua> PUT /tmp/tmpjZzhjm TO /home/srvadmin/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340/bower
<transformation.server.ndv.net.ua> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/victor/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=srvadmin -o ConnectTimeout=10 transformation.server.ndv.net.ua /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=vilcuzdrghmtlvfndvzibzqgxnyjsrmj] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vilcuzdrghmtlvfndvzibzqgxnyjsrmj; LANG=C LC_CTYPE=C /usr/bin/python /home/srvadmin/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340/bower; rm -rf /home/srvadmin/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340/ >/dev/null 2>&1'"'"''

failed: [localhost] => {"failed": true, "parsed": false}

BECOME-SUCCESS-vilcuzdrghmtlvfndvzibzqgxnyjsrmj
Traceback (most recent call last):
  File "/home/srvadmin/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340/bower", line 1786, in <module>
    main()
  File "/home/srvadmin/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340/bower", line 173, in main
    installed, missing, outdated = bower.list()
  File "/home/srvadmin/.ansible/tmp/ansible-tmp-1431673951.26-168306551298340/bower", line 121, in list
    elif data['dependencies'][dep]['pkgMeta']['version'] != data['dependencies'][dep]['update']['latest']:
KeyError: 'version'
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to transformation.server.ndv.net.ua closed.
```

It looks like a bug.

P.S. I run playbook with `-vvvv` key. Remote machine is Ubuntu 12.04, bower is installed and work correctly if I run it manually with `bower install` or `bower update`

My workaround is to remove manually `bower_components` folder first if exists and then execute `install bower vendor dependencies` task.

**Comment by anton-kasperovich** [comment]
Same problem, throws only if components already installed:

```
#playbook.yml
  - name: Install bower dependencies
    sudo: no
    environment:
      PATH: "{{ ansible_env.PATH }}:{{ npm_env }}"
    bower: path=/var/www
    tags: bower_dependencies
```

Error:

```
failed: [construct] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1431682341.19-238187010913402/bower", line 1786, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1431682341.19-238187010913402/bower", line 168, in main
    installed, missing, outdated = bower.list()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1431682341.19-238187010913402/bower", line 121, in list
    elif data['dependencies'][dep]['pkgMeta']['version'] != data['dependencies'][dep]['update']['latest']:
KeyError: 'version'
```

P.S. I guess this issue should be in ansible-modules-extras repo...

**Comment by bcoca** [comment]
This ticket is in the wrong repo, the bower module is in ansible-modules-extras, please reopen there.

**Comment by bocharsky-bw** [comment]
@bcoca Sorry, thanks. Reopen as https://github.com/ansible/ansible-modules-extras/issues/495
