### ISSUE TITLE
paramiko.transport

### ISSUE THREAD

**Issue by bryanheo** [ansible/ansible#11061]
I have error message as shown below
Could you please give a solution?

2015-05-23 23:43:22,798 paramiko.transport Exception: Error reading SSH protocol banner
2015-05-23 23:43:22,850 paramiko.transport Traceback (most recent call last):
2015-05-23 23:43:22,851 paramiko.transport   File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 1509, in run
2015-05-23 23:43:22,851 paramiko.transport     self._check_banner()
2015-05-23 23:43:22,851 paramiko.transport   File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 1626, in _check_banner
2015-05-23 23:43:22,851 paramiko.transport     raise SSHException('Error reading SSH protocol banner' + str(x))
2015-05-23 23:43:22,851 paramiko.transport SSHException: Error reading SSH protocol banner

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel. Meanwhile assuming ssh worksfrom command line works can you please try -c ssh and debug -vvvv with ansible-playbook , that might give some clues in what the issues is.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
