### ISSUE TITLE
Bug report: KeyError when trying to remove not existing entry

### ISSUE THREAD

**Issue by myniva** [ansible/ansible#11109]
When running our playbook (that perfectly works with Ansible 1.6) in Ansible 1.9.1, we run into this issue: 

```
Traceback (most recent call last):
  File "/Users/bbru/Development/ansible/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/bbru/Development/ansible/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/Users/bbru/Development/ansible/lib/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Users/bbru/Development/ansible/lib/ansible/playbook/play.py", line 194, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Users/bbru/Development/ansible/lib/ansible/playbook/play.py", line 669, in _load_tasks
    loaded = self._load_tasks(data, mv, role_params, default_vars, included_become_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/Users/bbru/Development/ansible/lib/ansible/playbook/play.py", line 669, in _load_tasks
    loaded = self._load_tasks(data, mv, role_params, default_vars, included_become_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/Users/bbru/Development/ansible/lib/ansible/playbook/play.py", line 681, in _load_tasks
    role_name=role_name
  File "/Users/bbru/Development/ansible/lib/ansible/playbook/task.py", line 194, in __init__
    del ds['su']
KeyError: 'su'
```

It looks like that line 194 https://github.com/ansible/ansible/blob/f4172fb9daf27baaedd63d1f67ad072b2263d9e7/lib/ansible/playbook/task.py#L194 should be moved up to the if-block.

**Comment by bcoca** [comment]
closed via merged #11110
