### ISSUE TITLE
Gathering Facts failing on shared hosting environment

### ISSUE THREAD

**Issue by gmhenderson** [ansible/ansible#11114]
I am fairly sure there isn't anything wrong with Ansible, and that this following is a host-specific error, but I could use some help interpreting the error.

I am trying to use Ansible on a Media Temple grid account. Running this works:

```
ansible grid7 -m ping
```

However, when I set up a playbook to accomplish the same thing, it breaks:

```

---
- hosts: grid7
  tasks:
    - name: ping
      ping:
```

```
GATHERING FACTS ***************************************************************
failed: [grid7] => {"failed": true, "parsed": false}
/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup:3416: DeprecationWarning: object.__new__() takes no parameters
  return super(cls, subclass).__new__(subclass, *arguments, **keyword)
Traceback (most recent call last):
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 4465, in <module>
    main()
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 137, in main
    data = run_setup(module)
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 81, in run_setup
    facts = ansible_facts(module)
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 4407, in ansible_facts
    facts.update(Virtual().populate())
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 4114, in populate
    self.get_virtual_facts()
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 4212, in get_virtual_facts
    for line in get_file_lines('/proc/cpuinfo'):
  File "/home/207074/users/.home/.ansible/tmp/ansible-tmp-1433184390.31-228590385287030/setup", line 4396, in get_file_lines
    datafile = open(path)
IOError: [Errno 13] Permission denied: '/proc/cpuinfo'
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/ghenderson/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 72.47.244.117 closed.


TASK: [ping] *****************************************************************
```

Using the same playbook on a Media Temple DV (dedicated virtual) works fine, so I'm sure it has to do with how their shared grid servers are configured. Again, just some help interpreting why it's failing would help. Thanks.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case I suspect that you are using python 3 on the target for whatever reason.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
