### ISSUE TITLE
unable to run adhoc commands with devel checkout

### ISSUE THREAD

**Issue by linuxbsdfreak** [ansible/ansible#11143]
Hi,

Receving the following error when running the following command

ansible -i inventory hostgroup -m shell -a "w"

hostname | FAILED! => {u'msg': u'# System setting: app \'blah\' role \'blah\' release \'tag_01\' cluster \'default\'\r\nTraceback (most recent call last):\r\n  File "/home/kevferna/.ansible/tmp/ansible-tmp-1433323910.88-255405376945214/command", line 2106, in <module>\r\n    main()\r\n  File "/home/kevferna/.ansible/tmp/ansible-tmp-1433323910.88-255405376945214/command", line 158, in main\r\n    module = CommandModule(argument_spec=dict())\r\n  File "/home/kevferna/.ansible/tmp/ansible-tmp-1433323910.88-255405376945214/command", line 607, in **init**\r\n    self._check_for_check_mode()\r\n  File "/home/kevferna/.ansible/tmp/ansible-tmp-1433323910.88-255405376945214/command", line 1133, in _check_for_check_mode\r\n    for (k,v) in self.params.iteritems():\r\nAttributeError: \'tuple\' object has no attribute \'iteritems\'\r\n', u'failed': True, u'changed': False, u'parsed': False, u'invocation': {u'module_name': u'command', u'module_args': {u'_raw_params': u'sudo w', u'_uses_shell': True}}}

**Comment by linuxbsdfreak** [comment]
Uninstalled and reinstalled the RPM. Works now
