### ISSUE TITLE
errors is undefined in hashing.py

### ISSUE THREAD

**Issue by BrianHicks** [ansible/ansible#11154]
My team encountered the following error today:

```
TASK: [common | deploy root ca] *********************************************** 
fatal: [lbarrett-worker-02] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1028, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/copy.py", line 165, in run
    local_checksum = utils.checksum(source_full)
  File "/usr/lib/python2.7/site-packages/ansible/utils/hashing.py", line 66, in secure_hash
    raise errors.AnsibleError("error while accessing the file %s, error was: %s" % (filename, e))
NameError: global name 'errors' is not defined

FATAL: all hosts have already failed -- aborting
```

It looks like in tag `1.9.2-0.1.rc1` this isn't fixed, but it is fixed in `devel`. I'm not sure how the branching policy is interacting with the upcoming 1.9.2 and 2.0.0 releases, so I thought I'd open a bug just in case. It'd be great to have this fixed in 1.9.2!

**Comment by BrianHicks** [comment]
Oops, I forgot to say what's actually wrong: `ansible.errors` isn't imported. This is fixed in the `devel` branch by adding the import.

**Comment by bcoca** [comment]
fixed via 7661f86c05eb5955af826e435a8bcd78b1665218, should be out with 1.9.2

**Comment by langston-barrett** [comment]
@bcoca Are you sure that's the correct commit? All I see is an edit to a `docsite/_themes/srtd/layout.html`. Which should not have much to do with this bug. Thanks for your help!

**Comment by bcoca** [comment]
refresh, i did initial comment with bad paste

**Comment by BrianHicks** [comment]
thanks, @bcoca. :)
