### ISSUE TITLE
accelerated mode not working with Vagrant and forwarded port

### ISSUE THREAD

**Issue by pansen** [ansible/ansible#11212]
hey there, 

thanks for your awesome library! i discovered a problem locally which is a bit sad, cause i try a lot locally before i deploy something to live. if i use `accelerate: True` in my playbook and have a host to provision which is cascaded behind a port forwarding from Vagrant, the ssh acceleration port is not openend. 

```
$ bin/ansible --version
ansible 1.9.1
  configured module search path = None

$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!

$ uname -a
Darwin pansen-2.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

stacktrace is that one: 

```
GATHERING FACTS *************************************************************** 
fatal: [127.0.0.1] => Traceback (most recent call last):
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/__init__.py", line 964, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/connection.py", line 52, in connect
    self.active = conn.connect()
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/connection_plugins/accelerate.py", line 137, in connect
    if not self.validate_user():
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/connection_plugins/accelerate.py", line 212, in validate_user
    response = self.recv_data()
  File "/Users/andi/.buildout/eggs/ansible-1.9.1-py2.7.egg/ansible/runner/connection_plugins/accelerate.py", line 169, in recv_data
    d = self.conn.recv(header_len - len(data))
error: [Errno 54] Connection reset by peer
```

here is the vagrant config section for that host: 

```
  config.vm.define "blog" do |app|
    app.vm.hostname = "inv-blog.dev"
    app.vm.box = "ubuntu_precise_64"
    app.vm.synced_folder "src", "/var/www/inventorum.cms/src"

    # override the default ssh forwarding
    app.vm.network :forwarded_port, guest: 22, host: 2226, id: "ssh"
    app.vm.network :forwarded_port, guest: 80, host: 8082, id: "www"

    # TODO amb: why this does not work for ``accelerate``
    app.vm.network :forwarded_port, guest: 5099, host: 5099, protocol: 'tcp', auto_correct: false, id: "ansible_accelerate"

    # bart: DO NOT HARDCODE IP HERE, on different machines masks can be different
    app.vm.network "private_network", type: "dhcp"
  end
```

in that machine i'm checking for open ports when trying to run an accelerated run, which displays to me, there is no open port: 

```
Every 1.0s: netstat -ntpl                                                                       Tue Jun  9 13:23:23 2015

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      7699/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      13000/master
tcp        0      0 0.0.0.0:58436           0.0.0.0:*               LISTEN      565/rpc.statd
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      19411/mysqld
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      26418/memcached
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      553/rpcbind
tcp6       0      0 :::22                   :::*                    LISTEN      7699/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      13000/master
tcp6       0      0 :::33277                :::*                    LISTEN      565/rpc.statd
tcp6       0      0 :::111                  :::*                    LISTEN      553/rpcbind
```

(whereas when i use the ip vms directly, not 127.0.0.1, then there will be an open port on `0.0.0.0:5099`)

my inventory config section looks like this: 

```
[blog]
127.0.0.1 ansible_ssh_port=2226
```

i searched for an answer already, but since i discoverd the missing listening port in the vm i suspect this is a misbehaviour, not a misconfiguration. 

if you want me to prepare a complete example, please let me know. 

thanks in advance! best, andi

**Comment by jctanner** [comment]
Accelerate mode has been deprecated ....

http://docs.ansible.com/ansible/playbooks_acceleration.html

> Accelerated mode is deprecated. Consider using SSH with ControlPersist and pipelining enabled instead. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
