### ISSUE TITLE
winrm stops working in latest trunk revision

### ISSUE THREAD

**Issue by rophy** [ansible/ansible#11217]
##### Issue Type:

Bug Report
##### Ansible Version:

```
# ansible --version
ansible 2.0.0 (devel 757fb39a2e) last updated 2015/06/10 12:15:29 (GMT +800)
  lib/ansible/modules/core: (detached HEAD d6ed6113a7) last updated 2015/06/10 12:15:50 (GMT +800)
  lib/ansible/modules/extras: (detached HEAD 57813a2e74) last updated 2015/06/10 12:16:11 (GMT +800)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/10 12:16:30 (GMT +800)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/10 12:16:51 (GMT +800)
  configured module search path = None
```
##### Ansible Configuration:

Clean check out from git
##### Environment:

Ansible Control Machine: fedora 19
Ansible Target: Windows 2008 R2 SP1
##### Summary:

Since I update to latest trunk, winrm stopped working.
I'm not sure if it's due to misconfiguration, but things were working fine before I update trunk.
- /etc/ansible/hosts contain 1 machine under [windows]
- /etc/ansible/group_vars/windows.yml contains 

```
ansible_ssh_user: Administrator
ansible_ssh_pass: _password_ 
ansible_ssh_port: 5986
ansible_connection: winrm
```
##### Steps To Reproduce:

```
$ git clone git://github.com/ansible/ansible.git --recursive
$ cd ./ansible
$ source ./hacking/env-setup
$ pip install http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
$ pip install kerberos
$ ansible windows -m win_ping  -vvvv
```
##### Expected Results:

ansible should run winrm module and pong the ping.
##### Actual Results:

Seems ansible is not using winrm:

```
[root@lsc102 ansible]# cat /etc/ansible/hosts
lsc102.tw.ibm.com

[windows]
lsc624.tw.ibm.com

[root@lsc102 ansible]# ansible windows -m win_ping  -vvvv
<lsc624.tw.ibm.com> ESTABLISH SSH CONNECTION FOR USER: root
<lsc624.tw.ibm.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=15 lsc624.tw.ibm.com mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433911152.75-194932908369349 && echo $HOME/.ansible/tmp/ansible-tmp-1433911152.75-194932908369349
lsc624.tw.ibm.com | FAILED! => {'msg': u'ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.2p2, OpenSSL 1.0.1e-fips 11 Feb 2013\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 50: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/tmp/ansible-ssh-lsc624.tw.ibm.com-22-root" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to lsc624.tw.ibm.com [172.16.148.118] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 172.16.148.118 port 22: Connection timed out\r\nssh: connect to host lsc624.tw.ibm.com port 22: Connection timed out\r\n', 'failed': True}

```

Attempt to force winrm for target machine:

```
[root@lsc102 ansible]# cat /etc/ansible/hosts
lsc102.tw.ibm.com

[windows]
lsc624.tw.ibm.com ansible_connection=winrm

[root@lsc102 ansible]# ansible windows -m win_ping  -vvvv
lsc624.tw.ibm.com | FAILED! => {'failed': True, 'exception': 'Traceback (most recent call last):\n  File "/root/ansible/lib/ansible/executor/process/worker.py", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File "/root/ansible/lib/ansible/executor/task_executor.py", line 107, in run\n    res = self._execute()\n  File "/root/ansible/lib/ansible/executor/task_executor.py", line 214, in _execute\n    self._handler = self._get_action_handler(connection=self._connection, templar=templar)\n  File "/root/ansible/lib/ansible/executor/task_executor.py", line 421, in _get_action_handler\n    shared_loader_obj=self._shared_loader_obj,\n  File "/root/ansible/lib/ansible/plugins/__init__.py", line 276, in get\n    obj = getattr(self._module_cache[path], self.class_name)(*args, **kwargs)\n  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 64, in __init__\n    self._shell = shell_loader.get(shell_type)\n  File "/root/ansible/lib/ansible/plugins/__init__.py", line 266, in get\n    path = self.find_plugin(name)\n  File "/root/ansible/lib/ansible/plugins/__init__.py", line 246, in find_plugin\n    if not name.startswith(\'_\'):\nAttributeError: \'ShellModule\' object has no attribute \'startswith\'\n', 'stdout': ''}
```

**Comment by rophy** [comment]
update: things will work if i source **v1**/hacking/env-setup.
if this is intended then please close this issue.

**Comment by bcoca** [comment]
not intended, but known that the winrm has not been updated to work with v2

**Comment by brianlloyd** [comment]
FWIW as a clue, I also ran into this. If you put the vars in group_vars/windows.yml they are not picked up and Ansible tries to use SSH. But if you inline them in your hosts file it does get picked up:

[windows:vars]
ansible_ssh_user = myuser
ansible_ssh_pass = mypassword
ansible_ssh_port = 5986
ansible_connection = winrm

**Comment by jimi-c** [comment]
This should be resolved for the devel branch, unless you're running python 2.7.9+ (in which case https://github.com/ansible/ansible/issues/10294 is still an issue).

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
