### ISSUE TITLE
ansible-pull not working on HEAD

### ISSUE THREAD

**Issue by Erethon** [ansible/ansible#11214]
##### Issue Type:

Bug Report
##### Ansible Version:

I'm on `HEAD`, currently 8e3213a.

```
(ansible-devel)c@g:~/Code/ansible [devel]$ ansible-pull --version
ansible-pull 2.0.0
  configured module search path = None
```
##### Ansible Configuration:

I'm running this on a clean enviroment, on a virtual env.
##### Environment:

N/A
##### Summary:

Unless I'm missing something obvious, since the move to V2 (I think
ce3ef7f4c16e47d5a0b5600e1c56c177b7c93f0d) and 0b836262f0720bf6b95761095bbaaf44046973c2, ansible-pull is not working.

For example, commit 0b83626 removes the sys import line, while it's used a
couple of lines later. ce3ef7f4c16e4 seems to remove the `cmd_functions.py`
file in V2, which ansible-pull is depended upon.

There are numerous other issues, preventing ansible-pull from running, this is
just a short list.
##### Steps To Reproduce:

```
make install
ansible-pull localhost -U https://github.com/ansible/ansible -d /tmp/whatever
```
##### Expected Results:

Expected `ansible-pull` to run :P
##### Actual Results:

```
(ansible-devel)c@g:~/Code/ansible [devel]$ ansible-pull localhost -U https://github.com/ansible/ansible -d /tmp/whatever
Traceback (most recent call last):
  File "/home/cool/venvs/ansible-devel/bin/ansible-pull", line 5, in <module>
    pkg_resources.run_script('ansible==2.0.0', 'ansible-pull')
  File "/home/cool/venvs/ansible-devel/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cool/venvs/ansible-devel/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/cool/venvs/ansible-devel/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/EGG-INFO/scripts/ansible-pull", line 65, in <module>
    cli.parse()
  File "/home/cool/venvs/ansible-devel/local/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/cli/pull.py", line 90, in parse
    self.validate_conflicts()
  File "/home/cool/venvs/ansible-devel/local/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/cli/__init__.py", line 188, in validate_conflicts
    if (op.su or op.su_user or op.ask_su_pass) and \
AttributeError: Values instance has no attribute 'su'
```

I'm cc'ing @bcoca who has written one of the above commits.

**Comment by bcoca** [comment]
it was missing a few things, try now from current devel

**Comment by Erethon** [comment]
Was about to comment on the `q` debugging lines, but you beat me to it!

Works like a charm, thank you.

**Comment by Erethon** [comment]
Turns out I was wrong, `lib/ansible/utils/plugins.py` is needed for this to work and it was removed in the past.

**Comment by bcoca** [comment]
hmm, it should be getting what it needs from `lib/ansible/utils/plugins/__init__.py`

**Comment by bcoca** [comment]
ok, fixed it, I had lingering .pyc which made it 'work'.

**Comment by Erethon** [comment]
Yeap, had the same issue. Always forgetting to run `make clean`. Thank you!
