### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FilterModule'

### ISSUE THREAD

**Issue by lucazz** [ansible/ansible#11304]
I have a MacBook Pro (Retina, 13-inch, Late 2013)
Runnning:
Freshly Installed OS X Yosemite 10.10.3 (14D136)
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
Ansible 1.9.1

After doing a clean OS X + Ansible install whenever I try and run a simple playbook, I got the following error message:

```
MacBook-Pro:Ansible Lucas$ ansible-playbook -vvvv -i inventory/hosts stress-test.yml 
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 194, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 681, in _load_tasks
    role_name=role_name
  File "/Library/Python/2.7/site-packages/ansible/playbook/task.py", line 253, in __init__
    self.async_seconds = template.template_from_string(play.basedir, self.async_seconds, all_vars)
  File "/Library/Python/2.7/site-packages/ansible/utils/template.py", line 335, in template_from_string
    environment.filters.update(_get_filters())
  File "/Library/Python/2.7/site-packages/ansible/utils/template.py", line 52, in _get_filters
    plugins = [ x for x in utils.plugins.filter_loader.all()]
  File "/Library/Python/2.7/site-packages/ansible/utils/plugins.py", line 233, in all
    yield getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
AttributeError: 'module' object has no attribute 'FilterModule'
```

Here's a pastebin of all the steps I've done in order to install ansible:
http://pastebin.com/MeMAHWTk

Here's the playbook I've tried to run:
http://pastebin.com/Te0PbhXB
How should I proceed in order to get a playbok running again?

BTW: Ansible ad-hoc commands work just fine

**Comment by lucazz** [comment]
Solved it:
I had forgotten a ancient version of vmware dynamic inventory module installed.
Once I removed that, everything went smoothly

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by CuriousLearner** [comment]
Hi @lucazz,

Were you trying to run Ansible in vagrant? Can you please explain what was the exact issue? Seems like I'm stuck in the same problem.

Thanks :)
