### ISSUE TITLE
Encryption with vault crashes

### ISSUE THREAD

**Issue by hhirsch** [ansible/ansible#11331]
ansible-vault encrypt file.yml

```
Traceback (most recent call last):
File "/usr/bin/ansible-vault", line 66, in <module>
sys.exit(cli.run())
File "/usr/lib/pymodules/python2.7/ansible/cli/vault.py", line 78, in run
self.execute()
File "/usr/lib/pymodules/python2.7/ansible/cli/__init__.py", line 96, in execute
fn()
File "/usr/lib/pymodules/python2.7/ansible/cli/vault.py", line 112, in execute_encrypt
this_editor.encrypt_file()
File "/usr/lib/pymodules/python2.7/ansible/parsing/vault/__init__.py", line 315, in encrypt_file
enc_data = this_vault.encrypt(tmpdata)
File "/usr/lib/pymodules/python2.7/ansible/parsing/vault/__init__.py", line 126, in encrypt
enc_data = this_cipher.encrypt(data, self.password)
File "/usr/lib/pymodules/python2.7/ansible/parsing/vault/__init__.py", line 535, in encrypt
key1, key2, iv = self.gen_key_initctr(password, salt)
File "/usr/lib/pymodules/python2.7/ansible/parsing/vault/__init__.py", line 523, in gen_key_initctr
count=10000, prf=pbkdf2_prf)
File "/usr/lib/python2.7/dist-packages/Crypto/Protocol/KDF.py", line 110, in PBKDF2
password = tobytes(password)
File "/usr/lib/python2.7/dist-packages/Crypto/Util/py3compat.py", line 85, in tobytes
return ''.join(s)
TypeError 
```

Debian 8, Ansible 2

**Comment by robyurkowski** [comment]
I can confirm this -- OSX 10.10.3 with Ansible 2.

```
ansible-vault encrypt ./secrets.yml
Traceback (most recent call last):
  File "/Users/rob/Sites/n/<redacted>/ansible/bin/ansible-vault", line 66, in <module>
    sys.exit(cli.run())
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/cli/vault.py", line 79, in run
    self.execute()
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/cli/__init__.py", line 96, in execute
    fn()
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/cli/vault.py", line 113, in execute_encrypt
    this_editor.encrypt_file()
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/parsing/vault/__init__.py", line 315, in encrypt_file
    enc_data = this_vault.encrypt(tmpdata)
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/parsing/vault/__init__.py", line 131, in encrypt
    enc_data = this_cipher.encrypt(data, self.password)
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/parsing/vault/__init__.py", line 575, in encrypt
    key1, key2, iv = self.gen_key_initctr(password, salt)
  File "/Users/rob/Sites/n/<redacted>/ansible/lib/ansible/parsing/vault/__init__.py", line 563, in gen_key_initctr
    count=10000, prf=pbkdf2_prf)
  File "build/bdist.macosx-10.10-intel/egg/Crypto/Protocol/KDF.py", line 110, in PBKDF2
  File "build/bdist.macosx-10.10-intel/egg/Crypto/Util/py3compat.py", line 85, in tobytes
TypeError
```

EDIT: Removed sensitive info.

**Comment by bcoca** [comment]
can you output ansible --version?

**Comment by bcoca** [comment]
nevermind, you are not passing a password, it should fail waaay before hitting this.

**Comment by bcoca** [comment]
fixed via e153f76c9551ed461f377f66c1a51d83dc65bb12

**Comment by hhirsch** [comment]
Thanks a lot. The solution was of course to add the parameter --ask-vault-pass.
Now I am wondering why there is a parameter that has to be supplied or the command won't work.

Like ansible-vault encrypt --ask-vault-pass --do-not-crash --realy-do-not-crash --supply-this-parameter-or-ansible-will-crash ./secrets.yml

But I do not realy need an answer for that. I was just wondering.

**Comment by bcoca** [comment]
its just that the dumbass that rewrote the cli never tested w/o a password (yep, that was me)
