### ISSUE TITLE
Handle winrm UnauthorizedError

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#11393]
As of:

```
commit 7ab74a4b8fbeb2af707c5628703c485f8d14238d
Author: Alexey Diyan <alexey.diyan@gmail.com>
Date:   Wed Aug 20 17:16:35 2014 +0300

    Handle unauthorized response and raise UnauthorizeError
```

winrm returns an UnauthorizedError exception for the 401 response code.  This causes unauthorized connections to time out with:

```
host.com | FAILED => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor     
    exec_rc = self._executor_internal(host, new_stdin)                                           
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 792, in _executor_internal                                                                                             
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)                                                                       
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 957, in _executor_internal_inner                                                                                       
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)                                                                  
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection.py", line 51, in connect      
    self.active = conn.connect()                                                                 
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 132, in connect                                                                                        
    self.protocol = self._winrm_connect()                                                        
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 86, in _winrm_connect                                                                                  
    protocol.send_message('')                                                                    
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message           
    return self.transport.send_message(message)                                                  
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 82, in send_message           
    response = urlopen(request, timeout=self.timeout)                                            
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen                                   
    return _opener.open(url, data, timeout)                                                      
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open                                      
    response = self._open(req, data)                                                             
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open                                     
    '_open', req)                                                                                
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain                               
    result = func(*args)                                                                         
  File "/usr/lib64/python2.7/urllib2.py", line 1216, in http_open                                
    return self.do_open(httplib.HTTPConnection, req)                                             
  File "/usr/lib64/python2.7/urllib2.py", line 1189, in do_open                                  
    r = h.getresponse(buffering=True)                                                            
  File "/usr/lib64/python2.7/httplib.py", line 1045, in getresponse                              
    response.begin()                                                                             
  File "/usr/lib64/python2.7/httplib.py", line 409, in begin                                     
    version, status, reason = self._read_status()                                                
  File "/usr/lib64/python2.7/httplib.py", line 365, in _read_status                              
    line = self.fp.readline(_MAXLINE + 1)                                                        
  File "/usr/lib64/python2.7/socket.py", line 476, in readline                                   
    data = self._sock.recv(self._rbufsize)                                                       
error: [Errno 104] Connection reset by peer 
```

Instead of the expected:

```
host.com | FAILED => the username/password specified for this server was incorrect
```

**Comment by opoplawski** [comment]
Hmm, I may have spoke to soon.  WIth 1.9.2 I seem to get:

```
host.com  | FAILED => 401 Unauthorized. basic auth failed
```
