### ISSUE TITLE
0eb1c88 causes traceback when specifying tags

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#11424]
Via a git bisect, I have found that a recent traceback when specifying tags on the command line, was introduced in 0eb1c88 to resolve #9380 

That commit references:

> Use itertools instead of set for tags

```
Traceback (most recent call last):
  File "/Users/matt/python_venvs/ansibledev/ansible/bin/ansible-playbook", line 66, in <module>
    sys.exit(cli.run())
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/cli/playbook.py", line 161, in run
    results = pbex.run()
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/executor/playbook_executor.py", line 127, in run
    result = self._tqm.run(play=play)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/executor/task_queue_manager.py", line 248, in run
    iterator = PlayIterator(inventory=self._inventory, play=new_play, connection_info=connection_info, all_vars=all_vars)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/executor/play_iterator.py", line 95, in __init__
    new_block = block.filter_tagged_tasks(connection_info, all_vars)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/playbook/block.py", line 318, in filter_tagged_tasks
    new_block.block  = evaluate_and_append_task(self.block)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/playbook/block.py", line 313, in evaluate_and_append_task
    if task.evaluate_tags(connection_info.only_tags, connection_info.skip_tags, all_vars=all_vars):
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/playbook/taggable.py", line 82, in evaluate_tags
    elif tags.intersection(only_tags):
AttributeError: 'list' object has no attribute 'intersection'
```

cc @jimi-c

**Comment by jimi-c** [comment]
As noted in #11424, I fixed this in a slightly different way than proposed there. Simply ensuring the tags are saved as a set internally should fix this.

Thanks!

**Comment by marconius** [comment]
Hello! I worked on a fix for this issue, but the issue was closed in the meantime. My fix includes tests for the `taggable` module. I also took the approach of leaving tags as a list and constructing sets only when intersection is called, because it seemed more straightforward to me. Anyway, my changes are at on [my branch](https://github.com/marconius/ansible/tree/fixes_11424_list_has_no_intersection) if anyone wants to see them.

**Comment by jimi-c** [comment]
@marconius thanks, I had implemented a fix for this already.

**Comment by marconius** [comment]
@jimi-c , might the tests I wrote be useful?

**Comment by jimi-c** [comment]
@marconius I did not see any tests in that PR.

**Comment by marconius** [comment]
sorry @jim-c, I hadn't created a pull request. You probably looked at sivel's PR.

I created PR #11527 now.

**Comment by jimi-c** [comment]
@marconius thanks!
