### ISSUE TITLE
yum with_items is not working

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible#11448]
This code works fine in 1.8.4

tasks:
    - name: install tools
      yum: name={{ item }} state=latest
      with_items:
        - curl-devel
        - expat-devel

However, in the head version I get an error like this:

TASK [install tools] ************************************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/jgrigonis/github/ansible/lib/ansible/executor/process/worker.py", line 118, in run
    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/Users/jgrigonis/github/ansible/lib/ansible/executor/task_executor.py", line 83, in run
    item_results = self._run_loop(items)
  File "/Users/jgrigonis/github/ansible/lib/ansible/executor/task_executor.py", line 151, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/Users/jgrigonis/github/ansible/lib/ansible/executor/task_executor.py", line 189, in _squash_items
    if templar._contains_vars(name):
  File "/Users/jgrigonis/github/ansible/lib/ansible/template/__init__.py", line 204, in _contains_vars
    return self.environment.block_start_string in data or self.environment.variable_start_string in data
TypeError: argument of type 'NoneType' is not iterable

fatal: [computer]: FAILED! => {"failed": true, "stdout": ""}

**Comment by bcoca** [comment]
so I cannot reproduce this, can you try again with current head?

**Comment by jgrigonis** [comment]
It seems to have been fixed. Working now on latest head revision.
