### ISSUE TITLE
v1.9.1 firewalld with state=enabled errors when port is already enabled

### ISSUE THREAD

**Issue by jhitt25** [ansible/ansible#11473]
Ansible task:

```
- name: Open SNMP port in the firewall
  firewalld: port=snmp/udp permanent=true state=enabled immediate=yes
```

Output:

```
TASK: [snmp | Open SNMP port in the firewall] *********************************
failed: [example.org] => {"failed": true, "parsed": false}
BECOME-SUCCESS-amzwrjvuuadecjeviifjjsetfswhsthp
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
[sudo via ansible, key=amzwrjvuuadecjeviifjjsetfswhsthp] password: Traceback (most recent call last):
  File "<stdin>", line 2002, in <module>
  File "<stdin>", line 341, in main
  File "<stdin>", line 111, in set_port_enabled
  File "<string>", line 2, in addPort
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 103, in _enable_proxy
    return func(*p, **k)
  File "<string>", line 2, in addPort
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 2060, in addPort
    return dbus_to_python(self.fw_zone.addPort(zone, port, protocol, timeout))
  File "/usr/lib/python2.7/site-packages/slip/dbus/proxies.py", line 50, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ALREADY_ENABLED
```

**Comment by jhitt25** [comment]
I have done some further tracking on this issue and found the culprit.  If the display of 'firewall-cmd' does not exactly match the command ansible creates, then ansible does not detect that the rule already exists, thus trying to add it again.  This can be more easily seen with a rich rule example:

This fails:
`firewalld: rich_rule='rule family="ipv4" source address="192.168.1.10" port protocol="tcp" port="11211" accept' permanent=true state=enabled immediate=yes`

But this suceeds:
`firewalld: rich_rule='rule family="ipv4" source address="192.168.1.10" port port="11211" protocol="tcp" accept' permanent=true state=enabled immediate=yes`

**Comment by ag-wood** [comment]
@jhitt25 - I have lodged a pull request that fixes this issue at: ansible/ansible-modules-extras#1081

**Comment by Tanz0rz** [comment]
This has been merged. This issue should probably be marked as closed now @jhitt25

**Comment by jhitt25** [comment]
My apologies. I lost track of it over the holidays.
