### ISSUE TITLE
ansible-vault rekey fails

### ISSUE THREAD

**Issue by fabianbadoi** [ansible/ansible#11584]
There's a bug in ansible-vault.py that causes it to fail on "rekey".
Error:

```
[ERROR]: Unexpected Exception: global name 'action' is not defined

the full traceback was:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/EGG-INFO/scripts/ansible-vault", line 76, in <module>
    cli.parse()
  File "/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/cli/vault.py", line 61, in parse
    elif action == "rekey":
NameError: global name 'action' is not defined
```

The error is caused by this line https://github.com/ansible/ansible/blob/032690a8439012833ca4206acd3ce3fe4d725e6c/lib/ansible/cli/vault.py#L61

Which should be `elif self.action == "rekey":`

**Comment by fabianbadoi** [comment]
Thanks for the swift action, Brian!
