### ISSUE TITLE
hacking/test-module needs updating for devel

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#11619]
following #11618 I started trying different modules

```
$  hacking/test-module -m ~/dev/ansible-modules-core/cloud/amazon/ec2.py -a '{ "region":"eu-west-1", "key_name":"ec2"}'
Traceback (most recent call last):
  File "hacking/test-module", line 194, in <module>
    main()
  File "hacking/test-module", line 178, in main
    (modfile, module_style) = boilerplate_module(options.module_path, options.module_args, options.interpreter, options.check)
  File "hacking/test-module", line 103, in boilerplate_module
    complex_args = utils.combine_vars(complex_args, utils.parse_yaml(args))
AttributeError: 'module' object has no attribute 'combine_vars'
```

is `lib/ansible/utils/__init__.py` supposed to pull in all other files in the folder?  The above error happens unless  the following import is added `import ansible.utils.vars as vars`

With the above import added it then errors with

```
$  hacking/test-module -m ~/dev/ansible-modules-core/cloud/amazon/ec2.py -a '{ "region":"eu-west-1", "key_name":"ec2"}'
Traceback (most recent call last):
  File "hacking/test-module", line 196, in <module>
    main()
  File "hacking/test-module", line 180, in main
    (modfile, module_style) = boilerplate_module(options.module_path, options.module_args, options.interpreter, options.check)
  File "hacking/test-module", line 105, in boilerplate_module
    complex_args = vars.combine_vars(complex_args, utils.parse_yaml(args))
AttributeError: 'module' object has no attribute 'parse_yaml'
```

grep'ing shows that parse_yaml and parse_yaml_from_file only exist in the v1 code base.

That's as far as I got.

**Comment by jimi-c** [comment]
Since the above was merged in, we will close this issue.

Thanks!
