### ISSUE TITLE
ansible-doc --list fails / get_url documentaion defect?

### ISSUE THREAD

**Issue by svnhmyr** [ansible/ansible#11772]
Environment: Ubuntu 14.04 / Ansible 2.0 branch devel , d78c2fc212840a0d128244893e6a4a88f3feef48

sven@l:~/folder$ ansible-doc --list
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/utils/module_docs.py", line 62, in get_docstring
    doc = yaml.safe_load(child.value.s)
  File "/usr/lib/python2.7/dist-packages/yaml/**init**.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<string>", line 75, column 5:
        description:
        ^
expected <block end>, but found '<block mapping start>'
  in "<string>", line 77, column 6:
         required: false
         ^
ERROR! module get_url has a documentation error formatting or is missing documentation

**Comment by bcoca** [comment]
this should be fixed in current devel
