### ISSUE TITLE
AttributeError: 'str' object has no attribute 'set_playbook_basedir'

### ISSUE THREAD

**Issue by zukeru** [ansible/ansible#11777]
I'm trying to call a playbook I know works from github on boot of an ec2 instance through cloud-init scripting. I wrote a python script to do this but I'm getting the following error:

```
AttributeError: 'str' object has no attribute 'set_playbook_basedir
```

I'm not quite sure what im doing wrong with the python and why my api call doesn't work. the playbook is there.

```
/usr/lib64/python2.7/dist-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
fatal: destination path 'vision_provis' already exists and is not an empty directory.
/home/ec2-user/vision_provis/storm.yml
Traceback (most recent call last):
  File "/var/lib/cloud/instance/scripts/part-001", line 58, in <module>
    check=True)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 169, in __init__
    self.inventory.set_playbook_basedir(self.basedir)
AttributeError: 'str' object has no attribute 'set_playbook_basedir'



#!/usr/bin/python
import ansible.runner
from ansible.playbook import PlayBook
from ansible import inventory
from ansible import callbacks
import json
import subprocess
import os
from ansible import utils
import time

def shell_command_execute(cmd):
    try:
        subprocess.Popen(['/bin/bash', '-c', cmd])
    except:
        print 'There seems to be an error'
repo = "https://github.com/zukeru/vision_provis.git"
playbook = "storm.yml"


echo_bash_profile = "export CLOUD_ENVIRONMENT=integration|export CLOUD_MONITOR_BUCKET=0|export CLOUD_APP=ES-test-storm-deploy-DEV--_yV_cyE-|export CLOUD_STACK=infra|export CLOUD_CLUSTER=0|export CLOUD_AUTO_SCALE_GROUP=0|export CLOUD_LAUNCH_CONFIG=0|export EC2_REGION=us-west-2|export CLOUD_DEV_PHASE=0|export CLOUD_REVISION=0|export CLOUD_DOMAIN=0|export SG_GROUP=ES-test-storm-deploy-DEV--qtv6a_Uj"

for commands in echo_bash_profile.split('|'):
    command_to_send = 'echo "' + commands + '" >> /home/ec2-user/.bash_profile'
    shell_command_execute(commands)
    shell_command_execute(command_to_send)

var_user_data = "export SHARDS = 3"

for commands in var_user_data.split('|'):
    echo_bash_profile_passed = 'echo "' + commands  + '" >> /home/ec2-user/.bash_profile'
    shell_command_execute(commands)
    shell_command_execute(echo_bash_profile_passed)

command_remove = 'rm -rf /home/ec2-user/'+repo
shell_command_execute(command_remove)

command = 'cd /home/ec2-user/; git clone ' + repo
shell_command_execute(command)

folder = repo.split('/')[4].replace('.git','')
full_path = '/home/ec2-user/' + folder + '/' + playbook

time.sleep(6)

# setting callbacks
stats = callbacks.AggregateStats()
playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)

print full_path
# creating the playbook instance to run, based on "test.yml" file
pb = PlayBook(playbook = full_path,
                               stats = stats,
                               callbacks = playbook_cb,
                               runner_callbacks = runner_cb,
                               inventory = "localhost",
                               check=True)
# running the playbook
pr = pb.run()

# print the summary of results for each host
#print json.dumps(pr, sort_keys=True, indent=4, separators=(',', ': '))
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jimi-c** [comment]
Hi @zukeru, it looks like you're using the v1 API, which is being changed for that in devel. If you want examples of how to use it, please reference the cli/ sub-directory (we don't currently have any documentation on others using the API directly).

Thanks!
