### ISSUE TITLE
Colon in password causes strange issues with SSH port variable.

### ISSUE THREAD

**Issue by MeanEYE** [ansible/ansible#11911]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible-playbook", line 157, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 100, in __init__
    self.parser = InventoryDirectory(filename=host_list)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/dir.py", line 54, in __init__
    parser = InventoryDirectory(filename=fullpath)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/dir.py", line 54, in __init__
    parser = InventoryDirectory(filename=fullpath)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/dir.py", line 58, in __init__
    parser = InventoryParser(filename=fullpath)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/ini.py", line 43, in __init__
    self._parse()
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/ini.py", line 47, in _parse
    self._parse_base_groups()
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/ini.py", line 140, in _parse_base_groups
    host = Host(name=hn, port=port)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/host.py", line 32, in __init__
    self.set_variable('ansible_ssh_port', int(port))
ValueError: invalid literal for int() with base 10: 'KyX0Vx.gpWqyGYt'
```

Upon further investigation I discovered password generated with `lookup('password', ...)` from task command. Complete generated password is `zDq8:KyX0Vx.gpWqyGYt`. So something with parsing `:` is causing this error.

**Comment by MeanEYE** [comment]
Okay, so issue with this one is that I am storing files inside of inventory directory and Ansible is parsing these files. It's bad usage on my part. Am closing it as invalid. Thanks!
