### ISSUE TITLE
Uncought type error

### ISSUE THREAD

**Issue by mschirmacher** [ansible/ansible#11938]
Hello again.
im trying to create CouchDB views using ansible. On my machine runs ansible 1.9.2 (the current version in Debian sid and testing).
Fortunately you dont need CouchDB to reproduce the bug. All you need is netcat listening on port 5984.
Please find  the playbook here: https://gist.github.com/mschirmacher/f0d0c885c6f2ebe1cb2b
Running this playbook results in a stack trace here:

```
TASK: [Create views] ********************************************************** 
failed: [default] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1439379804.74-207004154518409/uri", line 2067, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1439379804.74-207004154518409/uri", line 419, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout, validate_certs)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1439379804.74-207004154518409/uri", line 312, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)     
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1592, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1334, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 854, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: must be string or buffer, not dict
OpenSSH_6.7p1 Debian-6, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /home/thana/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.


FATAL: all hosts have already failed -- aborting
```

Also when looking at the netcat output you will see, that ansible does not send any body.
Funnily when you break the json syntax (i did that by removing the last " in line 2 of the linked template) it sends the content body!

**Comment by mschirmacher** [comment]
FWIW:

 the output of the debug task when the json is OK:

```
TASK: [debug var=view_creation_body] ****************************************** 
ok: [default] => {
    "var": {
        "view_creation_body": {
            "_id": "_design/node_id", 
            "bar": {
                "map": "function(doc){if(doc.eventType && doc.eventType===\"bar\"){emit(doc.eventType,doc.payload);}}"
            }, 
            "foo": {
                "map": "function(doc){if(doc.eventType && doc.eventType===\"foo\"){emit(doc.eventType,doc.payload);}}"
            }
        }
    }
}
```

**Comment by mschirmacher** [comment]
I came to the conclusion this is a bug in the uri module, so i created an issue against the correct project.
