### ISSUE TITLE
Error when set fact_caching_timeout to 0 with ansible version 1.9.2

### ISSUE THREAD

**Issue by nwe01** [ansible/ansible#12018]
Issue Type:

Bug Report

ansible version:  1.9.2

Ansible Configuration:
(ansible.cfg)
# redis facts_cache

fact_caching = redis
fact_caching_timeout = 0
fact_caching_connection = 127.0.0.1:6379:0

Environment:
CentOS Linux release 7.

When using facts caching with redis and has set  fact_caching_timeout = 0 ( to disable expiring)
you get this error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/**init**.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 664, in _executor_internal
    inject = self.get_inject_vars(host)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 607, in get_inject_vars
    combined_cache = self.get_combined_cache()
  File "/usr/lib/python2.7/site-packages/ansible/runner/**init**.py", line 602, in get_combined_cache
    combined_cache = self.setup_cache.copy()
  File "/usr/lib/python2.7/site-packages/ansible/cache/**init**.py", line 54, in copy
    return dict([(k, v) for (k, v) in self.iteritems()])
  File "/usr/lib64/python2.7/_abcoll.py", line 386, in iteritems
    for key in self:
  File "/usr/lib/python2.7/site-packages/ansible/cache/__init__.py", line 47, in **iter**
    return iter(self._plugin.keys())
  File "/usr/lib/python2.7/site-packages/ansible/cache/redis.py", line 87, in keys
    self._expire_keys()
  File "/usr/lib/python2.7/site-packages/ansible/cache/redis.py", line 84, in _expire_keys
    self._cache.zremrangebyscore(self._keys_set, 0, expiry_age)
UnboundLocalError: local variable 'expiry_age' referenced before assignment

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
