### ISSUE TITLE
Vault encryption breaks with non-ASCII data

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#12037]
Issue type: Bug report
Ansible version: devel
Ansible configuration: NA
Environment: Linux
Summary:

If there's any non-ASCII data in the file to be encrypted, ansible-vault breaks with the stack trace shown below. (In my case, the non-ASCII data in question was the single character "ä".)

Steps to reproduce:

```
ansible-vault -vvvv create x.yml
```

Enter a password, enter "ä" in the editor, save, quit.

Expected results: Encryption is successful.

Actual results:

```
Traceback (most recent call last):
  File "/home/ams/extern/ansible/bin/ansible-vault", line 79, in <module>
    sys.exit(cli.run())
  File "/home/ams/extern/ansible/lib/ansible/cli/vault.py", line 83, in run
    self.execute()
  File "/home/ams/extern/ansible/lib/ansible/cli/__init__.py", line 97, in execute
    fn()
  File "/home/ams/extern/ansible/lib/ansible/cli/vault.py", line 89, in execute_create
    this_editor.create_file()
  File "/home/ams/extern/ansible/lib/ansible/parsing/vault/__init__.py", line 258, in create_file
    self._edit_file_helper(cipher=self.cipher_name)
  File "/home/ams/extern/ansible/lib/ansible/parsing/vault/__init__.py", line 240, in _edit_file_helper
    enc_data = this_vault.encrypt(tmpdata)
  File "/home/ams/extern/ansible/lib/ansible/parsing/vault/__init__.py", line 132, in encrypt
    enc_data = this_cipher.encrypt(data, self.password)
  File "/home/ams/extern/ansible/lib/ansible/parsing/vault/__init__.py", line 601, in encrypt
    cryptedData = cipher.encrypt(data)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 0: ordinal not in range(128)
```

**Comment by amenonsen** [comment]
A related problem: at the vault password prompt, if I enter the single character "ä" as a password, `ansible-vault` quits with a usage message. But entering two of them, or a mixture, works as expected. It's only one non-ASCII character as a password that breaks.

**Comment by abadger** [comment]
The first half of this is now fixed: https://github.com/ansible/ansible/pull/12075

I couldn't replicate the second part of this even by checking out older versions of the code.  Are you still seeing the problem with single character non-ASCII passwords?

**Comment by amenonsen** [comment]
I can't reproduce the password problem any more with current devel, so I'm closing this issue now.
