### ISSUE TITLE
Unable to pass variable to pause module

### ISSUE THREAD

**Issue by bladypirat** [ansible/ansible#1209]
While having in playbook:

```
  vars:
    sleep_time: 15
  tasks:
    - name: test pause module ${sleep_time}
      action: pause seconds=${sleep_time}
```

I got output from ansible:

```
TASK: [test pauser module 15] *********************
fatal: [s-host] => Traceback (most recent call last):
  File "/home/user/GIT/ansible/lib/ansible/runner/__init__.py", line 227, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/user/GIT/ansible/lib/ansible/runner/__init__.py", line 276, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/user/GIT/ansible/lib/ansible/runner/__init__.py", line 360, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject)
  File "/home/user/GIT/ansible/lib/ansible/runner/action_plugins/pause.py", line 68, in run
    self.pause_type, pause_params)
TypeError: not enough arguments for format string


FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Since the idea of executing a module outside the host loop is new, I'm guessing this is just missing a simple utils.template call.    Should be very easy to fix.

@tbielawa want to look at this?

**Comment by timlnx** [comment]
Im on it

**Comment by timlnx** [comment]
Note to @bladypirat using vars in the `name` doesn't always work in all cases. For `seconds` it works, but not for `prompt`s. It's just the way things are. Otherwise your wish has been granted, enjoy!

**Comment by bladypirat** [comment]
Thanks:)
