### ISSUE TITLE
Problem with Ansible on OS X

### ISSUE THREAD

**Issue by Mykolaichenko** [ansible/ansible#12183]
Hi guys, I have some trouble.. Can anybody help me? 
I've reinstalled all that I can: python, ansible... What may I do? 
Thanks a lot. 

omykolaichenkos-MacBook-Pro:playbooks oleg$ ansible testserver -i hosts -m ping
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible", line 197, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible", line 121, in run
    inventory_manager = inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/**init**.py", line 128, in **init**
    self.parser = InventoryParser(filename=host_list)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/ini.py", line 43, in **init**
    self._parse()
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/ini.py", line 47, in _parse
    self._parse_base_groups()
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/inventory/ini.py", line 108, in _parse_base_groups
    tokens = shlex.split(line)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 191, in read_token
    raise ValueError, "No escaped character"
ValueError: No escaped character

**Comment by jimi-c** [comment]
Hi @Mykolaichenko, can you share the INI file for inventory which is being parsed? It appears that you may have a backslash or some other character in it which is tripping up shlex.

**Comment by jimi-c** [comment]
FWIW, that was recently rewritten in devel, and that line of code no longer exists.

**Comment by Mykolaichenko** [comment]
<img width="802" alt="screen shot 2015-09-01 at 9 55 43 pm" src="https://cloud.githubusercontent.com/assets/10963524/9613474/3c3053f0-50f4-11e5-901f-aa43321d04b6.png">
Thanks a lot. I had the mistake in hosts file (showing on screen). It looks like I had copy-paste code to file and haven't deleted backslashes. After I fixed my hosts file, it works pretty well.

**Comment by jimi-c** [comment]
Ahh yes, that's an editing thing, and not valid in an INI. Thanks for following up, I'll go ahead and close this out.
