### ISSUE TITLE
"Unexpected Exception: maximum recursion depth exceeded" when defining many vars at runtime

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#12260]
##### Issue Type:
- Bug Report
##### Ansible Version:

`v2.0.0-0.2.alpha2`
##### Ansible Configuration:

```
[defaults]
roles_path = ~/Dropbox/VMs/roles
nocows = 1
hostfile = /etc/ansible/hosts
forks = 20
host_key_checking=False
```
##### Environment:

Mac OS X 10.10.5 Yosemite
##### Summary:

A common pattern I use in Ansible roles to allow for variable defaults per OS platform is to define variables like `__variable` in two platform-specific `vars` files, of which one is included at runtime, then when the role is run, there is a task that checks if `variable` is defined (without `__` prefix).

If `variable` is defined, then it will remain set as-is, but if not, `set_fact` sets `variable` to the value of `__variable`.

For example:

``` yaml
- name: Define php_extension_conf_path.
  set_fact:
    php_extension_conf_path: "{{ __php_extension_conf_path }}"
  when: php_extension_conf_path is not defined
```

See the actual failing example in this role: https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L21-L24

What's strange is that three earlier variables in the same role are defined the same way, and they work correctly. It bails on this fourth var.
##### Steps To Reproduce:
1. Run a playbook defining many variables at runtime (e.g. one that uses the `geerlingguy.php` role from Ansible Galaxy).

Note that this error has so far been mainly tested by running the Ansible playbook that's part of [Drupal VM](http://www.drupalvm.com/). The quick start guide shows how to install dependencies and run the playbook locally using Vagrant.
##### Expected Results:

The playbook run completes successfully.
##### Actual Results:

The playbook bails on the `Define php_extension_conf_path.` step. Full traceback:

```
TASK [geerlingguy.php : Define php_extension_conf_path.] ***********************
ok: [drupalvm] => {"ansible_facts": {"php_extension_conf_path": "/etc/php5/apache2/conf.d"}, "changed": false}
Unexpected Exception: maximum recursion depth exceeded
the full traceback was:

Traceback (most recent call last):
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/bin/ansible-playbook", line 79, in <module>
    sys.exit(cli.run())
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/cli/playbook.py", line 138, in run
    results = pbex.run()
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/executor/playbook_executor.py", line 135, in run
    result = self._tqm.run(play=play)
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/executor/task_queue_manager.py", line 209, in run
    return strategy.run(iterator, play_context)
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/plugins/strategies/linear.py", line 214, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/vars/__init__.py", line 272, in get_vars
    all_vars['vars'] = all_vars['hostvars'][host.get_name()]
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/vars/hostvars.py", line 78, in __getitem__
    return templar.template(data, fail_on_undefined=False)
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/template/__init__.py", line 262, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/template/__init__.py", line 240, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/template/__init__.py", line 376, in _do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/vars/unsafe_proxy.py", line 74, in __str__
    return str(object.__getattribute__(self, "_obj"))
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/vars/unsafe_proxy.py", line 74, in __str__
    return str(object.__getattribute__(self, "_obj"))
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/vars/unsafe_proxy.py", line 74, in __str__
    return str(object.__getattribute__(self, "_obj"))
[... the above line repeats about 200 times ...]
    return str(object.__getattribute__(self, "_obj"))
RuntimeError: maximum recursion depth exceeded
```

**Comment by geerlingguy** [comment]
Note that this playbook completes successfully with Ansible 1.9.3 (and prior).

**Comment by geerlingguy** [comment]
If I entirely remove that task, then Ansible bails on the _next_ task that defines a variable at runtime.

And if I entirely remove _that_ task (the next one that fails), then the one after _it_ fails. So there's some sort of hard limit being reached that wasn't in Ansible 1.9.x.

**Comment by geerlingguy** [comment]
Even if I skip all of those variable steps, Ansible eventually bails on an include with a `when` condition. (Specifically, the include of the `setup-RedHat` or `setup-Debian` task file.)

**Comment by jimi-c** [comment]
The code that's being hit was just added Friday, so I'll look into why. Really, this particular object should currently only be used on variables from the setup cache (facts) to ensure they're not templated.

**Comment by jody-frankowski** [comment]
I'm having the same issue. I have tried to strip down my playbook to a reproducible bug. It seemed that when I removed a sufficient number of hosts from my inventory the problem did not reproduce.

**Comment by jimi-c** [comment]
@geerlingguy I've pushed the above commit, which resolves the issue for @jody-frankowski, if you'd like to validate against your plays as well.

**Comment by geerlingguy** [comment]
@jimi-c - Thanks—just updated local git branch, and the problem is gone. You'll be happy to know that [Drupal VM](http://www.drupalvm.com/) is by far the most complex playbook monstrosity I've created, and it is running fine with Ansible 2.0 now; haven't tested with CentOS 7 yet, but Ubuntu 12/14 and CentOS 6 are all happy.

**Comment by jimi-c** [comment]
Excellent, I'll go ahead and close this then.

Thanks!
