### ISSUE TITLE
Ansible win_copy fails for local centos to remote windows machine

### ISSUE THREAD

**Issue by jugalporwal** [ansible/ansible#12376]
Hi

Im trying to copy a file directory from my local centos control node to a remote windows machine using win_copy.My playbook is follows :
- hosts: windows
  tasks:
  - name: Deploy the Jenkins build on windows
    win_copy: src=/home/router/ dest=D:\test\

It starts copying but in the final stage i get the below error

<192.168.199.93> WINRM PUT /home/router/thirdparty/lib/spring-web-4.1.7.RELEASE.jar to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\source (offset=720650 size=1565)
<192.168.199.93> PUT /tmp/tmpL_R4df TO C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\win_copy
<192.168.199.93> WINRM PUT /tmp/tmpL_R4df to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\win_copy.ps1 (offset=0 size=2031)
<192.168.199.93> WINRM PUT /tmp/tmpL_R4df to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\win_copy.ps1 (offset=2031 size=2031)
<192.168.199.93> WINRM PUT /tmp/tmpL_R4df to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\win_copy.ps1 (offset=4062 size=2031)
<192.168.199.93> WINRM PUT /tmp/tmpL_R4df to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\win_copy.ps1 (offset=6093 size=2031)
<192.168.199.93> WINRM PUT /tmp/tmpL_R4df to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1442321410.65-34546933940647\win_copy.ps1 (offset=8124 size=646)
fatal: [192.168.199.93] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/**init**.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 1032, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/action_plugins/win_copy.py", line 256, in run
    module_return = self.runner._execute_module(conn, tmp_path, 'win_copy', module_args_tmp, inject=inject, complex_args=complex_args, delete_remote_tmp=delete_remote_tmp)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 507, in _execute_module
    argsfile = self._transfer_str(conn, tmp, 'arguments', utils.jsonify(utils.parse_kv(args)))
  File "/usr/lib/python2.6/site-packages/ansible/utils/__init__.py", line 787, in parse_kv
    vargs = split_args(args)
  File "/usr/lib/python2.6/site-packages/ansible/module_utils/splitter.py", line 185, in split_args
    raise Exception("error while splitting arguments, either an unbalanced jinja2 block or quotes")
Exception: error while splitting arguments, either an unbalanced jinja2 block or quotes

Im using ansible 1.9.2

**Comment by cchurch** [comment]
@jugalporwal Could you try against devel/2.0 to see if you can reproduce?

**Comment by jugalporwal** [comment]
@cchurch I installed ansible-2.0.0-0.2.alpha2.tar.gz . The installation was successful but on running the command ansible --version it says: 

Unexpected Exception: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 66, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/lib/python2.6/site-packages/ansible/cli/adhoc.py", line 22, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 31, in <module>
    from ansible.executor.process.worker import WorkerProcess
  File "/usr/lib/python2.6/site-packages/ansible/executor/process/worker.py", line 34, in <module>
    from Crypto.Random import atfork
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
How do i resolve it?

**Comment by jugalporwal** [comment]
@cchurch Hi Chris, I downloaded the ansible-2.0.0-0.2.alpha2.tar.gz and installed it on my control machine. Hoever now I'm not able to ping any of my machines. It gives the following error

Unexpected Exception: lstat() argument 1 must be encoded string without NULL bytes, not str
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 79, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.6/site-packages/ansible/cli/adhoc.py", line 111, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/**init**.py", line 77, in **init**
    self.parse_inventory(host_list)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/**init**.py", line 133, in parse_inventory
    host.vars = combine_vars(host.vars, self.get_host_variables(host.name))
  File "/usr/lib/python2.6/site-packages/ansible/inventory/**init**.py", line 499, in get_host_variables
    self._vars_per_host[hostname] = self._get_host_variables(hostname, vault_password=vault_password)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/__init__.py", line 529, in _get_host_variables
    vars = combine_vars(vars, self.get_host_vars(host))
  File "/usr/lib/python2.6/site-packages/ansible/inventory/__init__.py", line 653, in get_host_vars
    return self._get_hostgroup_vars(host=host, group=None, new_pb_basedir=new_pb_basedir)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/__init__.py", line 702, in _get_hostgroup_vars
    base_path = os.path.realpath(os.path.join(basedir, "host_vars/%s" % host.name))
  File "/usr/lib64/python2.6/posixpath.py", line 365, in realpath
    if islink(component):
  File "/usr/lib64/python2.6/posixpath.py", line 132, in islink
    st = os.lstat(path)
TypeError: lstat() argument 1 must be encoded string without NULL bytes, not str

**Comment by anthonygreen** [comment]
Bug persists in ansible 1.9.3

**Comment by jhawkesworth** [comment]
@jugalporwal , @anthonygreen 
Regarding the original reported problem, instead of 

   dest=D:\test\
try

  dest=D:/test/

The issue here is that \ on the end of a line has special meaning to YAML.  This is actually mentioned in the module documentation on this page: http://docs.ansible.com/ansible/win_copy_module.html 

I suspect that the problem described will also go away in v2 if you use / instead of \

Please could you reconfirm if using the syntax as advised fixes the problem?

Many thanks,

Jon

**Comment by jhawkesworth** [comment]
Incidentally if you are wondering how D:\test\ could be considered a valid path on windows, it turns out Powershell has supported \ as path separator for a long time.

**Comment by jugalporwal** [comment]
Hi @jhawkesworth . Thank you for replying on the thread. The above remark solved my problem.

**Comment by jhawkesworth** [comment]
@jugalporwal please can you close the issue then?

**Comment by jugalporwal** [comment]
Yes.
