### ISSUE TITLE
Authentication failed when delegating from windows to linux

### ISSUE THREAD

**Issue by t-v** [ansible/ansible#12370]
I run a playbook for new windows hosts that have to do certain things on on a linux host too.
(ex. check_mk config on our linux monitoring server)

So when I try to run this in a playbook:

``` yaml
 name: create host directory on share
  action: file
  args:
    path:  '{{ smb.path }}/windows/hosts/{{ ansible_hostname }}/'
    state: directory
  delegate_to: "{{ smb.host }}"
  sudo: yes
  tags: always
```

I get:

```
TASK: [win-tools | create host directory on share] **************************** 
<172.31.220.4> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO 172.31.220.4
fatal: [rt1802-acc-web1 -> admatriusy03] => {'msg': 'FAILED: Authentication failed.', 'failed': True}

FATAL: all hosts have already failed -- aborting
```

All my windows task work without any issues, but delegation to seems to give an authentication failed.

I also checked my groupvars and the windows-authentication is only defined as a groupvar only for those windows hosts and for all the linux things it should just take current user, like what happens when we run a linux-only playbook.

**Comment by cchurch** [comment]
May be related to #12347?

**Comment by t-v** [comment]
I'm not sure, but doubt it.
Especially since this only seems to happen when delegating from Windows to Linux systems.

Another thing I've noticed is that this issue already exists from 1.8.x since I've test runned it on all the different versions we had installed.

**Comment by t-v** [comment]
I am going to bump this issue, since it is currently really blocking for us.

> cat test.yml 

``` yaml
---

- hosts: acc-varnish01-atr
  tasks:
    - action: ping

- hosts: acc-rt1902-sta
  tasks:
    - action: win_ping

    - action: ping
      delegate_to: acc-varnish01-atr
```

And when I run this playbook, I get this:

```
PLAY [acc-varnish01-atr] ****************************************************** 

GATHERING FACTS *************************************************************** 
ok: [acc-varnish01-atr]

TASK: [ping] ****************************************************************** 
ok: [acc-varnish01-atr]

PLAY [acc-rt1902-sta] ********************************************************* 

GATHERING FACTS *************************************************************** 
ok: [acc-rt1902-sta]

TASK: [win_ping] ************************************************************** 
ok: [acc-rt1902-sta]

TASK: [ping] ****************************************************************** 
fatal: [acc-rt1902-sta -> acc-varnish01-atr] => to use the 'ssh' connection type with passwords, you must install the sshpass program

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/test.retry

acc-rt1902-sta             : ok=2    changed=0    unreachable=1    failed=0   
acc-varnish01-atr          : ok=2    changed=0    unreachable=0    failed=0 
```

I've also seen this error return in https://github.com/ansible/ansible/issues/3564 where the issue is closed but it seems it is still available.

so I tried to run it with the -c paramiko variable, but the result isn't getting any better.

```
PLAY [acc-varnish01-atr] ****************************************************** 

GATHERING FACTS *************************************************************** 
ok: [acc-varnish01-atr]

TASK: [ping] ****************************************************************** 
ok: [acc-varnish01-atr]

PLAY [acc-rt1902-sta] ********************************************************* 

GATHERING FACTS *************************************************************** 
ok: [acc-rt1902-sta]

TASK: [win_ping] ************************************************************** 
ok: [acc-rt1902-sta]

TASK: [ping] ****************************************************************** 
fatal: [acc-rt1902-sta -> acc-varnish01-atr] => {'msg': 'FAILED: Authentication failed.', 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/test.retry

acc-rt1902-sta             : ok=2    changed=0    unreachable=1    failed=0   
acc-varnish01-atr          : ok=2    changed=0    unreachable=0    failed=0  
```

**Comment by berlic** [comment]
Same here – Ansible 1.9.4 on Mac OS.
When delegate_to linux machine within windows playbook.

```
TASK: [icinga2-windows-config | Update host config on server] *****************
<192.168.168.205> ESTABLISH CONNECTION FOR USER: vagrant
fatal: [icinga2-windows -> icinga2-server] => to use the 'ssh' connection type with passwords, you must install the sshpass program
```

Same thing with linux-linux works ok.

Can't modify monitoring server configs because of this...

**Comment by t-v** [comment]
My assumption is that the main issue is that the windows hosts use a password for the connection and ansible is trying to use the same authentication for the delegation, but my linux hosts only have a key-based authentication, not a password-based one.

**Comment by t-v** [comment]
And maybe this helps, it's a copy for /var/log/secure:
 **The normal ping.**

```
Jan 12 14:41:33 acc-varnish01-atr sshd[995]: Accepted publickey for ansible from 172.31.220.209 port 33729 ssh2
Jan 12 14:41:33 acc-varnish01-atr sshd[995]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jan 12 14:41:33 acc-varnish01-atr sshd[998]: subsystem request for sftp
Jan 12 14:41:34 acc-varnish01-atr sshd[995]: pam_unix(sshd:session): session closed for user ansible
Jan 12 14:41:34 acc-varnish01-atr sshd[1070]: Accepted publickey for ansible from 172.31.220.209 port 33730 ssh2
Jan 12 14:41:34 acc-varnish01-atr sshd[1070]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jan 12 14:41:34 acc-varnish01-atr sshd[1073]: subsystem request for sftp
Jan 12 14:41:34 acc-varnish01-atr sshd[1070]: pam_unix(sshd:session): session closed for user ansible
```

**The ping through a delegation.**

```
Jan 12 14:41:40 acc-varnish01-atr sshd[1105]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=172.31.220.209  user=ansible
Jan 12 14:41:42 acc-varnish01-atr sshd[1105]: pam_sss(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=172.31.220.209 user=ansible
Jan 12 14:41:42 acc-varnish01-atr sshd[1105]: pam_sss(sshd:auth): received for user ansible: 8 (Insufficient credentials to access authentication data)
Jan 12 14:41:43 acc-varnish01-atr sshd[1105]: Failed password for ansible from 172.31.220.209 port 33833 ssh2
Jan 12 14:41:43 acc-varnish01-atr sshd[1106]: Connection closed by 172.31.220.209
Jan 12 14:41:44 acc-varnish01-atr sudo:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/varnishadm debug.health
```

**Comment by t-v** [comment]
and the output on the latest 2.0.0.1 which proves my assumption, it is using the windows group_vars or login info instead of the ones for the host I am trying to connect to.

```
TASK [ping] ********************************************************************
task path: /home/ansible/git/operations/werner/test.yml:11
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.venv/ansible-2.0.0.1/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/home/ansible/.venv/ansible-2.0.0.1/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/ansible/.venv/ansible-2.0.0.1/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 367, in _execute
    self._connection.set_host_overrides(host=self._host)
  File "/home/ansible/.venv/ansible-2.0.0.1/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 97, in set_host_overrides
    if '@' in self._winrm_user:
TypeError: argument of type 'NoneType' is not iterable

fatal: [acc-rt1903-sta]: FAILED! => {"failed": true, "stdout": ""}
```

**Comment by bcoca** [comment]
not really, Ansible will still go over the connection info for the 'delegated for' host.

**Comment by t-v** [comment]
Than why is it trying to connect to a linux host over winrm?
Because in the play, it 1st connects to the linux hosts, no problem there. But the moment I try to do the same action as a delegate, it fails.

**Comment by t-v** [comment]
_bump_
Since this issue is blocking our upgrade to ansible 2.0

Also, I have just tested the same playbook on the new version 2.0.0.2 and it gives the same error. This leads me to believe there is something fundamentally wrong in the code for delegation.
playbook:

``` yaml
- hosts: acc-varnish01-atr
  tasks:
    - action: ping

- hosts: acc-rt1903-sta
  tasks:
    - action: win_ping

    - action: ping
      delegate_to: acc-varnish01-atr
```

And this keeps giving the same error when being delegated:

```
TASK [ping] ********************************************************************
task path: /home/ansible/git/operations/werner-exh345/test.yml:11
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.venv/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/home/ansible/.venv/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/ansible/.venv/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 367, in _execute
    self._connection.set_host_overrides(host=self._host)
  File "/home/ansible/.venv/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 97, in set_host_overrides
    if '@' in self._winrm_user:
TypeError: argument of type 'NoneType' is not iterable

fatal: [acc-rt1903-sta]: FAILED! => {"failed": true, "stdout": ""}

PLAY RECAP *********************************************************************
acc-rt1903-sta             : ok=2    changed=0    unreachable=0    failed=1 
```

**Comment by t-v** [comment]
Also forgot to mention that https://github.com/ansible/ansible/issues/13561 fixed it in the older versions.

**Comment by t-v** [comment]
If it helps defining the problem, I noticed that this only happens when delegating from windows (winrm) to linux (ssh or paramiko)

hosts:

```
acc-rt1903-sta
acc-rt1903-web1
acc-varnish01-atr
acc-varnish02-blo

[win2012]
acc-rt1903-sta
acc-rt1903-web1
```

test.yml:

``` yaml
- hosts: acc-rt1903-sta:acc-varnish01-atr
  tasks:
    - action: win_ping
      when: inventory_hostname in groups['win2012']

    - action: ping
      when: inventory_hostname not in groups['win2012']

    - debug: var=ansible_connection
      delegate_to: acc-rt1903-web1

    - debug: var=ansible_connection
      delegate_to: acc-varnish02-blo
```

play:

```
> ansible-playbook -i accept/ test.yml -v
No config file found; using defaults

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [acc-varnish01-atr]
ok: [acc-rt1903-sta] => {"ansible_facts": {"ansible_architecture": "64-bit", "ansible_date_time": {"date": "2/26/2016", "day": "26", "hour": "11", "iso8601": "2016-02-26T11:05:23", "minute": "05", "month": "02", "year": "2016"}, "ansible_distribution": "Microsoft Windows NT 6.3.9600.0", "ansible_distribution_version": "6.3.9600.0", "ansible_fqdn": "acc-rt1903-sta.railtour.psop.be", "ansible_hostname": "ACC-RT1903-STA", "ansible_interfaces": [{"default_gateway": null, "dns_domain": null, "interface_index": 12, "interface_name": "Red Hat VirtIO Ethernet Adapter"}, {"default_gateway": "10.2.58.6", "dns_domain": null, "interface_index": 13, "interface_name": "Red Hat VirtIO Ethernet Adapter #2"}, {"default_gateway": null, "dns_domain": "psop.be", "interface_index": 14, "interface_name": "Red Hat VirtIO Ethernet Adapter #3"}], "ansible_ip_addresses": ["10.2.37.229", "fe80::e9bd:bebb:f6b8:a08a", "10.2.58.229", "fe80::a4e1:4f03:962f:94ac", "172.31.221.229", "fe80::8179:7ad3:a9da:3ce3"], "ansible_lastboot": "2016-02-26 09:23:53Z", "ansible_os_family": "Windows", "ansible_os_name": "Microsoft Windows Server 2012 R2 Datacenter", "ansible_powershell_version": 4, "ansible_system": "Win32NT", "ansible_totalmem": 17179443200, "ansible_uptime_seconds": 6090, "ansible_winrm_certificate_expires": "2016-12-09 10:16:38"}, "changed": false}

TASK [win_ping] ****************************************************************
skipping: [acc-varnish01-atr] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [acc-rt1903-sta] => {"changed": false, "ping": "pong"}

TASK [ping] ********************************************************************
skipping: [acc-rt1903-sta] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [acc-varnish01-atr] => {"changed": false, "ping": "pong"}

TASK [debug] *******************************************************************
ok: [acc-rt1903-sta -> acc-rt1903-web1] => {
    "ansible_connection": "winrm"
}
ok: [acc-varnish01-atr -> acc-rt1903-web1] => {
    "ansible_connection": "winrm"
}

TASK [debug] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'NoneType' is not iterable
fatal: [acc-rt1903-sta]: FAILED! => {"failed": true, "stdout": ""}
ok: [acc-varnish01-atr -> acc-varnish02-blo] => {
    "ansible_connection": "ssh"
}

PLAY RECAP *********************************************************************
acc-rt1903-sta             : ok=3    changed=0    unreachable=0    failed=1   
acc-varnish01-atr          : ok=4    changed=0    unreachable=0    failed=0 
```

**Comment by t-v** [comment]
ok, I just upgraded to ansible 2.0.1 which seems to force debug to be a local action, this allowed me to debug the connection variables on delegation.

This is my test playbook.

```
(ansible-2.0.1.0)ansible@adm-in-blo ~/git/operations/werner-exh345 release/2.0 ✖ 
> cat test.yml 
---

- hosts: acc-rt1903-sta:acc-varnish01-atr
  tasks:
    - name: test win_ping to windows host
      action: win_ping
      when: inventory_hostname in groups['win2012']

    - name: test ping to linux host
      action: ping
      when: inventory_hostname not in groups['win2012']

    - debug: var=ansible_connection
      delegate_to: acc-rt1903-web1

    - debug: var=ansible_connection
      delegate_to: acc-varnish02-blo

    - name: win_ping when windows
      action: win_ping
      delegate_to: acc-rt1903-web1
      when: inventory_hostname in groups['win2012']

    - name: win_ping when linux
      action: win_ping
      delegate_to: acc-rt1903-web1
      when: inventory_hostname not in groups['win2012']

    - name: ping when linux
      action: ping
      delegate_to: acc-varnish02-blo
      when: inventory_hostname not in groups['win2012']

    - name: ping when windows
      action: ping
      delegate_to: acc-varnish02-blo
      when: inventory_hostname in groups['win2012']
```

And this is the result of my play:

```
(ansible-2.0.1.0)ansible@adm-in-blo ~/git/operations/werner-exh345 release/2.0 ✖ 
> ansible-playbook -i accept/ test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [acc-varnish01-atr]
ok: [acc-rt1903-sta]

TASK [test win_ping to windows host] *******************************************
skipping: [acc-varnish01-atr]
ok: [acc-rt1903-sta]

TASK [test ping to linux host] *************************************************
skipping: [acc-rt1903-sta]
ok: [acc-varnish01-atr]

TASK [debug] *******************************************************************
ok: [acc-rt1903-sta -> acc-rt1903-web1] => {
    "ansible_connection": "winrm"
}
ok: [acc-varnish01-atr -> acc-rt1903-web1] => {
    "ansible_connection": "winrm"
}

TASK [debug] *******************************************************************
ok: [acc-rt1903-sta -> acc-varnish02-blo] => {
    "ansible_connection": "winrm"
}
ok: [acc-varnish01-atr -> acc-varnish02-blo] => {
    "ansible_connection": "ssh"
}

TASK [win_ping when windows] ***************************************************
skipping: [acc-varnish01-atr]
ok: [acc-rt1903-sta -> acc-rt1903-web1]

TASK [win_ping when linux] *****************************************************
skipping: [acc-rt1903-sta]
ok: [acc-varnish01-atr -> acc-rt1903-web1]

TASK [ping when linux] *********************************************************
skipping: [acc-rt1903-sta]
ok: [acc-varnish01-atr -> acc-varnish02-blo]

TASK [ping when windows] *******************************************************
skipping: [acc-varnish01-atr]
fatal: [acc-rt1903-sta]: FAILED! => {"failed": true, "msg": "ssl: 500 WinRMTransport. [Errno 111] Connection refused"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
acc-rt1903-sta             : ok=5    changed=0    unreachable=0    failed=1   
acc-varnish01-atr          : ok=6    changed=0    unreachable=0    failed=0  
```

So as you can see, it only fails when delegating from a windows to a default linux host.
Also when outputting the 'ansible_connection' variable, we can see that the connection, when delegating from a windows or a linux host to a windows host always is winrm. But when delegating from a windows host to a linux host, it does use winrm instead of ssh. This makes me assume there might be something wrong in managing the variables.

**Comment by t-v** [comment]
Closed because of a better documented issue:
https://github.com/ansible/ansible/issues/14677
