### ISSUE TITLE
quantum_router attempts to hit wrong auth url

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible#12443]
When I attempt to create a new router using quantum_router, I get the following error:

```
TASK: [prep_tenant | Create a router] *****************************************
<localhost> REMOTE_MODULE quantum_router name=iotsprouter
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279 && echo $HOME/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279']
<localhost> PUT /var/folders/25/9g455r414513s9bhl85qg3vm0000gn/T/tmpstcU9d TO /Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 ./venv/bin/python /Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router']
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router", line 1916, in <module>
    main()
  File "/Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router", line 188, in main
    _set_tenant_id(module)
  File "/Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router", line 137, in _set_tenant_id
    for tenant in _os_keystone.tenants.list():
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/v2_0/tenants.py", line 123, in list
    tenant_list = self._list('/tenants%s' % query, 'tenants')
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/base.py", line 113, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/adapter.py", line 170, in get
    return self.request(url, 'GET', **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/adapter.py", line 206, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/adapter.py", line 95, in request
    return self.session.request(url, method, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/utils.py", line 336, in inner
    return func(*args, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/session.py", line 382, in request
    resp = send(**kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/session.py", line 426, in _send_request
    raise exceptions.ConnectionRefused(msg)
keystoneclient.openstack.common.apiclient.exceptions.ConnectionRefused: Unable to establish connection to https://int.us-internal-1.cloud.cisco.com:35357/v2.0/tenants

FATAL: all hosts have already failed -- aborting
```

Inside ~/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router, I see the following lines, indicating that it has picked up the correct value from $OS_AUTH_URL:

```
MODULE_ARGS = "login_username=davcrame login_password='XXXXX' auth_url=https://us-internal-1.cloud.cisco.com:5000/v2.0 login_tenant_name=iotsp-internal-us-internal-1 tenant_name=iotsp-internal-us-internal-1 name=iotsprouter "
```

Why does it try to connect to https://int.us-internal-1.cloud.cisco.com:35357/v2.0/tenants? I have no idea where it has gotten that url.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
