### ISSUE TITLE
Handle stray characters better

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#12478]
Ansible 2.0 devel branch

In a playbook I had a stray "-" on its own line and instead of a nice error I got the following crash:

``````
Traceback (most recent call last):
  File "/Usersxxxx/Dropbox (Seatgeek)/ansible/bin/ansible-playbook", line 79, in <module>
    sys.exit(cli.run())
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/cli/playbook.py", line 138, in run
    results = pbex.run()
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/executor/playbook_executor.py", line 74, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/__init__.py", line 53, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/__init__.py", line 91, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/play.py", line 110, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/base.py", line 188, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/play.py", line 196, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/role/__init__.py", line 115, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/role/__init__.py", line 178, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/helpers.py", line 51, in load_list_of_blocks
    loader=loader
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/block.py", line 72, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/xxxx/Dropbox (Seatgeek)/ansible/lib/ansible/playbook/base.py", line 160, in load_data
    assert ds is not None
AssertionError``` 

This should be handled better, I think so the user knows what to look for.
``````

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
