### ISSUE TITLE
TypeError: build_module_command() got an unexpected keyword argument 'arg_path'

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#12616]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0 (devel a1f6de8745) last updated 2015/10/02 16:19:12 (GMT -500)
  lib/ansible/modules/core: (detached HEAD dbc860daaa) last updated 2015/10/02 16:19:12 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 9f5420e459) last updated 2015/10/02 16:19:12 (GMT -500)
  config file = /Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

$ source hacking/env-setup

```

---
# file: windows-workstations.yml

- hosts: windows-workstations
  vars:
  pre_tasks:
  roles:
    - { role: windows-workstations }
  tasks:
    - name: Ping? Pong?
      action: 
          win_ping
      tags: 
          - ping
  post_tasks:
```
##### Environment:

OS X Yosemite 10.10.5

$ python -V
Python 2.7.6
##### Summary:

TASK [setup] fails with TypeError: build_module_command() got an unexpected keyword argument 'arg_path'
##### Steps To Reproduce:

But the IP address of your favorite Windows computer into testing.

group_vars/windows-workstations

```
ansible_ssh_user: Administrator
ansible_ssh_pass: SuperSecrectPasswordHere
ansible_ssh_port: 5986
ansible_connection: winrm
```

```
$ ansible-playbook -i testing windows-workstations.yml --tag=ping --ask-vault-pass -vvvv
1 plays in windows-workstations.yml
Loaded callback default of type stdout, v2.0

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<reporter.testing.real-time.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO reporter.testing.real-time.com
<reporter.testing.real-time.com> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1443822499.12-261399832152565").FullName | Write-Host -Separator '';
<reporter.testing.real-time.com> PUT "/var/folders/d_/bm7rvz154jb_2djkqybb503h0000gp/T/tmpeptiuY" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1443822499.12-261399832152565\setup"
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py", line 343, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/normal.py", line 26, in run
    results = self._execute_module(tmp=tmp, task_vars=task_vars)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/__init__.py", line 409, in _execute_module
    cmd = self._connection._shell.build_module_command(environment_string, shebang, cmd, arg_path=args_file_path, rm_tmp=rm_tmp)
TypeError: build_module_command() got an unexpected keyword argument 'arg_path'

fatal: [reporter.testing.real-time.com]: FAILED! => {"failed": true, "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
```
##### Expected Results:

Ping? Pong? Would return results.

**Comment by abadger** [comment]
Thanks for reporting this!  It was a typo in a change from earlier today.  Fixed here:
https://github.com/ansible/ansible/commit/613e87db6c9e83c604157ab96d8b8be5c814b042

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
