### ISSUE TITLE
[ansible 1.9.3] docker module error - UnboundLocalError: local variable 'bind' referenced before assignment

### ISSUE THREAD

**Issue by hrstoyanov** [ansible/ansible#12625]
This code:

```
- hosts: web
  tasks:
      - name: Launch Wildfly container
        docker:
          name: "{{wfsv_container_app_name}}"
          image: "{{wfsv_image_tag}}"
          state: reloaded
          ports: "{{wf_ports|default('-p 8080:8080 -p 9999:9999')}}"
          links:
            - "{{pgdb_container_app_name}}:{{pg_alias}}" 
          volumes_from:
            - "{{pgdb_container_data_name}}"
```

is causing this error:

```
TASK: [Launch Wildfly container] ********************************************** 
<localhost> REMOTE_MODULE docker ports='-p 9876:9876 -p 8080:8080 -p 9990:9990 -p 10010:10010' state=reloaded image=peruncs/wfsv_dev name=wfsv_app_dev
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087 && echo $HOME/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087']
<localhost> PUT /tmp/tmpRF_b7m TO /home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/docker
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/docker; rm -rf /home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/docker", line 3185, in <module>
    main()
  File "/home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/docker", line 1513, in main
    manager = DockerManager(module)
  File "/home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/docker", line 550, in __init__
    self.port_bindings = self.get_port_bindings(self.module.params.get('ports'))
  File "/home/hristo/.ansible/tmp/ansible-tmp-1443921607.03-149917801274087/docker", line 797, in get_port_bindings
    binds[container_port] = bind
UnboundLocalError: local variable 'bind' referenced before assignment


FATAL: all hosts have already failed -- aborting
```

The issue seems to be with this line:

```
ports: "{{wf_ports|default('-p 8080:8080 -p 9999:9999')}}"
```

I should mention that wf_ports is coming from an inventory file and the playbook is launched as:

```
ansible-playbook start-devenv.yml -i dev
```

This does not work either:

```
ports: "-p 8080:8080 -p 9999:9999 -p 10010:10010"
```

I am using the latest release version of the docker-py as of October 3rd

**Comment by hrstoyanov** [comment]
Looks like this fixes, but better explanation is welcome:
```
   #ports: "{{wf_ports|default('-p 8080:8080 -p 9999:9999')}}"
     ports: "-p 8080:8080 -p 9999:9999"
```

**Comment by kswope** [comment]
I'm getting this very issue, why was this closed?

Nevermind, my input argument for the ip address had a newline in it.

Docker is probably returning 

```
docker: Invalid ip address
```

And that results in this unhelpful message from ansible 

```
UnboundLocalError: local variable 'bind' referenced before assignment
```

**Comment by hrstoyanov** [comment]
I saw a = in my valuable file instead of :

A better error message would have been nice, but it was my mistake
