### ISSUE TITLE
Playbooks issue.

### ISSUE THREAD

**Issue by mraczdrekuga** [ansible/ansible#12680]
Hi there, after changing my linux distribution from debian to arch i've got little issue to run playbooks. When ansbile was installed by pacman i have error like:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 103, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 440, in _load_roles
    roles = self._build_role_dependencies(roles, [], {})
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 282, in _build_role_dependencies
    dependencies = data.get('dependencies',[])
AttributeError: 'list' object has no attribute 'get'
```

But when I uninstall package by pacman and install by pip I've got:

```
  File "/usr/bin/ansible-playbook", line 218
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'
```

On this same playbooks...
Version of ansible is 1.9.3 in both cases.
Version of python is:

```
 > sudo pacman -Q python 
python 3.4.3-3
 > sudo pacman -Q python2
python2 2.7.10-2
```

Many thanks for help.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
