### ISSUE TITLE
[v2] cannot handle modules that set non-string facts

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12709]
**Issue Type**: Bug Report
**Ansible Version**:

```
ansible 2.0.0 (devel eb60ce1b6e) last updated 2015/10/12 09:17:27 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 92d25017ed) last updated 2015/10/12 09:17:45 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 205115ea1f) last updated 2015/10/12 09:17:45 (GMT +300)
```

**Summary**: when a custom module returns `ansible_facts` with non-string values, Ansible 2 fails.

**Steps to Reproduce**
- enable fact caching in ansible.cfg:

``` ini
[defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = .cache/facts/
fact_caching_timeout = 86400
```
- create a custom module `library/mymodule.py`

``` python
#!/usr/bin/env python


def main():
    module = AnsibleModule(
        argument_spec=dict(),
    )
    module.exit_json(
        message="bye",
        ansible_facts=dict(
            somebool=True,
        )
    )


from ansible.module_utils.basic import *  # noqa


if __name__ == '__main__':
    main()
```
- create a playbook

``` yaml
- hosts: localhost
  tasks:
    - mymodule:
```
- run `ansible-playbook test.yml -vvv`

**Expected Results**:

```
PLAY ***************************************************************************

TASK [set_fact wtf=true] *******************************************************
ok: [localhost -> localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Actual Results**:

```
PLAY ***************************************************************************

TASK [mymodule] ****************************************************************
Unexpected Exception: expected string or buffer
to see the full traceback, use -vvv
```

with `-vvv`:

```
1 plays in test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: mg
127.0.0.1 EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1444639409.83-191416103850701)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1444639409.83-191416103850701)")
127.0.0.1 PUT /tmp/tmpTLtKpY TO /home/mg/.ansible/tmp/ansible-tmp-1444639409.83-191416103850701/setup
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/mg/.venv/bin/python /home/mg/.ansible/tmp/ansible-tmp-1444639409.83-191416103850701/setup; rm -rf "/home/mg/.ansible/tmp/ansible-tmp-1444639409.83-191416103850701/" > /dev/null 2>&1
ok: [localhost -> localhost]

TASK [mymodule] ****************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: mg
127.0.0.1 EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1444639410.55-67769449678699)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1444639410.55-67769449678699)")
127.0.0.1 PUT /tmp/tmpnyo2Gq TO /home/mg/.ansible/tmp/ansible-tmp-1444639410.55-67769449678699/mymodule
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/env python /home/mg/.ansible/tmp/ansible-tmp-1444639410.55-67769449678699/mymodule; rm -rf "/home/mg/.ansible/tmp/ansible-tmp-1444639410.55-67769449678699/" > /dev/null 2>&1
Unexpected Exception: expected string or buffer
the full traceback was:

Traceback (most recent call last):
  File "/home/mg/src/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/home/mg/src/ansible/lib/ansible/cli/playbook.py", line 138, in run
    results = pbex.run()
  File "/home/mg/src/ansible/lib/ansible/executor/playbook_executor.py", line 137, in run
    result = self._tqm.run(play=play)
  File "/home/mg/src/ansible/lib/ansible/executor/task_queue_manager.py", line 217, in run
    return strategy.run(iterator, play_context)
  File "/home/mg/src/ansible/lib/ansible/plugins/strategy/linear.py", line 252, in run
    results = self._wait_on_pending_results(iterator)
  File "/home/mg/src/ansible/lib/ansible/plugins/strategy/__init__.py", line 303, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/home/mg/src/ansible/lib/ansible/plugins/strategy/__init__.py", line 284, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, facts)
  File "/home/mg/src/ansible/lib/ansible/vars/__init__.py", line 550, in set_host_facts
    self._fact_cache.update(host.name, facts)
  File "/home/mg/src/ansible/lib/ansible/plugins/cache/__init__.py", line 75, in update
    self._plugin.set(key, host_cache)
  File "/home/mg/src/ansible/lib/ansible/plugins/cache/jsonfile.py", line 88, in set
    f.write(jsonify(value))
  File "/home/mg/src/ansible/lib/ansible/parsing/utils/jsonify.py", line 42, in jsonify
    return json.dumps(result2, sort_keys=True, indent=indent, ensure_ascii=False)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
  File "/usr/lib/python2.7/json/encoder.py", line 39, in encode_basestring
    return '"' + ESCAPE.sub(replace, s) + '"'
TypeError: expected string or buffer
```

Note: this failure leaves a broken cache file, which triggers bug #12708, so be sure to `rm -rf .cache` before you repeat the reproduction steps.

**Comment by mgedmin** [comment]
git bisect blames commit 01ba2e94c0fad51e13d5d7c4bf0bb36bfa2cffb5 for this bug.

**Comment by jimi-c** [comment]
Should be fixed by cd2cb178aeb799efe4aba36f93d48c95f6da3b61, just waiting for a little burn-in due to the major change involved in that commit.

**Comment by mgedmin** [comment]
Confirming that the bug looks fixed from over here too.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
