### ISSUE TITLE
[v2] error while trying to read .cache/facts// : [Errno 21] Is a directory: u'.cache/facts//'

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12722]
**Issue Type**: Bug Report
**Ansible Version**:
ansible 2.0.0 (devel 8277747a04) last updated 2015/10/13 08:59:15 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 92d25017ed) last updated 2015/10/12 09:17:45 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 205115ea1f) last updated 2015/10/12 09:17:45 (GMT +300)

**Summary**:
I've a set of tasks that generate an SSH keypair on host A, then install the public key on host B.  The tasks look like this:

```
- name: ssh private key for cloning repos
  user: name=jenkins-slave generate_ssh_key=yes
  when: jenkins_install_key_on != ""
  tags: [ jenkins, ssh ]

- name: get the ssh public key
  command: cat /var/lib/jenkins-slave/.ssh/id_rsa.pub
  register: pubkey_result
  changed_when: false
  always_run: yes
  when: jenkins_install_key_on != ""
  tags: [ jenkins, ssh ]

- name: install ssh public key
  authorized_key: key="{{ pubkey_result.stdout }}" user="{{ jenkins_install_key_for }}" state=present
  delegate_to: "{{ jenkins_install_key_on }}"
  when: jenkins_install_key_on != ""
  tags: [ jenkins, ssh ]
```

The last task fails on Ansible v2:

```
TASK [jenkins-worker : ssh private key for cloning repos] **********************
skipping: [precise] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [trusty] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [jenkins-worker : get the ssh public key] *********************************
skipping: [precise] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [trusty] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
 [WARNING]: error while trying to read .cache/facts// : [Errno 21] Is a directory: u'.cache/facts//'

Unexpected Exception: local variable 'f' referenced before assignment
the full traceback was:

Traceback (most recent call last):
  File "/home/mg/src/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/home/mg/src/ansible/lib/ansible/cli/playbook.py", line 138, in run
    results = pbex.run()
  File "/home/mg/src/ansible/lib/ansible/executor/playbook_executor.py", line 137, in run
    result = self._tqm.run(play=play)
  File "/home/mg/src/ansible/lib/ansible/executor/task_queue_manager.py", line 217, in run
    return strategy.run(iterator, play_context)
  File "/home/mg/src/ansible/lib/ansible/plugins/strategy/linear.py", line 214, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/home/mg/src/ansible/lib/ansible/vars/__init__.py", line 316, in get_vars
    all_vars['ansible_delegated_vars'] = self._get_delegated_vars(loader, play, task, all_vars)
  File "/home/mg/src/ansible/lib/ansible/vars/__init__.py", line 446, in _get_delegated_vars
    include_hostvars=False,
  File "/home/mg/src/ansible/lib/ansible/vars/__init__.py", line 246, in get_vars
    host_facts = wrap_var(self._fact_cache.get(host.name, dict()))
  File "/home/mg/.venv/lib/python2.7/_abcoll.py", line 382, in get
    return self[key]
  File "/home/mg/src/ansible/lib/ansible/plugins/cache/__init__.py", line 45, in __getitem__
    return self._plugin.get(key)
  File "/home/mg/src/ansible/lib/ansible/plugins/cache/jsonfile.py", line 76, in get
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
```

It seems to me that there are two errors here:
1. Getting the host name wrong (EDIT: no; the bug is not skipping cache loading when the task is skipped)
2. UnboundLocalError in the error handling.

Let's focus on the error handling bug first.

**Comment by mgedmin** [comment]
**Steps to Reproduce**
- enable fact caching in `ansible.cfg`:

``` ini
[defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = .cache/facts/
fact_caching_timeout = 86400
```
- create a playbook that conditionally runs a delegated task

``` yaml
# test.yml
- hosts: localhost
  vars:
    there: ""
  tasks:
    - command: echo hi
      delegate_to: "{{ there }}"
      when: there != ""
```
- run `ansible-playbook test.yml`

**Excpected Results**

```
PLAY [localhost] ************************************************************** 

TASK: [command echo hi] ******************************************************* 
skipping: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

**Actual Results**

```
PLAY ***************************************************************************
 [WARNING]: error while trying to read .cache/facts// : [Errno 21] Is a directory: u'.cache/facts//'

Unexpected Exception: local variable 'f' referenced before assignment
to see the full traceback, use -vvv
```

**Comment by mgedmin** [comment]
git bisect blames commit 1f5584aa5b9d1142e67fed209bbeea1ca99fc307

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
