### ISSUE TITLE
Uncatched traceback running cowsay

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#12773]
It seems cowsay is now ran at each cli invocation, but if womething is wrong with the installation of cowsay, there's an uncatched traceback.

```
$ ansible --version
Unexpected Exception: [Errno 13] Permission denied
the full traceback was:

Traceback (most recent call last):
  File "/home/serge/src/ansible/ansible/bin/ansible", line 62, in <module>
    display = Display()
  File "/home/serge/src/ansible/ansible/lib/ansible/utils/display.py", line 84, in __init__
    cmd = subprocess.Popen([self.cowsay, "-l"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

tested with 174ecb8

The issue causing the error is an old install of `cowsay` which happened to have it's binary not executeable:
`-rw-r--r-- 1 root root 203539 Aug 19  2014 /usr/bin/cowsay`

This by itself is not an ansible problem of course, but I wanted to just report the "ugly" traceback that is not catched here.

**Comment by bcoca** [comment]
this should fix that

```
diff --git a/lib/ansible/utils/display.py b/lib/ansible/utils/display.py
index c91f4f8..e4bc923 100644
--- a/lib/ansible/utils/display.py
+++ b/lib/ansible/utils/display.py
@@ -81,9 +81,13 @@ class Display:
         self.set_cowsay_info()

         if self.cowsay:
-            cmd = subprocess.Popen([self.cowsay, "-l"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
-            (out, err) = cmd.communicate()
-            self.cows_available = list(set(C.ANSIBLE_COW_WHITELIST).intersection(out.split()))
+            try:
+                cmd = subprocess.Popen([self.cowsay, "-l"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+                (out, err) = cmd.communicate()
+                self.cows_available = list(set(C.ANSIBLE_COW_WHITELIST).intersection(out.split()))
+            except:
+                # could not execute cowsay for some reason
+                self.cowsay = False

         self._set_column_width()
```
