### ISSUE TITLE
[v2] Playbook stuck after setup with strategy free and tags

### ISSUE THREAD

**Issue by Lowess** [ansible/ansible#12784]
##### Issue Type:
- Bug Report
##### Ansible Version:

``` bash
ansible-playbook 2.0.0 (devel 38b99a7a4d) last updated 2015/10/16 07:45:42 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 84b1a1a2b7) last updated 2015/10/15 08:31:49 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 8ce3104bc5) last updated 2015/10/15 08:31:49 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

EC2 dynamic inventory.
##### Environment:

Ubuntu 14.04, Python 2.7.6, Boto 2.38.0
##### Summary:

I am using a really simple playbook to test the `strategy: free` feature. When the playbook is used with the `-t (--tags)` option, it gets stuck after the setup step.

+Example:+

``` yaml
### strategy.yaml
- hosts: all
  become: yes
  strategy: free

  tasks:
    - debug:
        msg: "You will not see me when used with ansible-playbook -t debug"
      tags: debug
```

When I run the playbook without tags it works fine:

``` bash
ansible-playbook strategy.yaml -l tag_Name_somehost
```

Output:

``` bash
PLAY ***************************************************************************

TASK [setup] *******************************************************************

TASK [setup] *******************************************************************
ok: [172.30.x.xxx -> localhost]
ok: [172.30.x.xxx -> localhost]

TASK [debug msg=You will not see me when used with tags] ***********************

TASK [debug msg=You will not see me when used with tags] ***********************
ok: [172.30.x.xxx -> localhost] => {
    "changed": false, 
    "msg": "You will not see me when used with tags"
}
ok: [172.30.x.xxx -> localhost] => {
    "changed": false, 
    "msg": "You will not see me when used with tags"
}

PLAY RECAP *********************************************************************
172.30.x.xxx               : ok=2    changed=0    unreachable=0    failed=0   
172.30.x.xxx               : ok=2    changed=0    unreachable=0    failed=0   
```

Now with the `-t debug` option:

``` bash
ansible-playbook strategy.yaml -t debug -l tag_Name_somehost
```

Output:

``` bash

PLAY ***************************************************************************

TASK [setup] *******************************************************************

TASK [setup] *******************************************************************
ok: [172.30.1.109 -> localhost]
ok: [172.30.1.110 -> localhost]
...
> This is hanging here until you CTRL+C which gives:
^CProcess WorkerProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process WorkerProcess-3:
Process WorkerProcess-1:
Traceback (most recent call last):
Process WorkerProcess-2:
Process WorkerProcess-5:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/opt/ansible/lib/ansible/executor/process/worker.py", line 100, in run
    (host, task, basedir, job_vars, play_context, shared_loader_obj) = self._main_q.get()
Traceback (most recent call last):
  File "/opt/ansible/lib/ansible/executor/process/worker.py", line 100, in run
    (host, task, basedir, job_vars, play_context, shared_loader_obj) = self._main_q.get()
  File "/opt/ansible/lib/ansible/executor/process/worker.py", line 100, in run
    (host, task, basedir, job_vars, play_context, shared_loader_obj) = self._main_q.get()
  File "/opt/ansible/lib/ansible/executor/process/worker.py", line 100, in run
    (host, task, basedir, job_vars, play_context, shared_loader_obj) = self._main_q.get()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/opt/ansible/lib/ansible/executor/process/worker.py", line 100, in run
    (host, task, basedir, job_vars, play_context, shared_loader_obj) = self._main_q.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    res = self._recv()
KeyboardInterrupt
```
##### Steps To Reproduce:

Run the above playbook.
##### Expected Results:

It should run tasks / roles that are set  with the corresponding tag.
##### Actual Results:

The playbook is getting stuck after the setup task.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Lowess** [comment]
Thank you for the quick fix! I tested it and it worked fine.
