### ISSUE TITLE
problem with './plugins/inventory/ec2.py --list' 

### ISSUE THREAD

**Issue by SirkoMann** [ansible/ansible#1280]
I try to use the ec2 plugin but it seems to not work. :(

``` bash
root@alpha:~/ansible# ./plugins/inventory/ec2.py --list
Traceback (most recent call last):
  File "./plugins/inventory/ec2.py", line 404, in <module>
    Ec2Inventory()
  File "./plugins/inventory/ec2.py", line 144, in __init__
    self.do_api_calls_update_cache()
  File "./plugins/inventory/ec2.py", line 228, in do_api_calls_update_cache
    self.get_instances_by_region(region)
  File "./plugins/inventory/ec2.py", line 247, in get_instances_by_region
    self.add_instance(instance, region)
  File "./plugins/inventory/ec2.py", line 295, in add_instance
    for group in instance.groups:
AttributeError: 'Instance' object has no attribute 'groups'
root@alpha:~/ansible#
```

**Comment by mpdehaan** [comment]
@SirkoMann -- are you using the development branch?

@cocoy @pas256 I know you guys use this one, can you help @SirkoMann ?

**Comment by SirkoMann** [comment]
@mpdehaan yes I'm on the dev branch

``` bash
root@alpha:~/ansible# git status
# On branch devel
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   hacking/env-setup
#   modified:   plugins/inventory/ec2.ini
#   modified:   plugins/inventory/ec2.py
#
no changes added to commit (use "git add" and/or "git commit -a")
root@alpha:~/ansible# 
```

**Comment by cocoy** [comment]
What is the content of your ec2.ini? 
Could you test first the defaults. i.e. without modifying the ec2.ini and ec2.py

My test on newly cloned git repo,  this is working.

**Comment by SirkoMann** [comment]
@cocoy Tried this with the default files

``` bash
root@alpha:~/ansible# git checkout plugins/inventory/ec2.ini
root@alpha:~/ansible# git checkout plugins/inventory/ec2.py
root@alpha:~/ansible# git status
# On branch devel
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   hacking/env-setup
#
no changes added to commit (use "git add" and/or "git commit -a")
root@alpha:~/ansible# ./plugins/inventory/ec2.py --host ec2-184-73-120-129.compute-1.amazonaws.com
Traceback (most recent call last):
  File "./plugins/inventory/ec2.py", line 404, in <module>
    Ec2Inventory()
  File "./plugins/inventory/ec2.py", line 144, in __init__
    self.do_api_calls_update_cache()
  File "./plugins/inventory/ec2.py", line 228, in do_api_calls_update_cache
    self.get_instances_by_region(region)
  File "./plugins/inventory/ec2.py", line 247, in get_instances_by_region
    self.add_instance(instance, region)
  File "./plugins/inventory/ec2.py", line 295, in add_instance
    for group in instance.groups:
AttributeError: 'Instance' object has no attribute 'groups'
root@alpha:~/ansible# 
```

**Comment by pas256** [comment]
That is a really strange error. It would imply you have an EC2 instance that is not in any security groups, which as far as I know is not possible. Can you confirm this is the case?

**Comment by pas256** [comment]
You can also try running `ec2.py` with any arguments to see if it will successfully list all of your instances.

```
./plugins/inventory/ec2.py
```

**Comment by SirkoMann** [comment]
@pas256 I tried both suggestions you made, but:
The instances all got security groups assigned. Without this wont work. At least the 'default' security group to _every_ running instance if you don't change this to another security group.

``` bash
root@alpha:~/ansible# ./plugins/inventory/ec2.py 
Traceback (most recent call last):
  File "./plugins/inventory/ec2.py", line 404, in <module>
    Ec2Inventory()
  File "./plugins/inventory/ec2.py", line 144, in __init__
    self.do_api_calls_update_cache()
  File "./plugins/inventory/ec2.py", line 228, in do_api_calls_update_cache
    self.get_instances_by_region(region)
  File "./plugins/inventory/ec2.py", line 247, in get_instances_by_region
    self.add_instance(instance, region)
  File "./plugins/inventory/ec2.py", line 295, in add_instance
    for group in instance.groups:
AttributeError: 'Instance' object has no attribute 'groups'
root@alpha:~/ansible# ./plugins/inventory/ec2.py --list
Traceback (most recent call last):
  File "./plugins/inventory/ec2.py", line 404, in <module>
    Ec2Inventory()
  File "./plugins/inventory/ec2.py", line 144, in __init__
    self.do_api_calls_update_cache()
  File "./plugins/inventory/ec2.py", line 228, in do_api_calls_update_cache
    self.get_instances_by_region(region)
  File "./plugins/inventory/ec2.py", line 247, in get_instances_by_region
    self.add_instance(instance, region)
  File "./plugins/inventory/ec2.py", line 295, in add_instance
    for group in instance.groups:
AttributeError: 'Instance' object has no attribute 'groups'
root@alpha:~/ansible# 
```

**Comment by cocoy** [comment]
What is the version of boto you are using? I believe ec2.py depends on this library. I'm using ver 2.5.2

**Comment by SirkoMann** [comment]
@cocoy It's deployed on a debian squeeze box.

``` bash
root@alpha:~/ansible# aptitude show python-boto
Package: python-boto                     
State: installed
Automatically installed: no
Version: 1.9b-4
Priority: optional
Section: python
Maintainer: Eric Evans <eevans@debian.org>
Uncompressed Size: 1,430 k
Depends: python (>= 2.5), python-support (>= 0.90.0)
Provides: python2.5-boto, python2.6-boto
Description: Python interface to Amazon's Web Services
 Boto is a Python interface to the infrastructure services available from Amazon. 

 Boto supports the following services: 
 * Elastic Compute Cloud (EC2) 
 * SimpleDB 
 * Simple Storage Service (S3) 
 * CloudFront 
 * Simple Queue Service (SQS) 
 * Elastic MapReduce 
 * Relational Database Service (RDS)
Homepage: http://code.google.com/p/boto/

root@alpha:~/ansible# 
```

**Comment by cocoy** [comment]
Ok, I see. That version of boto is a bit older, which does not contain the groups attribute for instance. 
Please see the boto 1.9 docs. I suggest upgrade to a higher version of boto.

**Comment by SirkoMann** [comment]
@cocoy Thanks for your help. I will try this and let you know how the things goes.

**Comment by mpdehaan** [comment]
If it is possible to check the version of boto prior to running, this seems
like a helpful thing to do in the inventory script, such that we don't get
this question too many times :)

Can you guys make that happen?

Thanks!

**Comment by cocoy** [comment]
@mpdehaan  I will try to send a fix :)

**Comment by SirkoMann** [comment]
I upgraded to a newer version of boto and now all is working well. Thanks for your help.
