### ISSUE TITLE
[v2] Prompt call generates unhandled exception in step mode

### ISSUE THREAD

**Issue by bcsontos** [ansible/ansible#12833]
ansible-playbook dies with an unhandled exception when being run in step mode. Full output with traceback:

```
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yaml

PLAY ***************************************************************************
Unexpected Exception: prompt() takes exactly 2 arguments (1 given)
the full traceback was:

Traceback (most recent call last):
  File "/opt/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/opt/ansible/lib/ansible/cli/playbook.py", line 142, in run
    results = pbex.run()
  File "/opt/ansible/lib/ansible/executor/playbook_executor.py", line 140, in run
    result = self._tqm.run(play=play)
  File "/opt/ansible/lib/ansible/executor/task_queue_manager.py", line 217, in run
    return strategy.run(iterator, play_context)
  File "/opt/ansible/lib/ansible/plugins/strategy/linear.py", line 207, in run
    if self._take_step(task):
  File "/opt/ansible/lib/ansible/plugins/strategy/__init__.py", line 541, in _take_step
    resp = self._display.prompt(msg)
TypeError: prompt() takes exactly 2 arguments (1 given)
```

**Comment by bcoca** [comment]
can you give minimal example that triggers this?
