### ISSUE TITLE
Include tasks is broken in devel, while works with 1.9.4

### ISSUE THREAD

**Issue by bborysenko** [ansible/ansible#12837]
##### Issue Type:

Bug Report
##### Ansible Version:

```
➜ ansible --version
ansible 2.0.0 (devel a22cf8ffc1) last updated 2015/10/20 09:40:47 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 49ee5dd443) last updated 2015/10/19 23:32:48 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 6c0765f48f) last updated 2015/10/19 23:33:04 (GMT +300)
  config file =
  configured module search path = None
```
##### Ansible Configuration:

```
➜ cat ~/ansible_hosts
127.0.0.1 ansible_connection=local
➜ echo $ANSIBLE_INVENTORY
/Users/bbo/ansible_hosts
```
##### Environment:
- OS X 10.10.5
- Python 2.7.10
##### Summary:

Include is broken in devel (a22cf8ffc1), but it works with 1.9.4 fine.

I'm not sure but it seems issue with `included_file.py`.
##### Steps To Reproduce:

```
➜ cat playbook.yml
- hosts: all
  tasks:
  - include: included_task.yml
➜ cat included_task.yml
- debug: msg="included_task"
```
##### Expected Results:

```
➜ ansible --version
ansible 1.9.4
  configured module search path = None
➜ ansible-playbook playbook.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [debug msg="included_task"] *********************************************
ok: [127.0.0.1] => {
    "msg": "included_task"
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
➜ ansible --version
ansible 2.0.0 (devel a22cf8ffc1) last updated 2015/10/20 09:40:47 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 49ee5dd443) last updated 2015/10/19 23:32:48 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 6c0765f48f) last updated 2015/10/19 23:33:04 (GMT +300)
  config file =
  configured module search path = None
➜ ansible-playbook playbook.yml -vvv
No config file found; using defaults
1 plays in playbook.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: bbo
127.0.0.1 EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445344154.14-53112497014124)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445344154.14-53112497014124)")
127.0.0.1 PUT /var/folders/_p/m1v4m5kn1lnfzktjfkjn2glh0000gn/T/tmpb4ozLM TO /Users/bbo/.ansible/tmp/ansible-tmp-1445344154.14-53112497014124/setup
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/bbo/.ansible/tmp/ansible-tmp-1445344154.14-53112497014124/setup; rm -rf "/Users/bbo/.ansible/tmp/ansible-tmp-1445344154.14-53112497014124/" > /dev/null 2>&1
ok: [127.0.0.1]

TASK [include] *****************************************************************
Unexpected Exception: object of type 'NoneType' has no len()
the full traceback was:

Traceback (most recent call last):
  File "/Users/bbo/src/github.com/ansible/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/cli/playbook.py", line 142, in run
    results = pbex.run()
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/executor/playbook_executor.py", line 140, in run
    result = self._tqm.run(play=play)
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 217, in run
    return strategy.run(iterator, play_context)
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/plugins/strategy/linear.py", line 262, in run
    included_files = IncludedFile.process_include_results(host_results, self._tqm, iterator=iterator, loader=self._loader, variable_manager=self._variable_manager)
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/playbook/included_file.py", line 97, in process_include_results
    include_file = loader.path_dwim(res._task.args.get('_raw_params'))
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/parsing/__init__.py", line 210, in path_dwim
    given = unquote(given)
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/parsing/splitter.py", line 272, in unquote
    if is_quoted(data):
  File "/Users/bbo/src/github.com/ansible/ansible/lib/ansible/parsing/splitter.py", line 268, in is_quoted
    return len(data) > 1 and data[0] == data[-1] and data[0] in ('"', "'") and data[-2] != '\\'
TypeError: object of type 'NoneType' has no len()
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bborysenko** [comment]
Just to confirm that issue really has been fixed, thanks @jimi-c !

**Comment by jimi-c** [comment]
Thanks!
