### ISSUE TITLE
Unexpected Exception: 'VariableManager' object has no attribute '_display'

### ISSUE THREAD

**Issue by isgroup** [ansible/ansible#12859]
Unexpected Exception: 'VariableManager' object has no attribute '_display'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/cli/playbook.py", line 142, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/playbook_executor.py", line 140, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/task_queue_manager.py", line 217, in run
    return strategy.run(iterator, play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/strategy/linear.py", line 214, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/vars/__init__.py", line 316, in get_vars
    all_vars['ansible_delegated_vars'] = self._get_delegated_vars(loader, play, task, all_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/vars/__init__.py", line 388, in _get_delegated_vars
    self._display.deprecated("Skipping task due to undefined attribute, in the future this will be a fatal error.")
AttributeError: 'VariableManager' object has no attribute '_display'

**Comment by isgroup** [comment]
Fast!
