### ISSUE TITLE
UnboudLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#13093]
Version: 1.9 but also devel as the file handling code does not changed.
Server/Client OS: Ubuntu

This is not a duplicate of #2618. When defining a caching path for the jsonfile caching plugin that is not writable by Ansible. Ansible fails with the following message:

```
fatal: [my-host] => Traceback (most recent call last):
  File "/home/david/.pip/ansible/lib/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/david/.pip/ansible/lib/ansible/runner/__init__.py", line 668, in _executor_internal
    inject = self.get_inject_vars(host)
  File "/home/david/.pip/ansible/lib/ansible/runner/__init__.py", line 611, in get_inject_vars
    combined_cache = self.get_combined_cache()
  File "/home/david/.pip/ansible/lib/ansible/runner/__init__.py", line 606, in get_combined_cache
    combined_cache = self.setup_cache.copy()
  File "/home/david/.pip/ansible/lib/ansible/cache/__init__.py", line 54, in copy
    return dict([(k, v) for (k, v) in self.iteritems()])
  File "/usr/lib/python2.7/_abcoll.py", line 406, in iteritems
    yield (key, self[key])
  File "/home/david/.pip/ansible/lib/ansible/cache/__init__.py", line 35, in __getitem__
    return self._plugin.get(key)
  File "/home/david/.pip/ansible/lib/ansible/cache/jsonfile.py", line 69, in get
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
```

**Comment by davidfischer-ch** [comment]
Do you have any update on this please? Thanks for your time.

**Comment by bcoca** [comment]
the PR above fixes the issues in my tests, please confirm

**Comment by davidfischer-ch** [comment]
Hello, great, its working!
