### ISSUE TITLE
ansible fails with an exception in python

### ISSUE THREAD

**Issue by tzookb** [ansible/ansible#13103]
I sinply run command: "forever stopall"

but I get this output from stdout when it fails:

fatal: [node1] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/**init**.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 1005, in _executor_internal_inner
    num_args_post = self._count_module_args(module_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 433, in _count_module_args
    vargs = split_args(args)
  File "/Library/Python/2.7/site-packages/ansible/module_utils/splitter.py", line 73, in split_args
    args = args.strip()
AttributeError: 'dict' object has no attribute 'strip'

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by michalmedvecky** [comment]
The same happens to me.

t.yml:

```
- hosts: all
  roles:
    -
```

blalunglaj:ansible-library misko$ ansible-playbook -i inventory/ t.yml
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/**init**.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 103, in **init**
    ds = self._load_roles(self.roles, ds)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 440, in _load_roles
    roles = self._build_role_dependencies(roles, [], {})
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 251, in _build_role_dependencies
    role_path,role_vars = self._get_role_path(role)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 221, in _get_role_path
    role_name = utils.role_spec_parse(orig_path)["name"]
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/utils/__init__.py", line 391, in role_spec_parse
    role_spec = role_spec.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by abadger** [comment]
In 2.0, this returns an error message instead of a traceback:

```
ERROR! A malformed role declaration was encountered.
```

So marking this as fixed.
