### ISSUE TITLE
[v2] TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#13110]
**Ansible Version**

```
ansible 2.0.0 (devel 09994c18f3) last updated 2015/11/10 08:56:11 (GMT +300)
  lib/ansible/modules/core: (detached HEAD fde6ee15d6) last updated 2015/11/10 09:01:29 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 6cc43bbd56) last updated 2015/11/10 09:01:29 (GMT +300)
```

**Summary**

My Vagrant test playbook failed with this error:

```
TASK [roundup : configure alias_database] **************************************
task path: /home/mg/src/deployments/provisioning/roles/roundup/tasks/main.yml:62
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/mg/src/ansible/lib/ansible/executor/process/worker.py", line 134, in run
    shared_loader_obj,
  File "/home/mg/src/ansible/lib/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "/home/mg/src/ansible/lib/ansible/executor/task_executor.py", line 381, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/mg/src/ansible/lib/ansible/plugins/action/normal.py", line 29, in run
    results = super(ActionModule, self).run(tmp, task_vars)
TypeError: super(type, obj): obj must be an instance or subtype of type

fatal: [trusty]: FAILED! => {"failed": true, "stdout": ""}
```

This playbook works with Ansible 1.9.4.

I'm using a [custom module](https://gist.github.com/mgedmin/5f8ac034df0c371444be):

```
- name: configure alias_database
  postfix: name=alias_database value="hash:/etc/aliases, hash:/etc/roundup/aliases"
  notify: postfix reload
  tags: mail
```

The module has a custom action plugin, needed to support --diff on Ansible 1.x, but this doesn't do anything on v2 -- just re-imports ActionModule from ansible.plugins.action.normal.

I'll try to reproduce with a smaller example.

**Comment by mgedmin** [comment]
I'm having trouble reproducing this with a small example.

Instead I added some debugging prints

``` diff
diff --git a/lib/ansible/plugins/action/normal.py b/lib/ansible/plugins/action/normal.py
index bf93fda..2ea942f 100644
--- a/lib/ansible/plugins/action/normal.py
+++ b/lib/ansible/plugins/action/normal.py
@@ -26,6 +26,8 @@ class ActionModule(ActionBase):
         if task_vars is None:
             task_vars = dict()

+        print(type(self), id(type(self)))
+        print(ActionModule, id(ActionModule))
         results = super(ActionModule, self).run(tmp, task_vars)
         results.update(self._execute_module(tmp=tmp, task_vars=task_vars))
```

and I see this output:

```
TASK [roundup : configure alias_database] **************************************
task path: /home/mg/src/deployments/provisioning/roles/roundup/tasks/main.yml:62
<class 'ansible.plugins.action.normal.ActionModule'> 22793120
<class 'ansible.plugins.action.normal.ActionModule'> 37483152
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/mg/src/ansible/lib/ansible/executor/process/worker.py", line 134, in run
    shared_loader_obj,
  File "/home/mg/src/ansible/lib/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "/home/mg/src/ansible/lib/ansible/executor/task_executor.py", line 381, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/mg/src/ansible/lib/ansible/plugins/action/normal.py", line 31, in run
    results = super(ActionModule, self).run(tmp, task_vars)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

Somehow there are two different classes with the same name.

**Comment by mgedmin** [comment]
`git bisect` is going badly, when I have to suffer 2 minute test runs and skip too many of the tests because of unrelated errors.

**Comment by jimi-c** [comment]
It seems like you're using an ActionModule class which does not inherit from ActionBase. You have custom action plugins, correct?

**Comment by mgedmin** [comment]
I've reproduced with a small example: https://github.com/mgedmin/ansible-bug-13110

**Comment by mgedmin** [comment]
Bisected to 59b67a2f6856998971cebe9863e604238168be5a

**Comment by mgedmin** [comment]
Clue: with the following instrumentation

``` diff
diff --git a/lib/ansible/plugins/__init__.py b/lib/ansible/plugins/__init__.py
index 4def393..2c33b65 100644
--- a/lib/ansible/plugins/__init__.py
+++ b/lib/ansible/plugins/__init__.py
@@ -304,8 +304,21 @@ class PluginLoader:
     __contains__ = has_plugin

     def _load_module_source(self, name, path):
+        import os, sys
+        def m(name):
+            if name in sys.modules:
+                print(os.getpid(), "sys.modules['%s'] is" % name, hex(id(sys.modules[name])))
+            else:
+                print(os.getpid(), "sys.modules['%s'] is missing" % name)
+        if 'action' in name:
+            m('ansible.plugins.action')
+            m('ansible.plugins.action.normal')
+            print(os.getpid(), "LOADING", name, "FROM", path)
         with open(path, 'r') as module_file:
             module = imp.load_source(name, path, module_file)
+        if 'action' in name:
+            m('ansible.plugins.action')
+            m('ansible.plugins.action.normal')
         return module

     def get(self, name, *args, **kwargs):
diff --git a/lib/ansible/plugins/action/normal.py b/lib/ansible/plugins/action/normal.py
index bf93fda..481cfae 100644
--- a/lib/ansible/plugins/action/normal.py
+++ b/lib/ansible/plugins/action/normal.py
@@ -19,6 +19,9 @@ __metaclass__ = type

 from ansible.plugins.action import ActionBase

+import os
+print(os.getpid(), "IMPORTING ansible.plugins.action.normal")
+

 class ActionModule(ActionBase):

@@ -26,6 +29,17 @@ class ActionModule(ActionBase):
         if task_vars is None:
             task_vars = dict()

+        import os, sys
+        def m(name):
+            if name in sys.modules:
+                print(os.getpid(), "sys.modules['%s'] is" % name, hex(id(sys.modules[name])))
+            else:
+                print(os.getpid(), "sys.modules['%s'] is missing" % name)
+
+        m('ansible.plugins.action')
+        m('ansible.plugins.action.normal')
+        print(os.getpid(), "RUNNING some module dunno which one")
+
         results = super(ActionModule, self).run(tmp, task_vars)
         results.update(self._execute_module(tmp=tmp, task_vars=task_vars))

```

I see that the module is being loaded twice:

```
mg@platonas: ~/src/bugs/ansible-bug-13110 [git:master=] $ ansible-playbook -i localhost, test.yml -f 1 -vvv
No config file found; using defaults
2 plays in test.yml

PLAY ***************************************************************************
21642 sys.modules['ansible.plugins.action'] is 0x7f06610abec0
21642 sys.modules['ansible.plugins.action.normal'] is missing
21642 LOADING ansible.plugins.action.custom_module FROM /home/mg/src/bugs/ansible-bug-13110/action_plugins/custom_module.py
21642 IMPORTING ansible.plugins.action.normal
21642 sys.modules['ansible.plugins.action'] is 0x7f06610abec0
21642 sys.modules['ansible.plugins.action.normal'] is 0x7f066105b1a0

TASK [custom_module] ***********************************************************
task path: /home/mg/src/bugs/ansible-bug-13110/test.yml:5
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

PLAY ***************************************************************************

TASK [command] *****************************************************************
task path: /home/mg/src/bugs/ansible-bug-13110/test.yml:11
21652 sys.modules['ansible.plugins.action'] is 0x7f06610abec0
21652 sys.modules['ansible.plugins.action.normal'] is 0x7f066105b1a0
21652 LOADING ansible.plugins.action.normal FROM /home/mg/src/ansible/lib/ansible/plugins/action/normal.py
21652 IMPORTING ansible.plugins.action.normal
21652 sys.modules['ansible.plugins.action'] is 0x7f06610abec0
21652 sys.modules['ansible.plugins.action.normal'] is 0x7f066105b1a0
21652 sys.modules['ansible.plugins.action'] is 0x7f06610abec0
21652 sys.modules['ansible.plugins.action.normal'] is 0x7f066105b1a0
21652 RUNNING some module dunno which one
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost (umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1447168652.82-42051715797769`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1447168652.82-42051715797769`")
<localhost> PUT /tmp/tmp63wszN TO /home/mg/.ansible/tmp/ansible-tmp-1447168652.82-42051715797769/command
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r [localhost]
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mg/.ansible/tmp/ansible-tmp-1447168652.82-42051715797769/command; rm -rf "/home/mg/.ansible/tmp/ansible-tmp-1447168652.82-42051715797769/" > /dev/null 2>&1
changed: [localhost] => {"changed": true, "cmd": ["echo", "hi"], "delta": "0:00:00.001640", "end": "2015-11-10 17:17:33.220137", "invocation": {"module_args": {"_raw_params": "echo hi"}, "module_name": "command"}, "rc": 0, "start": "2015-11-10 17:17:33.218497", "stderr": "", "stdout": "hi", "stdout_lines": ["hi"], "warnings": []}

TASK [custom_module] ***********************************************************
task path: /home/mg/src/bugs/ansible-bug-13110/test.yml:12
21652 sys.modules['ansible.plugins.action'] is 0x7f06610abec0
21652 sys.modules['ansible.plugins.action.normal'] is 0x7f066105b1a0
21652 RUNNING some module dunno which one
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/mg/src/ansible/lib/ansible/executor/process/worker.py", line 134, in run
    shared_loader_obj,
  File "/home/mg/src/ansible/lib/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "/home/mg/src/ansible/lib/ansible/executor/task_executor.py", line 381, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/mg/src/ansible/lib/ansible/plugins/action/normal.py", line 43, in run
    results = super(ActionModule, self).run(tmp, task_vars)
TypeError: super(type, obj): obj must be an instance or subtype of type

fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1   
```

**Comment by mgedmin** [comment]
After some IRC discussion with <jimi|ansible> we think this is what happens:
- custom_module.py is loaded by the PluginLoader and causes normal.py to be imported (and stuffed into sys.modules)
- custom_module's module **dict** gets a reference to ActionModule from normal.py
- normal.py is loaded by the PluginLoader, which doesn't notice that it's already present in sys.modules, so it calls imp.load_source()
- load_source() executes the code again, overriding all the class definitions with new classes
- when custom_module is executed, it still has a reference to the old ActionModule class, which doesn't match the new ActionModule currently residing in the **dict** of the ansible.plugins.action.normal module

One fix is "don't do that then": instead of having users import standard Ansible action plugin code and subclass for extension, require that users copy and paste the source and modify it in place.

(I'm not very happy with this solution.)

Another fix is to have PluginLoader.get() check sys.modules in addition to self._module_cache, before it calls imp.load_source().
