### ISSUE TITLE
AttributeError: 'Galaxy' object has no attribute 'display'

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible#13131]
Running `ansible-galaxy` fails on `devel` with:

```
Traceback (most recent call last):
  File "/Users/benjixx/Dropbox/src/goodplay/.tox/py27/bin/ansible-galaxy", line 84, in <module>
    sys.exit(cli.run())
  File "/Users/benjixx/Dropbox/src/goodplay/.tox/py27/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 129, in run
    self.api = GalaxyAPI(self.galaxy, api_server)
  File "/Users/benjixx/Dropbox/src/goodplay/.tox/py27/lib/python2.7/site-packages/ansible/galaxy/api.py", line 55, in __init__
    self.galaxy.display.vvvvv("Base API: %s" % self.baseurl)
AttributeError: 'Galaxy' object has no attribute 'display'
```

**Comment by jimi-c** [comment]
This was fixed by 8aa2cbd6475df9dc94f150a6fcd449f5a41d0519 already.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
