### ISSUE TITLE
list index out of range while doing setup step

### ISSUE THREAD

**Issue by dbpeng** [ansible/ansible#13359]
### environment

OS: centos 6.5
nodes: centos 6.5
Ansible version: ansible 2.0.0 (devel 6671d78f95)
### symptom

I have a series of playbooks that already run correctly at ansible-1.9.4...  
Then upgraded my ansible to ansible 2.0.0 (devel 6671d78f95) recently and found a weird thing that it sometimes failed at `setup` setup, The possibility is around 50%.  

Not sure if anyone encounter similar issue like this?

the error traceback:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/playmore/ansible/lib/ansible/executor/process/worker.py", line 135, in run
    shared_loader_obj,
  File "/home/playmore/ansible/lib/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/playmore/ansible/lib/ansible/executor/task_executor.py", line 402, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/playmore/ansible/lib/ansible/plugins/action/normal.py", line 30, in run
    results.update(self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/home/playmore/ansible/lib/ansible/plugins/action/__init__.py", line 396, in _execute_module
    tmp = self._make_tmp_path()
  File "/home/playmore/ansible/lib/ansible/plugins/action/__init__.py", line 232, in _make_tmp_path
    rc = self._connection._shell.join_path(result['stdout'].strip(), u'').splitlines()[-1]
IndexError: list index out of range
```

**Comment by lukehoersten** [comment]
Getting something similar but on a `copy` module not `setup`:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 135, in run
    shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 402, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 148, in run
    dest = self._remote_expand_user(dest)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 336, in _remote_expand_user
    initial_fragment = data['stdout'].strip().splitlines()[-1]
IndexError: list index out of range
```

Not sure if this is related. @bcoca let me know if I should open this as a separate issue.

**Comment by lukehoersten** [comment]
After looking at the code more closely I see it's the same error but in different code. Made a new issue: #13531

**Comment by wrouesnel** [comment]
This is happening to me as of 404b2864efa89f97f3bb14bf1448461d0c9de52f
