### ISSUE TITLE
[Bug Report] --tree option not working on 2.0

### ISSUE THREAD

**Issue by tatref** [ansible/ansible#13379]
I'm using the following version:

```
ansible 2.0.0 (devel f873cc0fb5) last updated 2015/12/01 21:23:53 (GMT +200)
lib/ansible/modules/core: (detached HEAD cd9a7667aa) last updated 2015/12/01 21:24:33 (GMT +200)
lib/ansible/modules/extras: (detached HEAD 3c4f954f0f) last updated 2015/12/01 21:24:33 (GMT +200)
```

```
$ ansible -i hosts 192.168.0.2 -m setup --tree facts
Unexpected Exception: __init__() takes exactly 2 arguments (1 given)
to see the full traceback, use -vvv
```

Using -vvv:

```
$ ansible -i hosts 192.168.0.2 -m setup --tree facts -vvv
Unexpected Exception: __init__() takes exactly 2 arguments (1 given)
the full traceback was:
Traceback (most recent call last):
  File "/home/yann/code/ansible/ansible/bin/ansible", line 84, in <module>
    sys.exit(cli.run())
  File "/home/yann/code/ansible/ansible/lib/ansible/cli/adhoc.py", line 181, in run
    result = self._tqm.run(play)
  File "/home/yann/code/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 179, in run
    self.load_callbacks()
  File "/home/yann/code/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 165, in load_callbacks
    self._callback_plugins.append(callback_plugin())
TypeError: __init__() takes exactly 2 arguments (1 given)
```

ansible.cfg is very simple:

```
[defaults]
fact_caching = jsonfile
fact_caching_connection = facts
```

I'm using Debian 8.2 64b.

The exact same commands works fine with 1.9.4

Let me know if you need more information.

**Comment by bcoca** [comment]
fixed via 3e01516783a3fbfa35c695513a486a40d37db47f
