### ISSUE TITLE
Windows support on v2.0.0-0.6.rc1: unicode bug?

### ISSUE THREAD

**Issue by juju4** [ansible/ansible#13387]
Hello,

testing ansible v2, host is lubuntu trusty (fr UTF8). guest is win10 virtualbox (FR too, Installlanguage REG_SZ 040C)
got an unicode issue it seems for a variable containing output of a command on a french system (accent...)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 79: ordinal not in range(128)

Issue Type: bug report
Ansible Version: v2.0.0-0.6.rc1

Steps To Reproduce:

```
- raw: "netstat -anoq"
  register: netstatanoq
- local_action: copy content={{ netstatanoq }} dest=/tmp/{{ prefix }}-netstat-anoq
```

Actual Results:

```
TASK [incidentresponse : raw] **************************************************
task path: /home/julien/Documents/script/homelab/roles/incidentresponse/tasks/windows-cmds.yml:7
<192.168.2.109> ESTABLISH WINRM CONNECTION FOR USER: user on PORT 5986 TO 192.168.2.109
<192.168.2.109> EXEC netstat -anoq
ok: [192.168.2.109] => {"changed": false, "invocation": {"module_args": {"_raw_params": "netstat -anoq"}, "module_name": "raw"}, "rc": 0, "stderr": "", "stdout": "\r\nConnexions actives\r\n\r\n  Proto  Adresse locale         Adresse distante       �tat\r\n  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       624\r\n  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:5985           0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:5986           0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       764\r\n  TCP    0.0.0.0:47001          0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:49408          0.0.0.0:0              LISTENING       408\r\n  TCP    0.0.0.0:49409          0.0.0.0:0              LISTENING       764\r\n  TCP    0.0.0.0:49410          0.0.0.0:0              LISTENING       280\r\n  TCP    0.0.0.0:49411
[...]

TASK [incidentresponse : copy content={{ netstatanoq }} dest=/tmp/{{ prefix }}-netstat-anoq] ***
task path: /home/julien/Documents/script/homelab/roles/incidentresponse/tasks/windows-cmds.yml:9
ESTABLISH LOCAL CONNECTION FOR USER: julien
localhost EXEC rc=flag; [ -r /tmp/DESKTOP-PTPUFI8-netstat-anoq ] || rc=2; [ -f /tmp/DESKTOP-PTPUFI8-netstat-anoq ] || rc=1; [ -d /tmp/DESKTOP-PTPUFI8-netstat-anoq ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/tmp/DESKTOP-PTPUFI8-netstat-anoq && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'/tmp/DESKTOP-PTPUFI8-netstat-anoq'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'/tmp/DESKTOP-PTPUFI8-netstat-anoq'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/tmp/DESKTOP-PTPUFI8-netstat-anoq)
localhost EXEC (umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1449018691.64-133920109984120`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1449018691.64-133920109984120`")
localhost PUT /tmp/tmpNONK30 TO /home/julien/.ansible/tmp/ansible-tmp-1449018691.64-133920109984120/source
localhost EXEC (umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930`")
localhost PUT /tmp/tmpR40NWl TO /home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy; rm -rf "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy", line 2245, in <module>
    main()
  File "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy", line 222, in main
    supports_check_mode=True,
  File "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy", line 895, in __init__
    self._log_invocation()
  File "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy", line 1751, in _log_invocation
    self.log(msg, log_args=log_args)
  File "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy", line 1692, in log
    journal_msg = remove_values(msg.decode('utf-8', 'replace'), self.no_log_values)
  File "/home/julien/.ansible/tmp/ansible-tmp-1449018691.64-77202891227930/copy", line 734, in remove_values
    value = value.replace(omit_me, '*' * 8)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 79: ordinal not in range(128)

fatal: [192.168.2.109 -> localhost]: FAILED! => {"changed": false, "checksum": "51bce163c2aec0c18fab61ef9e8c3bc616fda0b3", "failed": true, "invocation": {"module_args": {"content": {"changed": false, "rc": 0, "stderr": "", "stdout": "\r\nConnexions actives\r\n\r\n  Proto  Adresse locale         Adresse distante       �tat\r\n  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       624\r\n  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:5985           0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:5986           0.0.0.0:0              LISTENING       4\r\n  TCP    0.0.0.0:7680           0.0.0.0:0
[...]
%6]:546  *:*                                    280", "  UDP    [fe80::9d6b:93db:7dc1:bd34%6]:1900  *:*                                    292", "  UDP    [fe80::9d6b:93db:7dc1:bd34%6]:58100  *:*                                    292"]}, "dest": "/tmp/DESKTOP-PTPUFI8-netstat-anoq"}, "module_name": "copy"}, "parsed": false}

```

Expected Results:
contents saved to file.

**Comment by nitzmahone** [comment]
Windows being the source of the Unicode data here is a red herring- the play is bombing in the copy module. I can reproduce the behavior with the following playbook:

```
- hosts: win
  tasks:
  - local_action: copy 
    args:
      content: "bleeæ" 
      dest: /tmp/foo.txt
```

It looks like the module_utils logging stuff has a replace that's choking on the UTF8 surrogate.

**Comment by abadger** [comment]
Okay, that makes the test case given work.  Also added some test cases for unicode values.

**Comment by abadger** [comment]
Pushed to devel and stable-2.0
