### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' 

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible#13385]
I'm using latest Ansible 2 from git. 

I am runnig this task:

``` yaml
- name: "create APT security auto-upgrades configuration"
  copy: "src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644"
  with_items:
    - { src: 'apt/auto-upgrades', dest: '/etc/apt/apt.conf.d/20auto-upgrades' }
```

My template file contents are:

```
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
```

I am getting this result:

```
$ ansible-playbook timeboxes.yml --limit 18f90a257a0b69c2d569 -vvv
Using /Users/Hackeron/Development/Xanview/xanview-ansible/ansible.cfg as config file
1 plays in timeboxes.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<vpn-18f90a257a0b69c2d569.timeline.is> ESTABLISH SSH CONNECTION FOR USER: deployer
<vpn-18f90a257a0b69c2d569.timeline.is> SSH: EXEC ssh -C -q -o ForwardAgent=yes -o ConnectTimeout=300 -o ControlPersist=60m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deployer -o ConnectTimeout=300 -o ControlPath=/Users/Hackeron/.ansible/cp/ansible-ssh-%h-%p-%r -tt vpn-18f90a257a0b69c2d569.timeline.is /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jnlznspxlvwuxkzqagmmjisqzrfezzai; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 python -uc '"'"'"'"'"'"'"'"'import sys; [sys.stdout.write(s) for s in iter(sys.stdin.readline, "__EOF__942d747a0772c3284ffb5920e234bd57__\n")]'"'"'"'"'"'"'"'"'| LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"''
ok: [18f90a257a0b69c2d569]

TASK [common : include] ********************************************************
task path: /Users/Hackeron/Development/Xanview/xanview-ansible/roles/common/tasks/main.yml:1
included: /Users/Hackeron/Development/Xanview/xanview-ansible/roles/common/tasks/user.yml for 18f90a257a0b69c2d569

TASK [common : include] ********************************************************
task path: /Users/Hackeron/Development/Xanview/xanview-ansible/roles/common/tasks/main.yml:12
included: /Users/Hackeron/Development/Xanview/xanview-ansible/roles/common/tasks/apt.yml for 18f90a257a0b69c2d569

TASK [common : create APT security auto-upgrades configuration] ****************
task path: /Users/Hackeron/Development/Xanview/xanview-ansible/roles/common/tasks/apt.yml:16
<vpn-18f90a257a0b69c2d569.timeline.is> ESTABLISH SSH CONNECTION FOR USER: deployer
<vpn-18f90a257a0b69c2d569.timeline.is> SSH: EXEC ssh -C -q -o ForwardAgent=yes -o ConnectTimeout=300 -o ControlPersist=60m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deployer -o ConnectTimeout=300 -o ControlPath=/Users/Hackeron/.ansible/cp/ansible-ssh-%h-%p-%r -tt vpn-18f90a257a0b69c2d569.timeline.is /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-xzmfbpsfnfkoawniiyorsnxvpxzifgfp; rc=flag; [ -r /etc/apt/apt.conf.d/20auto-upgrades ] || rc=2; [ -f /etc/apt/apt.conf.d/20auto-upgrades ] || rc=1; [ -d /etc/apt/apt.conf.d/20auto-upgrades ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/apt/apt.conf.d/20auto-upgrades && exit 0; (python -c '"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'"'"'"'"'"'"'/etc/apt/apt.conf.d/20auto-upgrades'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'"'"'"'"'"'"'/etc/apt/apt.conf.d/20auto-upgrades'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'0  '"'"'"'"'"'"'"'"'/etc/apt/apt.conf.d/20auto-upgrades)'"'"''
<vpn-18f90a257a0b69c2d569.timeline.is> ESTABLISH SSH CONNECTION FOR USER: deployer
<vpn-18f90a257a0b69c2d569.timeline.is> SSH: EXEC ssh -C -q -o ForwardAgent=yes -o ConnectTimeout=300 -o ControlPersist=60m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deployer -o ConnectTimeout=300 -o ControlPath=/Users/Hackeron/.ansible/cp/ansible-ssh-%h-%p-%r -tt vpn-18f90a257a0b69c2d569.timeline.is (umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1449016250.41-39620320318556`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1449016250.41-39620320318556`")
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 135, in run
    shared_loader_obj,
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 91, in run
    item_results = self._run_loop(items)
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 241, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 404, in _execute
    return dict(unreachable=True, msg=str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 478: ordinal not in range(128)

fatal: [18f90a257a0b69c2d569]: FAILED! => {"failed": true, "stdout": ""}

PLAY RECAP *********************************************************************
18f90a257a0b69c2d569       : ok=3    changed=0    unreachable=0    failed=1   
$
```

Any ideas? -- I do not have anything non ascii anywhere I can tell, what is causing this all of a sudden?

**Comment by tetherit** [comment]
Ah, figured it out, my /home/deployer/.ansible became owned by root - because of this ansible couldn't copy the source. Maybe this needs to be checked for because a UnicodeEncodeError is very confusing/misleading.

**Comment by abadger** [comment]
Fixed the traceback and pushed to both devel ans the stable-2.0 branch.  Thanks for reporting this!

**Comment by tetherit** [comment]
Thank you for the super quick fix :)
