### ISSUE TITLE
Backport v2 dynamic connection args to winrm 

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#13508]
Pywinrm 0.1.1 has the ability to ignore cert validation on Python 2.7.9+, but we don't have a way to tell it to do so in 1.9.x. Backport the ansible_winrm_\* args handler from 2.0 to allow passing arbitrary args to pywinrm.

**Comment by sumanthreddybolledla** [comment]
Does Pywinrm 0.1.1 has the ability to ignore cert validation on python 2.6.6?

**Comment by jhawkesworth** [comment]
If I recall cert validation wasn't required until python 2.7.9

**Comment by sumanthreddybolledla** [comment]
I'm getting the below issue, Can you please help me?
ansible version: 1.9.4
python: 2.6
pyopenssl: 0.10

FAILED => Traceback (most recent call last):
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 586, in _executor
exec_rc = self._executor_internal(host, new_stdin)
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 789, in _executor_internal
return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 968, in _executor_internal_inner
conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
File "/usr/lib/python2.6/site-packages/ansible/runner/connection.py", line 35, in connect
conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
File "/usr/lib/python2.6/site-packages/ansible/utils/plugins.py", line 218, in get
self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
File "/usr/lib/python2.6/site-packages/ansible/runner/connection_plugins/winrm.py", line 32, in 
from winrm import Response
File "/usr/lib/python2.6/site-packages/winrm/init.py", line 6, in 
from winrm.protocol import Protocol
File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 11, in 
from winrm.transport import Transport
File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 42, in 
from requests_credssp import HttpCredSSPAuth
File "/usr/lib/python2.6/site-packages/requests_credssp/init.py", line 1, in 
from .credssp import HttpCredSSPAuth
File "/usr/lib/python2.6/site-packages/requests_credssp/credssp.py", line 8, in 
raise Exception("Cannot import pyOpenSSL")
Exception: Cannot import pyOpenSSL

**Comment by nitzmahone** [comment]
@sumanthreddybolledla - commenting on closed issues isn't the best way to get help. This looks like an installation issue- you'd probably have more luck on the [mailing list](https://groups.google.com/forum/#!forum/ansible-project).
