### ISSUE TITLE
Unhelpful error from apt_repository module when python-apt is not installed

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#13520]
When I try to use the `apt_repository` type on a host that doesn't have the `python-apt` package installed, ansible gives an unhelpful error message.

```
TASK [ansible : ansible PPA] ***************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'aptsources_distro' is not defined
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

Running with `-vvv` gives me the full traceback:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/pi/.ansible/tmp/ansible-tmp-1449858323.5-265259943853239/apt_repository", line 3184, in <module>
    main()
  File "/home/pi/.ansible/tmp/ansible-tmp-1449858323.5-265259943853239/apt_repository", line 443, in main
    if isinstance(distro, aptsources_distro.UbuntuDistribution):
NameError: global name 'aptsources_distro' is not defined
```

**Comment by mattclay** [comment]
I've reproduced this issue on Ubuntu 14.04 LTS, but only when using check mode.

To reproduce, uninstall python-apt:

```
root@ubuntu1404-os:~# apt-get remove python-apt -qqy
(Reading database ... 17290 files and directories currently installed.)
Removing python-apt (0.9.3.5ubuntu2) …
```

Then try to use apt_repository in check mode:

```
root@ubuntu1404-os:~# ansible localhost -m apt_repository -a "repo='deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse'" --check
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'aptsources_distro' is not defined
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "parsed": false
}
```

The apt_repository module automatically installs python-apt if it is not already installed. However, installation is skipped in check mode without logging an error. This causes an exception to be thrown when the module attempts to use python-apt after the installation is skipped.
