### ISSUE TITLE
make tests and tests-py3 is broken in devel

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#13551]
##### Issue Type:

make tests is brocken in devel
##### Ansible Version:

```
ansible 2.1.0 (devel_fix_python3_tests 5d1a2eac3e) last updated 2015/12/15 11:39:57 (GMT +200)
  lib/ansible/modules/core: (detached HEAD e6b7b17326) last updated 2015/12/15 11:17:40 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f3251de29c) last updated 2015/12/15 11:17:40 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Nothing special
##### Environment:

Nothing special
##### Summary:

make tests is broken
##### Steps To Reproduce:

make tests
##### Expected Results:

```
Ran 333 tests in 5.335s

OK (SKIP=3)
```
##### Actual Results:

```
======================================================================
ERROR: test_strategy_base_run_handlers (units.plugins.strategies.test_strategy_base.TestStrategyBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yannig/dev/yannig/ansible/test/units/plugins/strategies/test_strategy_base.py", line 385, in test_strategy_base_run_handlers
    result = strategy_base.run_handlers(iterator=mock_iterator, play_context=mock_play_context)
  File "/home/yannig/dev/yannig/ansible/lib/ansible/plugins/strategy/__init__.py", line 524, in run_handlers
    result = self._do_handler_run(handler, handler_name, iterator=iterator, play_context=play_context)
  File "/home/yannig/dev/yannig/ansible/lib/ansible/plugins/strategy/__init__.py", line 561, in _do_handler_run
    host_results = self._wait_on_pending_results(iterator)
  File "/home/yannig/dev/yannig/ansible/lib/ansible/plugins/strategy/__init__.py", line 339, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/home/yannig/dev/yannig/ansible/lib/ansible/plugins/strategy/__init__.py", line 185, in _process_pending_results
    result = self._final_q.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/usr/lib/python2.7/dist-packages/funcsigs/__init__.py", line 190, in __new__
    obj._name = kwargs['name']
KeyError: 'name'

----------------------------------------------------------------------
Ran 335 tests in 5.403s

FAILED (SKIP=3, errors=1)
Makefile:103: recipe for target 'tests' failed
make: *** [tests] Error 1
```

**Comment by Yannig** [comment]
Actually, I'm suspecting the following commit to broke things up:
https://github.com/ansible/ansible/commit/279c5a359631d296e1a91c1520417e68750138bb

**Comment by Yannig** [comment]
For tests-py3, the result is a little bit different. The test hangs on the following result:

```
test_strategy_base_run_handlers (units.plugins.strategies.test_strategy_base.TestStrategyBase) ... Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/queues.py", line 247, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class
```

Pressing Ctrl+C the test continue with no error at the end but an error reported by make:

```
-------------------------------------------------------------------------------------
TOTAL                                     10792   4058   4623   2821    55%   
----------------------------------------------------------------------
Ran 301 tests in 46.062s

OK (SKIP=32)
Makefile:106: recipe for target 'tests-py3' failed
make: *** [tests-py3] Interrompre
```

**Comment by jimi-c** [comment]
This should be resolved by 6109f703970d741df6e2e28e750667f5d0083fda (and cherry-picked to devel too).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Yannig** [comment]
I can confirm :)

```
make tests
...
-------------------------------------------------------------------------------------
TOTAL                                     11279   4327   4684   2789    55%   
----------------------------------------------------------------------
Ran 335 tests in 10.300s

OK (SKIP=3)
```

```
make tests-py3
...
----------------------------------------------------------------------
Ran 335 tests in 7.394s

OK (SKIP=32)
```

Thanks @jimi-c !

**Comment by jimi-c** [comment]
Thanks for the follow-up!
