### ISSUE TITLE
Bug Report: make tests-py3 is broken in devel

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#13638]
##### Ansible Version:

last devel
##### Ansible Configuration:

Nothing special
##### Environment:

Nothing special
##### Summary:

make tests-py3 is broken
##### Steps To Reproduce:

Launch `make tests-py3`
##### Expected Results:

Tests OK
##### Actual Results:

```
======================================================================
FAIL: test_sudo_only_if_user_differs (units.plugins.action.test_action.TestActionBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ansible/ansible/test/units/plugins/action/test_action.py", line 52, in test_sudo_only_if_user_differs
    play_context.make_become_cmd.assert_called_once_with('ECHO', executable=None)
  File "/opt/python/3.4.2/lib/python3.4/unittest/mock.py", line 782, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/opt/python/3.4.2/lib/python3.4/unittest/mock.py", line 771, in assert_called_with
    raise AssertionError(_error_message()) from cause
nose.proxy.AssertionError: Expected call: mock('ECHO', executable=None)
Actual call: mock(b'ECHO', executable=None)
    None = (('ECHO',), {'executable': None}) if isinstance((('ECHO',), {'executable': None}), Exception) else None
>>  raise AssertionError(_error_message()) from None
```

**Comment by Yannig** [comment]
The following commit broke the tests in python3: https://github.com/ansible/ansible/commit/0c013f592a31c06baac7aadf27d23598f6abe931
