### ISSUE TITLE
SOLVED: route53 in v2.0: "__init__() got an unexpected keyword argument 'health_check'"

### ISSUE THREAD

**Issue by senorsmile** [ansible/ansible#13646]
I'm getting a strange error with the route53 module.  I have tested it on all alpha, beta and rc tags (alpha1 through rc3).  The following works without error on 1.9.4.  

Sample playbook (only domain name sanitized):

```

---
- hosts: localhost             
  tasks:
    - name: add deleteme route53 entry
      route53:
        command: create        
        zone: "example.org"      
        record: "deleteme.example.org"
        type: A
        ttl: 300
        value: "127.0.0.1"
        overwrite: yes
```

Error: 

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/shaun/.ansible/tmp/ansible-tmp-1450827287.46-59994245410580/route53", line 2613, in <module>
    main()
  File "/home/shaun/.ansible/tmp/ansible-tmp-1450827287.46-59994245410580/route53", line 379, in main
    health_check=health_check_in, failover=failover_in)
TypeError: __init__() got an unexpected keyword argument 'health_check'
```

**Comment by 16hands** [comment]
I can confirm the same issue, it worked 1.x but not v2:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got an unexpected keyword argument 'health_check'
fatal: [10.0.10.159]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

-vvv outputs:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1450862106.6-203792820809180/route53", line 2613, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1450862106.6-203792820809180/route53", line 379, in main
    health_check=health_check_in, failover=failover_in)
TypeError: __init__() got an unexpected keyword argument 'health_check'

fatal: [10.0.20.207]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"aws_access_key": "xx", "aws_secret_key": "xx", "command": "create", "overwrite": true, "record": "tester.public.co.nz", "ttl": 60, "type": "A", "value": "10.0.20.20", "zone": "public.co.nz"}, "module_name": "route53"}, "parsed": false}
```

This happens on both private and public domains 

this is the task:

```
 - name: Route53 add/update node to public.co.nz
    route53:
          command: create
          zone:  public.co.nz.
          record: "tester.public.co.nz."
          type: A
          ttl: 60
          overwrite: yes
          value: "10.0.20.20"
      connection: local
```

```
ansible --version
ansible 2.0.0 (stable-2.0 a2120a3d63) last updated 2015/12/23 02:38:29 (GMT +1300)
```

the same AWS auth keys have permission via the aws-cli 

kind regards
Carl.

**Comment by senorsmile** [comment]
I believe I've traced the incompatibility.  It seems to have to do with the Record module from Boto.  

The version I originally installed from my OS (Ubuntu 14.04) had the version:
2.20.1-2ubuntu2

I used pip to install the newest version (2.38) and everything works as expected: 
`pip install --upgrade --user boto`

Thus, this is solved!

**Comment by bcoca** [comment]
the change should have been made with version awareness, it is good you have a workaround but its not good we broke backwards compatibility. It got added in boto 2.26.0.
