### ISSUE TITLE
Can't get python traceback from exception thrown in callback plugin

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#13713]
As part of #13712 , I was trying to track down the source of a python exception in the `default.py` stdout callback plugin. Unfortunately, this effort was hindered by the apparent inability to get more than the exception and the file that it came from (no line number or traceback). Even when running with `-vvv`, this is the most I could get (which is exactly what I get without any `-v` option):

```
 [WARNING]: Error when using <bound method CallbackModule.v2_on_file_diff of </home/agaffney/dev/ansible/lib/ansible/plugins/callback/default.CallbackModule object at
0x760c34f0>>: 'TaskResult' object has no attribute 'get'
```

**Comment by bcoca** [comment]
check if PR above fixes this for you.

**Comment by agaffney** [comment]
That PR does result in a full traceback, but it's a bit hard to read, since the lines are smushed together.

```
 [WARNING]: Traceback (most recent call last):   File "/home/agaffney/dev/ansible/lib/ansible/executor/task_queue_manager.py", line 292, in send_callback     method(*args, **kwargs)   File
"/home/agaffney/dev/ansible/lib/ansible/plugins/callback/default.py", line 140, in v2_on_file_diff     newres = self._copy_result(result)   File "/usr/lib/python2.7/copy.py", line 155, in deepcopy     y = memo.get(d, _nil)
AttributeError: 'TaskResult' object has no attribute 'get'
```

**Comment by agaffney** [comment]
The current version of the PR outputs the following:

```
Traceback (most recent call last):
  File "/home/agaffney/dev/ansible/lib/ansible/executor/task_queue_manager.py", line 292, in send_callback
    method(*args, **kwargs)
  File "/home/agaffney/dev/ansible/lib/ansible/plugins/callback/default.py", line 140, in v2_on_file_diff
    if 'diff' in res2 and res['diff']:
NameError: global name 'res2' is not defined
```

This is much more readable, but it dropped the `[WARNING]` bit.
