### ISSUE TITLE
Exception using ansible_ssh_port in the .ini file

### ISSUE THREAD

**Issue by lcosmin** [ansible/ansible#1371]
I'm getting the following traceback with ansible 0.8 (7b51e30):

``` python
dev-aggregator01 | FAILED => Traceback (most recent call last):
  File "/home/work/ansible-upstream/lib/ansible/runner/__init__.py", line 263, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/work/ansible-upstream/lib/ansible/runner/__init__.py", line 326, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/work/ansible-upstream/lib/ansible/runner/__init__.py", line 400, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port)
  File "/home/work/ansible-upstream/lib/ansible/runner/connection.py", line 53, in connect
    self.active = conn.connect()
  File "/home/work/ansible-upstream/lib/ansible/runner/connection_plugins/ssh.py", line 53, in connect
    self.common_args += ["-o", "Port=%d" % (self.port)]
TypeError: %d format: a number is required, not str
```

hosts.ini:

```
[all]
dev-aggregator01 ansible_ssh_port=60001 ansible_ssh_host=10.120.137.181 dns_name="aggregator01"
```

command line:

```
ansible all -vvv -f 1 -c ssh -i ./hosts.ini -m shell -a "uptime"
```

The same happens with paramiko.

The problem seems to be that the `ini` parser doesn't add `ansible_ssh_port` as an integer, but as a normal `str` variable and gets passed down to the connection code as such, causing the above exception to be thrown.

**Comment by mpdehaan** [comment]
Thanks, I'll fix the formatter to use "%s" and push that later tonight, and will also check elsewhere for "%d" usage.

**Comment by lcosmin** [comment]
It's not only a formatter problem, for instance, paramiko doesn't accept a `str` as the port, see the following ipython session:

``` python
In [1]: import paramiko

In [2]: ssh = paramiko.SSHClient()

In [3]: ssh.connect('127.0.0.1', username="root", password="test", port="22")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/work/ansible-upstream/<ipython-input-3-2651afd1dc91> in <module>()
----> 1 ssh.connect('127.0.0.1', username="root", password="test", port="22")

/usr/lib/python2.7/dist-packages/paramiko/client.pyc in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress)
    308             server_hostkey_name = hostname
    309         else:
--> 310             server_hostkey_name = "[%s]:%d" % (hostname, port)
    311         our_server_key = self._system_host_keys.get(server_hostkey_name, {}).get(keytype, None)
    312         if our_server_key is None:

TypeError: %d format: a number is required, not str
```

**Comment by mpdehaan** [comment]
@dhozac should have fixed this in a previous PR.

Should be all good to go.

Thanks!
