### ISSUE TITLE
Not able to execute windows module in Ansible 1.9.4

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13733]
Hello, I am getting below error when I try to run below ansible command. Though accessing Linux works perfectly

```
$ansible -vvv windows -m win_ping
<ec2-54-xxx-xxx-xxx.compute-1.amazonaws.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO ec2-54-xxx-xxx-xxx.compute-1.amazonaws.com
ec2-54-xxx-xxx-xxx.compute-1.amazonaws.com | FAILED => Traceback (most recent call last):
  File "/home/ansible/ansible/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/ansible/ansible/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/ansible/ansible/lib/python2.7/site-packages/ansible/runner/__init__.py", line 968, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/home/ansible/ansible/lib/python2.7/site-packages/ansible/runner/connection.py", line 52, in connect
    self.active = conn.connect()
  File "/home/ansible/ansible/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 140, in connect
    self.protocol = self._winrm_connect()
  File "/home/ansible/ansible/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 96, in _winrm_connect
    protocol.send_message('')
  File "/home/ansible/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 193, in send_message
    return self.transport.send_message(message)
  File "/home/ansible/ansible/lib/python2.7/site-packages/winrm/transport.py", line 108, in send_message
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1142, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 946, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 986, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python2.7/httplib.py", line 924, in putheader
    str = '%s: %s' % (header, '\r\n\t'.join(values))
TypeError: sequence item 0: expected string, int found
```

Environment details:
Running python 2.7 on virtualenv
OS: CentOS 6.6

**Comment by jhawkesworth** [comment]
which pywinrm version are you using?

I don't use virtualenv but have this working fine on Centos and Ubuntu ansible controller hosts, so I suspect the problem is somewhere in your environment.

If I recall python 2.7.x checks ssl certs which previous versions didn't do and a workaround was required.

I suggest trying http instead of https (change ansible_port to 5985) and trying an older python version if possible to see if this isolates the problem.

I believe there is a fix in pywinrm 0.1.1

As an aside if you can I suggest trying the 2.0 version - along with latest pywinrm it is much faster than 1.9.4 when communicating with windows hosts.

**Comment by ghost** [comment]
Hello, Appreciate if you could let me know the workaround of ssl certs issue with python 2.7.x.

I am using pywinrm 0.1.1

**Comment by ghost** [comment]
I tried using Ansible 2.0 and got following error:

```
$ ansible -vvv windows -m win_stat -a "path=c:\windows\win.ini"
Using /etc/ansible/ansible.cfg as config file
<ec2-54-145-xxx-xxx.compute-1.amazonaws.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO ec2-54-145-xxx-xxx.compute-1.amazonaws.com
ec2-54-145-xxx-xxx.compute-1.amazonaws.com | FAILED! => {
    "failed": true,
    "msg": "ERROR! ssl: sequence item 0: expected string, int found"
}
```

**Comment by jhawkesworth** [comment]
Not sure the python 2.7 ssl certs is the issue at this point but workaround described here: https://github.com/ansible/ansible/issues/10294#issuecomment-93629047 more discussion here: https://github.com/ansible/ansible/pull/10132 

It looks however like you are getting essentially the same error in both versions of ansible.
Its failing to set an http header in the request as it is being sent an integer instead of a string.

I would be tempted to (temporarily) stick a few print statements in the python code so I could see what values it is trying to use to create the header and double check my inventory and windows group_vars for any keys or values that look like integers (and double quote them if they do to try and force them to be treated as strings).

Hope this helps.

**Comment by ghost** [comment]
I install Python 2.7.10 then it solved the issue. Earlier I was using Python 2.7

**Comment by jhawkesworth** [comment]
Thanks for the update, can you close off this issue now?

**Comment by ghost** [comment]
Thank you, Please close it!
