### ISSUE TITLE
Hostname as bool at `unarchive`

### ISSUE THREAD

**Issue by igormukhingmailcom** [ansible/ansible#13790]
Hi.

(Tested at `ansible` versions `1.9.2`, `1.9.4`)

When we write domain name at `inventory` without dots (like `vagrant`, not `vagrant.com`), and having variable `vagrant` defined at `Vagrantfile` (and set to `true`), playbook will fail at commands like `unarchive`:

```
<192.168.2.21> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.2.21> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/private/var/www/.../ansible/vendor/ansible-magento/tests/.vagrant/machines/default/virtualbox/private_key -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/igor/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 192.168.2.21 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452445305.97-47688423674771 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1452445305.97-47688423674771 && echo $HOME/.ansible/tmp/ansible-tmp-1452445305.97-47688423674771'
fatal: [vagrant] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/action_plugins/unarchive.py", line 85, in run
    remote_checksum = self.runner._remote_checksum(conn, tmp, dest, inject)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 1250, in _remote_checksum
    python_interp = inject['hostvars'][host].get('ansible_python_interpreter', 'python')
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 105, in __getitem__
    result.update(self.vars_cache.get(host, {}))
TypeError: 'bool' object is not iterable


FATAL: all hosts have already failed -- aborting
```

```
# inventory
vagrant ansible_ssh_host=192.168.2.21 # Our hostname is vagrant !!!
```

```
# Vagrantfile
Vagrant.configure(2) do |config|
    config.vm.box = $VM_BOX
    config.vm.network "private_network", ip: $IP
    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
            ansible_ssh_user: 'vagrant',
            vagrant: true  # <------------------------ Variable (boolean) !!!
        }
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "inventory"
        ansible.limit = "all"
    end
end

```

```
# playbook.yml
...
- unarchive:
    src=...
    dest=...
    copy=no
```

**Comment by bcoca** [comment]
i'm not sure this is an ansible issue, it looks like its being passed a boolean value as the hos list and reacting accordingly

**Comment by abadger** [comment]
This looks like it is a problem with vagrant doing the wrong things when it invokes ansible.  Going to close it.  If there's more information that you can give that shows how ansible can help out here,, feel free to open a new issue.
