### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_groups'

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1382]
We get the following error with the latest master branch. This used to work well until ansible-0.8-0.git201210141357.

```
TASK: [vsphere_boot host='${esxserver}.${sysdomain}' login='${esxlogin}' password='${esxpassword}' guest='${cmdb_physical_id}' state='poweroff'] *********************
fatal: [system01] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 263, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 326, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 395, in _executor_internal_inner
    delegate_info = inject['hostvars'][delegate_to]
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 90, in __getitem__
    result = self.inventory.get_variables(host)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/__init__.py", line 264, in get_variables
    self._vars_per_host[hostname] = self._get_variables(hostname)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/__init__.py", line 282, in _get_variables
    groups = [ g.name for g in host.get_groups() if g.name != 'all' ]
AttributeError: 'NoneType' object has no attribute 'get_groups'
```

**Comment by dagwieers** [comment]
Fixed by #1385
