### ISSUE TITLE
[2.0] Running ansible as simple user fails

### ISSUE THREAD

**Issue by secured** [ansible/ansible#13830]
If i run any ansible command (direct or playbook) it fails with the following error:

```
$ ansible all -m ping
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 40, in <module>
    from ansible.utils.display import Display
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/display.py", line 49, in <module>
    debug_lock = Lock()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 176, in Lock
    return Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

What could cause this problem? Everything was running fine with 1.9.
Ansible was installied via pip. If i use sudo it works as expected.

```
Debian GNU/Linux 7.9 (wheezy)
2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 GNU/Linux
Python 2.7.3
```

Even this fails :(

```
$ ansible --help
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 40, in <module>
    from ansible.utils.display import Display
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/display.py", line 49, in <module>
    debug_lock = Lock()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 176, in Lock
    return Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

**Comment by secured** [comment]
Found a solution to my problem ^^
Seems like on my vps /dev/shm wasn't configured correctly

http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied

```
rm /dev/shm
mkdir /dev/shm
chmod 777 /dev/shm
nano /etc/fstab
-> none /dev/shm tmpfs rw,nosuid,nodev,noexec 0 0
```

**Comment by pgasiorowski** [comment]
Is there any way to disable this semaphore or multiprocessing completely?
I am getting the same error when trying to run Ansible in AWS Lambda which does not provide shm? Or how do I tell Ansible to use /tmp instead of /dev/shm?
