### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1384]
When running this example playbook:

``` yaml
- hosts: all
  tasks:
  - local_action: debug msg="System $inventory_hostname has uuid $ansible_product_uuid"
  - local_action: debug
  - local_action: debug eval="'1' == '1'" fail=no
  - local_action: debug eval="'1' == '2'" fail=no
  - local_action: debug eval="'1' == '1'"
  - local_action: debug eval="'1' == '2'"
    ignore_errors: True
  - local_action: debug eval="'1' == '2'" fail=yes
    ignore_errors: True
  - local_action: debug eval="'1' == '1'" fail=yes
    ignore_errors: True
  - local_action: debug msg="System $inventory_hostname lacks a gateway" fail=yes
    only_if: "is_unset('${ansible_default_ipv4.gateway}')"
  - local_action: debug msg="System $inventory_hostname has gateway ${ansible_default_ipv4.gateway}"
    only_if: "is_set('${ansible_default_ipv4.gateway}')"
```

I get this error:

```
[root@moria ansible]# ansible-playbook -l loalhost test6.yml

PLAY [all] ********************* 
no hosts matched

PLAY RECAP ********************* 


[root@moria ansible]# ansible-playbook -l localhost test6.yml

PLAY [all] ********************* 

GATHERING FACTS ********************* 
ok: [localhost]

TASK: [debug msg="System $inventory_hostname has uuid $ansible_product_uuid"] ********************* 
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 263, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 326, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 405, in _executor_internal_inner
    conn = self.connector.connect(actual_host, int(actual_port), transport=transport)
TypeError: int() argument must be a string or a number, not 'NoneType'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
localhost                      : ok=1    changed=0    unreachable=1    failed=0    
```

**Comment by dagwieers** [comment]
Fixed by #1383
