### ISSUE TITLE
Looping modifiers in roles may crash in Ansible 2.0

### ISSUE THREAD

**Issue by JScott** [ansible/ansible#13857]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.1
  config file = /Users/justinscott/dev/sauce-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

`vault_password_file` is set to decrypt certain inventory variables.
##### Environment:

I'm pretty sure it doesn't apply but:

```
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F1505
```
##### Summary:

Looping modifiers (`with_items` or `with_subelements`) are crashing out when used in a role where the elements are provided from the playbook as parameters. The python code for a playbook role tries to add an AnsibleSequence to an array but it's "unhashable".
##### Steps To Reproduce:

jscott-test.yml

```

---
- hosts: localhost
  roles:
    - role: jscott-test
      custom_settings:
        - [1, 2]
```

roles/jscott-test/tasks/main.yml

```

---
- debug:
    msg: "{{ item.0 }}"
  with_items:
    - custom_settings
```
##### Expected Results:

I would expect it to print a debug message of `1`.
##### Actual Results:

`ansible-playbook -i inventory jscott-test.yml` crashes out:

```
Unexpected Exception: unhashable type: 'AnsibleSequence'
the full traceback was:

Traceback (most recent call last):
  File "/Users/justinscott/.virtualenvs/ansible2/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 79, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 52, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 92, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/play.py", line 109, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/base.py", line 200, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/play.py", line 211, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/role/__init__.py", line 110, in load
    hashed_params = hash_params(params)
  File "/Users/justinscott/.virtualenvs/ansible2/lib/python2.7/site-packages/ansible/playbook/role/__init__.py", line 62, in hash_params
    s.update((k, tuple(things)))
TypeError: unhashable type: 'AnsibleSequence'
```

As you might expect from the erroring file, it works as expected if the variable is either entirely in the role or entirely in the playbook.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
@JScott one thing I did notice, using the syntax:

<pre>
with_items:
- custom_settings
</pre>

Is not what you want, it should be `"{{custom_settings}}"`, otherwise a "c" will be printed out in the debug (individual items are not templated as bare variables using that form).
