### ISSUE TITLE
Unexpected Exception using ansible-vault

### ISSUE THREAD

**Issue by guybluebat** [ansible/ansible#13855]
I've suddenly started getting an exception when I quit an encrypted file after editing it with ansible-vault. The exception doesn't appear to stop ansible-vault from working ok.

I'm currently using the devel branch, but I did try changing to the stable-2.0 branch and it continued to show this exception.

Here's the full stack trace:

```
Unexpected Exception: non-integer arg 1 for randrange()
the full traceback was:

Traceback (most recent call last):
  File "/Users/guy/Library/ansible/bin/ansible-vault", line 85, in <module>
    sys.exit(cli.run())
  File "/Users/guy/Library/ansible/lib/ansible/cli/vault.py", line 119, in run
    self.execute()
  File "/Users/guy/Library/ansible/lib/ansible/cli/__init__.py", line 99, in execute
    fn()
  File "/Users/guy/Library/ansible/lib/ansible/cli/vault.py", line 155, in execute_edit
    self.editor.edit_file(f)
  File "/Users/guy/Library/ansible/lib/ansible/parsing/vault/__init__.py", line 355, in edit_file
    self._edit_file_helper(filename, existing_data=plaintext, force_save=False)
  File "/Users/guy/Library/ansible/lib/ansible/parsing/vault/__init__.py", line 306, in _edit_file_helper
    self._shred_file(tmp_path)
  File "/Users/guy/Library/ansible/lib/ansible/parsing/vault/__init__.py", line 282, in _shred_file
    self._shred_file_custom(tmp_path)
  File "/Users/guy/Library/ansible/lib/ansible/parsing/vault/__init__.py", line 246, in _shred_file_custom
    chunk_len = random.randint(max_chunk_len/2, max_chunk_len)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 187, in randrange
    raise ValueError, "non-integer arg 1 for randrange()"
ValueError: non-integer arg 1 for randrange()
```

**Comment by guybluebat** [comment]
I have no idea why, but I just used ansible-vault again (to edit the same file) and now I don't get the exception.

I'll leave it open in case you want to investigate, but please feel free to close it otherwise.

**Comment by abadger** [comment]
Hmmm... it's strange that it's non-repeatable but I think I do see the problem.  I'll push a fix in just a moment.

**Comment by abadger** [comment]
This is what the fix will be:  (in `lib/ansible/parsing/valut/__init__.py`):

``` python
-                chunk_len = random.randint(max_chunk_len/2, max_chunk_len)
+                chunk_len = random.randint(max_chunk_len//2, max_chunk_len)
```

**Comment by abadger** [comment]
Fix pushed to devel and to stable-2.0.  It will be in the next 2.0.x release of ansible.

**Comment by guybluebat** [comment]
Fast work, thanks!

**Comment by kpx-dev** [comment]
Hi guys, I'm having same issue on 

```
$ansible --version
ansible 2.1.0
```

I edit my vault file like this:
`ansible-vault edit --vault-password-file=.vault_pass.txt group_vars/staging/vault.yml`

And when save, I get error: 
`Unexpected Exception: non-integer arg 1 for randrange()`
