### ISSUE TITLE
2.0.0.1 error AttributeError: 'module' object has no attribute '_vendor'

### ISSUE THREAD

**Issue by n2aws** [ansible/ansible#13867]
After upgrading to ansible 2.0.0.1 on ubuntu wily, (fully dist-upgraded) I started getting the following error:

$ ansible --version
Unexpected Exception: 'module' object has no attribute '_vendor'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 74, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/lib/pymodules/python2.7/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_queue_manager.py", line 29, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/lib/pymodules/python2.7/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/lib/pymodules/python2.7/ansible/playbook/**init**.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/lib/pymodules/python2.7/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/usr/lib/pymodules/python2.7/ansible/parsing/dataloader.py", line 33, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/lib/pymodules/python2.7/ansible/parsing/vault/**init**.py", line 66, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/**init**.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 90, in <module>
    packaging = pkg_resources._vendor.packaging
AttributeError: 'module' object has no attribute '_vendor'

**Comment by n2aws** [comment]
In working to debug this issue,  I found that I have both python-crytpo as well as python-cryptography installed.    If I apt-get remove python-cryptography, ansible begins working as expected.

It appears as though there is a conflict between these two modules,  potentially in function names or something that causes a conflict with ansible when both are installed.

The immediate workaround it to remove python-cryptography.

**Comment by SAL-e** [comment]
Thanks palmerit for your investigation, unfortunately for me the workaround will not work because ubuntu-desktop and other desktop packages depend on python-cryptography. This will work on CLI only install.

**Comment by abadger** [comment]
Okay, see if `apt-get install  python-setuptools` fixes this for you.

**Comment by abadger** [comment]
Corresponded via IRC and that does indeed fix the issue.  I've added python-setuptools to the debian control file for when we build our next package for the PPA.  6c0b4bc56e507b8ead48e5b3a3c8ffbc55a72f74

Merged to both devel and stable-2.0 branches.

**Comment by mattclay** [comment]
In case anyone runs into this same error, but installing python-setuptools doesn't help...

I encountered this same error running from devel, but I already had python-setuptools installed (version 18.4-1 according to apt). However, installing the latest setuptools version 20.2.2 revealed the actual problem:

```
root@ubuntu-wily-amd64-os:~# ansible --version
ERROR! Unexpected Exception: The 'paramiko' distribution was not found and is required by ansible
the full traceback was:

Traceback (most recent call last):
  File "/root/ansible/bin/ansible", line 75, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/root/ansible/lib/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/root/ansible/lib/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/root/ansible/lib/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/root/ansible/lib/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/root/ansible/lib/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/root/ansible/lib/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/root/ansible/lib/ansible/parsing/dataloader.py", line 32, in <module>
    from ansible.parsing.vault import VaultLib
  File "/root/ansible/lib/ansible/parsing/vault/__init__.py", line 67, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2912, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2898, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 642, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 830, in resolve
DistributionNotFound: The 'paramiko' distribution was not found and is required by ansible
```

I was running from source I didn't have python-paramiko installed. Installing python-paramiko resolved the issue. Uninstalling python-cryptography also worked, but wasn't a good solution since it's needed by other packages.

**Comment by toshiueno** [comment]
@palmerit I've removed python-cryptography and python-json and it worked for me. Tks

**Comment by henderbj** [comment]
I fixed this problem by removing cryptography from pip:
`root@server:~# pip list | egrep -i crypt`
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.22.0)
bcrypt (3.1.3)
cryptography (2.0.3)
pycrypto (2.6.1)
`root@server:~# pip uninstall cryptography`
...
Proceed (y/n)? y
  Successfully uninstalled cryptography-2.0.3
`root@server:~# `

I hope it helps someone.

**Comment by rosinwang** [comment]
I had the same issue on mac OS. After reinstall or upgrade the cryptography package, the problem resolved.
```
sudo pip uninstall cryptography
sudo pip install cryptography
```
