### ISSUE TITLE
Threadsafety with Ansible Python API

### ISSUE THREAD

**Issue by hacpai** [ansible/ansible#13903]
When I call ansible 2.0 API with multithreading,  sometimes it will prompt the error information:

```
the exc type is: <type 'exceptions.AttributeError'>
 the exc value is: 'module' object has no attribute 'CacheModule'
the exc tb is: <traceback object at 0x103edf5f0>
Traceback (most recent call last):
  File "/Users/wenhui/iDev/ceres/ceres/utils.py", line 67, in run
the exc type is: <type 'exceptions.AttributeError'>
    do(args)
  File "/Users/wenhui/iDev/ceres/ceres/utils.py", line 169, in run_ansible
    callback=callback.PlutoCallbackModule())
  File "/Users/wenhui/iDev/ceres/ceres/task.py", line 40, in __init__
the exc value is: 'module' object has no attribute 'CacheModule'
the exc tb is: <traceback object at 0x103edf710>
Traceback (most recent call last):
  File "/Users/wenhui/iDev/ceres/ceres/utils.py", line 67, in run
    do(args)
  File "/Users/wenhui/iDev/ceres/ceres/utils.py", line 169, in run_ansible
    callback=callback.PlutoCallbackModule())
  File "/Users/wenhui/iDev/ceres/ceres/task.py", line 40, in __init__
    self.variable_manager = VariableManager()
  File "/usr/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 92, in __init__
    self.variable_manager = VariableManager()
  File "/usr/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 92, in __init__
    self._fact_cache = FactCache()
    self._fact_cache = FactCache()
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 35, in __init__
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 35, in __init__
    self._plugin = cache_loader.get(C.CACHE_PLUGIN)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 331, in get
    self._plugin = cache_loader.get(C.CACHE_PLUGIN)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 331, in get
    obj = getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
AttributeError: 'module' object has no attribute 'CacheModule'
    obj = getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
AttributeError: 'module' object has no attribute 'CacheModule'
/Users/wenhui/iDev/ecs-ansible/roles/common/files/keys/10-85-0-13.pem
the exc type is: <type 'exceptions.AttributeError'>
the exc value is: 'module' object has no attribute 'StrategyModule'
the exc tb is: <traceback object at 0x10485bb00>
Traceback (most recent call last):
  File "/Users/wenhui/iDev/ceres/ceres/utils.py", line 67, in run
    do(args)
  File "/Users/wenhui/iDev/ceres/ceres/utils.py", line 170, in run_ansible
    result = ansible_task.run()
  File "/Users/wenhui/iDev/ceres/ceres/task.py", line 134, in run
    result = tqm.run(play)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 239, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 331, in get
    obj = getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
AttributeError: 'module' object has no attribute 'StrategyModule'
```

How can I fix this?

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by bcoca** [comment]
So Ansible is NOT thread safe, it uses multiprocessing not multi-threading, calling Ansible from withing a threaded environment is NOT expected to work. This is now documented in the developer API page.
