### ISSUE TITLE
ec2_elb_facts invalid literal int() with base 10

### ISSUE THREAD

**Issue by robmessick** [ansible/ansible#13928]
Running ec2_elb_facts through a playbook generates the error below.

ansible 2.0.0.2
boto 2.38.0

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/robm/.ansible/tmp/ansible-tmp-1452917234.12-163996366850200/ec2_elb_facts", line 2357, in <module>
    main()
  File "/Users/robm/.ansible/tmp/ansible-tmp-1452917234.12-163996366850200/ec2_elb_facts", line 193, in main
    list_elb(connection, module)
  File "/Users/robm/.ansible/tmp/ansible-tmp-1452917234.12-163996366850200/ec2_elb_facts", line 165, in list_elb
    elb_array.append(get_elb_info(elb))
  File "/Users/robm/.ansible/tmp/ansible-tmp-1452917234.12-163996366850200/ec2_elb_facts", line 144, in get_elb_info
    'health_check': get_health_check(elb.health_check),
  File "/Users/robm/.ansible/tmp/ansible-tmp-1452917234.12-163996366850200/ec2_elb_facts", line 124, in get_health_check
    'ping_port': int(port),
ValueError: invalid literal for int() with base 10: '443/healthtest/'
```

```
- hosts: localhost
  tasks:
    - action:
        module: ec2_elb_facts
        region: us-west-2
      register: elb_facts
```

**Comment by robmessick** [comment]
This can be closed as duplicate of https://github.com/ansible/ansible-modules-extras/issues/1421
