### ISSUE TITLE
Error when ansible config path contains unicode characters

### ISSUE THREAD

**Issue by dmromanov** [ansible/ansible#13937]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.2
  config file = /home/dmromanov/пример/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
hostfile = hosts
```
##### Environment:

Ubuntu 15.10
Python 2.7.10
##### Summary:

If path to Ansible project directory contains non-ascii characters running Ansible will fail.
##### Steps To Reproduce:
1. create project directory containing non-unicode characters /home/dmromanov/пример/
2. create ansible.cfg, deploy.yml and hosts files in that directory

./deploy.yml

```

---
- hosts: all
  tasks:
  - shell: echo 'test'
```

./ansible.cfg

```
[defaults]
hostfile = hosts
```

./hosts

```
[test]
localhost
```
1. Run provision `ansible-playbook deploy.yml`
##### Expected Results:

```
 ______
< PLAY >
 ------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ______________
< TASK [setup] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=0    changed=0    unreachable=1    failed=0   
```
##### Actual Results:

```
$ ansible-playbook deploy.yml -vvv
Unexpected Exception: 'ascii' codec can't decode byte 0xd0 in position 22: ordinal not in range(128)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/pymodules/python2.7/ansible/cli/playbook.py", line 89, in run
    super(PlaybookCLI, self).run()
  File "/usr/lib/pymodules/python2.7/ansible/cli/__init__.py", line 108, in run
    display.display("Using %s as config file" % C.CONFIG_FILE)
  File "/usr/lib/pymodules/python2.7/ansible/utils/display.py", line 119, in display
    if not msg.endswith(u'\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 22: ordinal not in range(128)
```

**Comment by abadger** [comment]
I've got an easy fix for this traceback but it immediately leads to another traceback that's harder to solve.  The path that the playbook is in gets stored and used in a bunch of path manipulations.  These will have to all use byte strings or all use unicode strings otherwise we'll get tracebacks from them.

**Comment by abadger** [comment]
Fix for utf8 directory names added above and pushed to both devel and stable-2.0.  So it should be in 2.0.1 when we release that.

@dmromanov could you verify that the commit works?  (There is a caveat that non-utf8 will still not work so I'd like to make sure you that isn't the scenario that you are experiencing.)

**Comment by dmromanov** [comment]
@abadger Sure.

**Comment by dmromanov** [comment]
@abadger Works for me. Tested on ansible 2.1.0 (devel e3a6accc1d)

**Comment by joaocc** [comment]
Hi.
It doesn't seem to be solver on 2.1.0.0 on Ubuntu and OS-X.
Strangely enough, it works on Alpine 3.4

```
$ ansible --version
ansible 2.1.0.0

$ wget https://github.com/ansible/ansible/archive/stable-2.1.zip
...
2016-06-11 18:59:01 (596 KB/s) - 'stable-2.1.zip' saved [2276006/2276006]

$ ansible all -c local -i localhost, -m unarchive -a 'src=./stable-2.1.zip dest=.' -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: joaocc
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465667974.35-234723768403765 `" && echo ansible-tmp-1465667974.35-234723768403765="` echo $HOME/.ansible/tmp/ansible-tmp-1465667974.35-234723768403765 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465667974.5-138013658396661 `" && echo ansible-tmp-1465667974.5-138013658396661="` echo $HOME/.ansible/tmp/ansible-tmp-1465667974.5-138013658396661 `" ) && sleep 0'
<localhost> PUT /var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/tmp7zJDMJ TO /Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.5-138013658396661/stat
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.5-138013658396661/stat; rm -rf "/Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.5-138013658396661/" > /dev/null 2>&1 && sleep 0'
<localhost> PUT /private/tmp/aaa/stable-2.1.zip TO /Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.35-234723768403765/source
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465667974.93-152080169563452 `" && echo ansible-tmp-1465667974.93-152080169563452="` echo $HOME/.ansible/tmp/ansible-tmp-1465667974.93-152080169563452 `" ) && sleep 0'
<localhost> PUT /var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/tmp1_3rHy TO /Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.93-152080169563452/unarchive
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.93-152080169563452/unarchive; rm -rf "/Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.93-152080169563452/" > /dev/null 2>&1 && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.35-234723768403765/ > /dev/null 2>&1 && sleep 0'
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "copy": true,
            "creates": null,
            "delimiter": null,
            "dest": ".",
            "directory_mode": null,
            "exclude": [],
            "extra_opts": [],
            "follow": false,
            "force": null,
            "group": null,
            "keep_newer": false,
            "list_files": false,
            "mode": null,
            "original_basename": "stable-2.1.zip",
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/Users/joaocc/.ansible/tmp/ansible-tmp-1465667974.35-234723768403765/source"
        }
    },
    "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: './ansible-stable-2.1/test/integration/roles/test_unarchive/files/test-unarchive-nonascii-a\\xcc\\x80a\\xcc\\x82\\xc3\\xa6c\\xcc\\xa7e\\xcc\\x81e\\xcc\\x80i\\xcc\\x88i\\xcc\\x82o\\xcc\\x82\\xc5\\x93.tar.gz'"
}
```
