### ISSUE TITLE
URI module fails with variables in the JSON body

### ISSUE THREAD

**Issue by gbarnard2** [ansible/ansible#13954]
The following task in a playbook errors because of the body option. If you replace the username and password variables with hard coded values, it works fine. Note my version was the one just before 2.0 was released. (Formatting is correct, but doesn't come out well in web app).

  -- name: Connect to ansible with creds provided
    uri:
      url: https://{{ url }}/api/v1/authtoken/
      method: POST
      HEADER_Content-Type: application/json 
      body: '{ "username" : "{{ username }}", "password" : "{{ password }}" }'
      validate_certs: no
      return_content: yes

The following output from Ansible:

TASK: [Connect to ansible with creds provided] ********************************
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/gbarnard/.ansible/tmp/ansible-tmp-1452538099.69-278641758230235/uri", line 2081, in <module>
    main()
  File "/home/gbarnard/.ansible/tmp/ansible-tmp-1452538099.69-278641758230235/uri", line 416, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeut, validate_certs)
  File "/home/gbarnard/.ansible/tmp/ansible-tmp-1452538099.69-278641758230235/uri", line 312, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/httplib2/**init**.py", line 1605, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cacekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1353, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1290, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 839, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 811, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/ssl.py", line 723, in sendall
    v = self.send(data[count:])
TypeError: unhashable type

FATAL: all hosts have already failed -- aborting

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
