### ISSUE TITLE
An exception is thrown when displaying another exception backtrace

### ISSUE THREAD

**Issue by dmromanov** [ansible/ansible#14042]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.1.0 (devel 627dec716b) last updated 2016/01/21 12:46:03 (GMT +300)
  lib/ansible/modules/core: (detached HEAD d7fac82f97) last updated 2016/01/21 12:46:12 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD f798240f43) last updated 2016/01/21 12:46:18 (GMT +300)
  config file = /home/dromanov/ansible-test/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
hostfile = hosts
```
##### Environment:

Ubuntu 15.10
Python 2.7.10
##### Summary:

If Ansible is installed in path containing unicode character, trying to display a backtrace of exception (like in #14041) will produce another exception.
##### Steps To Reproduce:
1. install Ansible in path containg unicode characters (e.g. /home/dromanov/пример/ansible)
2. create a playbook that triggers exception (#14041 for example)
3. run playbook in verbose mode
##### Expected Results:

```
$ ansible-playbook deploy.yml -vvvv
...
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/dromanov/ansible/lib/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/home/dromanov/ansible/lib/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/dromanov/ansible/lib/ansible/executor/task_executor.py", line 410, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/dromanov/ansible/lib/ansible/plugins/action/synchronize.py", line 248, in run
    if 'SyntaxError' in result['msg']:
KeyError: 'msg'

fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

```
##### Actual Results:

```
$ ansible-playbook deploy.yml -vvvv
...
ERROR! Unexpected Exception: 'ascii' codec can't decode byte 0xd0 in position 71: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/dromanov/пример/ansible/bin/ansible-playbook", line 111, in <module>
    display.display("the full traceback was:\n\n%s" % traceback.format_exc())
  File "/home/dromanov/пример/ansible/lib/ansible/utils/display.py", line 119, in display
    if not msg.endswith(u'\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 83: ordinal not in range(128)
```

**Comment by abadger** [comment]
Fixed and pushed to devel and stable-2.0
