### ISSUE TITLE
[2.0.0.2] LookupError: unknown encoding

### ISSUE THREAD

**Issue by steenzout** [ansible/ansible#14053]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible-playbook 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None.
##### Environment:

N/A.
##### Summary:

Problem while converting an object into a byte :class:`str`.
It seems in some cases of AnsibleParserError the message doesn't get printed but a stack trace is printed instead.
##### Steps To Reproduce:

Not clear.
##### Expected Results:

A failure message printed on the screen.
##### Actual Results:

```
   # Could use isbasestring, isbytestring here but we want this to be as fast
    # as possible
    if isinstance(obj, basestring):
        if isinstance(obj, binary_type):
            return obj  # line 207
        print('encoding=%s type=%s\terrors=%s type=%s' % (repr(encoding), type(encoding), repr(errors), type(errors)))  # added
        return(obj.encode(encoding, errors))  # former line 208 (now 209)
    if not nonstring:
        nonstring = 'simplerepr'
```

The problem happens on `except AnsibleParserError as e:` in the ansible-playbook:

```
encoding='utf-8' type=<type 'str'>  errors='replace' type=<type 'str'>
encoding='' type=<type 'str'>   errors='replace' type=<type 'str'>
encoding='utf-8' type=<type 'str'>  errors='replace' type=<type 'str'>
e2=ERROR! The handlers/main.yml file for role 'myrole' must contain a list of tasks

- include: debug.yml
^ here

encoding='' type=<type 'str'>   errors='replace' type=<type 'str'>
Traceback (most recent call last):
  File "/path2virtualenv/myrole/.tox/ansible2002/bin/ansible-playbook", line 94, in <module>
    display.error(to_unicode(e), wrap_text=False)
  File "/path2virtualenv/myrole/.tox/ansible2002/lib/python2.7/site-packages/ansible/utils/display.py", line 261, in error
    self.display(new_msg, color='red', stderr=True)
  File "/path2virtualenv/myrole/.tox/ansible2002/lib/python2.7/site-packages/ansible/utils/display.py", line 124, in display
    msg2 = to_bytes(msg2, encoding=self._output_encoding(stderr=stderr))
  File "/path2virtualenv/myrole/.tox/ansible2002/lib/python2.7/site-packages/ansible/utils/unicode.py", line 209, in to_bytes
    return(obj.encode(encoding, errors))
LookupError: unknown encoding:
```

or on a `except Exception as e:` of ansible-playbook:

```
# the next 4 lines are from the debug statement I added
encoding='utf-8' type=<type 'str'>  errors='replace' type=<type 'str'>
encoding='' type=<type 'str'>   errors='replace' type=<type 'str'>
encoding='utf-8' type=<type 'str'>  errors='replace' type=<type 'str'>
encoding='' type=<type 'str'>   errors='replace' type=<type 'str'>
Traceback (most recent call last):
  File "/path2virtualenv/myrole/.tox/ansible2002/bin/ansible-playbook", line 92, in <module>
    display.error(to_unicode(e), wrap_text=False)
  File "/path2virtualenv/myrole/.tox/ansible2002/lib/python2.7/site-packages/ansible/utils/display.py", line 261, in error
    self.display(new_msg, color='red', stderr=True)
  File "/path2virtualenv/myrole/.tox/ansible2002/lib/python2.7/site-packages/ansible/utils/display.py", line 124, in display
    msg2 = to_bytes(msg2, encoding=self._output_encoding(stderr=stderr))
  File "/path2virtualenv/myrole/.tox/ansible2002/lib/python2.7/site-packages/ansible/utils/unicode.py", line 209, in to_bytes
    return(obj.encode(encoding, errors))
LookupError: unknown encoding: 
```

**Comment by steenzout** [comment]
I've setup a repo to replicate the problem with a single command: https://github.com/steenzout/ansible-issue-14053

**Comment by steenzout** [comment]
if I add these environment variables (could be other variables) the problem is solved:

```
+setenv=
+    LANG=en_US.UTF-8
+    LC_ALL=en_US.UTF-8
```
