### ISSUE TITLE
ansible 2.0.0.2 : winrm UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by dacr** [ansible/ansible#14077]
Can't use ansible windows support through winrm, encoding character issue, the full error message :  

```
$ ansible --version
ansible 2.0.0.2

$ ansible xxxxxx -vvv -m win_ping
Using /xxxxxxx/ansible.cfg as config file
<xxxxx> ESTABLISH WINRM CONNECTION FOR USER: xxxxx on PORT 5985 TO xxxxxx
<xxxxx> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1453467080.37-30169280583037").FullName | Write-Host -Separator '';
<xxxxxx> PUT "/tmp/tmpslyHoz" TO "\ufeffC:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1453467080.37-30169280583037\win_ping.ps1"
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/opt/ansible/lib/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/opt/ansible/lib/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/opt/ansible/lib/ansible/executor/task_executor.py", line 401, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/opt/ansible/lib/ansible/plugins/action/__init__.py", line 406, in _execute_module
    self._transfer_data(remote_module_path, module_data)
  File "/opt/ansible/lib/ansible/plugins/action/__init__.py", line 278, in _transfer_data
    self._connection.put_file(afile, remote_path)
  File "/opt/ansible/lib/ansible/plugins/connection/winrm.py", line 304, in put_file
    script = script_template.format(self._shell._escape(out_path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

vault | FAILED! => {
    "failed": true, 
    "stdout": ""
}
```

**Comment by jhawkesworth** [comment]
For some reason you are getting a byte order mark \ufeff at the start of the destination 

```
<xxxxxx> PUT "/tmp/tmpslyHoz" TO "\ufeffC:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1453467080.37-30169280583037\win_ping.ps1"
```

It seems likely then that it is specific either to the host you are running ansible on or the windows machine.

What OS are you running on the controller and windows machine?
What locale is set?
Do you have any language packs in place on the windows machine?

**Comment by jhawkesworth** [comment]
Also of interest would be python version you are running and how ansible was installed (pip, rpm etc)

The issue template is a good starting point for these things actually: https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md

**Comment by dacr** [comment]
##### Ansible Version:

2.0.0.2

##### Ansible Configuration:

default one

##### Environment:

Where ansible is executed : 
- gentoo 4.0.5-gentoo #2 SMP Mon Jul 20 13:33:56 CEST 2015 x86_64 Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz GenuineIntel GNU/Linux
- Python 2.7.10
- LANG=fr_FR.utf8
- ansible was installed from the tar (tar xvfz ansible-2.0.0.2.tar.gz and installed in /opt). For the config, I execute  `export ANSIBLE_CONFIG=$(pwd)/ansible.cfg` from my current project working directory.

About the Windows host : 
- Windows Server 2008R2 Service Pack1 64bits the user interface is in english.
  - Current Location : France
  - Language pack : English (English)

**Comment by dacr** [comment]
I've made a try with newer python releases, but with those new releases I got other errors more linked to python 3.x support : 

```
yyy@zzz ~/xxxx $ eselect python list
Available Python interpreters:
  [1]   python2.7 *
  [2]   python3.3
  [3]   python3.4

yyy@zzz ~/xxxx $ sudo su -
Password: 
yyy ~ # eselect python set 2
yyy ~ # exit
déconnexion
yyy@zzz ~/xxxx $ python --version
Python 3.3.5
yyy@zzz ~/xxxx $ ansible vault -m win_ping
Unexpected Exception: 'ImportError' object has no attribute 'message'
the full traceback was:

Traceback (most recent call last):
  File "/opt/ansible/bin/ansible", line 74, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/opt/ansible/lib/ansible/cli/__init__.py", line 27, in <module>
    import yaml
ImportError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ansible/bin/ansible", line 78, in <module>
    if e.message.endswith(' %s' % sub):
AttributeError: 'ImportError' object has no attribute 'message'
yyy@zzz ~/xxxx $ sudo su -
yyy ~ # eselect python set 3
yyy ~ # déconnexion
yyy@zzz ~/xxxx $ python --version
Python 3.4.3
yyy@zzz ~/xxxx $ ansible vault -m win_ping
Unexpected Exception: name 'basestring' is not defined
to see the full traceback, use -vvv
```

I've also made a try by setting current LANG to en : 

```
>python --version
Python 2.7.10
>export LANG=en
>ansible vault -m win_ping
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
vault | FAILED! => {
    "failed": true, 
    "stdout": ""
}
```

**Comment by abadger** [comment]
I'm not sure if the byte order mark is supposed to be there or not but we did recently make a change that i think will get rid of the unicode exception: https://github.com/ansible/ansible/commit/45355cd5660da17350811d92a5144077910ea434

If you'd care to try that and it works I could push it to the stable-2.0 branch for inclusion in the next 2.0.x release.

**Comment by dacr** [comment]
I've applied this small patch, but I still get an error, a new one : 

```
$ ansible vault -vvv  -m win_ping
Using xxxxxxx/201601/ansible.cfg as config file
<xxxxxxx> ESTABLISH WINRM CONNECTION FOR USER: xxxxxxx on PORT 5985 TO xxxxxxx
<xxxxxx> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1453496187.31-183760398244670").FullName | Write-Host -Separator '';
<xxxxxx> PUT "/tmp/tmpVu5dmt" TO "﻿C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1453496187.31-183760398244670\win_ping.ps1"
vault | FAILED! => {
    "failed": true, 
    "msg": "ERROR! ﻿#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">Exception calling \"Create\" with \"1\" argument(s): \"The given path's format is no_x000D__x000A_</S><S S=\"Error\">t supported.\"_x000D__x000A_</S><S S=\"Error\">At line:6 char:31_x000D__x000A_</S><S S=\"Error\">+ $fd = [System.IO.File]::Create &lt;&lt;&lt;&lt; ($path)_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE _x000D__x000A_</S><S S=\"Error\">   xception_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>"
}

```

looks like something wrong with the content of $path in my case : 

```
                $fd = [System.IO.File]::Create($path)
```

**Comment by abadger** [comment]
<nod>  Okay, so I will merge the previous commit to stable-2.0 but you'll want to continue talking with @jhawkesworth  and @mdavis if he gets a chance to look at this since the unicode error seems somewhat superficial to what's really going on here.

**Comment by jhawkesworth** [comment]
So the failure now appears to be because the path that is getting presented
to [System.IO.File]::Create is, in some way, mangled.  Not obvious what
though as

C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1453496187.31-183760398244670\win_ping.ps1

looks to me like an acceptable windows path.

Could you run with a -vvvvv to see if you can get all of the error message
in the CLIXML part of the response?  It might give us a clue why the path
is unacceptable to [System.IO.File]::Create

Pinging @nitzmahone (M Davis' github id) in case he has any insights
(perhaps where he came across the need to introduce
https://github.com/ansible/ansible/commit/45355cd5660da17350811d92a5144077910ea434

I don't have a gentoo box to try this on for myself unfortunately.

Incidentally I would stick with python 2.X as I believe support for python
3 is on the roadmap but a goal for some time after Ansible 2.0 - that's for
Ansible staff to say though.

Jon

**Comment by dacr** [comment]
the output result with -vvvvv flag, python 2.7.10, and [45355cd](https://github.com/ansible/ansible/commit/45355cd5660da17350811d92a5144077910ea434) still applied : 

```
$ ansible vault -vvvvv  -m win_ping
Using xxxxxxx/201601/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<xxxx> ESTABLISH WINRM CONNECTION FOR USER: winxxxx on PORT 5985 TO xxxx
<xxxx> WINRM CONNECT: transport=plaintext endpoint=http://xxxx:5985/wsman
<xxxx> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1453638785.98-207349378673732").FullName | Write-Host -Separator '';
<xxxx> WINRM OPEN SHELL: 42F11E5F-F328-457F-8C0C-67DFC39E7AB8
<xxxx> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADMANgAzADgANwA4ADUALgA5ADgALQAyADAANwAzADQAOQAzADcAOAA2ADcAMwA3ADMAMgAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA=']
<xxxx> WINRM RESULT u'<Response code 0, out "\ufeffC:\\Users\\Administ", err "">'
<xxxx> PUT "/tmp/tmpRnkoNI" TO "﻿C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1453638785.98-207349378673732\win_ping.ps1"
<xxxx> WINRM PUT "/tmp/tmpRnkoNI" to "﻿C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1453638785.98-207349378673732\win_ping.ps1" (offset=8547 size=8547)
<xxxx> WINRM CLOSE SHELL: 42F11E5F-F328-457F-8C0C-67DFC39E7AB8
vault | FAILED! => {
    "failed": true, 
    "msg": "ERROR! ﻿#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">Exception calling \"Create\" with \"1\" argument(s): \"The given path's format is no_x000D__x000A_</S><S S=\"Error\">t supported.\"_x000D__x000A_</S><S S=\"Error\">At line:6 char:31_x000D__x000A_</S><S S=\"Error\">+ $fd = [System.IO.File]::Create &lt;&lt;&lt;&lt; ($path)_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE _x000D__x000A_</S><S S=\"Error\">   xception_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>"
```

**Comment by nitzmahone** [comment]
The BOM should definitely not be in there, and is almost certainly the reason that the path creation is failing, but I have no clue where it's coming from. There also seems to be some other cruft I wasn't expecting to see in the second batch. @dacr- any chance you have a Red Hat-flavored machine you could try this from, and install 2.0 with yum via epel-testing? Just trying to cut down some variables here...

**Comment by ladislashornok** [comment]
Hi, I'm a new user of Ansible. But I seem to have the same problem with a Windows 2008R2 SP1 64-bit server that has the version 2 of PowerShell. I have another server with Windows 2012 and a version 4 of Powershell. It works well. I'm not sure, but maybe does this relate to the version of Powershell ?

**Comment by jhawkesworth** [comment]
hi @ladislashornok - ansible only works with powershell 3.0 or higher, so yours is a different issue I think.  Please see http://docs.ansible.com/ansible/intro_windows.html#windows-system-prep

I would advise installing Windows Management Framework 4.0 if possible because on Server 2008 R2 machines, due to a bug in Windows Management Framework 3.0, it may be necessary to install this hotfix http://support.microsoft.com/kb/284223

By the way, the best places to ask user questions are on the ansible project google group or in the #ansible irc channel.

**Comment by jhawkesworth** [comment]
Going back to the reported issue, just wondering if changing
LANG=fr_FR.utf8
to something like
LANG=en_US.UTF-8
temporarily is worth trying to see if that is causing the Byte Order Mark to be added.
Might be another way to narrow down the cause.

**Comment by alv000h** [comment]
I confirm this issue is repeteable under Powershell v2 (Windows 2008 R2). 
**Environment:**
RHEL 6.6
Python 2.6.6
Powershell v2 (Not works with Ansible as stated above)
ansible --version 
51584 1454424947.69794: starting run ansible 2.1.0 (devel 6105c8c77c) last updated 2016/02/02 15:48:23 (GMT +200) lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/02/01 18:29:25 (GMT +200) lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/02/01 18:29:40 (GMT +200) config file = /etc/ansible/ansible.cfg configured module search path = Default w/o override

**Relevant output.**
RAW module  (returns Powershell Version)
`$ ansible -i host all -m raw -a "PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command write-host \$PSVersionTable.PSVersion"
wintel.local | SUCCESS | rc=0 >>
2.0`

WIN_PING Module
`$ ansible -i host all -m win_ping
wintel.local | FAILED! => {
    "failed": true,
    "msg": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">Exception calling \"Create\" with \"1\" argument(s): \"The given path's format is no_x000D__x000A_</S><S S=\"Error\">t supported.\"_x000D__x000A_</S><S S=\"Error\">At line:6 char:31_x000D__x000A_</S><S S=\"Error\">+ $fd = [System.IO.File]::Create &lt;&lt;&lt;&lt; ($path)_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE _x000D__x000A_</S><S S=\"Error\">   xception_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>"`

**Personal Ruminations:**
Ansible Documentation states that it only works with Poweshell v3 and higher.
Maybe could be possible check the Powershell version within win_ping module and suggest upgrade it???

**Comment by nitzmahone** [comment]
@dacr: can you confirm that you're running at least Powershell v3?

@alv000h: The current state of the world is that we just don't work with Powershell v2 at all- full stop. We can't have modules check the version, because the underlying infrastructure that Ansible uses to run modules remotely doesn't work against Powershell v2 (thus a chicken-and-egg problem exists). 

I've played with some different ways to use Ansible to bootstrap older machines up to at least Powershell v3, but don't have anything stable enough to share at the moment. For now, we'll have to stick to the party line of "PS3 minimum"...

**Comment by jbarascut** [comment]
No solution if I have only powershell 2 and I can't upgrade?

**Comment by CharlieC3** [comment]
I'm getting the same error using Powershell 4 with Ansible 2.0.1.0.

**Comment by nitzmahone** [comment]
@jbarascut Sorry, no, Ansible requires PS3+.

**Comment by nitzmahone** [comment]
closing for inactivity, cannot reproduce

**Comment by PeterMartini** [comment]
https://github.com/WinRb/WinRM/blob/master/changelog.md implies this is a regression specific to Windows 2008 R2

**Comment by alexoj** [comment]
I'm having this problem as well, the BOM comes from the temp environment variable fetch request (this line in the log: (New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1453467080.37-30169280583037").FullName | Write-Host -Separator '';)

You can see that it's sent by the winrm server itself:
http://i.imgur.com/LZTwdfK.png

Ansible runs .strip() on that string somewhere along the way but .strip() does nothing to BOMs

EDIT: Nevermind, disregard this, the damn thing said it installed powershell 3 but didn't. Problem went away after installing it manually.

**Comment by nitzmahone** [comment]
I'm playing with adding a sub-PS3 check directly to our module exec wrapper so we can fail more gracefully on ancient Powershell versions... We can do it very cheaply- the biggest issue is just keeping the wrapper size well under the EncodedCommand limit (unless we switch to PSRP, which presents its own issues), as well as ensuring that the module wrapper will execute far enough to return the check.
