### ISSUE TITLE
Install on Debian using pip have missing packages

### ISSUE THREAD

**Issue by pmarques** [ansible/ansible#14083]
I have installed Ansible on Debian jessie 8.1 (minimal installation) but doesn't run unless you install two more dependencies one of them are not referenced anywhere, I don't know if I've missed anything, if is just a documentation issue or if someone forgot a dependency.

```
$ sudo pip install ansible

Downloading/unpacking ansible
  Downloading ansible-2.0.0.2.tar.gz (1.5MB): 1.5MB downloaded
  Running setup.py (path:/tmp/pip-build-YUcG46/ansible/setup.py) egg_info for package ansible

    no previously-included directories found matching 'v2'
    no previously-included directories found matching 'docsite'
    no previously-included directories found matching 'ticket_stubs'
    no previously-included directories found matching 'packaging'
    no previously-included directories found matching 'test'
    no previously-included directories found matching 'hacking'
    warning: no previously-included files found matching 'lib/ansible/modules/core/.git*'
    warning: no previously-included files found matching 'lib/ansible/modules/extras/.git*'
    no previously-included directories found matching 'lib/ansible/modules/core/.git'
    no previously-included directories found matching 'lib/ansible/modules/extras/.git'
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python2.7/dist-packages (from ansible)
Installing collected packages: ansible
  Running setup.py install for ansible
    changing mode of build/scripts-2.7/ansible from 644 to 755
    changing mode of build/scripts-2.7/ansible-playbook from 644 to 755
    changing mode of build/scripts-2.7/ansible-pull from 644 to 755
    changing mode of build/scripts-2.7/ansible-doc from 644 to 755
    changing mode of build/scripts-2.7/ansible-galaxy from 644 to 755
    changing mode of build/scripts-2.7/ansible-vault from 644 to 755

    no previously-included directories found matching 'v2'
    no previously-included directories found matching 'docsite'
    no previously-included directories found matching 'ticket_stubs'
    no previously-included directories found matching 'test'
    no previously-included directories found matching 'hacking'
    warning: no previously-included files found matching 'lib/ansible/modules/core/.git*'
    warning: no previously-included files found matching 'lib/ansible/modules/extras/.git*'
    no previously-included directories found matching 'lib/ansible/modules/core/.git'
    no previously-included directories found matching 'lib/ansible/modules/extras/.git'
    changing mode of /usr/local/bin/ansible-doc to 755
    changing mode of /usr/local/bin/ansible-vault to 755
    changing mode of /usr/local/bin/ansible-galaxy to 755
    changing mode of /usr/local/bin/ansible-pull to 755
    changing mode of /usr/local/bin/ansible-playbook to 755
    changing mode of /usr/local/bin/ansible to 755
Successfully installed ansible
Cleaning up...
```

```
$ ansible --version
```

```
Unexpected Exception: No module named markupsafe
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 74, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 29, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 32, in <module>
    from jinja2.exceptions import UndefinedError
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

Then I have to install tow other packages, 
Jinja 2 install instructions http://jinja.pocoo.org/docs/dev/intro/#installation says that "As of version 2.7 Jinja2 depends on the MarkupSafe module. If you install Jinja2 via pip or easy_install it will be installed automatically for you." but it wasn't.

```
$ pip install markupsafe
$ pip install ecdsa
```

Extra info

```
$ python --version
Python 2.7.9

$ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by sivel** [comment]
markupsafe is indeed a dependency of jinja2, and should have been installed, with the initia install of jinja2.

In the logs you provide jinaj2 was already installed, as such it did not attempt to install deps for jinja2.

Your initial install of jinja2 and markupsafe must have failed and not been noticed.  The same with ecdsa which I believe is a dependency of paramiko.

Providing `-U` to pip may have allowed the dependencies to be installed, by upgrading the direct dependencies of Ansible.

**Comment by pmarques** [comment]
@sivel I have tested it again and this time it were installed correctly. I was trying to reproduce the issue and it seems to have been a problem when I was installing some dependencies like python-dev and build-essentials.

Thanks for the quick answer.
