### ISSUE TITLE
Unexpected Exception: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by doertedev** [ansible/ansible#14108]
OHAI.

I have ansible running in a phusion container alongside a hubot instance (that should execute ansible playbooks). I get the mentioned exception, no matter how far I downgrade ansible (which is installed via pip, tried every version down to 1.9.4).

`pip freeze`:
- ansible==2.0.0.2
- awscli==1.10.0
- botocore==1.3.22
- colorama==0.3.3
- crypto==1.4.1
- docutils==0.12
- ecdsa==0.13
- j2cli==0.3.1.post0
- Jinja2==2.8
- jmespath==0.9.0
- MarkupSafe==0.23
- Naked==0.1.31
- paramiko==1.16.0
- pyasn1==0.1.9
- python-dateutil==2.4.2
- python-keyczar==0.715
- PyYAML==3.11
- requests==2.9.1
- rsa==3.3
- shellescape==3.4.1
- six==1.10.0

I looked up similar looking exception bugtickets and made sure python-setuptools is installed. Also I patched the diff from [this particular bug](https://github.com/ansible/ansible/issues/11521) by hand, which didn't solve the problem in any version either.

The playbook I execute is:

``` yml
- name: "SLACK: Get the list of developers and check for 'intruders'."
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Make sure redis is running."
      shell: "redis-cli ping"
      register: redis_running
      failed_when: redis_running.rc != 0 or "PONG" not in redis_running.stdout
    - name: "Read raw list of slack presence from hubot's Redis."
      shell: "redis-cli get hubot:storage 2> /dev/null | jq -c -r '.users|.[]|select(.roles|.[]==\"dev\")|.slack|.id + \" \" + .real_name + \" \" +  .profile.email' 2> /dev/null"
      register: developers
      failed_when: developers.stdout == ""
    - name: "Reading users with dev rights but without asdf.com email address"
      shell: "redis-cli get hubot:storage 2> /dev/null | jq -c -r '.users|.[]|select(.roles|.[]==\"dev\")|.slack|select(.profile.email|contains(\"asdf.com\")|not)' 2> /dev/null"
      register: false_devs
      failed_when: false_devs.stdout != ""
```

The -vvv version is:

```
Unexpected Exception: 'list' object has no attribute 'get'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 128, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 81, in __init__
    self.parse_inventory(host_list)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 141, in parse_inventory
    host.vars = combine_vars(host.vars, self.get_host_variables(host.name))
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 534, in get_host_variables
    self._vars_per_host[hostname] = self._get_host_variables(hostname, vault_password=vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 561, in _get_host_variables
    vars = combine_vars(vars, self.parser.get_host_variables(host))
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/script.py", line 148, in get_host_variables
    got = self.host_vars_from_top.get(host.name, {})
AttributeError: 'list' object has no attribute 'get'
```

Hope I passed all relevant pieces of information required.

**Comment by bcoca** [comment]
the problem seems to be with your inventory script, which you gave no info on.

**Comment by doertedev** [comment]
Oh. Okay. It's basically a python executeable that runs towards a consul server node and asks the k/v store for informations that were provided when ansible set the node up (API limit screwups etcetc).

It outputs something similar to:

``` json
{
  "ec2_tag_Name_you_can_imagine": [
    "x.x.x.x",
    "x.x.x.y"
  ],
  "ec2_tag_Name_some_other_machine": [
    "x.x.x.x",
    "x.x.x.y"
  ], ...
  "_meta": {
    "hostvars": [
      {
        "ec2_region": "us-east-1",
        "ec2_security_group_names": [
          "x",
          "y",
          "z"
        ],
        "ec2_private_ip_address": "10.0.0.x",
        "ec2_tag_myapp_apps": [
          "x",
          "y",
          "z"
        ],
        "ec2_tag_Environment": "xyz",
        "ec2_tag_myapp_services": [
          "x",
          "y",
          "z"
        ],
        "ec2_ip_address": "54.x.x.x",
        "ec2_id": "i-0fxyz",
        "ec2_tag_Name": "my_app_bla_foo"
      },
      {
      ...
      },
    ]
  }
}
```

It's set to `#!/usr/bin/env python` and runs fine when executed in a bash inside the container. Also jq tells me the output syntax is fine as well. Linters tell me the file is doing well, and basically it works fine for any ansible that is executed outside of a container.

**Comment by doertedev** [comment]
TIL: _meta.hostvars may not be an array, but must be a hash with the IPs as keys.

Thanks for the hint!
