### ISSUE TITLE
[2.0.0.2] Elasticache module throws TypeError exception in fail_json and exit_json

### ISSUE THREAD

**Issue by agani** [ansible/ansible#14113]
If I pass an incorrect parameter to the elasticache module (eg num_nodes > 1) the module throws a TypeError in fail_json:-

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 2727, in <module>
    main()
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 553, in main
    elasticache_manager.ensure_present()
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 187, in ensure_present
    self.create()
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 229, in create
    self.module.fail_json(msg=e.message)
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 2111, in fail_json
    kwargs = remove_values(kwargs, self.no_log_values)
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 980, in remove_values
    return [remove_values(elem, no_log_strings) for elem in value]
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453741160.56-278817282458791/elasticache", line 991, in remove_values
    raise TypeError('Value of unknown type: %s, %s' % (type(value), value))
TypeError: Value of unknown type: <type 'object'>, <object object at 0x10b4c60f0>

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "elasticache"}, "parsed": false}
```

If I have a successful run with the elasticache module the exit_json throws a TypeError (note that I define a successful run as the required changes occurring in AWS (in this case a Redis instance was created))

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 2727, in <module>
    main()
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 562, in main
    module.exit_json(**facts_result)
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 2099, in exit_json
    kwargs = remove_values(kwargs, self.no_log_values)
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 980, in remove_values
    return [remove_values(elem, no_log_strings) for elem in value]
  File "/Users/abdulg/.ansible/tmp/ansible-tmp-1453742406.53-15593205936008/elasticache", line 991, in remove_values
    raise TypeError('Value of unknown type: %s, %s' % (type(value), value))
TypeError: Value of unknown type: <type 'object'>, <object object at 0x1020c90f0>

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "elasticache"}, "parsed": false}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
