### ISSUE TITLE
ansible-galaxy - fails to login (ValueError: No JSON object could be decoded)

### ISSUE THREAD

**Issue by mwilliammyers** [ansible/ansible#14122]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default 
##### Environment:

Verified on: 
- OS X 10.11.1
- Archlinux
- Ubuntu 15.10
##### Summary:

Not sure where to direct `ansible-galaxy` issues or whether or not this is an issue with python's implementation of JSON or what but...

Using Homebrew installed python/ansible or system python with pip installed ansible (and all combinations of those), AUR or apt-get installed python/ansible the command `ansible-galaxy login` fails with `ValueError: No JSON object could be decoded`. I spent a little time digging around in the code but couldn't seem to find the issue...

Additionally, when I view my personal access tokens I can see one token from ansible which has never been used. I can delete this and retry it or regenerate a new token and use it with `ansible-galaxy login --github-token xxxxxxxxxxxxx` to no avail. I can also see that a new token was generated and then deleted by ansible in my security history report on GitHub. 
##### Steps To Reproduce:

```
ansible-galaxy login --github-token xxxxxxxxxxxxx
```

or 

```
ansible-galaxy login
```
##### Expected Results:

Authenticate and be able to run commands like `ansible-galaxy import ...`
##### Actual Results:

System `Python 2.7.10` and pip installed `ansible 2.0.0.2`: 

```
No config file found; using defaults
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
Unexpected Exception: No JSON object could be decoded
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 85, in <module>
    sys.exit(cli.run())
  File "/Library/Python/2.7/site-packages/ansible/cli/galaxy.py", line 152, in run
    self.execute()
  File "/Library/Python/2.7/site-packages/ansible/cli/__init__.py", line 99, in execute
    fn()
  File "/Library/Python/2.7/site-packages/ansible/cli/galaxy.py", line 553, in execute_login
    galaxy_response = self.api.authenticate(github_token)
  File "/Library/Python/2.7/site-packages/ansible/galaxy/api.py", line 119, in authenticate
    data = json.load(resp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Homebrew installed `Python 2.7.11` and homebrew installed `ansible 2.0.0.2`: 

```
No config file found; using defaults
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
Unexpected Exception: No JSON object could be decoded
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 152, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 99, in execute
    fn()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 553, in execute_login
    galaxy_response = self.api.authenticate(github_token)
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 119, in authenticate
    data = json.load(resp)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jimi-c** [comment]
We've included that command in 2.0, however it will not work until Galaxy 2.0 has been released (which will be very soon). I'll hold this open until then, to see if there are any further issues once that's live.

**Comment by jctanner** [comment]
@s-hertel can you look into this please?

**Comment by mwilliammyers** [comment]
I just verified that this is indeed working now that Galaxy 2.0 has been released.
