### ISSUE TITLE
got error when using vars_prompt and run with echo '\n' | ansible-playbook

### ISSUE THREAD

**Issue by wor-k** [ansible/ansible#14147]
Issue Type: Bug Report
Ansible Version: 2.0.0.2
Ansible Configuration: None
Environment: Centos 7, Ubuntu 14.04

Summary: 
got error when using vars_prompt and run with echo '\n' | ansible-playbook $$$

Steps To Reproduce: 
echo '\n' | ansible-playbook $$$ 

Actual Results:

```
Unexpected Exception: global name 'display' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/pymodules/python2.7/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/pymodules/python2.7/ansible/executor/playbook_executor.py", line 117, in run
    play.vars[vname] = display.do_var_prompt(vname, private, prompt, encrypt, confirm, salt_size, salt, default)
  File "/usr/lib/pymodules/python2.7/ansible/utils/display.py", line 303, in do_var_prompt
    display.warning("Not prompting as we are not in interactive mode")
NameError: global name 'display' is not defined
```

**Comment by techgirlgeek** [comment]
I am still getting the same error identified above, when using vars_prompt.
