### ISSUE TITLE
when use devel branch run playbook error, but no error in tag/v2.0.0.2-1

### ISSUE THREAD

**Issue by zz** [ansible/ansible#14174]
```
➜  tc-game-ansible git:(master) ansible-playbook prdservers.yml -l "tag_Name_prd1*chat*" --list-hosts -vvv

Using /Users/zz/work/drive/tc-game-ansible/ansible.cfg as config file
1 plays in prdservers.yml
ERROR! Unexpected Exception: 'NoneType' object has no attribute '_failed_hosts'
the full traceback was:

Traceback (most recent call last):
  File "/Users/zz/work/personal/ansible/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/Users/zz/work/personal/ansible/lib/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/Users/zz/work/personal/ansible/lib/ansible/executor/playbook_executor.py", line 176, in run
    retries = list(set(self._tqm._failed_hosts.keys() + self._tqm._unreachable_hosts.keys()))
AttributeError: 'NoneType' object has no attribute '_failed_hosts'
```

**Comment by jimi-c** [comment]
Hi @zz, this has been resolved on the devel branch. Thanks!
