### ISSUE TITLE
Incorrect input causes traceback

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1419]
This is just one example, but I have seen it in other places as well. We need reports for every one occurring...

``` yaml
- name: Test
  hosts: all

  tasks:
  - action: true
    register: test

  - action: mail subject='Process RC = ${test.rc}'
```

causes:

```
[root@moria ansible]# ansible-playbook -l localhost test13.yml 
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 164, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 135, in main
    pb.run()
  File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 170, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/play.py", line 83, in __init__
    self._tasks      = self._load_tasks(self._ds, 'tasks')
  File "/usr/lib/python2.6/site-packages/ansible/playbook/play.py", line 123, in _load_tasks
    results.append(Task(self,x,module_vars=task_vars))
  File "/usr/lib/python2.6/site-packages/ansible/playbook/task.py", line 128, in __init__
    tokens = self.action.split(None, 1)
AttributeError: 'bool' object has no attribute 'split'
```

Input should have been `action: command true`

**Comment by mpdehaan** [comment]
we need pull requests for everyone occuring :)
