### ISSUE TITLE
Elasticache summarily fails

### ISSUE THREAD

**Issue by sbussetti** [ansible/ansible#14414]
Ansible version: 2.0.0.2

 The cache_subnet_group directive works, but attempting to configure an elasticache cluster just fails. 

Elasticache config:

```
- hosts: 127.0.0.1
  tasks:
    - name: '[aws] elasticache subnet group'
      elasticache_subnet_group:
        state: present
        name: 'production-cache'
        region: 'us-east-1'
        description: 'Production Cache'
        subnets:
          - subnet-XXXXXX
          - subnet-YYYYYY

    - name: '[aws] set up memcached cluster'
      elasticache:
        aws_access_key: "{{aws_access_key_id}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        name: 'prod-mc'
        region: 'us-east-1'
        hard_modify: false
        state: present
        engine: memcached
        cache_engine_version: 1.4.24
        node_type: cache.t2.small
        num_nodes: 2
        cache_port: 11211
        cache_subnet_group: 'production-cache'
        security_group_ids:
          - 'production-web'
```

Error:

```
<127.0.0.1> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=5m -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=$HOME/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 2727, in <module>
  File "<stdin>", line 553, in main
  File "<stdin>", line 185, in ensure_present
  File "<stdin>", line 281, in sync
  File "<stdin>", line 2111, in fail_json
  File "<stdin>", line 982, in remove_values
  File "<stdin>", line 982, in <genexpr>
  File "<stdin>", line 982, in remove_values
  File "<stdin>", line 982, in <genexpr>
  File "<stdin>", line 982, in remove_values
  File "<stdin>", line 982, in <genexpr>
  File "<stdin>", line 980, in remove_values
  File "<stdin>", line 991, in remove_values
TypeError: Value of unknown type: <type 'object'>, <object object at 0x10fb510f0>

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "elasticache"}, "parsed": false}
```

**Comment by jameseggleston** [comment]
any work around for this ?

**Comment by sbussetti** [comment]
I switched up to the dev branch.  This is working fine on ansible 2.1.0

**Comment by jamesdmorgan** [comment]
@sbussetti Did you get this working with num_nodes: 2? AWS currently complains that "Cannot create a Redis cluster with a NumCacheNodes parameter greater than 1." 

Im looking to have a secondary read node.
