### ISSUE TITLE
Parsing error in Ansible 1.9.4 in debug module if string contains special sequences

### ISSUE THREAD

**Issue by kuboj** [ansible/ansible#14573]
##### Issue Type:

 Bug Report
##### Ansible Version:

```
ansible 1.9.4
```
##### Ansible Configuration:

Default
##### Environment:

Ubuntu 15.04
Python 2.7.9
##### Summary:

Execution of playbook fails with parsing error when trying to print debug variable containing sequence of special characters.
##### Steps To Reproduce:

_file.txt_

```
{%‘’
```

_site.yml_

```
- name: test
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - shell: cat file.txt
      register: out

    - debug: var=out.stdout
```

_execution_

```
$ ansible-playbook -i inventory/ansible-hosts site.yml                                     
```
##### Expected Results:

Successful debug print.
##### Actual Results:

Ansible fails with parsing error.

```
$ ansible-playbook -i inventory/ansible-hosts site.yml     

PLAY [test] ******************************************************************* 

TASK: [shell cat log1] ******************************************************** 
changed: [127.0.0.1]

TASK: [debug var=out.stdout] ************************************************** 
fatal: [127.0.0.1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/debug.py", line 54, in run
    results = template.template(self.basedir, args['var'], inject, convert_bare=True)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 126, in template
    raise errors.AnsibleError("Failed to template %s: %s" % (varname, str(e)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 1198823: ordinal not in range(128)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/bubo/site.retry

127.0.0.1                  : ok=1    changed=1    unreachable=1    failed=0   
```

Interestingly enough, Ansible produces different error when `file.txt` contains only `{%` (without backquotes)

```
$ ansible-playbook -i inventory/ansible-hosts site.yml

PLAY [test] ******************************************************************* 

TASK: [shell cat txt] ********************************************************* 
changed: [127.0.0.1]

TASK: [debug var=out.stdout] ************************************************** 
fatal: [127.0.0.1] => Failed to template {{out.stdout}}: Failed to template {%: template error while templating string: tag name expected

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/bubo/site.retry

127.0.0.1                  : ok=1    changed=1    unreachable=1    failed=0   
```

Note that calling `debug` module with `msg` parameter instead of `var` or using jinja `escape` filter doesn't help.

**Comment by dagwieers** [comment]
@bcoca Can we close this ? The fix has been merged.

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
