### ISSUE TITLE
--diff Flag crashes on win_copy

### ISSUE THREAD

**Issue by blakfeld** [ansible/ansible#14659]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel cd51ba7965) last updated 2016/02/24 21:58:23 (GMT +000)
  lib/ansible/modules/core: (detached HEAD e9454fa44f) last updated 2016/02/24 21:58:47 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD fade5b7936) last updated 2016/02/24 21:58:47 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /opt/maxpoint/ansible/release/library
```
##### Ansible Configuration:

Stock
##### Environment:

Running from: Ubuntu 14.04

Targeting: Windows 2k12
##### Summary:

The `--diff` flag fails when using the win_copy module.
##### Steps To Reproduce:

Run any playbook that contains the `win_copy` module while using the `--diff` flag against a Windows box.

```
- name: Copy Over Pool Config Scripts
  win_copy:
    src: "iis_pool_settings.ps1"
    dest: D:\\Temp\\iis_pool_settings.ps1
```
##### Expected Results:

I expect to see a diff between the file that was already on disk, and the one I just copied over.
##### Actual Results:

Here's the entire output
https://gist.github.com/blakfeld/542b191c85f4385e50bf

Here's the relevant output

```
TASK [company_bidder_deploy : Copy Over company Pool Config Scripts] *********
task path: /opt/company/ansible/release/roles/company_bidder_deploy/tasks/pre_install.yml:29
<computername.companyinteractive.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO computername.companyinteractive.com
<computername.companyinteractive.com> WINRM CONNECT: transport=ssl endpoint=https://computername.companyinteractive.com:5986/wsman
<computername.companyinteractive.com> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1456414325.16-195672407265922").FullName | Write-Host -Separator '';
<computername.companyinteractive.com> WINRM OPEN SHELL: ABD20C31-4581-4A04-9E03-527A04A2F27F
<computername.companyinteractive.com> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADYANAAxADQAMwAyADUALgAxADYALQAxADkANQA2ADcAMgA0ADAANwAyADYANQA5ADIAMgAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA=']
<computername.companyinteractive.com> WINRM RESULT u'<Response code 0, out "C:\\Users\\Administrat", err "">'
<computername.companyinteractive.com> WINRM STDOUT C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414325.16-195672407265922
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> PUT "/tmp/tmpfOwmcO" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414325.16-195672407265922\stat.ps1"
<computername.companyinteractive.com> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'YgBlAGcAaQBuACAAewAKACQAcABhAHQAaAAgAD0AIAAiAEMAOgBcAFUAcwBlAHIAcwBcAEEAZABtAGkAbgBpAHMAdAByAGEAdABvAHIAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADYANAAxADQAMwAyADUALgAxADYALQAxADkANQA2ADcAMgA0ADAANwAyADYANQA5ADIAMgBcAHMAdABhAHQALgBwAHMAMQAiAAoAJABEAGUAYgB1AGcAUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAiAEMAbwBuAHQAaQBuAHUAZQAiAAoAJABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAiAFMAdABvAHAAIgAKAFMAZQB0AC0AUwB0AHIAaQBjAHQATQBvAGQAZQAgAC0AVgBlAHIAcwBpAG8AbgAgADIACgAkAGYAZAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ASQBPAC4ARgBpAGwAZQBdADoAOgBDAHIAZQBhAHQAZQAoACQAcABhAHQAaAApAAoAJABzAGgAYQAxACAAPQAgAFsAUwB5AHMAdABlAG0ALgBTAGUAYwB1AHIAaQB0AHkALgBDAHIAeQBwAHQAbwBnAHIAYQBwAGgAeQAuAFMASABBADEAQwByAHkAcAB0AG8AUwBlAHIAdgBpAGMAZQBQAHIAbwB2AGkAZABlAHIAXQA6ADoAQwByAGUAYQB0AGUAKAApAAoAJABiAHkAdABlAHMAIAA9ACAAQAAoACkAIAAjAGkAbgBpAHQAaQBhAGwAaQB6AGUAIABmAG8AcgAgAGUAbQBwAHQAeQAgAGYAaQBsAGUAIABjAGEAcwBlAAoAfQAKAHAAcgBvAGMAZQBzAHMAIAB7AAoAJABiAHkAdABlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAaQBuAHAAdQB0ACkACgAkAHMAaABhADEALgBUAHIAYQBuAHMAZgBvAHIAbQBCAGwAbwBjAGsAKAAkAGIAeQB0AGUAcwAsACAAMAAsACAAJABiAHkAdABlAHMALgBMAGUAbgBnAHQAaAAsACAAJABiAHkAdABlAHMALAAgADAAKQAgAHwAIABPAHUAdAAtAE4AdQBsAGwACgAkAGYAZAAuAFcAcgBpAHQAZQAoACQAYgB5AHQAZQBzACwAIAAwACwAIAAkAGIAeQB0AGUAcwAuAEwAZQBuAGcAdABoACkACgB9AAoAZQBuAGQAIAB7AAoAJABzAGgAYQAxAC4AVAByAGEAbgBzAGYAbwByAG0ARgBpAG4AYQBsAEIAbABvAGMAawAoACQAYgB5AHQAZQBzACwAIAAwACwAIAAwACkAIAB8ACAATwB1AHQALQBOAHUAbABsAAoAJABoAGEAcwBoACAAPQAgAFsAUwB5AHMAdABlAG0ALgBCAGkAdABDAG8AbgB2AGUAcgB0AGUAcgBdADoAOgBUAG8AUwB0AHIAaQBuAGcAKAAkAHMAaABhADEALgBIAGEAcwBoACkALgBSAGUAcABsAGEAYwBlACgAIgAtACIALAAgACIAIgApAC4AVABvAEwAbwB3AGUAcgBJAG4AdgBhAHIAaQBhAG4AdAAoACkACgAkAGYAZAAuAEMAbABvAHMAZQAoACkACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACIAewAiACIAcwBoAGEAMQAiACIAOgAiACIAJABoAGEAcwBoACIAIgB9ACIACgB9AA==']
<computername.companyinteractive.com> WINRM PUT "/tmp/tmpfOwmcO" to "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414325.16-195672407265922\stat.ps1" (offset=10177 size=10177)
<computername.companyinteractive.com> WINRM RESULT u'<Response code 0, out "{"sha1":"4b5fc9661a0", err "">'
<computername.companyinteractive.com> WINRM STDOUT {"sha1":"4b5fc9661a08b2372dc5efa608f719480e61502b"}
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> EXEC Set-StrictMode -Version Latest
Try
{
& "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414325.16-195672407265922\stat.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414325.16-195672407265922" -Force -Recurse -ErrorAction SilentlyContinue }
<computername.companyinteractive.com> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBUAHIAeQAKAHsACgAmACAAIgBDADoAXABVAHMAZQByAHMAXABBAGQAbQBpAG4AaQBzAHQAcgBhAHQAbwByAFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXABhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQANQA2ADQAMQA0ADMAMgA1AC4AMQA2AC0AMQA5ADUANgA3ADIANAAwADcAMgA2ADUAOQAyADIAXABzAHQAYQB0AC4AcABzADEAIgAKAH0ACgBDAGEAdABjAGgACgB7AAoAJABfAG8AYgBqACAAPQAgAEAAewAgAGYAYQBpAGwAZQBkACAAPQAgACQAdAByAHUAZQAgAH0ACgBJAGYAIAAoACQAXwAuAEUAeABjAGUAcAB0AGkAbwBuAC4ARwBlAHQAVAB5AHAAZQApAAoAewAKACQAXwBvAGIAagAuAEEAZABkACgAJwBtAHMAZwAnACwAIAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAE0AZQBzAHMAYQBnAGUAKQAKAH0ACgBFAGwAcwBlAAoAewAKACQAXwBvAGIAagAuAEEAZABkACgAJwBtAHMAZwAnACwAIAAkAF8ALgBUAG8AUwB0AHIAaQBuAGcAKAApACkACgB9AAoASQBmACAAKAAkAF8ALgBJAG4AdgBvAGMAYQB0AGkAbwBuAEkAbgBmAG8ALgBQAG8AcwBpAHQAaQBvAG4ATQBlAHMAcwBhAGcAZQApAAoAewAKACQAXwBvAGIAagAuAEEAZABkACgAJwBlAHgAYwBlAHAAdABpAG8AbgAnACwAIAAkAF8ALgBJAG4AdgBvAGMAYQB0AGkAbwBuAEkAbgBmAG8ALgBQAG8AcwBpAHQAaQBvAG4ATQBlAHMAcwBhAGcAZQApAAoAfQAKAEUAbABzAGUASQBmACAAKAAkAF8ALgBTAGMAcgBpAHAAdABTAHQAYQBjAGsAVAByAGEAYwBlACkACgB7AAoAJABfAG8AYgBqAC4AQQBkAGQAKAAnAGUAeABjAGUAcAB0AGkAbwBuACcALAAgACQAXwAuAFMAYwByAGkAcAB0AFMAdABhAGMAawBUAHIAYQBjAGUAKQAKAH0ACgBUAHIAeQAKAHsACgAkAF8AbwBiAGoALgBBAGQAZAAoACcAZQByAHIAbwByAF8AcgBlAGMAbwByAGQAJwAsACAAKAAkAF8AIAB8ACAAQwBvAG4AdgBlAHIAdABUAG8ALQBKAHMAbwBuACAAfAAgAEMAbwBuAHYAZQByAHQARgByAG8AbQAtAEoAcwBvAG4AKQApAAoAfQAKAEMAYQB0AGMAaAAKAHsACgB9AAoARQBjAGgAbwAgACQAXwBvAGIAagAgAHwAIABDAG8AbgB2AGUAcgB0AFQAbwAtAEoAcwBvAG4AIAAtAEMAbwBtAHAAcgBlAHMAcwAgAC0ARABlAHAAdABoACAAOQA5AAoARQB4AGkAdAAgADEACgB9AAoARgBpAG4AYQBsAGwAeQAgAHsAIABSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAiAEMAOgBcAFUAcwBlAHIAcwBcAEEAZABtAGkAbgBpAHMAdAByAGEAdABvAHIAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADYANAAxADQAMwAyADUALgAxADYALQAxADkANQA2ADcAMgA0ADAANwAyADYANQA5ADIAMgAiACAALQBGAG8AcgBjAGUAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAIAB9AA==']
<computername.companyinteractive.com> WINRM RESULT u'<Response code 0, out "{"stat":{"exists":fa", err "">'
<computername.companyinteractive.com> WINRM STDOUT {"stat":{"exists":false},"changed":false}
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1456414326.29-74854495923127").FullName | Write-Host -Separator '';
<computername.companyinteractive.com> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADYANAAxADQAMwAyADYALgAyADkALQA3ADQAOAA1ADQANAA5ADUAOQAyADMAMQAyADcAIgApAC4ARgB1AGwAbABOAGEAbQBlACAAfAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAFMAZQBwAGEAcgBhAHQAbwByACAAJwAnADsA']
<computername.companyinteractive.com> WINRM RESULT u'<Response code 0, out "C:\\Users\\Administrat", err "">'
<computername.companyinteractive.com> WINRM STDOUT C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414326.29-74854495923127
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1456414326.6-190477404467970").FullName | Write-Host -Separator '';
<computername.companyinteractive.com> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADYANAAxADQAMwAyADYALgA2AC0AMQA5ADAANAA3ADcANAAwADQANAA2ADcAOQA3ADAAIgApAC4ARgB1AGwAbABOAGEAbQBlACAAfAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAFMAZQBwAGEAcgBhAHQAbwByACAAJwAnADsA']
<computername.companyinteractive.com> WINRM RESULT u'<Response code 0, out "C:\\Users\\Administrat", err "">'
<computername.companyinteractive.com> WINRM STDOUT C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414326.6-190477404467970
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> PUT "/tmp/tmpcEFZin" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414326.6-190477404467970\file.ps1"
<computername.companyinteractive.com> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'YgBlAGcAaQBuACAAewAKACQAcABhAHQAaAAgAD0AIAAiAEMAOgBcAFUAcwBlAHIAcwBcAEEAZABtAGkAbgBpAHMAdAByAGEAdABvAHIAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADYANAAxADQAMwAyADYALgA2AC0AMQA5ADAANAA3ADcANAAwADQANAA2ADcAOQA3ADAAXABmAGkAbABlAC4AcABzADEAIgAKACQARABlAGIAdQBnAFAAcgBlAGYAZQByAGUAbgBjAGUAIAA9ACAAIgBDAG8AbgB0AGkAbgB1AGUAIgAKACQARQByAHIAbwByAEEAYwB0AGkAbwBuAFAAcgBlAGYAZQByAGUAbgBjAGUAIAA9ACAAIgBTAHQAbwBwACIACgBTAGUAdAAtAFMAdAByAGkAYwB0AE0AbwBkAGUAIAAtAFYAZQByAHMAaQBvAG4AIAAyAAoAJABmAGQAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEYAaQBsAGUAXQA6ADoAQwByAGUAYQB0AGUAKAAkAHAAYQB0AGgAKQAKACQAcwBoAGEAMQAgAD0AIABbAFMAeQBzAHQAZQBtAC4AUwBlAGMAdQByAGkAdAB5AC4AQwByAHkAcAB0AG8AZwByAGEAcABoAHkALgBTAEgAQQAxAEMAcgB5AHAAdABvAFMAZQByAHYAaQBjAGUAUAByAG8AdgBpAGQAZQByAF0AOgA6AEMAcgBlAGEAdABlACgAKQAKACQAYgB5AHQAZQBzACAAPQAgAEAAKAApACAAIwBpAG4AaQB0AGkAYQBsAGkAegBlACAAZgBvAHIAIABlAG0AcAB0AHkAIABmAGkAbABlACAAYwBhAHMAZQAKAH0ACgBwAHIAbwBjAGUAcwBzACAAewAKACQAYgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdABlAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAGkAbgBwAHUAdAApAAoAJABzAGgAYQAxAC4AVAByAGEAbgBzAGYAbwByAG0AQgBsAG8AYwBrACgAJABiAHkAdABlAHMALAAgADAALAAgACQAYgB5AHQAZQBzAC4ATABlAG4AZwB0AGgALAAgACQAYgB5AHQAZQBzACwAIAAwACkAIAB8ACAATwB1AHQALQBOAHUAbABsAAoAJABmAGQALgBXAHIAaQB0AGUAKAAkAGIAeQB0AGUAcwAsACAAMAAsACAAJABiAHkAdABlAHMALgBMAGUAbgBnAHQAaAApAAoAfQAKAGUAbgBkACAAewAKACQAcwBoAGEAMQAuAFQAcgBhAG4AcwBmAG8AcgBtAEYAaQBuAGEAbABCAGwAbwBjAGsAKAAkAGIAeQB0AGUAcwAsACAAMAAsACAAMAApACAAfAAgAE8AdQB0AC0ATgB1AGwAbAAKACQAaABhAHMAaAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AQgBpAHQAQwBvAG4AdgBlAHIAdABlAHIAXQA6ADoAVABvAFMAdAByAGkAbgBnACgAJABzAGgAYQAxAC4ASABhAHMAaAApAC4AUgBlAHAAbABhAGMAZQAoACIALQAiACwAIAAiACIAKQAuAFQAbwBMAG8AdwBlAHIASQBuAHYAYQByAGkAYQBuAHQAKAApAAoAJABmAGQALgBDAGwAbwBzAGUAKAApAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAiAHsAIgAiAHMAaABhADEAIgAiADoAIgAiACQAaABhAHMAaAAiACIAfQAiAAoAfQA=']
<computername.companyinteractive.com> WINRM PUT "/tmp/tmpcEFZin" to "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414326.6-190477404467970\file.ps1" (offset=10656 size=10656)
<computername.companyinteractive.com> WINRM RESULT u'<Response code 0, out "{"sha1":"7f5d2fe5184", err "">'
<computername.companyinteractive.com> WINRM STDOUT {"sha1":"7f5d2fe5184e28c170ff1de2a7b611897f896275"}
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> EXEC Set-StrictMode -Version Latest
Try
{
& "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456414326.6-190477404467970\file.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
<computername.companyinteractive.com> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBUAHIAeQAKAHsACgAmACAAIgBDADoAXABVAHMAZQByAHMAXABBAGQAbQBpAG4AaQBzAHQAcgBhAHQAbwByAFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXABhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQANQA2ADQAMQA0ADMAMgA2AC4ANgAtADEAOQAwADQANwA3ADQAMAA0ADQANgA3ADkANwAwAFwAZgBpAGwAZQAuAHAAcwAxACIACgB9AAoAQwBhAHQAYwBoAAoAewAKACQAXwBvAGIAagAgAD0AIABAAHsAIABmAGEAaQBsAGUAZAAgAD0AIAAkAHQAcgB1AGUAIAB9AAoASQBmACAAKAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAEcAZQB0AFQAeQBwAGUAKQAKAHsACgAkAF8AbwBiAGoALgBBAGQAZAAoACcAbQBzAGcAJwAsACAAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkACgB9AAoARQBsAHMAZQAKAHsACgAkAF8AbwBiAGoALgBBAGQAZAAoACcAbQBzAGcAJwAsACAAJABfAC4AVABvAFMAdAByAGkAbgBnACgAKQApAAoAfQAKAEkAZgAgACgAJABfAC4ASQBuAHYAbwBjAGEAdABpAG8AbgBJAG4AZgBvAC4AUABvAHMAaQB0AGkAbwBuAE0AZQBzAHMAYQBnAGUAKQAKAHsACgAkAF8AbwBiAGoALgBBAGQAZAAoACcAZQB4AGMAZQBwAHQAaQBvAG4AJwAsACAAJABfAC4ASQBuAHYAbwBjAGEAdABpAG8AbgBJAG4AZgBvAC4AUABvAHMAaQB0AGkAbwBuAE0AZQBzAHMAYQBnAGUAKQAKAH0ACgBFAGwAcwBlAEkAZgAgACgAJABfAC4AUwBjAHIAaQBwAHQAUwB0AGEAYwBrAFQAcgBhAGMAZQApAAoAewAKACQAXwBvAGIAagAuAEEAZABkACgAJwBlAHgAYwBlAHAAdABpAG8AbgAnACwAIAAkAF8ALgBTAGMAcgBpAHAAdABTAHQAYQBjAGsAVAByAGEAYwBlACkACgB9AAoAVAByAHkACgB7AAoAJABfAG8AYgBqAC4AQQBkAGQAKAAnAGUAcgByAG8AcgBfAHIAZQBjAG8AcgBkACcALAAgACgAJABfACAAfAAgAEMAbwBuAHYAZQByAHQAVABvAC0ASgBzAG8AbgAgAHwAIABDAG8AbgB2AGUAcgB0AEYAcgBvAG0ALQBKAHMAbwBuACkAKQAKAH0ACgBDAGEAdABjAGgACgB7AAoAfQAKAEUAYwBoAG8AIAAkAF8AbwBiAGoAIAB8ACAAQwBvAG4AdgBlAHIAdABUAG8ALQBKAHMAbwBuACAALQBDAG8AbQBwAHIAZQBzAHMAIAAtAEQAZQBwAHQAaAAgADkAOQAKAEUAeABpAHQAIAAxAAoAfQA=']
<computername.companyinteractive.com> WINRM RESULT u'<Response code 1, out "{"msg":"path will no", err "">'
<computername.companyinteractive.com> WINRM STDOUT {"msg":"path will not be created","failed":true}
<computername.companyinteractive.com> WINRM STDERR 
<computername.companyinteractive.com> WINRM CLOSE SHELL: ABD20C31-4581-4A04-9E03-527A04A2F27F
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/opt/ansible-src/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/opt/ansible-src/lib/ansible/executor/task_executor.py", line 418, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ansible-src/lib/ansible/plugins/action/copy.py", line 202, in run
    diffs.append(self._get_diff_data(dest_file, source_full, task_vars))
  File "/opt/ansible-src/lib/ansible/plugins/action/__init__.py", line 614, in _get_diff_data
    if peek_result['state'] == 'absent':
KeyError: 'state'
```

The problem appears to be because the `--diff` command is relying upon the existence of a 'state' key in the returned JSON. This appears to be a key added in the module_utils.basic Python module, specifically the add_path_info method, which seems to be called by load_common_file_arguments. I was going to just hack this into win_copy, but it seems to me that the most reasonable solution would be to add load_common_file_arguments to powershell_common.ps1. I'm more than happy to start work on that if the community agrees that is the best answer.

**Comment by jhawkesworth** [comment]
Pretty certain diff mode has never been available for any windows modules.  Personally I haven't ever dug in to how it works but by all means make a start - I know of at least 1 person asking for this on ansible-project google group.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
