### ISSUE TITLE
Exception when trying to install packages

### ISSUE THREAD

**Issue by perk11** [ansible/ansible#14664]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible-playbook 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Environment:

Ubuntu 14.04 amd64
##### Summary:

After updating to 2.0.1.0, this role:

```
- name: Install PostgreSQL
  apt: package={{ item }}
  with_items:
    - postgresql
    - python-psycopg2
  tags: postgresql

```

is causing this error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 92, in run
    item_results = self._run_loop(items)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 223, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 273, in _squash_items
    if templar._contains_vars(name):
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 373, in _contains_vars
    return self.environment.block_start_string in data or self.environment.variable_start_string in data
TypeError: argument of type 'NoneType' is not iterable

fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by gou1** [comment]
A colleague had the same bug ; as a workaround, replacing "package=" with "name=" fixed the issue.

**Comment by problame** [comment]
Can confirm the bug on ansible-2.0.0.0 to ansible-2.0.1.0 (all from pip).

**Comment by bcoca** [comment]
fixed via 67d5b77898872335f18fd58f3aa53798ef7a2e31

**Comment by nbrownus** [comment]
I believe this also affects `apt: deb='{{ item }}'`

**Comment by cyxxx** [comment]
> I believe this also affects apt: deb='{{ item }}'

failed: [ansible-test1] => {"failed": true}
msg: unsupported parameter for module: deb

didnt worked for me, I guess package or pkg or name should be the right, but I got also (still) the same errors..

fatal: [testsystem] => failed to parse: SUDO-SUCCESS-uutlfvrdibcjzzxpopccemsazyjehsye
Traceback (most recent call last):
  File "/home/XXX/.ansible/tmp/ansible-tmp-1458546406.72-55121988074891/apt", line 1566, in <module>
    main()
  File "/home/XXX/.ansible/tmp/ansible-tmp-1458546406.72-55121988074891/apt", line 400, in main
    cache = apt.Cache()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 107, in **init**
    self.open(progress)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 155, in open
    self._list.read_main_list()
SystemError: E:Malformed line 64 in source list /etc/apt/sources.list (dist)

any suggestions?

**Comment by jheehu** [comment]
@cyxxx  by now, this problem can be solved by command

> name: install all 
> command: /usr/bin/dpkg -i *

**Comment by abadger** [comment]
Could people reporting the problem with deb open a new bug? We often don't
see new comments on closed tickets.

**Comment by richardweiu** [comment]
maybe this also affects the unarchive moudle 

```
        - name: unarchive the guacad
          unarchive:
               src: files/guacamole-server-0.9.9.tar.gz
               dest: /path/to/dest
```

the get this error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'bool' object is not iterable
fatal: [wei-test]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

then I use the `-vvv` get more info:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 490, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/unarchive.py", line 70, in run
    if self._remote_file_exists(creates):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 101, in _remote_file_exists
    cmd = self._connection._shell.exists(path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/shell/__init__.py", line 90, in exists
    cmd = ['test', '-e', pipes.quote(path)]
  File "/usr/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'bool' object is not iterable

fatal: [wei-test]: FAILED! => {
    "failed": true,     "msg": "Unexpected failure during module execution.",     "stdout": ""}

```
