### ISSUE TITLE
TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)

### ISSUE THREAD

**Issue by mearsten** [ansible/ansible#14776]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0 (detached HEAD bb6cadefa2) last updated 2016/03/03 17:34:56 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated 2016/03/03 17:34:49 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated 2016/03/03 17:34:55 (GMT +300)
  config file = /home/snp/reproduce_ansible_bug_3vs4_args/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

Debian 8
##### Summary:

```
TASK [do_copy : reproduce a bug in Ansible v2.0.1.0-1] *************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "a8fdc205a9f19cc1c7507a60c4f01b13d11d7fd0", "failed": true, "parsed": false}
```

I've got a simple playbook

```
278134    4 drwx------   3 snp      snp          4096 Mar  3 18:11 roles/do_copy/files
278135    4 drwx------   2 snp      snp          4096 Mar  3 18:11 roles/do_copy/files/some_dir
278136    4 -rw-------   1 snp      snp             4 Mar  3 18:11 roles/do_copy/files/some_dir/some_file
278137    4 drwx------   2 snp      snp          4096 Mar  3 18:12 roles/do_copy/tasks
278138    4 -rw-------   1 snp      snp           102 Mar  3 18:12 roles/do_copy/tasks/main.yml
```

And just one task in it:

```

---
- name: reproduce a bug in Ansible v2.0.1.0-1
  copy: >
    src=some_dir/
    dest=/tmp/some_dir/
```

The task succeeds if `/tmp/some_dir/some_file` is absent or differs from the one in the role; and fails if that file is identical to the one in the role.
##### Steps To Reproduce:
- `git clone https://github.com/serge-name/reproduce_ansible_bug_3vs4_args.git`
- `cd reproduce_ansible_bug_3vs4_args`
- `ansible-playbook playbook.yml`
- `ansible-playbook playbook.yml`

(steps 3 and 4 are identical, i.e. run the playbook twice)
##### Expected Results:

That task works fine on earlier versions (at least on `2.0.0-0.7.rc2` and `1.9.4`)
##### Actual Results:

```
TASK [do_copy : reproduce a bug in Ansible v2.0.1.0-1] *************************
task path: /home/snp/reproduce_ansible_bug_3vs4_args/roles/do_copy/tasks/main.yml:2
ESTABLISH LOCAL CONNECTION FOR USER: snp
localhost EXEC /bin/sh -c 'rc=flag; [ -r /tmp/some_dir/some_file ] || rc=2; [ -f /tmp/some_dir/some_file ] || rc=1; [ -d /tmp/some_dir/some_file ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/tmp/some_dir/some_file && exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'/tmp/some_dir/some_file'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"' 2>/dev/null) || (python -c '"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'/tmp/some_dir/some_file'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"' 2>/dev/null) || (echo '"'"'0  '"'"'/tmp/some_dir/some_file)'
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910 `" )'
localhost PUT /tmp/tmpVVMHrZ TO /home/snp/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910/file
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/snp/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910/file; rm -rf "/home/snp/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/snp/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910/file", line 2395, in <module>
    main()
  File "/home/snp/.ansible/tmp/ansible-tmp-1457019285.3-37768388483910/file", line 325, in main
    changed = module.set_fs_attributes_if_different(file_args, changed, diff)
TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)

fatal: [localhost]: FAILED! => {"changed": false, "checksum": "a8fdc205a9f19cc1c7507a60c4f01b13d11d7fd0", "failed": true, "invocation": {"module_args": {"dest": "/tmp/some_dir/", "src": "some_dir/"}, "module_name": "copy"}, "parsed": false}
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

The only way to get this error is by mixing module vs core versions of the code.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mearsten** [comment]
Dear bcoca,

> This appears to be a user question

I disagree.

> The only way to get this error is by mixing module vs core versions of the code.

Nothing was "mixed". I installed the 2.1.0.1-1 release from git. From scratch.

Ok, let's make it clear. I'm going to add more steps to reproduce:
- `rm -rf /opt/ansible-2.0.1.0-1`
- `virtualenv /opt/ansible-2.0.1.0-1`
- `/opt/ansible-2.0.1.0-1/bin/pip install -e 'git+https://github.com/ansible/ansible.git@v2.0.1.0-1#egg=ansible'`
- then repeat steps I provided in my report

This is a bug and a detailed way how to reproduce. I hope you will try to reproduce it yourself before answering to me.

Thank you.

**Comment by vincevriend** [comment]
I also have the same problem. copy works fine, unless there are no changes between the source and destination file you are copying.

``` yaml
- name: Copy the Django local_settings.py    
  copy: src=local_settings.py dest=local_settings.py force=yes
```

Running this gives me this error:

``` bash
TASK [common : Copy the Django local_settings.py] ******************************
fatal: [10.0.0.10]: FAILED! => {"changed": false, "checksum": "ceb3ff5a4ba04c0143fc3c0e8085377e3c1aa1e5", "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible-tmp-1459219183.0-193835636828676/file\", line 2419, in <module>\r\n    main()\r\n  File \"/tmp/ansible-tmp-1459219183.0-193835636828676/file\", line 283, in main\r\n    changed = module.set_fs_attributes_if_different(file_args, changed, diff)\r\nTypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Which is the same `TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)` that serge-name got.
