### ISSUE TITLE
BUG: TypeError: argument of type 'builtin_function_or_method' is not iterable

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1481]
While the Ansible built 2012-10-23 is working fine, I am unable to use the latest Ansible version because of the following error:

ansible-playbook playbook.yml -i hosts.dev1 --extra-vars "myvar=dev1"

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 164, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 135, in main
    pb.run()
  File "/usr/lib/python2.6/site-packages/ansible/playbook/**init**.py", line 170, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/play.py", line 83, in **init**
    self._tasks      = self._load_tasks(self._ds, 'tasks')
  File "/usr/lib/python2.6/site-packages/ansible/playbook/play.py", line 126, in _load_tasks
    results.append(Task(self,y,module_vars=mv.copy()))
  File "/usr/lib/python2.6/site-packages/ansible/playbook/task.py", line 149, in __init__
    self.action = utils.template(None, self.action, self.module_vars)
  File "/usr/lib/python2.6/site-packages/ansible/utils.py", line 231, in template
    return ans_template.template(basedir, text, vars, expand_lists=expand_lists)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 222, in template
    text = varReplace(unicode(text), vars, expand_lists=expand_lists)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 129, in varReplace
    m = _varFind(raw, vars, depth)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 104, in _varFind
    space = _varFindLimitSpace(space, text[part_start[0]:end], depth)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 51, in _varFindLimitSpace
    part = varReplace(part, vars, depth=depth + 1)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 129, in varReplace
    m = _varFind(raw, vars, depth)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 116, in _varFind
    space = _varFindLimitSpace(space, text[part_start[0]:var_end], depth)
  File "/usr/lib/python2.6/site-packages/ansible/template.py", line 52, in _varFindLimitSpace
    if part in space:
TypeError: argument of type 'builtin_function_or_method' is not iterable

**Comment by mpdehaan** [comment]
I'm going to need to see both your playbook.yml file and possibly any
templates included if I'm to reproduce this.

Your host file is probably /not/ needed, but I can't be sure, so include
that also.

**Comment by mpdehaan** [comment]
Ah, @dhozac is extra fast as usual.

Great.

**Comment by mpdehaan** [comment]
Try to work this down to a minimal example if you can.

I suspect there is some unexpected usage of variables, i.e. "$", the
varReplace code is not happy with.

**Comment by dhozac** [comment]
``` yaml
---
- hosts: all
  vars:
    var: lol
  tasks:
  - name: test
    action: command echo ${item.part_$var}
    with_items:
    - part_lol: mystring
```

was enough to reproduce it for me.

**Comment by mpdehaan** [comment]
That message arrived out of order, FWIW.   (Email vs commenting on github).

**Comment by mpdehaan** [comment]
closing given other pull request will fix this, testing/merging later today
