### ISSUE TITLE
[Errno 12] Not enough space when fork > 1

### ISSUE THREAD

**Issue by naisanza** [ansible/ansible#14818]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 45b7fe1590) last updated 2016/03/05 01:59:49 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated 2016/03/05 01:59:52 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated 2016/03/05 01:59:55 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
```
##### Summary:

I was testing out the ping module on my inventory file and was receiving the following error constantly:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Not enough space
10.0.9.4 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

There were no errors when using the ping module individually. Then, I found the fork option and set it to `1` and all errors stopped. I tested fork values from `1` to `6`. Errors occur sporadically when the fork value is `2` and greater.
##### Steps To Reproduce:

hosts-ansible (inventory file)

```
[internaldmz0]
10.0.9.3      ansible_host=10.0.9.1   ansible_python_interpreter=/opt/local/bin/python
10.0.9.4      ansible_host=10.0.9.1   ansible_python_interpreter=/opt/local/bin/python
10.0.9.5      ansible_host=10.0.9.1   ansible_python_interpreter=/opt/local/bin/python
10.0.9.6      ansible_host=10.0.9.1   ansible_python_interpreter=/opt/local/bin/python
10.0.9.7      ansible_host=10.0.9.1   ansible_python_interpreter=/opt/local/bin/python
```

```
ansible all -i hosts-ansible -m ping
```

##### Expected Results:

```
10.0.9.3 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.9.4 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.9.5 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.9.6 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.9.7 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```
##### Actual Results:

```
[root@control0 ~]# ansible internaldmz0 -i hosts-ansible -m ping -f 5 -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.7-155196597767358 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.7-155196597767358 `" )'"'"''
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.7-142803718066350 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.7-142803718066350 `" )'"'"''
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.77-111275755459897 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.77-111275755459897 `" )'"'"''
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.79-22496953692024 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.79-22496953692024 `" )'"'"''
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.79-213638954896117 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457156387.79-213638954896117 `" )'"'"''
<10.0.9.1> PUT /tmp/tmpY6ENzC TO /root/.ansible/tmp/ansible-tmp-1457156387.7-155196597767358/ping
<10.0.9.1> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.0.9.1]'
<10.0.9.1> PUT /tmp/tmpVCPbUI TO /root/.ansible/tmp/ansible-tmp-1457156387.7-142803718066350/ping
<10.0.9.1> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.0.9.1]'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 424, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 440, in _execute_module
    tmp = self._make_tmp_path()
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 211, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 556, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 590, in exec_command
    return_tuple = self._exec_command(*args, **kwargs)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 567, in _exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 339, in _run
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/local/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Not enough space

10.0.9.7 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 424, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 440, in _execute_module
    tmp = self._make_tmp_path()
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 211, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 556, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 590, in exec_command
    return_tuple = self._exec_command(*args, **kwargs)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 567, in _exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 339, in _run
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/local/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Not enough space

10.0.9.3 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 424, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 440, in _execute_module
    tmp = self._make_tmp_path()
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 211, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 556, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 590, in exec_command
    return_tuple = self._exec_command(*args, **kwargs)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 567, in _exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 339, in _run
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/local/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Not enough space

10.0.9.5 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /opt/local/bin/python /root/.ansible/tmp/ansible-tmp-1457156387.7-155196597767358/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1457156387.7-155196597767358/" > /dev/null 2>&1'"'"''
<10.0.9.1> ESTABLISH SSH CONNECTION FOR USER: None
<10.0.9.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.9.1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /opt/local/bin/python /root/.ansible/tmp/ansible-tmp-1457156387.7-142803718066350/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1457156387.7-142803718066350/" > /dev/null 2>&1'"'"''
10.0.9.6 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
10.0.9.4 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
```

**Comment by naisanza** [comment]
Increasing RAM to the VM solved the problem

Memory usage checks before spawning forks could be helpful (e.g. spawning forks incrementally and stopping forks when free memory is too low).

**Comment by naisanza** [comment]
Also, looks like `ansible_host` setting does not work
