### ISSUE TITLE
Exception looping

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#14880]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

fact_caching = redis
fact_caching_timeout = 86400
ANSIBLE_HOSTS=./hosts
##### Environment:

Linux samsung-ubuntu 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 GNU/Linux
##### Summary:

Cf. example
##### Steps To Reproduce:

```
# hosts
[all:vars]
ansible_connection = "{{ connections.ansible }}"

[spines-sf]
NX-OSv-Spine-1[1:2]

# san-francisco.yml
- hosts: spines-sf
  gather_facts: no
  vars_files:
    - group_vars/spines/features.yml
  roles:
    - common
    - spine

# group_vars/spines/features.yml
features:
        - name: bfd
          state: enabled
        - name: bgp
          state: enabled
...

# roles/common/tasks/main.yml
- name: Enable features with a CLI command
  nxos_command:
      host: "{{ inventory_hostname }}"
      username: "{{ connections.username }}"
      password: "{{ connections.password }}"
      protocol: "{{ connections.protocol }}"
      commands:
        - conf t
        - feature {{ item.name }}
      with_items: "{{ features }}"
```
##### Expected Results:

Ansible should loop over all "features"
##### Actual Results:

```
ERROR! Unexpected Exception: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/lib/pymodules/python2.7/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/pymodules/python2.7/ansible/executor/playbook_executor.py", line 71, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 52, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 86, in _load_playbook_data
    pb = PlaybookInclude.load(entry, basedir=self._basedir, variable_manager=variable_manager, loader=self._loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/playbook_include.py", line 42, in load
    return PlaybookInclude().load_data(ds=data, basedir=basedir, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/playbook_include.py", line 80, in load_data
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 92, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 109, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/base.py", line 200, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 205, in _load_roles
    role_includes = load_list_of_roles(ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/helpers.py", line 117, in load_list_of_roles
    i = RoleInclude.load(role_def, play=play, current_role_path=current_role_path, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/role/include.py", line 57, in load
    return ri.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/base.py", line 189, in load_data
    ds = self.preprocess_data(ds)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/role/definition.py", line 87, in preprocess_data
    (role_name, role_path) = self._load_role_path(role_name)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/role/definition.py", line 157, in _load_role_path
    all_vars = self._variable_manager.get_vars(loader=self._loader, play=self._play)
  File "/usr/lib/pymodules/python2.7/ansible/vars/__init__.py", line 265, in get_vars
    for vars_file_item in play.get_vars_files():
TypeError: 'NoneType' object is not iterable
```

**Comment by bcoca** [comment]
I cannot seem to reproduce this error, in any case it is on the `vars_files` loading, not on the `with_` loop.

also group vars are designed to be auto-loaded by matching group name, doing it from vars_files is not the expected way for this to work.

**Comment by jean-christophe-manciot** [comment]
Yes, but it does not change the issue if I remove all the "vars_files" declarations.
I don't think there's anything invalid in group_vars/spines/features.yml
[features.txt](https://github.com/ansible/ansible/files/193727/features.txt)
(I had to rename it just for the upload).

Am I missing something?

**Comment by bcoca** [comment]
So i made small play and using your file:

```
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/features.txt
  tasks:
    - debug: var=features
```

I don't have any issues:

```
______________ 
< TASK [debug] >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "features": [                                                                                                                                                                                                          
        {                                                                                                                                                                                                                  
            "name": "bfd",                                                                                                                                                                                                 
            "state": "enabled"                                                                                                                                                                                             
        },                                                                                                                                                                                                                 
        {                                                                                                                                                                                                                  
            "name": "bgp",                                                                                                                                                                                                 
            "state": "enabled"                                                                                                                                                                                             
        },                                                                                                                                                                                                                 
        {                                                                                                                                                                                                                  
            "name": "bulkstat",                                                                                                                                                                                            
            "state": "disabled"                                                                                                                                                                                            
        },                                                                                                                                                                                                                 
        {                                                                                                                                                                                                                  
            "name": "cable-management",                                                                                                                                                                                    
            "state": "enabled"                                                                                                                                                                                             
        },                                                                                                                                                                                                                 
        {                                                                                                                                                                                                                  
            "name": "cts",                                                                                                                                                                                                 
            "state": "disabled"                                                                                                                                                                                            
        },                                                                                                                                                                                                                 
        {                                                                                                                                                                                                                  
            "name": "dhcp",                                                                                                                                                                                                
            "state": "disabled"                                                                                                                                                                                            
        },                             
...
```

**Comment by jean-christophe-manciot** [comment]
I removed all calls to empty roles from the main playbook and the issue vanished into thin air...

However, I'm facing another issue with the unmodified "group_vars/spines/features.yml" and the following call in the "common" role:

```
- name: Enable features with a CLI command
  nxos_command:
      host: "{{ inventory_hostname }}"
      username: "{{ connections.username }}"
      password: "{{ connections.password }}"
      protocol: "{{ connections.protocol }}"
      commands:
        - "config terminal"
        - "feature {{ item.name }}"
      with_items: "{{ features }}"
  register: return
```

I get:

```
TASK [common : Enable features with a CLI command] *****************************
task path: /media/actionmystique/SAMSUNG-Ext4-1/Labs/GNS3/CCNP-Cloud/CLDAUT/Distributed-Clouds/Ansible/roles/common/tasks/main.yml:67
fatal: [NX-OSv-Spine-11]: FAILED! => {"failed": true, "msg": "'item' is undefined"}
fatal: [NX-OSv-Spine-12]: FAILED! => {"failed": true, "msg": "'item' is undefined"}
```

**Comment by jean-christophe-manciot** [comment]
We cannot use nxos_command to configure, but rather nxos_config, which has its own set of issues.
Anyway, I consider the issue of this thread as closed since no one seems interested in further investigation. 
Let's not use calls to empty roles.
