### ISSUE TITLE
ansible-vault: ERROR! Unexpected Exception: insecure string pickle

### ISSUE THREAD

**Issue by nolith** [ansible/ansible#14895]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Environment:

OS X 10.11.3

```
$  python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
OpenSSL 0.9.8zg 14 July 2015
```

```
$ python --version
Python 2.7.10
```
##### Summary:

Any operation wich attemps to write an encrypted vault file fails with `ERROR! Unexpected Exception: insecure string pickle`
##### Steps To Reproduce:
- `echo "ciao:\n  test: true" > secrets.yml`
- `ansible-vault encrypt secrets.yml`
##### Expected Results:

secrets.yml was supposed to be encrypted.

Please note that `ansible-vault view` command works as expected on already encrypted files,
`ansible-vault edit` fails whan you attempt to save the modifications.
##### Actual Results:

```
nolith at mehetueret in /tmp 
$ echo "ciao:\n  test: true" > secrets.yml

nolith at mehetueret in /tmp 
$ ansible-vault encrypt secrets.yml
New Vault password: 
Confirm New Vault password: 
ERROR! Unexpected Exception: insecure string pickle
to see the full traceback, use -vvv

nolith at mehetueret in /tmp 
$ ansible-vault encrypt secrets.yml -vvv
No config file found; using defaults
New Vault password: 
Confirm New Vault password: 
ERROR! Unexpected Exception: insecure string pickle
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/bin/ansible-vault", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/lib/python2.7/site-packages/ansible/cli/vault.py", line 120, in run
    self.execute()
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/lib/python2.7/site-packages/ansible/cli/__init__.py", line 114, in execute
    fn()
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/lib/python2.7/site-packages/ansible/cli/vault.py", line 131, in execute_encrypt
    self.editor.encrypt_file(f, output_file=self.options.output_file)
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 324, in encrypt_file
    self.write_data(ciphertext, output_file or filename)
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 409, in write_data
    self._shred_file(filename)
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 277, in _shred_file
    r = call(['shred', tmp_path])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Comment by nolith** [comment]
I've reverted to ansible 2.0.0.2 and everything works as expected.

`brew switch ansible 2.0.0.2`

**Comment by resmo** [comment]
@nolith close bug please

**Comment by resmo** [comment]
@nolith igore my comment... :)

**Comment by binarytemple** [comment]
Also experiencing the same with Ansible 2.1 - output follows:

```
% echo foo > test.yml
% ansible-vault -vvv encrypt test.yml
Using /etc/ansible/ansible.cfg as config file
New Vault password:
Confirm New Vault password:
ERROR! Unexpected Exception: insecure string pickle
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-vault", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/vault.py", line 120, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 114, in execute
    fn()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/vault.py", line 131, in execute_encrypt
    self.editor.encrypt_file(f, output_file=self.options.output_file)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 324, in encrypt_file
    self.write_data(ciphertext, output_file or filename)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 422, in write_data
    self._shred_file(filename)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 277, in _shred_file
    r = call(['shred', tmp_path])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

```
% ansible --version
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by binarytemple** [comment]
Upgraded to latest Ansible master using:

```
pip install -U git+https://github.com/ansible/ansible.git@devel#egg=ansible
```

Still broken.

**Comment by binarytemple** [comment]
I replaced lines 212-216 of /usr/local/lib/python2.7/site-packages/ansible/parsing/vault/**init**.py 
with the following, and the problem went away.. 

```
212          try:
213              r = call(['shred', tmp_path])
214          except OSError:
215              # shred is not available on this system, or some other error occured.
216              r = 1


212          r=1
213          
214          
215          
216          
```

I'm using disk encryption anyway (like most developers who use OSX) so don't really care much whether the files have been shredded or not. In any event, skipping that block just means that the python '_shred_file_custom' function is called instead. Sub-processes, never pretty.

**Comment by abadger** [comment]
Some googling has revealed this to be a bug in python 2 subprocess code,
recently fixed (no release yet). Since we have fallback code we should be
able to workaround this by catching valueerror as well as oserror.

**Comment by abadger** [comment]
Fixed and pushed to both the devel and stable-2.0 branches.

**Comment by v1k0d3n** [comment]
i'm still having issues with this for both homebrew and pip installs. is anyone else? if i need to reach out to them too, but i would've thought the pip route would've at least solved the problem.

**Comment by binarytemple** [comment]
I can confirm its been fixed in development. I uninstalled the brew version
and installed from pip like so:

pip install git+git://github.com/ansible/ansible.git@devel

**Comment by v1k0d3n** [comment]
so heres a bit of information: so if I set `LC_ALL=pl_pl.utf-8` as an environment variable the errors go away. where is a better place to set this (other than `.*profile`)? i don't want to place it in  `.*profile` because it will throw errors every time i remote into another machine. i tried putting into `~/.ansible.cfg`, but it doesn't seem like ansible likes this in the same format as it would be in a `.*profile`.

**Comment by v1k0d3n** [comment]
ok, `locale` must have gotten fried during an El Capitan upgrade/update, so I changed to `LC_ALL=en_US.UTF-8` and all seems right again. i will stop spamming everyone now! :)
