### ISSUE TITLE
Failed to connect running ansible with vagrant

### ISSUE THREAD

**Issue by mansinga1** [ansible/ansible#14925]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.5.4

```
joseph@joseph-HP-Pavilion-17-Notebook-PC:~/playbooks$ sudo ansible testserver -i hosts -m ping -vvvv
Traceback (most recent call last):
  File "/usr/bin/ansible", line 226, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/bin/ansible", line 142, in run
    inventory_manager = inventory.Inventory(options.inventory)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 106, in __init__
    self.parser = InventoryParser(filename=host_list)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/ini.py", line 41, in __init__
    self._parse()
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/ini.py", line 45, in _parse
    self._parse_base_groups()
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/ini.py", line 83, in _parse_base_groups
    tokens = shlex.split(line)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 191, in read_token
    raise ValueError, "No escaped character"
ValueError: No escaped character
```
##### Summary:

same error report

**Comment by bcoca** [comment]
please fill in the full form and provide a way to reproduce this issue, also I would advise trying it with a current version (2.0.1) as this might have already been fixed.

**Comment by jctanner** [comment]
This appears to be a parsing error for the content inside the inventory file. However, without knowing the content of the inventory, any further response from the reporter, and such an old version of ansible we are not going to be able to debug this.
