### ISSUE TITLE
In Ansible Tower "AttributeError: 'str' object has no attribute 'get'" on Job run

### ISSUE THREAD

**Issue by tspycher** [ansible/ansible#15092]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

Default
##### Environment:

CentOS 7
##### Summary:

Gettin the following error when run an Job Template in Ansible Tower. Jobs of type check do work without any error:

```
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<192.168.201.102> REMOTE_MODULE setup
ok: [192.168.201.102]

TASK: [php | Install remi repo.] ********************************************** 
<192.168.201.102> REMOTE_MODULE yum name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
ok: [192.168.201.102] => {"changed": false, "msg": "", "rc": 0, "results": ["http://rpms.famillecollet.com/enterprise/remi-release-7.rpm: Nothing to do"]}
fatal: [192.168.201.102] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1121, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 548, in on_ok
    super(PlaybookRunnerCallbacks, self).on_ok(host, host_result)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 347, in on_ok
    call_callback_module('runner_on_ok', host, res)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 179, in call_callback_module
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 222, in runner_on_ok
    self._log_event('runner_on_ok', host=host, res=res)
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 366, in _log_event
    super(JobCallbackModule, self)._log_event(event, **event_data)
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 202, in _log_event
    event_data['res'] = censor(deepcopy(event_data['res']))
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 84, in censor
    obj['results'][i] = censor(obj['results'][i])
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 70, in censor
    if obj.get('_ansible_no_log', False):
AttributeError: 'str' object has no attribute 'get'

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 348, in run
    if not self._run_play(play):
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 789, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 497, in _run_task
    results = self._run_task_internal(task, include_failed=include_failed)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 439, in _run_task_internal
    results = runner.run()
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1498, in run
    results = [ self._executor(h, None) for h in hosts ]
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 599, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 473, in on_unreachable
    super(PlaybookRunnerCallbacks, self).on_unreachable(host, results)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 353, in on_unreachable
    call_callback_module('runner_on_unreachable', host, res)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 179, in call_callback_module
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 242, in runner_on_unreachable
    self._log_event('runner_on_unreachable', host=host, res=res)
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 366, in _log_event
    super(JobCallbackModule, self)._log_event(event, **event_data)
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 202, in _log_event
    event_data['res'] = censor(deepcopy(event_data['res']))
  File "/usr/lib/python2.7/site-packages/awx/plugins/callback/job_event_callback.py", line 70, in censor
    if obj.get('_ansible_no_log', False):
AttributeError: 'str' object has no attribute '
```

**Comment by bcoca** [comment]
for Ansible Tower please go to http://support.ansible.com or email support@ansible.com
