### ISSUE TITLE
Exception on non-static include after a static one

### ISSUE THREAD

**Issue by olfway** [ansible/ansible#15193]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 5fdac707fd) last updated 2016/03/29 10:43:45 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 0268864211) last updated 2016/03/29 10:43:50 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 6978984244) last updated 2016/03/29 10:43:55 (GMT +300)
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Exception on non-static include after a static one
##### STEPS TO REPRODUCE

include-test-static-dynamic.yml:

```
- hosts: localhost
  gather_facts: False
  tasks:
    - include: include-test_include-localhost-dynamic.yml
```

include-test_include-localhost-dynamic.yml

```
- include: include-test_print-{{ inventory_hostname }}.yml
```

include-test_print-localhost.yml

```
- debug: msg="{{ inventory_hostname }}"
```
##### EXPECTED RESULTS

```
TASK [debug] *******************************************************************
task path: /Volumes/Users/int/Development/Ansible/ansible-include/include-test_print-localhost.yml:2
ok: [localhost] => {
    "msg": "localhost"
}
```
##### ACTUAL RESULTS

ansible-playbook -i "localhost," -c local -vvv include-test-static-dynamic.yml

```
TASK [include] *****************************************************************
task path: /Volumes/Users/int/Development/Ansible/ansible-include/include-test_include-localhost-dynamic.yml:2
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'rfind'
the full traceback was:

Traceback (most recent call last):
  File "/Volumes/Users/int/Development/Ansible/ansible/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/Volumes/Users/int/Development/Ansible/ansible/lib/ansible/cli/playbook.py", line 151, in run
    results = pbex.run()
  File "/Volumes/Users/int/Development/Ansible/ansible/lib/ansible/executor/playbook_executor.py", line 141, in run
    result = self._tqm.run(play=play)
  File "/Volumes/Users/int/Development/Ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 246, in run
    play_return = strategy.run(iterator, play_context)
  File "/Volumes/Users/int/Development/Ansible/ansible/lib/ansible/plugins/strategy/linear.py", line 284, in run
    variable_manager=self._variable_manager
  File "/Volumes/Users/int/Development/Ansible/ansible/lib/ansible/playbook/included_file.py", line 96, in process_include_results
    parent_include_dir = templar.template(os.path.dirname(parent_include.args.get('_raw_params')))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by jimi-c** [comment]
Hi @olfway, I fixed this yesterday, so if you update to the latest devel you should be good to go.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
