### ISSUE TITLE
uri body parameter can't receive json string

### ISSUE THREAD

**Issue by XooR** [ansible/ansible#15262]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 5cd3f71792) last updated 2016/02/03 16:32:33 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/04/04 16:18:00 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/04/04 16:18:00 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT
- I'm running Ansible from 'Ubuntu 14.04.4 LTS'
##### SUMMARY

Problem is that if I use `to_json` filter in 'uri' parameter body it gets passed as dictionary. In Ansible 1.9 this worked.
##### STEPS TO REPRODUCE

json_error.yml:

``` YAML

---
- hosts: localhost
  vars:
    some_dict:
      key_a:
        key_b: value
  tasks:
    - uri: url="http://www.google.com/" method=GET body="{{ some_dict | to_json }}"
```

```
$ ansible-playbook json_error.yml -vvvv
```

##### EXPECTED RESULTS

```
failed: [localhost] => {"content": "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 400 (Bad Request)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>400.</b> <ins>That’s an error.</ins>\n  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>\n", "content_length": "1555", "content_type": "text/html; charset=UTF-8", "date": "Mon, 04 Apr 2016 14:37:30 GMT", "failed": true, "redirected": false, "status": 400}
msg: Status code was not [200]
```
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/stanislava/.ansible/tmp/ansible-tmp-1459780543.47-169023004249196/uri", line 2501, in <module>
    main()
  File "/home/stanislava/.ansible/tmp/ansible-tmp-1459780543.47-169023004249196/uri", line 453, in main
    resp, content, dest = uri(module, url, dest, user, password, body, body_format, method, dict_headers, redirects, socket_timeout, validate_certs)
  File "/home/stanislava/.ansible/tmp/ansible-tmp-1459780543.47-169023004249196/uri", line 340, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)     
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1569, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1316, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1252, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 839, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 811, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: must be string or buffer, not dict

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "uri"}, "parsed": false}
```

**Comment by sivel** [comment]
You should add `body_format=json` to your task.  This will ensure that the body is a string and that the correct content-type headers are set.
