### ISSUE TITLE
__init.py__ data check for no stdout and None as well

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#15329]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```

ansible 2.0.0.2
##### CONFIGURATION

 https://github.com/yhekma/ansible_extra/blob/master/library/db2
##### OS / ENVIRONMENT

RedHat 7
##### SUMMARY

Running playbook with db2 action:
action: db2 instance=db2inst1 command='db2 list db directory' outputfile=/tmp/output.txt

gives error message:
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 401, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
 *\* File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 477, in _execute_module
    data['stdout_lines'] = data.get('stdout', u'').splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'**
##### STEPS TO REPRODUCE

 Mentioned in Summary. DB2 10.5 used.
Example output of the command is documented at
https://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0001954.html

```
<!--- Paste example playbooks or commands between quotes -->
```

https://github.com/yhekma/ansible_extra/blob/master/library/db2

https://github.com/yhekma/ansible_extra/blob/master/library/db2
##### EXPECTED RESULTS

Output documented at https://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0001954.html
##### ACTUAL RESULTS

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 401, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
 *\* File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 477, in _execute_module
    data['stdout_lines'] = data.get('stdout', u'').splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'**

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by ghost** [comment]
Did some more tests, looks like the **init**.py is ok. '':  write_to_output(outputfile, out, output_format), gives good result.
