### ISSUE TITLE
expect module exception: AttributeError: 'list' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by do11** [ansible/ansible#15354]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Full ansible.cfg:

```
[defaults]
inventory = hosts
host_key_checking = False
```
##### SUMMARY

When using expect module ansible fail with exception when responses is list (like in second example on this page [http://docs.ansible.com/ansible/expect_module.html](http://archive.is/1bD61).

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'rstrip'
fatal: [box3 -> localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```
##### STEPS TO REPRODUCE

$ ansible-playbook examplebelow.yml -vvvv

```
- hosts: all
  gather_facts: false

  tasks:
  - expect:
      command: "bash -i"
      responses:
        "anything":
          - "quit"
    delegate_to: localhost
```

##### EXPECTED RESULTS

Well, I expect that expect module shows something except exception.
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/do/.ansible/tmp/ansible-tmp-1460226886.99-90931381656810/expect", line 2136, in <module>
    main()
  File "/home/do/.ansible/tmp/ansible-tmp-1460226886.99-90931381656810/expect", line 114, in main
    events[key.decode()] = u'%s\n' % value.rstrip('\n').decode()
AttributeError: 'list' object has no attribute 'rstrip'

fatal: [box3 -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "expect"}, "parsed": false}
```

**Comment by sivel** [comment]
Per the documentation, the second form, or list form:

> List functionality is new in 2.1.

2.1 has not yet been released.  Per your version output you are using 2.0.
