### ISSUE TITLE
when_(un)set works badly with non-strings

### ISSUE THREAD

**Issue by svyatov** [ansible/ansible#1539]
Here is simple playbook for reproduction:

``` yaml

---
- hosts: all

  tasks:
  - apt: update-cache=yes
    when_unset: $apt_cache_updated
    register: apt_cache_updated
  - apt: update-cache=yes
    when_unset: $apt_cache_updated
    register: apt_cache_updated
```

Output:

```
TASK: [apt update-cache=yes] ********************* 
ok: [192.168.22.10]

TASK: [apt update-cache=yes] ********************* 
fatal: [192.168.22.10] => Traceback (most recent call last):
  File "/Users/leonid/ansible/lib/ansible/runner/__init__.py", line 233, in _executor
    exec_rc = self._executor_internal(host)
  File "/Users/leonid/ansible/lib/ansible/runner/__init__.py", line 289, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/Users/leonid/ansible/lib/ansible/runner/__init__.py", line 344, in _executor_internal_inner
    if not utils.check_conditional(conditional):
  File "/Users/leonid/ansible/lib/ansible/utils/__init__.py", line 146, in check_conditional
    return eval(conditional.replace("\n", "\\n"))
  File "<string>", line 1
    is_unset('{'invocation': {'module_name': u'apt', 'module_args': u'update-cache=yes'}, u'changed': False}')
                         ^
SyntaxError: invalid syntax
```

The same for `when_unset: "$apt_cache_updated"` and  `when_unset: "${apt_cache_updated}"`.

The only way it works:

``` yaml

---
- hosts: all
  tasks:
  - apt: update-cache=yes
    only_if: is_unset("$apt_cache_updated")
    register: apt_cache_updated
  - apt: update-cache=yes
    only_if: is_unset("$apt_cache_updated")
    register: apt_cache_updated
```

By the way `only_if: is_unset($apt_cache_updated)` (without quotes) fails almost same way, but for first call:

```
TASK: [apt update-cache=yes] ********************* 
fatal: [192.168.22.10] => Traceback (most recent call last):
  File "/Users/leonid/ansible/lib/ansible/runner/__init__.py", line 233, in _executor
    exec_rc = self._executor_internal(host)
  File "/Users/leonid/ansible/lib/ansible/runner/__init__.py", line 289, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/Users/leonid/ansible/lib/ansible/runner/__init__.py", line 344, in _executor_internal_inner
    if not utils.check_conditional(conditional):
  File "/Users/leonid/ansible/lib/ansible/utils/__init__.py", line 146, in check_conditional
    return eval(conditional.replace("\n", "\\n"))
  File "<string>", line 1
    is_unset($apt_cache_updated)
             ^
SyntaxError: invalid syntax
```

**Comment by mpdehaan** [comment]
looks like the only_if compiler just needs to use double quotes.
