### ISSUE TITLE
gather_facts fails with latest @devel

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible#15407]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

@devel (commit 74c83a9)
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

Exception occurs when gathering facts. This seems to be caused by a recent commit as this was still working correctly some hours ago.

```
TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: travis
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1460572386.46-177743852786386 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1460572386.46-177743852786386 `" )'
<127.0.0.1> PUT /tmp/tmp8uOFc_ TO /home/travis/.ansible/tmp/ansible-tmp-1460572386.46-177743852786386/setup
<127.0.0.1> EXEC /bin/sh -c 'LC_MESSAGES=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/travis/.ansible/tmp/ansible-tmp-1460572386.46-177743852786386/setup; rm -rf "/home/travis/.ansible/tmp/ansible-tmp-1460572386.46-177743852786386/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Dj7IS8/ansible_module_setup.py", line 127, in <module>
    main()
  File "/tmp/ansible_Dj7IS8/ansible_module_setup.py", line 119, in main
    data = get_all_facts(module)
  File "/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py", line 3157, in get_all_facts
  File "/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py", line 3101, in ansible_facts
  File "/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py", line 176, in __init__
  File "/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py", line 703, in get_caps_facts
NameError: global name 'module' is not defined
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Dj7IS8/ansible_module_setup.py\", line 127, in <module>\n    main()\n  File \"/tmp/ansible_Dj7IS8/ansible_module_setup.py\", line 119, in main\n    data = get_all_facts(module)\n  File \"/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3157, in get_all_facts\n  File \"/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3101, in ansible_facts\n  File \"/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 176, in __init__\n  File \"/tmp/ansible_Dj7IS8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 703, in get_caps_facts\nNameError: global name 'module' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```
##### STEPS TO REPRODUCE

Run with `gather_facts: yes`
##### EXPECTED RESULTS

No exception, and facts gathered successfully.
##### ACTUAL RESULTS

Exception occurs, see summary.

**Comment by bcoca** [comment]
fixed via a5a6bcfbbf674ca8613f5c8b24ed7f3206f8d464
