### ISSUE TITLE
inconsistent json formatting in result stdout

### ISSUE THREAD

**Issue by beneshed** [ansible/ansible#15545]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Mac OSX 10.11.4
##### SUMMARY

We use a node script to generate json settings with a local action. In 2.0.2.0 it always is formmated as example one but in 2.0.0.2 it isn't consistent. How can we make sure it stays as example one? Or how can we un autoformat the json in example1. Our app works with example2, but not with example1
##### STEPS TO REPRODUCE

[example1](https://gist.github.com/thebenwaters/402af4bb71ec146f3703a7e7b9f56181)
[example2](https://gist.github.com/thebenwaters/7795d1cdead9280e0c5abcbc23b9ca59)

##### ACTUAL RESULTS

Example 1

```
ok: [development] => {
    "myvar": {
        "widget": {
            "debug": "on",
            "image": {
                "alignment": "center",
                "hOffset": 250,
                "name": "sun1",
                "src": "Images/Sun.png",
                "vOffset": 250
            },
            "text": {
                "alignment": "center",
                "data": "Click Here",
                "hOffset": 250,
                "name": "text1",
                "onMouseUp": "sun1.opacity = (sun1.opacity / 100) * 90;",
                "size": 36,
                "style": "bold",
                "vOffset": 100
            },
            "window": {
                "height": 500,
                "name": "main_window",
                "title": "Sample Konfabulator Widget",
                "width": 500
            }
        }
    }
}
```

Example 2

```
ok: [development] => {
    "tmp_settings.stdout": "{\"web-app\":{\"servlet\":[{\"servlet-name\":\"cofaxCDS\",\"servlet-class\":\"org.cofax.cds.CDSServlet\",\"init-param\":{\"configGlossary:installationAt\":\"Philadelphia, PA\",\"configGlossary:adminEmail\":\"ksm@pobox.com\",\"configGlossary:poweredBy\":\"Cofax\",\"configGlossary:poweredByIcon\":\"/images/cofax.gif\",\"configGlossary:staticPath\":\"/content/static\",\"templateProcessorClass\":\"org.cofax.WysiwygTemplate\",\"templateLoaderClass\":\"org.cofax.FilesTemplateLoader\",\"templatePath\":\"templates\",\"templateOverridePath\":\"\",\"defaultListTemplate\":\"listTemplate.htm\",\"defaultFileTemplate\":\"articleTemplate.htm\",\"useJSP\":false,\"jspListTemplate\":\"listTemplate.jsp\",\"jspFileTemplate\":\"articleTemplate.jsp\",\"cachePackageTagsTrack\":200,\"cachePackageTagsStore\":200,\"cachePackageTagsRefresh\":60,\"cacheTemplatesTrack\":100,\"cacheTemplatesStore\":50,\"cacheTemplatesRefresh\":15,\"cachePagesTrack\":200,\"cachePagesStore\":100,\"cachePagesRefresh\":10,\"cachePagesDirtyRead\":10,\"searchEngineListTemplate\":\"forSearchEnginesList.htm\",\"searchEngineFileTemplate\":\"forSearchEngines.htm\",\"searchEngineRobotsDb\":\"WEB-INF/robots.db\",\"useDataStore\":true,\"dataStoreClass\":\"org.cofax.SqlDataStore\",\"redirectionClass\":\"org.cofax.SqlRedirection\",\"dataStoreName\":\"cofax\",\"dataStoreDriver\":\"com.microsoft.jdbc.sqlserver.SQLServerDriver\",\"dataStoreUrl\":\"jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon\",\"dataStoreUser\":\"sa\",\"dataStorePassword\":\"dataStoreTestQuery\",\"dataStoreTestQuery\":\"SET NOCOUNT ON;select test='test';\",\"dataStoreLogFile\":\"/usr/local/tomcat/logs/datastore.log\",\"dataStoreInitConns\":10,\"dataStoreMaxConns\":100,\"dataStoreConnUsageLimit\":100,\"dataStoreLogLevel\":\"debug\",\"maxUrlLength\":500}},{\"servlet-name\":\"cofaxEmail\",\"servlet-class\":\"org.cofax.cds.EmailServlet\",\"init-param\":{\"mailHost\":\"mail1\",\"mailHostOverride\":\"mail2\"}},{\"servlet-name\":\"cofaxAdmin\",\"servlet-class\":\"org.cofax.cds.AdminServlet\"},{\"servlet-name\":\"fileServlet\",\"servlet-class\":\"org.cofax.cds.FileServlet\"},{\"servlet-name\":\"cofaxTools\",\"servlet-class\":\"org.cofax.cms.CofaxToolsServlet\",\"init-param\":{\"templatePath\":\"toolstemplates/\",\"log\":1,\"logLocation\":\"/usr/local/tomcat/logs/CofaxTools.log\",\"logMaxSize\":\"\",\"dataLog\":1,\"dataLogLocation\":\"/usr/local/tomcat/logs/dataLog.log\",\"dataLogMaxSize\":\"\",\"removePageCache\":\"/content/admin/remove?cache=pages&id=\",\"removeTemplateCache\":\"/content/admin/remove?cache=templates&id=\",\"fileTransferFolder\":\"/usr/local/tomcat/webapps/content/fileTransferFolder\",\"lookInContext\":1,\"adminGroupID\":4,\"betaServer\":true}}],\"servlet-mapping\":{\"cofaxCDS\":\"/\",\"cofaxEmail\":\"/cofaxutil/aemail/*\",\"cofaxAdmin\":\"/admin/*\",\"fileServlet\":\"/static/*\",\"cofaxTools\":\"/tools/*\"},\"taglib\":{\"taglib-uri\":\"cofax.tld\",\"taglib-location\":\"/WEB-INF/tlds/cofax.tld\"}}}"
}
```

In 
`ansible 2.0.2.0`

```
ok: [development] => {
    "myvar": {
        "web-app": {
            "servlet": [
                {
                    "init-param": {
                        "cachePackageTagsRefresh": 60,
                        "cachePackageTagsStore": 200,
                        "cachePackageTagsTrack": 200,
                        "cachePagesDirtyRead": 10,
                        "cachePagesRefresh": 10,
                        "cachePagesStore": 100,
                        "cachePagesTrack": 200,
                        "cacheTemplatesRefresh": 15,
                        "cacheTemplatesStore": 50,
                        "cacheTemplatesTrack": 100,
                        "configGlossary:adminEmail": "ksm@pobox.com",
                        "configGlossary:installationAt": "Philadelphia, PA",
                        "configGlossary:poweredBy": "Cofax",
                        "configGlossary:poweredByIcon": "/images/cofax.gif",
                        "configGlossary:staticPath": "/content/static",
                        "dataStoreClass": "org.cofax.SqlDataStore",
                        "dataStoreConnUsageLimit": 100,
                        "dataStoreDriver": "com.microsoft.jdbc.sqlserver.SQLServerDriver",
                        "dataStoreInitConns": 10,
                        "dataStoreLogFile": "/usr/local/tomcat/logs/datastore.log",
                        "dataStoreLogLevel": "debug",
                        "dataStoreMaxConns": 100,
                        "dataStoreName": "cofax",
                        "dataStorePassword": "dataStoreTestQuery",
                        "dataStoreTestQuery": "SET NOCOUNT ON;select test='test';",
                        "dataStoreUrl": "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon",
                        "dataStoreUser": "sa",
                        "defaultFileTemplate": "articleTemplate.htm",
                        "defaultListTemplate": "listTemplate.htm",
                        "jspFileTemplate": "articleTemplate.jsp",
                        "jspListTemplate": "listTemplate.jsp",
                        "maxUrlLength": 500,
                        "redirectionClass": "org.cofax.SqlRedirection",
                        "searchEngineFileTemplate": "forSearchEngines.htm",
                        "searchEngineListTemplate": "forSearchEnginesList.htm",
                        "searchEngineRobotsDb": "WEB-INF/robots.db",
                        "templateLoaderClass": "org.cofax.FilesTemplateLoader",
                        "templateOverridePath": "",
                        "templatePath": "templates",
                        "templateProcessorClass": "org.cofax.WysiwygTemplate",
                        "useDataStore": true,
                        "useJSP": false
                    },
                    "servlet-class": "org.cofax.cds.CDSServlet",
                    "servlet-name": "cofaxCDS"
                },
                {
                    "init-param": {
                        "mailHost": "mail1",
                        "mailHostOverride": "mail2"
                    },
                    "servlet-class": "org.cofax.cds.EmailServlet",
                    "servlet-name": "cofaxEmail"
                },
                {
                    "servlet-class": "org.cofax.cds.AdminServlet",
                    "servlet-name": "cofaxAdmin"
                },
                {
                    "servlet-class": "org.cofax.cds.FileServlet",
                    "servlet-name": "fileServlet"
                },
                {
                    "init-param": {
                        "adminGroupID": 4,
                        "betaServer": true,
                        "dataLog": 1,
                        "dataLogLocation": "/usr/local/tomcat/logs/dataLog.log",
                        "dataLogMaxSize": "",
                        "fileTransferFolder": "/usr/local/tomcat/webapps/content/fileTransferFolder",
                        "log": 1,
                        "logLocation": "/usr/local/tomcat/logs/CofaxTools.log",
                        "logMaxSize": "",
                        "lookInContext": 1,
                        "removePageCache": "/content/admin/remove?cache=pages&id=",
                        "removeTemplateCache": "/content/admin/remove?cache=templates&id=",
                        "templatePath": "toolstemplates/"
                    },
                    "servlet-class": "org.cofax.cms.CofaxToolsServlet",
                    "servlet-name": "cofaxTools"
                }
            ],
            "servlet-mapping": {
                "cofaxAdmin": "/admin/*",
                "cofaxCDS": "/",
                "cofaxEmail": "/cofaxutil/aemail/*",
                "cofaxTools": "/tools/*",
                "fileServlet": "/static/*"
            },
            "taglib": {
                "taglib-location": "/WEB-INF/tlds/cofax.tld",
                "taglib-uri": "cofax.tld"
            }
        }
    }
}
```

Tested in 2.0.2.0

```
 - set_fact: myvar="{{tmp_settings.stdout}}"
 - debug: var="{{myvar | quote }}"
```

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 379, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/task.py", line 234, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 309, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 359, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 331, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 495, in _do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/filter/core.py", line 122, in quote
    return pipes.quote(a)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pipes.py", line 278, in quote
    return "'" + file.replace("'", "'\"'\"'") + "'"
AttributeError: 'dict' object has no attribute 'replace'

fatal: [development]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by bcoca** [comment]
the first is being recognized as a data structure, the 2nd as string ~~, since you are not showing what/how is displaying them I cannot really help much.~~

had missed  `- debug: var="{{myvar | quote }}"`

but that still stands, it is displaying a quoted string, if you want JSON use `|to_json` or `|to_nice_json` filters

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by beneshed** [comment]
But what if i want the quoted string @bcoca ?
If I escape the json, it then escapes the escapes. There doesn't be a way in 2.0.2.0 to be able to force an escaped json string.

Ok so if you use the `|quote` filter on the register instead of the debug it works fine, but now there's a leading single quote and ending single quote, which is invalid

```
{"settings": "'{\"web-app\":{\"servlet\":[{\"servlet-name\":\"cofaxCDS\",\"servlet-class\":\"org.cofax.cds.CDSServlet\",\"init-param\":{\"configGlossary:installationAt\":\"Philadelphia, PA\",\"configGlossary:adminEmail\":\"ksm@pobox.com\",\"configGlossary:poweredBy\":\"Cofax\",\"configGlossary:poweredByIcon\":\"/images/cofax.gif\",\"configGlossary:staticPath\":\"/content/static\",\"templateProcessorClass\":\"org.cofax.WysiwygTemplate\",\"templateLoaderClass\":\"org.cofax.FilesTemplateLoader\",\"templatePath\":\"templates\",\"templateOverridePath\":\"\",\"defaultListTemplate\":\"listTemplate.htm\",\"defaultFileTemplate\":\"articleTemplate.htm\",\"useJSP\":false,\"jspListTemplate\":\"listTemplate.jsp\",\"jspFileTemplate\":\"articleTemplate.jsp\",\"cachePackageTagsTrack\":200,\"cachePackageTagsStore\":200,\"cachePackageTagsRefresh\":60,\"cacheTemplatesTrack\":100,\"cacheTemplatesStore\":50,\"cacheTemplatesRefresh\":15,\"cachePagesTrack\":200,\"cachePagesStore\":100,\"cachePagesRefresh\":10,\"cachePagesDirtyRead\":10,\"searchEngineListTemplate\":\"forSearchEnginesList.htm\",\"searchEngineFileTemplate\":\"forSearchEngines.htm\",\"searchEngineRobotsDb\":\"WEB-INF/robots.db\",\"useDataStore\":true,\"dataStoreClass\":\"org.cofax.SqlDataStore\",\"redirectionClass\":\"org.cofax.SqlRedirection\",\"dataStoreName\":\"cofax\",\"dataStoreDriver\":\"com.microsoft.jdbc.sqlserver.SQLServerDriver\",\"dataStoreUrl\":\"jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon\",\"dataStoreUser\":\"sa\",\"dataStorePassword\":\"dataStoreTestQuery\",\"dataStoreTestQuery\":\"SET NOCOUNT ON;select test='\"'\"'test'\"'\"';\",\"dataStoreLogFile\":\"/usr/local/tomcat/logs/datastore.log\",\"dataStoreInitConns\":10,\"dataStoreMaxConns\":100,\"dataStoreConnUsageLimit\":100,\"dataStoreLogLevel\":\"debug\",\"maxUrlLength\":500}},{\"servlet-name\":\"cofaxEmail\",\"servlet-class\":\"org.cofax.cds.EmailServlet\",\"init-param\":{\"mailHost\":\"mail1\",\"mailHostOverride\":\"mail2\"}},{\"servlet-name\":\"cofaxAdmin\",\"servlet-class\":\"org.cofax.cds.AdminServlet\"},{\"servlet-name\":\"fileServlet\",\"servlet-class\":\"org.cofax.cds.FileServlet\"},{\"servlet-name\":\"cofaxTools\",\"servlet-class\":\"org.cofax.cms.CofaxToolsServlet\",\"init-param\":{\"templatePath\":\"toolstemplates/\",\"log\":1,\"logLocation\":\"/usr/local/tomcat/logs/CofaxTools.log\",\"logMaxSize\":\"\",\"dataLog\":1,\"dataLogLocation\":\"/usr/local/tomcat/logs/dataLog.log\",\"dataLogMaxSize\":\"\",\"removePageCache\":\"/content/admin/remove?cache=pages&id=\",\"removeTemplateCache\":\"/content/admin/remove?cache=templates&id=\",\"fileTransferFolder\":\"/usr/local/tomcat/webapps/content/fileTransferFolder\",\"lookInContext\":1,\"adminGroupID\":4,\"betaServer\":true}}],\"servlet-mapping\":{\"cofaxCDS\":\"/\",\"cofaxEmail\":\"/cofaxutil/aemail/*\",\"cofaxAdmin\":\"/admin/*\",\"fileServlet\":\"/static/*\",\"cofaxTools\":\"/tools/*\"},\"taglib\":{\"taglib-uri\":\"cofax.tld\",\"taglib-location\":\"/WEB-INF/tlds/cofax.tld\"}}}'"}, "changed": false, "invocation": {"module_args": {"worker_settings": "'{\"web-app\":{\"servlet\":[{\"servlet-name\":\"cofaxCDS\",\"servlet-class\":\"org.cofax.cds.CDSServlet\",\"init-param\":{\"configGlossary:installationAt\":\"Philadelphia, PA\",\"configGlossary:adminEmail\":\"ksm@pobox.com\",\"configGlossary:poweredBy\":\"Cofax\",\"configGlossary:poweredByIcon\":\"/images/cofax.gif\",\"configGlossary:staticPath\":\"/content/static\",\"templateProcessorClass\":\"org.cofax.WysiwygTemplate\",\"templateLoaderClass\":\"org.cofax.FilesTemplateLoader\",\"templatePath\":\"templates\",\"templateOverridePath\":\"\",\"defaultListTemplate\":\"listTemplate.htm\",\"defaultFileTemplate\":\"articleTemplate.htm\",\"useJSP\":false,\"jspListTemplate\":\"listTemplate.jsp\",\"jspFileTemplate\":\"articleTemplate.jsp\",\"cachePackageTagsTrack\":200,\"cachePackageTagsStore\":200,\"cachePackageTagsRefresh\":60,\"cacheTemplatesTrack\":100,\"cacheTemplatesStore\":50,\"cacheTemplatesRefresh\":15,\"cachePagesTrack\":200,\"cachePagesStore\":100,\"cachePagesRefresh\":10,\"cachePagesDirtyRead\":10,\"searchEngineListTemplate\":\"forSearchEnginesList.htm\",\"searchEngineFileTemplate\":\"forSearchEngines.htm\",\"searchEngineRobotsDb\":\"WEB-INF/robots.db\",\"useDataStore\":true,\"dataStoreClass\":\"org.cofax.SqlDataStore\",\"redirectionClass\":\"org.cofax.SqlRedirection\",\"dataStoreName\":\"cofax\",\"dataStoreDriver\":\"com.microsoft.jdbc.sqlserver.SQLServerDriver\",\"dataStoreUrl\":\"jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon\",\"dataStoreUser\":\"sa\",\"dataStorePassword\":\"dataStoreTestQuery\",\"dataStoreTestQuery\":\"SET NOCOUNT ON;select test='\"'\"'test'\"'\"';\",\"dataStoreLogFile\":\"/usr/local/tomcat/logs/datastore.log\",\"dataStoreInitConns\":10,\"dataStoreMaxConns\":100,\"dataStoreConnUsageLimit\":100,\"dataStoreLogLevel\":\"debug\",\"maxUrlLength\":500}},{\"servlet-name\":\"cofaxEmail\",\"servlet-class\":\"org.cofax.cds.EmailServlet\",\"init-param\":{\"mailHost\":\"mail1\",\"mailHostOverride\":\"mail2\"}},{\"servlet-name\":\"cofaxAdmin\",\"servlet-class\":\"org.cofax.cds.AdminServlet\"},{\"servlet-name\":\"fileServlet\",\"servlet-class\":\"org.cofax.cds.FileServlet\"},{\"servlet-name\":\"cofaxTools\",\"servlet-class\":\"org.cofax.cms.CofaxToolsServlet\",\"init-param\":{\"templatePath\":\"toolstemplates/\",\"log\":1,\"logLocation\":\"/usr/local/tomcat/logs/CofaxTools.log\",\"logMaxSize\":\"\",\"dataLog\":1,\"dataLogLocation\":\"/usr/local/tomcat/logs/dataLog.log\",\"dataLogMaxSize\":\"\",\"removePageCache\":\"/content/admin/remove?cache=pages&id=\",\"removeTemplateCache\":\"/content/admin/remove?cache=templates&id=\",\"fileTransferFolder\":\"/usr/local/tomcat/webapps/content/fileTransferFolder\",\"lookInContext\":1,\"adminGroupID\":4,\"betaServer\":true}}],\"servlet-mapping\":{\"cofaxCDS\":\"/\",\"cofaxEmail\":\"/cofaxutil/aemail/*\",\"cofaxAdmin\":\"/admin/*\",\"fileServlet\":\"/static/*\",\"cofaxTools\":\"/tools/*\"},\"taglib\":{\"taglib-uri\":\"cofax.tld\",\"taglib-location\":\"/WEB-INF/tlds/cofax.tld\"}}}'"}, "module_name": "set_fact"}}
```

As soon as I run a filter to remove the single quotes and the beginning and end it starts to autoformat...

I've posted to both irc and the mailing list and am waiting 😄

**Comment by beneshed** [comment]
@bcoca anytime I try to hack my way around it in 2.0.2.0 it throws a lot of stack traces....

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 379, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/task.py", line 234, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 309, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 359, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 331, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 474, in _do_template
    data = _escape_backslashes(data, myenv)
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 94, in _escape_backslashes
    for token in jinja_env.lex(d2):
  File "/usr/local/lib/python2.7/site-packages/jinja2/lexer.py", line 734, in tokeniter
    name, filename)
TemplateSyntaxError: unexpected char u"'" at 25
  line 1

fatal: [webdev]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by beneshed** [comment]
It works when writing to a file, but not with registering, set_fact, etc. (something with stdout?)
