### ISSUE TITLE
error in runtest function in hacking/test-module prevents modules from being tested

### ISSUE THREAD

**Issue by k4otix** [ansible/ansible#15606]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 54440a30c0)
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The test-module script in ansible/hacking fails to run due to incorrect call to runtest() function. I believe the issue can be fixed by removing the "modstyle" parameter from the runtest function definition (line no. 178) in the file; it is not referenced anywhere in the funcion.
##### STEPS TO REPRODUCE

```
$ ./hacking/test-module -m ./lib/ansible/modules/core/commands/command.py -a "date"
```

##### EXPECTED RESULTS

```
***********************************
RAW OUTPUT
{"changed": true, "end": "2016-04-26 12:39:21.177339", "stdout": "Tue Apr 26 12:39:21 EDT 2016", "cmd": ["date"], "rc": 0, "start": "2016-04-26 12:39:21.173692", "stderr": "", "delta": "0:00:00.003647", "invocation": {"module_args": {"warn": true, "executable": null, "chdir": null, "_raw_params": "date", "removes": null, "creates": null, "_uses_shell": false}}, "warnings": []}


***********************************
PARSED OUTPUT
{
    "changed": true, 
    "cmd": [
        "date"
    ], 
    "delta": "0:00:00.003647", 
    "end": "2016-04-26 12:39:21.177339", 
    "invocation": {
        "module_args": {
            "_raw_params": "date", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2016-04-26 12:39:21.173692", 
    "stderr": "", 
    "stdout": "Tue Apr 26 12:39:21 EDT 2016", 
    "warnings": []
}

```
##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "./hacking/test-module", line 242, in <module>
    main()
  File "./hacking/test-module", line 238, in main
    runtest(modfile, argspath, modname, module_style)
TypeError: runtest() takes exactly 5 arguments (4 given)

```

**Comment by abadger** [comment]
You're correct, thanks for spotting that!  When I worked on test-module last week, I seem to have added module_style/modstyle twice in the definition of the function.  Fixed by removing modstyle just as you suggested:

https://github.com/ansible/ansible/commit/2762f12f7f5b2ce73e96db5676f5a5aa15663ee6
