### ISSUE TITLE
AttributeError: 'AnsibleLoader' object has no attribute 'dispose'

### ISSUE THREAD

**Issue by jl-montes** [ansible/ansible#15660]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

CentOS 6.7
##### SUMMARY

Running ansible-playbook <playbookname>.yml results in 

ERROR! Unexpected Exception: 'AnsibleLoader' object has no attribute 'dispose'
##### STEPS TO REPRODUCE

$ ansible-playbook <playbookname>.yml

```
<!--- Paste example playbooks or commands between quotes -->

---
- hosts: all:!coreos
  remote_user: jmontes
  become: yes
  become_method: sudo
  tasks:
   - name: Update ubuntu packages (Debian based) 
     apt: update_cache=yes upgrade=dist 
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   - name: Check if packages need to be autoremoved (Debian based)
     command: apt-get --dry-run autoremove
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     register: check_autoremove
     changed_when: False
   - name: Autoremove unused packages (Debian based)
     command: apt-get -y autoremove --purge
     when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') 
           and ("'packages will be REMOVED' in check_autoremove.stdout")
   - name: Limit the number of kernels (RedHat)
     lineinfile: dest=/etc/yum.conf 
           regexp="^installonly_limit" line="installonly_limit=3" state=present
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

   - name: Update yum packages (RedHat based) 
     yum: name=* state=latest 
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
   - name: Cleanup yum cache (RedHat based)
     command: yum clean all
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

```

##### EXPECTED RESULTS

My Playbooks would always run without issues until recently
##### ACTUAL RESULTS

Playbook never executed, ansible errored out

```
<!--- Paste verbatim command output between quotes -->
$ ansible-playbook -vvv update-os-packages.yml 
Using /etc/ansible/ansible.cfg as config file
ERROR! Unexpected Exception: 'AnsibleLoader' object has no attribute 'dispose'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.6/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.6/site-packages/ansible/executor/playbook_executor.py", line 71, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 52, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 74, in _load_playbook_data
    ds = self._loader.load_from_file(os.path.basename(file_name))
  File "/usr/lib/python2.6/site-packages/ansible/parsing/dataloader.py", line 114, in load_from_file
    parsed_data = self.load(data=file_data, file_name=file_name, show_content=show_content)
  File "/usr/lib/python2.6/site-packages/ansible/parsing/dataloader.py", line 93, in load
    new_data = self._safe_load(new_data, file_name=file_name)
  File "/usr/lib/python2.6/site-packages/ansible/parsing/dataloader.py", line 150, in _safe_load
    loader.dispose()
AttributeError: 'AnsibleLoader' object has no attribute 'dispose'
```

**Comment by xox2** [comment]
Probably, it has been fixed in v2.0.2.
- https://github.com/ansible/ansible/blob/v2.0.2.0-1/lib/ansible/parsing/dataloader.py#L148-L152
- [fix issues with older yaml lib versions · ansible/ansible@df1ee5a](https://github.com/ansible/ansible/commit/df1ee5a15bc4c085a061bc893786800c46117627)

**Comment by preethi29** [comment]
I get the same error with v 2.0.1. python-yaml version installed is 3.0.9.

**Comment by bcoca** [comment]
already fixed via cc3cb0f65e4904775ca4e3eb277a606943e78887

**Comment by preethi29** [comment]
Is it fixed in 2.0.1?

**Comment by bcoca** [comment]
no,  but it seems that the fix is included in subsequent releases

**Comment by bcoca** [comment]
closing as this has already been fixed
