### ISSUE TITLE
Regression in delegate_to: {{ item }} delegate_facts: true

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/ansible#15694]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

`v2.1.0.0-0.1.rc1`

```
ansible 2.1.0.0 (detached HEAD 5954a82dd6) last updated 2016/05/02 23:17:06 (GMT -400)
  lib/ansible/modules/core: (detached HEAD ce79e7c72d) last updated 2016/05/02 23:17:08 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 156a8cd0b3) last updated 2016/05/02 23:17:08 (GMT -400)
  config file = /Users/meyers/ansible/examples/ansible_performance/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Mac OS X
##### SUMMARY

`set_fact` fails with a traceback when using `{{ item }}` in `delegate_to` with `delegate_facts: true` 
##### STEPS TO REPRODUCE

`ansible-playbook -i inventory main.yml -vvvv`

```
# inventory
host1
localhost

[all:vars]
ansible_connection=local
```

```
- hosts: localhost
  tasks:
    - set_fact:
        foo: "bar"
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items:
        - host1
```

##### EXPECTED RESULTS

Success!
##### ACTUAL RESULTS

```
No config file found; using defaults
Loaded callback default of type stdout, v2.0

PLAYBOOK: main.yml *************************************************************
1 plays in main.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: meyers
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462245894.94-220195374966035 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462245894.94-220195374966035 `" )'
<localhost> PUT /var/folders/3j/jfj3hzx55nvgvmw983jr7n2m0000gn/T/tmppsN1xj TO /Users/meyers/.ansible/tmp/ansible-tmp-1462245894.94-220195374966035/setup
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/meyers/.ansible/tmp/ansible-tmp-1462245894.94-220195374966035/setup; rm -rf "/Users/meyers/.ansible/tmp/ansible-tmp-1462245894.94-220195374966035/" > /dev/null 2>&1'
ok: [localhost]

TASK [set_fact] ****************************************************************
task path: /Users/meyers/ansible/examples/bugs/set_fact_delegate_facts/main.yml:3
ok: [localhost -> host1] => (item=host1) => {"ansible_facts": {"foo": "bar"}, "changed": false, "invocation": {"module_args": {"foo": "bar"}, "module_name": "set_fact"}, "item": "host1"}
ERROR! Unexpected Exception: 'NoneType' object does not support item assignment
the full traceback was:

Traceback (most recent call last):
  File "/Users/meyers/ansible/ansible/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/Users/meyers/ansible/ansible/lib/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/Users/meyers/ansible/ansible/lib/ansible/executor/playbook_executor.py", line 141, in run
    result = self._tqm.run(play=play)
  File "/Users/meyers/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 246, in run
    play_return = strategy.run(iterator, play_context)
  File "/Users/meyers/ansible/ansible/lib/ansible/plugins/strategy/linear.py", line 268, in run
    results += self._wait_on_pending_results(iterator)
  File "/Users/meyers/ansible/ansible/lib/ansible/plugins/strategy/__init__.py", line 391, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/Users/meyers/ansible/ansible/lib/ansible/plugins/strategy/__init__.py", line 339, in _process_pending_results
    task_vars[loop_var] = item
TypeError: 'NoneType' object does not support item assignment
```

**Comment by abadger** [comment]
First bad commit is 6eefc11c3954cbdd2f439c0fad0b9527461b4383

Assigning to @jimi-c to take a look at.
