### ISSUE TITLE
Install ansible inside virtualenv

### ISSUE THREAD

**Issue by weldpua2008** [ansible/ansible#15733]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
>= 2.0.0
```
##### OS / ENVIRONMENT

lsb_release -a

```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.3 LTS
Release:        12.04
Codename:       precise
```
##### SUMMARY

I am trying to install Ansible at vitrualenv. I tried do this until 2.0.0.0 and it worked.
I tried install ansible 2.0.0.0, 2.0.0.1, 2.0.0.2, 2.0.1.0, 2.0.2.0 but got same error.
##### STEPS TO REPRODUCE

```
export venv_name="ansible_2x_virt_env"
mkdir ~/venv && cd ~/venv
echo "Virtualenv ${venv_name} directory" > README
virtualenv --no-site-packages --prompt="ansible" ${venv_name:-venv}
. ~/venv/${venv_name:-venv}/bin/activate
~/venv/${venv_name:-venv}/bin/pip install  -U pip
~/venv/${venv_name:-venv}/bin/pip install  -U setuptools
~/venv/${venv_name:-venv}/bin/pip install ansible
```
##### EXPECTED RESULTS

ansible 2.0.X
##### ACTUAL RESULTS

```
ansibleroot@[RDE1.3]:~/venv# ansible --version
ERROR! Unexpected Exception: jinja2
the full traceback was:

Traceback (most recent call last):
  File "/root/venv/ansible_virt_env/bin/ansible", line 75, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 32, in <module>
    from ansible.parsing.vault import VaultLib
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 67, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/venv/ansible_virt_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: jinja2
```

**Comment by alikins** [comment]
Could you include a log of the output from the 'pip install' command?

`virtualenv --no-site-packages --prompt="ansible" ${venv_name:-venv}`

That creates a virtual env called ansible_2x_virt_env

`ansibleroot@[RDE1.3]:~/venv# ansible --version`

`Traceback (most recent call last):
  File "/root/venv/ansible_virt_env/bin/ansible", line 75, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli`

The version of ansible that is on the path is from the virtual env called 'ansible_virt_env'.

Is `~/venv/${venv_name:-venv}/bin/activate` failing to update the PATH? 

What does PATH/PYTHONPATH look like after the install attempt?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
