### ISSUE TITLE
fetch module doesn't respect become_method: sudo

### ISSUE THREAD

**Issue by lin-zhao** [ansible/ansible#15933]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0 (detached HEAD 26209342a2) last updated 2016/05/19 22:46:00 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 38a38bbd03) last updated 2016/05/19 22:46:08 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 40acb516fd) last updated 2016/05/19 22:46:16 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux ip-10-10-2-85.us-west-2.compute.internal 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

When using fetch module with sudo, and src being in a directory that belongs to root, the task fails with "Permission denied" error
##### STEPS TO REPRODUCE

```
-  fetch: dest=some_path src=local_directory_belonging_to_root/some_file flat=yes
   delegate_to: some_host
   become: yes
   become_method: true
```
##### EXPECTED RESULTS

File gets fetched successfully as this command is expected to be run as root
##### ACTUAL RESULTS

```
<10.10.2.85> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.10.2.85> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/opt/exabeam_installer/.ssh/key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/ec2-user/.ansible/cp/ansible-ssh-%h-%p-%r 10.10.2.85 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1463702218.97-115300537888150 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1463702218.97-115300537888150 `" )'"'"''
<10.10.2.85> PUT /tmp/tmpe8lg5Z TO /home/ec2-user/.ansible/tmp/ansible-tmp-1463702218.97-115300537888150/slurp
<10.10.2.85> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/opt/exabeam_installer/.ssh/key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/ec2-user/.ansible/cp/ansible-ssh-%h-%p-%r '[10.10.2.85]'
<10.10.2.85> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.10.2.85> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/opt/exabeam_installer/.ssh/key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/ec2-user/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.10.2.85 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-mlvfhpagemvngflrgczvmrrhsnlkiayl; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1463702218.97-115300537888150/slurp; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1463702218.97-115300537888150/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/opt/exabeam_installer/.env/src/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/opt/exabeam_installer/.env/src/ansible/lib/ansible/executor/task_executor.py", line 424, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/exabeam_installer/.env/src/ansible/lib/ansible/plugins/action/fetch.py", line 155, in run
    makedirs_safe(os.path.dirname(dest))
  File "/opt/exabeam_installer/.env/src/ansible/lib/ansible/utils/path.py", line 44, in makedirs_safe
    os.makedirs(path)
  File "/opt/exabeam_installer/.env/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/tmp/tmp.M9ZTKBPuQw/exa-support-05-19'

fatal: [master1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by bcoca** [comment]
this is failing in making the 'local' directories to store the fetched files in, this should NOT be using become as that only affects the target or remote machine.

**Comment by lin-zhao** [comment]
@bcoca thanks for the explaination. What's the right way to fetch a remote file to a local directory that belongs to root? The `ansible_user` has passwordless sudo right.

**Comment by bcoca** [comment]
run ansible under sudo or as root
