### ISSUE TITLE
Fireball can't transfer binary files

### ISSUE THREAD

**Issue by titanous** [ansible/ansible#1596]
I just tried a deploy script that copies a binary file with fireball (works fine with ssh), and got this:

```
fatal: [10.10.10.10] => Traceback (most recent call last):
  File "/home/admin/ansible/lib/ansible/runner/__init__.py", line 263, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/admin/ansible/lib/ansible/runner/__init__.py", line 326, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/admin/ansible/lib/ansible/runner/__init__.py", line 428, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject)
  File "/home/admin/ansible/lib/ansible/runner/action_plugins/copy.py", line 79, in run
    conn.put_file(source, tmp_src)
  File "/home/admin/ansible/lib/ansible/runner/connection_plugins/fireball.py", line 102, in put_file
    data = utils.jsonify(data)
  File "/home/admin/ansible/lib/ansible/utils.py", line 127, in jsonify
    return json.dumps(result2, sort_keys=True)
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 203, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 428, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 384, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8c in position 24: invalid start byte
```

I'm running ansible 2bdad2c393afabb8670c3a2162938414caec3019.

**Comment by mpdehaan** [comment]
Are you using the copy module or fetch?

**Comment by titanous** [comment]
Copy.

**Comment by mpdehaan** [comment]
Ok, I would suggest you add some debug to see what is in this part:

```
data = utils.jsonify(data)
```

**Comment by titanous** [comment]
The problem is pretty clear: binary data isn't UTF-8, and python's encoder is blowing up when it tries to stuff a binary into the UTF-8 encoding.

The question here is whether fireball is intended to transfer arbitrarily sized binary files? If so, file buffering needs to be implemented so that the entire file isn't loaded into memory, and it needs to be transfered using binary encoding, not UTF-8. If not, then there should be some docs added that explain that binary transfers are not supported.

**Comment by mpdehaan** [comment]
Was not intended but do not see why we can't just base64 encode and decode all files for fireball.

-- Michael

**Comment by mpdehaan** [comment]
We could also teach it to chunk.  By we I mean someone :)

**Comment by mpdehaan** [comment]
ok, pushed some fixes to base64 transfers.  Slightly tested, so more testing is welcome.

I also noticed it was fairly broken with fetch, so I made fetch work again.
