### ISSUE TITLE
python3 cannot use ansible api2.0 

### ISSUE THREAD

**Issue by qingshanli1988** [ansible/ansible#16001]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0
python 3.5

user ansible api 2.0 :
http://docs.ansible.com/ansible/developing_api.html
```
##### OS / ENVIRONMENT

centos 7 
##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "bb.py", line 42, in <module>
    result = tqm.run(play)
  File "/apps/dbdat/envdolphin/lib/python3.5/site-packages/ansible-2.2.0-py3.5.egg/ansible/executor/task_queue_manager.py", line 195, in run
    self.load_callbacks()
  File "/apps/dbdat/envdolphin/lib/python3.5/site-packages/ansible-2.2.0-py3.5.egg/ansible/executor/task_queue_manager.py", line 164, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/apps/dbdat/envdolphin/lib/python3.5/site-packages/ansible-2.2.0-py3.5.egg/ansible/plugins/__init__.py", line 368, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/apps/dbdat/envdolphin/lib/python3.5/site-packages/ansible-2.2.0-py3.5.egg/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/apps/dbdat/envdolphin/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/apps/dbdat/envdolphin/lib/python3.5/site-packages/ansible-2.2.0-py3.5.egg/ansible/plugins/callback/hipchat.py", line 32, in <module>
    from ansible.module_utils.urls import open_url
  File "/apps/dbdat/envdolphin/lib/python3.5/site-packages/ansible-2.2.0-py3.5.egg/ansible/module_utils/urls.py", line 330, in <module>
    if hasattr(httplib, 'HTTPSConnection') and hasattr(urllib2, 'HTTPSHandler'):
NameError: name 'urllib2' is not defined

```

**Comment by resmo** [comment]
ansible 2.2 is in devel.

**Comment by qingshanli1988** [comment]
ansible 2.1 hase the same error ....

**Comment by resmo** [comment]
ansible 2.1 does not support python3, ansible 2.2 will, also see http://docs.ansible.com/ansible/intro_installation.html#control-machine-requirements
