### ISSUE TITLE
Unexpected Exception setuptools 3.6 - Requirement.parse('setuptools>=11.3'))

### ISSUE THREAD

**Issue by phil-dileo** [ansible/ansible#16015]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
(2.1.0.0) Can't run Ansible --version (ergo the bug report)
```
##### CONFIGURATION

Created a new virtualenv in OSX.  Pretty basic virtualenv setup.
##### OS / ENVIRONMENT

Running OSX 10.10.3
##### SUMMARY

I'm getting setuptools exceptions when I try to use ansible. 
##### STEPS TO REPRODUCE
1. Create new virtualenv
2. pip install ansible

**Note that this issue can be fixed by:**

```
pip install -U distribute
```

It's just annoying that the setuptools issue isn't fixed during install.

Result:

```
Successfully installed ansible paramiko jinja2 PyYAML pycrypto pyasn1 cryptography MarkupSafe idna six enum34 ipaddress cffi pycparser
```

Pip list:

```
ansible (2.1.0.0)
cffi (1.6.0)
cryptography (1.3.2)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.16)
Jinja2 (2.8)
MarkupSafe (0.23)
paramiko (2.0.0)
pip (1.5.6)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (3.6)
six (1.10.0)
wsgiref (0.1.2)
```
##### EXPECTED RESULTS

NA
##### ACTUAL RESULTS

NA

```
(ansible21)phil:epitaph phil$ ansible --version
ERROR! Unexpected Exception: (setuptools 3.6 (/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))
the full traceback was:

Traceback (most recent call last):
  File "/Users/phil/.virtualenvs/ansible21/bin/ansible", line 81, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 33, in <module>
    from ansible.parsing.vault import VaultLib
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 67, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages/pkg_resources.py", line 643, in resolve
    raise VersionConflict(dist, req) # XXX put more info here
VersionConflict: (setuptools 3.6 (/Users/phil/.virtualenvs/ansible21/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))
```

**Comment by phil-dileo** [comment]
In particular I'm wondering if 
https://github.com/ansible/ansible/blob/devel/setup.py#L25
can include a min for setuptools.

**Comment by ajain17** [comment]
I added setuptools=11.3 to my requirements.txt and it worked.

**Comment by abadger** [comment]
We've added code to be more graceful about this.  The problem is in pip.

We want to work on older systems that do not have a newer setuptools thus we cannot specify a newer setuptools minimum than we actually need.  We make optional use of cryptography if it's installed.  If cryptography is installed, it requires the newer setuptools. When pip installs ansible, it will end up upgrading or installing cryptography but not upgrading setuptools because pip only looks at version information for the initial package's deps, not the depended upon package's deps.  This leads to the error.

The code we've added makes it so cryptography failing to import for the pkg_resources error is treated the same as an ImportError.  You can see that code here: https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault/__init__.py#L82
