### ISSUE TITLE
Ansible fails to run modules against CoreOS

### ISSUE THREAD

**Issue by istaheev** [ansible/ansible#16063]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/ilya/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

The only configuration change is to disable host key checking:

```
[defaults]
host_key_checking = False
```
##### OS / ENVIRONMENT

Host OS: `Linux ilya-pc 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
Target OS: `Linux etcd-staging-0 4.5.0-coreos-r1 #2 SMP Tue May 24 17:45:36 UTC 2016 x86_64 QEMU Virtual CPU version 2.0.0 GenuineIntel GNU/Linux`
##### SUMMARY

Running any module or playbooks against CoreOS fails with following error:

```
<etcd-staging-0> ESTABLISH SSH CONNECTION FOR USER: core
<etcd-staging-0> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=/home/ilya/.ansible/cp/ansible-ssh-%h-%p-%r etcd-staging-0 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161 `" && echo ansible-tmp-1464680549.2-230558530199161="` echo $HOME/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161 `" ) && sleep 0'"'"''
<etcd-staging-0> PUT /tmp/tmpyTH9GO TO /home/core/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161/ping
<etcd-staging-0> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=/home/ilya/.ansible/cp/ansible-ssh-%h-%p-%r '[etcd-staging-0]'
<etcd-staging-0> ESTABLISH SSH CONNECTION FOR USER: core
<etcd-staging-0> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=/home/ilya/.ansible/cp/ansible-ssh-%h-%p-%r -tt etcd-staging-0 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 PATH=/home/core/bin:$PATH python /home/core/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161/ping; rm -rf "/home/core/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161/" > /dev/null 2>&1 && sleep 0'"'"''
etcd-staging-0 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ping"
    }, 
    "module_stderr": "", 
    "module_stdout": "/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\n/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n('Args:', ['PATH=/home/core/bin:$PATH python', '/tmp/ansible_AzLRr6/ansible_module_ping.py'])\r\n('Executable:', None)\r\nTraceback (most recent call last):\r\n  File \"app_main.py\", line 75, in run_toplevel\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161/ping\", line 114, in <module>\r\n    exitcode = invoke_module(module, zipped_mod, ZIPLOADER_PARAMS)\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1464680549.2-230558530199161/ping\", line 28, in invoke_module\r\n    p = subprocess.Popen(['PATH=/home/core/bin:$PATH python', module], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)\r\n  File \"/home/core/pypy/lib-python/2.7/subprocess.py\", line 712, in __init__\r\n    errread, errwrite)\r\n  File \"/home/core/pypy/lib-python/2.7/subprocess.py\", line 1333, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

It happens only against CoreOS, other Linux machines (Ubuntu ones to be precise) handle same modules without issues.

CoreOS machine is bootstrapped with PyPy using [coreos-bootstrap role](https://github.com/defunctzombie/ansible-coreos-bootstrap). Ansible version 2.0.0 handled same commands without issues.
##### STEPS TO REPRODUCE

```
ansible -i inventory coreos -m ping
```

Sample inventory file:

```
[coreos]
etcd-staging-0

[coreos:vars]
ansible_ssh_user=core
ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
```
##### EXPECTED RESULTS

```
etcd-staging-0 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```
##### ACTUAL RESULTS

Execution fails with exception:

```
Loaded callback minimal of type stdout, v2.0
<etcd-staging-0> ESTABLISH SSH CONNECTION FOR USER: core
<etcd-staging-0> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=/home/ilya/.ansible/cp/ansible-ssh-%h-%p-%r etcd-staging-0 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587 `" && echo ansible-tmp-1464681005.08-131997339542587="` echo $HOME/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587 `" ) && sleep 0'"'"''
<etcd-staging-0> PUT /tmp/tmpE9VHC_ TO /home/core/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587/ping
<etcd-staging-0> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=/home/ilya/.ansible/cp/ansible-ssh-%h-%p-%r '[etcd-staging-0]'
<etcd-staging-0> ESTABLISH SSH CONNECTION FOR USER: core
<etcd-staging-0> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=/home/ilya/.ansible/cp/ansible-ssh-%h-%p-%r -tt etcd-staging-0 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 PATH=/home/core/bin:$PATH python /home/core/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587/ping; rm -rf "/home/core/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587/" > /dev/null 2>&1 && sleep 0'"'"''
etcd-staging-0 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ping"
    }, 
    "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18008\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to etcd-staging-0 closed.\r\n", 
    "module_stdout": "/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\n/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n('Args:', ['PATH=/home/core/bin:$PATH python', '/tmp/ansible_KKhscy/ansible_module_ping.py'])\r\n('Executable:', None)\r\nTraceback (most recent call last):\r\n  File \"app_main.py\", line 75, in run_toplevel\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587/ping\", line 114, in <module>\r\n    exitcode = invoke_module(module, zipped_mod, ZIPLOADER_PARAMS)\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1464681005.08-131997339542587/ping\", line 28, in invoke_module\r\n    p = subprocess.Popen(['PATH=/home/core/bin:$PATH python', module], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)\r\n  File \"/home/core/pypy/lib-python/2.7/subprocess.py\", line 712, in __init__\r\n    errread, errwrite)\r\n  File \"/home/core/pypy/lib-python/2.7/subprocess.py\", line 1333, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```
##### Additional info

I executed ansible with `env ANSIBLE_KEEP_REMOTE_FILES=1 ansible -i inventory etcd-staging-0 -m ping` and did some analysis on the CoreOS side:

```
core@etcd-staging-0 ~/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127 $ /home/core/bin/python ping execute
/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
('Args:', ['PATH=/home/core/bin:$PATH python', '/home/core/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127/debug_dir/ansible_module_ping.py', '/home/core/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127/debug_dir/args'])
('Executable:', None)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "ping", line 215, in <module>
    exitcode = debug(sys.argv[1], zipped_mod, ZIPLOADER_PARAMS)
  File "ping", line 158, in debug
    p = subprocess.Popen(['PATH=/home/core/bin:$PATH python', script_path, args_path], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
  File "/home/core/pypy/lib-python/2.7/subprocess.py", line 712, in __init__
    errread, errwrite)
  File "/home/core/pypy/lib-python/2.7/subprocess.py", line 1333, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

(Additional Args and Executable parameters are output by debug prints I inserted into subprocess.py)

I run a Python session then:

```
> /home/core/bin/python
Python 2.7.8 (f5dcc2477b97, Sep 18 2014, 11:33:30)
[PyPy 2.4.0 with GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import subprocess
>>>> import os
>>>> args = ['PATH=/home/core/bin:$PATH python', '/home/core/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127/debug_dir/ansible_module_ping.py', '/home/core/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127/debug_dir/args']
>>>> subprocess.Popen(args, env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/core/pypy/lib-python/2.7/subprocess.py", line 712, in __init__
    errread, errwrite)
  File "/home/core/pypy/lib-python/2.7/subprocess.py", line 1333, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
>>>> subprocess.Popen(args, env=os.environ, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
('Args:', ['PATH=/home/core/bin/python', '/home/core/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127/debug_dir/ansible_module_ping.py', '/home/core/.ansible/tmp/ansible-tmp-1464679374.5-157723340661127/debug_dir/args'])
('Executable:', None)
<subprocess.Popen object at 0x0000000004371460>
```

When `shell=False` I got same exception, but if it is changed to `shell=True` everything works fine. This is a key to this issue.

**Comment by istaheev** [comment]
Source of the issue has been found, see the diff below which helped:

```
-ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
+ansible_python_interpreter="/home/core/bin/python"
```

**Comment by istaheev** [comment]
(This was changed in the inventory file)

**Comment by dberuben** [comment]
Same issue now its Working for me !

**Comment by cocotton** [comment]
Thanks for the fix

**Comment by jl-montes** [comment]
Had the same issue, glad this was reported and written up nicely, works for me as well.
I have an ubuntu ansible workstation that runs scripts against a cluster of CoreOS machines.

**Comment by mklebrasseur** [comment]
Same issue, this resolved it on my end too.

Thanks!
