### ISSUE TITLE
`ImportError: No module named netrc` in vmware esxi 6.0

### ISSUE THREAD

**Issue by alswl** [ansible/ansible#16082]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/alswl/duitang/workspace/dansible/ansible.cfg
  configured module search path = Default w/o overrides
```

installed by brew
##### CONFIGURATION

```
[defaults]
transport = ssh
sudo_flags=-HE

[ssh_connection]
ssh_args = -o ForwardAgent=yes
pipelining=True
```

```
echo $ANSIBLE_NOCOWS
1
```
##### OS / ENVIRONMENT

Mac 10.11.5 (15F34)
##### SUMMARY

when i connet to Vmware ESXi container, try to run some task, it will show:

```
TASK [vmware_vsphere : ssh key] ************************************************
task path: /Users/alswl/duitang/workspace/dansible/roles/vmware_vsphere/tasks/main.yml:3
<10.1.5.6> ESTABLISH SSH CONNECTION FOR USER: root
<10.1.5.6> SSH: EXEC ssh -C -q -o ForwardAgent=yes -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 10.1.5.6 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_EVlV_C/ansible_module_authorized_key.py", line 482, in <module>
    from ansible.module_utils.urls import *
  File "/tmp/ansible_EVlV_C/ansible_modlib.zip/ansible/module_utils/urls.py", line 84, in <module>
ImportError: No module named netrc
```

If I connect to ther Vmware EXSi server, import netrc, it will fail:

```
[root@localhost:~] python
Python 2.7.9 (default, Dec 21 2015, 01:11:33)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netrc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named netrc
>>> import argparse
>>>
```
##### STEPS TO REPRODUCE

run a authorized_key command.

```

---

- name: ssh key
  authorized_key:
    user=root
    key="{{ item }}"
    path=/etc/ssh/keys-root/authorized_keys
  with_file:
    - roles/common/files/public_keys/jingchao.di.pub

```

##### EXPECTED RESULTS

the command runs successful.
##### ACTUAL RESULTS

```
TASK [vmware_vsphere : ssh key] ************************************************
task path: /Users/alswl/duitang/workspace/dansible/roles/vmware_vsphere/tasks/main.yml:3
<10.1.5.6> ESTABLISH SSH CONNECTION FOR USER: root
<10.1.5.6> SSH: EXEC ssh -C -q -o ForwardAgent=yes -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 10.1.5.6 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_EVlV_C/ansible_module_authorized_key.py", line 482, in <module>
    from ansible.module_utils.urls import *
  File "/tmp/ansible_EVlV_C/ansible_modlib.zip/ansible/module_utils/urls.py", line 84, in <module>
ImportError: No module named netrc
```

**Comment by alswl** [comment]
It seems Vmware ESXi python is a lite version, I copy my local netrc.py to remote server. now it works.

```
scp -P 22 /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/netrc.py root@10.1.5.6:/tmp
```

**Comment by alswl** [comment]
A task to fix:

```
- name: fix netrc
  copy:
    src=roles/common/files/patch/netrc.py
    dest=/lib/python2.7/
```

This `copy` command will works even if there is no netrc module.
