### ISSUE TITLE
list index out of range during fact gather

### ISSUE THREAD

**Issue by antonym** [ansible/ansible#16174]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

On Ansible 2.1, when gathering facts, for a chroot host the facts gather fails with a list index out of range exception.

Issue does not occur on previous 2.0.x versions.
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

Should gather facts correctly.
##### ACTUAL RESULTS

exception

```
[root@box ansible]# sudo -E ansible-playbook -vvvv -i hosts_generator.py wisp-util.yml
Using /mnt/datadisk/jenkins/workspace/squashible-util/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: wisp-util.yml ********************************************************
1 plays in wisp-util.yml

PLAY [chroot] ******************************************************************

TASK [setup] *******************************************************************
<chroot> THIS IS A LOCAL CHROOT DIR
<chroot> EXEC ['/sbin/chroot', u'chroot', '/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465321346.92-86268247124152 `" && echo ansible-tmp-1465321346.92-86268247124152="` echo $HOME/.ansible/tmp/ansible-tmp-1465321346.92-86268247124152 `" ) && sleep 0\'']
<chroot> PUT /tmp/tmpftiGkl TO /root/.ansible/tmp/ansible-tmp-1465321346.92-86268247124152/setup
<chroot> EXEC ['/sbin/chroot', u'chroot', '/bin/sh', '-c', u'dd of=/root/.ansible/tmp/ansible-tmp-1465321346.92-86268247124152/setup bs=65536']
<chroot> EXEC ['/sbin/chroot', u'chroot', '/bin/sh', '-c', u'/bin/sh -c \'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1465321346.92-86268247124152/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1465321346.92-86268247124152/" > /dev/null 2>&1 && sleep 0\'']
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Y_rKjr/ansible_module_setup.py", line 127, in <module>
    main()
  File "/tmp/ansible_Y_rKjr/ansible_module_setup.py", line 119, in main
    data = get_all_facts(module)
  File "/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py", line 3177, in get_all_facts
  File "/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py", line 3123, in ansible_facts
  File "/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py", line 919, in populate
  File "/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py", line 107, in wrapper
  File "/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py", line 1142, in get_mount_facts
IndexError: list index out of range

fatal: [chroot]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Y_rKjr/ansible_module_setup.py\", line 127, in <module>\n    main()\n  File \"/tmp/ansible_Y_rKjr/ansible_module_setup.py\", line 119, in main\n    data = get_all_facts(module)\n  File \"/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3177, in get_all_facts\n  File \"/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3123, in ansible_facts\n  File \"/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 919, in populate\n  File \"/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 107, in wrapper\n  File \"/tmp/ansible_Y_rKjr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 1142, in get_mount_facts\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by bcoca** [comment]
can you show the contents of your /etc/mtab on the target machine?

**Comment by antonym** [comment]
@bcoca 

```
[root@dfw ~]# cat /etc/mtab
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=7678396k,nr_inodes=1919599,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/xvda1 / ext4 rw,seclabel,noatime,nobarrier,errors=remount-ro,data=ordered 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=34,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
/dev/xvde1 /mnt/datadisk ext4 rw,seclabel,noatime,data=ordered 0 0
none /proc/xen xenfs rw,relatime 0 0
tmpfs /run/user/1184 tmpfs rw,seclabel,nosuid,nodev,relatime,size=1539568k,mode=700,uid=1184,gid=513 0 0
```

**Comment by antonym** [comment]
Can confirm that the patch resolves the exception.  Thanks!

**Comment by arikon** [comment]
When it will be released?

**Comment by joaocc** [comment]
@arikon: there is a simple workaround for this:
- set this var before calling ansible: `export ANSIBLE_GATHER_SUBSET=!hardware``
- add this to ansible.cfg: `gather_subset=!hardware`
