### ISSUE TITLE
get_url module fails to download url: AttributeError: 'function' object has no attribute 'urlsplit'

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible#16191]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 5f1bbb4fcd) last updated 2016/06/08 14:05:44 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a8072f9ef0) last updated 2016/06/08 13:35:54 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 6ee1cfc5cf) last updated 2016/06/08 13:35:54 (GMT -400)
  config file = /Users/jladd/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[ssh_connection]
control_path = %(directory)s/%%h-%%r
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In the `stable-2.1` and `stable-1.9` versions of ansible, I am able to download `http://www.google.com` using `ansible -vvv localhost -i inventory -m get_url -a 'url=http://www.google.com dest=/tmp'`. On the devel branch, though, I'm seeing the following error: 

`AttributeError: 'function' object has no attribute 'urlsplit'`
##### STEPS TO REPRODUCE
1. Download the Ansible devel repo. Run `git submodule update --init --recursive` in the repo, then `source hacking/env-setup`.
2. Create new file, `inventory`, with contents `localhost ansible_connection=local`.
3. Run `ansible -vvvv localhost -i inventory -m get_url -a 'url=http://www.google.com dest=/tmp'`
##### EXPECTED RESULTS

On ansible 2.1.0.0, command is successful ([results](https://gist.github.com/jladdjr/23c535228a61150303ef5b6cde6b0a72)). Confirmed that google homepage appears in /tmp/index.html.

On ansible 1.9.6, command is successful ([results](https://gist.github.com/jladdjr/7e3d00013e33fd5823e7692f516bbbce)). Confirmed that google homepage appears in /tmp/index.html.
##### ACTUAL RESULTS

On `devel` branch, seeing:

```
ansible -vvvv localhost -i inventory -m get_url -a 'url=http://www.google.com dest=/tmp'
Using /Users/jladd/.ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
Using module file /Users/jladd/ansible/devel/lib/ansible/modules/core/network/basics/get_url.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jladd
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465409997.54-132115840425562 `" && echo ansible-tmp-1465409997.54-132115840425562="` echo $HOME/.ansible/tmp/ansible-tmp-1465409997.54-132115840425562 `" ) && sleep 0'
<localhost> PUT /var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/tmpz6D7Df TO /Users/jladd/.ansible/tmp/ansible-tmp-1465409997.54-132115840425562/get_url.py
<localhost> EXEC /bin/sh -c 'chmod -R u+x /Users/jladd/.ansible/tmp/ansible-tmp-1465409997.54-132115840425562/ && sleep 0'
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/jladd/.ansible/tmp/ansible-tmp-1465409997.54-132115840425562/get_url.py; rm -rf "/Users/jladd/.ansible/tmp/ansible-tmp-1465409997.54-132115840425562/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/ansible_u0u8lm/ansible_module_get_url.py", line 439, in <module>
    main()
  File "/var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/ansible_u0u8lm/ansible_module_get_url.py", line 359, in main
    filename = url_filename(info['url'])
  File "/var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/ansible_u0u8lm/ansible_module_get_url.py", line 192, in url_filename
    fn = os.path.basename(urlparse.urlsplit(url)[2])
AttributeError: 'function' object has no attribute 'urlsplit'

localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "get_url"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/ansible_u0u8lm/ansible_module_get_url.py\", line 439, in <module>\n    main()\n  File \"/var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/ansible_u0u8lm/ansible_module_get_url.py\", line 359, in main\n    filename = url_filename(info['url'])\n  File \"/var/folders/9f/lfcc9zd96fngv4bpptdg86700000gn/T/ansible_u0u8lm/ansible_module_get_url.py\", line 192, in url_filename\n    fn = os.path.basename(urlparse.urlsplit(url)[2])\nAttributeError: 'function' object has no attribute 'urlsplit'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

**Comment by jladdjr** [comment]
This issue does have an impact on Tower testing. Our Tower installs fail on all platforms (ubuntu 12/14, centos 6/7, rhel 6/7, oracle linux 6/7) at the point where we try to download a tarball containing the tower installer. Sample failure [here](http://jenkins.testing.ansible.com/me/my-views/view/Dashboard/job/Test_Tower_Install/ANSIBLE_NIGHTLY_BRANCH=devel,PLATFORM=rhel-7.2-x86_64/4608/console).

**Comment by mattclay** [comment]
When this is fixed the test_get_url integration test should be updated to cover this use case.

**Comment by jctanner** [comment]
This is the workaround ...

```
diff --git a/network/basics/get_url.py b/network/basics/get_url.py
index 3d180f6..69abec5 100644
--- a/network/basics/get_url.py
+++ b/network/basics/get_url.py
@@ -183,13 +183,13 @@ EXAMPLES='''
   get_url: url="file:///tmp/afile.txt" dest=/tmp/afilecopy.txt
 '''

-import urlparse
+import urlparse as _urlparse

 # ==============================================================
 # url handling

 def url_filename(url):
-    fn = os.path.basename(urlparse.urlsplit(url)[2])
+    fn = os.path.basename(_urlparse.urlsplit(url)[2])
     if fn == '':
         return 'index.html'
     return fn
```

Trying to understand why from ansible.module_utils.six.moves.urllib.parse import urlparse, urlunparse from urls.py is now overwriting the namespace for this code.

**Comment by jctanner** [comment]
Second try:

```
diff --git a/lib/ansible/module_utils/six.py b/lib/ansible/module_utils/six.py
index 85898ec..09bde63 100644
--- a/lib/ansible/module_utils/six.py
+++ b/lib/ansible/module_utils/six.py
@@ -186,6 +186,7 @@ _moved_attributes = [
     MovedModule("tkinter_tksimpledialog", "tkSimpleDialog",
                 "tkinter.simpledialog"),
     MovedModule("urllib_parse", __name__ + ".moves.urllib_parse", "urllib.parse"),
+    MovedModule("urllib_split", __name__ + ".moves.urllib_split", "urllib.split"),
     MovedModule("urllib_error", __name__ + ".moves.urllib_error", "urllib.error"),
     MovedModule("urllib", __name__ + ".moves.urllib", __name__ + ".moves.urllib"),
     MovedModule("urllib_robotparser", "robotparser", "urllib.robotparser"),
```

```
diff --git a/network/basics/get_url.py b/network/basics/get_url.py
index 3d180f6..83e6b13 100644
--- a/network/basics/get_url.py
+++ b/network/basics/get_url.py
@@ -183,13 +183,13 @@ EXAMPLES='''
   get_url: url="file:///tmp/afile.txt" dest=/tmp/afilecopy.txt
 '''

-import urlparse
+from ansible.module_utils.six.moves.urllib.parse import urlsplit

 # ==============================================================
 # url handling

 def url_filename(url):
-    fn = os.path.basename(urlparse.urlsplit(url)[2])
+    fn = os.path.basename(urlsplit(url)[2])
     if fn == '':
         return 'index.html'
     return fn
```

**Comment by thapakazi** [comment]
@jctanner thanks :bow: mate

**Comment by jladdjr** [comment]
@jctanner - ditto, danke!

**Comment by ttbigc** [comment]
After the import change I am now getting the following error when trying to use get_url:
Could not find imported module support code for get_url.  Looked for either urlsplit or parse

I do have six installed. Any suggestions on how I should troubleshoot or what additional information needs to be provided to determine if this issue needs to be re-opened?

**Comment by mattclay** [comment]
@ttbigc Since that sounds like a new (but possibly related) issue, go ahead and open a new issue and reference this one.

**Comment by xuchen81** [comment]
+1. it still happens on the latest devel branch. 2.3
I am running vagrant up on my Mac OS:
Vagrant 1.9.1
Mac OS 10.11.6

**Comment by mattclay** [comment]
@xuchen81 I'm not able to reproduce the issue using devel on Mac OS 10.11. Also, the integration test that was implemented to detect this particular issue is passing. Can you please open a new issue with more details on the error you're seeing?
