### ISSUE TITLE
Nxos_config fatal error when deploying swtich banner statement

### ISSUE THREAD

**Issue by ebmarquez** [ansible/ansible#16499]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
timeout = 60
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
```
##### OS / ENVIRONMENT

Ansible server: 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Cisco Nexus  system:    version 6.0(2)U6(4)
##### STEPS TO REPRODUCE

```
ansible-playbook test.yml -vvvv --limit 3172hl-3-1a

---
# Setup playbook to deploy a banner
- name: Setup Common Banner
  hosts: tora
  remote_user: admin
  gather_facts: no
  connection: local
  roles:
    - banner


---
#- name: debug banner
#  debug: msg=" {% include 'templates/Banner.txt' %} "

- name: Banner
  register: output
  nxos_config:
    provider: "{{ cli }}"
    lines:
      - "banner motd #"
      - NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE
      -
      - Unauthorized access and/or use prohibited.
      - All access and/or use subject to monitoring.
      -
      - This switch has been deployed using automation.
      - Do not edit the switch configs by hand -- YOUR CHANGES WILL BE OVERWRITTEN
      -
      - NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE   NOTICE
      - "#"
- name: Debug nxos_config banner
  debug: var=output
```

##### EXPECTED RESULTS

Apply a valid config.
##### ACTUAL RESULTS

fatal error

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [Setup Common Banner] *****************************************************

TASK [banner : Banner] *********************************************************
task path: /home/emarq/Solutions.Network.Automation/MAS/Ansible/cisco/nexus/roles/banner/tasks/main.yml:5
<2001:4898:5808:ff35::1> ESTABLISH LOCAL CONNECTION FOR USER: emarq
<2001:4898:5808:ff35::1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467213418.34-137149513674700 `" && echo ansible-tmp-1467213418.34-137149513674700="` echo $HOME/.ansible/tmp/ansible-tmp-1467213418.34-137149513674700 `" ) && sleep 0'
<2001:4898:5808:ff35::1> PUT /tmp/tmpaKRttx TO /home/emarq/.ansible/tmp/ansible-tmp-1467213418.34-137149513674700/nxos_config
<2001:4898:5808:ff35::1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/emarq/.ansible/tmp/ansible-tmp-1467213418.34-137149513674700/nxos_config; rm -rf "/home/emarq/.ansible/tmp/ansible-tmp-1467213418.34-137149513674700/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_L_MH98/ansible_module_nxos_config.py", line 229, in <module>
    main()
  File "/tmp/ansible_L_MH98/ansible_module_nxos_config.py", line 198, in main
    candidate.add(lines, parents=parents)
  File "/tmp/ansible_L_MH98/ansible_modlib.zip/ansible/module_utils/netcfg.py", line 269, in add
  File "/tmp/ansible_L_MH98/ansible_modlib.zip/ansible/module_utils/netcfg.py", line 243, in _build_children
AttributeError: 'NoneType' object has no attribute 'rjust'

fatal: [3172hl-3-1a]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_config"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_L_MH98/ansible_module_nxos_config.py\", line 229, in <module>\n    main()\n  File \"/tmp/ansible_L_MH98/ansible_module_nxos_config.py\", line 198, in main\n    candidate.add(lines, parents=parents)\n  File \"/tmp/ansible_L_MH98/ansible_modlib.zip/ansible/module_utils/netcfg.py\", line 269, in add\n  File \"/tmp/ansible_L_MH98/ansible_modlib.zip/ansible/module_utils/netcfg.py\", line 243, in _build_children\nAttributeError: 'NoneType' object has no attribute 'rjust'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
3172hl-3-1a    : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by dgjustice** [comment]
@ebmarquez I know this is an old, closed issue, but it shows up high on the Google search list.  I had a royal pain with this as well.  Here is my workaround: build a template with your banner using the regular template module.  You can then copy it to your remote host using scp (for example, nxos_file_copy).  Finally, you can run a command (nxos_command) to copy the text file to the running-config where it will be merged.  It's a long way around a simple problem, but works for me.  I hope this helps!
