### ISSUE TITLE
ansible_connection=lxd fails when connecting to a gentoo container due to default python 3.4 (even though 2.7 is installed as well)

### ISSUE THREAD

**Issue by killua-eu** [ansible/ansible#16737]
How to reproduce:

```
lxc launch images:gentoo/current/amd64 gentootest
lxc exec gentootest -- emerge -u dev-lang/python dev-python/simplejson
echo "[lxd]" >> /etc/ansible/hosts
echo "gentootest ansible_connection=lxd" >> /etc/ansible/hosts
echo "

---
- hosts: gentootest
  tasks:
    - debug: msg=ipv4_address={{ ansible_default_ipv4.address }}
" > ./gentootest.yaml
ansible-playbook -vvv ./gentootest.yaml

```

fails like this:

```
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: gentootest.yaml ******************************************************
1 plays in ./gentootest.yaml

PLAY [gentootest] **************************************************************

TASK [setup] *******************************************************************
<gentootest> ESTABLISH LXD CONNECTION FOR USER: root
<gentootest> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1468692434.99-109064323899823 `" && echo ansible-tmp-1468692434.99-109064323899823="` echo $HOME/.ansible/tmp/ansible-tmp-1468692434.99-109064323899823 `" ) && sleep 0'
<gentootest> PUT /tmp/tmpKWDB6v TO /root/.ansible/tmp/ansible-tmp-1468692434.99-109064323899823/setup
<gentootest> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1468692434.99-109064323899823/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1468692434.99-109064323899823/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_cfg3wwsc/ansible_module_setup.py", line 127, in <module>
    main()
  File "/tmp/ansible_cfg3wwsc/ansible_module_setup.py", line 117, in main
    supports_check_mode = True,
  File "/tmp/ansible_cfg3wwsc/ansible_modlib.zip/ansible/module_utils/basic.py", line 679, in __init__
  File "/tmp/ansible_cfg3wwsc/ansible_modlib.zip/ansible/module_utils/basic.py", line 1615, in _log_invocation
  File "/tmp/ansible_cfg3wwsc/ansible_modlib.zip/ansible/module_utils/basic.py", line 475, in heuristic_log_sanitize
TypeError: 'str' does not support the buffer interface

fatal: [gentootest]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_cfg3wwsc/ansible_module_setup.py\", line 127, in <module>\n    main()\n  File \"/tmp/ansible_cfg3wwsc/ansible_module_setup.py\", line 117, in main\n    supports_check_mode = True,\n  File \"/tmp/ansible_cfg3wwsc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 679, in __init__\n  File \"/tmp/ansible_cfg3wwsc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1615, in _log_invocation\n  File \"/tmp/ansible_cfg3wwsc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 475, in heuristic_log_sanitize\nTypeError: 'str' does not support the buffer interface\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @./gentootest.retry

PLAY RECAP *********************************************************************
gentootest                 : ok=0    changed=0    unreachable=0    failed=1   

```

... replace gentoo with an ubuntu image by modifying the `lxc exec gentootest -- emerge -u dev-lang/python dev-python/simplejson` line and everything will work as expceted.

This is due to the fact, that gentoo uses by default python 3.4, as is obvious from

```
lxc exec gentootest -- eselect python list
Available Python interpreters:
  [1]   python2.7
  [2]   python3.4 *
```

Packages on gentoo can use any of the installed interpreter versions, but unless a specified, the default (3.4) is used, which ansible fails. **I didnt test this with other connectors other than lxd, but I assume a similar result.** Switching to 2.7 by running

```
lxc exec gentootest -- eselect python set 1
```

and rerunning the playbook works. So basically, asnible should force usage of /usr/bin/python2.7 instead of /usr/bin/python on gentoo.

**Comment by jctanner** [comment]
@killua-eu does setting ansible_python_interpreter make any difference?

**Comment by killua-eu** [comment]
Yep it does, sorry I didn't know this option existed! Is it possible to set ansible_python_interpreter=/usr/bin/python2.7 whenever a Gentoo node is detected? Or at least document this somewhere, so that others using Ansible with Gentoo won't be bitten by this?

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The requirements are clear, python2 is currently needed on the target to use anything other than the `raw` module.  http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements

And ansible_python_interpreter is already documented:
http://docs.ansible.com/ansible/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
