### ISSUE TITLE
`ansible -m include` fails with Unexpected Exception. Error should probably just be "nope".

### ISSUE THREAD

**Issue by sourcejedi** [ansible/ansible#16821]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Fedora 23
##### SUMMARY

`ansible -m include` fails with Unexpected Exception.
##### STEPS TO REPRODUCE

```
ansible -vvv -c local -i "localhost,"  all -m include -a /dev/null
```
##### EXPECTED RESULTS

Obviously I was _trying_ to see if it would work. Failing that, I wouldn't expect an "Unexpected Exception"; I'd expect some error message. I get the impression the error is roughly "nope, this is not a thing, don't to try to do it".
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: 'Task' object has no attribute 'static'
the full traceback was:

Traceback (most recent call last):
  File "bin/ansible", line 97, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 193, in run
    result = self._tqm.run(play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 256, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 284, in run
    variable_manager=self._variable_manager
  File "/usr/lib/python2.7/site-packages/ansible/playbook/included_file.py", line 90, in process_include_results
    if original_task.static:
AttributeError: 'Task' object has no attribute 'static'
```

Google didn't find any results for this error.

**Comment by bcoca** [comment]
fixed via ff34f5548ddde266742bee2765f32af2828c5ee7
