### ISSUE TITLE
ansible 2.1.0.0 missing to install required setuptools and fails later due to this

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#16831]
On a clean machine like Ubuntu 15.04, after you install ansible using `pip2 install ansible` you will get a version of ansible that fails to run because it needs a newer version of setuptools.

```
ansible --version
ERROR! Unexpected Exception: (setuptools 5.5.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=11.3'))
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 81, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 33, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 67, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
VersionConflict: (setuptools 5.5.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=11.3'))
```

Adding `setuptools>=11.3` in the requirements should fix this issue.

**Comment by abadger** [comment]
Thanks for reporting!  This isn't a requirement from Ansible but a requirement from an optional dependency, cryptography.  Due to this, we've taken steps in the latest Ansible-2.1.1rc4 code to not throw errors if cryptography is broken.  You should be able to try the latest 2.1.1 release candidate and have a fixed version.

**Comment by ssbarnea** [comment]
@abadger I would personally not mind if Ansible would upgrade setuptools, or having cryptography fix this directly. If you can point me to a bug on it I will be more than happy to vote it.

**Comment by abadger** [comment]
We can't specify a newer dep because we also run on currently supported distros via system packages (which have older setuptools and presumably older cryptography which doesn't have the newer setuptools dep.).  I think that the problem is in pip since pip isn't taking the versioned dep from the cryptography package and applying it: https://github.com/pypa/pip/issues/988

**Comment by ssbarnea** [comment]
I have to defent pip in this case, it's not really pip fault that some distros, like ubuntu, are still installing 5+ years old pip versions and refusing to update their packages. 

Among Python users it is kinda known that you have to uninstall Ubuntu pip version and install a current version using `get-pip.py`, or you are kinda doomed.
