### ISSUE TITLE
[regression] Exception in nxos_nxapi

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#16934]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.1.0
```
##### CONFIGURATION

inventory = ./hosts
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
fact_caching = redis
fact_caching_timeout = 86400
##### OS / ENVIRONMENT
- **Local host**: Ubuntu 16.04 4.4.0
- **Target nodes**: NX-OSv 7.3(0)D1(1) (last release available in Cisco VIRL)
##### SUMMARY

Running nxos_nxapi triggers an exception, whereas I can manually login into the target node with SSH.
##### STEPS TO REPRODUCE

**Inventory ./hosts**:

```
[nx_osv]
192.168.137.244 ansible_host=NX_OSv_1 mgt_interface=mgmt0
192.168.137.234 ansible_host=NX_OSv_2 mgt_interface=mgmt0
```

Structure passed as "**provider**": connections.ssh
Defined in group_vars/nx_osv/connections.yml

```
connections:
        compute: local
...
        ssh:
          transport: cli 
          host: "{{ inventory_hostname }}"
          # ansible_port
          port: 22
          # ansible_user
          username: admin
          # ansible_ssh_pass
          password: Cisco2016$
          authorize: yes
          # enable_secret_password
          auth_pass: Cisco2016$
          # private_key_file
          ssh_keyfile: "~/.ssh/id_rsa"
          version: 2
          timeout: 10
ansible_connection: "{{ connections.compute }}" 
```

Structures http & https
Defined in group_vars/nx_osv/http.yml

```
http:
        # enable_http can be true / false
        service: true
        port: 80
https:
        # enable_https can be true / false
        service: false
        port: 10443
```

**Role**: nxos_init

```
- include_vars: "{{ role_path }}/../../group_vars/{{ hostvars[inventory_hostname].group_names[0] }}/connections.yml"
- include_vars: "{{ role_path }}/../../group_vars/{{ hostvars[inventory_hostname].group_names[0] }}/http.yml"

- name: Enable NX-API
  nxos_nxapi: 
      state=started 
      sandbox=false
      http={{ http.service }}
      http_port={{ http.port }}
      https={{ https.service }}
      https_port={{ https.port }}
      provider={{ connections.ssh }}
  register: return
...
```

**Playbook**: init.yml

```
- name: Initialize all NX-OS features & save facts
  hosts:
    - nx_os
    - nx_osv
  roles:
    - nxos_init
```
##### EXPECTED RESULTS

Successful nxos_nxapi
##### ACTUAL RESULTS

```
TASK [nxos_init : Enable NX-API] ***********************************************
task path: /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles/nxos_init/tasks/main.yml:29
<NX_OSv_1> ESTABLISH LOCAL CONNECTION FOR USER: root
<NX_OSv_1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470230351.99-196486228076050 `" && echo ansible-tmp-1470230351.99-196486228076050="` echo $HOME/.ansible/tmp/ansible-tmp-1470230351.99-196486228076050 `" ) && sleep 0'
<NX_OSv_2> ESTABLISH LOCAL CONNECTION FOR USER: root
<NX_OSv_2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470230351.99-268650786865216 `" && echo ansible-tmp-1470230351.99-268650786865216="` echo $HOME/.ansible/tmp/ansible-tmp-1470230351.99-268650786865216 `" ) && sleep 0'
<NX_OSv_2> PUT /tmp/tmpu2bixy TO /root/.ansible/tmp/ansible-tmp-1470230351.99-268650786865216/nxos_nxapi
<NX_OSv_1> PUT /tmp/tmpyyn3Hd TO /root/.ansible/tmp/ansible-tmp-1470230351.99-196486228076050/nxos_nxapi
<NX_OSv_2> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1470230351.99-268650786865216/nxos_nxapi; rm -rf "/root/.ansible/tmp/ansible-tmp-1470230351.99-268650786865216/" > /dev/null 2>&1 && sleep 0'
<NX_OSv_1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1470230351.99-196486228076050/nxos_nxapi; rm -rf "/root/.ansible/tmp/ansible-tmp-1470230351.99-196486228076050/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_4CyDsX/ansible_module_nxos_nxapi.py", line 257, in <module>
    main()
  File "/tmp/ansible_4CyDsX/ansible_module_nxos_nxapi.py", line 248, in main
    result = config_server(module)
  File "/tmp/ansible_4CyDsX/ansible_module_nxos_nxapi.py", line 156, in config_server
    nxapi_state = get_nxapi_state(module)
  File "/tmp/ansible_4CyDsX/ansible_module_nxos_nxapi.py", line 148, in get_nxapi_state
    features = module.execute(['show feature | grep nxapi'])[0]
  File "/tmp/ansible_4CyDsX/ansible_modlib.zip/ansible/module_utils/nxos.py", line 253, in execute
  File "/tmp/ansible_4CyDsX/ansible_modlib.zip/ansible/module_utils/nxos.py", line 230, in connect
  File "/tmp/ansible_4CyDsX/ansible_modlib.zip/ansible/module_utils/nxos.py", line 182, in connect
  File "/tmp/ansible_4CyDsX/ansible_modlib.zip/ansible/module_utils/shell.py", line 120, in open
  File "/tmp/ansible_4CyDsX/ansible_modlib.zip/ansible/module_utils/shell.py", line 129, in receive
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 615, in recv
    raise socket.timeout()
socket.timeout
...
```
##### Troubleshooting
- Downgrading paramiko from 2.0.1 to 1.16 does not change anything
- When trying to manually ssh into the target:

```
# ssh admin@192.168.137.234
User Access Verification
Cisco NX-OS Software
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.
NX-OSv software ("NX-OSv Software") and related documentation,
...
NX_OSv_2# exit
Connection to 192.168.137.234 closed.
```

**Comment by jean-christophe-manciot** [comment]
Transferred to [**ansible-modules-core**](https://github.com/ansible/ansible-modules-core/issues/4311).
