### ISSUE TITLE
broken plugins cause UnboundLocalError: local variable 'obj' referenced before assignment

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#16951]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.2 devel
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

PluginLoader.all() creates a variable named "obj" in try/except, raises a warning if failed and then attempts to use the variable later even though it may not exist.
##### STEPS TO REPRODUCE

Create a bad plugin file in "filter_plugins" and run a playbook with a debug: var=

```
mkdir filter_plugins
touch filter_plugins/foobar.py
```
##### EXPECTED RESULTS

No traceback, just a warning.
##### ACTUAL RESULTS

```
task path: .../tasks/main.yml:57
[WARNING]: Skipping plugin (....library/<BROKEMODULE>.py) as it seems to be invalid: 'module' object has no attribute 'FilterModule'

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
   res = self._execute()
 File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 401, in _execute
   self._task.post_validate(templar=templar)
 File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 246, in post_validate
   super(Task, self).post_validate(templar)
 File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 317, in post_validate
   value = templar.template(getattr(self, name))
 File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 358, in template
   d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
 File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 330, in template
   result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
 File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 467, in _do_template
   myenv.filters.update(self._get_filters())
 File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 186, in _get_filters
   plugins = [x for x in self._filter_loader.all()]
 File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 388, in all
   obj = obj(*args, **kwargs)
UnboundLocalError: local variable 'obj' referenced before assignment
```

**Comment by jctanner** [comment]
Fixed by https://github.com/ansible/ansible/commit/b0786a1845366a5fb81a40f7a8fd42d556556f7a
