### ISSUE TITLE
ovirt module (start Vm) used by Ansible 2.2.0 and Python 2.7 seems broken

### ISSUE THREAD

**Issue by toxeek** [ansible/ansible#16969]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report

```
Bug report
```
##### ANSIBLE VERSION

```
2.2.0
```
##### OS / ENVIRONMENT

```
CentOS 7
```
##### STEPS TO REPRODUCE

```
- name: starting vm "{{ vm_name }}"
  ovirt:
    instance_name: "{{ vm_name }}"
    state: started
    user: "{{ ovirt_user }}"
    password: "{{ ovirt_password }}"
    url: "{{ ovirt_url }}"
...
```

##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_l42zpO/ansible_module_ovirt.py", line 520, in <module>
    main()
  File "/tmp/ansible_l42zpO/ansible_module_ovirt.py", line 491, in main
    vm_start(c, vmname, hostname, ip, netmask, gateway, domain, dns, rootpw, key)
  File "/tmp/ansible_l42zpO/ansible_module_ovirt.py", line 342, in vm_start
    nics = params.GuestNicsConfiguration(nic_configuration=[nic])
UnboundLocalError: local variable 'nic' referenced before assignment

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ovirt"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_l42zpO/ansible_module_ovirt.py\", line 520, in <module>\n    main()\n  File \"/tmp/ansible_l42zpO/ansible_module_ovirt.py\", line 491, in main\n    vm_start(c, vmname, hostname, ip, netmask, gateway, domain, dns, rootpw, key)\n  File \"/tmp/ansible_l42zpO/ansible_module_ovirt.py\", line 342, in vm_start\n    nics = params.GuestNicsConfiguration(nic_configuration=[nic])\nUnboundLocalError: local variable 'nic' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}

```

**Comment by toxeek** [comment]
My temporaty solution due to the error being 
UnboundLocalError: local variable 'nic' referenced before assignment

# vim /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/misc/ovirt.py

(GOTO: line 331)

``` python
def vm_start(conn, vmname, hostname=None, ip=None, netmask=None, gateway=None,
             domain=None, dns=None, rootpw=None, key=None):
    vm = conn.vms.get(name=vmname)
    use_cloud_init = False
    nics = None
    if hostname or ip or netmask or gateway or domain or dns or rootpw or key:
        use_cloud_init = True
    if ip and netmask and gateway:
        ipinfo = params.IP(address=ip, netmask=netmask, gateway=gateway)
        #nic = params.GuestNicConfiguration(name='eth0', boot_protocol='STATIC', ip=ipinfo, on_boot=True)
        nics = params.Nics()
    ipinfo = params.IP(address=ip, netmask=netmask, gateway=gateway)
    nic = params.GuestNicConfiguration(name='eth0', boot_protocol='STATIC', ip=ipinfo, on_boot=True)
    nics = params.GuestNicsConfiguration(nic_configuration=[nic])
    initialization=params.Initialization(regenerate_ssh_keys=True, host_name=hostname, domain=domain, user_name='root',
                                         root_password=rootpw, nic_configurations=nics, dns_servers=dns,
                                         authorized_ssh_keys=key)
    action = params.Action(use_cloud_init=use_cloud_init, vm=params.VM(initialization=initialization))
    vm.start(action=action)
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
