### ISSUE TITLE
ziploader lock failure

### ISSUE THREAD

**Issue by ryanlovett** [ansible/ansible#16982]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

executor/module_common.py
ziploader
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I'm using the ansible ppa:

```
 *** 2.1.1.0-1ppa~trusty 0
        500 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main amd64 Packages
```
##### CONFIGURATION

```
# egrep -v '^#|^$' /etc/ansible/ansible.cfg
[defaults]
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
```
##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```
##### SUMMARY

Possibly related to this closed bug:
https://github.com/ansible/ansible-modules-core/issues/3504

This error happens every time I run ansible-playbook.
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  tasks:
  - name: do nothing
    command: /bin/true
```

The command was `ansible-playbook -vvvv /var/tmp/ansible/test.yml`.

##### EXPECTED RESULTS

No error.
##### ACTUAL RESULTS

```
# ansible-playbook -vvvv /var/tmp/ansible/test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in /var/tmp/ansible/test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 583, in _execute_module
    (module_style, shebang, module_data) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 149, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 733, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 576, in _find_snippet_imports
    with lock:
AttributeError: __exit__

fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/var/tmp/ansible/test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1


```

**Comment by alikins** [comment]
Would it be possible to retry this with the 'stable-2.1' or 'devel' branch from git? There have been some ziploader and module building changes in both branches that may be related.

**Comment by ryanlovett** [comment]
I'll try stable-2.1 out-of-band and report back.

**Comment by abadger** [comment]
@ryanlovett, Is this still happening with stable-2.1 or devel?

needs_info

**Comment by ryanlovett** [comment]
This is still happening with ansible from the official ansible PPA. However, I created a container running the same OS and using ansible from the same PPA and wasn't able to reproduce from inside.

```
root@818523ed16d2:~# ansible-playbook -vvvv /root/test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in /root/test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474497788.27-114845066091406 `" && echo ansible-tmp-1474497788.27-114845066091406="` echo $HOME/.ansible/tmp/ansible-tmp-1474497788.27-114845066091406 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpHhWzte TO /root/.ansible/tmp/ansible-tmp-1474497788.27-114845066091406/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1474497788.27-114845066091406/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1474497788.27-114845066091406/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [do nothing] **************************************************************
task path: /root/test.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474497790.32-55274296327351 `" && echo ansible-tmp-1474497790.32-55274296327351="` echo $HOME/.ansible/tmp/ansible-tmp-1474497790.32-55274296327351 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpPYCLyz TO /root/.ansible/tmp/ansible-tmp-1474497790.32-55274296327351/command
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1474497790.32-55274296327351/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1474497790.32-55274296327351/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.068113", "end": "2016-09-21 22:43:10.501841", "invocation": {"module_args": {"_raw_params": "/bin/true", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-09-21 22:43:10.433728", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0

```

So, notabug. I'm still wondering what is causing the behavior however.

**Comment by abadger** [comment]
@ryanlovett Very strange.  If you ever manage to figure out enough information that we can reproduce, feel free to ping us about whether we can anticipate that case in our code.

**Comment by ryanlovett** [comment]
@abadger We found out what the problem was. An old version of python's multiprocessing library, https://code.google.com/archive/p/python-multiprocessing/, was masking the distribution's newer version. I'm guessing nobody else will run into this. :)
