### ISSUE TITLE
 ansible does not work after installation

### ISSUE THREAD

**Issue by netodevel** [ansible/ansible#17133]
```
sudo     apt-get install    software-properties-common
sudo apt-add-repository ppa:ansible/ansible             
sudo apt-get update
sudo apt-get install    ansible
```

i'm using elementary OS and Python 2.7.4

**Error** 

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 44, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/dist-packages/ansible/constants.py", line 152, in <module>
    DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, 'local_tmp',        'ANSIBLE_LOCAL_TEMP',      '$HOME/.ansible/tmp', istmppath=True)
  File "/usr/lib/python2.7/dist-packages/ansible/constants.py", line 78, in get_config
    os.makedirs(value, 0o700)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/josevieira/.ansible/tmp'

```

**Comment by netodevel** [comment]
**resolved** 

`sudo chown -R YOUR_USERNAME /home/YOUR_USERNAME/.ansible`
