### ISSUE TITLE
Ansible  2.2 devel parses `default(int)` wrong

### ISSUE THREAD

**Issue by wildefires** [ansible/ansible#17185]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel a4785c2691) last updated 2016/08/22 11:44:30 (GMT -400)                                       
  lib/ansible/modules/core: (detached HEAD 24db4de245) last updated 2016/08/04 10:46:55 (GMT -400)                 
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/08/04 10:46:55 (GMT -400)               
  config file = /home/R1/mitchell.usher/.ansible.cfg                                                              
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

Host is CentOS 7, but I don't think it's a centos issue
##### SUMMARY

Ansible no longer parses `default(int)` properly
##### STEPS TO REPRODUCE

I'm attempting to run a playbook that uses a `|default(10)` for a variable. I updated this morning and it does not work as expected

```
 ---
 - name: Install ruby 2.x
   hosts: "{{ hosts }}"
   become: yes
   become_user: root
   serial: "{{ serial | default(10) }}" #This is the problem line
   gather_facts: False
   tags:
     - install
   vars_files:
     - config.yml
... tasks below, never gets to tasks
```

##### ACTUAL RESULTS

```
(ansibleenv) R1+mitchell.usher@server[~/ansible/CatalystConfig/tasks/install-ruby-2]: ansible-playbook inst
all.yml -i 'localhost,' -e 'hosts=all ruby_version=2.1.3 force_install=yes' -kK -vvv                                
Using /home/R1/mitchell.usher/.ansible.cfg as config file                                                           
SSH password:                                                                                                       
SUDO password[defaults to SSH password]:                                                                            
statically included: /home/R1/mitchell.usher/ansible/CatalystConfig/tasks/install-ruby-2/install-ruby.yml           

PLAYBOOK: install.yml **********************************************************                                    
1 plays in install.yml                                                                                              
ERROR! Unexpected Exception: invalid literal for int() with base 10: '{{ serial | default(10) }}'                   
the full traceback was:                                                                                            

Traceback (most recent call last):                                                                                 
  File "/home/R1/mitchell.usher/ansible/ansible/bin/ansible-playbook", line 97, in <module>                        
    exit_code = cli.run()                                                                                          
  File "/home/R1/mitchell.usher/ansible/ansible/lib/ansible/cli/playbook.py", line 154, in run                     
    results = pbex.run()                                                                                           
  File "/home/R1/mitchell.usher/ansible/ansible/lib/ansible/executor/playbook_executor.py", line 147, in run       
    result = self._tqm.run(play=play)                                                                              
  File "/home/R1/mitchell.usher/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 233, in run      
    max_serial = max([pct_to_int(x, num_hosts) for x in serial_items])                                             
  File "/home/R1/mitchell.usher/ansible/ansible/lib/ansible/utils/helpers.py", line 33, in pct_to_int              
    return int(value)                                                                                              
ValueError: invalid literal for int() with base 10: '{{ serial | default(10) }}'  
```

**Comment by wildefires** [comment]
This worked previously with (and I've reverted to) 93c5ec42cf

**Comment by abadger** [comment]
This is happening due to this commit: 159aa26b36a6455ebc38d527c294c60899892c04  which changed the value of serial to a list to implement a new feature.
\cc @jimi-c to take a look at whether the feature can be reconciled with this bug.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
