### ISSUE TITLE
until behaviour changed and partly broken

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#17256]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

until
##### ANSIBLE VERSION

```
2.1.1.0
```
##### SUMMARY

Pause module stopped working with `until`.
##### STEPS TO REPRODUCE

```
- pause: prompt="[y/n]"
  register: test
  until: test.user_input in ["y","n"]
```

##### EXPECTED RESULTS

Working prompt.
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 427, in _execute
    retries = self._task.retries + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

fatal: [vagrant]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

That's reproduced with other modules as well. Worked fine with ansible 2.1.0.0.

**Comment by abadger** [comment]
Thanks for reporting this!  The problem has been fixed in the stable-2.1 branch and should be in the 2.1.2 release which is currently going through release candidates:

```
$ ansible-playbook 17256.yml                                    (07:08:53)
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [pause] *******************************************************************
[pause]
[y/n]:
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
$ ansible --version                                             (07:08:59)
ansible 2.1.2.0 (stable-2.1 559fcbe531) last updated 2016/08/25 21:54:18 (GMT -700)
  lib/ansible/modules/core: (stable-2.1 e3131829e3) last updated 2016/08/08 09:05:06 (GMT -700)
  lib/ansible/modules/extras: (stable-2.1 4556f8ba19) last updated 2016/08/17 07:34:24 (GMT -700)
  config file = /srv/ansible/troubleshooting/ansible.cfg
  configured module search path = Default w/o overrides
```

The PR fixing it is here: https://github.com/ansible/ansible/pull/16963

The 2.1.2 release candidate tarballs are available here: https://releases.ansible.com/ansible/ in case you want to test that this problem will be fixed in the upcoming release.
