### ISSUE TITLE
after upgrade ansible appear some pyton errors

### ISSUE THREAD

**Issue by jahern6** [ansible/ansible#17314]
##### ISSUE TYPE

- Bug Report
  ansible --version
  Traceback (most recent call last):
  File "/usr/bin/ansible", line 44, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/dist-packages/ansible/constants.py", line 152, in <module>
    DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, 'local_tmp',        'ANSIBLE_LOCAL_TEMP',      '$HOME/.ansible/tmp', istmppath=True)
  File "/usr/lib/python2.7/dist-packages/ansible/constants.py", line 78, in get_config
    os.makedirs(value, 0o700)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
  OSError: [Errno 28] No space left on device: '/home/user/.ansible'
- Feature Idea
- Documentation Report
##### COMPONENT NAME

--version
##### ANSIBLE VERSION

```
2.1.1 upgrade
```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by mscherer** [comment]
It seems to be a local issue to your setup (like the disk is full and/or broken ), and I think that's more suitable for the mailling list  and/or irc. See https://docs.ansible.com/ansible/community.html#i-ve-got-a-question

So I am closing that issue, since that's for bug in the code more than direct help.
