### ISSUE TITLE
While using paramiko as connection via API, exception encountered: TypeError: sequence item 0: expected string, NoneType found

### ISSUE THREAD

**Issue by veereshkhanorkar** [ansible/ansible#17330]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

connection/paramiko_ssh.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 591, in _execute_module
    tmp = self._make_tmp_path(remote_user)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 218, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 718, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 253, in exec_command
    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/__init__.py", line 51, in wrapped
    self._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 139, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 212, in _connect_uncached
    sock_kwarg = self._parse_proxy_command(port)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 153, in _parse_proxy_command
    args = self._split_ssh_args(' '.join(ssh_args))
TypeError: sequence item 0: expected string, NoneType found
##### EXPECTED RESULTS

SSH using PARAMIKO should work.
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 591, in _execute_module
    tmp = self._make_tmp_path(remote_user)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 218, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 718, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 253, in exec_command
    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/__init__.py", line 51, in wrapped
    self._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 139, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 212, in _connect_uncached
    sock_kwarg = self._parse_proxy_command(port)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 153, in _parse_proxy_command
    args = self._split_ssh_args(' '.join(ssh_args))
TypeError: sequence item 0: expected string, NoneType found

```

**Comment by nitzmahone** [comment]
Can you post the paramiko version you're using from `pip list` (or elsewhere)?

**Comment by veereshkhanorkar** [comment]
Here you go :

paramiko (2.0.2)

OS Version:

CentOS Linux release 7.2.1511 (Core)

**Comment by abadger** [comment]
Closing this in favor of the PR.
