### ISSUE TITLE
netcli.py: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17407]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

module_utils/netcli.py
##### ANSIBLE VERSION

```
ansible-playbook 2.2.0 (devel 9c5bcda4fe) last updated 2016/09/05 11:03:11 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 982c4557d2) last updated 2016/09/04 17:05:50 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 06bd2a5ce2) last updated 2016/09/04 17:05:50 (GMT +100)
  config file = /home/johnb/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Looks like we are redefining the one of the named arguments.

Maybe just return, or change the name in of the passed argument (`result` as an input is a strange name)

Annoyingly this doesn't seem to be caught by pep8, pylint or pyflakes

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/netcli.py#L266

http://stackoverflow.com/questions/32359946/attributeerror-str-object-has-no-attribute-get-when-trying-to-get-string-in
##### STEPS TO REPRODUCE

`test-network-modules (devel)$ ansible-playbook -vvv eos.yaml  -i inventory`
##### EXPECTED RESULTS

No traceback
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_RbIbW3/ansible_module_eos_command.py", line 242, in <module>
    main()
  File "/tmp/ansible_RbIbW3/ansible_module_eos_command.py", line 218, in main
    runner.run()
  File "/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py", line 166, in run
  File "/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py", line 206, in __call__
  File "/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py", line 229, in get_value
  File "/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py", line 268, in get_json
AttributeError: 'str' object has no attribute 'get'

fatal: [veos01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "eos_command"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_RbIbW3/ansible_module_eos_command.py\", line 242, in <module>\n    main()\n  File \"/tmp/ansible_RbIbW3/ansible_module_eos_command.py\", line 218, in main\n    runner.run()\n  File \"/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 166, in run\n  File \"/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 206, in __call__\n  File \"/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 229, in get_value\n  File \"/tmp/ansible_RbIbW3/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 268, in get_json\nAttributeError: 'str' object has no attribute 'get'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

**Comment by privateip** [comment]
link to PR #17422

**Comment by gundalow** [comment]
fixed
