### ISSUE TITLE
include task using "=" in template fails with unexpected exception

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#17428]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`include`
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```

and

```
ansible 2.2.0 (devel abbb93e117) last updated 2016/09/06 16:36:27 (GMT -600)
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using a "complex" template with an `include` task, `ansible-playbook` fails with an expected exception.
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  vars:
    enable: false
  tasks:
    - include: "{{ enable | ternary('enable', 'disable') }}-fips{{ (ansible_lsb.major_release == 5) | ternary('RedHat5', '') }}.yml"
```
##### EXPECTED RESULTS

No errors
##### ACTUAL RESULTS

```
$ ansible-playbook --check -vvv fips-playbook.yml 
Using /home/agaffney/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Unexpected Exception: '_raw_params'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 73, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 53, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 98, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/play.py", line 115, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/play.py", line 167, in _load_tasks
    return load_list_of_blocks(ds=ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/helpers.py", line 58, in load_list_of_blocks
    loader=loader
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/block.py", line 79, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/block.py", line 115, in _load_block
    use_handlers=self._use_handlers,
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/helpers.py", line 122, in load_list_of_tasks
    (not templar._contains_vars(t.args['_raw_params']) and not t.loop)
KeyError: '_raw_params'
```

If the `include:` is replaced with `debug: msg=`, you get the expected output:

```
TASK [debug] *******************************************************************
task path: /tmp/ansible_test/fips-playbook.yml:6
ok: [localhost] => {
    "msg": "disable-fips.yml"
}
```

Additionally, if you add `static: no` to the `include` task, you get different (bad) output:

```
TASK [include] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No include file was specified to the include"}
```

**Comment by agaffney** [comment]
This issue was originally reported by `rgm3` in the `#ansible` IRC channel. I was able to create a small test case based on that report.

**Comment by agaffney** [comment]
This appears to be due to using a fact as part of the template. When I strip off the `RedHat5` bit of the template, it seems to work as expected.

Task:

```
    - include: "{{ enable | ternary('enable', 'disable') }}-fips.yml"
```

Output:

```
TASK [include] *****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "reason": "the file_name '/tmp/ansible_test/disable-fips.yml' does not exist, or is not readable"}
```

**Comment by agaffney** [comment]
When this same template is used in the `vars:` section and then that var used in the `include` task, it seems to work as expected (or at least without error):

Playbook:

```
---
- hosts: localhost
  vars:
    enable: true
    include_file: "{{ enable | ternary('enable', 'disable') }}-fips{{ (ansible_lsb.major_release == 5) | ternary('RedHat5', '') }}.yml"
  tasks:
    - include: "{{ include_file }}"
```

Output:

```
TASK [include] *****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "reason": "the file_name '/tmp/ansible_test/enable-fips.yml' does not exist, or is not readable"}
```

**Comment by bcoca** [comment]
so that the fact triggers this issue seems to indicate that the include is not being treated as dynamic. Facts are not available during static includes

**Comment by jimi-c** [comment]
I agree with @bcoca, this seems to be a bug in the code which tries to detect a variable in the included file name, however it's not necessarily hitting where I would have expected so I'll have to do some debugging to pin it down.

**Comment by jimi-c** [comment]
For now, using `static: no` on the include will force it to be dynamic, and should get past the error.

**Comment by agaffney** [comment]
As noted above, using `static: no` does prevent the error, but the template ends up as a blank string, which still causes the `include` to fail.

**Comment by jimi-c** [comment]
So it turns out this is occuring because of the `==` in the jinja2 expression above. The `parse_kv` method does not care about the fact that the above is inside a jinja2 variable, or that it's quoted, so the fix would need to be there. Another workaround right now would be to escape the equals: `\\=\\=`

**Comment by bcoca** [comment]
or just set a var with that expression and use the var in the include

```
vars:
  dafile: "{{ enable | ternary('enable', 'disable') }}-fips{{ (ansible_lsb.major_release == 5) | ternary('RedHat5', '') }}"
...
include: "{{dafile}}.yml"
```

**Comment by Akasurde** [comment]
@agaffney Are you still facing this issue ? needs_info

**Comment by agaffney** [comment]
The test playbook does still fail with a similar traceback, but this was never really my issue (it was filed on behalf of another user), so I don't personally care about it.

**Comment by rgm3** [comment]
This still affects my team from time to time.  I've trained them on workarounds.
