### ISSUE TITLE
module_utils/netcli.py: AttributeError: 'dict' object has no attribute 'read'

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17442]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

module_utils/netcli.py
##### ANSIBLE VERSION

```
ansible-playbook --version
ansible-playbook 2.2.0 (devel d67af04c45) last updated 2016/09/07 14:24:26 (GMT +100)
  lib/ansible/modules/core: (devel db38f0c876) last updated 2016/09/07 14:49:01 (GMT +100)
  lib/ansible/modules/extras: (devel 8bfdcfcab2) last updated 2016/09/07 14:49:33 (GMT +100)
  config file = /home/johnb/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### STEPS TO REPRODUCE

```
test-network-modules (devel)$ ansible-playbook -vvv ios.yaml -i inventory  

```
##### EXPECTED RESULTS

No backtrace
##### ACTUAL RESULTS

```
TASK [test_ios_command : test bad operator] ************************************
task path: /home/johnb/git/ansible-inc/test-network-modules/roles/test_ios_command/tests/cli/bad_operator.yaml:4
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/ios/ios_command.py
<ios01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<ios01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817 `" && echo ansible-tmp-1473260341.13-202460472474817="` echo $HOME/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817 `" ) && sleep 0'
<ios01> PUT /tmp/tmp59USiD TO /home/johnb/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817/ios_command.py
<ios01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817/ /home/johnb/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817/ios_command.py && sleep 0'
<ios01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817/ios_command.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1473260341.13-202460472474817/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_RBDdN_/ansible_module_ios_command.py", line 235, in <module>
    main()
  File "/tmp/ansible_RBDdN_/ansible_module_ios_command.py", line 204, in main
    runner.add_conditional(item)
  File "/tmp/ansible_RBDdN_/ansible_modlib.zip/ansible/module_utils/netcli.py", line 148, in add_conditional
  File "/tmp/ansible_RBDdN_/ansible_modlib.zip/ansible/module_utils/netcli.py", line 190, in __init__
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 124, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'dict' object has no attribute 'read'

fatal: [ios01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ios_command"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_RBDdN_/ansible_module_ios_command.py\", line 235, in <module>\n    main()\n  File \"/tmp/ansible_RBDdN_/ansible_module_ios_command.py\", line 204, in main\n    runner.add_conditional(item)\n  File \"/tmp/ansible_RBDdN_/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 148, in add_conditional\n  File \"/tmp/ansible_RBDdN_/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 190, in __init__\n  File \"/usr/lib/python2.7/shlex.py\", line 279, in split\n    return list(lex)\n  File \"/usr/lib/python2.7/shlex.py\", line 269, in next\n    token = self.get_token()\n  File \"/usr/lib/python2.7/shlex.py\", line 96, in get_token\n    raw = self.read_token()\n  File \"/usr/lib/python2.7/shlex.py\", line 124, in read_token\n    nextchar = self.instream.read(1)\nAttributeError: 'dict' object has no attribute 'read'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
...ignoring

```

**Comment by gundalow** [comment]
qalthos said

> in `test_ios_command/tests/cli/bad_operator.yaml`, changing `- result[0] contains 'Description: Foo'` to `- "result[0] contains 'Description: Foo'"` avoids the error
> (needs quotes)
> something about interpreting the colon to mean that the line is a mapping from `result[0] contains 'Description` to `Foo'`
