### ISSUE TITLE
ansible_become_pass in vault results in 

### ISSUE THREAD

**Issue by kkirsche** [ansible/ansible#17463]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ansible-playbook
##### ANSIBLE VERSION

```
~/g/p/ansible-setup ❯❯❯ ansible --version                                                                                              ⏎
ansible 2.1.1.0
  config file = /Users/kkirsche/git/python/ansible-setup/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
fact_caching: jsonfile
fact_caching_connection: ./facts
inventory: ./production
remote_user: ansible
remote_port: 22
forks: 20
pipelining: true
ask_vault_pass: true

[privilege_escalation]
become_method: su
become_user: root
```
##### OS / ENVIRONMENT

- Running ansible 2.1.1.0 with configured module search path = Default w/o overrides on OS X 10.11.6
- Managing multiple operating systems, believe N/A for issue.
##### SUMMARY

While attempting to run a playbook, ansible dies with an unexpected exception. No modules are ran.
##### STEPS TO REPRODUCE

```

---
# file: playbook1.yml

---
  - name: Setup network accounts for use
    hosts: group
    remote_user: kkirsche
    roles:
      - common
      - prezto

---
# file: playbook2.yml

---
  - name: Setup local accounts and tasks
    hosts: group-name
    remote_user: kkirsche
    roles:
      - common
      - prezto

---
# file: group_vars/group-name.yml
- ansible_become_pass=ThisIsAPassword

---
# file: group_vars/group.yml
- ansible_become_pass=ThisIsADifferentPassword


# Inventory
##############################
# personal
# ...
# work
##############################
[int-syslog-aggregator]
log-coll1.example.com ansible_host=1.2.3.4 ansible_ssh_host=1.2.3.4
log-coll2.example.com ansible_host=1.2.4.3 ansible_ssh_host=1.2.4.3

[group:children]
int-syslog-aggregator

[rn-jumphost]
jh-mgt.rn.net ansible_host=1.3.2.4 ansible_ssh_host=1.3.2.4 
jh.rn.net ansible_host=1.2.3.4 ansible_ssh_host=1.2.3.4

[group-name:children]
rn-jumphost

[work:vars]
ansible_user=kkirsche
ansible_ssh_user=kkirsche

##############################
# collection
##############################
[all:children]
work

[all:vars]
ansible_port=22
ansible_ssh_port=22
```

##### ACTUAL RESULTS

There was no difference when running the command with a higher verbosity level. It seemed as though from the traceback this had / has something to do with loading of group variables

The output of the command:

```
~/g/p/ansible-setup ❯❯❯ ansible-playbook role-name.yml -vvvv
Using /Users/kkirsche/git/python/ansible-setup/ansible.cfg as config file
Vault password:
ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 92, in __init__
    self.parse_inventory(host_list)
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 159, in parse_inventory
    group.vars = combine_vars(group.vars, self.get_group_variables(group.name))
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 527, in get_group_variables
    self._vars_per_group[groupname] = self._get_group_variables(groupname, vault_password=vault_password)
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 545, in _get_group_variables
    vars = combine_vars(vars, self.get_group_vars(group))
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 727, in get_group_vars
    return self._get_hostgroup_vars(host=None, group=group, new_pb_basedir=new_pb_basedir, return_results=return_results)
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 788, in _get_hostgroup_vars
    host_results = self._variable_manager.add_group_vars_file(base_path, self._loader)
  File "/usr/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 616, in add_group_vars_file
    data = self._load_inventory_file(path, loader)
  File "/usr/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 574, in _load_inventory_file
    rval.update(data)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by alikins** [comment]
```
~/g/p/ansible-setup ❯❯❯ ansible-playbook role-name.yml -vvvv
Using /Users/kkirsche/git/python/ansible-setup/ansible.cfg as config file
Vault password:
ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
the full traceback was:
```

Was the error before or after entering the vault password?
Is the behavior different without 'ask_vault_pass' set?

Was this playbook/inventory working with earlier versions of ansible?

**Comment by kkirsche** [comment]
- The error occurred after entering the vault password. The vault can be accessed using `ansible-vault edit group_vars/role-name.yml` as expected.
- Anytime that Ansible attempts to load the group variables from the vault, it seems to fail.
- N/A — Was made with this version

**Comment by amenonsen** [comment]
> ---
> 
> # file: group_vars/group-name.yml
> - ansible_become_pass=ThisIsAPassword

That "=" is not valid YAML.

> ---
> 
> # file: group_vars/group.yml
> - ansible_become_pass=ThisIsADifferentPassword

Same. Also, you shouldn't put the assignments into a list (it may still
work, I'm not sure; but it's not expected).

Your file should look like this instead:

```
---

ansible_become_pass: ThisIsAPassword
other_stuff: ThisIsNotAPassword
```

**Comment by kkirsche** [comment]
Seems it was as simple as a misunderstanding of YAML syntax. Thank you for your time and help.
