### ISSUE TITLE
Fail to install 2.1.1.0 on Debian 8 (Docker)

### ISSUE THREAD

**Issue by weldpua2008** [ansible/ansible#17578]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

standart 
##### OS / ENVIRONMENT

[Official Debian 8 Docker Image](https://hub.docker.com/_/debian/)
##### SUMMARY

I am trying to install ansible 2.1.1.0 on Debian 8 (Oficial Docker image) and it is failing.
The build log:  https://travis-ci.org/weldpua2008/docker-ansible/jobs/160005850
##### STEPS TO REPRODUCE

There is my Dockerfile for Debian 8:
https://github.com/weldpua2008/docker-ansible/blob/2.1.x/debian/8/Dockerfile

```
wget https://raw.githubusercontent.com/weldpua2008/docker-ansible/2.1.x/debian/8/Dockerfile
docker build -t test .
```
##### EXPECTED RESULTS

Ansible is working
##### ACTUAL RESULTS

https://api.travis-ci.org/jobs/160005850/log.txt?deansi=true

```
===> Installing Ansible 2.1.1.0 ..
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 4, in <module>
    binding = Binding()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in _ensure_ffi_initialized
    libraries=libraries,
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
    extra_link_args=extra_link_args,
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 437, in verify
    lib = self.verifier.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 114, in load_library
    return self._load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 225, in _load_library
    return self._vengine.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 174, in load_library
    lst = list(map(self.ffi._get_cached_btype, lst))
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 409, in _get_cached_btype
    BType = type.get_cached_btype(self, finishlist)
  File "/usr/local/lib/python2.7/dist-packages/cffi/model.py", line 61, in get_cached_btype
    BType = self.build_backend_type(ffi, finishlist)
  File "/usr/local/lib/python2.7/dist-packages/cffi/model.py", line 507, in build_backend_type
    base_btype = self.build_baseinttype(ffi, finishlist)
  File "/usr/local/lib/python2.7/dist-packages/cffi/model.py", line 525, in build_baseinttype
    % self._get_c_name())
cffi.api.CDefError: 'point_conversion_form_t' has no values explicitly defined: refusing to guess which integer type it is meant to be (unsigned/signed, int/long)
The command '/bin/sh -c echo "===> Installing python, sudo, and supporting tools..."  &&     apt-get update  &&     DEBIAN_FRONTEND=noninteractive              apt-get install -y                              python python-yaml sudo                      curl gcc python-pip python-dev  &&          apt-get install libssl-dev libffi-dev python-setuptools -y &&         pip install --upgrade cffi &&         echo "===> Installing Ansible 2.1.1.0 .."   &&     pip install ansible==2.1.1.0                &&             echo "===> Removing unused APT resources..."                       &&     apt-get -f -y --auto-remove remove curl gcc python-pip python-dev  &&     apt-get clean                                                      &&     rm -rf /var/lib/apt/lists/*  /tmp/*                                &&             echo "===> Adding hosts for convenience..."        &&     mkdir -p /etc/ansible                              &&     echo '[local]\nlocalhost\n' > /etc/ansible/hosts' returned a non-zero code: 1
failed
```

**Comment by remyleone** [comment]
Same here.

**Comment by jacderida** [comment]
This is also happening to me when trying to install Ansible via pip on the Vagrant [debian/jessie64](https://atlas.hashicorp.com/debian/boxes/jessie64) box.

**Comment by bcoca** [comment]
not sure this is an Ansible issue, looks like a pip/debian/cryptography issue (cryptography is a dependency)

**Comment by remyleone** [comment]
When I install cryptography before installing ansible it seems to work.

**Comment by bcoca** [comment]
So cryptography is a dependency, but not a direct one, it comes in via ~~pycrypto~~ paramiko. 
We don't have control over pip nor the ~~pycrypto~~ paramiko package and I'm still unclear what the exact problem is (version? dependency resolution?).

I'm leaving the ticket open as a reminder to research this issue, but I suspect that the most likely solution on our side will be documenting this quirk in our install docs.

**Comment by abadger** [comment]
Correction: cryptography is an optional dependency of ansible.  If it's installed we use it because it's faster than pycrypto.  If it's not there we fallback to using pycrypto.

**Comment by sivel** [comment]
cryptography is actually a direct dependency of paramiko since paramiko version 2.

```
Collecting cryptography>=1.1 (from paramiko->ansible)
```

https://github.com/paramiko/paramiko/commit/56a4739923a356ff5670b4620139ca55a2f30148

**Comment by jctanner** [comment]
The first problem is that "pip install --upgrade cffi" breaks pip permanently on a Jessie system. Every operation will fail on the cffi.api.CDefError regardless of it's relation to ansible or crypto. For example, I can no longer install epdb because of the cffi.api.CDefError. So do not try to upgrade cffi through pip.

Second problem that you'll hit if trying to pip install ansible without first upgrading cryptography/cffi is an incompatibility between cryptography and setuptools (https://github.com/byt3bl33d3r/MITMf/issues/163). I'm guessing that's why you attempted to update cffi initially.

There's no clear way to fix the importerror that I could find, but I did eventually figure out a workaround ...

```
dkpg -r python-pip ; easy_install pip ; /usr/local/bin/pip install ansible==2.1.1.0
```

The latest version of pip can handle and eventually sort out the crypto issues. However, you can't simply upgrade pip via pip due to a "owned by OS" error. So remove it via dpkg so that the dependencies are left behind, install it with easy_install and then install ansible with the new pip.

Not a clean workaround by any means, but it does work and allows you to continue using pip. The better solution is to use an officially released package of ansible or find a PPA.
