### ISSUE TITLE
"serial" can't be passed as a command line argument (-e) to ansible-playbook

### ISSUE THREAD

**Issue by jbartus** [ansible/ansible#1767]
``` shell
[root@cobbler ~]# cat foo.yml

---
- hosts: app-pool
  serial: ${servar}

  tasks:

    - name: write a file
      action: shell touch /tmp/foo

    - name: delete it
      action: shell rm -f /tmp/foo

[root@cobbler ~]# ansible-playbook foo.yml -e "servar=1"

PLAY [app-pool] *********************

GATHERING FACTS *********************
ok: [app02.foo.bar.com]
ok: [app03.foo.bar.com]
ok: [app05.foo.bar.com]
ok: [app04.foo.bar.com]
ok: [app01.foo.bar.com]
ok: [app06.foo.bar.com]
ok: [app07.foo.bar.com]
ok: [app08.foo.bar.com]
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 164, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 135, in main
    pb.run()
  File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 193, in run
    if not self._run_play(play):
  File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 378, in _run_play
    for x in range(play.serial):
TypeError: range() integer end argument expected, got str.
```

**Comment by dominis** [comment]
Pull request: https://github.com/ansible/ansible/pull/1777
