### ISSUE TITLE
Simple example from Ansible documentation fails with 'ImportError: No module named runner'

### ISSUE THREAD

**Issue by ligurio** [ansible/ansible#18024]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible core
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

- Ubuntu 16.04 LTS
- Python 2.7.11+

```
test@ubuntu-16-04:~$ pip --version ansible
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
test@ubuntu-16-04:~$ pip show ansible

---
Metadata-Version: 2.0
Name: ansible
Version: 2.1.2.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: support@ansible.com
Installer: pip
License: GPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: PyYAML, setuptools, jinja2, paramiko, pycrypto
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Intended Audience :: Developers
  Intended Audience :: Information Technology
  Intended Audience :: System Administrators
  License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
  Natural Language :: English
  Operating System :: POSIX
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Topic :: System :: Installation/Setup
  Topic :: System :: Systems Administration
  Topic :: Utilities
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
test@ubuntu-16-04:~$
```
##### STEPS TO REPRODUCE
1. copy text of detailed API example from documentation from http://docs.ansible.com/ansible/developing_api.html and insert to the text file on your environment

```
#!/usr/bin/python

import ansible.runner
import sys

# construct the ansible runner and execute on all hosts
results = ansible.runner.Runner(
    pattern='*', forks=10,
    module_name='command', module_args='/usr/bin/uptime',
).run()

if results is None:
   print "No hosts found"
   sys.exit(1)

print "UP ***********"
for (hostname, result) in results['contacted'].items():
    if not 'failed' in result:
        print "%s >>> %s" % (hostname, result['stdout'])

print "FAILED *******"
for (hostname, result) in results['contacted'].items():
    if 'failed' in result:
        print "%s >>> %s" % (hostname, result['msg'])

print "DOWN *********"
for (hostname, result) in results['dark'].items():
    print "%s >>> %s" % (hostname, result)
```
1. try to run this example with python ansible.py

##### EXPECTED RESULTS

I'm expect successful execution of script.
##### ACTUAL RESULTS

```
test@ubuntu-16-04:~$ python ansible.py                                                                                       
Traceback (most recent call last):
  File "ansible.py", line 3, in <module>
    import ansible.runner
  File "/home/test/ansible.py", line 3, in <module>
    import ansible.runner
ImportError: No module named runner
test@ubuntu-16-04:~$ 
```

**Comment by jctanner** [comment]
@ligurio "runner" is a pre-2.0 api, which has been deprecated. For a 2.0 api example, please use this page: http://docs.ansible.com/ansible/dev_guide/developing_api.html#python-api-2-0
