### ISSUE TITLE
Ansible dynamic inventory script ec2.py fails with --profile

### ISSUE THREAD

**Issue by TimJDFletcher** [ansible/ansible#18496]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2.py dynamic inventory

##### ANSIBLE VERSION
```
macbook:ansible tim$ ansible --version
ansible 2.2.0.0
  config file = /Users/tim/XXXX/ansible/ansible.cfg
  configured module search path = ['modules']
```

##### CONFIGURATION
Created simple AWS profiles in .aws/config and .aws/credentials

$HOME/.aws/credentials
```
[example]
aws_access_key_id = XXXX
aws_access_key_id  = YYYY
```

$HOME/.aws/config
```
[profile example]
region = eu-west-1
output = json
```

##### OS / ENVIRONMENT
macOS 10.11.6
Ansible installed via pip (pip install -U git+git://github.com/ansible/ansible.git@stable-2.2)

##### SUMMARY
Calling the inventory script with a profile on the command line gives an error, calling it with the same config file but passing the profile name as an environment variable works.

I suspect it may be related to or the same root cause as bug #9984

##### STEPS TO REPRODUCE

Call ec2.py with AWS profile name on the command line

```
./ec2.py --profile example 
Traceback (most recent call last):
  File "./ec2.py", line 1510, in <module>
    Ec2Inventory()
  File "./ec2.py", line 188, in __init__
    self.do_api_calls_update_cache()
  File "./ec2.py", line 494, in do_api_calls_update_cache
    self.include_rds_clusters_by_region(region)
  File "./ec2.py", line 608, in include_rds_clusters_by_region
    account_id = boto.connect_iam().get_user().arn.split(':')[4]
  File "/usr/local/lib/python2.7/site-packages/boto/__init__.py", line 382, in connect_iam
    return IAMConnection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto/iam/connection.py", line 73, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 993, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```
Call the ec2.py inventory script with the profile name passed as an environment variable works correctly as shown:
```
AWS_PROFILE=example ./ec2.py 
{
  "_meta": {
    "hostvars": {}
  }, 
  "db_clusters": {}
}
```

**Comment by s-hertel** [comment]
I wasn't able to replicate this on macOS 10.12.2 using 
`./contrib/inventory/ec2.py --profile shertel` on 
```
ansible 2.2.1.0
  config file = /Users/shertel/XXXX/ansible/ansible.cfg
  configured module search path = ['modules']
```
I tried `git diff v2.2.0.0-1 -- ./contrib/inventory/ec2.py` and the only code difference between our versions is a python3 compatibility thing 
```
             @@ -1313,7 +1313,7 @@ class Ec2Inventory(object):
             elif key == 'ec2_tags':
                 for k, v in value.items():
                     if self.expand_csv_tags and ',' in v:
-                        v = map(lambda x: x.strip(), v.split(','))
+                        v = list(map(lambda x: x.strip(), v.split(',')))
                     key = self.to_safe('ec2_tag_' + k)
                     instance_vars[key] = v
             elif key == 'ec2_groups':
```
 
So I'm going to close this since it seems to be working.
