### ISSUE TITLE
`ansible-playbook` crashes when all hosts fail and playbook filename is UTF-8

### ISSUE THREAD

**Issue by clonedagain** [ansible/ansible#18523]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Defaults provided by the official Ubuntu 16.04 backport package.

##### OS / ENVIRONMENT
Ubuntu 16.04  in French

##### SUMMARY
When a playbook has a filename in UTF-8, if all hosts in a play fail then `ansible-playbook` crashes while reporting the failures.

##### STEPS TO REPRODUCE
Set your shell to French (`LANG="fr_FR.UTF-8"`, `LANGUAGE="fr_FR"`)

Save this playbook to a file called "pêche.yml":
```
---
- hosts: localhost
  tasks:
    - fail: msg="Parti à la pêche"
```

Run `ansible-playbook pêche.yml -vvv`

##### EXPECTED RESULTS
Failure should be reported for each host.

##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7f092ecd43d0>): 'ascii' codec can't
decode byte 0xc3 in position 12: ordinal not in range(128)

1 plays in pêche.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ls
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1479390317.69-240727645238194 `" && echo ansible-tmp-1479390317.69-240727645238194="` echo $HOME/.ansible/tmp/ansible-tmp-1479390317.69-240727645238194 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpJ6u9R2 TO /home/ls/.ansible/tmp/ansible-tmp-1479390317.69-240727645238194/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python /home/ls/.ansible/tmp/ansible-tmp-1479390317.69-240727645238194/setup; rm -rf "/home/ls/.ansible/tmp/ansible-tmp-1479390317.69-240727645238194/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [fail] ********************************************************************
task path: /home/ls/Bureau/bug ansible/pêche.yml:4
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"msg": "Parti à la pêche"}, "module_name": "fail"}, "msg": "Parti à la pêche"}

NO MORE HOSTS LEFT *************************************************************
ERROR! Unexpected Exception: 'ascii' codec can't decode byte 0xc3 in position 42: ordinal not in range(128)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 199, in run
    if self._generate_retry_inventory(filename, retries):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 273, in _generate_retry_inventory
    display.warning("Could not create retry file '%s'.\n\t%s" % (retry_path, to_str(e)))
  File "/usr/lib/python2.7/dist-packages/ansible/utils/display.py", line 232, in warning
    self.display(new_msg, color=C.COLOR_WARN, stderr=True)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/display.py", line 122, in display
    msg = stringc(msg, color)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/color.py", line 73, in stringc
    return u"\033[%sm%s\033[0m" % (codeCodes[color], text)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 42: ordinal not in range(128)

```

**Comment by clonedagain** [comment]
My bad, it's fixed in 2.2.
