### ISSUE TITLE
module_utils atomic_move causes traceback when safe write fails

### ISSUE THREAD

**Issue by danielkza** [ansible/ansible#18628]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module_utils

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /Users/cobli/cobli/herbie/deploy/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Irrelevant

##### OS / ENVIRONMENT
Irrelevant

##### SUMMARY
module_utils.basic.atomic_move crashes when attempting to handle some exceptions due to a typo, attempting to use an uninitialized variable `exception` instead of calling `get_exception`

##### STEPS TO REPRODUCE
Use the lineinfile to modify /etc/hosts (a bind-mounted file) in a Docker container.

##### EXPECTED RESULTS
A failed task with the corresponding error message.

##### ACTUAL RESULTS
Traceback.

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_puPX1w/ansible_module_lineinfile.py", line 425, in <module>
    main()
  File "/tmp/ansible_puPX1w/ansible_module_lineinfile.py", line 417, in main
    ins_aft, ins_bef, create, backup, backrefs)
  File "/tmp/ansible_puPX1w/ansible_module_lineinfile.py", line 298, in present
    write_changes(module, b_lines, dest)
  File "/tmp/ansible_puPX1w/ansible_module_lineinfile.py", line 175, in write_changes
    unsafe_writes=module.params['unsafe_writes'])
  File "/tmp/ansible_puPX1w/ansible_modlib.zip/ansible/module_utils/basic.py", line 2001, in atomic_move
NameError: global name 'exception' is not defined

failed: [sensu-1] (item=172.17.0.5) => {
    "failed": true,
    "invocation": {
        "module_name": "lineinfile"
    },
    "item": "172.17.0.5",
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_puPX1w/ansible_module_lineinfile.py\", line 425, in <module>\n    main()\n  File \"/tmp/ansible_puPX1w/ansible_module_lineinfile.py\", line 417, in main\n    ins_aft, ins_bef, create, backup, backrefs)\n  File \"/tmp/ansible_puPX1w/ansible_module_lineinfile.py\", line 298, in present\n    write_changes(module, b_lines, dest)\n  File \"/tmp/ansible_puPX1w/ansible_module_lineinfile.py\", line 175, in write_changes\n    unsafe_writes=module.params['unsafe_writes'])\n  File \"/tmp/ansible_puPX1w/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2001, in atomic_move\nNameError: global name 'exception' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
```

**Comment by alikins** [comment]
Looks like 8b08a28c895666b9fc673e5bf26bd91b2be77fe6 may be the culprit here.

**Comment by alikins** [comment]
See also:

https://github.com/ansible/ansible/pull/18630 
https://github.com/ansible/ansible-modules-core/issues/5616

**Comment by hecko** [comment]
I can confirm this issue on centos6 docker image and ansible-2.2.0.0-3.el6.noarch from epel
