### ISSUE TITLE
ansible_python_interpreter is not templated before use

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#18665]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansiballz

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 8e4d95b125) last updated 2016/11/29 18:45:42 (GMT +1000)
  lib/ansible/modules/core: (rds_split 8f4cfaee07) last updated 2016/11/28 22:38:05 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 43bb97bc37) last updated 2016/11/28 20:36:43 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
OS X with python from homebrew or virtualenv

##### SUMMARY
Running `python $module_package execute` runs under /usr/bin/python, whether virtualenv or homebrew in use

##### STEPS TO REPRODUCE
```
virtualenv /path/to/venv
source /path/to/venv/bin/activate
pip install ansible epdb
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook playbook.yml -vvv
python $module_package explode
# add an `import epdb` statement and `epdb.st()`
python $module_package execute
```

##### EXPECTED RESULTS
Python drops into epdb session

##### ACTUAL RESULTS
```
$ python /Users/will/.ansible/tmp/ansible-tmp-1480409869.55-272491715446155/rds_instance.py execute
Traceback (most recent call last):
  File "/Users/will/.ansible/tmp/ansible-tmp-1480409869.55-272491715446155/debug_dir/ansible_module_rds_instance.py", line 710, in <module>
    main()
  File "/Users/will/.ansible/tmp/ansible-tmp-1480409869.55-272491715446155/debug_dir/ansible_module_rds_instance.py", line 678, in main
    import epdb
ImportError: No module named epdb
```

If I update the path in the ansiballz module (to remove the `/usr/bin/` in front of python) it works fine.

**Comment by willthames** [comment]
One for @abadger I suspect

**Comment by willthames** [comment]
This might just be a result of me not setting `ansible_python_interpreter` - it gets me every time, but would be nice if ansible just respected whatever python it was being run under on (particularly for `connection: local`) - it's difficult to set `ansible_python_interpreter` when one could be switching between virtualenvs

**Comment by bcoca** [comment]
if you use `local_action` or `delegate_to: localhost` you should get the proper interpreter automatically as they change the target host to localhost. `connection: local` does not change the target host and allows using specific ansible_python_interpreter for each of these that are not the same as the localhost one.

**Comment by willthames** [comment]
delegate_to: localhost is only available at a task level, not at a play level - it's frankly tedious to have to add delegate_to: localhost to every task.

It would be good if ansible_python_interpreter could be dynamically set (it can't).

See #33052 for this issue cropping up again (probably because people who use a lot of local actions tend to set connection: local)

**Comment by bcoca** [comment]
>It would be good if ansible_python_interpreter could be dynamically set (it can't).

incorrect, you can set it any level, just like any other var.

**Comment by willthames** [comment]
https://github.com/ansible/ansible/issues/29449#issuecomment-350022628 is likely also an example of this happening again

**Comment by willthames** [comment]
@bcoca, you *can't* set ansible_python_interpreter dynamically, it just doesn't work.

```
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
  - command: echo hello "{{ hello }}"
    vars:
      hello: world
```

```
PLAY [localhost] *********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: {{: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/will/tmp/ansible/playbook.retry
```

**Comment by bcoca** [comment]
@willthames nothing in your output points at that, here is an example of it working:

```
- hosts: notlocalhost
  gather_facts: false
  tasks:
    - command: echo hi
    - command: echo hi
      vars:
        ansible_python_interpreter: '{{ansible_playbook_python}}'
```
extracting the pertinent parts of the output:

```
task path: /home/bcoca/work/ansible/i.yml:5
Using module file /home/bcoca/work/ansible/lib/ansible/modules/commands/command.py
...
<notlocalhost> EXEC /bin/sh -c 'ANSIBLE_REMOTE_TEMP=/home/bcoca/.ansible/tmp/ansible-tmp-1512693036.87-240020235699087/ /usr/bin/python /home/bcoca/.ansible/tmp/ansible-tmp-1512693036.87-240020235699087/command.py; rm -rf "/home/bcoca/.ansible/tmp/ansible-tmp-1512693036.87-240020235699087/" > /dev/null 2>&1 && sleep 0'        
```
first task uses /usr/bin/python

```
task path: /home/bcoca/work/ansible/i.yml:6
Using module file /home/bcoca/work/ansible/lib/ansible/modules/commands/command.py
...
<notlocalhost> EXEC /bin/sh -c 'ANSIBLE_REMOTE_TEMP=/home/bcoca/.ansible/tmp/ansible-tmp-1512693036.98-174608139717732/ /usr/bin/python3 /home/bcoca/.ansible/tmp/ansible-tmp-1512693036.98-174608139717732/command.py; rm -rf "/home/bcoca/.ansible/tmp/ansible-tmp-1512693036.98-174608139717732/" > /dev/null 2>&1 && sleep 0'
```
2nd task uses /usr/bin/python3 (which is the python ansible is using as controller)

**Comment by willthames** [comment]
What do you mean nothing points to that? The error message literally says that "{{" is a bad interpreter.

You say I can set `ansible_python_interpreter` at any level, and I've demonstrated that you can't set it as a playbook var. If I have to set `ansible_python_interpreter` for every task, I might as well set `delegate_to: localhost` for every task. Neither is a suitable solution when my entire playbooks and roles are run locally.

If you can show a way that I can use a dynamically set python for all tasks in one place that would be great.

**Comment by willthames** [comment]
```
$ ansible-playbook playbook.yml -vvvv
ansible-playbook 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Nov  2 2017, 18:42:05) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: playbook.yml ***************************************************************************************************************************************
1 plays in playbook.yml

PLAY [localhost] *********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: will
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658 `" && echo ansible-tmp-1512693925.82-199076911779658="` echo /home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpdvkGh3 TO /home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658/ /home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '{{ ansible_playbook_python }} /home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658/setup.py; rm -rf "/home/will/.ansible/tmp/ansible-tmp-1512693925.82-199076911779658/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "/bin/sh: {{: command not found\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/will/tmp/ansible/playbook.retry

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```

(just in case this was a problem with gathering facts, I also tried with `gather_facts: no` at which point it just failed on the task instead)

**Comment by bcoca** [comment]
so narrowed down the problem to `vars:` at play level not getting templated

**Comment by willthames** [comment]
thanks @bcoca

**Comment by bcoca** [comment]
actually, vars are templated, just this one is not, `ansible_python_interpreter` gets used w/o templating, most people hardcode so that works, but `{{ }}` does not. Actually it affects all `ansible_X_interpreter` settings.

**Comment by bcoca** [comment]
My PR above fixes it for my test case, as a workaround:

```
- set_fact:
     ansible_python_interpreter: '{{ansible_playbook_python}}' 
```
should work as the value is templated before assignment in `set_fact` and not lazy like in `vars:`

**Comment by rlueckl** [comment]
Sorry, wrong ticket.
