### ISSUE TITLE
redis cache using --flush-cache fails: cannot concatenate 'str' and 'Host' objects

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#18708]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cache/redis.py

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
fact_caching=redis
```

##### OS / ENVIRONMENT
CentOS 7, though unlikely to be OS specific

##### SUMMARY
Using the redis caching fails if there are already items in the cache.

##### STEPS TO REPRODUCE

Populate redis cache, normal gather facts playbook suffices.
Run playbook to gather facts again w/ --flush-cache.

##### EXPECTED RESULTS
No error.

##### ACTUAL RESULTS

```
/usr/bin/ansible-playbook playbooks/gather-facts.yml -i inventory/_test-all --flush-cache -vvvvv
Using /home/jenkins-slave/slave/workspace/Ansible Fact Sync/ansible.cfg as config file
ERROR! Unexpected Exception: cannot concatenate 'str' and 'Host' objects
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    variable_manager.clear_facts(host)
  File "/usr/lib/python2.7/site-packages/ansible/vars/__init__.py", line 640, in clear_facts
    del self._fact_cache[hostname]
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 52, in __delitem__
    self._plugin.delete(key)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/redis.py", line 89, in delete
    self._cache.delete(self._make_key(key))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/redis.py", line 54, in _make_key
    return self._prefix + key
TypeError: cannot concatenate 'str' and 'Host' objects
```

**Comment by alikins** [comment]
I can reproduce this in 2.3/devel

```
[fedora-23:ansible (fix_tests %)]$ ansible-playbook -i hosts -v -v -v ping.yml --flush-cache
Using ansible_redis_caching.cfg as config file
ERROR! Unexpected Exception: coercing to Unicode: need string or buffer, Host found
the full traceback was:

Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/playbook.py", line 152, in run
    variable_manager.clear_facts(host)
  File "/home/adrian/src/ansible/lib/ansible/vars/__init__.py", line 646, in clear_facts
    del self._fact_cache[hostname]
  File "/home/adrian/src/ansible/lib/ansible/plugins/cache/__init__.py", line 52, in __delitem__
    self._plugin.delete(key)
  File "/home/adrian/src/ansible/lib/ansible/plugins/cache/redis.py", line 89, in delete
    self._cache.delete(self._make_key(key))
  File "/home/adrian/src/ansible/lib/ansible/plugins/cache/redis.py", line 54, in _make_key
    return self._prefix + key
TypeError: coercing to Unicode: need string or buffer, Host found
```
