### ISSUE TITLE
Using incorrect fact_caching gives weird error

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#18751]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cache plugin hook

##### ANSIBLE VERSION

v2.2

##### OS / ENVIRONMENT

Any

##### SUMMARY

When I incorrectly configured Ansible to use a JSON facts cache, I got a very weird error that I initially could not trace back to this configuration item.

##### STEPS TO REPRODUCE

```
fact_caching = json
```

##### EXPECTED RESULTS

Using /home/dag/home-made/ansible.testing/ansible.cfg as config file
 ERROR! No fact cache plugin found of type "json".

##### ACTUAL RESULTS

```
Using /home/dag/home-made/ansible.testing/ansible.cfg as config file
 [WARNING]: Failed to load fact cache plugins


PLAY [localhost] ***************************************************************
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'contains'
```

**Comment by alikins** [comment]
I can reproduce with 2.3

```
Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/playbook.py", line 157, in run
    results = pbex.run()
  File "/home/adrian/src/ansible/lib/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/home/adrian/src/ansible/lib/ansible/executor/task_queue_manager.py", line 269, in run
    start_at_done = self._start_at_done,
  File "/home/adrian/src/ansible/lib/ansible/executor/play_iterator.py", line 204, in __init__
    if host.name in variable_manager._fact_cache and variable_manager._fact_cache.get('module_setup', False):
  File "/home/adrian/src/ansible/lib/ansible/plugins/cache/__init__.py", line 56, in __contains__
    return self._plugin.contains(key)
AttributeError: 'NoneType' object has no attribute 'contains'
```

**Comment by dagwieers** [comment]
Thanks !
