### ISSUE TITLE
Unable to use registered variable in delegate_to statement

### ISSUE THREAD

**Issue by fabala** [ansible/ansible#18774]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_to and registered variable

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /root/.ansible.cfg
  configured module search path = ['/context/abc-core/library']
```

##### CONFIGURATION
[defaults]
library = /context/abc-core/library
roles_path = /context/abc-core/roles
host_key_checking = False

##### OS / ENVIRONMENT
ubuntu + docker

##### SUMMARY
You cannot use a registered variable in a `delegate_to` statement.

##### STEPS TO REPRODUCE
Register a variable and try to use it in a `delegate_to` statement in next task.

```
---
- hosts: test
  serial: 1
  gather_facts: no
  tasks:
  - name: test1
    command: echo localhost
    delegate_to: localhost
    register: var1
  
  - name: test2
    command: echo toto
    delegate_to: "{{ var1 }}"
    #delegate_to: localhost
```

##### EXPECTED RESULTS
```
PLAY [test] ********************************************************************

TASK [test1] *******************************************************************
changed: [host1 -> localhost]

TASK [test2] *******************************************************************
changed: [host1 -> localhost]

PLAY RECAP *********************************************************************
host1                      : ok=2    changed=2    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
Using /root/.ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [test] ********************************************************************

TASK [test1] *******************************************************************
task path: /context/abc-infra/test.yml:6
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666 `" && echo ansible-tmp-1480591207.22-36445557842666="` echo $HOME/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666 `" ) && sleep 0'
<localhost> PUT /tmp/tmpaOpB3z TO /root/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666/ /root/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666/command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1480591207.22-36445557842666/" > /dev/null 2>&1 && sleep 0'
changed: [host1 -> localhost] => {
    "changed": true,
    "cmd": [
        "echo",
        "localhost"
    ],
    "delta": "0:00:00.096470",
    "end": "2016-12-01 11:20:07.415705",
    "invocation": {
        "module_args": {
            "_raw_params": "echo localhost",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 0,
    "start": "2016-12-01 11:20:07.319235",
    "stderr": "",
    "stdout": "localhost",
    "stdout_lines": [
        "localhost"
    ],
    "warnings": []
}
ERROR! Unexpected Exception: unhashable type: 'dict'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 282, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 234, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 370, in get_vars
    all_vars['ansible_delegated_vars'] = self._get_delegated_vars(loader, play, task, all_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 464, in _get_delegated_vars
    if delegated_host_name in delegated_host_vars:
TypeError: unhashable type: 'dict'
```
If I don't use `delegate_to: "{{ var1 }}"` but `delegate_to: localhost` instead, it works as expected.

**Comment by fabala** [comment]
Tested with Ansible 2.0 and 2.1: same issue.

**Comment by fabala** [comment]
I try the following test:

```
---
- hosts: test
  serial: 1
  gather_facts: no
  tasks:
  - name: test1
    command: echo localhost
    delegate_to: localhost
    register: var1
  
  - name: test2
    command: "echo {{ var1 }}"
    delegate_to: localhost
```

In this test, I want to use the registered variable inside the `command` statement (instead of using it inside the `delegate_to` statement) and it works as expected.

So the issue is probably only related to the `delegate_to` statement.

**Comment by fabala** [comment]
I have found my mistake: I should use `{{ var1.stdout }}` instead of `{{ var1 }}`.

Sorry, not a bug. Maybe a check could be added in order to avoid the task execution to abruptly fail?
