### ISSUE TITLE
[Ubuntu 16.04 - ansible 2.2.0.0] apt-module throws KeyError: 'changed'

### ISSUE THREAD

**Issue by xiongchiamiov** [ansible/ansible#19013]
_From @JeffreyDevloo on November 2, 2016 13:43_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/lib/ansible/']
```

##### CONFIGURATION
Changed the path.

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Cannot install packages using apt-modules.

##### STEPS TO REPRODUCE
- Setup playbook with apt
- Run playbook

```
- hosts: cluster
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: check hosts their availability
      ping:
      tags:
         - cluster

    - name: add openvstorage apt-repo
      shell: echo "deb http://apt.openvstorage.org {{ hostvars[inventory_hostname].ovs_version }} main" > /etc/apt/sources.list.d/ovsaptrepo.list
      tags:
         - cluster

    - name: install required packages
      apt: update_cache=yes name=ntp state=present force=yes
      tags:
         - cluster

    - name: add performance settings to cluster
      shell: echo 1 > /proc/sys/vm/swappiness; echo 'vm.swappiness=1' >> /etc/sysctl.conf; echo '134217728' > /proc/sys/vm/dirty_background_bytes; echo 'vm.dirty_background_bytes = 134217728' >> /etc/sysctl.conf
      tags:
         - cluster
```

##### EXPECTED RESULTS
Module will throw a python KeyError causing the playbook to fail.

##### ACTUAL RESULTS
```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/packaging/os/apt.py
<10.100.199.151> ESTABLISH SSH CONNECTION FOR USER: root
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/packaging/os/apt.py
<10.100.199.152> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.151> SSH: EXEC sshpass -d22 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.100.199.151 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647 `" && echo ansible-tmp-1478093295.66-261469675321647="` echo $HOME/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647 `" ) && sleep 0'"'"''
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/packaging/os/apt.py
<10.100.199.153> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.152> SSH: EXEC sshpass -d23 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.100.199.152 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995 `" && echo ansible-tmp-1478093295.66-189382284835995="` echo $HOME/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995 `" ) && sleep 0'"'"''
<10.100.199.153> SSH: EXEC sshpass -d24 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.100.199.153 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999 `" && echo ansible-tmp-1478093295.67-152913268375999="` echo $HOME/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999 `" ) && sleep 0'"'"''
<10.100.199.151> PUT /tmp/tmpgRGqlV TO /root/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647/apt.py
<10.100.199.151> SSH: EXEC sshpass -d22 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.100.199.151]'
<10.100.199.153> PUT /tmp/tmpH7GQ9Q TO /root/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999/apt.py
<10.100.199.153> SSH: EXEC sshpass -d24 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.100.199.153]'
<10.100.199.152> PUT /tmp/tmpDGKfbU TO /root/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995/apt.py
<10.100.199.152> SSH: EXEC sshpass -d23 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.100.199.152]'
<10.100.199.151> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.151> SSH: EXEC sshpass -d22 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.100.199.151 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647/ /root/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647/apt.py && sleep 0'"'"''
<10.100.199.153> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.153> SSH: EXEC sshpass -d24 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.100.199.153 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999/ /root/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999/apt.py && sleep 0'"'"''
<10.100.199.152> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.152> SSH: EXEC sshpass -d23 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.100.199.152 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995/ /root/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995/apt.py && sleep 0'"'"''
<10.100.199.151> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.151> SSH: EXEC sshpass -d22 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.100.199.151 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647/apt.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1478093295.66-261469675321647/" > /dev/null 2>&1 && sleep 0'"'"''
<10.100.199.153> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.152> ESTABLISH SSH CONNECTION FOR USER: root
<10.100.199.152> SSH: EXEC sshpass -d23 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.100.199.152 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995/apt.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1478093295.66-189382284835995/" > /dev/null 2>&1 && sleep 0'"'"''
<10.100.199.153> SSH: EXEC sshpass -d24 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.100.199.153 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999/apt.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1478093295.67-152913268375999/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [ctl03]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "apt"
    }, 
    "module_stderr": "Shared connection to 10.100.199.153 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_LtFRMb/ansible_module_apt.py\", line 909, in <module>\r\n    main()\r\n  File \"/tmp/ansible_LtFRMb/ansible_module_apt.py\", line 892, in main\r\n    if updated_cache and not retvals['changed']:\r\nKeyError: 'changed'\r\n", 
    "msg": "MODULE FAILURE"
}
fatal: [ctl02]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "apt"
    }, 
    "module_stderr": "Shared connection to 10.100.199.152 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_A4al9W/ansible_module_apt.py\", line 909, in <module>\r\n    main()\r\n  File \"/tmp/ansible_A4al9W/ansible_module_apt.py\", line 892, in main\r\n    if updated_cache and not retvals['changed']:\r\nKeyError: 'changed'\r\n", 
    "msg": "MODULE FAILURE"
}
fatal: [ctl01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "apt"
    }, 
    "module_stderr": "Shared connection to 10.100.199.151 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_DLpMnw/ansible_module_apt.py\", line 909, in <module>\r\n    main()\r\n  File \"/tmp/ansible_DLpMnw/ansible_module_apt.py\", line 892, in main\r\n    if updated_cache and not retvals['changed']:\r\nKeyError: 'changed'\r\n", 
    "msg": "MODULE FAILURE"
}

```

_Copied from original issue: ansible/ansible-modules-core#5459_

**Comment by xiongchiamiov** [comment]
_From @ansibot on November 2, 2016 14:2_

@JeffreyDevloo we are unable to validate that "ansible_module" is an existing ansible module.

We are expecting a component name that matches something that can be found in:
- http://docs.ansible.com/ansible/list_of_all_modules.html

Please revise the component name in the description.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by xiongchiamiov** [comment]
_From @ansibot on November 2, 2016 14:44_

@JeffreyDevloo, we need more information to resolve this issue. For that reason, we put this Issue into the 'needs_info' state.

When you have answered the questions or filled in the missing data, please comment with text 'ready_for_review' and we will put this Issue back into review.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by xiongchiamiov** [comment]
_From @davidak on November 16, 2016 13:55_

I have the same error when i try to install 8 packages with the apt module. It worked with only 3 of them.

```
TASK [common : install libreoffice] ********************************************
task path: /home/davidak/code/ansible-ubuntu-desktop/roles/common/tasks/libreoffice.yml:1
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/packaging/os/apt.py
<unibook> ESTABLISH LOCAL CONNECTION FOR USER: davidak
<unibook> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576 `" && echo ansible-tmp-1479303873.68-166869679633576="` echo $HOME/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576 `" ) && sleep 0'
<unibook> PUT /tmp/tmpOHhQhv TO /home/davidak/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576/apt.py
<unibook> EXEC /bin/sh -c 'chmod u+x /home/davidak/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576/ /home/davidak/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576/apt.py && sleep 0'
<unibook> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=bkddahvidsslivwebgkvkwdugpleesdl] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-bkddahvidsslivwebgkvkwdugpleesdl; /usr/bin/python /home/davidak/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576/apt.py; rm -rf "/home/davidak/.ansible/tmp/ansible-tmp-1479303873.68-166869679633576/" > /dev/null 2>&1'"'"' && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ZIqfy_/ansible_module_apt.py", line 909, in <module>
    main()
  File "/tmp/ansible_ZIqfy_/ansible_module_apt.py", line 892, in main
    if updated_cache and not retvals['changed']:
KeyError: 'changed'

failed: [unibook] (item=[u'libreoffice', u'libreoffice-templates', u'libreoffice-gtk3', u'libreoffice-style-elementary', u'libreoffice-l10n-de', u'hunspell-dictionary-de', u'hyphen-de', u'mythes-de']) => {
    "failed": true, 
    "invocation": {
        "module_name": "apt"
    }, 
    "item": [
        "libreoffice", 
        "libreoffice-templates", 
        "libreoffice-gtk3", 
        "libreoffice-style-elementary", 
        "libreoffice-l10n-de", 
        "hunspell-dictionary-de", 
        "hyphen-de", 
        "mythes-de"
    ], 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZIqfy_/ansible_module_apt.py\", line 909, in <module>\n    main()\n  File \"/tmp/ansible_ZIqfy_/ansible_module_apt.py\", line 892, in main\n    if updated_cache and not retvals['changed']:\nKeyError: 'changed'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
    to retry, use: --limit @/home/davidak/code/ansible-ubuntu-desktop/setup.retry

PLAY RECAP *********************************************************************
unibook                    : ok=22   changed=13   unreachable=0    failed=1
```

you find the whole code at https://github.com/davidak/ansible-ubuntu-desktop/blob/bd07fcbc894eb9d217a9d67abb802a23307c3c73/roles/common/tasks/libreoffice.yml

---

elementary OS 0.4 Loki (based on Ubuntu 16.04 LTS)

**Comment by xiongchiamiov** [comment]
_From @alonshoshani on November 20, 2016 19:51_

I'm using ansible 2.2.0.0 and try to install collectd 

```
- name: Install collecd agent
  apt:
   name: collectd
   update_cache: yes
```

Get this error:

```
fatal: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 54.214.197.219 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_wQP7ds/ansible_module_apt.py\", line 909, in <module>\r\n    main()\r\n  File \"/tmp/ansible_wQP7ds/ansible_module_apt.py\", line 892, in main\r\n    if updated_cache and not retvals['changed']:\r\nKeyError: 'changed'\r\n", "msg": "MODULE FAILURE"}
```

**Comment by xiongchiamiov** [comment]
_From @psviderski on November 23, 2016 4:31_

I got the same error when I tried to install a new version of a package that was marked as held back. `apt-mark unhold package_name`  before execution of the playbook solved the issue (ansible 2.2.0.0).

**Comment by xiongchiamiov** [comment]
_From @dschneller on November 23, 2016 10:19_

Also broken for 14.04 targets.

**Comment by xiongchiamiov** [comment]
_From @dschneller on November 23, 2016 11:55_

Cannot reproduce with a current checkout from the stable-2.2 branch (ansible 2.2.1.0 (stable-2.2 ac076dfc12)) -- any idea when a 2.2.1 release will be made?

**Comment by xiongchiamiov** [comment]
_From @dschneller on November 23, 2016 12:2_

If I am not mistaken, https://github.com/ansible/ansible-modules-core/pull/5487 fixes this.

**Comment by xiongchiamiov** [comment]
_From @ansibot on December 7, 2016 19:58_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by resmo** [comment]
fixed by https://github.com/ansible/ansible-modules-core/pull/5487 closing

**Comment by xshadow** [comment]
Same error on debian jessie with ansible 2.2.0.0 from jessie-backports.
