### ISSUE TITLE
unreachable if ansible_password is encrypted by 'per variable' vault

### ISSUE THREAD

**Issue by yunano** [ansible/ansible#19795]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
'per variable' vault ( https://github.com/ansible/ansible/pull/16274 )

##### ANSIBLE VERSION
both 2.2.0 and devel

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
ansible 2.3.0 (devel 425ab5598e) last updated 2017/01/03 13:01:56 (GMT +900)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
nothing special

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The ssh connection becomes unreachable by authentication failure if the value of ansible_password is encrypted.

##### STEPS TO REPRODUCE

* create a vault password file with any password (filename: vault_pass)

* create an inventory file (filename: hosts)
```
$ cat hosts
[test]
test1 ansible_host=172.21.1.184 ansible_user=vagrant
```

* set a value encrypted by vault to ansible_password in host_vars/test1.yml
```
$ echo 'ansible_password: !vault-encrypted |' > host_vars/test1.yml; echo -n 'vagrant' | ansible-vault encrypt --vault-password-file vault_pass | xargs -I @ printf "%2s%s\n" '' @ >> host_vars/test1.yml
$ cat host_vars/test1.yml
ansible_password: !vault-encrypted |
  $ANSIBLE_VAULT;1.1;AES256
  64383761663636303762306234383966333935346165633464646535376563653064353161363164
  6232346236353135376635373236333134363065353031390a613733333133653663643863303038
  64303734346238306633336161303439366335323338383964303833323564336532666564323532
  6131663132626539620a326331666530666334393436383134326265653736663866343534333366
  3562
```

* launch `ansible test1 -i hosts --vault-password-file vault_pass -m ping -vvvv`

##### EXPECTED RESULTS
success

##### ACTUAL RESULTS

```
$ ansible test1 -i hosts --vault-password-file vault_pass -m ping -vvvv
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /home/vagrant/ansible/lib/ansible/plugins/callback/__init__.pyc
Using module file /home/vagrant/ansible/lib/ansible/modules/system/ping.py
<172.21.1.184> ESTABLISH SSH CONNECTION FOR USER: vagrant
<172.21.1.184> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r 172.21.1.184 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1483429987.59-257858382794001 `" && echo ansible-tmp-1483429987.59-257858382794001="` echo ~/.ansible/tmp/ansible-tmp-1483429987.59-257858382794001 `" ) && sleep 0'"'"''
test1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication failure.",
    "unreachable": true
}
```

Additional information:

* I can retrieve the value of ansible_password with the debug module.
```
$ ansible test1 -i hosts --vault-password-file vault_pass -m debug -a var=ansible_password
test1 | SUCCESS => {
    "ansible_password": "vagrant"
}
```

* This issue also affects ansible_become_pass.

**Comment by alikins** [comment]
I can reproduce this on devel/ branch (a601f2c6a341f7b4026fea5f60ddc67f3e6d02dc).

**Comment by alikins** [comment]
Looks like the ssh connection plugin does a to_bytes() on ansible_password which is an AnsibleEncryptedUnicode at that point, and the to_bytes just returns a obj.encode('utf-8', 'replace').
On py2, that is already a str, so AnsibleEncryptedUnicode never gets its __str__() method called
(and the __str__() is what actually returns the decrypted value). The connection plugin gets the full
yaml string '$ANSIBLE_VAULT...'. 

I suspect AnsibleEncryptedUnicode needs a encode() that decrypts as well.

**Comment by wybczu** [comment]
It looks like the problem still occurs. When I try to use `winrm` connection with encrypted `ansible_passowrd`  I'm getting:

```
TASK [Gathering Facts] *************************************************************************************************************************
Using module file /home/luk/work/oss/ansible/lib/ansible/modules/windows/setup.ps1
<winhost> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO winhost
<winhost> WINRM CONNECT: transport=ssl endpoint=https://winhost:5986/wsman
<winhost> WINRM CONNECTION ERROR: encode() argument 2 must be string, not None
Traceback (most recent call last):
  File "/home/luk/work/oss/ansible/lib/ansible/plugins/connection/winrm.py", line 211, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/home/luk/.local/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/home/luk/.local/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/home/luk/.local/lib/python2.7/site-packages/winrm/transport.py", line 181, in send_message
    prepared_request = self.session.prepare_request(request)
  File "/home/luk/.local/lib/python2.7/site-packages/requests/sessions.py", line 436, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/luk/.local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/home/luk/.local/lib/python2.7/site-packages/requests/models.py", line 543, in prepare_auth
    r = auth(self)
  File "/home/luk/.local/lib/python2.7/site-packages/requests/auth.py", line 96, in __call__
    r.headers['Authorization'] = _basic_auth_str(self.username, self.password)
  File "/home/luk/.local/lib/python2.7/site-packages/requests/auth.py", line 63, in _basic_auth_str
    password = password.encode('latin1')
  File "/home/luk/work/oss/ansible/lib/ansible/parsing/yaml/objects.py", line 137, in encode
    return self.data.encode(encoding, errors)
TypeError: encode() argument 2 must be string, not None

fatal: [winhost]: UNREACHABLE! => {
    "changed": false, 
    "msg": "ssl: encode() argument 2 must be string, not None", 
    "unreachable": true
}
```

although I can access encrypted variable in a play. Following playbook works perfectly:

```yaml
- hosts: all
  become: false
  vars:
    # ansible_password__vault is a single encrypted variable
    ansible_password: "{{ ansible_password__vault }}"
  tasks:
    - win_ping:
``` 

Tested with ansible 2.4.0 (devel 0e0e5097a9).

**Comment by wybczu** [comment]
@bcoca could you reopen this issues or should I create a new one?

**Comment by stephenconnolly1** [comment]
Also a problem in ansible 2.3 with WinRM. ansible_password variable stored under group_vars\windows-servers.yaml as a separately encrypted variable.

Works fine if we encrypt the whole file, but not if we're doing per-variable encryption.

In our case the error log shows password.encode('utf-16le') rather than latin-1, and we are using ntlm rather than basic auth.
