### ISSUE TITLE
Ansible playbook error regarding template_ds

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#1983]
ansible-playbook generates a traceback if one's uses `only_if`. I've bissected this and it seems to happen since a79373f (post v1.0 release).

Here is a minimal example :

```
$ cat hosts
[ubuntu]
goat

$ cat host_vars/goat
install: yes

$ cat setup.yml 

---
- hosts: ubuntu

  tasks:
  - name: Test | Debug
    action: debug msg="debug => $install"
    only_if: '$install'

$ python2 bin/ansible-playbook -l goat ~/tmp/anstest/setup.yml -i ~/tmp/anstest/hosts

PLAY [ubuntu] ********************* 

GATHERING FACTS ********************* 
ok: [goat]

TASK: [Test | Debug] ********************* 
fatal: [goat] => Traceback (most recent call last):
  File "/home/leucos/dev/ansible/lib/ansible/runner/__init__.py", line 237, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/leucos/dev/ansible/lib/ansible/runner/__init__.py", line 293, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/leucos/dev/ansible/lib/ansible/runner/__init__.py", line 353, in _executor_internal_inner
    if not getattr(handler, 'BYPASS_HOST_LOOP', False) and not utils.check_conditional(conditional):
  File "/home/leucos/dev/ansible/lib/ansible/utils/__init__.py", line 155, in check_conditional
    return eval(conditional.replace("\n", "\\n"))
AttributeError: 'bool' object has no attribute 'replace'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
goat                           : ok=1    changed=0    unreachable=1    failed=0    
$ 
```

I tested variations on the `only_if` line :

`only_if: 'True'` => ok
`only_if: '$install'` => fail
`only_if: '${install}'` => fail
`only_if: '${some.dictionnary.install}'` => fail

Thanks.

**Comment by mpdehaan** [comment]
thanks for the example & bisect

looks like we just need to make check_conditional smarter in this case as
something was already a bool.
