### ISSUE TITLE
"UnicodeEncodeError: 'ascii' codec can't encode..." error, instead of actual "Failed to set permissions on the temporary files..." error

### ISSUE THREAD

**Issue by karlmdavis** [ansible/ansible#19964]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
I'm using the `command` module, but the bug itself is in Ansible core.

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.0.0
  config file = /home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg
  configured module search path = ['/home/karl/.ansible/roles']
```

##### CONFIGURATION
(Haven't changed the Ansible config in any relevant way.)

##### OS / ENVIRONMENT
Management system is Ubuntu 14.04, and the managed system is the same.

##### SUMMARY
When running the `command` module as an unprivileged user, I receive the following output:

```
TASK [karlmdavis.jenkins2 : Verify CLI] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 29: ordinal not in range(128)
fatal: [52.90.107.158]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

If I re-reun with `-vvv`, I get the following:

```
TASK [karlmdavis.jenkins2 : Verify CLI] ****************************************                                                                                                              [11/1842]
task path: /home/karl/.ansible/roles/karlmdavis.jenkins2/tasks/cli_config.yml:94
Using module file /home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<52.90.107.158> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.90.107.158> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Passwo
rdAuthentication=no -o User=ubuntu -o ConnectTimeout=10 52.90.107.158 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1483664177.87-272363309495442 `" && echo ansible-tmp-1483664177.
87-272363309495442="` echo /tmp/ansible-tmp-1483664177.87-272363309495442 `" ) && sleep 0'"'"''
<52.90.107.158> PUT /tmp/tmpm0NaYz TO /tmp/ansible-tmp-1483664177.87-272363309495442/command.py
<52.90.107.158> SSH: EXEC sftp -b - -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o 
PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 '[52.90.107.158]'
<52.90.107.158> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.90.107.158> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Passwo
rdAuthentication=no -o User=ubuntu -o ConnectTimeout=10 52.90.107.158 '/bin/sh -c '"'"'setfacl -m u:jenkins:rx /tmp/ansible-tmp-1483664177.87-272363309495442/ /tmp/ansible-tmp-1483664177.87-272363309
495442/command.py && sleep 0'"'"''
<52.90.107.158> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.90.107.158> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Passwo
rdAuthentication=no -o User=ubuntu -o ConnectTimeout=10 52.90.107.158 '/bin/sh -c '"'"'chmod u+x /tmp/ansible-tmp-1483664177.87-272363309495442/ /tmp/ansible-tmp-1483664177.87-272363309495442/command
.py && sleep 0'"'"''
<52.90.107.158> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.90.107.158> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o Passwo
rdAuthentication=no -o User=ubuntu -o ConnectTimeout=10 52.90.107.158 '/bin/sh -c '"'"'chown jenkins /tmp/ansible-tmp-1483664177.87-272363309495442/ /tmp/ansible-tmp-1483664177.87-272363309495442/com
mand.py && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 490, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 617, in _execute_module
    self._fixup_perms2(remote_files, remote_user)
  File "/home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 394, in _fixup_perms2
    ' see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user'.format(res['rc'], res['stderr']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 29: ordinal not in range(128)

fatal: [52.90.107.158]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

##### STEPS TO REPRODUCE

Here's my `command` task:

```yaml
- name: Verify CLI
  shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }} who-am-i"
  register: cli_whoami
  become: true
  become_user: jenkins
  changed_when: false
```

##### EXPECTED RESULTS
I'd expect to see the following error output (which I produced by applying the fix mentioned below):

```
TASK [karlmdavis.jenkins2 : Verify CLI] ****************************************
fatal: [52.90.107.158]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of ‘/tmp/ansible-tmp-1483666630.43-160731891715309/’: Operation not permitted\nchown: changing ownership of ‘/tmp/ansible-tmp-1483666630.43-160731891715309/command.py’: Operation not permitted\n). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

##### ACTUAL RESULTS
See above. Note that the error message here (without `-vvv`) is completely useless, and will lead folks down a Google deadend.

##### FIX/TRIAGE
I can get the correct error by editing line `394` of the `venv/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py` file on my box from:

    raise AnsibleError('Failed to set file mode on remote files (rc: {0}, err: {1})'.format(res['rc'], res['stderr']))

To instead be this:

    raise AnsibleError('Failed to set file mode on remote files (rc: {0}, err: {1})'.format(res['rc'], res['stderr'].encode('utf-8')))

This problem (not properly encoding `STDOUT`/`STDERR` output) looks like it might be all over the place, though, and should probably be addressed in a comprehensive fashion.

**Comment by abadger** [comment]
This was fixed in: https://github.com/ansible/ansible/pull/18565

The fix is in both the devel and stable-2.2 branches.  The next release will be 2.2.1 which has the fix applied.  You can try running from source ( http://docs.ansible.com/ansible/intro_installation.html#running-from-source ) to test that or download the latest 2.2.1 release candidate tarballsfrom here: https://releases.ansible.com/ansible/
