### ISSUE TITLE
Umlaut in current path brakes while argument parsing

### ISSUE THREAD

**Issue by schmic** [ansible/ansible#2010]
I just checked out the latest devel-branch, sourced hacking/env-setup.

``` bash
[buk@delle ansible]$ pwd
/home/buk/Arbeitsfläche/Workspaces/ansible
[buk@delle ansible]$ bin/ansible -v
Traceback (most recent call last):
  File "bin/ansible", line 143, in <module>
    (options, args) = cli.parse()
  File "bin/ansible", line 61, in parse
    parser.print_help()
  File "/usr/lib/python2.7/optparse.py", line 1669, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1428: ordinal not in range(128)
[buk@delle ansible]$ echo $LANG
de_DE.utf8
```

**Comment by schmic** [comment]
Showing the version does work though.

``` bash
[buk@delle ansible]$ bin/ansible --version
ansible 1.1 (devel dddfeac9c4) last updated 2013/02/07 20:21:12 (GMT +200)
[buk@delle ansible]$ pwd
/home/buk/Arbeitsfläche/Workspaces/ansible
```

**Comment by schmic** [comment]
I'm sorry but must have been some other glitch ... can't reproduce it anymore.

``` bash
[buk@delle ansible]$ ansible -k -v -i /tmp/inv all -m ping
SSH password: 
localhost | success >> {
    "changed": false, 
    "ping": "pong"
}

[buk@delle ansible]$ pwd
/home/buk/Arbeitsfläche/Workspaces/ansible
[buk@delle ansible]$ ansible -v
Usage: ansible <host-pattern> [options]
[...]
```
