### ISSUE TITLE
Jinja <2.9 requirement breaks package dependencies on Arch Linux

### ISSUE THREAD

**Issue by cdown** [ansible/ansible#20285]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible core

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Arch Linux, with the following packages:

```
% pacman -Qi ansible
Name            : ansible
Version         : 2.2.1.0rc5-3
Description     : Radically simple IT automation platform
Architecture    : any
URL             : http://www.ansible.com
Licenses        : GPL3
Groups          : None
Provides        : python2-ansible
Depends On      : python2  python2-yaml  python2-paramiko  python2-jinja  python2-crypto
Optional Deps   : python2-passlib: crypt values for vars_prompt
                  python2-netaddr: for the ipaddr filter
                  python2-systemd: log to journal
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 31.22 MiB
Packager        : Sven-Hendrik Haase <sh@lutzhaase.com>
Build Date      : Mon 16 Jan 2017 02:02:23 AM GMT
Install Date    : Mon 16 Jan 2017 07:24:44 AM GMT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

% pacman -Qi python2-jinja
Name            : python2-jinja
Version         : 2.9.4-1
Description     : A simple pythonic template language written in Python
Architecture    : any
URL             : http://jinja.pocoo.org/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python2-setuptools  python2-markupsafe
Optional Deps   : None
Required By     : ansible
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 2032.00 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Wed 11 Jan 2017 03:28:14 AM GMT
Install Date    : Mon 16 Jan 2017 07:29:17 AM GMT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

##### SUMMARY

This seems to have something to do with #20197. I didn't find the exact code (the stack implicates our dependency on cryptography, but cryptography has no dependency on jinja at all), but we require jinja>2.9, but Arch Linux ships Jinja 2.9.4. This means that builds from the official Arch Linux repositories (and, I assume, other distributions that try to quickly update from upstream).

For now I can install this in a virtualenv I guess, but that seems nasty compared to this just working.

##### STEPS TO REPRODUCE

1. Run `ansible-playbook` on any playbook on Arch Linux.

##### EXPECTED RESULTS

Ansible works.

##### ACTUAL RESULTS

```
root@ansible-personal % ansible-playbook -i localhost, -v setup.yml -vvv
Using /etc/ansible/ansible.cfg as config file
Set default localhost to localhost
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/pacman.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/network.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/ssh.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/zsh.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/users.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/aur.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/sudo.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/ntp.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/fonts.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/xorg.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/blacklist-pc-speaker.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/desktop.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/basic-tools.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/cron.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/systemd.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/email.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/media.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/chinese.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/sysctl.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/shared.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/pkgfile.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/vostro-tools.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/lin-dev.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/udev.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/printing.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/sound.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/skype.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/power.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/remove.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/debugging.yml
skipping vars_file 'vars/{{ config_file }}.yml' due to an undefined variable
statically included: /root/git/ansible-personal/tasks/locale.yml
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
ERROR! Unexpected Exception: The 'jinja2<2.9' distribution was not found and is required by ansible
the full traceback was:

Traceback (most recent call last):
  File "/usr/sbin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 177, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 394, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 324, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'jinja2<2.9' distribution was not found and is required by ansible
```

**Comment by alikins** [comment]
Afaict, the change in https://github.com/ansible/ansible/pull/20197 should not be involved (that just changes some of the CI setup on https://shippable.com and shouldn't effect normal use).


Were versions of the ansible arch linux package before '2.2.1.0rc5-3' working? 

I suspect the arch package change at:
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/ansible&id=1c9a83d1cb519d1da8b90cd037cab1ab0f8ac578

may be causing the problems.

**Comment by cdown** [comment]
Hm, based on that change to the package, we now depend on setuptools (which does package enforcement) whereas previously we didn't, so it seems suspect. Did Ansible not use setuptools before?

**Comment by barthalion** [comment]
For now, I pushed a package to our repositories that reverts the commit adding said restriction. I believe these issues with jinja 2.9 must have been happening with the previous stable as well so why not keep being broken. If I'm wrong, I can downgrade jinja2 or Ansible, but I'd like to have your confirmation first (or at least a link to the issue with 2.9, so I can test it myself).

**Comment by alikins** [comment]
@Barthalion cool. Looks like we are going to rollback the jinja2 2.9 requirement in setup.py as well so that should get stuff stabilized.

**Comment by abadger** [comment]
jinja2-2.9.0-2.9.4 are broken with ansible.  See, for instance, https://github.com/ansible/ansible/issues/20098 .  If you want to work around that downstream, that's fine.  I'll be reverting that in the stable-2.1 and stable-2.2 branches soon as we just wanted to make sure the last release didn't encounter this brokenness.

jinja2-2.9.5 has been released which fixes that particular error from the jinja2 side (mitsuhiko has been great!  I was expecting we'd need to update ansible code to run on jinja2-2.9).  If arch updates to 2.9.5 it should be safer to update. (Safer because I think there are some other 2.9.x incompatibilities.  They just aren't as major).

**Comment by abadger** [comment]
One other jinja2-2.9 problem so you have less hunting around to do: https://github.com/ansible/ansible/issues/20063

Changes to setup.py reverted in stable branches in the expectation that the problems will either have been ironed out in ansible or jinja2 code before the next releases.

As for this: "I believe these issues with jinja 2.9 must have been happening with the previous stable as well so why not keep being broken."  The reason to specify the version in setup.py is that anyone who can install multiple versions of jinja2 will get a working install if we specify the version.  (That includes installing into a virtualenv and installing an older jinja2 version using  setuptools multiple-version installs: https://packaging.python.org/multi_version_install/ ).

**Comment by barthalion** [comment]
Thanks, I will push upgraded jinja tomorrow.

**Comment by abadger** [comment]
@Barthalion Just an FYI I've been told in one of the other bugs that jinja2-2.9.5 has not yet been released.  It's the in-development version of jinja2 right now.

**Comment by chrissound** [comment]
I believe I'm running into this issue, I'm not too sure what the conclusion is? Any ideas how I can test if I am effected by this?

I'm essentially running into the below error:
`An unhandled exception occurred while templating '{{ kube_service_addresses|ipaddr('net')|ipaddr(2)|ipaddr('address') }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipaddr filter requires python-netaddr be installed on the ansible controller`

https://github.com/kubernetes-incubator/kubespray/issues/2685

**Comment by chrissound** [comment]
Fixed by:

```
sudo pip install --ignore-install -r requirements.txt
```

**requirements.txt**

    pbr>=1.6
    ansible>=2.4.0
    netaddr
    jinja2>=2.9.6
