### ISSUE TITLE
net_command: Not correctly detecting empty/undefined _raw_params

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#20294]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
net_command

##### ANSIBLE VERSION
```
ansible 2.3.0 (network-aws 1045e3a5a9) last updated 2017/01/11 19:42:39 (GMT +100)
```

##### SUMMARY
Calling `net_command` without any arguments causes a backtrace, rather than a graceful error message that `no command given`.

```python
      argument_spec = dict(
          _raw_params=dict()
      )   
  
      module = LocalAnsibleModule(argument_spec=argument_spec,
                                  supports_check_mode=False)
  
      if str(module.params['_raw_params']).strip() == '': 
          module.fail_json(rc=256, msg='no command given')
```

##### STEPS TO REPRODUCE
```yaml
- name: net_command - Missing command
  net_command:
  connection: network_cli
  register: result
```

##### EXPECTED RESULTS

Graceful failure (no backtrace) and
`"msg": "no command give", `

##### ACTUAL RESULTS
```python
TASK [net_command : net_command - Missing command] ***********************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/net_command/tasks/vyos.yml:108
<ec2-54-161-180-253.compute-1.amazonaws.com> closing connection
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/executor/task_executor.py", line 504, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/network.py", line 43, in run
    module.main()
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/modules/network/basics/net_command.py", line 115, in main
    rc, out, err = module.exec_command(module.params['_raw_params'])
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/module_utils/local.py", line 59, in exec_command
    rc, out, err = self.connection.exec_command(args)
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/network_cli.py", line 219, in exec_command
    obj = json.loads(cmd)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

fatal: [ec2-54-161-180-253.compute-1.amazonaws.com]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Comment by gundalow** [comment]
@rcarrillocruz Have a look at other modules that take freeform arguments, such as the `shell` or `command` modules

**Comment by rcarrillocruz** [comment]
will do , thanks

**Comment by privateip** [comment]
net_command has been removed for 2.3 final
