### ISSUE TITLE
ec2_asg fails to run when there is no instance in the Auto Scaling group

### ISSUE THREAD

**Issue by maximede** [ansible/ansible#20473]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel e98c0a3009) last updated 2017/01/04 10:41:06 (GMT -700)
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

If there is no Instances running in the auto-scaling group, running ec2_asg fails: 

##### STEPS TO REPRODUCE

- Have an ec2 Auto Scaling group running with at least one machine.
- Change the number of instances to 0
- When all the instances in our asg are terminated, re-run the ec2_asg task

```yaml
- ec2_asg:
    name: "server autoscaling group"
    launch_config_name: "server-launch-config"
    health_check_period: 60
    health_check_type: EC2
    desired_capacity: 0
    min_size: 0
    max_size: 1
    region: "{{aws_region}}"
    replace_all_instances: yes
    vpc_zone_identifier: "{{autoscaling_subnet_ids}}"
```

##### EXPECTED RESULTS

ec2_asg runs and update (or not) the asg config

##### ACTUAL RESULTS

```
TASK [ec2 : ec2_asg] ***************************************************************************************************************************************************************************************
task path: /../servers.yml
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/y2/l4g6_6zn03s1mh34lkz1czjm0000gn/T/ansible_lJMEl4/ansible_module_ec2_asg.py", line 928, in <module>
    main()
  File "/var/folders/y2/l4g6_6zn03s1mh34lkz1czjm0000gn/T/ansible_lJMEl4/ansible_module_ec2_asg.py", line 922, in main
    replace_changed, asg_properties=replace(connection, module)
  File "/var/folders/y2/l4g6_6zn03s1mh34lkz1czjm0000gn/T/ansible_lJMEl4/ansible_module_ec2_asg.py", line 646, in replace
    instances = props['instances']
KeyError: 'instances'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ec2_asg"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/y2/l4g6_6zn03s1mh34lkz1czjm0000gn/T/ansible_lJMEl4/ansible_module_ec2_asg.py\", line 928, in <module>\n    main()\n  File \"/var/folders/y2/l4g6_6zn03s1mh34lkz1czjm0000gn/T/ansible_lJMEl4/ansible_module_ec2_asg.py\", line 922, in main\n    replace_changed, asg_properties=replace(connection, module)\n  File \"/var/folders/y2/l4g6_6zn03s1mh34lkz1czjm0000gn/T/ansible_lJMEl4/ansible_module_ec2_asg.py\", line 646, in replace\n    instances = props['instances']\nKeyError: 'instances'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by maximede** [comment]
fixed with #20475
