### ISSUE TITLE
Unhandled unexpected exception when passing empty vault password to ansible-console

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible#20502]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
console

##### ANSIBLE VERSION

```
% ansible --version
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Ansible console throws unexpected exception stacktrace on empty vault password.

##### STEPS TO REPRODUCE

```
$ ansible-console localhost --ask-vault-pass
<press enter>
```

##### EXPECTED RESULTS
Continue on without vault password. And either run the tasks or error out on not being able to decrypt encountered vault.

##### ACTUAL RESULTS

```
% ansible-console localhost --ask-vault-pass -vvv
No config file found; using defaults
Vault password: 
ERROR! Unexpected Exception: string index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-console", line 103, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/console.py", line 427, in run
    vault_pass = self.ask_vault_passwords()[0]
IndexError: string index out of range
```

**Comment by ashemedai** [comment]
Looking at all uses of the `ask_vault_passwords()` method, only console.py does a hard array index reference in the form of `self.ask_vault_passwords()[0]`. The others all simply do `self.ask_vault_passwords()` prior to handing it over to `loader.set_vault_password()`.
