### ISSUE TITLE
Error when using callback plugins log_play.py and mail.py together

### ISSUE THREAD

**Issue by phgrau** [ansible/ansible#2064]
I run in an error if I use the callback plugins log_play.py and mail.py together;

``` sh
    $ ansible host1 -vvv -m shell -a "false"
    <host1> ESTABLISH CONNECTION FOR USER: root
    <host1> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'host1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1360702031.32-100841133739727 && echo $HOME/.ansible/tmp/ansible-1360702031.32-100841133739727'"]
    <host1> REMOTE_MODULE command false #USE_SHELL
    <host1> PUT /tmp/tmptdbJ5Z TO /root/.ansible/tmp/ansible-1360702031.32-100841133739727/command
    <host1> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'host1', "/bin/sh -c ' /usr/bin/python /root/.ansible/tmp/ansible-1360702031.32-100841133739727/command; rm -rf /root/.ansible/tmp/ansible-1360702031.32-100841133739727/ >/dev/null 2>&1'"]
    host1 | FAILED | rc=1 >>


    host1 | FAILED => Traceback (most recent call last):
      File "/user/home/src/ansible/lib/ansible/runner/__init__.py", line 272, in _executor
        exec_rc = self._executor_internal(host)
      File "/user/home/src/ansible/lib/ansible/runner/__init__.py", line 328, in _executor_internal
        return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
      File "/user/home/src/ansible/lib/ansible/runner/__init__.py", line 476, in _executor_internal_inner
        self.callbacks.on_failed(host, data, ignore_errors)
      File "/user/home/src/ansible/lib/ansible/callbacks.py", line 237, in on_failed
        super(CliRunnerCallbacks, self).on_failed(host, res, ignore_errors=ignore_errors)
      File "/user/home/src/ansible/lib/ansible/callbacks.py", line 195, in on_failed
        call_callback_module('runner_on_failed', host, res, ignore_errors=ignore_errors)
      File "/user/home/src/ansible/lib/ansible/callbacks.py", line 56, in call_callback_module
        method(*args, **kwargs)
      File "/user/home/src/ansible/lib/ansible/callback_plugins/mail.py", line 55, in runner_on_failed
        subject = 'Failed: %(module_name)s %(module_args)s' % res['invocation']
    KeyError: 'invocation'
```

Using them seperately is trouble free :-)

Regards.

**Comment by mpdehaan** [comment]
Probably because of the way things pop off invocation in a few places.

We need to not do that and just show a copy without the invocation struct.
