### ISSUE TITLE
PERSISTENT_CONNECTIONS regression

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#20693]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.3.0 (detached HEAD 6673673042) last updated 2017/01/26 12:50:00 (GMT +100)

```

##### SUMMARY
Looks like there is a regression caused by  https://github.com/ansible/ansible/commit/66736730422b4b3b8f585ecd58cdec5a6833c912

##### STEPS TO REPRODUCE

**inventory.network-jobarker**
```
[testhost]
x260 ansible_connection=local
```
**persistent_connect.yml**
```yaml
---
- hosts: all
  gather_facts: yes
  tasks:
    - debug:
        msg: Testing
johnb@x260:~/git/ansib
```

**Command**
`time ANSIBLE_USE_PERSISTENT_CONNECTIONS=True  ansible-playbook -vvvvv  persistent_connect.yml -i  inventory.network-jobarker --limit x260 -u johnb`

##### EXPECTED RESULTS
Successful gathering of facts

##### ACTUAL RESULTS

**sudo tail -f /var/log/syslog | grep ansible-connection:**
```
Jan 26 12:57:04 x260 ansible-connection: <x260> ESTABLISH LOCAL CONNECTION FOR USER: johnb
Jan 26 12:57:04 x260 ansible-connection: <x260> Traceback (most recent call last):#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 285, in main#012    server = Server(sf_path, pc)#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 123, in __init__#012    rc, out, err = self.conn._connect()#012TypeError: 'Connection' object is not iterable
```

```yaml
TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/system/setup.py
fatal: [x260]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1485435424.59-199483914968857 `\" && echo ansible-tmp-1485435424.59-199483914968857=\"` echo ~/.ansible/tmp/ansible-tmp-1485435424.59-199483914968857 `\" ), exited with result 255", 
 
```

**Comment by gundalow** [comment]
Rerunning with `ANSIBLE_DEBUG=True`

```

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
 18641 1485436253.75794: sending task start callback
 18641 1485436253.75796: entering _queue_task() for x260/setup
 18641 1485436253.75874: worker is 1 (out of 1 available)
 18641 1485436253.75894: exiting _queue_task() for x260/setup
 18641 1485436253.75932: done queuing things up, now waiting for results queue to drain
 18641 1485436253.75935: waiting for pending results...
 18649 1485436253.76229: running TaskExecutor() for x260/TASK: Gathering Facts
 18649 1485436253.76262: in run()
 18649 1485436253.76292: calling self._execute()
 18649 1485436253.76611: Loading Connection 'persistent' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/persistent.py
 18649 1485436253.76699: Loading ShellModule 'csh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/csh.py
 18649 1485436253.76725: Loading ShellModule 'fish' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/fish.py
 18649 1485436253.76761: Loading ShellModule 'powershell' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/powershell.py
 18649 1485436253.76779: Loading ShellModule 'sh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/sh.py
 18649 1485436253.76801: Loading ShellModule 'sh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 18649 1485436253.76814: in VariableManager get_vars()
 18649 1485436253.76854: done with get_vars()
 18649 1485436253.76894: Loading Connection 'local' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/local.py (found_in_cache=False, class_only=True)
 18649 1485436253.76946: Loading ActionModule 'normal' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/normal.py
 18649 1485436253.76976: starting attempt loop
 18649 1485436253.76985: running the handler
 18649 1485436253.77057: ANSIBALLZ: Using lock for setup
 18649 1485436253.77070: ANSIBALLZ: Acquiring lock
 18649 1485436253.77081: ANSIBALLZ: Lock acquired: 140034540219216
 18649 1485436253.77091: ANSIBALLZ: Creating module
 18649 1485436253.97140: ANSIBALLZ: Writing module
 18649 1485436253.97177: ANSIBALLZ: Renaming module
 18649 1485436253.97185: ANSIBALLZ: Done creating module
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/system/setup.py
 18649 1485436253.97250: _low_level_execute_command(): starting
 18649 1485436253.97255: _low_level_execute_command(): executing: /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485436253.97-157937486792640 `" && echo ansible-tmp-1485436253.97-157937486792640="` echo ~/.ansible/tmp/ansible-tmp-1485436253.97-157937486792640 `" ) && sleep 0'
 18649 1485436264.47684: _low_level_execute_command() done: rc=255, stdout=, stderr=failed to connect to the listener socket, connection timeout.  See syslog for more details
 18649 1485436264.47730: _execute() done
 18649 1485436264.47738: dumping result to json
 18649 1485436264.47747: done dumping result, returning
 18649 1485436264.47765: done running TaskExecutor() for x260/TASK: Gathering Facts
 18649 1485436264.47773: sending task result
 18649 1485436264.47843: done sending task result
 18649 1485436264.47851: WORKER PROCESS EXITING
 18641 1485436264.47951: in VariableManager get_vars()
 18641 1485436264.48013: done with get_vars()
fatal: [x260]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1485436253.97-157937486792640 `\" && echo ansible-tmp-1485436253.97-157937486792640=\"` echo ~/.ansible/tmp/ansible-tmp-1485436253.97-157937486792640 `\" ), exited with result 255", 
    "unreachable": true
}
 18641 1485436264.48054: no more pending results, returning what we have
 18641 1485436264.48060: results queue empty
 18641 1485436264.48064: checking for any_errors_fatal

```

```
Jan 26 13:10:54 x260 ansible-connection: message repeated 2 times: [ <x260> Traceback (most recent call last):#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 285, in main#012    server = Server(sf_path, pc)#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 122, in __init__#012    self.conn = connection_loader.get(play_context.connection, play_context, sys.stdin)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/__init__.py", line 356, in get#012    found_in_cache=found_in_cache, class_only=class_only)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/__init__.py", line 371, in _display_plugin_load#012    display.debug(msg)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/utils/display.py", line 173, in debug#012    self.display("%6d %0.5f: %s" % (os.getpid(]

```

**Comment by tumbl3w33d** [comment]
I just ran into the same error and bisected it to commit 10fa2cd0efcc6bd6634f261da79e66c2d9be1dc0 of @bcoca .
It only happens to some of my hosts though.

**Comment by gundalow** [comment]
Fixed by https://github.com/ansible/ansible/pull/20695
