### ISSUE TITLE
inline comment on hosts line causes traceback

### ISSUE THREAD

**Issue by nigelm** [ansible/ansible#2072]
Given a hosts line like this:-

  localhost  # this is the localhost

then ansible will bomb with the following traceback

Traceback (most recent call last):
  File "/Users/nigel/Work/ansible/ansible/bin/ansible", line 157, in <module>
    (runner, results) = cli.run(options, args)
  File "/Users/nigel/Work/ansible/ansible/bin/ansible", line 83, in run
    inventory_manager = inventory.Inventory(options.inventory)
  File "/Users/nigel/Work/ansible/ansible/lib/ansible/inventory/**init**.py", line 91, in **init**
    self.parser = InventoryParser(filename=host_list)
  File "/Users/nigel/Work/ansible/ansible/lib/ansible/inventory/ini.py", line 40, in **init**
    self._parse()
  File "/Users/nigel/Work/ansible/ansible/lib/ansible/inventory/ini.py", line 44, in _parse
    self._parse_base_groups()
  File "/Users/nigel/Work/ansible/ansible/lib/ansible/inventory/ini.py", line 112, in _parse_base_groups
    (k,v) = t.split("=")
ValueError: need more than 1 value to unpack

**Comment by nigelm** [comment]
Am working on this, will attach patch later

**Comment by nigelm** [comment]
See pull #2073 

https://github.com/ansible/ansible/pull/2073
