### ISSUE TITLE
Persistent Connections: Doesn't support ansible_connection=ssh or ansible_connection=paramiko_ssh

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#20748]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```

```

##### STEPS TO REPRODUCE
**Inventory**
```
localhost ansible_connection=ssh
```

Ensure no existing sockets exist (`rm -rf ~/.ansible/pc/`)
`ANSIBLE_USE_PERSISTENT_CONNECTIONS=True  ansible -vvv -i inventory.network-jobarker localhost  -m raw -a 'echo hello'

##### ACTUAL RESULTS
```
No config file found; using defaults
localhost | FAILED | rc=255 >>
failed to connect to the listener socket, connection timeout.  See syslog for more details

```

**Syslog**
```
Jan 27 11:41:03 x260 ansible-connection: <localhost> Traceback (most recent call last):#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 285, in main#012    server = Server(sf_path, pc)#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 125, in __init__#012    raise AnsibleConnectionFailure('unable to connect to remote host')#012AnsibleConnectionFailure: unable to connect to remote host
```

**Syslog when running with `ANSIBLE_DEBUG=TRUE`**
```
Jan 27 11:43:13 x260 ansible-connection: <localhost> Traceback (most recent call last):#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 285, in main#012    server = Server(sf_path, pc)#012  File "/home/johnb/git/ansible-inc/ansible/bin/ansible-connection", line 122, in __init__#012    self.conn = connection_loader.get(play_context.connection, play_context, sys.stdin)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/__init__.py", line 356, in get#012    found_in_cache=found_in_cache, class_only=class_only)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/__init__.py", line 371, in _display_plugin_load#012    display.debug(msg)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/utils/display.py", line 173, in debug#012    self.display("%6d %0.5f: %s" % (os.getpid(), time.time(), msg), color=C.COLOR_DEBUG)#012  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/utils/display.py", line 131, in display#012    fileobj.flush()#012IOError: [Errno 9] Bad file descriptor
```

**Comment by gundalow** [comment]
Same issue with `ansible_connection=paramiko_ssh`

**Comment by bcoca** [comment]
It overlaps with control persist

**Comment by gundalow** [comment]
Peter said this is something we can do for 2.4

**Comment by gundalow** [comment]
As discussed in the Network Team:
* This doesn't effect networking modules
* This would only effect Core modules
* Core modules already have ControlPersist

Unsure if their is a demand for this, so closing.
