### ISSUE TITLE
to_nice_yaml fails unexpectedly

### ISSUE THREAD

**Issue by conleym** [ansible/ansible#20885]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

ansible.cfg:

```
[defaults]
nocows = 1
retry_files_enabled = False
```

Environment:

```
ANSIBLE_RETRY_FILES_ENABLED=0
ANSIBLE_NOCOWS=1
```

##### OS / ENVIRONMENT

macOS 10.12.2

##### STEPS TO REPRODUCE

playbook.yml:

```yaml
---
- hosts: localhost
  gather_facts: no

  tasks:
    - command: "jq .Stuff foo.json"
      register: stuff

    - set_fact:
        stuff_json: "{{ stuff.stdout | from_json }}"

    - name: Write yaml
      copy:
        dest: "{{ playbook_dir }}/out.yaml"
        content: "{{ stuff_json | to_nice_yaml }}"
```

foo.json:

```json
{
  "Stuff": {
    "asdf": "jkl;"
  }
}
```

##### EXPECTED RESULTS

`out.yml` should contain 

```
asdf: jkl;
```

as it does with ansible 2.2.0.0.

##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: playbook.yml *********************************************************
1 plays in playbook.yml

PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
task path: /Users/mike/ansible-poop/playbook.yml:6
Using module file /Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/modules/core/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: mike
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477 `" && echo ansible-tmp-1485896212.65-113823495406477="` echo ~/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477 `" ) && sleep 0'
<localhost> PUT /var/folders/_r/5z5t3kln6yn8r3jgrbyvbb6r0000gn/T/tmp_ogWk2 TO /Users/mike/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/mike/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477/ /Users/mike/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477/command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/opt/local/bin/python /Users/mike/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477/command.py; rm -rf "/Users/mike/.ansible/tmp/ansible-tmp-1485896212.65-113823495406477/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "cmd": [
        "jq", 
        ".Stuff", 
        "foo.json"
    ], 
    "delta": "0:00:00.013267", 
    "end": "2017-01-31 14:56:52.838634", 
    "invocation": {
        "module_args": {
            "_raw_params": "jq .Stuff foo.json", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 0, 
    "start": "2017-01-31 14:56:52.825367", 
    "stderr": "", 
    "stdout": "{\n  \"asdf\": \"jkl;\"\n}", 
    "stdout_lines": [
        "{", 
        "  \"asdf\": \"jkl;\"", 
        "}"
    ], 
    "warnings": []
}

TASK [set_fact] ****************************************************************
task path: /Users/mike/ansible-poop/playbook.yml:9
ok: [localhost] => {
    "ansible_facts": {
        "stuff_json": {
            "asdf": "jkl;"
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "stuff_json": {
                "asdf": "jkl;"
            }
        }, 
        "module_name": "set_fact"
    }
}

TASK [Write yaml] **************************************************************
task path: /Users/mike/ansible-poop/playbook.yml:12
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/Users/mike/Library/Python/2.7/lib/python/site-packages/ansible/plugins/filter/core.py", line 79, in to_nice_yaml
    transformed = yaml.dump(a, Dumper=AnsibleDumper, indent=indent, allow_unicode=True, default_flow_style=False, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.py", line 225, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.py", line 122, in represent_mapping
    node_key = self.represent_data(item_key)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.py", line 249, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: asdf

fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```

**Comment by abadger** [comment]
Here's a single file way to reproduce this error:
```
$ cat 20885.yml                                                 (15:24:45)
---
- hosts: localhost
  gather_facts: False
  vars:
    stuff_string: '{ "asdf": "jkl;" }'
  tasks:
  - command: "echo '{{ stuff_string }}'"
    register: stuff

  - set_fact:
      stuff_json_bad: "{{ stuff.stdout | from_json }}"

  - set_fact:
      stuff_json_good: "{{ stuff_string | from_json }}"

  - debug:
      var=stuff_json_good
  - debug:
      var=stuff_json_bad

  - name: Write yaml (succeeds)
    copy:
      dest: "{{ playbook_dir }}/out_good.yaml"
      content: "{{ stuff_json_good | to_nice_yaml }}"
  - name: Write yaml (fails)
    copy:
      dest: "{{ playbook_dir }}/out_bad.yaml"
      content: "{{ stuff_json_bad | to_nice_yaml }}"
```

Assigning to @jimi-c as I think this is happening because of the security fixes.  If so, it may affect 2.1 as well.

**Comment by md5** [comment]
Is this the same issue that was fixed in https://github.com/ansible/ansible/commit/ec14572a60bd901bb52f80c2f0dbdaf1ada0eb8a? (cf. #20253, #20290)

**Comment by berlic** [comment]
As a temporary workaround I pipe broken object trough json:
`{{ broken_object | to_json | from_json | to_nice_yaml }}`

**Comment by jimi-c** [comment]
@berlic yes this is a dupe, so closing it now.
