### ISSUE TITLE
vmware_inventory pyVmomi.VmomiSupport.NoPermission

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#21051]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

[vmware_inventory](/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.py)

##### SUMMARY

```./vmware_inventory.py``` fails:

```
Traceback (most recent call last):
  File "./vmware_inventory.py", line 721, in <module>
    print(VMWareInventory().show())
  File "./vmware_inventory.py", line 134, in __init__
    self.do_api_calls_update_cache()
  File "./vmware_inventory.py", line 176, in do_api_calls_update_cache
    self.inventory = self.instances_to_inventory(self.get_instances())
  File "./vmware_inventory.py", line 329, in get_instances
    return self._get_instances(kwargs)
  File "./vmware_inventory.py", line 369, in _get_instances
    ifacts = self.facts_from_vobj(instance)
  File "./vmware_inventory.py", line 614, in facts_from_vobj
    inkey=method,
  File "./vmware_inventory.py", line 692, in _process_object_types
    level=(level + 1)
  File "./vmware_inventory.py", line 631, in _process_object_types
    rdata[key] = getattr(vobj, key)
  File "/home/user/vmware/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/home/user/vmware/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/user/vmware/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.HostSystem:host-66',
   privilegeId = 'System.View'
}
```

Not sure how to reproduce this as I've no idea what permissions are missed. But script shouldn't fail due to lack of permissions.

**Comment by alikins** [comment]
What ansible version?

**Comment by hryamzik** [comment]
Script is from latest devel, I didn't run it with ansible, just manually.

P.S.: this worked for me:

```python
        if vobj is None:
            rdata = None
        elif type(vobj) in self.vimTable:
            rdata = {}
            for key in self.vimTable[type(vobj)]:
                try:
                    rdata[key] = getattr(vobj, key)
                except Exception as e:
                    logging.error(e, exc_info=True)
```

**Comment by jctanner** [comment]
cc @dav1x @nerzhul

**Comment by jctanner** [comment]
@hryamzik seems like a logical patch. Would you be able to submit a pullrequest?

**Comment by hryamzik** [comment]
@jctanner sure, going to fire it tomorrow, I just wasn't sure it's fine. This script doesn't provide me with datacenters and VM folders so I've already moved from it.

**Comment by jctanner** [comment]
resolved_by_pr #21518

**Comment by nerzhul** [comment]
thanks, i missed i fixed an existing issue :)

**Comment by einarc** [comment]
Question: How do you escalate privileges to avoid this error getting triggered on the first place? I'm getting this from Tower 3.1.1

 ```
 1.350 INFO     Updating inventory 32: VMware Servers
    1.366 INFO     Reading executable JSON source: /var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py
   55.072 ERROR    Failed to load JSON from: 
Traceback (most recent call last):
  File "/usr/bin/tower-manage", line 9, in <module>
    load_entry_point('ansible-tower==3.1.1', 'console_scripts', 'tower-manage')()
  File "/lib/python2.7/site-packages/awx/__init__.py", line 105, in manage
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1290, in handle_noargs
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 503, in load_inventory_source
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 392, in load
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 380, in command_to_json
RuntimeError: ['/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py', '--list'] failed (rc=1) with output: Traceback (most recent call last):
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 721, in <module>
    print(VMWareInventory().show())
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 134, in __init__
    self.do_api_calls_update_cache()
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 176, in do_api_calls_update_cache
    self.inventory = self.instances_to_inventory(self.get_instances())
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 329, in get_instances
    return self._get_instances(kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 369, in _get_instances
    ifacts = self.facts_from_vobj(instance)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 614, in facts_from_vobj
    inkey=method,
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 692, in _process_object_types
    level=(level + 1)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 631, in _process_object_types
    rdata[key] = getattr(vobj, key)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.HostSystem:host-13271',
   privilegeId = 'System.View'
}
```

**Comment by einarc** [comment]
Found my answer, it's on the Vmware side:

https://github.com/vmware/pyvmomi/issues/513
