### ISSUE TITLE
UnicodeDecodeError with module copy

### ISSUE THREAD

**Issue by anayrat** [ansible/ansible#21151]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Copy module

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ansible server under python 2.7.9

Remote host under python 2.6.6

##### SUMMARY

I get this error with module copy for specifics files : 
```
...
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1306: invalid continuation byte
```

It seems it is the same bug : https://github.com/ansible/ansible-modules-core/issues/2213

##### ACTUAL RESULTS

```
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: foo
<1.2.3.4> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<1.2.3.4> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=4222)
<1.2.3.4> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<1.2.3.4> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=foo)
<1.2.3.4> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<1.2.3.4> SSH: PlayContext set ssh_common_args: ()
<1.2.3.4> SSH: PlayContext set ssh_extra_args: ()
<1.2.3.4> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/var/lib/naemon/.ansible/cp/ansible-ssh-%h-%p-%r)
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=4222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=foo -o ConnectTimeout=10 -o ControlPath=/var/lib/naemon/.ansible/cp/ansible-ssh-%h-%p-%r 1.2.3.4 '/bin/sh -c '"'"'rm -f -r /home/foo/.ansible/tmp/ansible-tmp-1486569469.22-223747772455270/ > /dev/null 2>&1 && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 147, in run
    res = _clean_res(res)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 140, in _clean_res
    res[k] = _clean_res(res[k])
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 143, in _clean_res
    res[idx] = _clean_res(item)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 140, in _clean_res
    res[k] = _clean_res(res[k])
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 137, in _clean_res
    return to_text(res, errors='surrogate_or_strict')
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/_text.py", line 177, in to_text
    return obj.decode(encoding, errors)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1306: invalid continuation byte

fatal: [support_bar_bar_c]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

Thanks for your help!

**Comment by anayrat** [comment]
It occurs with only one file :(

**Comment by anayrat** [comment]
I found the problem, an accent "é" on both local file and destination. The diff failed.

**Comment by abadger** [comment]
Can you give us a reproducer?  Is the é encoded in utf8 or in another encoding?  Is the é in the filename or as contents of the file?

**Comment by anayrat** [comment]
The "é" was in content. How can I check if it is encoded in utf8?

**Comment by abadger** [comment]
For file contents I usually uise the UNIX file utility:
```
$ file /var/tmp/mine
mine: UTF-8 Unicode text
```

Depending on the implementation of file, it might cheat and only read an initial chunk of data and then report a guess about the output based on that.

**Comment by abadger** [comment]
@anayrat Was this only happening when you were using ansible with --diff output?  If so, I think that it was probably fixed by this change last week: https://github.com/ansible/ansible/pull/21913  That fix is in the current devel branch (will be 2.3.0) and stbale-2.2 branches (I don't believe it made the release candidate but it may make it into 2.2.2.. depends on whether we need another release candidate or not).

needs_info

**Comment by anayrat** [comment]
Yes it was only with  --diff. I'll try with 2.2.2.
Thanks!

**Comment by abadger** [comment]
@anayrat, have you had a chance to check this?  I'll close it in a few days under the assumption that #21913 fixed this.

**Comment by anayrat** [comment]
I'm sorry, I wasn't able to check your fix. I close this issue, I'll reopen it if the problem occurs.

Thanks for your help.
