### ISSUE TITLE
cron module fails on subsequent runs with complex cron 

### ISSUE THREAD

**Issue by dorfsmay** [ansible/ansible#2125]
This cron task:

```
- name: cron job ansible-pull
  cron: name="run ansible-pull" minute='0' job='/export/run_ansible.bash >/tmp/ansible.out.\\$(date +"\\\%Y\\\%m\\\%d\\\%H\\\%M")-\\$(uname -n) 2>&1'
```

works the first time you run, it adds the right cron entry, but it fails on subsequent runs:

```
<felix> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO felix
<felix> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1361205708.79-63172452819348 && echo $HOME/.ansible/tmp/ansible-1361205708.79-63172452819348'
<felix> REMOTE_MODULE cron name="run ansible-pull" minute='0' job='/export/run_ansible.bash >/tmp/ansible.out.\$(date +"\\\%Y\\\%m\\\%d\\\%H\\\%M")-\$(uname -n) 2>&1'
<felix> PUT /tmp/tmpumlrMt TO /root/.ansible/tmp/ansible-1361205708.79-63172452819348/cron
<felix> EXEC /bin/sh -c ' /usr/bin/python /root/.ansible/tmp/ansible-1361205708.79-63172452819348/cron; rm -rf /root/.ansible/tmp/ansible-1361205708.79-63172452819348/ >/dev/null 2>&1'
fatal: [felix] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1361205708.79-63172452819348/cron", line 1115, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1361205708.79-63172452819348/cron", line 320, in main
    (rc, out, err) = update_job(name,job,tmpfile.name)
ValueError: too many values to unpack
```

The correct cron entry (which I obtain on the first run) is:

```
#Ansible: run ansible-pull
0 * * * * /export/run_ansible.bash >/tmp/ansible.out.$(date +\%Y\%m\%d\%H\%M)-$(uname -n) 2>&1
```

**Comment by mpdehaan** [comment]
ok, thanks for the report.  should be easy to chase.
