### ISSUE TITLE
commit 4cbe6102637eba5b70b70be582ef4bdaaaa910d5 breaks Ansible

### ISSUE THREAD

**Issue by jannooo** [ansible/ansible#21271]
```
root@ansible:/etc/ansible# ansible -v
ERROR! Unexpected Exception: cannot import name get_unique_id
the full traceback was:

Traceback (most recent call last):
  File "/opt/ansible/bin/ansible", line 80, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/opt/ansible/lib/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/opt/ansible/lib/ansible/executor/task_queue_manager.py", line 29, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/opt/ansible/lib/ansible/executor/play_iterator.py", line 28, in <module>
    from ansible.playbook.block import Block
  File "/opt/ansible/lib/ansible/playbook/__init__.py", line 27, in <module>
    from ansible.playbook.play import Play
  File "/opt/ansible/lib/ansible/playbook/play.py", line 28, in <module>
    from ansible.playbook.base import Base
  File "/opt/ansible/lib/ansible/playbook/base.py", line 34, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/opt/ansible/lib/ansible/parsing/dataloader.py", line 36, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/opt/ansible/lib/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/opt/ansible/lib/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.vars.unsafe_proxy import wrap_var
  File "/opt/ansible/lib/ansible/vars/__init__.py", line 39, in <module>
    from ansible.inventory.host import Host
  File "/opt/ansible/lib/ansible/inventory/__init__.py", line 34, in <module>
    from ansible.inventory.dir import InventoryDirectory, get_file_parser
  File "/opt/ansible/lib/ansible/inventory/dir.py", line 31, in <module>
    from ansible.inventory.ini import InventoryParser as InventoryINIParser
  File "/opt/ansible/lib/ansible/inventory/ini.py", line 27, in <module>
    from ansible.inventory.host import Host
  File "/opt/ansible/lib/ansible/inventory/host.py", line 23, in <module>
    from ansible.utils.vars import combine_vars, get_unique_id
ImportError: cannot import name get_unique_id
```

**Comment by thaumos** [comment]
@elsobrino,

I have that commit and Ansible works fine for me.

```netnavi:~/Development/ansible$ ansible --version
ansible 2.3.0 (devel cd6792a058) last updated 2017/02/10 16:08:10 (GMT -500)
  config file = /Users/dsilva/.ansible.cfg
  configured module search path = Default w/o overrides
netnavi:~/Development/ansible$ ansible localhost -m ping
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}```

**Comment by jannooo** [comment]
@thaumos,

yeah, issue seems to be fixed now.

```
ansible 2.3.0 (devel 65e32243b8) last updated 2017/02/11 21:39:05 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
