### ISSUE TITLE
setup module failes on freebsd

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#2137]
version 1.1 (commit 589548531eb5a77145cbb3e40f9a38760d51e2df) fails when invoking get_cpu_facts in setup module:

``` python
FAILED => failed to parse: Traceback (most recent call last):
  File "/home/bcoca/.ansible/tmp/ansible-1361315528.31-80069835288983/setup", line 1796, in <module>
    main()
  File "/home/bcoca/.ansible/tmp/ansible-1361315528.31-80069835288983/setup", line 1049, in main
    data = run_setup(module)
  File "/home/bcoca/.ansible/tmp/ansible-1361315528.31-80069835288983/setup", line 999, in run_setup
    facts = ansible_facts()
  File "/home/bcoca/.ansible/tmp/ansible-1361315528.31-80069835288983/setup", line 989, in ansible_facts
    facts.update(Hardware().populate())
  File "/home/bcoca/.ansible/tmp/ansible-1361315528.31-80069835288983/setup", line 530, in populate
    self.get_cpu_facts()
  File "/home/bcoca/.ansible/tmp/ansible-1361315528.31-80069835288983/setup", line 547, in get_cpu_facts
    for line in dmesg_boot.readlines():
AttributeError: 'str' object has no attribute 'readlines'
```

**Comment by bcoca** [comment]
this also affects fstab file in device function.

this mostly happens with jails in alternate code path, works normally on hardware (or those with dmesg and fstab files present).
