### ISSUE TITLE
Networking Modules: AttributeError: 'NoneType' object has no attribute 'expand_user'

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21402]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```

```

##### SUMMARY
```
    cmd = self._connection._shell.expand_user(expand_path)
AttributeError: 'NoneType' object has no attribute 'expand_user'
```

##### STEPS TO REPRODUCE
```
cd test/integration
time  ANSIBLE_DEBUG=True ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network-jobarker eos.yaml -u admin -k
```

```yaml
  - name: enable cli on remote device
     eos_eapi:
       enable_http: yes 
       enable_https: yes 
       enable_local_http: yes 
       enable_socket: yes 
       provider: "{{ cli }}"
     register: eos_eapi_output

```

##### ACTUAL RESULTS
```yaml
TASK [prepare_eos_tests : enable cli on remote device] *******************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/prepare_eos_tests/tasks/main.yml:1
 20181 1487074258.67302: sending task start callback
 20181 1487074258.67304: entering _queue_task() for veos01/eos_eapi
 20181 1487074258.67306: Creating lock for eos_eapi
 20181 1487074258.67398: worker is 1 (out of 1 available)
 20181 1487074258.67422: exiting _queue_task() for veos01/eos_eapi
 20181 1487074258.67473: done queuing things up, now waiting for results queue to drain
 20181 1487074258.67477: waiting for pending results...
 20188 1487074258.67773: running TaskExecutor() for veos01/TASK: prepare_eos_tests : enable cli on remote device
 20188 1487074258.67825: in run()
 20188 1487074258.67863: calling self._execute()
 20188 1487074258.68230: Loading FilterModule 'core' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/core.py
 20188 1487074258.69339: Loading FilterModule 'ipaddr' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/ipaddr.py
 20188 1487074258.69369: Loading FilterModule 'json_query' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/json_query.py
 20188 1487074258.69388: Loading FilterModule 'mathstuff' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/mathstuff.py
 20188 1487074258.69479: Loading TestModule 'core' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/test/core.py
 20188 1487074258.69496: Loading TestModule 'files' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/test/files.py
 20188 1487074258.69512: Loading TestModule 'mathstuff' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/test/mathstuff.py
 20188 1487074258.71000: Loading FilterModule 'core' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/core.py (found_in_cache=True, class_only=False)
 20188 1487074258.71008: Loading FilterModule 'ipaddr' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/ipaddr.py (found_in_cache=True, class_only=False)
 20188 1487074258.71012: Loading FilterModule 'json_query' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/json_query.py (found_in_cache=True, class_only=False)
 20188 1487074258.71015: Loading FilterModule 'mathstuff' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/filter/mathstuff.py (found_in_cache=True, class_only=False)
 20188 1487074258.71029: Loading TestModule 'core' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/test/core.py (found_in_cache=True, class_only=False)
 20188 1487074258.71033: Loading TestModule 'files' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/test/files.py (found_in_cache=True, class_only=False)
 20188 1487074258.71035: Loading TestModule 'mathstuff' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/test/mathstuff.py (found_in_cache=True, class_only=False)
 20188 1487074258.75930: Loading Connection 'network_cli' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/network_cli.py
 20188 1487074258.76022: Loading ShellModule 'csh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/csh.py
 20188 1487074258.76048: Loading ShellModule 'fish' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/fish.py
 20188 1487074258.76084: Loading ShellModule 'powershell' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/powershell.py
 20188 1487074258.76103: Loading ShellModule 'sh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/sh.py
 20188 1487074258.76128: Loading ShellModule 'sh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 20188 1487074258.76139: in VariableManager get_vars()
 20188 1487074258.76165: done with get_vars()
 20188 1487074258.76423: Loading ActionModule 'eos' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/eos.py
 20188 1487074258.76442: starting attempt loop
 20188 1487074258.76447: running the handler
 20188 1487074258.76980: Loading Connection 'ssh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/ssh.py (found_in_cache=False, class_only=True)
 20188 1487074258.77131: Loading Connection 'persistent' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/persistent.py
 20188 1487074258.77190: Loading ShellModule 'csh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/csh.py (found_in_cache=True, class_only=False)
 20188 1487074258.77201: Loading ShellModule 'fish' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/fish.py (found_in_cache=True, class_only=False)
 20188 1487074258.77205: Loading ShellModule 'powershell' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/powershell.py (found_in_cache=True, class_only=False)
 20188 1487074258.77209: Loading ShellModule 'sh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 20188 1487074258.77213: Loading ShellModule 'sh' from /home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 20188 1487074269.19332: ANSIBALLZ: Using lock for eos_eapi
 20188 1487074269.19341: ANSIBALLZ: Acquiring lock
 20188 1487074269.19347: ANSIBALLZ: Lock acquired: 139624245050704
 20188 1487074269.19351: ANSIBALLZ: Creating module
 20188 1487074269.31359: ANSIBALLZ: Writing module
 20188 1487074269.31395: ANSIBALLZ: Renaming module
 20188 1487074269.31400: ANSIBALLZ: Done creating module
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/network/eos/eos_eapi.py
<veos01> closing connection
 20188 1487074269.31540: done running TaskExecutor() for veos01/TASK: prepare_eos_tests : enable cli on remote device
 20188 1487074269.31544: sending task result
 20188 1487074269.31581: done sending task result
 20188 1487074269.31596: WORKER PROCESS EXITING
 20181 1487074269.31623: in VariableManager get_vars()
 20181 1487074269.31689: done with get_vars()
 20181 1487074269.31703: marking veos01 as failed
 20181 1487074269.31709: marking host veos01 failed, current state: HOST STATE: block=2, task=1, rescue=0, always=0, run_state=ITERATING_TASKS, fail_state=FAILED_NONE, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
 20181 1487074269.31714: ^ failed state is now: HOST STATE: block=2, task=1, rescue=0, always=0, run_state=ITERATING_COMPLETE, fail_state=FAILED_TASKS, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
 20181 1487074269.31719: getting the next task for host veos01
 20181 1487074269.31722: host veos01 is done iterating, returning
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/executor/task_executor.py", line 504, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/eos.py", line 77, in run
    return super(ActionModule, self).run(tmp, task_vars)
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/normal.py", line 42, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=self._task.async))
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/__init__.py", line 622, in _execute_module
    tmp = self._make_tmp_path()
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/__init__.py", line 237, in _make_tmp_path
    tmpdir =  self._remote_expand_user(C.DEFAULT_REMOTE_TMP, sudoable=False)
  File "/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/action/__init__.py", line 533, in _remote_expand_user
    cmd = self._connection._shell.expand_user(expand_path)
AttributeError: 'NoneType' object has no attribute 'expand_user'

fatal: [veos01]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
 20181 1487074269.31750: no more pending results, returning what we have

```

**Comment by gundalow** [comment]
Confirmed fixed, though we now fail with https://github.com/ansible/ansible/issues/21422
