### ISSUE TITLE
ansible web-servers -m setup -a "http_port=8080" -u username

### ISSUE THREAD

**Issue by cocoy** [ansible/ansible#216]
hpcloud-a | FAILED => Traceback (most recent call last):

  File "/Users/cocoy/fromLinux/github/ansible/lib/ansible/runner.py", line 537, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/Users/cocoy/fromLinux/github/ansible/lib/ansible/runner.py", line 576, in _executor_internal
    result = self._execute_normal_module(conn, host, tmp, module_name)
  File "/Users/cocoy/fromLinux/github/ansible/lib/ansible/runner.py", line 351, in _execute_normal_module
    self._add_result_to_setup_cache(conn, result)
  File "/Users/cocoy/fromLinux/github/ansible/lib/ansible/runner.py", line 324, in _add_result_to_setup_cache
    var_result = result['ansible_facts']
TypeError: string indices must be integers, not str

--btw, this is using Ubuntu Oneiric, passwordless login and ansible/devel branch

**Comment by jhoekx** [comment]
I can reproduce this. As I broke it, I will fix it.

**Comment by jhoekx** [comment]
Turns out I didn't break it :-) But that did not keep me from fixing it.
