### ISSUE TITLE
Custom Ansible module fails in RHEL

### ISSUE THREAD

**Issue by senthil-t** [ansible/ansible#21707]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- module_common.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 5c36bd6714) last updated 2017/01/03 18:04:14 (GMT +550)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/senthil/ansible/lib']

i also have tried installing ansible 2.2.0, but the issue still persists.
```

##### OS / ENVIRONMENT

RHEL

##### SUMMARY

any ansible custome module fails with error "Unexpected failure during module execution.".

##### STEPS TO REPRODUCE

```yaml
- hosts: perry
  roles:
    - mx_persistance_service

```

##### ACTUAL RESULTS

[root@RHEL-64bit mx_service]# ansible-playbook persistence_mxservice.yml 

PLAY [perry] *******************************************************************

TASK [Gathering Facts] *********************************************************
 [WARNING]: Module invocation had junk after the JSON data:  STN39 Session
terminated - application closed terminal        02/21 16:04

ok: [perry.in.rdlabs.hpecorp.net]

TASK [mx_persistance_service : configure persistence mx service] ***************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [perry.in.rdlabs.hpecorp.net]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
	to retry, use: --limit @/root/senthil/mx_service/persistence_mxservice.retry

PLAY RECAP *********************************************************************
perry.in.rdlabs.hpecorp.net : ok=1    changed=0    unreachable=0    failed=1   

[root@RHEL-64bit mx_service]# 

```
TASK [mx_persistance_service : configure persistence mx service] ***************
task path: /root/senthil/mx_service/roles/mx_persistance_service/tasks/main.yml:5
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/senthil/ansible/lib/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/root/senthil/ansible/lib/ansible/executor/task_executor.py", line 504, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/senthil/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/root/senthil/ansible/lib/ansible/plugins/action/__init__.py", line 578, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/root/senthil/ansible/lib/ansible/plugins/action/__init__.py", line 152, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/root/senthil/ansible/lib/ansible/executor/module_common.py", line 785, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/root/senthil/ansible/lib/ansible/executor/module_common.py", line 646, in _find_snippet_imports
    recursive_finder(module_name, module_data, py_module_names, py_module_cache, zf)
  File "/root/senthil/ansible/lib/ansible/executor/module_common.py", line 447, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib64/python2.6/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    
   ^
SyntaxError: invalid syntax

fatal: [perry.in.rdlabs.hpecorp.net]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/root/senthil/mx_service/persistence_mxservice.retry

PLAY RECAP *********************************************************************
perry.in.rdlabs.hpecorp.net : ok=1    changed=0    unreachable=0    failed=1   


```

**Comment by ryansb** [comment]
This appears to be a problem in the module you're using, which is not an Ansible module. You can try running your module independently in Python, to see if the problem is something in the module. Can you please post a reproducing custom module and playbook?

**Comment by senthil-t** [comment]
Thanks for your response, Here is the reproducer:

test_play.yml
```yaml
---
- hosts: localhost
  tasks:
    - name: Test that my module works
      test_module: 
      register: result

    - debug: var=result 
```
test_module.py ( which is placed under library folder)
```
#!/usr/bin/python

from ansible.module_utils.basic import *

def main():

    module = AnsibleModule(argument_spec={})
    response = {"hello": "world"}
    module.exit_json(changed=False, meta=response)


if __name__ == '__main__':  
    main()
```
========== run output =========
```
[root@RHEL-64bit custom]# ansible-playbook test_play.yml -vvv
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test_play.yml ********************************************************
1 plays in test_play.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
Using module file /root/senthil/ansible/lib/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/senthil/ansible-tmp-1487744887.57-280102249365687 `" && echo ansible-tmp-1487744887.57-280102249365687="` echo /tmp/senthil/ansible-tmp-1487744887.57-280102249365687 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp94_ow0 TO /tmp/senthil/ansible-tmp-1487744887.57-280102249365687/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/senthil/ansible-tmp-1487744887.57-280102249365687/ /tmp/senthil/ansible-tmp-1487744887.57-280102249365687/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /tmp/senthil/ansible-tmp-1487744887.57-280102249365687/setup.py; rm -rf "/tmp/senthil/ansible-tmp-1487744887.57-280102249365687/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Test that my module works] ***********************************************
task path: /root/senthil/custom/test_play.yml:3
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/senthil/ansible/lib/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/root/senthil/ansible/lib/ansible/executor/task_executor.py", line 504, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/senthil/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/root/senthil/ansible/lib/ansible/plugins/action/__init__.py", line 578, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/root/senthil/ansible/lib/ansible/plugins/action/__init__.py", line 152, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/root/senthil/ansible/lib/ansible/executor/module_common.py", line 785, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/root/senthil/ansible/lib/ansible/executor/module_common.py", line 646, in _find_snippet_imports
    recursive_finder(module_name, module_data, py_module_names, py_module_cache, zf)
  File "/root/senthil/ansible/lib/ansible/executor/module_common.py", line 447, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib64/python2.6/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    
   ^
SyntaxError: invalid syntax

fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/root/senthil/custom/test_play.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

[root@RHEL-64bit custom
```

**Comment by senthil-t** [comment]
Also, here is the run output for the same module on windows/cygwin:
```
senthilt@SENTHILT3 ~/custom_module
$ ansible-playbook test_play.yml -vvv
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test_play.yml ********************************************************

1 plays in test_play.yml

PLAY [localhost] ***************************************************************


TASK [Gathering Facts] *********************************************************

Using module file /opt/ansible/lib/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: senthilt
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/senthil/ansible
-tmp-1487745975.23-46219891981264 `" && echo ansible-tmp-1487745975.23-462198919
81264="` echo /tmp/senthil/ansible-tmp-1487745975.23-46219891981264 `" ) && slee
p 0'
<127.0.0.1> PUT /tmp/tmp3lJ0IE TO /tmp/senthil/ansible-tmp-1487745975.23-4621989
1981264/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/senthil/ansible-tmp-1487745975.23-46
219891981264/ /tmp/senthil/ansible-tmp-1487745975.23-46219891981264/setup.py &&
sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /tmp/senthil/ansible-tmp-1487745975
.23-46219891981264/setup.py; rm -rf "/tmp/senthil/ansible-tmp-1487745975.23-4621
9891981264/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Test that my module works] ***********************************************

task path: /home/senthilt/custom_module/test_play.yml:3
Using module file /home/senthilt/custom_module/library/test_module.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: senthilt
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/senthil/ansible
-tmp-1487745979.8-58419428546363 `" && echo ansible-tmp-1487745979.8-58419428546
363="` echo /tmp/senthil/ansible-tmp-1487745979.8-58419428546363 `" ) && sleep 0
'
<127.0.0.1> PUT /tmp/tmpH9EpOY TO /tmp/senthil/ansible-tmp-1487745979.8-58419428
546363/test_module.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/senthil/ansible-tmp-1487745979.8-584
19428546363/ /tmp/senthil/ansible-tmp-1487745979.8-58419428546363/test_module.py
 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /tmp/senthil/ansible-tmp-1487745979
.8-58419428546363/test_module.py; rm -rf "/tmp/senthil/ansible-tmp-1487745979.8-
58419428546363/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {},
        "module_name": "test_module"
    },
    "meta": {
        "hello": "world"
    }
}

TASK [debug] *******************************************************************

task path: /home/senthilt/custom_module/test_play.yml:7
ok: [localhost] => {
    "result": {
        "changed": false,
        "meta": {
            "hello": "world"
        }
    }
}

PLAY RECAP *********************************************************************

localhost                  : ok=3    changed=0    unreachable=0    failed=0

```

**Comment by onurbrc** [comment]
Hi guys, 

I'm having the same problem trying to execute send tmsh commands to the devices. 

```
fatal: [F5-03]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 502, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.6/site-packages/ansible/plugins/action/__init__.py", line 572, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args                                                                                                                          =module_args, task_vars=task_vars)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/action/__init__.py", line 153, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/lib/python2.6/site-packages/ansible/executor/module_common.py", line 796, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args                                                                                                                          , task_vars, module_compression)
  File "/usr/lib/python2.6/site-packages/ansible/executor/module_common.py", line 657, in _find_snippet_imports
    recursive_finder(module_name, module_data, py_module_names, py_module_cache, zf)
  File "/usr/lib/python2.6/site-packages/ansible/executor/module_common.py", line 458, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib64/python2.6/ast.py", line 37, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 20

   ^
SyntaxError: invalid syntax

fatal: [F5-04]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
Do you have more information about bigip_command ?
Thanks.
Best regards.

**Comment by Akasurde** [comment]
@senthil-t @onurbrc There is syntax error in module code, this can be due to usage of mixed tabs and spaces or Windows carriage return characters. 
I have raised #49590 to handle traceback and provide useful information to user about such errors. 

Let me know if it works for you. Thanks.

needs_info
