### ISSUE TITLE
vsphere_guest - Add the ability to use an actual vSphere Template when defining template_src

### ISSUE THREAD

**Issue by McBadass** [ansible/ansible#21958]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
cloud/vmware/vsphere_guest

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel a284c3f7ea) last updated 2017/02/25 17:16:01 (GMT -600)
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.10

##### SUMMARY
When defining template_src within vsphere_guest, Ansible is expecting a vm object, not a template object.  If a template is specified, the task fails.  It would be nice to be able to speicify an actual template within vsphere.

The code in question can be found [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vsphere_guest.py#L660).

##### STEPS TO REPRODUCE

Create a vsphere_guest task and specify a vsphere template object instead of a vm to clone from.

```yaml
---
# Deploy vm from template

- name: Create VM
  vsphere_guest:
    validate_certs: no
    vcenter_hostname: "{{ global_vm_vcenter_hostname }}"
    username: "{{ global_vm_vsphere_username }}"
    password: "{{ global_vm_vsphere_user_password }}"
    guest: "{{ global_vm_name }}"
    from_template: yes
    template_src: "{{ global_vm_template }}"
    esxi:
      datacenter: "{{ global_vm_datacenter }}"
      hostname: "{{ global_vm_esxi_host }}"
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd: yes
      notes: Built by ansible and packer
      isolation.tools.copy.disable: false
      isolation.tools.paste.disable: false
    vm_hardware:
      memory_mb: "{{ global_vm_memory_mb }}"
      num_cpus: "{{ global_vm_cpu }}"

```

##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fU8Zb_/ansible_module_vsphere_guest.py", line 1917, in <module>
    main()
  File "/tmp/ansible_fU8Zb_/ansible_module_vsphere_guest.py", line 1874, in main
    vm_extra_config=vm_extra_config
  File "/tmp/ansible_fU8Zb_/ansible_module_vsphere_guest.py", line 661, in deploy_template
    vmTemplate = vsphere_client.get_vm_by_name(template_src)
  File "/usr/local/lib/python2.7/dist-packages/pysphere/vi_server.py", line 323, in get_vm_by_name
    FaultTypes.OBJECT_NOT_FOUND)
pysphere.resources.vi_exception.VIException: [Object Not Found]: Could not find a VM named 'packer-server-2016'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_fU8Zb_/ansible_module_vsphere_guest.py\", line 1917, in <module>\n
  main()\n  File \"/tmp/ansible_fU8Zb_/ansible_module_vsphere_guest.py\", line 1874, in main\n    vm_extra_config=vm_extra_config\n  File \"/tmp/ans
ible_fU8Zb_/ansible_module_vsphere_guest.py\", line 661, in deploy_template\n    vmTemplate = vsphere_client.get_vm_by_name(template_src)\n  File \"
/usr/local/lib/python2.7/dist-packages/pysphere/vi_server.py\", line 323, in get_vm_by_name\n    FaultTypes.OBJECT_NOT_FOUND)\npysphere.resources.vi
_exception.VIException: [Object Not Found]: Could not find a VM named 'packer-server-2016'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by McBadass** [comment]
I just realized this has been resolved by switching to vmware_guest instead of using vsphere_guest.  Apologies.  Closing.
