### ISSUE TITLE
Please asist me in find the issue for cloning ansible galaxy roles 

### ISSUE THREAD

**Issue by anuragdevops** [ansible/ansible#21999]
[ivmgr@rltv0171 stadm01: ansible-galaxy install git+https://as555y@codecloud.web.att.com/scm/st_ipa/ipa_galaxy_roles.git,master --roles-path=/opt/app/ipa/roles -vvv --force
Using /opt/app/ipa/ansible.cfg as config file
Opened /home/ivmgr/.ansible_galaxy
Installing role ipa_galaxy_roles
Password for 'https://as555y@codecloud.web.att.com':
- extracting ipa_galaxy_roles to /opt/app/ipa/roles/ipa_galaxy_roles
ERROR! Unexpected Exception: [Errno 2] No such file or directory: u'/opt/app/ipa/roles/ipa_galaxy_roles/meta/.galaxy_install_info'
the full traceback was:

Traceback (most recent call last):
  File "/opt/app/anaconda2/python27/lib/python2.7/site-packages/ansible-2.2.0.0-py2.7.egg/EGG-INFO/scripts/ansible-galaxy", line 103, in <module>
    exit_code = cli.run()
  File "/opt/app/anaconda2/python27/lib/python2.7/site-packages/ansible-2.2.0.0-py2.7.egg/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/opt/app/anaconda2/python27/lib/python2.7/site-packages/ansible-2.2.0.0-py2.7.egg/ansible/cli/__init__.py", line 145, in execute
    fn()
  File "/opt/app/anaconda2/python27/lib/python2.7/site-packages/ansible-2.2.0.0-py2.7.egg/ansible/cli/galaxy.py", line 396, in execute_install
    installed = role.install()
  File "/opt/app/anaconda2/python27/lib/python2.7/site-packages/ansible-2.2.0.0-py2.7.egg/ansible/galaxy/role.py", line 298, in install
    self._write_galaxy_install_info()
  File "/opt/app/anaconda2/python27/lib/python2.7/site-packages/ansible-2.2.0.0-py2.7.egg/ansible/galaxy/role.py", line 140, in _write_galaxy_install_info
    with open(info_path, 'w+') as f:
IOError: [Errno 2] No such file or directory: u'/opt/app/ipa/roles/ipa_galaxy_roles/meta/.galaxy_install_info'
[ivmgr@rltv0171 stadm01:

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
