### ISSUE TITLE
copy module fails with TypeError: expected string or buffer

### ISSUE THREAD

**Issue by mattwk** [ansible/ansible#2217]
ansible 1.1 (devel 0342b054fd) last updated 2013/02/27 13:11:33 (GMT -400)

From a playbook using ansible-playbook:

failed: [app-8] => (item=../pkgs/centrifydc-adbindproxy-4.5.4-deb5-x86_64.deb) => {"failed": true, "item": "../pkgs/centrifydc-adbindproxy-4.5.4-deb5-x86_64.deb", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1361989984.32-100665875707135/file", line 1093, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1361989984.32-100665875707135/file", line 147, in main
    supports_check_mode=True
  File "/root/.ansible/tmp/ansible-1361989984.32-100665875707135/file", line 419, in **init**
    (self.params, self.args) = self._load_params()
  File "/root/.ansible/tmp/ansible-1361989984.32-100665875707135/file", line 872, in _load_params
    params2 = json.loads(MODULE_COMPLEX_ARGS)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

also fails with cmdline: ansible app-8 -m copy -a "src=../pkgs/memcache_3.0.7-1_amd64.deb dest=/root/pkgs/"

**Comment by dhozac** [comment]
Fixed by cedfec763a6f84fc34a44eec65dba36897036a38. Thanks for the report!
