### ISSUE TITLE
run_command() produces TypeError when being fed a boolean in args

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#22190]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module_utils.basic.run_command()

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.2 (Maipo)

##### SUMMARY
I'm using the run_command module and in the argument I've to include booleans since the command I'm calling uses those to declare if the user for example is a manager. When I execute the module it produces a TypeError.

##### STEPS TO REPRODUCE
Create a module called test with the following content and run it. Using "use_unsafe_shell=True" produces the same error.
```python
from ansible.module_utils.basic import AnsibleModule

def main():
    module = AnsibleModule(
        argument_spec=dict(
            manager=dict(required=False, default=False, type='bool'),
        )
    )
    module.run_command(['echo', module.params['manager']])
```
```yaml
---
- hosts: localhost
  connection: local
  become: false

  tasks:
  - name: testing warning
    test:
```

##### EXPECTED RESULTS
Execution of the given command with the given values.

##### ACTUAL RESULTS
Results without use_unsafe_shell
```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: local.yml ************************************************************
1 plays in local.yml

PLAY [localhost] ***************************************************************

TASK [testing warning] *********************************************************
task path: /var/lib/mih_ansible/local.yml:7
Using module file /srv/ansible/git/library/test.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mih_ansible
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033 `" && echo ansible-tmp-1488454518.85-136887066138033="` echo ~/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpCW4ulK TO /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033/test.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033/ /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033/test.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033/test.py; rm -rf "/var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454518.85-136887066138033/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_dBN8ry/ansible_module_test.py", line 13, in <module>
    main()
  File "/tmp/ansible_dBN8ry/ansible_module_test.py", line 10, in main
    module.run_command(['echo', module.params['manager']])
  File "/tmp/ansible_dBN8ry/ansible_modlib.zip/ansible/module_utils/basic.py", line 2116, in run_command
  File "/usr/lib64/python2.7/posixpath.py", line 293, in expandvars
    if '$' not in path:
TypeError: argument of type 'bool' is not iterable

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "test"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_dBN8ry/ansible_module_test.py\", line 13, in <module>\n    main()\n  File \"/tmp/ansible_dBN8ry/ansible_module_test.py\", line 10, in main\n    module.run_command(['echo', module.params['manager']])\n  File \"/tmp/ansible_dBN8ry/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2116, in run_command\n  File \"/usr/lib64/python2.7/posixpath.py\", line 293, in expandvars\n    if '$' not in path:\nTypeError: argument of type 'bool' is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

Results with use_unsafe_shell=True
```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: local.yml ************************************************************
1 plays in local.yml

PLAY [localhost] ***************************************************************

TASK [testing warning] *********************************************************
task path: /var/lib/mih_ansible/local.yml:7
Using module file /srv/ansible/git/library/test.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mih_ansible
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537 `" && echo ansible-tmp-1488454681.95-69074041283537="` echo ~/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpCLbXAZ TO /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537/test.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537/ /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537/test.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537/test.py; rm -rf "/var/lib/mih_ansible/.ansible/tmp/ansible-tmp-1488454681.95-69074041283537/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_e2eJHg/ansible_module_test.py", line 13, in <module>
    main()
  File "/tmp/ansible_e2eJHg/ansible_module_test.py", line 10, in main
    module.run_command(['echo', module.params['manager']], use_unsafe_shell=True)
  File "/tmp/ansible_e2eJHg/ansible_modlib.zip/ansible/module_utils/basic.py", line 2086, in run_command
  File "/usr/lib64/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'bool' object is not iterable

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "test"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_e2eJHg/ansible_module_test.py\", line 13, in <module>\n    main()\n  File \"/tmp/ansible_e2eJHg/ansible_module_test.py\", line 10, in main\n    module.run_command(['echo', module.params['manager']], use_unsafe_shell=True)\n  File \"/tmp/ansible_e2eJHg/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2086, in run_command\n  File \"/usr/lib64/python2.7/pipes.py\", line 269, in quote\n    for c in file:\nTypeError: 'bool' object is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by sivel** [comment]
run_command only supports being passed strings or a list of strings.  You will have to cast all of your values to strings before passing them in to run_command.

Such as:

```
module.run_command(['echo', str(module.params['manager'])])
```

**Comment by rcarrillocruz** [comment]
not_a_bug

**Comment by ghost** [comment]
I'm transforming them now to strings indeed but it felt a bit "dirty" hence the issue. I'll close it then.

Thanks
