### ISSUE TITLE
I cant' start tomcat with ansible

### ISSUE THREAD

**Issue by Haitianisgood** [ansible/ansible#22351]
centos 6
ansible 2.2.1.0
tomcat:  8.0.15.0
jdk:1.8.0_112

All  executor are root

My shell files "start_stop.sh ,deploy.sh"

start_stop.sh:
```
#!/bin/bash
set -e

#PATH
export PATH=/opt/java/jdk1.8.0_112/bin/:/opt/java/jdk1.8.0_112/jre/bin:/opt/java/jdk1.8.0_112:$PATH

export JAVA_HOME=/opt/java/jdk1.8.0_112
export CATALINA_HOME=/data/server/tomcat8-card-ocr-8015
export JRE_HOME=/opt/java/jdk1.8.0_112/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH


function start_server()
{
    #start project server
    su - root -c /data/server/tomcat8-card-ocr-8015/bin/startup.sh    
    sleep 2
    #Determine whether the program start success
    Pid=$(ps aux|grep tomcat8-card-ocr-8015|grep -v grep |awk '{print $2}')
    if [ ! -n "$Pid" ];then
        echo  "Project server start error!"
        return 1
    else
        echo  "Project server start success!"
        return 0
}

function stop_server()
{
    #stop project server
    su - root -c /data/server/tomcat8-card-ocr-8015/bin/shutdown.sh 

    sleep 10

    #Determine whether the program stop success
    Pid=$(ps aux|grep tomcat8-card-ocr-8015|grep -v grep |awk '{print $2}')
    if [ ! -n "$Pid" ];then
        echo  "Project server stop success!" 
    else
        echo  "Project server stop failed!"
        for i in $Pid;do
            kill -9 $i
        done
    fi  
}

```
deploy.sh:

```
#!/bin/bash

 set -e
#Load dependent files
source ./start_stop.sh
#PATH
export PATH=/opt/java/jdk1.8.0_112/bin/:/opt/java/jdk1.8.0_112/jre/bin:/opt/java/jdk1.8.0_112:$PATH

function deploy()
{
  stop_server     
  start_server
  
}

function main()
{
    deploy
}
main
```

I can execute  deploy.sh on remote server to start tomcat!
but  I can't start tomcat with ansible 

ansible ERROR:
```
na.startup.Catalina stopServer
SEVERE: Could not contact localhost:8006. Tomcat may not be running.
Mar 07, 2017 3:45:47 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: Catalina.stop: 
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:450)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:400)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:487)
```
Note: I have changed my tomcat shutdown port to 8006

tomcat's  catalina.out   ERROR:

```
07-Mar-2017 15:46:02.128 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8015"]
07-Mar-2017 15:46:02.134 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8010"]
07-Mar-2017 15:46:02.135 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 3496 ms
07-Mar-2017 15:46:05.925 INFO [Thread-6] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8015"]
07-Mar-2017 15:46:05.979 INFO [Thread-6] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8010"]
07-Mar-2017 15:46:06.029 INFO [Thread-6] org.apache.catalina.core.StandardService.stopInternal Stopping service Catalina
07-Mar-2017 15:46:06.032 INFO [localhost-startStop-1] org.springframework.web.context.support.XmlWebApplicationContext.doClose Closing WebApplicationContext for namespace 'springmvc-servlet': startup date [Tue Mar 07 15:46:01 CST 2017]; parent: Root WebApplicationContext
07-Mar-2017 15:46:06.039 INFO [localhost-startStop-1] org.springframework.web.context.support.XmlWebApplicationContext.doClose Closing Root WebApplicationContext: startup date [Tue Mar 07 15:46:00 CST 2017]; root of context hierarchy
07-Mar-2017 15:46:06.044 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.PlainSocketImpl.socketAccept(Native Method)
 java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
 java.net.ServerSocket.implAccept(ServerSocket.java:545)
 java.net.ServerSocket.accept(ServerSocket.java:513)
mobile.socket.OcrSocketServer.run(OcrSocketServer.java:53)
07-Mar-2017 15:46:06.064 INFO [Thread-6] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8015"]
07-Mar-2017 15:46:06.065 INFO [Thread-6] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-8010"]
07-Mar-2017 15:46:06.067 INFO [Thread-6] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8015"]
07-Mar-2017 15:46:06.067 INFO [Thread-6] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8010"]
```

How can I solve this problem????

Thanks !!!!

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by Haitianisgood** [comment]
Hi,
 Sorry, I cant post on  https://groups.google.com/forum/#!forum/ansible-project.Because I am in China!
  Thanks!!!





At 2017-03-08 19:36:11, "jhawkesworth" <notifications@github.com> wrote:

List Information

Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by jhawkesworth** [comment]
Sorry to hear that you are not able to use the groups site.

Can I suggest that you search on ansible galaxy for tomcat roles - I think lots of people have already solved how to run tomcat.
This link will take you to the various tomcat roles that people have already shared via galaxy

 https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=tomcat

Hope this helps.

Jon

**Comment by gundalow** [comment]
https://groups.google.com/forum/#!topic/Ansible-project/wf-UOtPOuKk has some links in (which I know you can't access)

The relevant bits seem to be
* https://github.com/ansible/ansible-examples/blob/master/tomcat-standalone/roles/tomcat/files/tomcat-initscript.sh

**Comment by gundalow** [comment]
If you continue to have issues I'd suggest `#ansible` on Freenode IRC

**Comment by Haitianisgood** [comment]
I have sold this issues via set  liking in my shell 
```
#!/bin/bash 
set -m 
```
