### ISSUE TITLE
Ansible crash when file contain iso8859-15 with diff option: unknown error handler name 'surrogate_then_replace'

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#22436]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible copy/template with diff support (original issue here: https://github.com/ansible/ansible/issues/21803)

##### ANSIBLE VERSION
```ansible 2.2.2.0```

##### CONFIGURATION

Nothing special. I'm using the following playbook: https://github.com/Yannig/yannig-ansible-playbooks/tree/master/diff-iso8859-15

##### OS / ENVIRONMENT

Nothing special (crash with debian or RHEL)

##### SUMMARY

When using diff option with iso8859-15 file (with copy or template module), Ansible is crashing. The problem have been fixed in devel but the backport in 2.2 introduce a new crash.

##### STEPS TO REPRODUCE
You can retrieve a playbook example at the following location: https://github.com/Yannig/yannig-ansible-playbooks/tree/master/diff-iso8859-15

```yaml
- name: "Crash when using --diff option"
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: "Copy a dummy iso8859-15 file"
      copy: src=iso8859-15.txt dest=/tmp/test.txt
    - name: "Template over dummy file without iso8859-15 (crash with --diff)"
      template: src=utf8.txt.j2 dest=/tmp/test.txt
```

```ansible-playbook crash-diff.yml --diff```

##### EXPECTED RESULTS

```
PLAY [Crash when using --diff option] ***********************************************************************************************************

TASK [Copy a dummy iso8859-15 file] *************************************************************************************************************
--- before: /tmp/test.txt
+++ after: /home/drayan/dev/yannig-ansible-playbooks/diff-iso8859-15/iso8859-15.txt
@@ -1,3 +1,3 @@
-Un super fichier avec é en iso8859-15
+Un super fichier avec � en iso8859-15
 
-A super file with é in iso8859-15
+A super file with � in iso8859-15

changed: [localhost]

TASK [Template over dummy file without iso8859-15 (crash with --diff)] **************************************************************************
--- before: /tmp/test.txt
+++ after: dynamically generated
@@ -1,3 +1,3 @@
-Un super fichier avec � en iso8859-15
+Un super fichier avec é en iso8859-15
 
-A super file with � in iso8859-15
+A super file with é in iso8859-15

changed: [localhost]

PLAY RECAP **************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   

```

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: LookupError: unknown error handler name 'surrogate_then_replace'
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
exception:
Traceback (most recent call last):
  File "/home/yannig/ansible-2.2.2.0/lib/ansible/executor/task_executor.py", line 156, in run
    res = _clean_res(res)
  File "/home/yannig/ansible-2.2.2.0/lib/ansible/executor/task_executor.py", line 147, in _clean_res
    res[k] = _clean_res(res[k], errors='surrogate_then_replace')
  File "/home/yannig/ansible-2.2.2.0/lib/ansible/executor/task_executor.py", line 152, in _clean_res
    res[idx] = _clean_res(item, errors=errors)
  File "/home/yannig/ansible-2.2.2.0/lib/ansible/executor/task_executor.py", line 141, in _clean_res
    res[k] = _clean_res(res[k], errors=errors)
  File "/home/yannig/ansible-2.2.2.0/lib/ansible/executor/task_executor.py", line 137, in _clean_res
    return to_text(res, errors=errors)
  File "/home/yannig/ansible-2.2.2.0/lib/ansible/module_utils/_text.py", line 177, in to_text
    return obj.decode(encoding, errors)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
LookupError: unknown error handler name 'surrogate_then_replace'
```

**Comment by jctanner** [comment]
@Yannig I can reproduce the traceback with your playbook and any 2.2.x version. However, it appears to have been fixed in devel, which is going out as 2.3 very soon.
