### ISSUE TITLE
ANSIBLE_TIMEOUT= ansible causes OptionValueError traceback

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#22470]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lib/ansible/cli
lib/ansible/constants.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 7b167e7947) last updated 2017/03/09 15:58:00 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]


```

##### CONFIGURATION

See below

##### STEPS TO REPRODUCE

```
[fedora-25:ansible (devel % u=)]$ ANSIBLE_TIMEOUT= ansible -vvv localhost -m ping
ERROR! Unexpected Exception: option --timeout: invalid integer value: u''
the full traceback was:

Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible", line 102, in <module>
    cli.parse()
  File "/home/adrian/src/ansible/lib/ansible/cli/adhoc.py", line 75, in parse
    super(AdHocCLI, self).parse()
  File "/home/adrian/src/ansible/lib/ansible/cli/__init__.py", line 438, in parse
    self.options, self.args = self.parser.parse_args(self.args[1:])
  File "/usr/lib64/python2.7/optparse.py", line 1384, in parse_args
    values = self.get_default_values()
  File "/usr/lib64/python2.7/optparse.py", line 1329, in get_default_values
    defaults[option.dest] = option.check_value(opt_str, default)
  File "/usr/lib64/python2.7/optparse.py", line 770, in check_value
    return checker(self, opt, value)
  File "/usr/lib64/python2.7/optparse.py", line 430, in check_builtin
    _("option %s: invalid %s value: %r") % (opt, what, value))
OptionValueError: option --timeout: invalid integer value: u''
```

##### EXPECTED RESULTS

graceful error or for ANSIBLE_TIMEOUT= to be ignored

##### ACTUAL RESULTS
See above

**Comment by snowsky** [comment]
I reproduced in ubuntu 16.04 with 2d9bf888970708765703150313fd2e4b3f8905a0. I'll take another look.
