### ISSUE TITLE
open_url does not properly manages 5xx errors

### ISSUE THREAD

**Issue by Fale** [ansible/ansible#22602]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
/lib/ansible/module_utils/urls.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
uname -a
```
Linux redhat.fale.io 4.9.13-201.fc25.x86_64 #1 SMP Tue Mar 7 23:47:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
cat /etc/os-release 
```
NAME=Fedora
VERSION="25 (Twenty Five)"
ID=fedora
VERSION_ID=25
PRETTY_NAME="Fedora 25 (Twenty Five)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:25"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=25
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=25
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
```

##### SUMMARY
When the endpoint returns 5xx status, there is no way to retrieve the page body.

##### STEPS TO REPRODUCE
```
from ansible.module_utils.urls import open_url
import json

url = 'http://192.168.60.12:2379/health'
body = None
response = open_url(url, method='GET')
if response is not None:
    body = json.loads(response.read())
print body
```

##### Normal situation:
curl:
```
$ curl http://192.168.60.12:2379/health -v
*   Trying 192.168.60.12...
* TCP_NODELAY set
* Connected to 192.168.60.12 (192.168.60.12) port 2379 (#0)
> GET /health HTTP/1.1
> Host: 192.168.60.12:2379
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 14 Mar 2017 12:49:34 GMT
< Content-Length: 18
< Content-Type: text/plain; charset=utf-8
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.60.12 left intact
{"health": "true"}
```

Python script:
```
$ python test_open_url.py
{u'health': u'true'}
```

##### Normal situation:
curl:
```
$ curl http://192.168.60.12:2379/health -v
*   Trying 192.168.60.12...
* TCP_NODELAY set
* Connected to 192.168.60.12 (192.168.60.12) port 2379 (#0)
> GET /health HTTP/1.1
> Host: 192.168.60.12:2379
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 14 Mar 2017 12:50:45 GMT
< Content-Length: 20
< 
{"health": "false"}
* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.60.12 left intact
```

Python script:
```
$ python test_open_url.py 
Traceback (most recent call last):
  File "test_open_url.py", line 6, in <module>
    response = open_url(url, method='GET')
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 908, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by snowsky** [comment]
This is a urllib2 bug, but we may want to catch the error code like:
```
    import urllib2
    try:
        r = urllib_request.urlopen(*urlopen_args)
    except urllib2.HTTPError, err:
        return err.code
```

**Comment by sivel** [comment]
This is expected.  We provide no assumptions when making an HTTP request using `open_url`.  Authors using `open_url` will need to implement exception handling as with any other use of urllib within python.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
