### ISSUE TITLE
windows: ansible 2.3 RC1. ansible adhoc, win_reboot fails with "ERROR! Unexpected Exception: No module named boolean" 

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#22742]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_reboot 
##### ANSIBLE VERSION

```
ansible 2.3.0.0 (detached HEAD e4494f85b6) last updated 2017/03/17 12:34:17 (GMT +100)
  config file = /home/jon/ansible/ansible.cfg
  configured module search path = [u'/home/jon/ansible/library']
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

##### OS / ENVIRONMENT

Ubuntu (running inside Windows Subsystem for Linux on Windows 10).

##### SUMMARY

I am no longer able to run win_reboot module using 'ad hoc' ansible command.
Works ok in 2.1.1.
##### STEPS TO REPRODUCE

configure a windows host in your inventory
run ad-hoc ansible like this (where slweb is the group name that your windows host belongs to)

```yaml
ansible slweb -i INVENTORY -m win_reboot
```

##### EXPECTED RESULTS

malpdwfftwfe002 | SUCCESS => {
    "changed": true,
    "rebooted": true
}

##### ACTUAL RESULTS

```
Using /home/jon/ansible/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /home/jon/ansible-dev/lib/ansible/plugins/callback/__init__.pyc
Loading callback plugin profile_tasks of type aggregate, v2.0 from /home/jon/ansible-dev/lib/ansible/plugins/callback/__init__.pyc
META: ran handlers
ERROR! Unexpected Exception: No module named boolean
the full traceback was:

Traceback (most recent call last):
  File "/home/jon/ansible-dev/bin/ansible", line 109, in <module>
    exit_code = cli.run()
  File "/home/jon/ansible-dev/lib/ansible/cli/adhoc.py", line 200, in run
    result = self._tqm.run(play)
  File "/home/jon/ansible-dev/lib/ansible/executor/task_queue_manager.py", line 284, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/jon/ansible-dev/lib/ansible/plugins/strategy/linear.py", line 203, in run
    action = action_loader.get(task.action, class_only=True)
  File "/home/jon/ansible-dev/lib/ansible/plugins/__init__.py", line 353, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/home/jon/ansible-dev/lib/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/home/jon/ansible/plugins/action/win_reboot.py", line 23, in <module>
    from ansible.utils.boolean import boolean
ImportError: No module named boolean
```

**Comment by jctanner** [comment]
@jhawkesworth that import was removed by ,,,

```
commit 4ed88512e45112f9670560ac3f01707a40a7f5c5
Author: Toshio Kuratomi <a.badger@gmail.com>
Date:   Tue Sep 6 22:54:17 2016 -0700
```

How did you install/checkout ansible?

needs_info

**Comment by jhawkesworth** [comment]
Ah in that case it is most likely me being a doofus.

**Comment by jhawkesworth** [comment]
Confirmed it was me being a doofus.  I'd forgotten I'd grabbed a local copy of win_reboot into my /library.
