### ISSUE TITLE
Azure inventory fails with missing os_profile on certain machine types

### ISSUE THREAD

**Issue by james-portman** [ansible/ansible#22905]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
contrib/inventory/azure_rm.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Running azure_rm.py crashes due to missing/None os_profile on certain virtual machines.

##### STEPS TO REPRODUCE
Run azure_rm.py to retrieve inventory from Azure, while having a VM set up with no os_profile
```yaml
python azure_rm.py
```

##### EXPECTED RESULTS
Inventory output by the script

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "azure_rm.py", line 802, in <module>
    main()
  File "azure_rm.py", line 799, in main
    AzureInventory()
  File "azure_rm.py", line 442, in __init__
    self.get_inventory()
  File "azure_rm.py", line 507, in get_inventory
    self._load_machines(virtual_machines)
  File "azure_rm.py", line 541, in _load_machines
    computer_name=machine.os_profile.computer_name,
AttributeError: 'NoneType' object has no attribute 'computer_name'
```
Caused by the line:
```
computer_name=machine.os_profile.computer_name,
```
where machine.os_profile is None

**Comment by james-portman** [comment]
Further error once the above is resolved (again relating to os_profile of None):
```
Traceback (most recent call last):
  File "azure_rm.py", line 802, in <module>
    main()
  File "azure_rm.py", line 799, in main
    AzureInventory()
  File "azure_rm.py", line 442, in __init__
    self.get_inventory()
  File "azure_rm.py", line 507, in get_inventory
    self._load_machines(virtual_machines)
  File "azure_rm.py", line 562, in _load_machines
    if machine.os_profile.windows_configuration is not None:
AttributeError: 'NoneType' object has no attribute 'windows_configuration'
```

**Comment by cecchisandrone** [comment]
I have the same:
````
Traceback (most recent call last):
  File "./azure_rm.py", line 802, in <module>
    main()
  File "./azure_rm.py", line 799, in main
    AzureInventory()
  File "./azure_rm.py", line 442, in __init__
    self.get_inventory()
  File "./azure_rm.py", line 507, in get_inventory
    self._load_machines(virtual_machines)
  File "./azure_rm.py", line 541, in _load_machines
    computer_name=machine.os_profile.computer_name,
````
Is there any workaround?

**Comment by zyio** [comment]
Any progress on https://github.com/ansible/ansible/pull/22906 ? This is affecting us as well :/

**Comment by kmcquade** [comment]
Same issue

**Comment by jameslabocki** [comment]
Same issue for me as well

**Comment by dsuth1** [comment]
Same issue
