### ISSUE TITLE
Ansible Vault fails to decode files with CRLF line endings

### ISSUE THREAD

**Issue by DWSR** [ansible/ansible#22914]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Vault

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Windows Subsystem for Linux; Ubuntu 16.04

##### SUMMARY
Ansible Vault fails to decode files with CRLF line endings
##### STEPS TO REPRODUCE
After saving an file that is encrypted with vault, convert the line endings from LF to CRLF. This happens innocuously when using Git's EOL auto conversion feature.

##### EXPECTED RESULTS
The vault encrypted file is decrypted and used in the operation.

##### ACTUAL RESULTS
```
ansible-vault edit group_vars/role/vault.yml --vault-password-file=vault_pass -vvv
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use ansible.module_utils._text.to_text instead.
This feature will be removed
in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! Unexpected Exception: Odd-length string
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-vault", line 85, in <module>
    sys.exit(cli.run())
  File "/home/user/.local/lib/python2.7/site-packages/ansible/cli/vault.py", line 122, in run
    self.execute()
  File "/home/user/.local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 145, in execute
    fn()
  File "/home/user/.local/lib/python2.7/site-packages/ansible/cli/vault.py", line 158, in execute_edit
    self.editor.edit_file(f)
  File "/home/user/.local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 456, in edit_file
    plaintext = self.vault.decrypt(ciphertext)
  File "/home/user/.local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 259, in decrypt
    b_plaintext = this_cipher.decrypt(b_vaulttext, self.b_password)
  File "/home/user/.local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 743, in decrypt
    b_vaulttext = unhexlify(b_vaulttext)
TypeError: Odd-length string
```

**Comment by alikins** [comment]
There is a bit in parsing vaulttext that splits on b'\n', just needs to use splitlines() instead. pr incoming...
