### ISSUE TITLE
"make deb" of current devel fails in hacking/module_formatter.py

### ISSUE THREAD

**Issue by haskjold** [ansible/ansible#2293]
On Ubuntu 12.04 running "make deb" fails with the following error:

(cd docsite; make docs)
make[1]: Entering directory `/foo/ansible/docsite'
rm -f .buildinfo
rm -f *.inv
rm -rf *.doctrees
Cleaning up byte compiled python stuff
find . -regex ".*\.py[co]$" -delete
Cleaning up editor backup files
find . -type f \( -name "*~" -or -name "#*" \) -delete
find . -type f \( -name "*.swp" \) -delete
../hacking/module_formatter.py -t rst --template-dir=../hacking/templates --module-dir=../library -o rst/modules/ --includes-file=rst/modules/_list.rst
 processing module source ---> ../library/add_host
Traceback (most recent call last):
  File "../hacking/module_formatter.py", line 347, in <module>
    main()
  File "../hacking/module_formatter.py", line 299, in main
    doc, examples = ansible.utils.module_docs.get_docstring(fname, verbose=options.verbose)
ValueError: too many values to unpack
make[1]: *** [modules] Error 1
make[1]: Leaving directory`/foo/ansible/docsite'
make: **\* [webdocs] Error 2

**Comment by haskjold** [comment]
problem was trying to build with old ansible version. Fixed by sourcing hacking/env-setup
