### ISSUE TITLE
AttributeError: 'module' object has no attribute 'REPLACER_COMPLEX'

### ISSUE THREAD

**Issue by dominis** [ansible/ansible#2315]
this line: https://github.com/ansible/ansible/blob/devel/hacking/test-module#L91

causes this:

```
[vagrant@pythonbox ansible]$ python hacking/test-module -m library/ping
Traceback (most recent call last):
  File "hacking/test-module", line 155, in <module>
    main()
  File "hacking/test-module", line 145, in main
    (modfile, is_new_style) = boilerplate_module(options.module_path, options.module_args)
  File "hacking/test-module", line 91, in boilerplate_module
    module_data = module_data.replace(module_common.REPLACER_COMPLEX, empty_complex)
AttributeError: 'module' object has no attribute 'REPLACER_COMPLEX'
```

**Comment by dhozac** [comment]
This sounds like you have a mix of ansible versions. You should make sure you have run `source hacking/env-setup` before using test-module, and that it only uses the git-version of ansible and not the installed version.
