### ISSUE TITLE
ansible 2.3.0.0 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by SimplySeth** [ansible/ansible#23229]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```ansible 2.3.0.0
  config file = /home/asadmin/laptoplab/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```[defaults]
inventory = /etc/ansible/inventory
host_key_checking = False
roles_path = roles
retry_files_enabled = False
ansible_managed = "#############################
  ***      Ansible      ***
 Verizon Telematics Managed:
 Modified on: %Y-%m-%d %H:%M:%S
 By: {uid} on {host}
 Using template: {file}
 #############################"
fact_caching = jsonfile
fact_caching_connection = /etc/ansible/cache

[ssh_connection]
ssh_args =  -o UserKnownHostsFile=/dev/null
```
##### OS / ENVIRONMENT
```Description:	Ubuntu 16.04.2 LTS```

##### SUMMARY

Strange error when I add `hd['status_name'] = d['status_name'] or 'NA'` to dynamic inventory. 

It works find if I remove that line, which makes no sense.

It doesn't work if the only thing I have is that line. 

If I do `print type(d['status_name'])` it gives me `str`

##### STEPS TO REPRODUCE
Run playbook with dynamic inventory

```---
# Playbook
- hosts: machines
  user: asadmin
  become: true
  tasks:
    - debug:
```

``` #inventory script output
# --list 
{
 "controllers": {
  "vars": {},
  "hosts": [
   "maas"
  ]
 },
 "machines": {
  "vars": {},
  "hosts": [
   "lappytop001",
   "lappytop002",
   "lappytop003",
   "lappytop004",
   "lappytop005",
   "lappytop006"
  ]
 }
}

# --host 
{
  "ansible_ssh_host": "192.168.2.26",
  "distro_series": "xenial",
  "fqdn": "lappytop006.maas",
  "node_type": "NA",
  "node_type_name": "Machine",
  "osystem": "ubuntu",
  "power_state": "unknown",
  "power_type": "manual",
  "status_name": "Deployed",
  "swap_size": "-",
  "system_id": "dggtqy"
}
``` 

##### EXPECTED RESULTS

Successful run 

##### ACTUAL RESULTS

```
Using /home/asadmin/laptoplab/ansible.cfg as config file
ERROR! Unexpected Exception: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/EGG-INFO/scripts/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/ansible/cli/playbook.py", line 128, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/ansible/inventory/__init__.py", line 98, in __init__
    self.parse_inventory(host_list)
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/ansible/inventory/__init__.py", line 176, in parse_inventory
    host.vars = combine_vars(host.vars, self.get_host_variables(host.name))
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/ansible/inventory/__init__.py", line 619, in get_host_variables
    self._vars_per_host[hostname] = self._get_host_variables(hostname, vault_password=vault_password)
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/ansible/inventory/__init__.py", line 646, in _get_host_variables
    vars = combine_vars(vars, self.parser.get_host_variables(host))
  File "/usr/local/lib/python3.5/dist-packages/ansible-2.3.0.0-py3.5.egg/ansible/inventory/dir.py", line 297, in get_host_variables
    vars.update(i.get_host_variables(host))
TypeError: 'NoneType' object is not iterable
```

**Comment by abadger** [comment]
I'm unable to reproduce this with your configuration and a slightly modified dynamic inventory and playbook:
```
$ cat 23229.yml
- hosts: machines
  tasks:
    - debug:

$ cat dyninven.py                                                (10:40:55)
#!/usr/bin/python3

import sys

if '--list' in sys.argv:
    # --list 
    print("""
{
 "controllers": {
  "vars": {},
  "hosts": [
   "maas"
  ]
 },
 "machines": {
  "vars": {},
  "hosts": [
   "lappytop001",
   "lappytop002",
   "lappytop003",
   "lappytop004",
   "lappytop005",
   "lappytop006"
  ]
 }
}
    """)
if '--host' in sys.argv:
    # --host 
    print("""
{
  "ansible_ssh_host": "localhost",
  "distro_series": "xenial",
  "fqdn": "localhost",
  "node_type": "NA",
  "node_type_name": "Machine",
  "osystem": "ubuntu",
  "power_state": "unknown",
  "power_type": "manual",
  "status_name": "Deployed",
  "swap_size": "-",
  "system_id": "dggtqy"
}
    """)

$ python3 `which ansible-playbook` -i dyninven.py 23229.yml -K -k -e 'ansible_python_interpreter=/usr/bin/python3'
SSH password: 
SUDO password[defaults to SSH password]: 

PLAY [machines] *****************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [lappytop002]
ok: [lappytop003]
ok: [lappytop004]
ok: [lappytop005]
ok: [lappytop001]
ok: [lappytop006]

TASK [debug] ********************************************************************************************************
ok: [lappytop001] => {
    "changed": false,
    "msg": "Hello world!"
}
ok: [lappytop002] => {
    "changed": false,
    "msg": "Hello world!"
}
ok: [lappytop003] => {
    "changed": false,
    "msg": "Hello world!"
}
ok: [lappytop004] => {
    "changed": false,
    "msg": "Hello world!"
}
ok: [lappytop005] => {
    "changed": false,
    "msg": "Hello world!"
}
ok: [lappytop006] => {
    "changed": false,
    "msg": "Hello world!"
}

PLAY RECAP **********************************************************************************************************
lappytop001                : ok=2    changed=0    unreachable=0    failed=0   
lappytop002                : ok=2    changed=0    unreachable=0    failed=0   
lappytop003                : ok=2    changed=0    unreachable=0    failed=0   
lappytop004                : ok=2    changed=0    unreachable=0    failed=0   
lappytop005                : ok=2    changed=0    unreachable=0    failed=0   
lappytop006                : ok=2    changed=0    unreachable=0    failed=0
```

Can you try that out and then give us more information to reproduce?  (One thing I notice missing from the report is the output from ansible --version)

needs_info

**Comment by jjungnickel** [comment]
I believe I have encountered this issue and was able to narrow it down to a misbehaving dynamic inventory (in this case [terraform-inventory](https://github.com/adammck/terraform-inventory)).

Ansible will collect all hosts from static and dynamic inventories and then merge hostvars by calling `terraform-inventory --host <host>`. 

Given a host from the static (and thus unknown to the dynamic inventory), the dyanmic inventory will respond with an error message (as opposed to an empty dict), causing ansible to fail parsing the error message - with `ERROR! Unexpected Exception: 'NoneType' object is not iterable`

**Comment by bcoca** [comment]
inventory has change a lot in 2.4 and current ansible versions, could you confirm that this is still an issue?

needs_info
