### ISSUE TITLE
apt module - catch LockFailedException as non root

### ISSUE THREAD

**Issue by brandoniffert** [ansible/ansible#2325]
Running `apt update_cache=yes` as a non root user results in:

```
TASK: [Update all packages on the system] *********************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1362634726.76-241295796150835/apt", line 1082, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1362634726.76-241295796150835/apt", line 236, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/deprecation.py", line 98, in deprecated_function
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 397, in update
    raise LockFailedException("Failed to lock %s" % lockfile)
apt.cache.LockFailedException: Failed to lock /var/lib/apt/lists/lock
```

**Comment by mpdehaan** [comment]
What is the behavior you would expect in this case?

I agree the error message needs to be caught, at least...

**Comment by mpdehaan** [comment]
closing this ticket since we already merged a fix in previously.

Thanks!
