### ISSUE TITLE
solaris_project doesn't work in 2.2

### ISSUE THREAD

**Issue by helltone** [ansible/ansible#23848]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
solaris_project

##### ANSIBLE VERSION
2.2.1.0

##### CONFIGURATION
$ANSIBLE_LIBRARY
/usr/share/ansible
Python 2.6.6

##### STEPS TO REPRODUCE
Copy solaris_project module from @xen0l github, put it into /usr/share/ansible
set ANSIBLE_LIBRARY env var; add - soalris_project task into playbook, run against some solaris 11.3 hosts
```
---
- hosts: sb
  sudo: True

  tasks:


  - solaris_project:
                   name: test
```

##### EXPECTED RESULTS
create solaris project - test

##### ACTUAL RESULTS
```
task path: /home/adminosa/solaris_kolupayev/solaris_test.yml:25
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 502, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.6/site-packages/ansible/plugins/action/__init__.py", line 572, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/action/__init__.py", line 153, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/lib/python2.6/site-packages/ansible/executor/module_common.py", line 796, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/lib/python2.6/site-packages/ansible/executor/module_common.py", line 657, in _find_snippet_imports
    recursive_finder(module_name, module_data, py_module_names, py_module_cache, zf)
  File "/usr/lib/python2.6/site-packages/ansible/executor/module_common.py", line 458, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib64/python2.6/ast.py", line 37, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 3

   ^
SyntaxError: invalid syntax

fatal: [10.116.90.25]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by rcarrillocruz** [comment]
I'm a bit confused, I don't see solaris_project module within the ansible/ansible git repo.
Seems like you are reporting an issue on somebody else's ansible fork, in which case you may want to open the issue against that fork.

**Comment by helltone** [comment]
@rcarrillocruz sorry, my fault. It is extra module.
