### ISSUE TITLE
Crash with file module when directories have non utf-8 files

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#23861]
##### COMPONENT NAME

file

##### ANSIBLE VERSION

```
ansible 2.4.0 (recursive-crash-non-utf8 78836ec0b9) last updated 2017/04/21 15:31:54 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Nothing special

##### OS / ENVIRONMENT

Nothing special

##### SUMMARY

When launching file module with recurse = yes on directories with non utf-8 files, Ansible crash with the following message:

```
LookupError: unknown error handler name 'surrogate_then_strict'
```
##### STEPS TO REPRODUCE

You can retrieve an example at the following location: https://github.com/Yannig/yannig-ansible-playbooks/tree/master/file-encoding

```yaml
- name: "Recursive change with non utf-8 filename"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Recursive change (crash)"
      file: path=dir mode=0755 recurse=yes
```

##### EXPECTED RESULTS

Playbook apply change without crash

##### ACTUAL RESULTS

```
exception:
Traceback (most recent call last):
  File "/tmp/ansible_atAUEE/ansible_module_file.py", line 480, in <module>
    main()
  File "/tmp/ansible_atAUEE/ansible_module_file.py", line 362, in main
    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)
  File "/tmp/ansible_atAUEE/ansible_module_file.py", line 171, in recursive_set_attributes
    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed)
  File "/tmp/ansible_atAUEE/ansible_modlib.zip/ansible/module_utils/basic.py", line 1292, in set_fs_attributes_if_different
  File "/tmp/ansible_atAUEE/ansible_modlib.zip/ansible/module_utils/basic.py", line 995, in set_owner_if_different
  File "/tmp/ansible_atAUEE/ansible_modlib.zip/ansible/module_utils/_text.py", line 232, in to_text
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
LookupError: unknown error handler name 'surrogate_then_strict'
```

**Comment by Yannig** [comment]
This issue affect also Ansible 2.3.1.
Is there any way to have a feedback on this issue?
