### ISSUE TITLE
Python 3.4 String/Bytes Error On Syntax Check

### ISSUE THREAD

**Issue by naftulikay** [ansible/ansible#24180]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Playbooks.

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 3.4.5 (default, Nov  9 2016, 21:08:56) [GCC 4.8.4]
```

##### CONFIGURATION

None.

##### OS / ENVIRONMENT

Travis CI, Ubuntu Trusty 14.04, Python 3.4.5 as provided by Travis.

##### SUMMARY

On Python 2.7, Python 3.5, and Python 3.6, the same code works just fine: https://travis-ci.org/naftulikay/ansible-role-vagrant-rust-dev/builds/227706895

However, on Python 3.4, an exception is thrown when trying to execute the following:

```
$ ansible-playbook -vvv test-playbook.yml --syntax-check
ERROR! Unexpected Exception: unsupported operand type(s) for %: 'bytes' and 'bytes'
the full traceback was:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.5/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/__init__.py", line 99, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/play.py", line 119, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/base.py", line 251, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/play.py", line 199, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/role/__init__.py", line 156, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/role/__init__.py", line 209, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader, variable_manager=self._variable_manager)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/helpers.py", line 59, in load_list_of_blocks
    loader=loader,
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/block.py", line 85, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/base.py", line 251, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/block.py", line 121, in _load_block
    use_handlers=self._use_handlers,
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/playbook/helpers.py", line 190, in load_list_of_tasks
    include_file = loader.path_dwim_relative(t._role._role_path, subdir, include_target)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/parsing/dataloader.py", line 270, in path_dwim_relative
    is_role = self._is_role(path)
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/ansible/parsing/dataloader.py", line 237, in _is_role
    b_main = b'main%s' % (suffix)
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```

The playbook does hardly anything but depend on a role:

```
---
- hosts: localhost
  roles:
    - role: ansible-role-vagrant-rust-dev
```

##### STEPS TO REPRODUCE

Please see my repository here: https://github.com/naftulikay/ansible-role-vagrant-rust-dev

Please also see output from this build: https://travis-ci.org/naftulikay/ansible-role-vagrant-rust-dev/builds/227706895

##### EXPECTED RESULTS

Since the same thing works on Python 2.7, 3.5, and 3.6, I'd expect it to work on 3.4.

##### ACTUAL RESULTS

See above.

**Comment by sivel** [comment]
We have decided to only support python 3.5 and newer.

http://docs.ansible.com/ansible/dev_guide/developing_python3.html#minimum-version-of-python-3-x-and-python-2-x

As such, we are not supporting python 3.4.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by naftulikay** [comment]
Not a problem, glad there are docs.
