### ISSUE TITLE
Python3 incompatibility with parsing

### ISSUE THREAD

**Issue by Damgaard** [ansible/ansible#24352]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy

Although, I believe this to be a more generic issue coming from more fundamental problems with Python3 combatibility.

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/andreas/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.4.3 (default, Nov 17 2016, 01:08:31) [GCC 4.8.4]
```

##### CONFIGURATION

ansible.cf changes
```
[defaults]
pipelining = True

[ssh_connection]
pipelining=True
```

##### OS / ENVIRONMENT

Ubuntu 14.04 on controller
Ubuntu 16.04 on target machine. Only python 3x is installed.

##### SUMMARY

Running the copy function cause a Python3 incombatibility problem, that prevents it from executing.

##### STEPS TO REPRODUCE

Execute the following command while running the Ansible 2.3 with Python 3x on the controller.

```yaml

- name: Demonstrate problem
  hosts: webservers

  tasks:
  - name: Copy over test file
    copy: src=hello.txt dest=~/hello.txt

```

Note: Running the exact same playbook against the same machine will succeed if it's running from Python 2.7 locally.

##### EXPECTED RESULTS

I would expect the file to be copied from controller to target/

##### ACTUAL RESULTS

```
< TASK [Copy over test file] >
 ----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/andreas/Projects/common_ansible/all.yml:7
The full traceback is:
Traceback (most recent call last):
  File "/home/andreas/Projects/common_ansible/py3_virtualenv/lib/python3.4/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/home/andreas/Projects/common_ansible/py3_virtualenv/lib/python3.4/site-packages/ansible/executor/task_executor.py", line 521, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/andreas/Projects/common_ansible/py3_virtualenv/lib/python3.4/site-packages/ansible/plugins/action/copy.py", line 97, in run
    source = self._find_needle('files', source)
  File "/home/andreas/Projects/common_ansible/py3_virtualenv/lib/python3.4/site-packages/ansible/plugins/action/__init__.py", line 986, in _find_needle
    result = self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/home/andreas/Projects/common_ansible/py3_virtualenv/lib/python3.4/site-packages/ansible/parsing/dataloader.py", line 330, in path_dwim_relative_stack
    if is_role or self._is_role(path):
  File "/home/andreas/Projects/common_ansible/py3_virtualenv/lib/python3.4/site-packages/ansible/parsing/dataloader.py", line 237, in _is_role
    b_main = b'main%s' % (suffix)
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

fatal: [ocean2]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by sivel** [comment]
Ansible requires a minimum of python 3.5. It appears you are utilizing a version of python less than 3.5.

This is currently documented at http://docs.ansible.com/ansible/dev_guide/developing_python3.html

**Comment by Damgaard** [comment]
Ok. I hadn't seen that fine detail. I consider this issue closed then.
