### ISSUE TITLE
Confusing error message when vars_files is empty

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#2452]
If a user accidentally has an empty `vars_files` entry in a play, ansible-playbook will generate the following traceback:

```
Traceback (most recent call last):
  File "/Users/lorin/ansible/bin/ansible-playbook", line 209, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/lorin/ansible/bin/ansible-playbook", line 180, in main
    pb.run()
  File "/Users/lorin/ansible/lib/ansible/playbook/__init__.py", line 202, in run
    play = Play(self, play_ds, play_basedir)
  File "/Users/lorin/ansible/lib/ansible/playbook/play.py", line 81, in __init__
    self._update_vars_files_for_host(None)
  File "/Users/lorin/ansible/lib/ansible/playbook/play.py", line 318, in _update_vars_files_for_host
    filename4 = utils.path_dwim(self.basedir, filename3)
  File "/Users/lorin/ansible/lib/ansible/utils/__init__.py", line 192, in path_dwim
    if given.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

When I hit this, it took me a while to figure out what was wrong. It would help if ansible could provide a more meaningful error message in this situation.

Here's a simple playbook that reproduces the problem

```
- hosts: localhost
  gather_facts: False
  vars_files:
  tasks:
    - local_action: debug msg="yo!"
```

**Comment by mpdehaan** [comment]
Some sort of YAML type checking pre-processor step, perhaps.   Yes.

**Comment by lorin** [comment]
Alternatively, it could be legal to have an empty vars_files, just treat it like a no-op.

**Comment by mpdehaan** [comment]
patches would be accepted!

**Comment by gildegoma** [comment]
Thanks @lorin for reporting problem with full details, so that I very quickly find the solution. I'll try to reserve some time to provide a patch...
