### ISSUE TITLE
apt deb: with url always reports changed

### ISSUE THREAD

**Issue by saladpanda** [ansible/ansible#24673]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

apt deb (with url)

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

unchanged

##### OS / ENVIRONMENT

Distributor ID: neon
Description:    KDE neon User Edition 5.9
Release:        16.04
Codename:       xenial

##### SUMMARY

I have an apt-deb task which always reports "changed" although the deb is already installed.

##### STEPS TO REPRODUCE

```yaml
# main.yml: Install Drivers for Brother DCP-195C
# See:
# http://support.brother.com/g/b/downloadlist.aspx?c=de&lang=de&prod=dcp195c_all&os=128&flang=English

- hosts: localhost
  tasks:
    - name: "brother | install printer driver"
      become: yes
      ignore_errors: yes
      apt:
        deb: "{{ item }}"
      with_items:
        - "http://www.brother.com/pub/bsc/linux/packages/dcp195clpr-1.1.3-1.i386.deb" # lpr before cupswrapper
        - "http://www.brother.com/pub/bsc/linux/packages/dcp195ccupswrapper-1.1.3-1.i386.deb"
```
Then run `ansible-playbook -i localhost, -c local -K -vvvv main.yml`

##### EXPECTED RESULTS

Ansible should report no changes since I have already run this task multiple times. The packages are already installed.

##### ACTUAL RESULTS

Task always reports "changed".

```
$ ansible-playbook -i localhost, -c local -K -vvvv main.yml
Using /etc/ansible/ansible.cfg as config file
SUDO password: 
Set default localhost to localhost
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: main.yml ********************************************************************************************************************************************************************
1 plays in main.yml

PLAY [localhost] **********************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: stefan
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741 `" && echo ansible-tmp-1494945861.24-188838315268741="` echo /home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741 `" ) && sleep 0'
<localhost> PUT /tmp/tmpsz1R_v TO /home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741/ /home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741/setup.py; rm -rf "/home/stefan/.ansible/tmp/ansible-tmp-1494945861.24-188838315268741/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [brother | install printer driver] ***********************************************************************************************************************************************
task path: /home/stefan/ansible-test/main.yml:7
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: stefan
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444 `" && echo ansible-tmp-1494945861.7-210324426232444="` echo /home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444 `" ) && sleep 0'
<localhost> PUT /tmp/tmppjkF7q TO /home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444/apt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444/ /home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444/apt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=vcnveohugtpycwxqhljqvbesjsyjnwlj] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vcnveohugtpycwxqhljqvbesjsyjnwlj; /usr/bin/python /home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444/apt.py; rm -rf "/home/stefan/.ansible/tmp/ansible-tmp-1494945861.7-210324426232444/" > /dev/null 2>&1'"'"' && sleep 0'                                                                                                                                                            
changed: [localhost] => (item=http://www.brother.com/pub/bsc/linux/packages/dcp195clpr-1.1.3-1.i386.deb) => {
    "changed": true, 
    "diff": {
        "prepared": "(Reading database ... 191206 files and directories currently installed.)\nPreparing to unpack .../dcp195clpr-1.1.3-1.i386.deb ...\nUnpacking dcp195clpr:i386 (1.1.3-1) over (1.1.3-1) ...\nSetting up dcp195clpr:i386 (1.1.3-1) ..."                                                                                                                     
    }, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoremove": null, 
            "cache_valid_time": 0, 
            "deb": "/tmp/ansible_UkG3fk/dcp195clpr-1.1.3-1.i386.deb", 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": false, 
            "install_recommends": null, 
            "only_upgrade": false, 
            "package": null, 
            "purge": false, 
            "state": "present", 
            "update_cache": null, 
            "upgrade": null
        }
    }, 
    "item": "http://www.brother.com/pub/bsc/linux/packages/dcp195clpr-1.1.3-1.i386.deb", 
    "stderr": "mkdir: cannot create directory '/var/spool/lpd/dcp195c': No such file or directory\nchown: cannot access '/var/spool/lpd/dcp195c': No such file or directory\nchgrp: cannot access '/var/spool/lpd/dcp195c': No such file or directory\nchmod: cannot access '/var/spool/lpd/dcp195c': No such file or directory\n",                                           
    "stderr_lines": [
        "mkdir: cannot create directory '/var/spool/lpd/dcp195c': No such file or directory", 
        "chown: cannot access '/var/spool/lpd/dcp195c': No such file or directory", 
        "chgrp: cannot access '/var/spool/lpd/dcp195c': No such file or directory", 
        "chmod: cannot access '/var/spool/lpd/dcp195c': No such file or directory"
    ], 
    "stdout": "(Reading database ... 191206 files and directories currently installed.)\nPreparing to unpack .../dcp195clpr-1.1.3-1.i386.deb ...\nUnpacking dcp195clpr:i386 (1.1.3-1) over (1.1.3-1) ...\nSetting up dcp195clpr:i386 (1.1.3-1) ...\n",                                                                                                                        
    "stdout_lines": [
        "(Reading database ... 191206 files and directories currently installed.)", 
        "Preparing to unpack .../dcp195clpr-1.1.3-1.i386.deb ...", 
        "Unpacking dcp195clpr:i386 (1.1.3-1) over (1.1.3-1) ...", 
        "Setting up dcp195clpr:i386 (1.1.3-1) ..."
    ]
}
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt.py
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253 `" && echo ansible-tmp-1494945866.04-121364415219253="` echo /home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253 `" ) && sleep 0'
<localhost> PUT /tmp/tmp6N1eXt TO /home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253/apt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253/ /home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253/apt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=ruiizwouxuptmgkbuidmglnpjicccykm] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ruiizwouxuptmgkbuidmglnpjicccykm; /usr/bin/python /home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253/apt.py; rm -rf "/home/stefan/.ansible/tmp/ansible-tmp-1494945866.04-121364415219253/" > /dev/null 2>&1'"'"' && sleep 0'
changed: [localhost] => (item=http://www.brother.com/pub/bsc/linux/packages/dcp195ccupswrapper-1.1.3-1.i386.deb) => {
    "changed": true, 
    "diff": {
        "prepared": "(Reading database ... 191206 files and directories currently installed.)\nPreparing to unpack .../dcp195ccupswrapper-1.1.3-1.i386.deb ...\nRestarting cups (via systemctl): cups.service.\nUnpacking dcp195ccupswrapper:i386 (1.1.3-1) over (1.1.3-1) ...\nSetting up dcp195ccupswrapper:i386 (1.1.3-1) ...\nRestarting cups (via systemctl): cups.service."
    }, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoremove": null, 
            "cache_valid_time": 0, 
            "deb": "/tmp/ansible_Jj_E9s/dcp195ccupswrapper-1.1.3-1.i386.deb", 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": false, 
            "install_recommends": null, 
            "only_upgrade": false, 
            "package": null, 
            "purge": false, 
            "state": "present", 
            "update_cache": null, 
            "upgrade": null
        }
    }, 
    "item": "http://www.brother.com/pub/bsc/linux/packages/dcp195ccupswrapper-1.1.3-1.i386.deb", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "(Reading database ... 191206 files and directories currently installed.)\nPreparing to unpack .../dcp195ccupswrapper-1.1.3-1.i386.deb ...\nRestarting cups (via systemctl): cups.service.\nUnpacking dcp195ccupswrapper:i386 (1.1.3-1) over (1.1.3-1) ...\nSetting up dcp195ccupswrapper:i386 (1.1.3-1) ...\nRestarting cups (via systemctl): cups.service.\n", 
    "stdout_lines": [
        "(Reading database ... 191206 files and directories currently installed.)", 
        "Preparing to unpack .../dcp195ccupswrapper-1.1.3-1.i386.deb ...", 
        "Restarting cups (via systemctl): cups.service.", 
        "Unpacking dcp195ccupswrapper:i386 (1.1.3-1) over (1.1.3-1) ...", 
        "Setting up dcp195ccupswrapper:i386 (1.1.3-1) ...", 
        "Restarting cups (via systemctl): cups.service."
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

tag: @evgeni

**Comment by saladpanda** [comment]
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py compares the `Package` and `Version` fields reported by `dpkg --field FILE.deb Package` and `dpkg --field FILE.deb Version` with those reported by python-apt. These are the results of manually doing those checks:

```
~/ansible-test2
❯ dpkg --field dcp195ccupswrapper-1.1.3-1.i386.deb Package
dcp195ccupswrapper

~/ansible-test2
❯ dpkg --field dcp195clpr-1.1.3-1.i386.deb Package        
dcp195clpr

~/ansible-test2
❯ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> apt.Cache()['dcp195ccupswrapper']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 200, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'dcp195ccupswrapper'"
>>> apt.Cache()['dcp195clpr']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 200, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'dcp195clpr'"
```
But:
```
~/ansible-test2
❯ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> apt.Cache()['dcp195clpr:i386']
<Package: name:'dcp195clpr' architecture='i386' id:111420L>
>>> apt.Cache()['dcp195ccupswrapper:i386']
<Package: name:'dcp195ccupswrapper' architecture='i386' id:111424L>
```

So ansible is looking for `dcp195clpr` but `apt.Cache()` only contains `dcp195clpr:i386`.
Hence `installed_pkg` in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py#L555 is undefined and the check in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py#L557 fails.
