### ISSUE TITLE
error when specifying multiple group_names in ec2_group rules

### ISSUE THREAD

**Issue by clofresh** [ansible/ansible#24741]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
ec2_group module

##### ANSIBLE VERSION
Broken in 2.3.0 but fixed in devel branch

##### SUMMARY

Specifying multiple group_name values gives an error

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: test sg
      ec2_group:
        region: us-west-2
        name: test-sg
        description: test
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_name:
              - sg-1
              - sg-2
```

```
Traceback (most recent call last):
  File "/tmp/ansible_t3AIZS/ansible_module_ec2_group.py", line 487, in <module>
    main()
  File "/tmp/ansible_t3AIZS/ansible_module_ec2_group.py", line 356, in main
    group_id, ip, target_group_created = get_target_from_rule(module, ec2, rule, name, group, groups, vpc_id)
  File "/tmp/ansible_t3AIZS/ansible_module_ec2_group.py", line 225, in get_target_from_rule
    elif group_name in groups and (vpc_id is None or groups[group_name].vpc_id == vpc_id):
TypeError: unhashable type: 'list'
```

The bug is actually fixed in the devel branch, so I think it's more of a documentation issue to mention that multiple group_name values doesn't work until 2.4.0 is released.

**Comment by s-hertel** [comment]
Hi @clofresh - Is #24741 a helpful clarification? If you'd prefer different wording feel free to comment on it!
