### ISSUE TITLE
tower_job_template not receiving argument for extra_vars_path argument

### ISSUE THREAD

**Issue by jameslabocki** [ansible/ansible#25266]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible Module tower_job_template

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### OS / ENVIRONMENT
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
$  uname -a
Linux ip-10-220-192-72.localdomain 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY

```yaml
- name: Create aws-infrastructure job template
  tower_job_template:
    name: aws-infrastructure
    job_type: run
    inventory: aws-inventory
    project: openshift-ansible-contrib
    playbook: "reference-architecture/aws-ansible/playbooks/infrastructure.yaml"
    machine_credential: aws-privkey
    cloud_credential: ec2
    state: present
    tower_config_file: "~/.tower_cli.cfg"
    extra_vars_path: /opt/tmp/extra_vars.yaml
```
Returns
```
TASK [tower_config : Create aws-infrastructure job template] ****************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: ''
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_VOikLO/ansible_module_tower_job_template.py\", line 329, in <module>\n    main()\n  File \"/tmp/ansible_VOikLO/ansible_module_tower_job_template.py\", line 316, in main\n    result = jt.modify(**params)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 1234, in modify\n    force_on_exists=True, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/resources/job_template.py\", line 107, in write\n    return super(Resource, self).write(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 1249, in write\n    kwargs['extra_vars'])\n  File \"/usr/lib/python2.7/site-packages/tower_cli/utils/parser.py\", line 123, in process_extra_vars\n    with open(extra_vars_opt[1:], 'r') as f:\nIOError: [Errno 2] No such file or directory: ''\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/ec2-user/openshift-ansible-contrib/reference-architecture/ansible-tower-integration/tower_config/tower_config.retry
```

##### STEPS TO REPRODUCE
Use the tower_job_template with extra_vars_path set and see that extra_vars_path does not get picked up during execution.

##### EXPECTED RESULTS
File listed in extra_vars_path should be sourced.

**Comment by jameslabocki** [comment]
```
TASK [tower_config : Create aws-infrastructure job template] ****************************************************************************************************
task path: /home/ec2-user/openshift-ansible-contrib/reference-architecture/ansible-tower-integration/tower_config/tower_config/tasks/main.yaml:103
Using module file /usr/lib/python2.7/site-packages/ansible/modules/web_infrastructure/ansible_tower/tower_job_template.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580 `" && echo ansible-tmp-1496338745.32-235639177922580="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpR3yWeM TO /home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580/tower_job_template.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580/ /home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580/tower_job_template.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vbvtvhgzjhwzqtbitfhmkusefrmwtavs; /usr/bin/python2 /home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580/tower_job_template.py; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1496338745.32-235639177922580/" > /dev/null 2>&1'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_tWCG99/ansible_module_tower_job_template.py", line 329, in <module>
    main()
  File "/tmp/ansible_tWCG99/ansible_module_tower_job_template.py", line 316, in main
    result = jt.modify(**params)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 1234, in modify
    force_on_exists=True, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/job_template.py", line 107, in write
    return super(Resource, self).write(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 1249, in write
    kwargs['extra_vars'])
  File "/usr/lib/python2.7/site-packages/tower_cli/utils/parser.py", line 123, in process_extra_vars
    with open(extra_vars_opt[1:], 'r') as f:
IOError: [Errno 2] No such file or directory: ''

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tWCG99/ansible_module_tower_job_template.py\", line 329, in <module>\n    main()\n  File \"/tmp/ansible_tWCG99/ansible_module_tower_job_template.py\", line 316, in main\n    result = jt.modify(**params)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 1234, in modify\n    force_on_exists=True, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/resources/job_template.py\", line 107, in write\n    return super(Resource, self).write(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 1249, in write\n    kwargs['extra_vars'])\n  File \"/usr/lib/python2.7/site-packages/tower_cli/utils/parser.py\", line 123, in process_extra_vars\n    with open(extra_vars_opt[1:], 'r') as f:\nIOError: [Errno 2] No such file or directory: ''\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/ec2-user/openshift-ansible-contrib/reference-architecture/ansible-tower-integration/tower_config/tower_config.retry
```

**Comment by wenottingham** [comment]
cc @wwitzel3 @AlanCoding

**Comment by wenottingham** [comment]
-label needs_triage
