### ISSUE TITLE
ec2_group module throwing "Error in get_all_security_groups: AWS was not able to validate the provided access credentials"

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible#25296]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_group module
boto (probably)

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.0 (devel 2f33c1a1a1) last updated 2017/06/02 22:12:15 (GMT +1300)
  config file =
  configured module search path = [u'/Users/srdan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/srdan/code/ansible/lib/ansible
  executable location = /Users/srdan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Feb 28 2017, 09:57:00) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### OS / ENVIRONMENT
Running from: OS X
Managing: N/A (AWS API's)

##### SUMMARY
Module throws error instead of creating new security group.

##### STEPS TO REPRODUCE
Call "ec2_group" module task with a valid AWS API key, VPC ID and correct region.

```yaml
- name: Ensure Security group is there and lets us connect
  connection: local
  tags: ['security-group']
  ec2_group:
    name: "tempgroup"
    description: "temporary security group for creating AMI"
    vpc_id: "vpc-b1caa285" # TODO: don't hard code this
    region: "{{ aws_region_id | default('us-east-1') }}"
    aws_secret_key: "{{ aws_access_key_id }}"
    aws_access_key: "{{ aws_secret_access_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
```

##### EXPECTED RESULTS
I expected the security group to be created as per arguments passed to the task.

##### ACTUAL RESULTS
The following module error was thrown:

```
 ____________________________________________________________
/ TASK [create-ami : Ensure Security group is there and lets \
\ us connect]                                                /
 ------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/srdan/code/keystone/roles/create-ami/tasks/main.yml:40
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/ec2.py
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/six/_six.py
Using module_utils file /Users/srdan/code/ansible/lib/ansible/module_utils/cloud.py
Using module file /Users/srdan/code/ansible/lib/ansible/modules/cloud/amazon/ec2_group.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: srdan
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989 `" && echo ansible-tmp-1496398580.12-221457541621989="` echo /Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989 `" ) && sleep 0'
<localhost> PUT /var/folders/01/fswx1t811p3_q5bj53yjfhnw0000gn/T/tmpCBFirw TO /Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989/ec2_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989/ /Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989/ec2_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989/ec2_group.py; rm -rf "/Users/srdan/.ansible/tmp/ansible-tmp-1496398580.12-221457541621989/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/01/fswx1t811p3_q5bj53yjfhnw0000gn/T/ansible_xLalJR/ansible_module_ec2_group.py", line 414, in main
    security_groups = ec2.get_all_security_groups()
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 2984, in get_all_security_groups
    [('item', SecurityGroup)], verb='POST')
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>c967bb6a-1e29-4bc8-a4b5-62afd9aadfeb</RequestID></Response>

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": "ABCdeFG9wzkxfMow123459VMY+42uaMMJcTAAA4V",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",


            "description": "temporary security group for creating AMI",
            "ec2_url": null,
            "name": "tempgroup",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "us-east-1",
            "rules": [
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-b1caa285"
        }
    },
    "msg": "Error in get_all_security_groups: AWS was not able to validate the provided access credentials"
}
```

**Comment by jctanner** [comment]
cc @willthames @s-hertel @ryansb

**Comment by s-hertel** [comment]
Hi @srkiNZ84 thanks for the issue. Are your credentials in ~/.boto?

**Comment by s-hertel** [comment]
If so feel free to test the [fix](#24783).

**Comment by s-hertel** [comment]
If so feel free to test the [fix](https://github.com/ansible/ansible/pull/24783) and leave some feedback.

**Comment by s-hertel** [comment]
Closed because I believe this was fixed in https://github.com/ansible/ansible/pull/24783.
Please reopen this if I'm wrong and give some details about where your credentials are.
