### ISSUE TITLE
S3 delete non-existent bucket fails

### ISSUE THREAD

**Issue by bferg** [ansible/ansible#25445]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - S3 module

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

##### CONFIGURATION

Ansible config file:
```
[defaults]
host_key_checking = False
remote_user = centos
callback_whitelist = profile_tasks, human_log
callback_plugins = callback_plugins
lookup_plugins = lookup_plugins
log_path = log/ansible.log
retry_files_enabled = False
hostfile = inventory/ec2.py
timeout = 30

[ssh_connection]
ssh_args = -F ./ssh.cfg -o ForwardAgent=yes -o UserKnownHostsFile=/dev/null
control_path = none
pipelining = True
```

##### OS / ENVIRONMENT

Playbook launched on OS X 10.0.5, Darwin Kernel Version 14.5.0

Remote EC2 instance CentOS6 (not relevant for this bug)

##### STEPS TO REPRODUCE

If an S3 bucket has already been deleted or does not exist, running the S3 module with the "delete" mode on it will cause the module to fail with a stack trace. This occurs even with the "ignore_nonexistent_bucket" parameter set. Earlier versions of the S3 module did not fail in this case.

```yaml
---
- name: foo
  hosts: localhost
  connection: local
  tasks:
      - name: delete nonexistent bucket
        s3:
            bucket: "some-bucket-that-does-not-exist"
            mode: "delete"
            ignore_nonexistent_bucket: "True"
```

A possible fix is to extend the "ignore_nonexistent_bucket" parameter handling as follows around line 557:

```python
    if not ignore_nonexistent_bucket:
        validate = True
        if mode not in ('create', 'put') and not bucketrtn:
            module.fail_json(msg="Source bucket cannot be found.")
    else:
        if mode == 'delete' and not bucketrtn:
            module.exit_json(msg="Bucket not found for deletion", changed=False)
        validate = False
```

##### EXPECTED RESULTS

If "ignore_nonexistent_bucket" is set, I expect the S3 task to succeed on deletion even if the bucket does not exist. If the "ignore_nonexistent_bucket" is not set, I expect the S3 task to fail on deletion.

##### ACTUAL RESULTS

The S3 module fails with a stack trace.

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/mk/zyr99n9j3dg3tlqp__8xqp_0kbzv15/T/ansible_15ONhL/ansible_module_s3.py\", line 765, in <module>\n    main()\n  File \"/var/folders/mk/zyr99n9j3dg3tlqp__8xqp_0kbzv15/T/ansible_15ONhL/ansible_module_s3.py\", line 651, in main\n    deletertn = delete_bucket(module, s3, bucket)\n  File \"/var/folders/mk/zyr99n9j3dg3tlqp__8xqp_0kbzv15/T/ansible_15ONhL/ansible_module_s3.py\", line 340, in delete_bucket\n    bucket_contents = bucket.list()\nAttributeError: 'NoneType' object has no attribute 'list'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

Here's the stack trace in a readable form:
```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/mk/zyr99n9j3dg3tlqp__8xqp_0kbzv15/T/ansible_15ONhL/ansible_module_s3.py", line 765, in <module>
    main()
  File "/var/folders/mk/zyr99n9j3dg3tlqp__8xqp_0kbzv15/T/ansible_15ONhL/ansible_module_s3.py", line 651, in main
    deletertn = delete_bucket(module, s3, bucket)
  File "/var/folders/mk/zyr99n9j3dg3tlqp__8xqp_0kbzv15/T/ansible_15ONhL/ansible_module_s3.py", line 340, in delete_bucket
    bucket_contents = bucket.list()
AttributeError: 'NoneType' object has no attribute 'list'
```

**Comment by s-hertel** [comment]
I think the name `ignore_nonexistent_bucket` could be improved on or have some added documentation. The idea behind it is that the user may have permission to create/modify/delete a bucket, but may not have list bucket permission. So even if bucketrtn is false, we would still try to do something to that bucket, ignoring that the user can't "see" it and just trusting that it exists.
