### ISSUE TITLE
ImportError: cannot import name reduce

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#25460]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
plugins/callback/profile_roles.py

##### ANSIBLE VERSION

```
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
the reduce import from six is broken and is causing tracebacks in devel
https://github.com/ansible/ansible/commit/2e920d724dcb17bf559773859cd43ba022fcb04b#diff-46a3b4b016f324f278a7d2f8ab2a7855 looks like an attempt to fix a broken import, but that change doesn't work either.

```
Traceback (most recent call last):
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/bin/ansible", line 106, in <module>
    exit_code = cli.run()
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/lib/ansible/cli/adhoc.py", line 178, in run
    result = self._tqm.run(play)
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/lib/ansible/executor/task_queue_manager.py", line 211, in run
    self.load_callbacks()
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/lib/ansible/executor/task_queue_manager.py", line 179, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/lib/ansible/plugins/__init__.py", line 418, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/lib/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/home/jtanner/workspace/scratch/atomic-tests/ansible/lib/ansible/plugins/callback/profile_roles.py", line 30, in <module>
    from ansible.module_utils.six import reduce
ImportError: cannot import name reduce
```

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/ansible
source ansible/hacking/env-setup
ansible localhost -m setup

**Comment by sivel** [comment]
This is fixed in https://github.com/ansible/ansible/pull/25458

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/25458
