### ISSUE TITLE
On a python 3.4 host, copy runs into an type error

### ISSUE THREAD

**Issue by marceloslacerda** [ansible/ansible#25547]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy_module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In Python 3.4 tempfile.mkstemp does not support byte array in the dir argument:

```
tempfile.mkstemp(dir=b"/tmp/foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/tempfile.py", line 409, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python3.4/tempfile.py", line 337, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "/usr/lib/python3.4/posixpath.py", line 89, in join
    "components") from None
TypeError: Can't mix strings and bytes in path components
```

In [line 373 of the copy.py module](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/copy.py#L373 ) we pass a byte array to os.path.dirname that passes a byte array to tempfile.mkstemp.

##### STEPS TO REPRODUCE
1.  Install python 3.4 in a host "myhost"
2- ```ansible-playbook -e 'ansible_python_interpreter="/usr/bin/env <python3.4 binary>" myplaybook.yml```

myplaybook.yml:
```
- hosts: myhost
  tasks:
    - name: copy test file
      copy:
        src: /tmp/foo
        dest: /tmp/bar
```

##### EXPECTED RESULTS
Copy succeeds. Or a message is shown stating that ansible does not support python < 3.5.

##### ACTUAL RESULTS

```
failed: [myhost] (item=/usr/local/myplaybooks/deploy-playbooks.yml) => {"failed": true, "item": "/usr/local/myplaybooks/deploy-playbooks.yml", "module_stderr": "Shared connection to myhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_l27masdb/ansible_module_copy.py\", line 394, in <module>\r\n    main()\r\n  File \"/tmp/ansible_l27masdb/ansible_module_copy.py\", line 371, in main\r\n    _, b_mysrc = tempfile.mkstemp(dir=os.path.dirname(b_dest))\r\n  File \"/usr/local/lib/python3.4/tempfile.py\", line 270, in mkstemp\r\n    return _mkstemp_inner(dir, prefix, suffix, flags)\r\n  File \"/usr/local/lib/python3.4/tempfile.py\", line 198, in _mkstemp_inner\r\n    file = _os.path.join(dir, pre + name + suf)\r\n  File \"/usr/local/lib/python3.4/posixpath.py\", line 89, in join\r\n    \"components\") from None\r\nTypeError: Can't mix strings and bytes in path components\r\n", "msg": "MODULE FAILURE", "rc": 0}
failed: [myhost] (item=/usr/local/myplaybooks/myplaybook.yml) => {"failed": true, "item": "/usr/local/myplaybooks/myplaybook.yml", "module_stderr": "Shared connection to myhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_jbn66iqc/ansible_module_copy.py\", line 394, in <module>\r\n    main()\r\n  File \"/tmp/ansible_jbn66iqc/ansible_module_copy.py\", line 371, in main\r\n    _, b_mysrc = tempfile.mkstemp(dir=os.path.dirname(b_dest))\r\n  File \"/usr/local/lib/python3.4/tempfile.py\", line 270, in mkstemp\r\n    return _mkstemp_inner(dir, prefix, suffix, flags)\r\n  File \"/usr/local/lib/python3.4/tempfile.py\", line 198, in _mkstemp_inner\r\n    file = _os.path.join(dir, pre + name + suf)\r\n  File \"/usr/local/lib/python3.4/posixpath.py\", line 89, in join\r\n    \"components\") from None\r\nTypeError: Can't mix strings and bytes in path components\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

I noticed that ansible shows a different error when you try to run it as an ad-hoc command:

```ansible myhost -m copy -a "src=/tmp/foo dest=/tmp/bar " -e 'ansible_python_interpreter="/usr/bin/env <python3.4 binary>"

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: can't concat bytes to str
localhost | FAILED! => {
    "changed": false, 
    "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", 
    "failed": true, 
    "msg": "Failed creating temp file for atomic move.  This usually happens when using Python3 less than Python3.5.  Please use Python2.x or Python3.5 or greater."
}
```

Asking on the irc channel I was sent to [the developer guide page](http://docs.ansible.com/ansible/dev_guide/developing_python3.html#minimum-version-of-python-3-x-and-python-2-x) that states that python 3.5 < is not supported, but that fact is not mentioned in the [python 3 support page](https://docs.ansible.com/ansible/python_3_support.html).

**Comment by marceloslacerda** [comment]
The reason why running the ad-hoc command catches that I'm using python 3.4 is because I'm running it on the localhost and it's the [manager part of the code](https://github.com/ansible/ansible/blob/ba4f6de35a7499c1e894785d5a9b488002976588/lib/ansible/module_utils/basic.py#L2295) that catches the problem.

**Comment by abadger** [comment]
Yep.  Minimum Python3 version is 3.5.
