### ISSUE TITLE
Unable to use Ansible Tower modules in playbook

### ISSUE THREAD

**Issue by ababra** [ansible/ansible#25675]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_inventory
tower_host

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/ababra/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
[ssh_connection]
scp_if_ssh=True

##### OS / ENVIRONMENT
macOS Sierra 10.12.5

##### SUMMARY
Unable to use any Ansible Tower module in playbook, i.e. tower_host, tower_inventory, etc. Python error encountered when playbook executes.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
    - name: Add host to inventory
      tower_host:
        name: "test-host"
        inventory: "test-inventory"
        state: present
        tower_host: "{{tower_host}}"
        tower_username: "{{tower_username}}"
        tower_password: "{{tower_password}}"
        tower_verify_ssl: "{{tower_verify_ssl}}"
```

##### EXPECTED RESULTS
Host created successfully in Tower.

##### ACTUAL RESULTS
```
PLAYBOOK: tower-sync.yaml ****************************************************************************************
1 plays in tower-sync.yaml
ERROR! Unexpected Exception: 0
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/Library/Python/2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/Library/Python/2.7/site-packages/ansible/executor/playbook_executor.py", line 125, in run
    all_vars = self._variable_manager.get_vars(loader=self._loader, play=play)
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 312, in get_vars
    data = preprocess_vars(loader.load_from_file(vars_file))
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 110, in load_from_file
    file_name = self.path_dwim(file_name)
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 218, in path_dwim
    given = unquote(given)
  File "/Library/Python/2.7/site-packages/ansible/parsing/quoting.py", line 28, in unquote
    if is_quoted(data):
  File "/Library/Python/2.7/site-packages/ansible/parsing/quoting.py", line 24, in is_quoted
    return len(data) > 1 and data[0] == data[-1] and data[0] in ('"', "'") and data[-2] != '\\'
KeyError: 0
```

**Comment by ababra** [comment]
Syntax error, was missing "tasks:"
