### ISSUE TITLE
Python-apt module on Debian Lenny does not support the required attributes

### ISSUE THREAD

**Issue by cwstrommer** [ansible/ansible#257]
I know Debian 5 is to be considered deprecated, but backwards compatibility may make using ansible to upgrade these systems easier. 

The relevant log is:

```
$ ansible-playbook test-update.yml 


PLAY [test-update] ****************************

SETUP PHASE ****************************

ok: [10.0.0.11]


TASK: [ensure that the core packages are installed and at their latest version] *********

failed: [10.0.0.11] => apt pkg=vim-nox state=latest => {"failed": true, "msg": "", "parsed": false}

stderr: [10.0.0.11] => /usr/lib/python2.5/site-packages/apt/__init__.py:18: FutureWarning: apt API not stable yet

  warnings.warn("apt API not stable yet", FutureWarning)

Traceback (most recent call last):

  File "/tmp/ansible.QwvoSV/apt", line 141, in <module>

    changed = install(package, cache, upgrade=True)

  File "/tmp/ansible.QwvoSV/apt", line 74, in install

    (installed, upgradable) = package_status(pkgspec, cache)

  File "/tmp/ansible.QwvoSV/apt", line 71, in package_status

    return (pkg.is_installed, pkg.is_upgradable)

AttributeError: 'Package' object has no attribute 'is_installed'
```

**Comment by mpdehaan** [comment]
Assigning to mgw since he wrote the apt module and maybe he can get it to work better.

**Comment by mpdehaan** [comment]
per IRC discussion, closing since Lenny dropped off the Debian support cycle.
