### ISSUE TITLE
Error while fetching server API version

### ISSUE THREAD

**Issue by PREM1980** [ansible/ansible#25711]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
anisble-container

##### ANSIBLE VERSION
ansible 2.3.0.0

##### CONFIGURATION
Nothing changed

##### OS / ENVIRONMENT
MAC

##### SUMMARY
Trying to create a ansible-container as given in this tutorial but get an error while running anisble-container run. 

http://docs.ansible.com/ansible-container/getting_started.html#dipping-a-toe-in-starting-from-scratch

**DOcker version**
(bossa)PREMs-MacBook-Pro:ansible-container-example prem$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

Error:- 

2017-06-14T17:57:35.236681 In conductorcmd_run            [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_run caller_line=772 kwargs={u'with_volumes': [], 'repository_data': {}, u'service': [], u'settings': {u'pwd': u'/Users/prem/Documents/bossanova/ansible-container-example', u'conductor_base': u'centos:7'}, u'with_variables': [], u'selinux': True, u'subcommand': u'run', u'debug': True, u'devel': False, u'deployment_output_path': u'/Users/prem/Documents/bossanova/ansible-container-example/ansible-deployment', u'production': False, u'host_user_uid': 501, u'host_user_gid': 20, u'detached': False, 'volume_data': {}, u'roles_path': None}
2017-06-14T17:57:35.247794 GENERATE DEPLOYMENT            [container.docker.engine] caller_file=/_ansible/container/docker/engine.py caller_func=generate_orchestration_playbook caller_line=569 namespace=None url=None
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 366, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 773, in conductorcmd_run
    playbook = engine.generate_orchestration_playbook(**kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 637, in generate_orchestration_playbook
    for image in self.client.images.list(name=image_name):
  File "/_ansible/container/docker/engine.py", line 123, in client
    self._client = docker.from_env(version='auto')
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 79, in from_env
    **kwargs_from_env(**kwargs))
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 36, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 141, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 168, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
2017-06-14T13:57:35.887098 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/Users/prem/.virtualenvs/bossa/src/ansible-container/container/docker/engine.py caller_func=await_conductor_command caller_line=348 command_rc=1 conductor_id=u'9197051f2d14a22a3ea52ebdf60ab6642d4b03ff5f379859238697323b878879' save_container=False
2017-06-14T13:57:36.889002 Conductor exited with status 1 [container.cli] caller_file=/Users/prem/.virtualenvs/bossa/src/ansible-container/container/cli.py caller_func=__call__ caller_line=286

 STEPS TO REPRODUCE
Just followed the steps from here..Nothing changed.

http://docs.ansible.com/ansible-container/getting_started.html#dipping-a-toe-in-starting-from-scratch

##### EXPECTED RESULTS
The build run should work fine.

**Comment by nitzmahone** [comment]
This issue should be filed at https://github.com/ansible/ansible-container - ansible/ansible is for issues on the core Ansible engine.

**Comment by PREM1980** [comment]
Thanks.Should I open a new ticket there or Is there a way for me to link this ticket automatically?

**Comment by nitzmahone** [comment]
Gotta open a new one there

**Comment by jbarlow83** [comment]
For anyone else chasing this issue across the internet, it has most *recently moved* to
https://github.com/ansible/ansible-container/issues/608
