### ISSUE TITLE
ec2 module error

### ISSUE THREAD

**Issue by pgjones** [ansible/ansible#25790]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Commit 3bba43a487c6b24ee4948f23744f6a3fb8849194 introduced a bug into the ec2 module.

##### ANSIBLE VERSION
I'm actually running the exact commit mentioned.
```
ansible 2.4.0
  config file = .ansible/ansible.cfg
  configured module search path = [u'.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ansible/.ve/local/lib/python2.7/site-packages/ansible
  executable location = ansible/.ve/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I've tracked this bug down to the specific commit mentioned. I'll keep looking into how to fix, but I'm not very familiar with ansible.
```
Traceback (most recent call last):
      File "/tmp/ansible_wu0yzI/ansible_module_ec2.py", line 1695, in <module>
        main()
      File "/tmp/ansible_wu0yzI/ansible_module_ec2.py", line 1689, in main
        (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2, vpc)
      File "/tmp/ansible_wu0yzI/ansible_module_ec2.py", line 949, in enforce_count
        = create_instances(module, ec2, vpc, override_count=to_create)
      File "/tmp/ansible_wu0yzI/ansible_module_ec2.py", line 1034, in create_instances
        vpc_id = vpc.get_all_subnets(subnet_ids=[vpc_subnet_id])[0].vpc_id
      File ".ve/local/lib/python2.7/site-packages/boto/vpc/__init__.py", line 1153, in get_all_subnets
        return self.get_list('DescribeSubnets', params, [('item', Subnet)])
      File ".ve/local/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
        raise self.ResponseError(response.status, response.reason, body)
    boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
    <?xml version="1.0" encoding="UTF-8"?>
    <Response><Errors><Error><Code>InvalidSubnetID.NotFound</Code><Message>The subnet ID 'REDACTED' does not exist</Message></Error></Errors><RequestID>eb8da35e-b10e-4366-92f5-dc8ada0fef0b</RequestID></Response>
```

##### STEPS TO REPRODUCE
Try using the ec2 module to spawn an instance.

**Comment by s-hertel** [comment]
Hi @pgjones, thanks for opening this. I believe this bug was fixed yesterday in https://github.com/ansible/ansible/commit/938d60472af6f6b20d0d7a0c616e36b499e79c12. Please reopen this if that has not fixed the issue for you. 

Edit:
If you're looking to become a contributer feel free to join the #ansible-aws and #ansible-devel IRC channel. :)

**Comment by pgjones** [comment]
It does, thanks.
