### ISSUE TITLE
network_group_modules from ansible.cfg gets loaded incorrectly

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#26154]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

constants.py

##### ANSIBLE VERSION

```
 ansible --version
ansible 2.3.0.0
  config file = /home/jmighion/git/Ansible-Networking/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

```
$ grep -v '#' ansible.cfg | grep  -e "\S"
[defaults]
inventory      = inventory
forks          = 1400
gather_subset = !ohai,!facter
gathering = smart
roles_path    = roles
host_key_checking = False
timeout = 20
log_path = ~/ansible.log
fact_caching = jsonfile
fact_caching_connection = ~/.cache/facts
fact_caching_timeout = 86400
retry_files_enabled = False
network_group_modules=['eos', 'nxos', 'ios', 'iosxr', 'junos', 'vyos']
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
[diff]
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY

If you use the network_group_modules option in ansible.cfg, it gets loaded incorrectly in constants.py. Even using the default that's provided in ansible.cfg, just using it will cause TaskExecutor._get_action_handler to load the wrong action plugin. I've been able to reproduce this on 2.3.0, 2.3.1, and devel 2.4.0 (3d6d428).

##### STEPS TO REPRODUCE

Remove the comment before the network_group_modules line in ansible.cfg : 
network_group_modules=['eos', 'nxos', 'ios', 'iosxr', 'junos', 'vyos']

```yaml
- name: dev
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: dev
      ios_facts:
        gather_subset:
          - "!interfaces"
        provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Gather ios_facts
Added logging to show what C.NETWORK_GROUP_MODULES was  : 
```
Found module_prefix : ios
Found C.NETWORK_GROUP_MODULES : ['eos', 'nxos', 'ios', 'iosxr', 'junos', 'vyos', 'sros', 'dellos9', 'dellos10', 'dellos6']
```

##### ACTUAL RESULTS

Added logging to show what C.NETWORK_GROUP_MODULES was  : 

```
Found module_prefix : ios
Found C.NETWORK_GROUP_MODULES : [u"['eos'", u"'nxos'", u"'ios'", u"'iosxr'", u"'junos'", u"'vyos']"]
```

**Comment by calfonso** [comment]
@jmighion would you mind re-testing this in the devel branch? We believe it's fixed.

**Comment by rcarrillocruz** [comment]
needs_info

**Comment by jmighion** [comment]
I'll retest today hopefully. Sorry for the delay.

**Comment by jmighion** [comment]
Still persists on this morning's devel. I tried from a mac and from rhel. I added the same logging to both hosts' ansible/executor/task_executor.py : 
```
        module_prefix = self._task.action.split('_')[0]
        display.display('module_prefix : %s' % module_prefix)
        display.display('C.NETWORK_GROUP_MODULES : %s' % C.NETWORK_GROUP_MODULES)

        # let action plugin override module, fallback to 'normal' action plugin otherwise
        if self._task.action in self._shared_loader_obj.action_loader:
            handler_name = self._task.action
        elif all((module_prefix in C.NETWORK_GROUP_MODULES, module_prefix in self._shared_loader_obj.action_loader)):
            handler_name = module_prefix
        else:
            handler_name = 'normal'

        display.display('handler_name: %s' % handler_name)
```
Both hosts used the example ansible.cfg from the devel branch with only the following added : 
```
$ grep -v '#' ansible.cfg | grep  -e "\S"
[defaults]
inventory      = hosts
host_key_checking = False
log_path = ./ansible.log
retry_files_enabled = False
```

From the mac : 
```
$ ansible --version
 46233 1504892542.49112: starting run
ansible 2.5.0 (devel f58bd4f392) last updated 2017/09/08 09:46:04 (GMT -700)
  config file = /Users/james/Documents/Microsoft/local_ansible/ansible.cfg
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/james/Documents/git/ansible/lib/ansible
  executable location = /Users/james/Documents/git/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
A run **without** using the network_group_modules option in ansible.cfg : 
```
module_prefix : ios
C.NETWORK_GROUP_MODULES : ['eos', 'nxos', 'ios', 'iosxr', 'junos', 'ce', 'vyos', 'sros', 'dellos9', 'dellos10', 'dellos6', 'asa', 'aruba', 'aireos']
handler_name: ios
```
A run with the network_group_modules option in ansible.cfg added by just removing the comment : 
```
module_prefix : ios
C.NETWORK_GROUP_MODULES : ["['eos'", "'nxos'", "'ios'", "'iosxr'", "'junos'", "'vyos']"]
handler_name: normal
```


From the rhel host : 
```
$ ansible --version
 51278 1504892529.41093: starting run
ansible 2.5.0
  config file = /home/v-jamigh/git/Ansible-Networking/ansible.cfg
  configured module search path = [u'/home/v-jamigh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/v-jamigh/tmp/ansible/lib/ansible
  executable location = /home/v-jamigh/tmp/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
The extra logging output was exactly the same. The `handler_name` was `normal` instead of `ios`. This creates the following error in the playbook run : 
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_bHRUja/ansible_module_ios_command.py", line 234, in <module>
    main()
  File "/tmp/ansible_bHRUja/ansible_module_ios_command.py", line 203, in main
    responses = run_commands(module, commands)
  File "/tmp/ansible_bHRUja/ansible_modlib.zip/ansible/module_utils/ios.py", line 111, in run_commands
  File "/tmp/ansible_bHRUja/ansible_modlib.zip/ansible/module_utils/connection.py", line 66, in exec_command
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: argument must be string or read-only character buffer, not None

fatal: [tusredrwec23u1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bHRUja/ansible_module_ios_command.py\", line 234, in <module>\n    main()\n  File \"/tmp/ansible_bHRUja/ansible_module_ios_command.py\", line 203, in main\n    responses = run_commands(module, commands)\n  File \"/tmp/ansible_bHRUja/ansible_modlib.zip/ansible/module_utils/ios.py\", line 111, in run_commands\n  File \"/tmp/ansible_bHRUja/ansible_modlib.zip/ansible/module_utils/connection.py\", line 66, in exec_command\n  File \"/usr/lib64/python2.7/socket.py\", line 224, in meth\n    return getattr(self._sock,name)(*args)\nTypeError: argument must be string or read-only character buffer, not None\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```


Notice the difference in how the `C.NETWORK_GROUP_MODULES` is shown / typed. I wonder if the problem is how the group is formatted in the ansible.cfg or how it's pulled in / set in constants.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The configuration is not loaded incorrectly, you are just mixing python/yaml with ini formats. 
Ini does not support `['el1', 'el2']` as a list, use:
```ini
network_group_modules=eos, nxos, ios, iosxr, junos, vyos
```
In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by jmighion** [comment]
Should this ticket be opened against ansible.cfg? 
What was highlighted here was that the defaults in the config are incorrect and if you use the defaults they will break as described above.
