### ISSUE TITLE
null value in ec2_group causes TypeError

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#26291]
null `group_id` in `rules` list causes `TypeError`

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

Using latest devel version of ec2_group

https://github.com/ansible/ansible/blob/6b76bc924fdc7b1fbce71f1fb161e9b6c90b5058/lib/ansible/modules/cloud/amazon/ec2_group.py

##### SUMMARY

If you specify a empty (null) value for `group_id` inside `rules`. A `TypeError` will occur.

No other modules tested behave the same way and apply sensible defaults when presented with null values.

##### STEPS TO REPRODUCE

```yaml
- name: create security group
  ec2_group:
    description: foo
    name: bar
    purge_rules: true
    purge_rules_egress: true
    region: eu-central-1
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip:
          - 0.0.0.0/0
        group_id:
    rules_egress:
      - []
    state: present
    vpc_id: vpc-123456a
```

##### EXPECTED RESULTS

A security group is created.

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/9w/w2f_52y12pq86rn0glnxdgs40000gn/T/ansible_QMC0WD/ansible_module_ec2_group.py", line 632, in <module>
    main()
  File "/var/folders/9w/w2f_52y12pq86rn0glnxdgs40000gn/T/ansible_QMC0WD/ansible_module_ec2_group.py", line 505, in main
    group_id, ip, target_group_created = get_target_from_rule(module, ec2, rule, name, group, groups, vpc_id)
  File "/var/folders/9w/w2f_52y12pq86rn0glnxdgs40000gn/T/ansible_QMC0WD/ansible_module_ec2_group.py", line 280, in get_target_from_rule
    elif 'group_id' in rule and 'group_id' is not None and re.match(FOREIGN_SECURITY_GROUP_REGEX, rule['group_id']):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/9w/w2f_52y12pq86rn0glnxdgs40000gn/T/ansible_QMC0WD/ansible_module_ec2_group.py\", line 632, in <module>\n    main()\n  File \"/var/folders/9w/w2f_52y12pq86rn0glnxdgs40000gn/T/ansible_QMC0WD/ansible_module_ec2_group.py\", line 505, in main\n    group_id, ip, tar
get_group_created = get_target_from_rule(module, ec2, rule, name, group, groups, vpc_id)\n  File \"/var/folders/9w/w2f_52y12pq86rn0glnxdgs40000gn/T/ansible_QMC0WD/ansible_module_ec2_group.py\", line 280, in get_target_from_rule\n    elif 'group_id' in rule and 'group_id' is not None and re.match(FOREIGN_SECURITY_GROUP_REGEX, rule['group_id
']):\n  File \"/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py\", line 141, in match\n    return _compile(pattern, flags).match(string)\nTypeError: expected string or buffer\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

By removing the empty `group_id:` line from the task, the error goes away.

Line `280` should not try and run the regex check if `group_id` is null?

**Comment by aioue** [comment]
@ToddHertel this change now causes the task to fail instead of causing a stack trace, which is an improvement, if not a fix.

@bcoca politely suggest this needs re-opening and revision.

```
Using module file /Users/tom/repos/aws-codecommit/ansible-tower/library/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tom
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "failed_when_result": true,
    "group_id": "sg-12345678",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "Allow all",
            "ec2_url": null,
            "group_id": null,
            "name": "public",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": [
                        "0.0.0.0/0"
                    ],
                    "from_port": 22,
                    "group_id": null,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": [
                []
            ],
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-12345678"
        }
    }
}
```

This version of the module also fails with no message (even on -vvvvv) if `cidr_ip` is null (see https://github.com/ansible/ansible/issues/26286)

```
Using module file /Users/tom/repos/aws-codecommit/ansible-tower/library/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tom
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "failed_when_result": true,
    "group_id": "sg-12345678",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "Allow all",
            "ec2_url": null,
            "group_id": null,
            "name": "public",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": null,
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": [
                []
            ],
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-12345678"
        }
    }
}
```

**Comment by aioue** [comment]
Opened new issue following this change: https://github.com/ansible/ansible/issues/26431
