### ISSUE TITLE
ansible-playbook returns TypeError: 'module' object is not callable 

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#2645]
My playbooks were working fine before updating my ansible repo with last night's changes:

here's the error:

```
ansible-playbook -vv -u vagrant /tmp/simple.yaml -i ~/work/vms/ansible-riak/hosts -k
SSH password: 
Traceback (most recent call last):
  File "/Users/jmartin/work/code/my-ansible/bin/ansible-playbook", line 221, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/jmartin/work/code/my-ansible/bin/ansible-playbook", line 182, in main
    pb.run()
  File "/Users/jmartin/work/code/my-ansible/lib/ansible/playbook/__init__.py", line 215, in run
    play = Play(self, play_ds, play_basedir)
  File "/Users/jmartin/work/code/my-ansible/lib/ansible/playbook/play.py", line 96, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Users/jmartin/work/code/my-ansible/lib/ansible/playbook/play.py", line 236, in _load_tasks
    results.append(Task(self,x,module_vars=task_vars, additional_conditions=additional_conditions))
  File "/Users/jmartin/work/code/my-ansible/lib/ansible/playbook/task.py", line 101, in __init__
    self.sudo_user    = utils.template(play.basedir, ds.get('sudo_user', play.sudo_user), play.vars)
TypeError: 'module' object is not callable
```

version info:

```
ansible-playbook --version
ansible-playbook 1.2 (riak 3a8529f4d6) last updated 2013/04/11 10:41:49 (GMT -400)
```

I have a stripped down playbook as follows:

```
cat /tmp/simple.yaml 

---
- hosts: riak_cluster
  vars:
  sudo: True
  tasks:
  - debug: msg="ansible is broken."
```

and for what it's worth:

```
cat ~/work/vms/ansible-riak/hosts
[riak_cluster]
10.42.0.6 node_type=primary
10.42.0.7 node_type=middle
10.42.0.8 node_type=last

[riak_servers:children]
riak_cluster
```

**Comment by mpdehaan** [comment]
ok, thanks, this is related to template code upgrades and I missed a reference.  Working on this now.

**Comment by mpdehaan** [comment]
this was fixed yesterday, so closing
