### ISSUE TITLE
b09ef21 breaks pause

### ISSUE THREAD

**Issue by blair** [ansible/ansible#2657]
Doing a `git bisect start a05361f51500 v1.1` found that b09ef21 breaks this playbook:

``` ---
- hosts: all
  user: ubuntu
  sudo: True
  serial: 1

  tasks:
    - name: sleep for 15 seconds
      action: pause seconds=1
```

Here's the output:

```
$ ansible-playbook -i hosts.ini -l 192.168.2.2 playbooks/99-rolling-reboot.yml 
Traceback (most recent call last):
  File "/home/blair/Code/Ansible/ansible.git/bin/ansible-playbook", line 226, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/blair/Code/Ansible/ansible.git/bin/ansible-playbook", line 182, in main
    pb.run()
  File "/home/blair/Code/Ansible/ansible.git/lib/ansible/playbook/__init__.py", line 215, in run
    play = Play(self, play_ds, play_basedir)
  File "/home/blair/Code/Ansible/ansible.git/lib/ansible/playbook/play.py", line 96, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/home/blair/Code/Ansible/ansible.git/lib/ansible/playbook/play.py", line 236, in _load_tasks
    results.append(Task(self,x,module_vars=task_vars, additional_conditions=additional_conditions))
  File "/home/blair/Code/Ansible/ansible.git/lib/ansible/playbook/task.py", line 101, in __init__
    self.sudo_user    = utils.template(play.basedir, ds.get('sudo_user', play.sudo_user), play.vars)
TypeError: 'module' object is not callable
```

I'm not completely certain on the exact sha1 since multiple bisects found different sha1s, but this is a new issue since 1.1.

**Comment by mpdehaan** [comment]
Ok, this is a simple replacement, will take care of it, thanks!

**Comment by mpdehaan** [comment]
Fix pushed, thanks!
