### ISSUE TITLE
authorized_key: UnboundLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by iliv** [ansible/ansible#2694]
This pertains to the code with last commit a05361f51500c5a9f227f87f1ea91a45870602ce

When trying to use authorized_key module

```
   - authorized_key: user=$usr key='$ssh_pk'
     tags: sshpk
```

I get this

```
fatal: [org] => failed to parse: 
Traceback (most recent call last):
  File "/home/ansiblemgr/.ansible/tmp/ansible-1366119919.08-129363718910249/authorized_key", line 1053, in ?
    main()
  File "/home/ansiblemgr/.ansible/tmp/ansible-1366119919.08-129363718910249/authorized_key", line 215, in main
    results = enforce_state(module, module.params)
  File "/home/ansiblemgr/.ansible/tmp/ansible-1366119919.08-129363718910249/authorized_key", line 190, in enforce_state
    writekeys(module, keyfile(module, user, write, path, manage_dir), keys)
  File "/home/ansiblemgr/.ansible/tmp/ansible-1366119919.08-129363718910249/authorized_key", line 135, in keyfile
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
```

Rolled back to 1.1 and everything works as before, i.e. it works and does what it is designed to do.

**Comment by mpdehaan** [comment]
You will need to update your checkout as changes have been made since to address this.
