### ISSUE TITLE
Tasks hits an error and fails to register

### ISSUE THREAD

**Issue by lwade** [ansible/ansible#2704]
Hi,

I have a playbook containing a particular task which registers the return.  I then want to key off the return code with a conditional/when.

The interesting thing is that the output of the tool which I run is a message to stderr.  It seems that this stops the task return from registering and thus I'm unable to then perform a conditional evaluation of this later.

Here are are the two playbook tasks in question:

```
- name: Check Walrus Registration
  action: shell /usr/sbin/euca_conf --list-services | grep -q walrus-${hostvars.{$item}.ansible_hostname}
  ignore_errors: yes
  register: walrus_check
  with_items: ${groups.walrus}
  tags:
  - reg

- name: Register Walrus
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-walrus --partition walrus --host ${hostvars.{$item}.ansible_$vnet_pub.ipv4.address} --component walrus-${hostvars.{$item}.ansible_hostname}
  with_items: ${groups.walrus}
  when: walrus_check.rc == 1
  tags:
  - reg
```

So in the last task I'm expecting rc to be an integer but it gave me the following output:

```
TASK: [Check Walrus Registration] ********************* 
<g-08-10.prc.eucalyptus-systems.com> ESTABLISH CONNECTION FOR USER: lwade on PORT 22 TO g-08-10.prc.eucalyptus-systems.com
<g-08-10.prc.eucalyptus-systems.com> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1366213653.99-4355511466477 && chmod a+rx $HOME/.ansible/tmp/ansible-1366213653.99-4355511466477 && echo $HOME/.ansible/tmp/ansible-1366213653.99-4355511466477'
<g-08-10.prc.eucalyptus-systems.com> REMOTE_MODULE command /usr/sbin/euca_conf --list-services | grep -q walrus-g-08-10 #USE_SHELL
<g-08-10.prc.eucalyptus-systems.com> PUT /tmp/tmpYwSnM4 TO /home/lwade/.ansible/tmp/ansible-1366213653.99-4355511466477/command
<g-08-10.prc.eucalyptus-systems.com> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=nortatrpliclzpfogzaxmyjnyjynsydg] password: " -u root /bin/sh -c '"'"' /usr/bin/python /home/lwade/.ansible/tmp/ansible-1366213653.99-4355511466477/command; rm -rf /home/lwade/.ansible/tmp/ansible-1366213653.99-4355511466477/ >/dev/null 2>&1'"'"''
failed: [g-08-10.prc.eucalyptus-systems.com] => (item=g-08-10.prc.eucalyptus-systems.com) => {"changed": true, "cmd": "/usr/sbin/euca_conf --list-services | grep -q walrus-g-08-10 ", "delta": "0:00:01.419670", "end": "2013-04-17 08:47:35.683760", "item": "g-08-10.prc.eucalyptus-systems.com", "rc": 1, "start": "2013-04-17 08:47:34.264090"}
stderr: No credentials found, attempting local authentication
...ignoring


TASK: [Register Walrus] ********************* 
fatal: [g-08-10.prc.eucalyptus-systems.com] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 304, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 376, in _executor_internal
    result = self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=self.complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 427, in _executor_internal_inner
    if not utils.check_conditional(conditional):
  File "/usr/lib/python2.6/site-packages/ansible/utils/__init__.py", line 164, in check_conditional
    return eval(conditional.replace("\n", "\\n"))
  File "<string>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '${walrus_check.rc}'
```

I added a debug statement to check this:

```
TASK: [Debug] ********************* 
<g-08-10.prc.eucalyptus-systems.com> ESTABLISH CONNECTION FOR USER: lwade on PORT 22 TO g-08-10.prc.eucalyptus-systems.com
ok: [g-08-10.prc.eucalyptus-systems.com] => {"item": "", "msg": "return is walrus_check.rc = ${walrus_check.rc}"}
```

So it seems that walrus_check does not register correctly.  The conditional evaluation in the final task is expecting an int but ends up with the '${walrus_check.rc}' string itself.

You'll notice in my output that the tool I'm calling with shell outputs to stderr, which is perhaps what confuses things:

```
failed: [g-08-10.prc.eucalyptus-systems.com] => (item=g-08-10.prc.eucalyptus-systems.com) => {"changed": true, "cmd": "/usr/sbin/euca_conf --list-services | grep -q walrus-g-08-10 ", "delta": "0:00:01.419670", "end": "2013-04-17 08:47:35.683760", "item": "g-08-10.prc.eucalyptus-systems.com", "rc": 1, "start": "2013-04-17 08:47:34.264090"}
stderr: No credentials found, attempting local authentication
```

I want it to ignore this and allow me to still use the return code from the task.

**Comment by mpdehaan** [comment]
Ok so the underlying thing is that the registration code lives in playbook/**init**.py and only registers successful results.

We could make ignored errors not errors (which is not a very compatible thing to do, I think), or we could make them errors and make them also register, which means we need to inject something in the return to indicate that the error was ignored, like 'was_ignored=True' that could make that loop in playbook code also run across this.

Doing that.

**Comment by mpdehaan** [comment]
Change pushed!

Good catch, thanks for bringing this up.
