### ISSUE TITLE
UnicodeError ios_command

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#27118]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel aed35aba70) last updated 2017/07/20 09:27:04 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### STEPS TO REPRODUCE

`ansible-playbook -i inventory.network  iosxr.yaml -vvvv -u root -k -e limit_to=iosxr_command`

```yaml

```

##### ACTUAL RESULTS

```
TASK [iosxr_command : get output for multiple commands] **********************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/iosxr_command/tests/cli/output.yaml:14
<iosxr01> using connection plugin network_cli
<iosxr01> socket_path: /Users/dnewswan/.ansible/pc/c519def7ce
Using module file /Users/dnewswan/code/ansible/lib/ansible/modules/network/iosxr/iosxr_command.py
<iosxr01> ESTABLISH LOCAL CONNECTION FOR USER: dnewswan
<iosxr01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<iosxr01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151 `" && echo ansible-tmp-1500564512.81-129367623740151="` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151 `" ) && sleep 0'
<iosxr01> PUT /var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/tmpsvhXiZ TO /Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151/iosxr_command.py
<iosxr01> EXEC /bin/sh -c 'chmod u+x /Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151/ /Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151/iosxr_command.py && sleep 0'
<iosxr01> EXEC /bin/sh -c 'python /Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151/iosxr_command.py; rm -rf "/Users/dnewswan/.ansible/tmp/ansible-tmp-1500564512.81-129367623740151/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_qtA4lm/ansible_module_iosxr_command.py", line 228, in <module>
    main()
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_qtA4lm/ansible_module_iosxr_command.py", line 222, in main
    'stdout_lines': list(to_lines(responses))
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_qtA4lm/ansible_module_iosxr_command.py", line 144, in to_lines
    item = str(item).split('\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 5055: ordinal not in range(128)

fatal: [iosxr01]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_qtA4lm/ansible_module_iosxr_command.py\", line 228, in <module>\n    main()\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_qtA4lm/ansible_module_iosxr_command.py\", line 222, in main\n    'stdout_lines': list(to_lines(responses))\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_qtA4lm/ansible_module_iosxr_command.py\", line 144, in to_lines\n    item = str(item).split('\\n')\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe6' in position 5055: ordinal not in range(128)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

**Comment by newswangerd** [comment]
I can fix this one
