### ISSUE TITLE
Using play-level tags returns an error

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#2735]
Adding a tag to a play now results in an error. (Adding a tag to a task works fine).

Here's an example of a failing playbook:

```

---
- hosts: all
  tags:
    - mytag
  tasks:
    - action: ping
```

Running this playbook yields the following output:

```
$ ansible-playbook test.yaml
Traceback (most recent call last):
  File "/Users/lorin/ansible/bin/ansible-playbook", line 225, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/lorin/ansible/bin/ansible-playbook", line 186, in main
    pb.run()
  File "/Users/lorin/ansible/lib/ansible/playbook/__init__.py", line 215, in run
    play = Play(self, play_ds, play_basedir)
  File "/Users/lorin/ansible/lib/ansible/playbook/play.py", line 104, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Users/lorin/ansible/lib/ansible/playbook/play.py", line 286, in _load_tasks
    x.tags.extend(self.tags)
AttributeError: tags
```

Version info:

```
$ ansible --version
ansible 1.2 (devel 97f9b6df1c) last updated 2013/04/21 13:53:51 (GMT -400)
```

**Comment by mpdehaan** [comment]
Fix pushed in 6166057 thanks!
