### ISSUE TITLE
No closing quotation error because `#` is treated as a comment even inside a string

### ISSUE THREAD

**Issue by gw0** [ansible/ansible#2770]
The character `#` is treated as a comment even if it is inside a string. As a consequence the rest of the command line gets stripped away and a `No closing quotation` error appears.

```
$ cat _test.yml 

---
- hosts: all
  gather_facts: no
  tasks:
    - lineinfile: dest=/tmp/foo regexp="bar" line="bar # comment about bar"
```

With latest Ansible 1.2 development branch:

```
$ ansible-playbook -vvv _test.yml 

PLAY [all] ******************************************************************** 

TASK: [lineinfile dest=/tmp/foo regexp="bar" line="bar] *********************** 
<xxx.lan> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO xxx.lan
<xxx.lan> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1366795278.56-129433001277548 && chmod a+rx $HOME/.ansible/tmp/ansible-1366795278.56-129433001277548 && echo $HOME/.ansible/tmp/ansible-1366795278.56-129433001277548'
<xxx.lan> REMOTE_MODULE lineinfile dest=/tmp/foo regexp="bar" line="bar
<xxx.lan> PUT /tmp/tmp0GK3Pi TO /root/.ansible/tmp/ansible-1366795278.56-129433001277548/lineinfile
<xxx.lan> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1366795278.56-129433001277548/lineinfile; rm -rf /root/.ansible/tmp/ansible-1366795278.56-129433001277548/ >/dev/null 2>&1'
failed: [xxx] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1366795278.56-129433001277548/lineinfile", line 1167, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1366795278.56-129433001277548/lineinfile", line 293, in main
    supports_check_mode=True
  File "/root/.ansible/tmp/ansible-1366795278.56-129433001277548/lineinfile", line 467, in __init__
    (self.params, self.args) = self._load_params()
  File "/root/.ansible/tmp/ansible-1366795278.56-129433001277548/lineinfile", line 933, in _load_params
    items   = shlex.split(args)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by b6d** [comment]
For me this seems to be similar to issue #2769. 

There is exactly one YAML-string expected after `lineinfile:`. This one string itself may contain quotes. In your example, this one String starts implicitly with `dest`... and ends with the `#`-Sign.

I think what you need in this case is to state your string explicitly like this:

```
- lineinfile: 'dest=/tmp/foo regexp="bar" line="bar # comment about bar"'
```

or like this:

```
- lineinfile: "dest=/tmp/foo regexp=\"bar\" line=\"bar # comment about bar\""
```

(note the quotes).

**Comment by mpdehaan** [comment]
Right you need to quote the whole line in this case.

**Comment by gw0** [comment]
Oh, it makes sense. Thank you the explanation in both tickets. Maybe it should be added to the docs in a common mistakes section?

**Comment by jlsam** [comment]
I ran into a similar issue when issuing `mkpasswd --method=sha-512 {{ admin_password }}` when password happened to contain ". I guess I could wrap the whole command in ' ' to escape the ", but what if the random password contains ' instead of " ?
