### ISSUE TITLE
ansible does traceback when logging to systemd fails

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#2773]
This is related to: https://bugzilla.redhat.com/show_bug.cgi?id=924359

Even if this is fixed in systemd, ansible should still handle the case where logging to systemd's journal fails.  I'll come up with a patch for this that wraps the journal.sendv() call in a try/except.  For the fallback, I think it should send the message to syslog.

Here's the traceback:

```
GATHERING FACTS ***************************************************************
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/stephenf/.ansible/tmp/ansible-1366839780.64-144522374119376/setup", line 2468, in <module>
    main()
  File "/home/stephenf/.ansible/tmp/ansible-1366839780.64-144522374119376/setup", line 1614, in main
    supports_check_mode = True,
  File "/home/stephenf/.ansible/tmp/ansible-1366839780.64-144522374119376/setup", line 1791, in __init__
    self._log_invocation()
  File "/home/stephenf/.ansible/tmp/ansible-1366839780.64-144522374119376/setup", line 2280, in _log_invocation
    journal.sendv(*journal_args)
IOError: [Errno 111] Connection refused
```

**Comment by mpdehaan** [comment]
fixed per above merge, so closing, thanks
