### ISSUE TITLE
Error gathering facts on OpenVZ container with venet interface

### ISSUE THREAD

**Issue by prologic** [ansible/ansible#2783]
```
GATHERING FACTS *************************************************************** 
failed: [10.0.0.2] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1366953606.61-249290732362552/setup", line 2468, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1366953606.61-249290732362552/setup", line 1616, in main
    data = run_setup(module)
  File "/root/.ansible/tmp/ansible-1366953606.61-249290732362552/setup", line 1561, in run_setup
    facts = ansible_facts()
  File "/root/.ansible/tmp/ansible-1366953606.61-249290732362552/setup", line 1552, in ansible_facts
    facts.update(Network().populate())
  File "/root/.ansible/tmp/ansible-1366953606.61-249290732362552/setup", line 952, in populate
    interfaces, ips = self.get_interfaces_info(ip_path, default_ipv4, default_ipv6)
  File "/root/.ansible/tmp/ansible-1366953606.61-249290732362552/setup", line 1071, in get_interfaces_info
    default_ipv4['type'] = interfaces[device]['type']
KeyError: 'type'
```

**Comment by prologic** [comment]
The following patch to the setup module seems to fix this:

``` diff
diff --git a/library/setup b/library/setup
--- a/library/setup
+++ b/library/setup
@@ -1068,7 +1068,7 @@
                         default_ipv4['network'] = network
                         default_ipv4['macaddress'] = macaddress
                         default_ipv4['mtu'] = interfaces[device]['mtu']
-                        default_ipv4['type'] = interfaces[device]['type']
+                        default_ipv4['type'] = interfaces[device].get("type", "unknown")
                         default_ipv4['alias'] = words[-1]

                     if not address.startswith('127.'):
```

**Comment by prologic** [comment]
I noticed while debugging this that the interfaces dict does not contain "type" for the type of interface in question here **venet**. --JamesMills / prologic

**Comment by mpdehaan** [comment]
Sounds good, would you like to submit a pull request for this so it can be properly attributed?

**Comment by prologic** [comment]
Sure. Ill try to do this Mon when i get back to work.

Sent from my iPad

On 26/04/2013, at 22:27, Michael DeHaan notifications@github.com wrote:

Sounds good, would you like to submit a pull request for this so it can be
properly attributed?

—
Reply to this email directly or view it on
GitHubhttps://github.com/ansible/ansible/issues/2783#issuecomment-17071720
.

**Comment by mpdehaan** [comment]
closing per above fix, thank you!
