### ISSUE TITLE
 local variable 'async_result' referenced before assignment

### ISSUE THREAD

**Issue by Chanmoro** [ansible/ansible#27835]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

```

##### OS / ENVIRONMENT

Mac 10.11.6 (El Capitan)

##### SUMMARY

When execute async task, this python error has occored.
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 541, in _execute
    result = self._poll_async_result(result=result, templar=templar, task_vars=vars_copy)
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 684, in _poll_async_result
    if int(async_result.get('finished', 0)) != 1:
UnboundLocalError: local variable 'async_result' referenced before assignment
```

##### STEPS TO REPRODUCE

Execute tasks defined below yaml.
This task expects reboot server and wait for it by check ssh port up.

```yaml
---
- name: test connection (before reboot)
  ping:

- name: reboot after 2 sec
  shell: sleep 2s && /sbin/reboot
  async: 1

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  become: no

- name: wait for SSH port up
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=30
  delegate_to: 127.0.0.1
  become: no

- name: test connection (after reboot)
  ping:
```

##### EXPECTED RESULTS

My expectation is finish this task without error.

##### ACTUAL RESULTS

Error has occered when execute task.
Here is console output with -vvvv option.

```
TASK [reboot-server : test connection (before reboot)] *************************************************************************************************************************************************************************************************************************
task path: /Users/kazuki.morozumi/Documents/ansible/ubuntu-basic/roles/reboot-server/tasks/main.yml:2
Using module file /Library/Python/2.7/site-packages/ansible/modules/system/ping.py
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.56.101> (0, '/home/ubuntu\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844 `" && echo ansible-tmp-1502097175.6-210358602749844="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844 `" ) && sleep 0'"'"''
<192.168.56.101> (0, 'ansible-tmp-1502097175.6-210358602749844=/home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> PUT /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmp1mA11W TO /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/ping.py
<192.168.56.101> SSH: EXEC sshpass -d47 sftp -o BatchMode=no -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef '[192.168.56.101]'
<192.168.56.101> (0, 'sftp> put /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmp1mA11W /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/ping.py\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 8 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/ubuntu size 0\r\ndebug3: Looking up /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmp1mA11W\r\ndebug3: Sent message fd 8 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/ping.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:23158\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 23158 bytes at 32768\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/ /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/ping.py && sleep 0'"'"''
<192.168.56.101> (0, '', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef -tt 192.168.56.101 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=ackhljouumwdzfkazuagckevgbwsjtpw] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ackhljouumwdzfkazuagckevgbwsjtpw; /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/ping.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.6-210358602749844/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<192.168.56.101> (0, '\r\n\r\n{"invocation": {"module_args": {"data": null}}, "changed": false, "ping": "pong"}\r\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 192.168.56.101 closed.\r\n')
ok: [192.168.56.101] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": null
        }
    }, 
    "ping": "pong"
}

TASK [reboot-server : reboot after 2 sec] **************************************************************************************************************************************************************************************************************************************
task path: /Users/kazuki.morozumi/Documents/ansible/ubuntu-basic/roles/reboot-server/tasks/main.yml:5
Using module file /Library/Python/2.7/site-packages/ansible/modules/commands/command.py
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.56.101> (0, '/home/ubuntu\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198 `" && echo ansible-tmp-1502097175.8-180447717042198="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198 `" ) && sleep 0'"'"''
<192.168.56.101> (0, 'ansible-tmp-1502097175.8-180447717042198=/home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> PUT /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmpjGcVT8 TO /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/command.py
<192.168.56.101> SSH: EXEC sshpass -d47 sftp -o BatchMode=no -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef '[192.168.56.101]'
<192.168.56.101> (0, 'sftp> put /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmpjGcVT8 /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/command.py\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 8 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/ubuntu size 0\r\ndebug3: Looking up /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmpjGcVT8\r\ndebug3: Sent message fd 8 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/command.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:25552\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 25552 bytes at 32768\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> PUT /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmpxqbYr3 TO /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/async_wrapper.py
<192.168.56.101> SSH: EXEC sshpass -d47 sftp -o BatchMode=no -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef '[192.168.56.101]'
<192.168.56.101> (0, 'sftp> put /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmpxqbYr3 /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/async_wrapper.py\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 8 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/ubuntu size 0\r\ndebug3: Looking up /var/folders/nt/jj6k5z5s5rn3sgw19pxcvby80000gp/T/tmpxqbYr3\r\ndebug3: Sent message fd 8 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/async_wrapper.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:10799\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 10799 bytes at 0\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/ /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/command.py /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/async_wrapper.py && sleep 0'"'"''
<192.168.56.101> (0, '', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef -tt 192.168.56.101 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=xscxoaycmimezwzekzkmmaomqungtnze] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xscxoaycmimezwzekzkmmaomqungtnze; /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/async_wrapper.py 386233460093 1 /home/ubuntu/.ansible/tmp/ansible-tmp-1502097175.8-180447717042198/command.py _'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<192.168.56.101> (0, '\r\n{"started": 1, "_ansible_suppress_tmpdir_delete": true, "finished": 0, "results_file": "/root/.ansible_async/386233460093.4516", "ansible_job_id": "386233460093.4516"}\r\n', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1922\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 192.168.56.101 closed.\r\n')
Using module file /Library/Python/2.7/site-packages/ansible/modules/utilities/logic/async_status.py
<192.168.56.101> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.56.101> SSH: EXEC sshpass -d47 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef 192.168.56.101 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.56.101> (255, '', 'OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to 192.168.56.101 [192.168.56.101] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.56.101 port 22: Connection refused\r\nssh: connect to host 192.168.56.101 port 22: Connection refused\r\n')
Exception during async poll, retrying... (Failed to connect to the host via ssh: OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/kazuki.morozumi/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/Users/kazuki.morozumi/.ansible/cp/eca9ba44ef" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.56.101 [192.168.56.101] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 192.168.56.101 port 22: Connection refused
ssh: connect to host 192.168.56.101 port 22: Connection refused
)
The full traceback is:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 541, in _execute
    result = self._poll_async_result(result=result, templar=templar, task_vars=vars_copy)
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 684, in _poll_async_result
    if int(async_result.get('finished', 0)) != 1:
UnboundLocalError: local variable 'async_result' referenced before assignment

fatal: [192.168.56.101]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/Users/kazuki.morozumi/Documents/ansible/ubuntu-basic/playbook.retry
```

```

```

**Comment by jborean93** [comment]
I believe this may be because the SSH connection is closed so it cannot gather info on the task when the connection is closed. If you add in `poll: 0` to your async task so it becomes a fire and forget it should work.

There is also a new module called `wait_for_connection` which will wait for the connection to come online and that it works. I would recommend using this over `wait_for`, an example of this working would be

```
---
- name: test out reboot
  hosts: fedora
  become_user: root
  become_method: sudo
  tasks:
  - ping:

  - name: reboot server
    shell: sleep 2s && /sbin/shutdown -r now
    async: 1
    poll: 0
    become: yes
  
  - name: wait for SSH port to close during reboot
    wait_for:
      host: '{{inventory_hostname}}'
      port: 22
      state: stopped
    delegate_to: localhost
  
  - name: wait for connection to come back online after reboot
    wait_for_connection:
      delay: 30

  - ping:
```

**Comment by Chanmoro** [comment]
Thanks @jborean93 !

It has work fine, by adding ```poll: 0```.
Also thank you for additional tips. I'll use ```wait_for_connection``` instead.
