### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: u'prompt_ask_vault_pass'

### ISSUE THREAD

**Issue by jamieburchell** [ansible/ansible#27885]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel e8410c210d) last updated 2017/08/08 12:37:14 (GMT +100)
  config file = None
  configured module search path = [u'/home/jamie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jamie/ansible/lib/ansible
  executable location = /home/jamie/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

WSL on Windows 10 x64

##### SUMMARY

ansible-vault edit and encrypt no longer working

##### STEPS TO REPRODUCE

```
$ ansible-vault edit host_vars/project/vault.yml -vvv
ansible-vault 2.4.0 (devel e8410c210d) last updated 2017/08/08 12:37:14 (GMT +100)
  config file = None
  configured module search path = [u'/home/jamie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jamie/ansible/lib/ansible
  executable location = /home/jamie/ansible/bin/ansible-vault
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
No config file found; using defaults
Usage: ansible-vault edit [options] file_name

encryption/decryption utility for Ansible data files

Options:
  --ask-vault-pass      ask for vault password
  -h, --help            show this help message and exit
  --new-vault-id=NEW_VAULT_ID
                        the new vault identity to use for rekey
  --new-vault-password-file=NEW_VAULT_PASSWORD_FILES
                        new vault password file for rekey
  --output=OUTPUT_FILE  output file name for encrypt or decrypt; use - for
                        stdout
  --vault-id=VAULT_IDS  the vault identity to use
  --vault-password-file=VAULT_PASSWORD_FILES
                        vault password file
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit

 See 'ansible-vault <command> --help' for more information on a specific
command.
ERROR! A vault password is required to use Ansible's Vault
```

```
$ ansible-vault edit --ask-vault-pass host_vars/project/vault.yml -vvv
ansible-vault 2.4.0 (devel e8410c210d) last updated 2017/08/08 12:37:14 (GMT +100)
  config file = None
  configured module search path = [u'/home/jamie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jamie/ansible/lib/ansible
  executable location = /home/jamie/ansible/bin/ansible-vault
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
No config file found; using defaults
ERROR! Unexpected Exception, this is probably a bug: u'prompt_ask_vault_pass'
the full traceback was:

Traceback (most recent call last):
  File "/home/jamie/ansible/bin/ansible-vault", line 106, in <module>
    exit_code = cli.run()
  File "/home/jamie/ansible/lib/ansible/cli/vault.py", line 180, in run
    create_new_password=True)
  File "/home/jamie/ansible/lib/ansible/cli/__init__.py", line 237, in setup_vault_secrets
    prompted_vault_secret = PromptVaultSecret(prompt_formats=prompt_formats[vault_id_value],
KeyError: u'prompt_ask_vault_pass'
```

##### EXPECTED RESULTS

Was expecting to be prompted automatically, expected `--ask-vault-pass` to work when added

##### ACTUAL RESULTS
Exception

##### NOTES
`$ ansible-vault decrypt ./host_vars/project/vault.yml --ask-vault-pass` worked as expected

However

`$ ansible-vault encrypt ./host_vars/project/vault.yml`

```
Usage: ansible-vault encrypt [options] file_name

encryption/decryption utility for Ansible data files

Options:
  --ask-vault-pass      ask for vault password
  -h, --help            show this help message and exit
  --new-vault-id=NEW_VAULT_ID
                        the new vault identity to use for rekey
  --new-vault-password-file=NEW_VAULT_PASSWORD_FILES
                        new vault password file for rekey
  --output=OUTPUT_FILE  output file name for encrypt or decrypt; use - for
                        stdout
  --vault-id=VAULT_IDS  the vault identity to use
  --vault-password-file=VAULT_PASSWORD_FILES
                        vault password file
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit

 See 'ansible-vault <command> --help' for more information on a specific
command.
ERROR! A vault password is required to use Ansible's Vault
```

`$ ansible-vault encrypt ./host_vars/project/vault.yml --ask-vault-pass`

```
ERROR! Unexpected Exception, this is probably a bug: u'prompt_ask_vault_pass'
to see the full traceback, use -vvv
```

Rolling back to tag v2.3.2.0-1 seems to fix these issues.

**Comment by TheCapsLock** [comment]
I confirm this issue on ansible 2.4.0 (devel babec35faa)
I can use *ansible-vault view* but not *ansible-vault edit* : 

```bash
ansible-vault edit host_vars/myhost/myhost_vault.yml                                           
Usage: ansible-vault edit [options] file_name

encryption/decryption utility for Ansible data files

Options:
  --ask-vault-pass      ask for vault password
  -h, --help            show this help message and exit
  --new-vault-id=NEW_VAULT_ID
                        the new vault identity to use for rekey
  --new-vault-password-file=NEW_VAULT_PASSWORD_FILES
                        new vault password file for rekey
  --output=OUTPUT_FILE  output file name for encrypt or decrypt; use - for
                        stdout
  --vault-id=VAULT_IDS  the vault identity to use
  --vault-password-file=VAULT_PASSWORD_FILES
                        vault password file
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit

 See 'ansible-vault <command> --help' for more information on a specific
command.
ERROR! A vault password is required to use Ansible's Vault
```

If --ask-vault-pass option is provided, I get following error : 

```bash
ansible-vault edit --ask-vault-pass host_vars/myhost/myhost_vault.yml
ERROR! Unexpected Exception, this is probably a bug: u'prompt_ask_vault_pass'
```

**Comment by TheCapsLock** [comment]
I think it is related to 934b64519191b0df70495deecbb349532af48597

**Comment by TheCapsLock** [comment]
I can edit vault using *--vault-id=prompt* but I get weird prompts : 

```bash
ansible-vault edit --vault-id=prompt host_vars/myhost/myhost_vault.yml
New vault password (default):
Confirm vew vault password (default):
```
By answering with my vault password to these two prompts, editor opens and vault can be edited

**Comment by alikins** [comment]
The changes in 9f57920eab686f09e3eeb174b43d4e0ab8e2dde6 busted this, https://github.com/ansible/ansible/pull/27974 shoud fix.

**Comment by alikins** [comment]
https://github.com/ansible/ansible/pull/28185 was related fix as well

**Comment by juber9797** [comment]
hi all,
i am trying to set password using ansible-vault.
i am getting below.
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: '/etc/ansible/install_httpd.yaml'

i have set 777 for the yml file also tried sudo and normal way.

**Comment by juber9797** [comment]
my ansible version is 2.5.3
