### ISSUE TITLE
Would like non-traceback error when can't write to log file

### ISSUE THREAD

**Issue by rcuza** [ansible/ansible#2879]
**Problem** : Traceback error generated when running ansible as a user that can't write to the log file.

**How to Reproduce** :
- In `/etc/ansible/ansible.cfg`, set log_path to a file owned by root with 0644 permissions.
- Run ansible as non-root user

The following results:

``` shell
$ ansible --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 24, in <module>
    from ansible.runner import Runner
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 43, in <module>
    from ansible.callbacks import DefaultRunnerCallbacks, vv
  File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 33, in <module>
    logging.basicConfig(filename=constants.DEFAULT_LOG_PATH, level=logging.DEBUG, format='%(asctime)s %(name)s %(message)s')
  File "/usr/lib/python2.7/logging/__init__.py", line 1528, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/ansible.log'
```

**Comment by mpdehaan** [comment]
Yeah you need to fix permissions in this case.

I do believe you should get errors as you requested logging you shouldn't write to.

**Comment by rcuza** [comment]
I agree that one needs an error. I am suggesting that it shouldn't be a Traceback error. This is my first dive into the code, so I'm still learning the community's preferences.

The code which generates the error does two file opens within four lines. What is the intention here?

**Comment by mpdehaan** [comment]
you will now get a fatal error when this occurs instead.
