### ISSUE TITLE
local_action: include_role fails with 'this is probably a bug'

### ISSUE THREAD

**Issue by ctx** [ansible/ansible#28822]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
local_action: iclude_role

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel b35f39479b) last updated 2017/08/30 15:12:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Repos/ansible/lib/ansible
  executable location = /home/user/Repos/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

You cannot have a task that runs a role as local_action.

A workaround is `delegate_to: 127.0.0.1`.

##### STEPS TO REPRODUCE

```
.
├── playbook.yml
└── roles
    └── test
        └── tasks
            └── main.yml
```

* playbook.yml
```yaml
---

- name: Local action include role
  hosts: all
  tasks:
    - name: Trigger bug
      local_action: include_role name=test
```
* main.yml
```yaml
---

- debug: msg="will not be printed"
```

##### EXPECTED RESULTS

Ansible should execute the role and print the message 'will not be printed'
##### ACTUAL RESULTS

```
$ ansible-playbook -i "localhost," -c local playbook.yml -vvv
ansible-playbook 2.4.0 (devel b35f39479b) last updated 2017/08/30 15:12:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Repos/ansible/lib/ansible
  executable location = /home/user/Repos/ansible/bin/ansible-playbook
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
Parsed localhost, inventory source with host_list plugin

PLAYBOOK: playbook.yml ************************************************************************
1 plays in playbook.yml

PLAY [Local action include role] **************************************************************

TASK [Gathering Facts] ************************************************************************
Using module file /home/user/Repos/ansible/lib/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608 `" && echo ansible-tmp-1504099569.5-119095676611608="` echo /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608 `" ) && sleep 0'
<localhost> PUT /tmp/tmpnGFBA0 TO /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/ /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/setup.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Trigger bug] ****************************************************************************
task path: /home/user/Test/ansible-block/playbook.yml:6
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7fbe3cf06ad0>): TASK: Trigger
bug is not JSON serializable

ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'get_block_list'
the full traceback was:

Traceback (most recent call last):
  File "/home/user/Repos/ansible/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/home/user/Repos/ansible/lib/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/home/user/Repos/ansible/lib/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/home/user/Repos/ansible/lib/ansible/executor/task_queue_manager.py", line 289, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/user/Repos/ansible/lib/ansible/plugins/strategy/linear.py", line 318, in run
    blocks, handler_blocks = new_ir.get_block_list(play=iterator._play, variable_manager=self._variable_manager, loader=self._loader)
AttributeError: 'Task' object has no attribute 'get_block_list'
```

**Comment by mkrizek** [comment]
cc @bcoca

**Comment by jeffmhastings** [comment]
~~is there any workaround?~~ I got past this using `delegate_to: 127.0.0.1` instead of local_action

**Comment by Everspace** [comment]
I've gotten this now too

OS Environment: WSL Ubuntu 14.04.5 LTS
Ansible version: 2.4.1.0
python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```
task path: /mnt/c/git/ansible/plays/website_unarchive.yml:41
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7f985311b990>): TASK: Ensure db is present is not
JSON serializable

Callback Exception:
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 376, in send_callback
    method(*args, **kwargs)
   File "/usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.py", line 98, in v2_runner_on_ok
    msg += " => %s" % (self._dump_results(result._result),)
   File "/usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.py", line 109, in _dump_results
    return json.dumps(abridged_result, indent=indent, ensure_ascii=False, sort_keys=sort_keys)
   File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
   File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
   File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
   File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
   File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
   File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'get_block_list'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 302, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 331, in run
    new_blocks, handler_blocks = new_ir.get_block_list(
AttributeError: 'Task' object has no attribute 'get_block_list'
```

What is confusing is that it WAS working not too long ago, but I can't identify the change that may have caused this.

I had made the switch to using a dynamic inventory as the only memorable thing I've changed recently.
