### ISSUE TITLE
Upgrading to Ansible 2.3.2.0 via pip doesn't upgrade pyopenssl

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#28829]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = [...]/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
Debian Jessie (LMDE2)

##### SUMMARY
I just upgraded from Ansible 2.3.0.0 to 2.3.2.0 and got a weird ssl error. This was fixed by manually upgrading pyopenssl.

```
sudo pip install --upgrade ansible
Collecting ansible
  Downloading ansible-2.3.2.0.tar.gz (4.3MB)
    100% |████████████████████████████████| 4.3MB 364kB/s 
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/dist-packages (from ansible)
Collecting paramiko (from ansible)
  Downloading paramiko-2.2.1-py2.py3-none-any.whl (176kB)
    100% |████████████████████████████████| 184kB 4.3MB/s 
Requirement already up-to-date: pycrypto>=2.6 in /usr/lib/python2.7/dist-packages (from ansible)
Collecting setuptools (from ansible)
  Downloading setuptools-36.3.0-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 2.6MB/s 
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->ansible)
Collecting pynacl>=1.0.1 (from paramiko->ansible)
  Downloading PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl (539kB)
    100% |████████████████████████████████| 542kB 2.4MB/s 
Collecting pyasn1>=0.1.7 (from paramiko->ansible)
  Downloading pyasn1-0.3.3-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 8.9MB/s 
Collecting cryptography>=1.1 (from paramiko->ansible)
  Downloading cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 693kB/s 
Collecting bcrypt>=3.1.3 (from paramiko->ansible)
  Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
    100% |████████████████████████████████| 61kB 6.0MB/s 
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from pynacl>=1.0.1->paramiko->ansible)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from pynacl>=1.0.1->paramiko->ansible)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko->ansible)
Collecting idna>=2.1 (from cryptography>=1.1->paramiko->ansible)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.9MB/s 
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko->ansible)
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko->ansible)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 4.4MB/s 
Building wheels for collected packages: ansible, pycparser
  Running setup.py bdist_wheel for ansible ... done
  Stored in directory: /root/.cache/pip/wheels/7e/6c/a3/bc77398c75ba7cdb8bab258af9fe555c26f13d67ab90f9a46a
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built ansible pycparser
Installing collected packages: pynacl, pyasn1, idna, cryptography, bcrypt, paramiko, setuptools, ansible, pycparser
  Found existing installation: pyasn1 0.2.3
    Uninstalling pyasn1-0.2.3:
      Successfully uninstalled pyasn1-0.2.3
  Found existing installation: idna 2.5
    Uninstalling idna-2.5:
      Successfully uninstalled idna-2.5
  Found existing installation: cryptography 1.9
    Uninstalling cryptography-1.9:
      Successfully uninstalled cryptography-1.9
  Found existing installation: paramiko 2.1.2
    Uninstalling paramiko-2.1.2:
      Successfully uninstalled paramiko-2.1.2
  Found existing installation: setuptools 36.0.1
    Uninstalling setuptools-36.0.1:
      Successfully uninstalled setuptools-36.0.1
  Found existing installation: ansible 2.3.0.0
    Uninstalling ansible-2.3.0.0:
      Successfully uninstalled ansible-2.3.0.0
  Found existing installation: pycparser 2.17
    Uninstalling pycparser-2.17:
      Successfully uninstalled pycparser-2.17
Successfully installed ansible-2.3.2.0 bcrypt-3.1.3 cryptography-2.0.3 idna-2.6 paramiko-2.2.1 pyasn1-0.3.3 pycparser-2.18 pynacl-1.1.2 setuptools-36.3.0
```

```
ansible-playbook site.yml --limit host
SUDO password: 
ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'
```

```
ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 182, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 420, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 343, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

```
sudo pip install --upgrade pyopenssl
Collecting pyopenssl
  Downloading pyOpenSSL-17.2.0-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 2.4MB/s 
Requirement already up-to-date: cryptography>=1.9 in /usr/local/lib/python2.7/dist-packages (from pyopenssl)
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyopenssl)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: cffi>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7->cryptography>=1.9->pyopenssl)
Installing collected packages: pyopenssl
  Found existing installation: pyOpenSSL 0.15.1
    Uninstalling pyOpenSSL-0.15.1:
      Successfully uninstalled pyOpenSSL-0.15.1
Successfully installed pyopenssl-17.2.0
```

**Comment by CHBresser** [comment]
I have added pyopenssl to requirements.txt, how do I merge it into master branch?

**Comment by abadger** [comment]
This is really a problem that can be traced to a bug in the urllib3 package needing to specify a version of pyopenssl that does not have the bug.  Unfortunately it's not something that can be fixed in Ansible.  It should be fixed in urllib3 instead.
