### ISSUE TITLE
Can't connect using winrm not accepting self-signed certs 

### ISSUE THREAD

**Issue by julianbueno** [ansible/ansible#28863]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

winrm
##### ANSIBLE VERSION

```
ansible.git@devel
```

##### OS / ENVIRONMENT

Running it on windows 10 - docker - using alpine:latest
##### STEPS TO REPRODUCE

1. launch an ec2 instance on aws using 
https://gist.githubusercontent.com/julianbueno/e2b8bf6869f004f745ca26043d5e3a58/raw/189f32cc27ef192a6790a78f8adafb687c5d5d97/ec2.yml

NOTE: I'm tested using Windows_Server-2012-R2_RTM-English-64Bit-Base-2017.08.11 (ami-46f1e925)
and  Windows_Server-2016-English-Full-Base-2017.08.09 (ami-10b1a873)

2. userdata
https://gist.githubusercontent.com/julianbueno/7a5eb26a33e06aefb00bf3f9cc5f0066/raw/86dec0cc874fa6e0b4d6aab2cc9e2d7f3f803f39/userdata.ps1

3.  `ansible web -i inventories/staging -m win_ping --vault-password-file /vault_password_file -vvvvv`

##### EXPECTED RESULTS

Ping ok
##### ACTUAL RESULTS

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
No config file found; using defaults
Reading vault password file: /vault_password_file
setting up inventory plugins
Set default localhost to localhost
Parsed /opt/accounts/labs/inventories/staging inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt /opt/accounts/labs/group_vars/all/vault.yml
Trying to use vault secret=(FileVaultSecret(filename='/vault_password_file')) id=default to decrypt /opt/accounts/labs/group_vars/all/vault.yml
Trying secret FileVaultSecret(filename='/vault_password_file') for vault_id=default
decrypt succesful with secret=FileVaultSecret(filename='/vault_password_file') and vault_id=default
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_ping.ps1
<10.40.16.200> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.40.16.200
<10.40.16.200> WINRM CONNECT: transport=ssl endpoint=https://10.40.16.200:5986/wsman
<10.40.16.200> WINRM CONNECTION ERROR: HTTPSConnectionPool(host='10.40.16.200', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL:
 CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 209, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 184, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='10.40.16.200', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] c
ertificate verify failed (_ssl.c:661)'),))

10.40.16.200 | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='10.40.16.200', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FA
ILED] certificate verify failed (_ssl.c:661)'),))",
    "unreachable": true
}
```

**Comment by julianbueno** [comment]
did a test from my local using powershell
`Enter-PSSession -ComputerName 10.40.16.210 -UseSSL -Credential (Get-Credential)`

OUTPUT
```
Enter-PSSession : Connecting to remote server 10.40.16.210 failed with the following error message : The server certificate on the destination computer (10.40.16.210:5986) has the 
following errors:    
The SSL certificate is signed by an unknown certificate authority.  
The SSL certificate contains a common name (CN) that does not match the hostname. For more information, see the about_Remote_Troubleshooting Help topic.
```

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

For your case I would make sure you have added `ansible_winrm_server_cert_validation: ignore` to your inventory as it is failing to validate the server certificate. By default `ConfigureRemotingForAnsible.ps1` creates a self signed certificate which isn't trusted by default.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
