### ISSUE TITLE
azure_rm_deployment: 'APIversion not available' while specified in the template

### ISSUE THREAD

**Issue by elaurijssens** [ansible/ansible#28916]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
azure_rm_deployment (although azure_rm_common seems to be at work here)

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 35ec00ac5c) last updated 2017/08/31 15:55:04 (GMT +200)
  config file = /home/elaurijssens/voyager-image-factory/ansible.cfg
  configured module search path = [u'/home/elaurijssens/voyager-image-factory/library', u'/root/.ansible/library', u'/usr/share/ansible/library']
  ansible python module location = /opt/ansible/lib/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

Centos 7.3

##### SUMMARY

Even though the API versions are specified in the template fed to azure_rm_deployment, Ansible tries to deploy the template with different versions. 

##### STEPS TO REPRODUCE

I have a json containing sections like:
```json
        {
            "apiVersion": "[variables('apiVersion')]",
            "type": "Microsoft.Network/virtualNetworks",
            "name": "[parameters('virtualNetworkName')]",
            "location": "[resourceGroup().location]",
            "properties": {
                    "addressSpace": {
                        "addressPrefixes": [
                            "[variables('addressPrefix')]"
                        ]
                },
                "subnets": [
                    {
                        "name": "[parameters('subnetName')]",
                        "properties": {
                            "addressPrefix": "[variables('subnetPrefix')]"
                        }
                    }
                ]
            }
        },
```
Where apiVersion is defined as for example 2015-06-15.

```yaml
    - name: Create Azure VM from ARM template
      azure_rm_deployment:
        state: present
        deployment_name: "{{ vm_name }}-deployment"
        location: northeurope
       ...
        parameters:
       ...
        template: "{{ lookup('template', base_dir + '/include/azure/template.json') }}"
      register: _vm_facts
```

##### EXPECTED RESULTS

The API versions in the template are used 

##### ACTUAL RESULTS

The module fails, stating that APIversion 2017-06-01 is not available.

```
Traceback (most recent call last):
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 659, in <module>
    main()
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 655, in main
    AzureRMDeploymentManager()
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 440, in __init__
    supports_check_mode=False)
  File "/tmp/ansible_q5uQ_s/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 255, in __init__
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 454, in exec_module
    instances=self._get_instances(deployment)
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 604, in _get_instances
    for vm, nics in vms_and_nics]
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 648, in _nic_to_public_ips_instance
    nic['dep'].resource_name) for nic in nics)
  File "/tmp/ansible_q5uQ_s/ansible_module_azure_rm_deployment.py", line 648, in <genexpr>
    nic['dep'].resource_name) for nic in nics)
  File "/tmp/ansible_q5uQ_s/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 690, in network_client
  File "/usr/lib/python2.7/site-packages/azure/mgmt/network/__init__.py", line 80, in __init__
    client_models = {k: v for k, v in self.models(api_version).__dict__.items() if isinstance(v, type)}
  File "/usr/lib/python2.7/site-packages/azure/mgmt/network/__init__.py", line 138, in models
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2017-06-01 is not available
```

**Comment by elaurijssens** [comment]
In the code, I see that the API version is hard-coded, why?

```python
    @property
    def network_client(self):
        self.log('Getting network client')
        if not self._network_client:
            self.check_client_version('network', network_client_version, AZURE_EXPECTED_VERSIONS['network_client_version'])
            self._network_client = NetworkManagementClient(
                self.azure_credentials,
                self.subscription_id,
                base_url=self._cloud_environment.endpoints.resource_manager,
                api_version='2017-06-01'
            )
            self._register('Microsoft.Network')
        return self._network_client
```

**Comment by elaurijssens** [comment]
In azure_rm_common.py, the API version is hard-coded. Why?

```python
    @property
    def network_client(self):
        self.log('Getting network client')
        if not self._network_client:
            self.check_client_version('network', network_client_version, AZURE_EXPECTED_VERSIONS['network_client_version'])
            self._network_client = NetworkManagementClient(
                self.azure_credentials,
                self.subscription_id,
                base_url=self._cloud_environment.endpoints.resource_manager,
                api_version='2017-06-01'
            )
            self._register('Microsoft.Network')
        return self._network_client
```

If I change the API version there, the deployment succeeds.

**Comment by s-hertel** [comment]
cc @tstringer

**Comment by elaurijssens** [comment]
Anything on this one?

**Comment by elaurijssens** [comment]
Looks like my azure-mgmt-network was outdated. See https://github.com/ansible/ansible/blob/stable-2.4/packaging/requirements/requirements-azure.txt

**Comment by martinm82** [comment]
Question is actually quite good, why is the version hardcoded in commons? What if someone will require in a resource a different one?
