### ISSUE TITLE
Issue with Persistent Connection for Enos_facts.py - Connection is NOT reliable. Succeeds only 1/4

### ISSUE THREAD

**Issue by amuraleedhar** [ansible/ansible#29018]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module/network/lenovo/enos_facts.py
plugins/action/enos_facts.py

##### ANSIBLE VERSION
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

##### CONFIGURATION
Not applicable

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```
##### SUMMARY
I am trying to bring in the support for ENOS series of switches into Ansible portfolio. I started with enos_facts. I am using Ansible persistent connection to establish connection with device and extract data. Internally its establishing an SSH connectivity with device and extracts data from it using basic commands like "show version". Issue is that whenever I try to execute the playbook to run the facts module, the connection is timing out most of the times. Few times it gets connected and extracts data as well. The connection is not consistent.

##### STEPS TO REPRODUCE
1. Run the playbook using command ansible-playbook -vvvv enos.yaml
2. Few times (1 in 4) times it opens a socket and extracts data from device
3. Majority of time socket comes as None and the connection times out and playbook fails
4. When u run i debug mode enabled. majority of time, it succeeds but fails too.
5. In both cases I got the ansible.log which is pasted below (Success and Failure)
6. I am attaching the module, module_util and as well as action 

Failure Log - ansible.log
```
2017-09-05 18:07:54,970 p=12346 u=root |  TASK [enos_facts : Test Enos Facts] ************************************************************************************************************************************
2017-09-05 18:07:54,971 p=12346 u=root |  task path: /home/test/ansible/sheru/roles/enos_facts/tasks/main.yml:4
2017-09-05 18:07:54,996 p=12346 u=root |  remote_addr: 10.241.105.228
2017-09-05 18:07:55,573 p=12357 u=root |  creating new control socket for host 10.241.105.228:22 as user admin
2017-09-05 18:07:55,573 p=12357 u=root |  control socket path is /root/.ansible/pc/3912ce72db
2017-09-05 18:07:55,574 p=12357 u=root |  current working directory is /home/test/ansible/sheru
2017-09-05 18:07:55,574 p=12357 u=root |  using connection plugin network_cli
2017-09-05 18:07:55,634 paramiko.transport starting thread (client mode): 0xb539e9d0L
2017-09-05 18:07:55,634 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.0.2
2017-09-05 18:07:55,634 paramiko.transport Remote version/idstring: SSH-2.0-Lenovo
2017-09-05 18:07:55,634 paramiko.transport Connected (version 2.0, client Lenovo)
2017-09-05 18:07:55,635 paramiko.transport kex algos:[u'ecdh-sha2-nistp521', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp224', u'ecdh-sha2-nistp192', u'rsa2048-sha256', u'rsa1024-sha1', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes128-cbc', u'rijndael128-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes128-ctr', u'aes128-cbc', u'rijndael128-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2017-09-05 18:07:55,635 paramiko.transport Kex agreed: diffie-hellman-group1-sha1
2017-09-05 18:07:55,635 paramiko.transport Cipher agreed: aes128-ctr
2017-09-05 18:07:55,635 paramiko.transport MAC agreed: hmac-md5
2017-09-05 18:07:55,635 paramiko.transport Compression agreed: none
2017-09-05 18:07:55,717 paramiko.transport kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
2017-09-05 18:07:55,718 paramiko.transport Switch to new keys ...
2017-09-05 18:07:55,736 paramiko.transport userauth is OK
2017-09-05 18:07:55,737 paramiko.transport Auth banner:
2017-09-05 18:07:55,776 paramiko.transport Authentication (password) successful!
2017-09-05 18:07:55,799 p=12357 u=root |  ssh connection done, setting terminal
2017-09-05 18:07:55,800 paramiko.transport [chan 0] Max packet in: 32768 bytes
2017-09-05 18:07:55,801 paramiko.transport [chan 0] Max packet out: 4096 bytes
2017-09-05 18:07:55,802 paramiko.transport Secsh channel 0 opened.
2017-09-05 18:07:55,805 paramiko.transport [chan 0] Sesch channel 0 request ok
2017-09-05 18:07:55,807 paramiko.transport [chan 0] Sesch channel 0 request ok
2017-09-05 18:07:55,813 p=12357 u=root |  loaded terminal plugin for network_os enos
2017-09-05 18:07:55,814 p=12357 u=root |  loaded cliconf plugin for network_os enos
2017-09-05 18:08:05,598 p=12346 u=root |  failed: [10.241.105.228] (item={}) => {
    "changed": false,
    "failed": true,
    "item": {},
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
2017-09-05 18:08:05,601 p=12346 u=root |        to retry, use: --limit @/home/test/ansible/sheru/enos.retry

2017-09-05 18:08:05,601 p=12346 u=root |  PLAY RECAP *************************************************************************************************************************************************************
2017-09-05 18:08:05,601 p=12346 u=root |  10.241.105.228             : ok=0    changed=0    unreachable=0    failed=1
2017-09-05 18:08:06,263 p=12357 u=root |  failed to create control socket for host 10.241.105.228
2017-09-05 18:08:06,264 p=12357 u=root |  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/EGG-INFO/scripts/ansible-connection", line 316, in main
    server = Server(socket_path, pc)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/EGG-INFO/scripts/ansible-connection", line 112, in __init__
    self.connection._connect()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible/plugins/connection/network_cli.py", line 113, in _connect
    self.receive()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible/plugins/connection/network_cli.py", line 150, in receive
    data = self._shell.recv(256)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 615, in recv
    raise socket.timeout()
timeout

2017-09-05 18:08:06,276 paramiko.transport EOF in transport thread
```
[ConnectionIssue.zip](https://github.com/ansible/ansible/files/1277380/ConnectionIssue.zip)

Success log 
```
2017-09-05 18:03:05,485 p=12293 u=root |  TASK [enos_facts : Test Enos Facts] ************************************************************************************************************************************
2017-09-05 18:03:05,485 p=12293 u=root |  task path: /home/test/ansible/sheru/roles/enos_facts/tasks/main.yml:4
2017-09-05 18:03:05,507 p=12293 u=root |  remote_addr: 10.241.105.228
2017-09-05 18:03:06,072 p=12304 u=root |  creating new control socket for host 10.241.105.228:22 as user admin
2017-09-05 18:03:06,073 p=12304 u=root |  control socket path is /root/.ansible/pc/3912ce72db
2017-09-05 18:03:06,073 p=12304 u=root |  current working directory is /home/test/ansible/sheru
2017-09-05 18:03:06,074 p=12304 u=root |  using connection plugin network_cli
2017-09-05 18:03:06,121 paramiko.transport starting thread (client mode): 0xf30dd9d0L
2017-09-05 18:03:06,121 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.0.2
2017-09-05 18:03:06,122 paramiko.transport Remote version/idstring: SSH-2.0-Lenovo
2017-09-05 18:03:06,122 paramiko.transport Connected (version 2.0, client Lenovo)
2017-09-05 18:03:06,123 paramiko.transport kex algos:[u'ecdh-sha2-nistp521', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp224', u'ecdh-sha2-nistp192', u'rsa2048-sha256', u'rsa1024-sha1', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes128-cbc', u'rijndael128-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes128-ctr', u'aes128-cbc', u'rijndael128-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2017-09-05 18:03:06,123 paramiko.transport Kex agreed: diffie-hellman-group1-sha1
2017-09-05 18:03:06,123 paramiko.transport Cipher agreed: aes128-ctr
2017-09-05 18:03:06,123 paramiko.transport MAC agreed: hmac-md5
2017-09-05 18:03:06,123 paramiko.transport Compression agreed: none
2017-09-05 18:03:06,216 paramiko.transport kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
2017-09-05 18:03:06,216 paramiko.transport Switch to new keys ...
2017-09-05 18:03:06,223 paramiko.transport userauth is OK
2017-09-05 18:03:06,224 paramiko.transport Auth banner:
2017-09-05 18:03:06,260 paramiko.transport Authentication (password) successful!
2017-09-05 18:03:06,285 p=12304 u=root |  ssh connection done, setting terminal
2017-09-05 18:03:06,285 paramiko.transport [chan 0] Max packet in: 32768 bytes
2017-09-05 18:03:06,291 paramiko.transport [chan 0] Max packet out: 4096 bytes
2017-09-05 18:03:06,291 paramiko.transport Secsh channel 0 opened.
2017-09-05 18:03:06,294 paramiko.transport [chan 0] Sesch channel 0 request ok
2017-09-05 18:03:06,295 paramiko.transport [chan 0] Sesch channel 0 request ok
2017-09-05 18:03:06,297 p=12304 u=root |  loaded terminal plugin for network_os enos
2017-09-05 18:03:06,298 p=12304 u=root |  loaded cliconf plugin for network_os enos
2017-09-05 18:03:06,737 p=12304 u=root |  firing event: on_open_shell()
2017-09-05 18:03:06,867 p=12304 u=root |  firing event: on_authorize
2017-09-05 18:03:06,996 p=12304 u=root |  ssh connection has completed successfully
2017-09-05 18:03:06,996 p=12304 u=root |  connection established to 10.241.105.228 in 0:00:00.922416
2017-09-05 18:03:06,997 p=12304 u=root |  local socket is set to listening
2017-09-05 18:03:07,069 p=12304 u=root |  incoming request accepted on persistent socket
2017-09-05 18:03:07,069 p=12304 u=root |  socket operation is CONTEXT
2017-09-05 18:03:07,070 p=12304 u=root |  updating play_context for connection
2017-09-05 18:03:07,070 p=12304 u=root |  socket operation completed with rc 0
2017-09-05 18:03:07,071 p=12304 u=root |  socket operation is RUN
2017-09-05 18:03:07,071 p=12304 u=root |  socket operation completed with rc 0
2017-09-05 18:03:07,646 p=12314 u=root |  re-using existing socket for admin@10.241.105.228:22
2017-09-05 18:03:07,646 p=12304 u=root |  incoming request accepted on persistent socket
2017-09-05 18:03:07,646 p=12304 u=root |  socket operation is CONTEXT
2017-09-05 18:03:07,647 p=12304 u=root |  updating play_context for connection
2017-09-05 18:03:07,647 p=12304 u=root |  socket operation completed with rc 0
2017-09-05 18:03:07,647 p=12304 u=root |  socket operation is EXEC
2017-09-05 18:03:07,647 p=12304 u=root |  Command executed: prompt()
2017-09-05 18:03:07,647 p=12304 u=root |  socket operation completed with rc 0
2017-09-05 18:03:07,737 p=12293 u=root |  Using module file /home/test/ansible/sheru/library/enos_facts.py
2017-09-05 18:03:07,827 p=12304 u=root |  incoming request accepted on persistent socket
2017-09-05 18:03:07,827 p=12304 u=root |  socket operation is EXEC
2017-09-05 18:03:07,827 p=12304 u=root |  Command executed: {"answer": null, "command": "show system memory", "prompt": null}
2017-09-05 18:03:07,952 p=12304 u=root |  socket operation completed with rc 0
2017-09-05 18:03:07,953 p=12304 u=root |  incoming request accepted on persistent socket
2017-09-05 18:03:07,953 p=12304 u=root |  socket operation is EXEC
2017-09-05 18:03:07,953 p=12304 u=root |  Command executed: {"answer": null, "command": "show version", "prompt": null}
2017-09-05 18:03:08,796 p=12304 u=root |  socket operation completed with rc 0
2017-09-05 18:03:08,812 p=12293 u=root |  ok: [10.241.105.228] => (item={}) => {
    "ansible_facts": {
        "ansible_net_gather_subset": [
            "hardware",
            "default"
        ],
        "ansible_net_hostname": "NA",
        "ansible_net_image": "Image1",
        "ansible_net_memfree_mb": 3615,
        "ansible_net_memtotal_mb": 3987,
        "ansible_net_model": "G8264CS",
        "ansible_net_serialnum": "Y012CM3A9031",
        "ansible_net_version": "8.4.1.63"
    },
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "gather_subset": [
                "!config"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "10.241.105.228",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "item": {}
}
2017-09-05 18:03:08,812 p=12293 u=root |  META: ran handlers
2017-09-05 18:03:08,813 p=12293 u=root |  META: ran handlers
2017-09-05 18:03:08,814 p=12293 u=root |  PLAY RECAP *************************************************************************************************************************************************************
2017-09-05 18:03:08,814 p=12293 u=root |  10.241.105.228             : ok=1    changed=0    unreachable=0    failed=0
```
##### EXPECTED RESULTS
```
TASK [enos_facts : Test Enos Facts] ************************************************************************************************************************************
task path: /home/test/ansible/sheru/roles/enos_facts/tasks/main.yml:4
remote_addr: 10.241.105.228
<10.241.105.228> using connection plugin network_cli
<10.241.105.228> socket_path: /root/.ansible/pc/3912ce72db
Using module file /home/test/ansible/sheru/library/enos_facts.py
<10.241.105.228> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.241.105.228> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.241.105.228> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901 `" && echo ansible-tmp-1504610931.46-201452100908901="` echo /root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901 `" ) && sleep 0'
<10.241.105.228> PUT /tmp/tmppM6ybe TO /root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901/enos_facts.py
<10.241.105.228> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901/ /root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901/enos_facts.py && sleep 0'
<10.241.105.228> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901/enos_facts.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1504610931.46-201452100908901/" > /dev/null 2>&1 && sleep 0'
ok: [10.241.105.228] => (item={}) => {
    "ansible_facts": {
        "ansible_net_gather_subset": [
            "hardware",
            "default"
        ],
        "ansible_net_hostname": "NA",
        "ansible_net_image": "Image1",
        "ansible_net_memfree_mb": 3613,
        "ansible_net_memtotal_mb": 3987,
        "ansible_net_model": "G8264CS",
        "ansible_net_serialnum": "Y012CM3A9031",
        "ansible_net_version": "8.4.1.63"
    },
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "gather_subset": [
                "!config"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "10.241.105.228",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "item": {}
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************
10.241.105.228             : ok=1    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
TASK [enos_facts : Test Enos Facts] ************************************************************************************************************************************
task path: /home/test/ansible/sheru/roles/enos_facts/tasks/main.yml:4
remote_addr: 10.241.105.228
<10.241.105.228> using connection plugin network_cli
<10.241.105.228> socket_path: None
failed: [10.241.105.228] (item={}) => {
    "changed": false,
    "failed": true,
    "item": {},
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
        to retry, use: --limit @/home/test/ansible/sheru/enos.retry

PLAY RECAP *************************************************************************************************************************************************************
10.241.105.228             : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by amuraleedhar** [comment]
I think this could be the issue.
But I dont know internally whats happening in Ansible code
In my module action plugin code there is a segment like this
This segment is there for every plugin

```
        display.vvv('using connection plugin %s' % pc.connection, pc.remote_addr)
        connection = self._shared_loader_obj.connection_loader.get('persistent', pc, sys.stdin)
        socket_path = connection.run()
        display.vvvv('socket_path: %s' % socket_path, pc.remote_addr)
        if not socket_path:
            return {'failed': True,
                    'msg': 'unable to open shell. Please see: ' +
                           'https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell'}
```
This socket path is coming as None and the module is failing
If u try 3-4 times it succeeds
Then I added this segment to the code
```
        display.vvv('using connection plugin %s' % pc.connection, pc.remote_addr)
        connection = self._shared_loader_obj.connection_loader.get('persistent', pc, sys.stdin)

        socket_path = connection.run()
        display.vvvv('socket_path: %s' % socket_path, pc.remote_addr)
        count = 0
        while(socket_path is None and count < 3):
            socket_path = self._shared_loader_obj.connection_loader.get('persistent', pc, sys.stdin).run()
            count = count+1
        display.vvvv('Again socket_path: %s' % socket_path, pc.remote_addr)
        if not socket_path:
            return {'failed': True,
                    'msg': 'unable to open shell. Please see: ' +
                           'https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell'}
```
Then the failure rate has come down drastically as the logic will try to do the same 3 times.
I guess its failing from
`plugins/connection/persistent.py`
run method
This segment is failing
```
def run(self):
        """Returns the path of the persistent connection socket.
        Attempts to ensure (within playcontext.timeout seconds) that the
        socket path exists. If the path exists (or the timeout has expired),
        returns the socket path.
        """
        socket_path = None
        rc, out, err = self._do_it('RUN:')
        match = re.search(br"#SOCKET_PATH#: (\S+)", out)
        if match:
            socket_path = to_text(match.group(1).strip(), errors='surrogate_or_strict')

        return socket_path
```

**Comment by ganeshrn** [comment]
@amuraleedhar Can you please enable `log_path` in `ansible.cfg` and share the contents of log file.
More details can be found at `enable_network_logging` section here
http://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html#unable-to-open-shell

**Comment by amuraleedhar** [comment]
[Ansible_Intermittent_Issue.zip](https://github.com/ansible/ansible/files/1291805/Ansible_Intermittent_Issue.zip)
Hi Ganesh,

I have not enabled log_path in ansible.cfg rather I have set this environment variable 
`export ANSIBLE_LOG_PATH=./ansible.log`
I have also done both debug enabled and disabled and tried by setting 
`export ANSIBLE_DEBUG=False/True`
I have pasted what is relevant in ansible.log above. 
In /etc/ansible/hosts file there in only one device ie 10.241.107.48
I am attaching 2 files. 1 with debug enabled and debug not enabled

The issue is intermittent, once in 4 run it succeeds
ansible-playbook enos.yaml -vvvv

This is failing from this code snippet of action plugin
```
        display.vvv('using connection plugin %s' % pc.connection, pc.remote_addr)
        connection = self._shared_loader_obj.connection_loader.get('persistent', pc, sys.stdin)

        socket_path = connection.run()
        display.vvvv('socket_path: %s' % socket_path, pc.remote_addr)
        count = 0
        if not socket_path:
            return {'failed': True,
                    'msg': 'unable to open shell. Please see: ' +
                           'https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell'}

```

**Comment by ganeshrn** [comment]
@amuraleedhar Thank you for sharing the information.
To rule out timeout issue can you please set below timer settings as environment variable and rerun
```
ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=100
ANSIBLE_PERSISTENT_CONNECT_RETRY_TIMEOUT=60
ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=100
```
docs for these configuration settings in `ansible.cfg` file can be found [here](https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg#L408)

**Comment by amuraleedhar** [comment]
I have put these configurations and out of 3 devices in my inventory 1 succeded and 2 failed with the same issue. 
```
<10.241.107.74> socket_path: None
<10.241.105.136> socket_path: None
failed: [10.241.107.74] (item={}) => {
    "changed": false,
    "failed": true,
    "item": {},
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
failed: [10.241.105.136] (item={}) => {
    "changed": false,
    "failed": true,
    "item": {},
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
META: ran handlers
META: ran handlers
        to retry, use: --limit @/home/test/ansible/sheru/enos.retry

PLAY RECAP *************************************************************************************************************************************************************
10.241.105.136             : ok=0    changed=0    unreachable=0    failed=1
10.241.107.48              : ok=1    changed=0    unreachable=0    failed=0
10.241.107.74              : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by amuraleedhar** [comment]
I tried again and this time only one failed. This keeps on changing.. No consistency is my issue
```
    },
    "item": {}
}
<10.241.105.136> socket_path: None
failed: [10.241.105.136] (item={}) => {
    "changed": false,
    "failed": true,
    "item": {},
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
META: ran handlers
META: ran handlers
        to retry, use: --limit @/home/test/ansible/sheru/enos.retry

PLAY RECAP *************************************************************************************************************************************************************
10.241.105.136             : ok=0    changed=0    unreachable=0    failed=1
10.241.107.48              : ok=1    changed=0    unreachable=0    failed=0
10.241.107.74              : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by ganeshrn** [comment]
cc @amuraleedhar Edited above comments to improve readability.

**Comment by ganeshrn** [comment]
If I get this correctly now for a single device it is successful across multiple runs and failing if you add more than one host in inventory.

**Comment by amuraleedhar** [comment]
No. Based on my experience, even after putting all the variables as suggested by you in ansible.cfg. Chances of success are only 1 out of 4
Even if there is only one device, as just now tested, it fails. There is no pattern in it. Certain times, it succeeds continuously.  If u put multiple devices in inventory, there also the same pattern repeats.
No change in behavior in using the timeout parameters suggested by you.
I think its happening from ansible/plugins/connection/persistent.py
The following method may be making this socket_path as None
 def run(self):
        """Returns the path of the persistent connection socket.
        Attempts to ensure (within playcontext.timeout seconds) that the
        socket path exists. If the path exists (or the timeout has expired),
        returns the socket path.
        """
        socket_path = None
        rc, out, err = self._do_it('RUN:')
        match = re.search(br"#SOCKET_PATH#: (\S+)", out)
        if match:
            socket_path = to_text(match.group(1).strip(), errors='surrogate_or_strict')

        return socket_path

**Comment by ganeshrn** [comment]
@amuraleedhar background process `ansible-connection` waits for socket path to exist till the play context timeout value is expired [here](https://github.com/ansible/ansible/blob/devel/bin/ansible-connection#L247)

Time out value for play context is set in action plugin below.
```
pc.timeout = int(provider['timeout'] or C.PERSISTENT_COMMAND_TIMEOUT)
```

As you are trying to add new platform over the persistent connection is it possible for you to join `#ansible-network` channel on irc and discuss this issue over there for faster resolution.

**Comment by amuraleedhar** [comment]
I will do that. But one another question I have is - "Why this is happening only to my Switches? Why the issue not happening with Cisco, Juniper or Arista Switches ?" If such an issue was there, they would have tested and highlighted it much prior to me

**Comment by ganeshrn** [comment]
It works fine for all the other platforms that support persistent connection.
So probably something might be wrong in your environment or new code that you added locally or it might be something specific to the platform that needs to be supported in persistent connection framework.
I can share you a patch having additional debug logs which you can apply in your environment to help identify the root cause of this issue.

**Comment by amuraleedhar** [comment]
I have found out the issue based on comment by John on the issue. Upon login ENOS devices of lenovo was giving the following text to console

> Lenovo RackSwitch G8296.
> 
> ------------------------------------------------------------------
> Note: The current running configuration includes changes
>       that have NOT been saved to FLASH.
> ------------------------------------------------------------------
> 
> RS G8296>
> Sep 14 11:23:14 10.241.107.48 NOTICE  mgmt: admin(admin) login from host 10.162.24.74

The text was not ending in the prompt > . So the regular expressions given in action plugins were not matching. I added an appropriate regular expression and it worked.  Some how the above aspect has to stated in the documentation some where else many may stumble on this.
