### ISSUE TITLE
Setup module should allow for path not to exist

### ISSUE THREAD

**Issue by jtognazzi** [ansible/ansible#2906]
On old linux distrib (SLES 10 SP2) the setup module failed with:

``` python
fatal: [myhost] => failed to parse:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-1368456661.8-263287084724264/setup", line 2587, in ?
    main()
  File "/home/user/.ansible/tmp/ansible-1368456661.8-263287084724264/setup", line 1689, in main
    data = run_setup(module)
  File "/home/user/.ansible/tmp/ansible-1368456661.8-263287084724264/setup", line 1634, in run_setup
    facts = ansible_facts()
  File "/home/user/.ansible/tmp/ansible-1368456661.8-263287084724264/setup", line 1624, in ansible_facts
    facts.update(Hardware().populate())
  File "/home/user/.ansible/tmp/ansible-1368456661.8-263287084724264/setup", line 408, in populate
    self.get_device_facts()
  File "/home/user/.ansible/tmp/ansible-1368456661.8-263287084724264/setup", line 629, in get_device_facts
    for folder in os.listdir(sysdir + "/holders"):
OSError: [Errno 2] No such file or directory: '/sys/block/sdb/holders'
```

**Comment by tonk** [comment]
Could you post an 'ls -l' of '/sys', '/sys/block' and '/sys/block/sdb' if possible?

**Comment by jtognazzi** [comment]
Here you go:

``` bash
/sys/:
total 0
drwxr-xr-x 31 root root 0 2010-06-02 10:19 block
drwxr-xr-x 11 root root 0 2010-06-02 10:19 bus
drwxr-xr-x 22 root root 0 2010-09-22 10:01 class
drwxr-xr-x  6 root root 0 2010-06-02 10:16 devices
drwxr-xr-x  4 root root 0 2010-06-02 10:17 firmware
drwxr-xr-x  2 root root 0 2010-06-02 10:16 fs
drwxr-xr-x  4 root root 0 2010-06-02 10:18 kernel
drwxr-xr-x 54 root root 0 2011-08-23 13:19 module
drwxr-xr-x  2 root root 0 2010-06-02 10:19 power

/sys/block/:
total 0
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop0
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop1
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop2
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop3
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop4
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop5
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop6
drwxr-xr-x 2 root root 0 2010-09-22 10:01 loop7
drwxr-xr-x 3 root root 0 2010-09-22 10:01 md0
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram0
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram1
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram10
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram11
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram12
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram13
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram14
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram15
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram2
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram3
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram4
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram5
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram6
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram7
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram8
drwxr-xr-x 2 root root 0 2010-09-22 10:01 ram9
drwxr-xr-x 7 root root 0 2010-09-22 10:01 sda
drwxr-xr-x 3 root root 0 2010-09-22 10:01 sdb
drwxr-xr-x 3 root root 0 2010-09-22 10:01 sr0
drwxr-xr-x 3 root root 0 2010-09-22 10:01 sr1

/sys/block/sdb/:
total 0
-r--r--r-- 1 root root 4096 2010-06-02 10:19 dev
lrwxrwxrwx 1 root root    0 2010-06-02 10:19 device -> ../../devices/pci0000:00/0000:00:1d.7/usb1/1-1/1-1.2/1-1.2:1.1/host4/target4:0:0/4:0:0:0
drwxr-xr-x 3 root root    0 2013-05-13 16:04 queue
-r--r--r-- 1 root root 4096 2010-09-22 10:01 range
-r--r--r-- 1 root root 4096 2010-06-02 10:19 removable
-r--r--r-- 1 root root 4096 2010-09-22 10:01 size
-r--r--r-- 1 root root 4096 2010-09-22 10:01 stat
--w------- 1 root root 4096 2010-09-22 10:01 uevent
```

**Comment by tonk** [comment]
Thank you.

I submitted a pull request.

Could you change `library/system/setup` and add

```
   630                  if not folder:
   631                      continue
```

and test please (I cannot really test, all my systems have the `holders` directory)

**Comment by jtognazzi** [comment]
Humm, id doesn't seem to fix it.
I stil have the same error.

**Comment by tonk** [comment]
Did you do a `make install` ?
(Which version are you running?)

**Comment by jtognazzi** [comment]
I tested with

```
source hacking/env-setup
```

from a git clone.

**Comment by jtognazzi** [comment]
maybe with something like that:

```
try:
  holders = os.listdir(sysdir + "/holders")
except OSError:
  something

for folder in holders:
  ...
```

**Comment by tonk** [comment]
Added

```
if os.path.isdir(sysdir + "/holders"):
```

before the for loop

This should do it.

I'll update the pull request

**Comment by jtognazzi** [comment]
This works also.

thanks

**Comment by tonk** [comment]
Welcome. I hope Michael accepts my pull request. I really messed that one up :-)

**Comment by mpdehaan** [comment]
Yeah so that pull request needs to check if that directory exists and skip the loop, rather than seeing what gets returned by the listdir is None.

I will look at this shortly and you can help test as I don't have access to any SLES 10 SP2 instances ATM.

Thanks!

**Comment by tonk** [comment]
Resubmitted the pull request (without the messing up part ;-))

**Comment by mpdehaan** [comment]
code merged, so closing this one, thanks!
