### ISSUE TITLE
DistributionNotFound: The 'paramiko' distribution was not found and is required by ansible

### ISSUE THREAD

**Issue by rpijlman** [ansible/ansible#29084]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
v2.4.0.0-0.1.rc1
```

##### OS / ENVIRONMENT

Debian 9.1

##### SUMMARY
Ansible 2.3.2 was working fine in my environment. v2.4.0.0-0.1.rc1 fails with an exception because paramiko is missing. The Linux server has openssh installed, and Ansible 2.3 apparently detected that, while 2.4rc1 does not.

##### STEPS TO REPRODUCE

```
ansible-playbook --version
```

##### EXPECTED RESULTS
v2.4.0.0-0.1.rc1

##### ACTUAL RESULTS

```
applinet@short:~/local/infrastructure$ ansible-playbook --version
ERROR! Unexpected Exception, this is probably a bug: The 'paramiko' distribution was not found and is required by ansible
the full traceback was:

Traceback (most recent call last):
  File "/home/applinet/local/ansible_controller/ansible/ansible/bin/ansible-playbook", line 85, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/inventory/manager.py", line 29, in <module>
    from ansible.inventory.data import InventoryData
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/inventory/data.py", line 30, in <module>
    from ansible.plugins.cache import FactCache
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/plugins/cache/__init__.py", line 30, in <module>
    from ansible.plugins.loader import cache_loader
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/plugins/loader.py", line 36, in <module>
    from ansible.parsing.plugin_docs import read_docstring
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/parsing/plugin_docs.py", line 12, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.parsing.vault import VaultLib
  File "/home/applinet/local/ansible_controller/ansible/ansible/lib/ansible/parsing/vault/__init__.py", line 44, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'paramiko' distribution was not found and is required by ansible
```

**Comment by samdoran** [comment]
Do you have `ansible_python_interpreter` set? Any details you can share about your config or environment? Having trouble reproducing this without more details.

needs_info

**Comment by jmvbxx** [comment]
I just got this error right now. I did attempt to set `ansible_python_interpreter` (still not sure where the best place to set it is) but have since removed all references to it yet I'm still getting the error now

```
12:35 $ ansible-playbook -vv -i production servers/php-server.yml --vault-password-file "/home/jason/vault" --limit "php2.guba1.infra" --tags "php-server"
ERROR! Unexpected Exception, this is probably a bug: The 'paramiko' distribution was not found and is required by ansible
the full traceback was:

Traceback (most recent call last):
  File "/home/jason/coding/ansible/bin/ansible-playbook", line 85, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/home/jason/coding/ansible/lib/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/home/jason/coding/ansible/lib/ansible/inventory/manager.py", line 29, in <module>
    from ansible.inventory.data import InventoryData
  File "/home/jason/coding/ansible/lib/ansible/inventory/data.py", line 30, in <module>
    from ansible.plugins.cache import FactCache
  File "/home/jason/coding/ansible/lib/ansible/plugins/cache/__init__.py", line 30, in <module>
    from ansible.plugins.loader import cache_loader
  File "/home/jason/coding/ansible/lib/ansible/plugins/loader.py", line 22, in <module>
    from ansible.parsing.plugin_docs import read_docstring
  File "/home/jason/coding/ansible/lib/ansible/parsing/plugin_docs.py", line 12, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/home/jason/coding/ansible/lib/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/home/jason/coding/ansible/lib/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.parsing.vault import VaultLib
  File "/home/jason/coding/ansible/lib/ansible/parsing/vault/__init__.py", line 44, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'paramiko' distribution was not found and is required by ansible
```

**Comment by rpijlman** [comment]
No, I don't have ansible_python_interpreter set.

I just installed v2.4.0.0-1 branch and got the same error.

I'm source hacking/env-setup in bash.
lsb_release -a
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch

$ which python
/usr/bin/python
$ python -V
Python 2.7.13

OpenSSH is installed:
$ dpkg -l | grep ssh
ii  libssh2-1:amd64                 1.7.0-1                        amd64        SSH2 client-side library
ii  openssh-client                  1:7.4p1-10+deb9u1              amd64        secure shell (SSH) client, for secure access to remote machines
ii  openssh-server                  1:7.4p1-10+deb9u1              amd64        secure shell (SSH) server, for secure access from remote machines
ii  openssh-sftp-server             1:7.4p1-10+deb9u1              amd64        secure shell (SSH) sftp server module, for SFTP access from remote machines
ii  task-ssh-server                 3.39                           all          SSH server

When I change branch to 2.3, Ansible works fine in the same environment:
$ ansible --version
ansible 2.3.2.0 (detached HEAD c7052b42c7) last updated 2017/09/20 12:52:59 (GMT +200)
  config file = /home/applinet/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

Where/how does Ansible 2.4 detect it should use openssh and not fallback to paramiko? I'll be glad to investigate further, but I'd appreciate some pointers as to what I should be looking at.

**Comment by samdoran** [comment]
OpenSSH vs Paramiko for the connection is not the issue — this is a library import error. Ansible requires the `paramiko` Python library and it seems like it is missing.

Can you try running `python -c 'import paramiko'` to see if the required library is present in your `PYTHONPATH`?

You may also run [list-install.py](https://github.com/ansible/ansible-doctor/blob/master/list-installs.py) to get a good picture of your Python environment.

**Comment by rpijlman** [comment]
Thanks Sam, I dit 'apt-get install python-paramiko' and that fixed it.

This requirement is not mentioned in "Running from source" (or any other section) on http://docs.ansible.com/ansible/latest/intro_installation.html.
Also, Ansible 2.3 worked fine for me on the same controller without the python-paramiko package.

IMO this should be documented and the failure should produce a more meaningful error message.

**Comment by jmvbxx** [comment]
Installing `python-paramiko` did not fix it for me. Instead I had to remove
`python-cryptography`.

**Comment by rpijlman** [comment]
That's strange @jmvbxx. I have all of these packages installed on my Ansible controller and 2.4.0.0 seems to be running fine now on Debian 9.1 (from source, using hacking/env-setup):
```
- name: required packages for Ansible from source
  remote_user: root
  apt: name={{ item }} state=present
  with_items:
  - python-markupsafe
  - python-crypto
  - python-cryptography
  - python-jinja2
  - python-yaml
  - python-paramiko
  - python-dnspython # Required for dig lookup.
  - python-netaddr # Required for ipaddr() filter.
```

**Comment by jmvbxx** [comment]
Yeah, it was really weird. When I bumped up to 2.4.0.0 from 2.3 everything
worked fine until I tried the s3 module which requires boto3. Once I tried
to specify the python interpreter is when my troubles began.

Now I've got ansible working again and I'm still fighting with Python3 and
boto3. I've got it set in inventory but it's not picking it up. (I'm not
trying to hijack the conversation) 😂

**Comment by samdoran** [comment]
@rpijlman There is a `requirements.txt` file that needs to be installed when [running from source](http://docs.ansible.com/ansible/latest/intro_installation.html#running-from-source).

>Ansible also uses the following Python modules that need to be installed:
> `$ sudo pip install -r ./requirements.txt`

Note these are the bare minimum needed for the Ansible engine and not modules, which is why you hit the `boto3` missing @jmvbxx. Many of the EC2 modules use `boto3` in Ansible 2.4.

It looks like the imports in `lib/ansible/parsing/vault/__init__.py` changed in 2.4, which now imports `cryptography`. This may explain why this error appeared in 2.4.

**Comment by rpijlman** [comment]
Thanks again @samdoran, for you clear explanation. I wasn't aware of that requirements.txt file.

**Comment by samdoran** [comment]
No problem. Thanks for using Ansible!

**Comment by prakashpandey** [comment]
**Problem :** `ERROR! Unexpected Exception, this is probably a bug: (cryptography 1.2.3 (/usr/lib/python3/dist-packages), Requirement.parse('cryptography>=1.5'), {'paramiko'})`

**Solution**: 

`sudo pip3 uninstall cryptography`
removed cryptography-1.2.3

`sudo pip3 install cryptography`
install cryptography-2.2.2

**Comment by spezifanta** [comment]
@prakashpandey Thank you. This worked on a Mac. Removed 1.4.0 and installed 1.4.1
