### ISSUE TITLE
ansible-playbook  hangs if WorkerProcess killed with SIGINT

### ISSUE THREAD

**Issue by kupsef** [ansible/ansible#29124]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 3.4.3 (default, Nov 17 2016, 01:08:31) [GCC 4.8.4]
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

Linux 4.4.0-87-generic
Ubuntu 14.04.5 LTS

##### SUMMARY

Ansible process can hang indefinitely if one of its WorkerProcess is killed with `kill -2`

Note: This issue was discovered while investigating an other one, where the WorkerProcess returned with 0 (success), but failed to provide a result for ResultProcess. It resulted in a similar hang, with exactly the same process stack traces. I could not reproduce the 0 return_code case (it is extremely rare), but managed to create a similar hanging situation with `kill -2`.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - shell: sleep 10
```

```
ansible-playbook test.yml
kill -2 <worker process pid>
```

##### EXPECTED RESULTS

The main process detects the death of the worker and returns with an error message describing the situation.

##### ACTUAL RESULTS

The `ansible-playbook` command hangs.

```
$ ansible-playbook test.yml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [command] ******************************************************************************************************************************************************************************
Process WorkerProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/ansible/executor/process/worker.py", line 116, in run
    self._rslt_q
  File "/usr/local/lib/python3.4/dist-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/local/lib/python3.4/dist-packages/ansible/executor/task_executor.py", line 522, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.4/dist-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.4/dist-packages/ansible/plugins/action/__init__.py", line 734, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/local/lib/python3.4/dist-packages/ansible/plugins/action/__init__.py", line 883, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.4/dist-packages/ansible/plugins/connection/local.py", line 122, in exec_command
    stdout, stderr = p.communicate(in_data)
  File "/usr/lib/python3.4/subprocess.py", line 960, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1617, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.4/selectors.py", line 367, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt

```

**Comment by abadger** [comment]
!python3

**Comment by alikins** [comment]
ping @jimi-c @bcoca 

WorkerProcess doesnt really expect a SIGINT, but curious what would cause the other mention issue:


> where the WorkerProcess returned with 0 (success), but failed to provide a result for ResultProcess. It resulted in a similar hang, with exactly the same process stack traces.
