### ISSUE TITLE
Difference between how ansible detects statuses (or deeper in runner.py) in master and devel branch causing service start/restart failures.

### ISSUE THREAD

**Issue by dcoutu** [ansible/ansible#292]
Something has changed in runner.py (I think) that has caused status checking that was previously working under the service module in the master branch to be broken in the current devel branch.  Here's what I am seeing at the moment, if guided I can provide more:

From Master:

[me@overlord lib]$ ~/git/ansible/bin/ansible client01 -m service -a "name=jetty state=stopped" 
client01 | success >> {
    "changed": true
}

[me@overlord lib]$ ~/git/ansible/bin/ansible client01 -m service -a "name=jetty state=started" 
client01 | success >> {
    "changed": true
}

[me@overlord lib]$ ~/git/ansible/bin/ansible client01 -m service -a "name=jetty state=restarted" 
client01 | success >> {
    "changed": true
}

From Devel:

[me@overlord lib]$ ~/git/ansible/bin/ansible client01 -m service -a "name=jetty state=stopped" 
client01 | success >> {
    "changed": true
}

[me@overlord lib]$ ~/git/ansible/bin/ansible client01 -m service -a "name=jetty state=started" 
client01 | FAILED => Traceback (most recent call last):
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 572, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 611, in _executor_internal
    result = self._execute_normal_module(conn, host, tmp, module_name)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 352, in _execute_normal_module
    (result, err, executed) = self._execute_module(conn, tmp, module, self.module_args)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 299, in _execute_module
    res, err = self._exec_command(conn, cmd, tmp, sudoable=True)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 644, in _exec_command
    err="\n".join(stderr.readlines())
  File "/usr/lib/python2.6/site-packages/paramiko/file.py", line 259, in readlines
    line = self.readline()
  File "/usr/lib/python2.6/site-packages/paramiko/file.py", line 214, in readline
    new_data = self._read(n)
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 1227, in _read
    return self.channel.recv_stderr(size)
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 636, in recv_stderr
    raise socket.timeout()
timeout

[me@overlord lib]$ ~/git/ansible/bin/ansible client01 -m service -a "name=jetty state=restarted" 
client01 | FAILED => Traceback (most recent call last):
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 572, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 611, in _executor_internal
    result = self._execute_normal_module(conn, host, tmp, module_name)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 352, in _execute_normal_module
    (result, err, executed) = self._execute_module(conn, tmp, module, self.module_args)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 299, in _execute_module
    res, err = self._exec_command(conn, cmd, tmp, sudoable=True)
  File "/home/cout/git/ansible/lib/ansible/runner.py", line 644, in _exec_command
    err="\n".join(stderr.readlines())
  File "/usr/lib/python2.6/site-packages/paramiko/file.py", line 259, in readlines
    line = self.readline()
  File "/usr/lib/python2.6/site-packages/paramiko/file.py", line 214, in readline
    new_data = self._read(n)
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 1227, in _read
    return self.channel.recv_stderr(size)
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 636, in recv_stderr
    raise socket.timeout()
timeout

I initially thought it was something in the Jetty init script, but if it works in master but doesn't in devel calling the same init script, something funky is going on somewhere in ansible.

I also noticed a similar issue either yesterday afternoon or this morning on the devel branch where I was running a find across multiple hosts on a slightly deep directory structure (the puppet clientbucket which just loves to fill up) and had similar behaviour.

**Comment by mpdehaan** [comment]
OS?

On the devel module someone added an explicit /sbin/service and if you're using Ubuntu that explains a fair amount.

It needs to ignore the path but try a /sbin and /usr/sbin/service ... leaving later remove for systemctl and launchd

**Comment by mpdehaan** [comment]
see #296 and let me know if that is NOT the problem and I can reopen this.

**Comment by jhoekx** [comment]
This is the default SSH command timeout being too low. See the [mailing list thread](http://groups.google.com/group/ansible-project/browse_thread/thread/224baec0c2cf55a8).

**Comment by mpdehaan** [comment]
If this is being applied to module runtime, it should... NOT be
applied to module run time.

On Wed, May 2, 2012 at 8:34 AM, Jeroen Hoekx
reply@reply.github.com
wrote:

**Comment by dcoutu** [comment]
OS is CentOS 5.x.  It is not related to Issue #296.  It is also not related to the SSH command timeout being too low, I've set it to 30 seconds, 60 seconds, etc. with the same behavior.  The startup operation takes less than 1 second and behaved just fine on the master branch.  The stop command (which is the longer operation between start & stop) completes successfully.

I'm going to dig around changes in the service module between master and devel and see what I can find.  Please re-open as it is not related to the suggested reasons.
