### ISSUE TITLE
The use of $ENV(name) in some cases doesn't work in the devel branch(> v1.1)

### ISSUE THREAD

**Issue by kjkuan** [ansible/ansible#2943]
This minimal playbook:

<pre>

---
- hosts: localhost
  vars:
    ANSIBLE_HOME: $ENV(ANSIBLE_HOME)
</pre>

will produce a stack trace that looks like:

<pre>
Traceback (most recent call last):
  File "/Users/jkuan/work/ansible-playbooks/ansible/bin/ansible-playbook", line 7, in <module>
    execfile(__file__)
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/bin/ansible-playbook", line 235, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/bin/ansible-playbook", line 181, in main
    pb.run()
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/playbook/__init__.py", line 215, in run
    play = Play(self, play_ds, play_basedir)
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/playbook/play.py", line 80, in __init__
    ds = template(basedir, ds, self.vars) 
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/utils/template.py", line 327, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists)
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/utils/template.py", line 327, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists)
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/utils/template.py", line 309, in template
    m = _legacy_varFind(basedir, varname, vars, lookup_fatal, depth, expand_lists)
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/utils/template.py", line 237, in _legacy_varFind
    replacement = instance.run(args, inject=vars)
  File "/Users/jkuan/work/ansible-playbooks/ansible/src/ansible/lib/ansible/runner/lookup_plugins/env.py", line 35, in run
    var = term.split()[0]
IndexError: list index out of range
</pre>

**Comment by mpdehaan** [comment]
FYI, the following will work, since this is the new preferred way.

"{{ lookup('env', 'SOMEVAR') }}"

The old way should of course still work.

**Comment by mpdehaan** [comment]
Confirmed I can reproduce this.

This only seems to happen, BTW, when the environment variable is the same as the parameter.

Now seeing why this occurs :)

**Comment by mpdehaan** [comment]
Ok, the problem does not occur when using the new documented system.

Since this only occurs when the variable is named the same as the environment variable, I am inclined to say this is an acceptable corner case.

Our legacy variable system is somewhat unmaintainable so we are definitely encouraging everything to move to the new system.

**Comment by jkieley** [comment]
thanks, we ran into the same issue. This was super helpful!
