### ISSUE TITLE
Cannot install Ansible with pip

### ISSUE THREAD

**Issue by jimmycuadra** [ansible/ansible#2950]
I'm trying to install Ansible with pip. Running Mac OS X with Python 2.7 installed by Homebrew to `/usr/local`. Ansible seems to have the path `/usr/share/ansible` hardcoded as a place to install files, so I get a permissions error when trying to install it. How do I get it to install itself into the correct directories under `/usr/local`? Below is pip.log. Thanks!

```
------------------------------------------------------------
/usr/local/bin/pip run on Fri May 17 19:36:41 2013
Downloading/unpacking ansible

  Running setup.py egg_info for package ansible

    DATA FILES=[('/usr/share/ansible/', ['./library/add_host', './library/apt', './library/apt_key', './library/apt_repository', './library/assemble', './library/async_status', './library/async_wrapper', './library/authorized_key', './library/bzr', './library/cloudformation', './library/command', './library/copy', './library/cron', './library/debug', './library/django_manage', './library/easy_install', './library/ec2', './library/ec2_facts', './library/ec2_vol', './library/facter', './library/fail', './library/fetch', './library/file', './library/fireball', './library/gem', './library/get_url', './library/git', './library/group', './library/group_by', './library/hg', './library/homebrew', './library/ini_file', './library/lineinfile', './library/lvg', './library/lvol', './library/macports', './library/mail', './library/mongodb_user', './library/mount', './library/mysql_db', './library/mysql_user', './library/nagios', './library/netscaler', './library/ohai', './library/openbsd_pkg', './library/opkg', './library/pacman', './library/pause', './library/ping', './library/pip', './library/pkgin', './library/postgresql_db', './library/postgresql_user', './library/rabbitmq_parameter', './library/rabbitmq_plugin', './library/rabbitmq_user', './library/rabbitmq_vhost', './library/raw', './library/rhn_channel', './library/s3', './library/script', './library/seboolean', './library/selinux', './library/service', './library/setup', './library/shell', './library/slurp', './library/subversion', './library/supervisorctl', './library/svr4pkg', './library/sysctl', './library/template', './library/uri', './library/user', './library/vagrant', './library/virt', './library/wait_for', './library/yum', './library/zfs'])]

    running egg_info
    writing requirements to pip-egg-info/ansible.egg-info/requires.txt
    writing pip-egg-info/ansible.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/ansible.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/ansible.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found


    reading manifest file 'pip-egg-info/ansible.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/ansible.egg-info/SOURCES.txt'
  Source in /private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible has version 1.1, which satisfies requirement ansible
Downloading/unpacking paramiko (from ansible)

  Running setup.py egg_info for package paramiko

    running egg_info
    writing requirements to pip-egg-info/paramiko.egg-info/requires.txt
    writing pip-egg-info/paramiko.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/paramiko.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/paramiko.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found


    reading manifest file 'pip-egg-info/paramiko.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/paramiko.egg-info/SOURCES.txt'
  Source in /private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/paramiko has version 1.10.1, which satisfies requirement paramiko (from ansible)
Downloading/unpacking jinja2 (from ansible)

  Running setup.py egg_info for package jinja2

    running egg_info
    writing requirements to pip-egg-info/Jinja2.egg-info/requires.txt
    writing pip-egg-info/Jinja2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/Jinja2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/Jinja2.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/Jinja2.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found


    reading manifest file 'pip-egg-info/Jinja2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'docs/_build'

    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'

    warning: no previously-included files matching '*.pyc' found under directory 'docs'

    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'

    warning: no previously-included files matching '*.pyo' found under directory 'docs'

    writing manifest file 'pip-egg-info/Jinja2.egg-info/SOURCES.txt'
  Source in /private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/jinja2 has version 2.6, which satisfies requirement jinja2 (from ansible)
  skipping extra i18n
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/site-packages (from ansible)

Downloading/unpacking pycrypto>=2.1,!=2.4 (from paramiko->ansible)

  Running setup.py egg_info for package pycrypto

    running egg_info
    writing pip-egg-info/pycrypto.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pycrypto.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pycrypto.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found


    reading manifest file 'pip-egg-info/pycrypto.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/pycrypto.egg-info/SOURCES.txt'
  Source in /private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/pycrypto has version 2.6, which satisfies requirement pycrypto>=2.1,!=2.4 (from paramiko->ansible)
Installing collected packages: ansible, paramiko, jinja2, pycrypto

  Running setup.py install for ansible

    Running command /usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools;__file__='/private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-407uhP-record/install-record.txt --single-version-externally-managed
    DATA FILES=[('/usr/share/ansible/', ['./library/add_host', './library/apt', './library/apt_key', './library/apt_repository', './library/assemble', './library/async_status', './library/async_wrapper', './library/authorized_key', './library/bzr', './library/cloudformation', './library/command', './library/copy', './library/cron', './library/debug', './library/django_manage', './library/easy_install', './library/ec2', './library/ec2_facts', './library/ec2_vol', './library/facter', './library/fail', './library/fetch', './library/file', './library/fireball', './library/gem', './library/get_url', './library/git', './library/group', './library/group_by', './library/hg', './library/homebrew', './library/ini_file', './library/lineinfile', './library/lvg', './library/lvol', './library/macports', './library/mail', './library/mongodb_user', './library/mount', './library/mysql_db', './library/mysql_user', './library/nagios', './library/netscaler', './library/ohai', './library/openbsd_pkg', './library/opkg', './library/pacman', './library/pause', './library/ping', './library/pip', './library/pkgin', './library/postgresql_db', './library/postgresql_user', './library/rabbitmq_parameter', './library/rabbitmq_plugin', './library/rabbitmq_user', './library/rabbitmq_vhost', './library/raw', './library/rhn_channel', './library/s3', './library/script', './library/seboolean', './library/selinux', './library/service', './library/setup', './library/shell', './library/slurp', './library/subversion', './library/supervisorctl', './library/svr4pkg', './library/sysctl', './library/template', './library/uri', './library/user', './library/vagrant', './library/virt', './library/wait_for', './library/yum', './library/zfs'])]

    running install
    running build
    running build_py
    running build_scripts
    running install_lib
    running install_data
    creating /usr/share/ansible
    error: could not create '/usr/share/ansible': Permission denied

    Complete output from command /usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools;__file__='/private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-407uhP-record/install-record.txt --single-version-externally-managed:

    DATA FILES=[('/usr/share/ansible/', ['./library/add_host', './library/apt', './library/apt_key', './library/apt_repository', './library/assemble', './library/async_status', './library/async_wrapper', './library/authorized_key', './library/bzr', './library/cloudformation', './library/command', './library/copy', './library/cron', './library/debug', './library/django_manage', './library/easy_install', './library/ec2', './library/ec2_facts', './library/ec2_vol', './library/facter', './library/fail', './library/fetch', './library/file', './library/fireball', './library/gem', './library/get_url', './library/git', './library/group', './library/group_by', './library/hg', './library/homebrew', './library/ini_file', './library/lineinfile', './library/lvg', './library/lvol', './library/macports', './library/mail', './library/mongodb_user', './library/mount', './library/mysql_db', './library/mysql_user', './library/nagios', './library/netscaler', './library/ohai', './library/openbsd_pkg', './library/opkg', './library/pacman', './library/pause', './library/ping', './library/pip', './library/pkgin', './library/postgresql_db', './library/postgresql_user', './library/rabbitmq_parameter', './library/rabbitmq_plugin', './library/rabbitmq_user', './library/rabbitmq_vhost', './library/raw', './library/rhn_channel', './library/s3', './library/script', './library/seboolean', './library/selinux', './library/service', './library/setup', './library/shell', './library/slurp', './library/subversion', './library/supervisorctl', './library/svr4pkg', './library/sysctl', './library/template', './library/uri', './library/user', './library/vagrant', './library/virt', './library/wait_for', './library/yum', './library/zfs'])]

running install

running build

running build_py

running build_scripts

running install_lib

running install_data

creating /usr/share/ansible

error: could not create '/usr/share/ansible': Permission denied

----------------------------------------

Command /usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools;__file__='/private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-407uhP-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible

Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 271, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1185, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 592, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools;__file__='/private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-407uhP-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/mx/mfxgb8450d97ssnd588_bg980000gn/T/pip-build-jimmy/ansible
```

**Comment by mpdehaan** [comment]
You should use sudo in this case.

Ansible is of course super easy to just run from source (source ./hacking/env-setup) and all of the lookup paths can be configured in ~/.ansible.cfg or /etc/ansible/ansible.cfg or via the environment (as ./hacking/env-setup) does.

**Comment by ches** [comment]
Homebrew sets up its Python and pip installation so that `sudo` should never be necessary, so I don't think this is good advice honestly. I haven't yet fully grokked the issue discussed on [the apparent hack in the Ansible constants module](https://github.com/ansible/ansible/blob/b2d881a89928b053d40b87b4c9116a8d4be12aed/lib/ansible/constants.py#L82-L85) that results in `/usr/share/ansible` being effectively hardcoded in the case of Homebrew python/pip, but I'm guessing we could come up with something that avoids this.

As a workaround in the meantime, using a virtualenv to install Ansible with pip works fine, but that's a little inconvenient if you're using Ansible often.

**Comment by ches** [comment]
And FWIW, I'm looking to get a (Mac-using) team set up to learn and use Ansible to manage infrastructure and deploy an app. I want the setup steps I document for them to be as simple to explain (or better yet script) as possible -- `brew install python && pip install ansible` is far better than introducing virtualenvwrapper to a team that isn't familiar with Python development practices, or worse, telling them "check out this repo, source this script and put this repo's bin dir on your path." Someone is probably going to say, "I heard Chef has a one-line installer these days."

I think fixing hacks to improve installation experience is worth a little bit of attention.

**Comment by mpdehaan** [comment]
Patches welcome, honestly it's pretty easy right now.

Ansible is not a python framework, it's just an application, I think it's
100% fine for it to want to use LSB paths.   For those that want to use
other paths, this is all configurable in ansible.cfg

The comparison to Chef and requiring the database, erlang, etc, are not
warranted :)

**Comment by mpdehaan** [comment]
Not sure why you also can't just use sudo.

**Comment by esc** [comment]
Hey, I wanna bump this, I have the same issue on debian. I don't want to use sudo, because I do not want to pollute my system directories.

**Comment by pearofducks** [comment]
I'm working on improving and submitting this exact change for a few platforms, but for now you can manually patch this:
- In `lib/ansible/constants.py`
- replace all `/usr/share/ansible` with `/usr/local/share/ansible`
- Then just run `python setup.py install` from the ansible checkout root

**Comment by lvivski** [comment]
I have `~/.ansible.cfg` with

```
[defaults]
library = /usr/local/share/ansible
```

but still get this error

```
running install_data

creating /usr/share/ansible

error: could not create '/usr/share/ansible': Permission denied
```

**Comment by mblakele** [comment]
For homebrew users, the `ansible.rb` at https://github.com/mxcl/homebrew/pull/21946 may help. To get the devel branch, use `brew install --HEAD ansible`.

If you want to try it before it's merged, this should work:
- 1.2.2: `brew install https://raw.github.com/mblakele/homebrew/7ffb8defd8b8518a0d03a76303cb12578c0669d2/Library/Formula/ansible.rb`
- devel (1.3): `brew install --HEAD https://raw.github.com/mblakele/homebrew/7ffb8defd8b8518a0d03a76303cb12578c0669d2/Library/Formula/ansible.rb`

**Comment by psykidellic** [comment]
I have the same problem. Using Mac OS X and Homebrew. For now, I am just using virtualenv and setting up differently.

Using sudo is probably not the right answer.

**Comment by FredworkLemmas** [comment]
As best I can tell, there is no good way to install ansible in a virtualenv in ubuntu 12.04.  'pip install ansible' fails with:

  error: could not delete '/usr/share/ansible/commands/script': Permission denied

'sudo pip install ansible' succeeds but doesn't do anything useful as it reports that the requirement is already satisfied and leaves ansible as unusable as it was.

but installing ansible in a virtualenv is a bit of a hack in that it really can (and should?) be installed system-wide...what folks are looking for here is probably something more like:

  PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin" ansible-playbook something.yml

which will prevent ansible from using the virtualenv version of python.

it's what worked for me anyway.

cheers

**Comment by hgdeoro** [comment]
FYI: I had the same problem (`pip install ansible` trying to install to /usr/local). Removing the virtualenv and re-creating it solved my problem.

**Comment by cpbotha** [comment]
With pip 1.5.4 and virtualenv 1.11.4 on Ubuntu 12.04.4 I get the following:

```
virtualenv py1
source py1/bin/activate
pip install ansible
```

which gives the following output:

```
Downloading/unpacking ansible
  Downloading ansible-1.5.5.tar.gz (543kB): 543kB downloaded

... more dependencies downloaded

byte-compiling /home/cn/cnidspy/lib/python2.7/site-packages/ansible/playbook/play.py to play.pyc

byte-compiling /home/cn/cnidspy/lib/python2.7/site-packages/ansible/playbook/task.py to task.pyc

byte-compiling /home/cn/cnidspy/lib/python2.7/site-packages/ansible/playbook/__init__.py to __init__.pyc

running install_data

creating /usr/share/ansible

error: could not create '/usr/share/ansible': Permission denied
```

How should I go about installing ansible in this virtualenv? It has to be possible right??!

(to clarify: ansible is causing a whole pip install -r requirements.txt job to fail. would be nice to have a workaround for this. Seems related to https://github.com/ansible/ansible/issues/5814 )

**Comment by cpbotha** [comment]
Problem found! From a previous `sudo pip install ansible`, the `/etc/ansible/ansible.cfg` was interfering with this virtualenv `pip install`. Nuked the system `/etc/ansible` (we only need virtualenv ansible) and all is good.

**Comment by elimisteve** [comment]
Thanks for the tip @cpbotha. I moved /etc/ansible/ansible.cfg, did just `pip install ansible`, then moved it back. Everything seems to work. Sweet!

**Comment by fawkesley** [comment]
@cpbotha +1 - thanks for tip

**Comment by Tinche** [comment]
You know, if Ansible would just use pkg_resources for accessing data files it'd be less hacky and Ansible could actually run out of a PEX, which would be pretty cool.

**Comment by fawkesley** [comment]
What's a PEX?

**Comment by Tinche** [comment]
It's a way to put an entire virtual environment into a single executable file, with no outside dependencies. Like Java "fat jars", if you're familiar with those.

So you could have a single file, ansible.pex, with all Ansible functionality inside. It'd be a little more complicated (since Ansible doesn't use entry points) but that's the gist of it. I personally was looking into this as an easy way of harnessing Ansible for the creation of Docker images without running an SSH server inside the container - just transfer the PEX file over and run the playbook from the inside with --connection=local.

http://pex.readthedocs.org/en/latest/

**Comment by fawkesley** [comment]
Wow that's awesome, thanks. Have been looking for something like this.

**Comment by Tinche** [comment]
The idea is basically the same as in http://www.ansible.com/blog/2014/02/12/installing-and-building-docker-with-ansible, but with many fewer moving parts. But alas...

**Comment by Nowaker** [comment]
It's a pity it can't be installed with `pip install --user`. Maybe you could hint a different way to achieve my goal?

I develop [VirtKick, a simple cloud management panel (orchestrator)](https://www.virtkick.io). It will autoconfigure hypervisors (libvirt, QEMU, dnsmasq etc) so VirtKick users don't need to do anything other than entering the hostname and root password. Both Ansible and [Rex](http://www.rexify.org/) look great for this use case as they don't need any agent/client on the target machine. VirtKick itself is supposed to be installed with 1-click too, so I'd rather "embed" a particular, working version of Ansible/Rex in VirtKick, rather than requiring that users have Ansible installed themselves. For this reason I need `pip` to install everything locally, so I can package the files and ship with VirtKick.

Ideas are welcome. Thanks.

EDIT: Nevermind. Discovered `hacking` directory and it's perfectly doing what I need.
