### ISSUE TITLE
Playbooks containing nothing in notify crash

### ISSUE THREAD

**Issue by sYnfo** [ansible/ansible#3028]
```
- name: foo
  hosts: 127.0.0.1
  user: root

  tasks:
  - name: bar
    action: shell echo "Timber!"
    notify:
```

fails with

```
Traceback (most recent call last):
  File "/foo/bin/ansible-playbook", line 235, in <module>
    sys.exit(main(sys.argv[1:]))
  File "foobin/ansible-playbook", line 181, in main
    pb.run()
  File "/foo/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 245, in run
    if not self._run_play(play):
  File "/foo/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 531, in _run_play
    if not self._run_task(play, task, False):
  File "/foo/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 362, in _run_task
    if len(task.notify) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by mpdehaan** [comment]
Don't do this.
