### ISSUE TITLE
UnicodeEncodeError with --step and a unicode named task

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#3042]
UnicodeEncodeError is occured with --step and a unicode named task.
Without --step, the error is not occured.

```
  tasks:
  - name: こんにちは
    get_url: url=http://yahoo.com/index.html dest=/tmp/blah
```

Traceback is below.

```
Traceback (most recent call last):
  File "/home/shirou/Works/VEnvs/ansible/bin/ansible-playbook", line 235, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/shirou/Works/VEnvs/ansible/bin/ansible-playbook", line 181, in main
    pb.run()
  File "/home/shirou/Works/VEnvs/ansible/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 245, in run
    if not self._run_play(play):
  File "/home/shirou/Works/VEnvs/ansible/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 531, in _run_play
    if not self._run_task(play, task, False):
  File "/home/shirou/Works/VEnvs/ansible/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 326, in _run_task
    self.callbacks.on_task_start(template(play.basedir, task.name, task.module_vars, lookup_fatal=False), is_handler)
  File "/home/shirou/Works/VEnvs/ansible/local/lib/python2.7/site-packages/ansible/callbacks.py", line 551, in on_task_start
    resp = raw_input('Perform task: %s (y/n/c): ' % name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-18: ordinal not in range(128)
```

python version: 2.7.3

**Comment by bcoca** [comment]
try " export PYTHONIOENCODING='utf_8' " before running the playbook with

## --step

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by shirou** [comment]
PYTHONIOENCODING did not work. 
I tried this and works for me.
(sys.stdout.encoding should be change to 'utf-8' same as other parts?)

```
diff --git a/lib/ansible/callbacks.py b/lib/ansible/callbacks.py
index c00ba6d..dec5990 100644
--- a/lib/ansible/callbacks.py
+++ b/lib/ansible/callbacks.py
@@ -552,7 +552,8 @@ class PlaybookCallbacks(object):
         if hasattr(self, 'start_at'): # we still have start_at so skip the task
             self.skip_task = True
         elif hasattr(self, 'step') and self.step:
-            resp = raw_input('Perform task: %s (y/n/c): ' % name)
+            msg = ('Perform task: %s (y/n/c): ' % name).encode(sys.stdout.encoding)
+            resp = raw_input(msg)
             if resp.lower() in ['y','yes']:
                 self.skip_task = False
                 display(banner(msg))
```

**Comment by mpdehaan** [comment]
closing per above pull request, thanks!
