### ISSUE TITLE
remote script directory is not removed from `sys.path` when `remote_tmp` is a link

### ISSUE THREAD

**Issue by kostrzewa9ld** [ansible/ansible#30540]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* tempfile
* remote files handling in general

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /tmp/original/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
`ansible.cfg`:
```
[defaults]
remote_tmp: /tmp/link
```

##### OS / ENVIRONMENT
```
Linux ic5-16 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
Linux Mint 18.1 Serena \n \l
```

##### SUMMARY
When `remote_tmp` is a link it is not removed from `sys.path` in uploaded module. In case of `tempfile`,  it clashes with original python module which it uses.

##### STEPS TO REPRODUCE
```
mkdir -p /tmp/original /tmp/ansible
ln -s /tmp/original /tmp/link
echo "[defaults]\nremote_tmp: /tmp/link" > /tmp/ansible/ansible.cfg

cd /tmp/ansible && ansible -m tempfile localhost -vvv
```

##### EXPECTED RESULTS
Module `tempfile` should succeed.

##### ACTUAL RESULTS
```
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/tempfile.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: kostrzewa
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/link/ansible-tmp-1505799554.81-197426653923554 `" && echo ansible-tmp-1505799554.81-197426653923554="` echo /tmp/link/ansible-tmp-1505799554.81-197426653923554 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpXX2me4 TO /tmp/link/ansible-tmp-1505799554.81-197426653923554/tempfile.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/link/ansible-tmp-1505799554.81-197426653923554/ /tmp/link/ansible-tmp-1505799554.81-197426653923554/tempfile.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /tmp/link/ansible-tmp-1505799554.81-197426653923554/tempfile.py; rm -rf "/tmp/link/ansible-tmp-1505799554.81-197426653923554/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/link/ansible-tmp-1505799554.81-197426653923554/tempfile.py", line 136, in <module>
    shutil.rmtree(temp_path)
NameError: name 'temp_path' is not defined

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/link/ansible-tmp-1505799554.81-197426653923554/tempfile.py\", line 136, in <module>\n    shutil.rmtree(temp_path)\nNameError: name 'temp_path' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

##### EXTRA INFO
This happens because:
* remote module is invoked through path with a link
* in order to remove script's directory from `sys.path` module handling code resolves the path to script directory with `os.path.abspath()`
* in `sys.path` the script directory is registered with real path

thus script directory is not removed from `sys.path` and because ansible module has the same name as python module when it calls `import tempfile` it ends up importing itself.

When running ansible with `ANSIBLE_KEEP_REMOTE_FILES=1` and invoking the module directly, with some debug prints, I get:
```
/tmp/link$ /tmp/link/ansible-tmp-1505798980.71-111952868906477/tempfile.py 
scriptdir: /tmp/link/ansible-tmp-1505798980.71-111952868906477
sys.path: ['/tmp/original/ansible-tmp-1505798980.71-111952868906477', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
scriptdir: /tmp/link/ansible-tmp-1505798980.71-111952868906477
sys.path: ['/tmp/original/ansible-tmp-1505798980.71-111952868906477', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
Traceback (most recent call last):
  File "/tmp/link/ansible-tmp-1505798980.71-111952868906477/tempfile.py", line 281, in <module>
    shutil.rmtree(temp_path)
NameError: name 'temp_path' is not defined
```

After changing:
```
 56     scriptdir = os.path.dirname(os.path.abspath(__main__.__file__))
```
to:
```
 56     scriptdir = os.path.dirname(os.path.realpath(__main__.__file__))
```
the module starts to work.

**Comment by nrwahl2** [comment]
@kostrzewa9ld Can you test on the devel branch? The only place I can find the line you changed is in `executor/module_common.py` (not mentioned in this thread so far), which contains the following block of code:
```
scriptdir = None
try:
    scriptdir = os.path.dirname(os.path.realpath(__main__.__file__))
except (AttributeError, OSError):
    # Some platforms don't set __file__ when reading from stdin
    # OSX raises OSError if using abspath() in a directory we don't have
    # permission to read (realpath calls abspath)
    pass
if scriptdir is not None:
    sys.path = [p for p in sys.path if p != scriptdir]
```

**Comment by kostrzewa9ld** [comment]
@nrwahl2, that's exactly the place. I have tested it on `2.5.0` and it works. Closing the issue.
