### ISSUE TITLE
ansible-vault edit and encrypt output different payload format version

### ISSUE THREAD

**Issue by colinjc** [ansible/ansible#30575]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-vault

##### ANSIBLE VERSION

```
ansible 2.4.0.0
```

##### SUMMARY

When I encrypt a file with ```ansible-vault encrypt vault_name --vault-id staging@vault_pass``` it creates a file with the header
```$ANSIBLE_VAULT;1.2;AES256;staging```
When editing a vault file with ```ansible-vault edit vault_name --vault-id staging@vault_pass``` the vault is outputting with a header of
```$ANSIBLE_VAULT;1.1;AES256```
If I have made any changes and try to edit the file again, the following error occurs.
```ERROR! Unexpected Exception, this is probably a bug: list index out of range```
There is no error if I make no changes.

If I run decrypt it is successful. If I then run
```ansible-vault encrypt vault_name --vault_id staging@vault_pass```
the vault is outputting with a header of ```$ANSIBLE_VAULT;1.2;AES256;staging``` and I can run ```ansible-deploy edit``` again successfully.

##### STEPS TO REPRODUCE
```bash
ansible-vault edit vault_name --vault-id staging@vault_pass
ansible-vault edit vault_name --vault-id staging@vault_pass
ansible-vault decrypt vault_name --vault_id staging@vault_pass
ansible-vault encrypt vault_name --vault_id staging@vault_pass
```
##### ACTUAL RESULTS

```bash
$ head -n1 vault
$ANSIBLE_VAULT;1.2;AES256;staging
$ ansible-vault edit vault_name --vault_id staging@vault_pass
$ head -n1 group_vars/staging/vault
$ANSIBLE_VAULT;1.1;AES256
$ ansible-vault edit vault_name --vault_id staging@vault_pass
$ ERROR! Unexpected Exception, this is probably a bug: list index out of range
ansible-vault decrypt vault_name --vault_id staging@vault_pass
ansible-vault encrypt vault_name --vault_id staging@vault_pass
$ head -n1 vault
$ANSIBLE_VAULT;1.2;AES256;staging
```

**Comment by alikins** [comment]
Is there an 'vault_password_file' or 'vault_identity_list' setup in configuration?

Running 'ansible-vault' with a high verbosity level will show some details about which vault-ids are being used.

**Comment by alikins** [comment]
I can reproduce this:

```
[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ echo '30575' > vault_30575.yml

[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ ansible-vault encrypt -vvv --vault-id staging@password vault_30575.yml 
ansible-vault 2.5.0 (facts_arch_linux_30600 08cca42fd4) last updated 2017/09/22 10:22:26 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-vault
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
Using /home/adrian/src/ansible/ansible.cfg as config file
Encryption successful

[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ cat vault_30575.yml 
$ANSIBLE_VAULT;1.2;AES256;staging
<..>
```

vault edit without any changes

```
[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ ansible-vault edit -vvvvvv --vault-id staging@password vault_30575.yml 
< version info snipped >
Using /home/adrian/src/ansible/ansible.cfg as config file
Reading vault password file: password
Found a vault_id (staging) in the vaulttext
We have a secret associated with vault id (staging), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/home/adrian/src/ansible/password')) id=staging to decrypt None
Trying secret FileVaultSecret(filename='/home/adrian/src/ansible/password') for vault_id=staging
decrypt succesful with secret=FileVaultSecret(filename='/home/adrian/src/ansible/password') and vault_id=staging

[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ cat vault_30575.yml
$ANSIBLE_VAULT;1.2;AES256;staging
<..>
```

vault edit, making and saving changes:

```
[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ ansible-vault edit -vvvvvv --vault-id staging@password vault_30575.yml 
< version info snipped >

Using /home/adrian/src/ansible/ansible.cfg as config file
Reading vault password file: password
Found a vault_id (staging) in the vaulttext
We have a secret associated with vault id (staging), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/home/adrian/src/ansible/password')) id=staging to decrypt None
Trying secret FileVaultSecret(filename='/home/adrian/src/ansible/password') for vault_id=staging
decrypt succesful with secret=FileVaultSecret(filename='/home/adrian/src/ansible/password') and vault_id=staging
Encrypting with vault secret FileVaultSecret(filename='/home/adrian/src/ansible/password')

[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ cat vault_30575.yml
$ANSIBLE_VAULT;1.1;AES256
<..>
```

vault edit again: 

```
[newswoop:F25:ansible (facts_arch_linux_30600 %)]$ ansible-vault edit -vvvvvv --vault-id staging@password vault_30575.yml 
< version info snipped >
Using /home/adrian/src/ansible/ansible.cfg as config file
Reading vault password file: password
Found a vault_id (default) in the vaulttext
Found a vault_id (default) in the vault text, but we do not have a associated secret (--vault-id)
Trying to use vault secret=(FileVaultSecret(filename='/home/adrian/src/ansible/password')) id=staging to decrypt None
Trying secret FileVaultSecret(filename='/home/adrian/src/ansible/password') for vault_id=staging
decrypt succesful with secret=FileVaultSecret(filename='/home/adrian/src/ansible/password') and vault_id=staging
ERROR! Unexpected Exception, this is probably a bug: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-vault", line 109, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/vault.py", line 228, in run
    self.execute()
  File "/home/adrian/src/ansible/lib/ansible/cli/__init__.py", line 154, in execute
    fn()
  File "/home/adrian/src/ansible/lib/ansible/cli/vault.py", line 419, in execute_edit
    self.editor.edit_file(f)
  File "/home/adrian/src/ansible/lib/ansible/parsing/vault/__init__.py", line 768, in edit_file
    secret = secrets[0][1]
IndexError: list index out of range

```

**Comment by alikins** [comment]
@colinjc Thanks for the great bug report btw! Looking into a fix now.

**Comment by alikins** [comment]
Looks like the vault_id is getting dropped on the encrypt after edit with change. (vault_id isnt passed to encrypt correctly there so got a fix for that).

The traceback is from an assumption in edit that if we can decrypt, then we have a matching vault-id in the secrets. Because of above bug, on the second edit, the vault id from the edited file is unset (or 'default') but the only vault-id in secrets is 'staging'. Then the vault-id match returns a empty secrets list, and the the secrets[0][1] reference throws the IndexError.

**Comment by alikins** [comment]
#30772 should fix this if you want to try it out.

**Comment by alikins** [comment]
Cherry-picked to stable-2.4 in 042079aa8776254aa6c8c52da1aa9da23b57a736 (chery-pick of a14d0f3586617f678b2843a25b521243a99cd589 from https://github.com/ansible/ansible/issues/30772)
