### ISSUE TITLE
Removing cowsay in ansible playbook fails

### ISSUE THREAD

**Issue by tbekolay** [ansible/ansible#3092]
Running the following task crashes `ansible-playbook`.

```
- name: remove cowsay
  apt: pkg=cowsay state=absent purge=yes
```

The error is:

```
Traceback (most recent call last):
  File "/home/tbekolay/.virtualenvs/ansible/bin/ansible-playbook", line 209, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/tbekolay/.virtualenvs/ansible/bin/ansible-playbook", line 180, in main
    pb.run()
  File "/home/tbekolay/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 235, in run
    if not self._run_play(play):
  File "/home/tbekolay/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 419, in _run_play
    self.callbacks.on_play_start(play.name)
  File "/home/tbekolay/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/callbacks.py", line 536, in on_play_start
    print banner("PLAY [%s]" % pattern)
  File "/home/tbekolay/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/callbacks.py", line 150, in banner
    cmd = subprocess.Popen(runcmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

This is not terribly surprising, and I was mostly curious to see what would happen, but perhaps it should be possible to switch from using `cowsay` to not on the fly? `cowsay` does get removed, by the way, but of course the rest of the playbook does not get executed.

**Comment by mpdehaan** [comment]
Fix pushed in 4840e59

**Comment by tbekolay** [comment]
Wow! A kind of silly issue fixed in half an hour on a Saturday with a tongue in cheek commit :) And I thought I couldn't like ansible any more!

**Comment by bcoca** [comment]
I would have auto deleted the playbook
Brian Coca
