### ISSUE TITLE
Issue when opening Vault with python

### ISSUE THREAD

**Issue by j-cavoizy** [ansible/ansible#30969]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/homeipa/jcavoizy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

Nothing Changed

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS (trusty)

##### SUMMARY

Since we upgraded to ansible-vault (1.0.4) the code below doesn't work anymore 

##### STEPS TO REPRODUCE

```
>>> from ansible_vault import Vault
>>> vault = Vault("passphrase")
>>> data = vault.load(open('vault.yml').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ansible_vault/api.py", line 18, in load
    return yaml.load(self.vault.decrypt(stream))
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 543, in decrypt
    _matches = match_secrets(self.secrets, vault_id_matchers)
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 399, in match_secrets
    matches = [(vault_id, secret) for vault_id, secret in secrets if vault_id in target_vault_ids]
ValueError: need more than 1 value to unpack
>>>
```

##### EXPECTED RESULTS

I expect vault vars to be loaded in 'data' dict 

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ansible_vault/api.py", line 18, in load
    return yaml.load(self.vault.decrypt(stream))
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 543, in decrypt
    _matches = match_secrets(self.secrets, vault_id_matchers)
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 399, in match_secrets
    matches = [(vault_id, secret) for vault_id, secret in secrets if vault_id in target_vault_ids]
ValueError: need more than 1 value to unpack
```

**Comment by sivel** [comment]
The python API is not a public API and will sometimes change from release to release.  As the ansible bin scripts are not affected, this is a result of your API use being inconsistent with the new code.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
