### ISSUE TITLE
Simple localhost ini inventory file won't load when running playbook

### ISSUE THREAD

**Issue by tonytan4ever** [ansible/ansible#31032]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

InventoryManager

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/tonytan4ever/.ansible.cfg
  configured module search path = [u'/Users/tonytan4ever/.ansible/plugins/library']
  ansible python module location = /Users/tonytan4ever/bin/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/tonytan4ever/bin/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

```
DEFAULT_MODULE_PATH(/Users/tonytan4ever/.ansible.cfg) = [u'/Users/tonytan4ever/.ansible/plugins/library']
DEFAULT_ROLES_PATH(/Users/tonytan4ever/.ansible.cfg) = [u'/Users/tonytan4ever/.ansible/roles']
DEFAULT_TRANSPORT(/Users/tonytan4ever/.ansible.cfg) = ssh
HOST_KEY_CHECKING(/Users/tonytan4ever/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Mac OSX 10.12.6

##### SUMMARY

 A simple ini inventory won't load when running a play book.

```
$ ansible-playbook -i inventory/example.ini hello_world.yml -vvv
```  

##### STEPS TO REPRODUCE

```ini
localhost 

[lh]
localhost ansible_connection=local
```

```yaml
- name: Hello World!
  hosts: lh
  tasks:
  - name: Hello World!
    shell: echo "Hello world!"
```

##### EXPECTED RESULTS

```
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
ansible-playbook 2.4.0.0
  config file = /Users/tonytan4ever/.ansible.cfg
  configured module search path = [u'/Users/tonytan4ever/.ansible/plugins/library']
  ansible python module location = /Users/tonytan4ever/bin/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/tonytan4ever/bin/ansible/bin/ansible-playbook
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Using /Users/tonytan4ever/.ansible.cfg as config file
Parsed /Users/tonytan4ever/projects/Mine/hodge-podge/ansible_playground/inventory/example.ini inventory source with ini plugin

PLAYBOOK: hello_world.yml *************************************************************************************************************************
1 plays in hello_world.yml

PLAY [Hello World!] *******************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
**ERROR! Unexpected Exception, this is probably a bug: 'InventoryManager' object has no attribute 'get_group_dict'**
the full traceback was:

Traceback (most recent call last):
  File "/Users/tonytan4ever/bin/ansible/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/Users/tonytan4ever/bin/ansible/lib/python2.7/site-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/Users/tonytan4ever/bin/ansible/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/Users/tonytan4ever/bin/ansible/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 292, in run
    play_return = strategy.run(iterator, play_context)
  File "/Users/tonytan4ever/bin/ansible/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 277, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/Users/tonytan4ever/.ansible/plugins/strategy/linear.py", line 119, in _queue_task
    groups = self._inventory.get_group_dict()
AttributeError: 'InventoryManager' object has no attribute 'get_group_dict'
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

The issue is caused by a custom strategy plugin that is using an API that does not exist anymore.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
