### ISSUE TITLE
ansible-inventory failure with vaulted value in yaml inventory

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#31141]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`ansible-inventory` CLI

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

Also tested in 2.4, same behavior.

##### CONFIGURATION
```
ansible-config dump --only-changed
```
(no output)

##### OS / ENVIRONMENT
Running from Mac, python 2.7
controlling N/A

##### SUMMARY
Putting a vaulted value inside of a yaml inventory file causes an error running `ansible-inventory` on that file, apparently related to the serialization before writing the result to the terminal.

##### STEPS TO REPRODUCE
Use the following as your inventory file. Save file to `vault/yaml_subvar/ansible_example.yml` relative to where you're running it from, [example file in source control](https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/vault/yaml_subvar/ansible_example.yml).

```yaml
# https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
ungrouped:
  hosts:
      green.example.com:
          firstvariable: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              32633234373965356537366531333238363166393039306462633137353462396335653531633637
              6335366138623264303862306535303366646630643262650a386433376130383562343037613764
              62653330643635623033323764383461613331336339336435633864303032646233393336643366
              6163383166626565660a623836303939326564346338343338346366373561623862633065613266
              6132
          anyvariable: value
```

Now run `ansible-inventory` to list the outputs from this. Provide "password" as the vault password, as that is the password I used to vault the contents with `ansible-vault encrypt_string 191.168.100.32`. As so:

```
ansible-inventory -i vault/yaml_subvar/ansible_example.yml --list --ask-vault-pass -vvv
```

##### EXPECTED RESULTS
```
{
    "_meta": {
        "hostvars": {
            "green.example.com": {
                "firstvariable": "191.168.100.32", 
                "anyvariable": "value"
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "green.example.com"
        ]
    }
}
```

How am I sure of the validity of this expectation? Corresponding `ansible-playbook` command:

```
ansible-playbook -i vault/yaml_subvar/ansible_example.yml --ask-vault-pass debug.yml
```

(the vault password "password" is provided to this command as well)

Contents of `debug.yml`:

```
---

- hosts: all
  gather_facts: false
  vars:
    msg: 'hello world {{ firstvariable }}'
  tasks:
    - debug: var=msg
```

output:

```
Vault password: 

PLAY [all] *************************************************************************************************************************************************************

TASK [debug] ***********************************************************************************************************************************************************
ok: [green.example.com] => {
    "msg": "hello world 191.168.100.32"
}

PLAY RECAP *************************************************************************************************************************************************************
green.example.com          : ok=1    changed=0    unreachable=0    failed=0  
```

This proves that the functionality of Ansible works. Thus, the problem lies with `ansible-inventory` alone.

##### ACTUAL RESULTS
```
ansible-inventory 2.5.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-inventory
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
No config file found; using defaults
Vault password: 
Parsed /Users/alancoding/Documents/repos/ansible-inventory-file-examples/vault/yaml_subvar/ansible_example.yml inventory source with yaml plugin
ERROR! Unexpected Exception, this is probably a bug: u'191.168.100.32' is not JSON serializable
the full traceback was:

Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/EGG-INFO/scripts/ansible-inventory", line 109, in <module>
    exit_code = cli.run()
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/cli/inventory.py", line 164, in run
    results = self.dump(results)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/cli/inventory.py", line 181, in dump
    results = json.dumps(stuff, sort_keys=True, indent=4)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: u'191.168.100.32' is not JSON serializable
```

Note that the value was successfully unencrypted (191.168.100.32). Some kind of display/unicode error prevented the data's serialization.

**Comment by naisanza** [comment]
@AlanCoding So from what I'm seeing is, `firstvariable` is equal to `191.168.100.32` ?

Based from:

```yaml
msg: 'hello world {{ firstvariable }}'

"msg": "hello world 191.168.100.32"
```

But, in your steps you said:

```yaml
firstvariable: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              32633234373965356537366531333238363166393039306462633137353462396335653531633637
              6335366138623264303862306535303366646630643262650a386433376130383562343037613764
              62653330643635623033323764383461613331336339336435633864303032646233393336643366
              6163383166626565660a623836303939326564346338343338346366373561623862633065613266
              6132
```
Is expected to give:

```yaml
"ansible_ssh_host": "191.168.100.32"
```

I'm a little confused. Was the encrypted `firstvariable` a separate vars reference file that would be replaced with `"ansible_ssh_host": "191.168.100.32"` once Vault had decrypted and substituted it into the final output?

**Comment by AlanCoding** [comment]
sorry about that, I was editing the example as I was doing this, it should be `firstvariable`, not `ansible_ssh_host`. I had swapped them to rule out any role of magic variables. (edited original report)

**Comment by naisanza** [comment]
Does it work if the entire playbook is encrypted?

**Comment by AlanCoding** [comment]
(tested) Yes, that does work, but the playbook example already worked. Or did you mean to ask about encrypting the entire inventory file?

**Comment by kudrevatykh** [comment]
ansible-inventory with `--yaml` option also does not work properly
1. when variable assigned to single host output is encrypted
2. when variable assigned to multiply hosts output is mailformed with `&id001` and `*id001` symbols

example can be found in https://gist.github.com/kudrevatykh/39875c9939d7248cd91f7bd1155a22ae

**Comment by alikins** [comment]
Possibly related to https://github.com/ansible/ansible/issues/32160

**Comment by bcoca** [comment]
@kudrevatykh first, that is unrelated to this issue, please don't hijack the subject. In any case, that is not a bug, that is how YAML normally exports a repeated variable.

**Comment by AlanCoding** [comment]
This is no longer a bug, resolved with @bcoca's enhancements to `ansible-inventory` vault secrets pass-through.

proof

```
ansible-inventory -i vault/yaml_subvar/ansible_example.yml --list --ask-vault-pass -vvv
ansible-inventory 2.7.0.dev0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.7.0.dev0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-inventory
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
No config file found; using defaults
Vault password: 
Parsed /Users/alancoding/Documents/repos/ansible-inventory-file-examples/vault/yaml_subvar/ansible_example.yml inventory source with yaml plugin
{
    "_meta": {
        "hostvars": {
            "green.example.com": {
                "anyvariable": "value", 
                "firstvariable": {
                    "__ansible_vault": "$ANSIBLE_VAULT;1.1;AES256\n32633234373965356537366531333238363166393039306462633137353462396335653531633637\n6335366138623264303862306535303366646630643262650a386433376130383562343037613764\n62653330643635623033323764383461613331336339336435633864303032646233393336643366\n6163383166626565660a623836303939326564346338343338346366373561623862633065613266\n6132\n"
                }
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "green.example.com"
        ]
    }
}
```
