### ISSUE TITLE
ansible-inventory exception when vars contain things that look like datetime

### ISSUE THREAD

**Issue by eikef** [ansible/ansible#31181]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-inventory (and possibly others)

##### ANSIBLE VERSION
2.4.0.0

##### CONFIGURATION
ANSIBLE_SSH_PIPELINING = True
DEFAULT_GATHERING = smart
DEFAULT_HASH_BEHAVIOUR = merge

##### OS / ENVIRONMENT
Both Fedora 26 and the default AWX docker container exhibit this behavior

##### SUMMARY
When a YAML vars file contains a fact that looks like a datetime-String, it will be parsed as a datetime string. This works wonderfully.
Unfortunately when then using ansible-inventory -i inventory --list, an exception is thrown (for instance:

```
ERROR! Unexpected Exception, this is probably a bug: datetime.datetime(2017, 3, 7, 10, 20, 49) is not JSON serializable
```

##### STEPS TO REPRODUCE

inventory:
```
[test]

localhost
```

host_vars/localhost:
```yaml
---

testdata: 2017-03-07T10:20:49Z
```

```bash
ansible-inventory -i inventory --list
```

##### EXPECTED RESULTS

Either a serialized JSON string and no exception, or an explicit warning that this is not supported (and possibly also emit this warning during regular ansible parsin of vars-files)

##### ACTUAL RESULTS
```
ERROR! Unexpected Exception, this is probably a bug: datetime.datetime(2017, 3, 7, 10, 20, 49) is not JSON serializable
```

A workaround is to put quotes around the datetime-string so that YAML will interpret it as a mere string and not a datetime object.

**Comment by AlanCoding** [comment]
I was able to replicate (using 2.5 here). Verbose output:

```
ansible-inventory -i issues/datetime/inventory.ini --list -vvv
```

```
ansible-inventory 2.5.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-inventory
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
No config file found; using defaults
Parsed /Users/alancoding/Documents/repos/ansible-inventory-file-examples/issues/datetime/inventory.ini inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: datetime.datetime(2017, 3, 7, 10, 20, 49) is not JSON serializable
the full traceback was:

Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/EGG-INFO/scripts/ansible-inventory", line 109, in <module>
    exit_code = cli.run()
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/cli/inventory.py", line 164, in run
    results = self.dump(results)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/cli/inventory.py", line 181, in dump
    results = json.dumps(stuff, sort_keys=True, indent=4)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 3, 7, 10, 20, 49) is not JSON serializable
```

Both this and #31141 run through the line `results = json.dumps(stuff, sort_keys=True, indent=4)`, both of which are related to the fact that you can't really JSON dump dicts with python objects in them.

**Comment by sivel** [comment]
YAML automatically supports date like values, and if it matches the regex in YAML, it will be automatically converted to a datetime.  You will need to ensure you quote that value in your YAML to avoid the implicit conversion to datetime

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by AlanCoding** [comment]
^ comment made me think to try adding the `--yaml` flag:

```
ansible-inventory -i issues/datetime/inventory.ini --list --yaml
```

Turns out that works, because the datetime objects are understood by YAML, but not JSON.

```
all:
  children:
    test:
      hosts:
        localhost:
          testdata: 2017-03-07 10:20:49
    ungrouped: {}
```

But accepting this at face value - it might mean that `ansible-inventory` could actually be more robust if used to output YAML.
