### ISSUE TITLE
Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by joelwking** [ansible/ansible#31249]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-playbook
##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 101377768b) last updated 2017/10/03 14:54:07 (GMT +000)
  config file = /sbux_ansible/ansible.cfg
  configured module search path = [u'/sbux_ansible/library', u'/usr/share/ansible']
  ansible python module location = /home/ubuntu/ansible/lib/ansible
  executable location = /home/ubuntu/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
also in 2.4, and observed in 2.3
```
ansible 2.3.1.0
  config file = /home/administrator/ansible/playbooks/ansible.cfg
  configured module search path = [u'/usr/share/ansible/']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/sbux_ansible/ansible.cfg) = [u'/sbux_ansible/inventory.txt']
DEFAULT_MODULE_PATH(/sbux_ansible/ansible.cfg) = [u'/sbux_ansible/library', u'/usr/share/ansible']
RETRY_FILES_ENABLED(/sbux_ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

`ubuntu/xenial64`
##### SUMMARY

Method `play.get_vars_files()` returns None rather than an empty list. In very large playbooks, it is not obvious what is causing the exception.
##### STEPS TO REPRODUCE

If `vars_files` has no entries (note the comment), the play fails with `TypeError: 'NoneType' object is not iterable`

```yaml
#!/usr/bin/ansible-playbook
---
#
#
#      Copyright (c) 2017 World Wide Technology, Inc.
#      All rights reserved.
#
#      author: Joel W. King,  World Wide Technology
#
#
- hosts: localhost
  connection: local
  user: administrator

  vars_files:
   #  - "{{playbook_dir}}/passwords.yml"

  tasks:
  - name: debug the output
    debug: msg="{{f5.username}}"

```

##### EXPECTED RESULTS

Ignore the empty list or issue a warning to the user.
##### ACTUAL RESULTS

```
ubuntu@ubuntu-xenial:~/ansible/playbooks$ ansible-playbook ./debug_vars_files.yml -vvv
ansible-playbook 2.5.0 (devel 101377768b) last updated 2017/10/03 14:54:07 (GMT +000)
  config file = /sbux_ansible/ansible.cfg
  configured module search path = [u'/sbux_ansible/library', u'/usr/share/ansible']
  ansible python module location = /home/ubuntu/ansible/lib/ansible
  executable location = /home/ubuntu/ansible/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /sbux_ansible/ansible.cfg as config file
Parsed /sbux_ansible/inventory.txt inventory source with ini plugin

PLAYBOOK: debug_vars_files.yml *****************************************************************************************************
1 plays in ./debug_vars_files.yml
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/home/ubuntu/ansible/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/home/ubuntu/ansible/lib/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/home/ubuntu/ansible/lib/ansible/executor/playbook_executor.py", line 126, in run
    all_vars = self._variable_manager.get_vars(play=play)
  File "/home/ubuntu/ansible/lib/ansible/vars/manager.py", line 348, in get_vars
    for vars_file_item in play.get_vars_files():
TypeError: 'NoneType' object is not iterable
```

**Comment by ryansb** [comment]
The workaround here is, of course, to supply an empty list instead of a `None`. I notice that the vars file attributes are defaulted to `[]`, but won't override if the use supplies `None` which we could definitely handle more gracefully.
