### ISSUE TITLE
AWS | ERROR! Unexpected Exception, this is probably a bug: u'localhost'

### ISSUE THREAD

**Issue by winstonsimon** [ansible/ansible#31274]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

AWS Plugin

##### ANSIBLE VERSION

```
ansible --version                                                                                                                               
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/winston/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Oct  3 2017, 20:07:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
```
  - name: Load configuration for {{ envName }}_{{ region }}
    group_by: key="{{ envName }}_{{ region }}"

  - name: "Creating the security group for the {{ subsystem }} ELBs"
    ec2_group:
      name: "{{ group }}-{{ envName }}-elb-sg-{{ subsystem }}-{{ region }}"
      description: "{{ subsystem }} public elb security group for {{ envName }} and {{ region }}."
      state: present
      region: "{{ region }}"
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: tcp
          from_port: 443
          to_port: 443
          group_name: "{{ group }}-{{ envName }}-server-sg-{{ subsystem }}-{{ region }}"
          group_desc: "{{ subsystem }} server security group for {{ envName }} and {{ region }}."

```

##### OS / ENVIRONMENT

AWS

##### SUMMARY
We upgrade Ansible version from 2.3 to 2.4 which broken our pipeline due to following error.

Here is our folder structure:
<img width="917" alt="screen shot 2017-10-03 at 8 48 38 pm" src="https://user-images.githubusercontent.com/3705316/31159219-68a78c0a-a87c-11e7-9e78-4bcafe2d5590.png">

##### STEPS TO REPRODUCE
```
task path: /Users/winston/git/example-aws-helloworld/ansible/roles/security-group/tasks/main.yml:4
ERROR! Unexpected Exception, this is probably a bug: u'localhost'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 292, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 292, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 586, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 497, in _process_pending_results
    self._add_group(original_host, result_item)
  File "/usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 632, in _add_group
    real_host = self._inventory.hosts[host.name]
KeyError: u'localhost'
```

##### EXPECTED RESULTS
Playbook should have continued to work after upgrading to Ansible version 2.4

##### ACTUAL RESULTS

Getting following error while creating vpc, security group, elb etc..
ERROR! Unexpected Exception, this is probably a bug: u'localhost' 

Note: We don't have any ansible.cfg or inventory folder in our repo to override any host configuration

**Comment by winstonsimon** [comment]
Looks like ansible-2.4.1.0 has the fix for above error.

**Comment by jborean93** [comment]
@winstonsimon if 2.4.1.0 has fixed this error I am going to close this issue as it is already backported and will be available once released.

**Comment by tedder** [comment]
@abadger can you reopen this? Otherwise I can create a second ticket and ref it.

**Comment by winstonsimon** [comment]
add following in the "/etc/ansible/hosts" should fix the reported issue.

[localhost]
localhost ansible_connection=local
