### ISSUE TITLE
Ansible VaultLib.encrypt error

### ISSUE THREAD

**Issue by smuthali** [ansible/ansible#31431]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
VaultLib

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.0.0
  config file = /Users/<REDACTED>/ansible.cfg
  configured module search path = [u'/Users/<REDACTED>/ansible-lib/library']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Aug  7 2017, 22:02:14) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.28.1)]

```
##### CONFIGURATION
```
ANSIBLE_SSH_CONTROL_PATH(/Users/<REDACTED>/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_PIPELINING(/Users/<REDACTED>/ansible.cfg) = False
DEFAULT_ACTION_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/Users/<REDACTED>/ansible.cfg) = ['log_plays_capture', 'mail', 'actionable', 'skippy', 'task_timer', 'version_recorder']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/filter']
DEFAULT_HASH_BEHAVIOUR(/Users/<REDACTED>/ansible.cfg) = merge
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/lookup_plugins']
DEFAULT_MODULE_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/library']
DEFAULT_REMOTE_TMP(/Users/<REDACTED>/ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_STDOUT_CALLBACK(/Users/<REDACTED>/ansible.cfg) = skippy
DEFAULT_TRANSPORT(/Users/<REDACTED>/ansible.cfg) = smart
DEPRECATION_WARNINGS(/Users/<REDACTED>/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/Users/<REDACTED>/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/<REDACTED>/ansible.cfg) = False

```

##### OS / ENVIRONMENT
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A362a

```
##### SUMMARY
I've written an Action plugin that does the following:
1. Obfuscate secrets (custom code)
2. Persist the secrets to local disk and further secure them with Ansible Vault

```
# Import directives
import os
import ast
import json
import logging
from logging import config
from ansible import constants as C
from ansible.utils.path import makedirs_safe
from ansible.parsing.vault import VaultLib
from ansible.errors import AnsibleError
from ansible.plugins.action import ActionBase
...
...
...
    def vault_operation(self, vault_file_path):
        vault = VaultLib(self.password)
        encrypted_content = vault.encrypt(ast.literal_eval(json.dumps(self.data_to_persist)))
        with open(vault_file_path, 'w') as f:
            f.write(encrypted_content)
        os.chmod(vault_file_path, 0o600)
        return dict(path=vault_file_path,
                    content=encrypted_content
                    )
```
**vault.encrypt** fails
**encrypted_content = vault.encrypt(ast.literal_eval(json.dumps(self.data_to_persist)))**
##### EXPECTED RESULTS
This works perfectly okay in Ansible 2.3.x

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "<REDACTED>/ansible24_migration/deployment-switch/ansible-lib/action_plugins/vaulter.py", line 137, in run
    return write_op.vault_operation(filepath)
  File "<REDACTED>/ansible24_migration/deployment-switch/ansible-lib/action_plugins/vaulter.py", line 93, in vault_operation
    encrypted_content = vault.encrypt(ast.literal_eval(json.dumps(self.data_to_persist)))
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 466, in encrypt
    dummy, secret = match_encrypt_secret(self.secrets)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 419, in match_encrypt_secret
    _vault_id_matchers = [_vault_id for _vault_id, dummy in secrets]
ValueError: need more than 1 value to unpack

fatal: [<REDACTED>]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by sivel** [comment]
The underlying API has changed for the use of multiple vault IDs to identify different vault passwords per file.

Your code will need to be updated to reflect these changes. As the python API is not public, there is no public documentation.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by caparisi** [comment]
If someone need, solution is provide here:

https://stackoverflow.com/questions/48293226/how-to-run-playbook-api-in-ansible-with-vault?noredirect=1&lq=1
