### ISSUE TITLE
vmware_inventory.py and vmware_inventory.ini

### ISSUE THREAD

**Issue by rewilliamso** [ansible/ansible#31549]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

dynamic Inventory 
ansible/contrib/inventory/vmware_inventory.py
ansible/contrib/inventory/vmware_inventory.ini
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]

```

##### SUMMARY

I copied the vmware_inventory.py and vmware_inventory.ini to my ansible server.  I added my vsphere servername , username and password to the vmware_inventory.ini file. Then i tried running the following command: ansible -i vmware_inventory.py -m ping from ansible server and got the following error message.

##### STEPS TO REPRODUCE

copy vmware_inventory.ini and vmware_inventory.py to ansible server. replace values in vmware_inventory.ini files and run.

```yaml

```

##### EXPECTED RESULTS

I expected the ansible server to ping all hosts running in VCenter.

##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
ERROR! Attempted to execute "vmware_inventory.py" as inventory script: Inventory script (vmware_inventory.py) had an execution error: Traceback (most recent call last):
  File "/etc/ansible/dynamic_inventory/vmware_inventory.py", line 781, in <module>
    print(VMWareInventory().show())
  File "/etc/ansible/dynamic_inventory/vmware_inventory.py", line 159, in __init__
    self.read_settings()
  File "/etc/ansible/dynamic_inventory/vmware_inventory.py", line 277, in read_settings
    config.set('vmware', k, str(v))
  File "/usr/lib64/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib64/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'vmware'

```

**Comment by Akasurde** [comment]
@rewilliamso Thanks for reporting this issue. Could you please provide content of vmware_inventory.ini ? it should look like something similar.

```
$ cat vmware_inventory.ini | grep -v "^#" | grep -v "^$"
[vmware]
server=localhost
port=443
username=user
password=pass
validate_certs = False
```

Seeing at error, I suspect that `[vmware]` line is commented or missing.

**Comment by rewilliamso** [comment]
[vmware]
server=vcenter.example.com
port=443
username=ansibleo
password=password123

**Comment by rewilliamso** [comment]
The vmware_inventory.ini is in the path /etc/ansible/vmware_inventory.ini .
The vmware_inventory.py is located /etc/ansible/dynamic/vmware_inventory.py .

Not sure if you needed that info but thought I would provide it.

**Comment by Akasurde** [comment]
@rewilliamso Yes, the path will affect vmware_inventory.py. The script will look ini file in the current directory as the script. I will recommend to keep vmware_inventory.ini in same location as inventory script.

**Comment by rewilliamso** [comment]
I will try that, one sec.

**Comment by rewilliamso** [comment]
Is there a readme on how to use this script specifically? If i wanted to select a host inside of a specific VCenter folder.

**Comment by rewilliamso** [comment]
I am ran the following command and it seems like its hanging:

[root@anssvr101 ansible]# ansible tpmtst147.tpms -i vmware_inventory.py -m ping -vvv
Using /etc/ansible/ansible.cfg as config file

**Comment by Akasurde** [comment]
There is no README as such, but you can go through vmware_inventory.ini file. This file is well commented. 

I am not sure about the reason on hang state, but you can debug that using 

```./vmware_inventory.py --list --debug```

**Comment by rewilliamso** [comment]
I guess its working but is gathering facts, would you agree?

[root@anssvr101 ansible]# ./vmware_inventory.py --list --debug
2017-10-12 11:48:22.149596 cache path is /root/.ansible/tmp/ansible-vmware.cache
2017-10-12 11:48:22.149669 server is vcloud.scriptpro.com
2017-10-12 11:48:22.149697 username is rewilliamso@scriptpro.com
2017-10-12 11:48:22.149718 cert validation is False
2017-10-12 11:48:22.149733 max object level is 1
2017-10-12 11:48:22.149750 lower keys is True
2017-10-12 11:48:22.149772 skip keys is ['declaredalarmstate', 'disabledmethod', 'dynamicproperty', 'dynamictype', 'environmentbrowser', 'managedby', 'parent', 'childtype', 'resourceconfig']
2017-10-12 11:48:22.149791 host filters are ['{{ guest.gueststate == "running" }}']
2017-10-12 11:48:22.149808 groupby patterns are ['{{ guest.guestid }}', '{{ "templates" if config.template else "guests"}}']
2017-10-12 11:48:22.803633 retrieving all instances
2017-10-12 11:48:22.844220 creating containerview for virtualmachines
2017-10-12 11:48:23.045756 381 total instances in container view
2017-10-12 11:48:23.325098 get facts for servera
2017-10-12 11:48:28.493893 get facts for serverb
2017-10-12 11:48:32.557195 get facts for serverc
2017-10-12 11:48:36.656610 get facts for serverd
2017-10-12 11:48:40.320275 get facts for servere

**Comment by rewilliamso** [comment]
Everything is working as expected but I was hoping you could answer a few questions.

We have over 500 servers in our cloud environment so every time I run a dynamic inventory command it tries to cache 500 records. 

1. How can I cache this data to live on the server?
   I've already tried turning Cache on within the vmware_inventory.ini file but seems that only last for so 
    long.
2. How can I select a specific Data Center or Folder inside of VCenter?

Any help would be much appreciated.

Thanks,
