### ISSUE TITLE
multiple failures pip upgading OS X Ansible 2.3.1 > 2.4

### ISSUE THREAD

**Issue by t-readyroc** [ansible/ansible#31582]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Install/Upgrade
##### ANSIBLE VERSION

```
| => ansible --version
ansible 2.3.1.0
  config file = /Users/travis/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 20 2017, 12:51:48) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT

OS X Sierra 10.12.6
##### SUMMARY

Upgrade failed on several steps, resulting in stalled upgrade.
##### STEPS TO REPRODUCE

pip install ansible --upgrade

##### EXPECTED RESULTS

Upgrade Ansible
##### ACTUAL RESULTS

The first attempt resulted in the following ouput
```
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jt/rypccdt93sb33l699g2sfxg00000gn/T/pip-build-MfFaxD/xattr/
```

With the accompanying error of:

```
 Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
```

Something that you might want to mention in the Porting Guide. So I then ran that command, and ran the upgrade command again. This time, I got:

```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jt/rypccdt93sb33l699g2sfxg00000gn/T/pip-build-kQd3Rf/MarkupSafe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/jt/rypccdt93sb33l699g2sfxg00000gn/T/pip-oSgTN3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jt/rypccdt93sb33l699g2sfxg00000gn/T/pip-build-kQd3Rf/MarkupSafe/
```

With the accompanying error:

```
error: could not create '/Library/Python/2.7/site-packages/markupsafe': Permission denied
```

So, for giggles, I ran the upgrade command under sudo, and got the following:

```
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-CWjo_p-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

At that point, I gave up for the time being.

**Comment by sivel** [comment]
Your problem is the result of attempting to make modifications to files that exist in a protected part of the filesystem due to System Integrity Protection.  You may have to research how to disable SIP, remove the offending packages, re-enabled SIP, and then try to perform the install again.  Likely some packages were installed in those locations before an upgrade that enabled SIP, and now they are protected from modification.

As for the other errors, as ansible has some dependencies on C compiled extensions, Xcode must be available and it's license accepted before you can compile C code.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by t-readyroc** [comment]
OK. Thanks for the response.
