### ISSUE TITLE
Template lookup plugin traceback

### ISSUE THREAD

**Issue by lalinsky** [ansible/ansible#3165]
It seems that the `{{ lookup('template', 'test.j2') }}` does not work in the devel branch; it fails with a Python exception.

With a playbook like this:

```
- hosts: localhost
  tasks:
    - action: debug msg="{{ lookup('template', 'test.j2') }}"
```

I get this exception:

```
Traceback (most recent call last):
  File "/home/lukas/code/ansible/bin/ansible-playbook", line 241, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/lukas/code/ansible/bin/ansible-playbook", line 187, in main
    pb.run()
  File "/home/lukas/code/ansible/lib/ansible/playbook/__init__.py", line 244, in run
    if not self._run_play(play):
  File "/home/lukas/code/ansible/lib/ansible/playbook/__init__.py", line 536, in _run_play
    if not self._run_task(play, task, False):
  File "/home/lukas/code/ansible/lib/ansible/playbook/__init__.py", line 327, in _run_task
    self.callbacks.on_task_start(template(play.basedir, task.name, task.module_vars, lookup_fatal=False), is_handler)
  File "/home/lukas/code/ansible/lib/ansible/utils/template.py", line 308, in template
    varname = template_from_string(basedir, varname, vars)
  File "/home/lukas/code/ansible/lib/ansible/utils/template.py", line 496, in template_from_string
    res = jinja2.utils.concat(t.root_render_func(t.new_context(_jinja2_vars(basedir, vars, t.globals), shared=True)))
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 180, in call
    return __obj(*args, **kwargs)
  File "/home/lukas/code/ansible/lib/ansible/utils/template.py", line 492, in my_lookup
    return lookup(*args, basedir=basedir, **kwargs)
  File "/home/lukas/code/ansible/lib/ansible/utils/template.py", line 86, in lookup
    ran = instance.run(*args, inject=vars, **kwargs)
  File "/home/lukas/code/ansible/lib/ansible/runner/lookup_plugins/template.py", line 32, in run
    ret.append(template.template_from_file(self.basedir, term, inject))
  File "/home/lukas/code/ansible/lib/ansible/utils/template.py", line 432, in template_from_file
    vars = vars.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by mpdehaan** [comment]
I'll take a look.

**Comment by mpdehaan** [comment]
Fix pushed just now, thanks!
