### ISSUE TITLE
Can't use Ansible ios_ core modules to manage Cisco IOS version 15 using  ssh keys.

### ISSUE THREAD

**Issue by bukaj-mh** [ansible/ansible#31699]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/troolix/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

linux, managing Cisco IOS v15

##### SUMMARY
Ansible is not able login to cisco switch using rsa ssh key. The older issue wtih ssh keys was closed
due inactivity, so opening new. Belive there is more people managing Cisco IOS switches
who would like to use ansbile.

ansible debug:

```
2017-10-13 15:01:00,387 paramiko.transport Trying SSH agent key "*****some key here *****"
2017-10-13 15:01:00,633 paramiko.transport userauth is OK
2017-10-13 15:01:00,693 paramiko.transport Exception: Illegal info request from server
2017-10-13 15:01:00,694 paramiko.transport Traceback (most recent call last):
2017-10-13 15:01:00,694 paramiko.transport   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1906, in run
2017-10-13 15:01:00,694 paramiko.transport     handler(self.auth_handler, m)
2017-10-13 15:01:00,695 paramiko.transport   File "/usr/local/lib/python2.7/dist-packages/paramiko/auth_handler.py", line 613, in _parse_use
rauth_info_request
2017-10-13 15:01:00,695 paramiko.transport     raise SSHException('Illegal info request from server')
```
cisco ios ssh debug:
```
Oct 13 13:01:00.715: SSH2 1: Authenticating 'user1' with method: publickey
Oct 13 13:01:00.732: SSH2 1: SSH ERROR closing the connection
```

##### STEPS TO REPRODUCE

When running my playbook with login/password authentication then playbook works.
Ssh login itself using rsa key works. Ansible using rsa key does not work.

```
---
- hosts:  mng-key-login
  connection: local
  gather_facts: no

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: user1

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show interfaces
        provider: "{{ cli }}"
      register: output

    - debug: var=output
```

##### ACTUAL RESULTS

```

```

**Comment by gundalow** [comment]
Do you have anything in your `~/.ssh/config`?

Could you please enable logging as detailed in http://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html#enabling-networking-logging-and-how-to-read-the-logfile and provide that full log

needs_info

**Comment by bukaj-mh** [comment]
I don't have ~/.ssh/config file.
full log: [ansible.log](https://github.com/ansible/ansible/files/1413473/ansible.log)

Regards

**Comment by gundalow** [comment]
Relevant section from log
```
2017-10-25 08:25:03,745 p=10683 u=user1 |   10683 1508912703.74528: Loaded config def from plugin (connection/ssh)
2017-10-25 08:25:03,751 p=10683 u=user1 |  creating new control socket for host mng-kit-1.mszn:22 as user user1
2017-10-25 08:25:03,752 p=10683 u=user1 |  control socket path is /home/user1/.ansible/pc/928798e4ed
2017-10-25 08:25:03,752 p=10683 u=user1 |  current working directory is /home/user1/work/ansible
2017-10-25 08:25:03,752 p=10683 u=user1 |  using connection plugin network_cli
 10689 1508912703.81111: Loading Connection 'network_cli' from /usr/lib/python2.7/dist-packages/ansible/plugins/connection/network_cli.py
2017-10-25 08:25:03,811 p=10683 u=user1 |   10689 1508912703.81111: Loading Connection 'network_cli' from /usr/lib/python2.7/dist-packages/ansible/plugins/connection/network_cli.py
 10689 1508912703.81233: Loading ShellModule 'csh' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/csh.py
2017-10-25 08:25:03,812 p=10683 u=user1 |   10689 1508912703.81233: Loading ShellModule 'csh' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/csh.py
 10689 1508912703.81277: Loading ShellModule 'fish' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/fish.py
2017-10-25 08:25:03,812 p=10683 u=user1 |   10689 1508912703.81277: Loading ShellModule 'fish' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/fish.py
 10689 1508912703.81347: Loading ShellModule 'powershell' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/powershell.py
2017-10-25 08:25:03,813 p=10683 u=user1 |   10689 1508912703.81347: Loading ShellModule 'powershell' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/powershell.py
 10689 1508912703.81364: Loading ShellModule 'sh' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/sh.py
2017-10-25 08:25:03,813 p=10683 u=user1 |   10689 1508912703.81364: Loading ShellModule 'sh' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/sh.py
 10689 1508912703.81394: Loading ShellModule 'sh' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2017-10-25 08:25:03,813 p=10683 u=user1 |   10689 1508912703.81394: Loading ShellModule 'sh' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 10689 1508912703.81902: assigned :doc
2017-10-25 08:25:03,819 p=10683 u=user1 |   10689 1508912703.81902: assigned :doc
 10689 1508912703.81957: Loaded config def from plugin (connection/network_cli)
2017-10-25 08:25:03,819 p=10683 u=user1 |   10689 1508912703.81957: Loaded config def from plugin (connection/network_cli)
2017-10-25 08:25:05,857 paramiko.transport starting thread (client mode): 0xe2ad6d50L
2017-10-25 08:25:05,857 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.3.1
2017-10-25 08:25:05,858 paramiko.transport Remote version/idstring: SSH-2.0-Cisco-1.25
2017-10-25 08:25:05,858 paramiko.transport Connected (version 2.0, client Cisco-1.25)
2017-10-25 08:25:05,870 paramiko.transport kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2017-10-25 08:25:05,870 paramiko.transport Kex agreed: diffie-hellman-group-exchange-sha1
2017-10-25 08:25:05,870 paramiko.transport HostKey agreed: ssh-rsa
2017-10-25 08:25:05,871 paramiko.transport Cipher agreed: aes128-cbc
2017-10-25 08:25:05,871 paramiko.transport MAC agreed: hmac-sha1
2017-10-25 08:25:05,871 paramiko.transport Compression agreed: none
2017-10-25 08:25:06,069 paramiko.transport Got server p (2048 bits)
2017-10-25 08:25:12,507 paramiko.transport kex engine KexGex specified hash_algo <built-in function openssl_sha1>
2017-10-25 08:25:12,507 paramiko.transport Switch to new keys ...
2017-10-25 08:25:12,511 paramiko.transport Trying SSH agent key 2dbc8ecaaab4c2a188af5eec1a0b7762
2017-10-25 08:25:12,716 paramiko.transport userauth is OK
2017-10-25 08:25:12,762 paramiko.transport Exception: Illegal info request from server
2017-10-25 08:25:12,763 paramiko.transport Traceback (most recent call last):
2017-10-25 08:25:12,763 paramiko.transport   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1906, in run
2017-10-25 08:25:12,763 paramiko.transport     handler(self.auth_handler, m)
2017-10-25 08:25:12,763 paramiko.transport   File "/usr/local/lib/python2.7/dist-packages/paramiko/auth_handler.py", line 613, in _parse_userauth_info_request
2017-10-25 08:25:12,763 paramiko.transport     raise SSHException('Illegal info request from server')
2017-10-25 08:25:12,763 paramiko.transport SSHException: Illegal info request from server
2017-10-25 08:25:12,763 paramiko.transport 
2017-10-25 08:25:12,775 paramiko.transport Trying SSH agent key 2dbc8ecaaab4c2a188af5eec1a0b7762
2017-10-25 08:25:12,776 paramiko.transport Trying discovered key 2dbc8ecaaab4c2a188af5eec1a0b7762 in /home/user1/.ssh/id_rsa
2017-10-25 08:25:12,777 paramiko.transport Trying discovered key 5095c40000cba086050688450ae188c5 in /home/user1/.ssh/id_ed25519
2017-10-25 08:25:12,777 p=10683 u=user1 |  connecting to host mng-kit-1.mszn returned an error
2017-10-25 08:25:12,777 p=10683 u=user1 |  No existing session
```

**Comment by bukaj-mh** [comment]
hi, any update ?

**Comment by gundalow** [comment]
@bukaj-mh Could you please test this again on the `devel` branch, a lot of changes have gone in since this bug was raised. Please include the updated logs as well.

**Comment by WRJFontenot** [comment]
ANSIBLE VERSION

[ansible@localhost ~]$ ansible --version
  2908 1516312537.38636: starting run
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]


OS / ENVIRONMENT

Ansible Server: CentOS Linux release 7.4.1708 (Core)

Cisco Switch: WS-C3750X-24P-L
Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.0(2)SE11, RELEASE SOFTWARE (fc3)


SUMMARY

I am having the exact same problem when using the Ansible ios modules to manage a Cisco switch.  The ansible command works if I use the -k parameter and provide the Cisco user password. The command fails try to use the SSH key.

The debug output below is from this command:

[ansible@localhost ~]$ ansible all -m ios_facts -c local -vvvv

192.168.1.30 | FAILED! => {
    "changed": false,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}


ansible debug log:

2018-01-18 15:49:00,380 paramiko.transport starting thread (client mode): 0x23d1350L
2018-01-18 15:49:00,380 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.1.1
2018-01-18 15:49:00,382 paramiko.transport Remote version/idstring: SSH-1.99-Cisco-1.25
2018-01-18 15:49:00,382 paramiko.transport Connected (version 1.99, client Cisco-1.25)
2018-01-18 15:49:00,385 paramiko.transport kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2018-01-18 15:49:00,385 paramiko.transport Kex agreed: diffie-hellman-group1-sha1
2018-01-18 15:49:00,385 paramiko.transport Cipher agreed: aes128-cbc
2018-01-18 15:49:00,385 paramiko.transport MAC agreed: hmac-md5
2018-01-18 15:49:00,385 paramiko.transport Compression agreed: none
2018-01-18 15:49:01,460 paramiko.transport kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
2018-01-18 15:49:01,461 paramiko.transport Switch to new keys ...
2018-01-18 15:49:01,483 paramiko.transport Trying discovered key 9c2dd3edc1bd4f31edcdca04242f6c2d in /home/ansible/.ssh/id_rsa
2018-01-18 15:49:01,669 paramiko.transport userauth is OK
2018-01-18 15:49:01,677 paramiko.transport Exception: Illegal info request from server
2018-01-18 15:49:01,678 paramiko.transport Traceback (most recent call last):
2018-01-18 15:49:01,678 paramiko.transport   File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1795, in run
2018-01-18 15:49:01,678 paramiko.transport     self.auth_handler._handler_table[ptype](self.auth_handler, m)
2018-01-18 15:49:01,678 paramiko.transport   File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 575, in _parse_userauth_info_request
2018-01-18 15:49:01,678 paramiko.transport     raise SSHException('Illegal info request from server')
2018-01-18 15:49:01,678 paramiko.transport SSHException: Illegal info request from server
2018-01-18 15:49:01,678 paramiko.transport


Cisco debug ip ssh:

Jan 18 21:49:00.353: SSH0: starting SSH control process
Jan 18 21:49:00.353: SSH0: sent protocol version id SSH-1.99-Cisco-1.25
Jan 18 21:49:00.353: SSH0: protocol version id is - SSH-2.0-paramiko_2.1.1
Jan 18 21:49:00.353: SSH2 0: send:packet of  length 344 (length also includes padlen of 5)
Jan 18 21:49:00.353: SSH2 0: SSH2_MSG_KEXINIT sent
Jan 18 21:49:00.361: SSH2 0: ssh_receive: 640 bytes received
Jan 18 21:49:00.361: SSH2 0: input: total packet length of 640 bytes
Jan 18 21:49:00.361: SSH2
office#0: partial packet length(block size)8 bytes,needed 632 bytes,
               maclen 0
Jan 18 21:49:00.361: SSH2 0: input: padlength 4 bytes
Jan 18 21:49:00.361: SSH2 0: SSH2_MSG_KEXINIT received
Jan 18 21:49:00.361: SSH2 0: kex: client->server enc:aes128-cbc mac:hmac-md5
Jan 18 21:49:00.361: SSH2 0: kex: server->client enc:aes128-cbc mac:hmac-md5
Jan 18 21:49:00.361: SSH2 0: Using kex_algo = diffie-hellman-group1-sha1
Jan 18 21:49:00.395: SSH2 0: expecting SSH2_MSG_KEXDH_INIT
Jan 18 21:49:00.562:
office# SSH2 0: ssh_receive: 144 bytes received
Jan 18 21:49:00.562: SSH2 0: input: total packet length of 144 bytes
Jan 18 21:49:00.562: SSH2 0: partial packet length(block size)8 bytes,needed 136 bytes,
               maclen 0
Jan 18 21:49:00.562: SSH2 0: input: padlength 5 bytes
Jan 18 21:49:00.562: SSH2 0: SSH2_MSG_KEXDH_INIT received
Jan 18 21:49:01.426: SSH2 0: signature length 271
Jan 18 21:49:01.426: SSH2 0: send:packet of  length 704 (length also includes padlen of 7)
Jan 18 21:49:01.426: SSH2:
office#kex_derive_keys complete
Jan 18 21:49:01.426: SSH2 0: send:packet of  length 16 (length also includes padlen of 10)
Jan 18 21:49:01.426: SSH2 0: newkeys: mode 1
Jan 18 21:49:01.426: SSH2 0: SSH2_MSG_NEWKEYS sent
Jan 18 21:49:01.426: SSH2 0: waiting for SSH2_MSG_NEWKEYS
Jan 18 21:49:01.435: SSH2 0: ssh_receive: 16 bytes received
Jan 18 21:49:01.435: SSH2 0: input: total packet length of 16 bytes
Jan 18 21:49:01.435: SSH2 0: partial packet length(block size)8 bytes,needed 8 bytes,
               mac
office#len 0
Jan 18 21:49:01.435: SSH2 0: input: padlength 10 bytes
Jan 18 21:49:01.435: SSH2 0: newkeys: mode 0
Jan 18 21:49:01.435: SSH2 0: SSH2_MSG_NEWKEYS received
Jan 18 21:49:01.636: SSH2 0: ssh_receive: 48 bytes received
Jan 18 21:49:01.636: SSH2 0: input: total packet length of 32 bytes
Jan 18 21:49:01.636: SSH2 0: partial packet length(block size)16 bytes,needed 16 bytes,
               maclen 16
Jan 18 21:49:01.636: SSH2 0: MAC compared for #3 :ok
Jan 18 21:49:01.636: SSH2 0: input: padlength
office#10 bytes
Jan 18 21:49:01.636: SSH2 0: send:packet of  length 32 (length also includes padlen of 10)
Jan 18 21:49:01.636: SSH2 0: computed MAC for sequence no.#3 type 6
Jan 18 21:49:01.644: SSH2 0: ssh_receive: 640 bytes received
Jan 18 21:49:01.644: SSH2 0: input: total packet length of 624 bytes
Jan 18 21:49:01.644: SSH2 0: partial packet length(block size)16 bytes,needed 608 bytes,
               maclen 16
Jan 18 21:49:01.644: SSH2 0: MAC compared for #4 :ok
Jan 18 21:49:01.644: SSH2 0: input: p
office#adlength 6 bytes
Jan 18 21:49:01.644: SSH2 0: Using method = publickey
Jan 18 21:49:01.644: SSH2 0: send:packet of  length 304 (length also includes padlen of 4)
Jan 18 21:49:01.644: SSH2 0: computed MAC for sequence no.#4 type 60
Jan 18 21:49:01.644: SSH2 0: Authenticating 'ansible' with method: publickey
Jan 18 21:49:01.653: SSH2 0: SSH ERROR closing the connection
Jan 18 21:49:01.653: SSH2 0: send:packet of  length 80 (length also includes padlen of 15)
Jan 18 21:49:01.653: SSH2 0: computed MAC f
office#or sequence no.#5 type 1
Jan 18 21:49:01.653: SSH2 0: Pubkey Authentication failed for user ansible
Jan 18 21:49:01.653: SSH0: password authentication failed for ansible
Jan 18 21:49:03.658: SSH2 0: send:packet of  length 64 (length also includes padlen of 14)
Jan 18 21:49:03.658: SSH2 0: computed MAC for sequence no.#6 type 51
Jan 18 21:49:03.658: SSH2 0: authentication failed for userid (code=0)
Jan 18 21:49:03.758: SSH0: Session disconnected - error 0x00

**Comment by bukaj-mh** [comment]
Hi,
today I upgraded ansible, did test again:

ansible@net-ansible:~/ansible-test$ ansible --version
 25025 1522326090.04316: starting run
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

Cisco switch WS-C2960-24TT-L  IOS version 15.0(2)SE6


from ansbile.log:

2018-03-29 14:19:36,027 paramiko.transport starting thread (client mode): 0x5b31e310L
2018-03-29 14:19:36,027 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.4.1
2018-03-29 14:19:36,027 paramiko.transport Remote version/idstring: SSH-2.0-Cisco-1.25
2018-03-29 14:19:36,027 paramiko.transport Connected (version 2.0, client Cisco-1.25)
2018-03-29 14:19:36,031 paramiko.transport kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-s
ha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc',
 u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'h
mac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] clie
nt compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2018-03-29 14:19:36,031 paramiko.transport Kex agreed: diffie-hellman-group-exchange-sha1
2018-03-29 14:19:36,031 paramiko.transport HostKey agreed: ssh-rsa
2018-03-29 14:19:36,031 paramiko.transport Cipher agreed: aes128-cbc
2018-03-29 14:19:36,032 paramiko.transport MAC agreed: hmac-sha1
2018-03-29 14:19:36,032 paramiko.transport Compression agreed: none
2018-03-29 14:19:36,237 paramiko.transport Got server p (2048 bits)
2018-03-29 14:19:37,388 paramiko.transport kex engine KexGex specified hash_algo <built-in function openssl_sha1>
2018-03-29 14:19:37,389 paramiko.transport Switch to new keys ...
2018-03-29 14:19:37,420 paramiko.transport Trying discovered key b1242abf2ed870c930ee4b6b8b702f19 in /home/ansible/.ssh
/id_rsa
2018-03-29 14:19:37,587 paramiko.transport userauth is OK
2018-03-29 14:19:37,593 paramiko.transport Exception: Illegal info request from server
2018-03-29 14:19:37,594 paramiko.transport Traceback (most recent call last):
2018-03-29 14:19:37,594 paramiko.transport   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1949, in run
2018-03-29 14:19:37,594 paramiko.transport     handler(self.auth_handler, m)
2018-03-29 14:19:37,594 paramiko.transport   File "/usr/local/lib/python2.7/dist-packages/paramiko/auth_handler.py", line 622, in _parse_userauth_info_request
2018-03-29 14:19:37,594 paramiko.transport     raise SSHException('Illegal info request from server')
2018-03-29 14:19:37,594 paramiko.transport SSHException: Illegal info request from server
2018-03-29 14:19:37,594 paramiko.transport 
2018-03-29 14:19:37,622 p=24978 u=ansible |  shutdown complete
2018-03-29 14:19:37,656 p=24968 u=ansible |   24977 1522325977.65612: done running TaskExecutor() for mng1-lab.ko.seznam.cz/TASK: run multiple commands on remote nodes [e259e068-e286-8e22-11a7-00000000004e]

**Comment by rcarrillocruz** [comment]
Hi there

I'm afraid I'm unable to reproduce, I can connect to an IOS device on our lab just fine:

```
[ricky@ricky-laptop ~]$ ansible all -i /tmp/ios_inventory -m ios_facts                         
ios | SUCCESS => {                             
    "ansible_facts": {                                                 
        "ansible_net_all_ipv4_addresses": [    
            "172.31.0.25",                                                                     
            "10.8.38.65",                                                                      
            "192.168.255.2"           
```

Here's how it looks like my inventory (as you can see, no password set, so I use SSH agent):

```
ios ansible_host=10.8.38.65 ansible_user=ansible ansible_connection=network_cli ansible_network_os=ios
```

And here's my ssh pubkey settings on the IOS device (from a 'sh run'):

```
ip ssh pubkey-chain                            
  username ansible                             
   key-hash ssh-rsa 23C70B25FA2899AB2B77CC5719DDE5CA
...
...
ip ssh server algorithm authentication publickey password
```

**Comment by rcarrillocruz** [comment]
needs_info

**Comment by bukaj-mh** [comment]
Hi,
what is your IOS device ?
according to command "ip ssh server algorithm authentication publickey password" .. Cisco IOS 15.5(2)S This command was introduced., I'm running 15.0(2)SE5
unfortunatelly there is no IOS 15.5 version for Cisco 2960, so I can't try it :(

**Comment by mmihir82** [comment]
Following works:
sudo ansible -i inventories testsw -m ios_facts -c local  -u testuser -k

But when running thru playbook it does:
- name: IOS-FACTS
  ios_facts:
    gather_subset: all
  register: output

ERROR:
```
fatal: [testsw]: FAILED! => {
    "msg": "No existing session"
}
```

**Comment by lindenaar** [comment]
I am having the same issue with ansible 2.5.2, though only with one of my Cisco routers. The key difference seems to be  the IOS version, production routers running IOS 15.5 have no problems but for a test router still on IOS 15.1 Ansible fails to connect with the same messages in the log as above (```Exception: Illegal info request from server```)

To connect to this router we need to specify the Cipher to be used specifically with ```ssh -c aes256-cbc``` otherwise it won't connect. Strange enough I see in the logs above (and also on my system) that paramiko agrees on a Cipher of aes128-cbc (which does work as well, no issues to connect using ```ssh -c aes128-cbc``` and it confirms this is the cipher used)

Hope this helps to track down the issue, let me know in case I need to test anything or provide more info (looks like an issue in Paramiko?). Anyway the issue looks related to the IOS version to me.

Please note that I do get a different error message / result:
```
SUDO password:
niva | FAILED! => {
    "msg": "ssh None@niva:22 : Private key file is encrypted\nTo connect as a different user, use -u <username>."
}
```
Specifying my userid with -u on the command line only changes the ```None``` above into my username but with the same end result.

**Comment by rcarrillocruz** [comment]
This looks like a paramiko issue affecting some (not all) Cisco devices.

https://github.com/paramiko/paramiko/issues/122

Can you please check the paramiko snippet of code on above URL and see if you get the same 'Illegal info request from server' ?
Since the trace comes from Paramiko and we rely on it for connecting to devices, I recommend you try opening an issue on the paramiko project.

**Comment by lindenaar** [comment]
I can indeed reproduce the problem with a simple python script using paramiko directly, will follow-up with that project. Thanks!

For those that need a connection now: try using a password (ansible/ansible-playbook option -k). Not very scalable but so far that seems to work fine.

**Comment by ktbyers** [comment]
Note, that issue referenced is from 2012 which likely predates some of the reported operating systems (IOS 15.5). 

Also Paramiko not working with the given device does not necessarily tell you where the problem is. 

In other words, the problem could be with Cisco IOS or with Paramiko or a combination of both of them (as you are having an interaction problem between the two items).
