### ISSUE TITLE
rhn_register module fails on RHEL5 hosts

### ISSUE THREAD

**Issue by E-M** [ansible/ansible#3192]
rhn_register module fails on all RHEL5 hosts with:

```
HostA | FAILED => failed to parse:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-1371109421.04-39163328736735/rhn_register", line 1264, in ?
    main()
  File "/home/admin/.ansible/tmp/ansible-1371109421.04-39163328736735/rhn_register", line 349, in main
    rhn.register(module.params['enable_eus'] == True, activationkey)
  File "/home/admin/.ansible/tmp/ansible-1371109421.04-39163328736735/rhn_register", line 263, in register
    run_command(register_cmd)
  File "/home/admin/.ansible/tmp/ansible-1371109421.04-39163328736735/rhn_register", line 101, in run_command
    stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.4/subprocess.py", line 550, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.4/subprocess.py", line 996, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I guess this is because RHEL5 needs full path to rhnreg_ks binary.

**Comment by mpdehaan** [comment]
fixed on Ansible 1.3 branch
