### ISSUE TITLE
Possible refactor error "import ansible.inventory_script"

### ISSUE THREAD

**Issue by bradobro** [ansible/ansible#321]
Looks like some of the current refactoring around inventory parsing broke imports in inventory line 27, which tries to import a non-existent module:

(commit 46c661b3e3b037c39cb1954b4e706fd9af86e8d8)

Traceback (most recent call last):
  File "/home/brado/wc/ansible_mbl/ansible/bin/ansible", line 25, in <module>
    from ansible.runner import Runner
  File "/home/brado/wc/ansible_mbl/ansible/lib/ansible/runner.py", line 35, in <module>
    import ansible.inventory
  File "/home/brado/wc/ansible_mbl/ansible/lib/ansible/inventory.py", line 27, in <module>
    from ansible.inventory_script import InventoryScript
ImportError: No module named inventory_script

**Comment by mpdehaan** [comment]
_kicks self_ 

Forgot to check that file in, pushed now, thanks!
