### ISSUE TITLE
Intermittent Unexpected Exception loading inventory file

### ISSUE THREAD

**Issue by 0mmariano** [ansible/ansible#32193]
##### ISSUE TYPE
 Bug Report

##### COMPONENT NAME
ansible-playbook
_load_inventory_file

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/local/ansible/modules/community']
```

##### CONFIGURATION
defined values under [default]
roles_path = /usr/local/ansible/roles/community

##### OS / ENVIRONMENT
OS: Jessie

##### SUMMARY
Intermittent Unexpected Exception error in loading inventory file
Was unable to use a previously working/usable hosts file so I copied it to a different location (exact ownership/permissions as the original). The playbook run worked using this copy. After some time, running the same playbook/command and using both the original and the hosts file copy fail.

##### STEPS TO REPRODUCE
Inventory file that has been working = MYDIR/inventories/hosts
group_vars file used = MYDIR/inventories/group_vars/app1_server
ansible command = ansible-playbook deploy.yml -i MYDIR/inventories/hosts -e target=app1_server (and a bunch of other extra variables)

I have been able to use the above playbook, hosts file and group_vars file in the past to deploy changes to app1_server. However, two days ago, I got the error below when I ran it --
```
Using /etc/ansible/ansible.cfg as config file
ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 98, in __init__
    self.parse_inventory(host_list)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 165, in parse_inventory
    group.vars = combine_vars(group.vars, self.get_group_variables(group.name))
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 555, in get_group_variables
    self._vars_per_group[groupname] = self._get_group_variables(groupname, vault_password=vault_password)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 573, in _get_group_variables
    vars = combine_vars(vars, self.get_group_vars(group))
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 775, in get_group_vars
    return self._get_hostgroup_vars(host=None, group=group, new_pb_basedir=new_pb_basedir, return_results=return_results)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 839, in _get_hostgroup_vars
    host_results = self._variable_manager.add_group_vars_file(base_path, self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 619, in add_group_vars_file
    data = self._load_inventory_file(path, loader)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 577, in _load_inventory_file
    rval.update(data)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

I placed copies of hosts and group_vars/app1_server somewhere else as a test. The command below was successful (same as before but used the new copies)
```
ansible-playbook deploy.yml -i ANOTHERDIR/inventories/hosts -e target=app1_server (and a bunch of other extra variables)
```

Today, that is no longer working. At first I thought it was permission errors on the files so I created copies of hosts and app1_server in another filesystem but it still returned the exception. I ran my test playbook (testPlay.yml) which just writes a file in my home directory on the target server and doesn't use any group_vars
```
ansible-playbook testPlay.yml -i MYDIR/inventories/hosts -e target=app1_server
```

It was successful and a file was written in my home directory on the target server
About 30 mins later, I ran the same command for testPlay.yml again and got the above Unexpected Exception error

##### EXPECTED RESULTS
Playbook, hosts and app1_server files have not been changed since last successful run so the run should have been successful

##### ACTUAL RESULTS
Note that there were only a few minutes between the successful run and the failed run below for the same command

Successful run
```
PLAYBOOK RUN: ansible-playbook testPlay.yml -i MYDIR/hosts -e target=app1_server -vvv

2017-10-26 20:12:35,370  |  Using /etc/ansible/ansible.cfg as config file
2017-10-26 20:12:43,279  |  PLAYBOOK: testPlay.yml *********************************************************
2017-10-26 20:12:43,279  |  1 plays in testPlay.yml
2017-10-26 20:12:51,246  |  PLAY [cras_appserver] **********************************************************
2017-10-26 20:12:51,285  |  TASK [setup] *******************************************************************
2017-10-26 20:12:51,681  |  Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
2017-10-26 20:12:57,286  |  ok: [hostname]
2017-10-26 20:12:57,292  |  TASK [Say hello on target server] **********************************************
2017-10-26 20:12:57,292  |  task path: /usr/local/ansible/playbooks/testPlay.yml:18
2017-10-26 20:12:57,438  |  Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/file.py
2017-10-26 20:12:57,593  |  changed: [hostname] => {

more logs

2017-10-26 20:12:57,596  |  PLAY RECAP *********************************************************************
2017-10-26 20:12:57,597  |  hostname      : ok=2    changed=1    unreachable=0    failed=0

```
Failed run
```
PLAYBOOK RUN: ansible-playbook testPlay.yml -i MYDIR/hosts -e target=app1_server -vvv

2017-10-26 20:26:44,803  |  Using /etc/ansible/ansible.cfg as config file
2017-10-26 20:26:49,461  |  ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
2017-10-26 20:26:49,463  |  the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 98, in __init__
    self.parse_inventory(host_list)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 165, in parse_inventory
    group.vars = combine_vars(group.vars, self.get_group_variables(group.name))
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 555, in get_group_variables
    self._vars_per_group[groupname] = self._get_group_variables(groupname, vault_password=vault_password)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 573, in _get_group_variables
    vars = combine_vars(vars, self.get_group_vars(group))
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 775, in get_group_vars
    return self._get_hostgroup_vars(host=None, group=group, new_pb_basedir=new_pb_basedir, return_results=return_results)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 839, in _get_hostgroup_vars
    host_results = self._variable_manager.add_group_vars_file(base_path, self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 619, in add_group_vars_file
    data = self._load_inventory_file(path, loader)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 577, in _load_inventory_file
    rval.update(data)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by nitzmahone** [comment]
Are you able to reproduce this on a supported version of Ansible? With the release of 2.4, 2.2 is now in "security fixes only" mode, and large portions of the inventory code have been rewritten in 2.4.

**Comment by 0mmariano** [comment]
@nitzmahone I'll try that and let you know how it goes.
I have 3 Ansible servers that are identical and this error is manifesting on just two so its really inconsistent.

**Comment by 0mmariano** [comment]
@nitzmahone - I am on Debian Jessie and the only packaged version for it is Ansible 2.2. There is a 2.4 package for Buster but I cannot use it at this time. Is there something else we can look at if updating to 2.4 is not an option?

**Comment by sivel** [comment]
This issue appears to no longer happen on recent versions of ansible (2.5+). If you are still having problems with ansible 2.5+, please feel free to open a new issue with a full reproducer.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
