### ISSUE TITLE
ssh permission denied confusing

### ISSUE THREAD

**Issue by nixmomo** [ansible/ansible#32271]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ssh connection

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LIBVIRT_LXC_NOSECLABEL(/etc/ansible/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /var/lib/rundeck/var/tmp/ansible-l
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 120

##### OS / ENVIRONMENT
Linux deploy 4.13.4-1-pve #1 SMP PVE 4.13.4-25 (Fri, 13 Oct 2017 08:59:53 +0200) x86_64 GNU/Linux
 Debian Stretch

##### SUMMARY
i have 2 hosts in one group in inventory
[test]
10.8.0.11 ansible_user=root
10.8.0.12 ansible_user=root

##### STEPS TO REPRODUCE
setup group with more as one IP and do ansible -m ping group

##### EXPECTED RESULTS
ping success for both hosts cause both are reachable

##### ACTUAL RESULTS
if i ping this groups one of nodes always failed... they use both the same keyfile.
if 10.8.0.11 is reachable the 10.8.0.13 host failed. If 10.8.0.13 is reachable the 10.8.0.11 failed... they are never both reachable in one run
```
ansible -m ping test -vvv
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
META: ran handlers
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
<10.8.0.13> ESTABLISH SSH CONNECTION FOR USER: root
<10.8.0.13> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=15 -o ControlPath=/root/.ansible/cp/659afc6385 10.8.0.13'/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<10.8.0.11> ESTABLISH SSH CONNECTION FOR USER: root
<10.8.0.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=15 -o ControlPath=/root/.ansible/cp/21612e68a6 10.8.0.11 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1509129203.27-51361665222552/ /root/.ansible/tmp/ansible-tmp-1509129203.27-51361665222552/ping.py && sleep 0'"'"''
<10.8.0.11> (0, '', '')
<10.8.0.11> ESTABLISH SSH CONNECTION FOR USER: root
<10.8.0.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=15 -o ControlPath=/root/.ansible/cp/21612e68a6 -tt 10.8.0.11 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1509129203.27-51361665222552/ping.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1509129203.27-51361665222552/" > /dev/null 2>&1 && sleep 0'"'"''
<10.8.0.13> (255, '', 'Permission denied (publickey,password).\r\n')
10.8.0.13 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n",
    "unreachable": true
}
<10.8.0.11> (0, '\r\n{"invocation": {"module_args": {"data": "pong"}}, "ping": "pong"}\r\n', 'Shared connection to 10.8.0.11 closed.\r\n')
10.8.0.11 | SUCCESS => {
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}
META: ran handlers
META: ran handlers

```

**Comment by nixmomo** [comment]
in playbook he do all steps but after 18. it brakes ... here is a log (if i run the playbook on one host only it works without errors)

```
21:05:38 | <10.8.0.11> ESTABLISH SSH CONNECTION FOR USER: root
-- | --
21:05:38 | <10.8.0.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/rundeck/var/tmp/ansible-runner7900417963739834709id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=15 -o ControlPath=/var/lib/rundeck/.ansible/cp/%h-%r 10.8.0.11 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1509131138.06-227120233719349 `" && echo ansible-tmp-1509131138.06-227120233719349="` echo /root/.ansible/tmp/ansible-tmp-1509131138.06-227120233719349 `" ) && sleep 0'"'"''
21:05:38 | <10.8.0.11> (0, 'ansible-tmp-1509131138.06-227120233719349=/root/.ansible/tmp/ansible-tmp-1509131138.06-227120233719349\n', '')
21:05:38 | <10.8.0.11> PUT /tmp/tmpKMLNmI TO /root/.ansible/tmp/ansible-tmp-1509131138.06-227120233719349/command.py
21:05:38 | <10.8.0.11> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/rundeck/var/tmp/ansible-runner7900417963739834709id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=15 -o ControlPath=/var/lib/rundeck/.ansible/cp/%h-%r '[10.8.0.11]'
21:05:38 | <10.8.0.13> (255, '', 'Permission denied (publickey,password).\r\n')
21:05:38 | fatal: [10.8.0.13]: UNREACHABLE! => {
21:05:38 | "changed": false,
21:05:38 | "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n",
21:05:38 | "unreachable": true
21:05:38 | }
```
At the end from the log it posts this

```

21:05:39 | ERROR: Ansible execution returned with non zero code.
-- | --
21:05:39 | Failed executing step plugin [com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep]: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: ERROR: Ansible execution returned with non zero code. 	at com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep.executeStep(AnsiblePlaybookWorkflowStep.java:84) 	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:105) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:97) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687) 	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71) 	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73) 	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31) 	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$27(WorkflowEngineOperationsProcessor.java:197) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: com.batix.rundeck.core.AnsibleException: ERROR: Ansible execution returned with non zero code. 	at com.batix.rundeck.core.AnsibleRunner.run(AnsibleRunner.java:493) 	at com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep.executeStep(AnsiblePlaybookWorkflowStep.java:82) 	... 12 more
21:05:39 | 1: Workflow step finished, result: AnsibleNonZero: ERROR: Ansible execution returned with non zero code.
21:05:39 | [workflow] Finish step: 1,com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep


```

**Comment by nixmomo** [comment]
update 2:
other playbooks works without errors with both of this hosts... im pretty sure that the problem is that the playbook plays very long (more as 5 minutes) and that i run in any timeout or file deletion before the playbooks finished.
Im new to ansible so all ideas that point me in the right way are welcome

**Comment by nixmomo** [comment]
to help the devs... it is a bug in transport = smart (or whatever is default )

If i set transport      = paramiko in ansible.cfg it works as expected but that cant be the solution

**Comment by samdoran** [comment]
This seems like an issue best addressed on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
