### ISSUE TITLE
ssh issue

### ISSUE THREAD

**Issue by arun8796** [ansible/ansible#32331]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ssh
##### ANSIBLE VERSION

2.4

##### OS / ENVIRONMENT

conrol server is centOS 7
remote host is redhat 7

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
need to connect to remote host with ssh

##### ACTUAL RESULTS
ansible all -m ping
The authenticity of host 'ansmaster (xx.xx.xx.xx)' can't be established.
ECDSA key fingerprint is SHA256:KnoUCPBMGuHmA83ZNBwCZvcxIXQIrXjW8QJ6vF16dVs.
ECDSA key fingerprint is MD5:70:d4:4a:cc:32:3c:bf:3a:c5:cf:47:60:06:42:9d:2b.
Are you sure you want to continue connecting (yes/no)? webapp1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n",
    "unreachable": true
}
^CProcess WorkerProcess-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
    self._rslt_q
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 639, in _execute_module
    tmp = self._make_tmp_path()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 245, in _make_tmp_path
    tmpdir = self._remote_expand_user(self._play_context.remote_tmp_dir, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 549, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 886, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 948, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 233, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 846, in _run
    return self._bare_run(cmd, in_data, sudoable, checkrc)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 686, in _bare_run
    events = selector.select(timeout)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 482, in select
    maxevents=max_events)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 136, in _syscall_wrapper
    result = func(*args, **kwargs)
KeyboardInterrupt
 [ERROR]: User interrupted execution

**Comment by thaumos** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by loay317** [comment]
Hello  friends 

I;m new to ansible and I would like to run simple playbook on some Centos servers 

Im able to ssh without password isng keys to the target servers but when I run single command or simple playbook I get error as below



# [root@ansible ~]# ansible -vvv CPANEL-SERVERS  -m command -a "uptime"
Using /etc/ansible/ansible.cfg as config file
META: ran handlers
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 472, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 729, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 353, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 272
    b"-o", b"PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey",
        ^
SyntaxError: invalid syntax

217.66.226.50 | FAILED | rc=-1 >>
Unexpected failure during module execution.

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 472, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 729, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 353, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 272
    b"-o", b"PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey",
        ^
SyntaxError: invalid syntax

217.66.226.116 | FAILED | rc=-1 >>
Unexpected failure during module execution.

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 472, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 729, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new

**Comment by loay317** [comment]
**## [root@ansible ansible]# ansible-playbook  removeuser-item.yml**

PLAY [CPANEL-SERVERS] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.50]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.79]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.62]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.116]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.38]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.211]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [217.66.226.212]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
        to retry, use: --limit @/etc/ansible/removeuser-item.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
217.66.226.116             : ok=0    changed=0    unreachable=0    failed=1
217.66.226.211             : ok=0    changed=0    unreachable=0    failed=1
217.66.226.212             : ok=0    changed=0    unreachable=0    failed=1
217.66.226.38              : ok=0    changed=0    unreachable=0    failed=1
217.66.226.50              : ok=0    changed=0    unreachable=0    failed=1
217.66.226.62              : ok=0    changed=0    unreachable=0    failed=1
217.66.226.79              : ok=0    changed=0    unreachable=0    failed=1

**Comment by rahulbhatu** [comment]
Hi ,
I am new to ansible i have control server centos7 and one ubuntu 18.04 & centos7 as client , i have setup setup static ip address on all 3 servers, i am able to ping both machines successfully via ansible command line but when i am trying to run below command from control server

ansible (centos client)  -s -m shell -a  'yum install telnet' 

the command runs forever it doesnt timeout and when i cancel the command i get below error.
can someone please help


Process WorkerProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
    self._final_q
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 603, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/shell.py", line 27, in run
    result = command_action.run(task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/command.py", line 24, in run
    results = merge_hash(results, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 839, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 954, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1081, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 337, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 971, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 808, in _bare_run
    events = selector.select(timeout)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 466, in select
 [ERROR]: User interrupted execution

    maxevents=max_events)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 119, in _syscall_wrapper
    result = func(*args, **kwargs)
