### ISSUE TITLE
improve error handling when specifying invalid inventory files

### ISSUE THREAD

**Issue by broferek** [ansible/ansible#3238]
With 1.1, if you want to setup hostfile = /etc/ansible in /etc/ansible/ansible.cfg and put multiple inventories in it, your commands will hang forever.
I have 2 manual inventories with 80 and 600 hosts respectively.

A simple ping of one host of my inventory hangs for ever, then, I kill it and get : 

Traceback (most recent call last):
  File "/usr/bin/ansible", line 157, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/bin/ansible", line 83, in run
    inventory_manager = inventory.Inventory(options.inventory)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/**init**.py", line 83, in **init**
    self.parser = InventoryDirectory(filename=host_list)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/dir.py", line 47, in **init**
    parser = InventoryDirectory(filename=fullpath)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/dir.py", line 51, in **init**
    parser = InventoryParser(filename=fullpath)
  File "/usr/lib/python2.6/site-packages/ansible/inventory/ini.py", line 40, in **init**
    self._parse()
  File "/usr/lib/python2.6/site-packages/ansible/inventory/ini.py", line 44, in _parse
    self._parse_base_groups()
  File "/usr/lib/python2.6/site-packages/ansible/inventory/ini.py", line 114, in _parse_base_groups
    (k,v) = t.split("=")
ValueError: need more than 1 value to unpack

If I put my inventories into a subdirectory, it works fine (for ex : /etc/ansible/inventories)

**Comment by mpdehaan** [comment]
Not sure there's any recursion going on but I'll take a look at the error handling.

It's true that you can't use /etc/ansible as an inventory dir though because you've got /etc/ansible/ansible.cfg in it which is not an inventory file.

**Comment by jimi-c** [comment]
It appears that the error handling was fixed, so I'm going to close. Thanks!

<pre>
$ ansible -m ping all
ERROR: Invalid ini entry: /etc/ansible - need more than 1 value to unpack
</pre>
