### ISSUE TITLE
Can't pass vault_pass to PlaybookExecutor

### ISSUE THREAD

**Issue by huzilin** [ansible/ansible#32844]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
PlaybookExecutor

##### ANSIBLE VERSION
```
ansible 2.5.0
```

##### OS / ENVIRONMENT
centos6.8 

##### SUMMARY
Can't pass vault_pass to PlaybookExecutor

##### STEPS TO REPRODUCE
```
.
├── files
├── group_vars
│   └── all
│       └── vault
│           └── passwd.yml      # I want to use vault_pass to access this file.
├── inventory
├── roles
│   └── all
│       ├── tasks
│       │   └── main.yml
│       └── templates
│           └── test.j2
├── test_pbexcute.py
└── test.yml
```

My code:

```
import json
from collections import namedtuple
from ansible.parsing.dataloader import DataLoader
from ansible.vars.manager import VariableManager
from ansible.inventory.manager import InventoryManager
from ansible.playbook.play import Play
from ansible.executor.task_queue_manager import TaskQueueManager
from ansible.plugins.callback import CallbackBase
from ansible.executor.playbook_executor import PlaybookExecutor


class ResultCallback(CallbackBase):
    """A sample callback plugin used for performing an action as results come in

    If you want to collect all results into a single object for processing at
    the end of the execution, look into utilizing the ``json`` callback plugin
    or writing your own custom callback plugin
    """

    def v2_runner_on_ok(self, result, **kwargs):
        """Print a json representation of the result

        This method could store the result in an instance attribute for retrieval later
        """
        host = result._host
        print(json.dumps({host.name: result._result}, indent=4))


results_callback = ResultCallback()
Options = namedtuple('Options', ['connection', 'listtags', 'listtasks', 'listhosts', 'syntax', 'module_path', 'forks', 'become', 'become_method', 'become_user', 'check', 'diff'])
# initialize needed objects
loader = DataLoader()
options = Options(connection='ssh', listtags=False, listtasks=False, listhosts=False, syntax=False, module_path=None, forks=100, become=None, become_method=None, become_user=None, check=False, diff=False)
passwords = dict(vault_pass='123456')     # I follow the API document

inventory = InventoryManager(
    loader=loader, sources=['test/inventory'])
variable_manager = VariableManager(loader=loader, inventory=inventory)

playbook_path = 'test/test.yml'

pbex = PlaybookExecutor(playbooks=[playbook_path], inventory=inventory,
                        variable_manager=variable_manager, loader=loader,
                        options=options, passwords=passwords)
pbex._tqm._stdout_callback=results_callback
code = pbex.run()
print results_callback
```

##### EXPECTED RESULTS
I execute the playbook correctly.

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "/opt/dev/ansible/test/test_pbexcute.py", line 46, in <module>
    code = pbex.run()
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/executor/task_queue_manager.py", line 290, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/plugins/strategy/linear.py", line 248, in run
    task_vars = self._variable_manager.get_vars(play=iterator._play, host=host, task=task)
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/vars/manager.py", line 311, in get_vars
    all_vars = combine_vars(all_vars, locals()[entry]())
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/vars/manager.py", line 278, in all_plugins_inventory
    return _plugins_inventory([all_group])
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/vars/manager.py", line 262, in _plugins_inventory
    data = combine_vars(data, _get_plugin_vars(plugin, inventory_dir, entities))
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/vars/manager.py", line 236, in _get_plugin_vars
    data = plugin.get_vars(self._loader, path, entities)
  File "/usr/lib/python2.6/site-packages/ansible-2.5.0-py2.6.egg/ansible/plugins/vars/host_group_vars.py", line 103, in get_vars
    raise AnsibleParserError(to_native(e))
ansible.errors.AnsibleParserError: A vault password must be specified to decrypt data
```

**Comment by sivel** [comment]
The Ansible python API is an internal API and not considered to be a stable public API.  As the ansible command line utilities are unaffected, that indicates that you are misusing the API.

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
