### ISSUE TITLE
[Regression] ios broken with connection: network_cli

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#32942]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_*

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 43f89004a0) last updated 2017/11/15 11:25:45 (GMT +100)
```

##### SUMMARY
ios seems to be fairly broken when using `connection: network_cli`

This works correctly when `ansible_connection=local` is used

##### STEPS TO REPRODUCE
```yaml
- name: "Download switch configuration"
  hosts: switches
  gather_facts: no

  tasks:
   ###
   # Collect data
    - name: command (ios)
      ios_command:
        commands:
          show version
      when: "'ios' in group_names"
```

```
[ios]
ios02.example.net ansible_connection=network_cli ansible_network_os=ios ansible_user=user1 ansible_ssh_pass=mypassword
```
##### ACTUAL RESULTS
```
TASK [command (ios)] *****************************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/gundalows-test-cases/connection_playground/become-network.yml:8
<ios02.example.net> attempting to start connection
<ios02.example.net> using connection plugin network_cli
The full traceback is:
Traceback (most recent call last):
  File "/home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/executor/task_executor.py", line 482, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/executor/task_executor.py", line 742, in _get_connection
    socket_path = self._start_connection()
  File "/home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/executor/task_executor.py", line 803, in _start_connection
    result = json.loads(stderr)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

fatal: [ios02.example.net]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Comment by gundalow** [comment]
Adding some extra logging shows
```
Traceback (most recent call last):
  File "/home/johnb/git/ansible-inc/ansible-workspace-4/bin/ansible-connection", line 326, in <module>
    main()
  File "/home/johnb/git/ansible-inc/ansible-workspace-4/bin/ansible-connection", line 302, in main
    if isinstance(exc, ConnectionError) and getattr(exc, 'code') == -32601:
AttributeError: 'ConnectionError' object has no attribute 'code'
```
