### ISSUE TITLE
ansible-galaxy install in Ansible Tower Vagrant IndexError: list index out of range.

### ISSUE THREAD

**Issue by Armesh** [ansible/ansible#32954]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
Ansible Tower Vagrant Box
$ vagrant init ansible/tower
$ vagrant up --provider virtualbox

##### ANSIBLE VERSION
ansible/tower (virtualbox, 3.2.1)

```
[vagrant@ansible-tower ~]$ ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ISSUE SUMMARY

ansible-galaxy install command in Ansible Tower Vagrant box always giving IndexError: list index out of range.
```
[vagrant@ansible-tower ~]$ ansible-galaxy install geerlingguy.mysql -vvv
Using /etc/ansible/ansible.cfg as config file
Opened /home/vagrant/.ansible_galaxy
Installing role geerlingguy.mysql
Opened /home/vagrant/.ansible_galaxy
- downloading role 'mysql', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=mysql
https://galaxy.ansible.com/api/v1/roles/435/versions/?page_size=50
https://galaxy.ansible.com/api/v1/roles/435/versions/?page=2&page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.8.0.tar.gz
- extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
- extracting geerlingguy.mysql to /usr/share/ansible/roles/geerlingguy.mysql
ERROR! Unexpected Exception: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 109, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 138, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 149, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 387, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 336, in install
    self.path = self.paths[nextidx]
IndexError: list index out of range
[vagrant@ansible-tower ~]$

```

**Comment by Armesh** [comment]
```
[vagrant@ansible-tower ~]$ sudo -s
  Welcome to Ansible Tower!
  Log into the web interface here:
    https://10.42.0.xx/
    Username: admin
    Password: xxxxx
  The documentation for Ansible Tower is available here:
    http://www.ansible.com/tower/
  For help, visit  http://support.ansible.com/
[root@ansible-tower vagrant]# ansible-galaxy install geerlingguy.mysql
- downloading role 'mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.8.0.tar.gz
- extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
- geerlingguy.mysql (2.8.0) was installed successfully
```

Switching to root user in vagrant and then doing ansible-galaxy install works fine.

**Comment by samdoran** [comment]
The error message you're getting from `ansible-galaxy` is not very helpful. The issue is the `vagrant` user can't write to `/etc/ansible/roles` or `/usr/share/ansible/roles`. Those are the default installation paths unless you use `-p` and specify a path. That is also running as `root` works.
