### ISSUE TITLE
Upgrade to 2.4.1.0 via pip fails on MacOS

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible#32982]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Upgrade of ansible via pip.

##### ANSIBLE VERSION
2.4.1.0

Existing version:
```shell
$ ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/xxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```
##### CONFIGURATION
Default.

##### OS / ENVIRONMENT
```
      System Version: macOS 10.13.1 (17B48)
      Kernel Version: Darwin 17.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: SD12355
      User Name: XXXXX, XXXXX
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 6:14
```

##### SUMMARY
Unable to upgrade to the latest version via pip.

##### STEPS TO REPRODUCE

```shell
$ pip2 install -U ansible
Collecting ansible
  Downloading ansible-2.4.1.0.tar.gz (6.7MB)
    100% |████████████████████████████████| 6.7MB 217kB/s
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/__init__.py", line 160, in <module>
    monkey.patch_all()
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/monkey.py", line 67, in patch_all
    distutils.core.Command = setuptools.Command
AttributeError: 'module' object has no attribute 'Command'
```

##### EXPECTED RESULTS
Upgrade should be successful.

##### ACTUAL RESULTS
Fails with error (see above).

**Comment by sivel** [comment]
This error is coming from setuptools and not from ansible.  You should consider upgrading pip/setuptools which should resolve your errors:

```
sudo pip install -U pip
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
