### ISSUE TITLE
ini_file module parse error using krb5.conf

### ISSUE THREAD

**Issue by dch** [ansible/ansible#3355]
ubuntu 13.04 amd64 azure build.
ansible devel as of 20130626

playbook snippet:

```
  - name: ensure realm name is correct
    ini_file: dest=/etc/krb5.conf section=libdefaults option=default_realm value=DOMAIN.COM mode=0644 backup=yes
```

error:

```
ASK: [ensure realm name is correct] ******************************************
...
<domain.cloudapp.net> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=foofoofootoyou] password: " -u root /bin/sh -c '"'"'/usr/bin/python /home/ansible/.ansible/tmp/ansible-1372289222.24-181665965697044/ini_file; rm -rf /home/ansible/.ansible/tmp/ansible-1372289222.24-181665965697044/ >/dev/null 2>&1'"'"''
fatal: [domain.cloudapp.net] => failed to parse: Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-1372289222.24-181665965697044/ini_file", line 1121, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-1372289222.24-181665965697044/ini_file", line 200, in main
    changed = do_ini(module, dest, section, option, value, state, backup)
  File "/home/ansible/.ansible/tmp/ansible-1372289222.24-181665965697044/ini_file", line 99, in do_ini
    cp.readfp(f)
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /etc/krb5.conf
    [line  2]: '\tdefault_realm = 3793B6DBE90A42B3871644917931843C.DOMAIN.549413043.EUROPEWEST.INTERNAL.CLOUDAPP.NET\n'
    [line  5]: '\tkrb4_config = /etc/krb.conf\n'
    [line  6]: '\tkrb4_realms = /etc/krb.realms\n'
    [line  7]: '\tkdc_timesync = 1\n'
    [line  8]: '\tccache_type = 4\n'
    [line  9]: '\tforwardable = true\n'
    [line 10]: '\tproxiable = true\n'
    [line 27]: '\tv4_instance_resolve = false\n'
    [line 28]: '\tv4_name_convert = {\n'
    [line 29]: '\t\thost = {\n'
    [line 30]: '\t\t\trcmd = host\n'
    [line 31]: '\t\t\tftp = ftp\n'
    [line 32]: '\t\t}\n'
    [line 33]: '\t\tplain = {\n'
    [line 34]: '\t\t\tsomething = something-else\n'
    [line 35]: '\t\t}\n'
    [line 36]: '\t}\n'
    [line 37]: '\tfcc-mit-ticketflags = true\n'
    [line 40]: '\tATHENA.MIT.EDU = {\n'
    [line 41]: '\t\tkdc = kerberos.mit.edu:88\n'
    [line 42]: '\t\tkdc = kerberos-1.mit.edu:88\n'
    [line 43]: '\t\tkdc = kerberos-2.mit.edu:88\n'
    [line 44]: '\t\tadmin_server = kerberos.mit.edu\n'
    [line 45]: '\t\tdefault_domain = mit.edu\n'
    [line 46]: '\t}\n'
    [line 47]: '\tMEDIA-LAB.MIT.EDU = {\n'
    [line 48]: '\t\tkdc = kerberos.media.mit.edu\n'
    [line 49]: '\t\tadmin_server = kerberos.media.mit.edu\n'
    [line 50]: '\t}\n'
    [line 51]: '\tZONE.MIT.EDU = {\n'
    [line 52]: '\t\tkdc = casio.mit.edu\n'
    [line 53]: '\t\tkdc = seiko.mit.edu\n'
    [line 54]: '\t\tadmin_server = casio.mit.edu\n'
    [line 55]: '\t}\n'
    [line 56]: '\tMOOF.MIT.EDU = {\n'
    [line 57]: '\t\tkdc = three-headed-dogcow.mit.edu:88\n'
    [line 58]: '\t\tkdc = three-headed-dogcow-1.mit.edu:88\n'
    [line 59]: '\t\tadmin_server = three-headed-dogcow.mit.edu\n'
    [line 60]: '\t}\n'
    [line 61]: '\tCSAIL.MIT.EDU = {\n'
    [line 62]: '\t\tkdc = kerberos-1.csail.mit.edu\n'
    [line 63]: '\t\tkdc = kerberos-2.csail.mit.edu\n'
    [line 64]: '\t\tadmin_server = kerberos.csail.mit.edu\n'
    [line 65]: '\t\tdefault_domain = csail.mit.edu\n'
    [line 66]: '\t\tkrb524_server = krb524.csail.mit.edu\n'
    [line 67]: '\t}\n'
    [line 68]: '\tIHTFP.ORG = {\n'
    [line 69]: '\t\tkdc = kerberos.ihtfp.org\n'
    [line 70]: '\t\tadmin_server = kerberos.ihtfp.org\n'
    [line 71]: '\t}\n'
    [line 72]: '\tGNU.ORG = {\n'
    [line 73]: '\t\tkdc = kerberos.gnu.org\n'
    [line 74]: '\t\tkdc = kerberos-2.gnu.org\n'
    [line 75]: '\t\tkdc = kerberos-3.gnu.org\n'
    [line 76]: '\t\tadmin_server = kerberos.gnu.org\n'
    [line 77]: '\t}\n'
    [line 78]: '\t1TS.ORG = {\n'
    [line 79]: '\t\tkdc = kerberos.1ts.org\n'
    [line 80]: '\t\tadmin_server = kerberos.1ts.org\n'
    [line 81]: '\t}\n'
    [line 82]: '\tGRATUITOUS.ORG = {\n'
    [line 83]: '\t\tkdc = kerberos.gratuitous.org\n'
    [line 84]: '\t\tadmin_server = kerberos.gratuitous.org\n'
    [line 85]: '\t}\n'
    [line 86]: '\tDOOMCOM.ORG = {\n'
    [line 87]: '\t\tkdc = kerberos.doomcom.org\n'
    [line 88]: '\t\tadmin_server = kerberos.doomcom.org\n'
    [line 89]: '\t}\n'
    [line 90]: '\tANDREW.CMU.EDU = {\n'
    [line 91]: '\t\tkdc = kerberos.andrew.cmu.edu\n'
    [line 92]: '\t\tkdc = kerberos2.andrew.cmu.edu\n'
    [line 93]: '\t\tkdc = kerberos3.andrew.cmu.edu\n'
    [line 94]: '\t\tadmin_server = kerberos.andrew.cmu.edu\n'
    [line 95]: '\t\tdefault_domain = andrew.cmu.edu\n'
    [line 96]: '\t}\n'
    [line 97]: '\tCS.CMU.EDU = {\n'
    [line 98]: '\t\tkdc = kerberos.cs.cmu.edu\n'
    [line 99]: '\t\tkdc = kerberos-2.srv.cs.cmu.edu\n'
    [line 100]: '\t\tadmin_server = kerberos.cs.cmu.edu\n'
    [line 101]: '\t}\n'
    [line 102]: '\tDEMENTIA.ORG = {\n'
    [line 103]: '\t\tkdc = kerberos.dementix.org\n'
    [line 104]: '\t\tkdc = kerberos2.dementix.org\n'
    [line 105]: '\t\tadmin_server = kerberos.dementix.org\n'
    [line 106]: '\t}\n'
    [line 107]: '\tstanford.edu = {\n'
    [line 108]: '\t\tkdc = krb5auth1.stanford.edu\n'
    [line 109]: '\t\tkdc = krb5auth2.stanford.edu\n'
    [line 110]: '\t\tkdc = krb5auth3.stanford.edu\n'
    [line 111]: '\t\tmaster_kdc = krb5auth1.stanford.edu\n'
    [line 112]: '\t\tadmin_server = krb5-admin.stanford.edu\n'
    [line 113]: '\t\tdefault_domain = stanford.edu\n'
    [line 114]: '\t}\n'
    [line 115]: '        UTORONTO.CA = {\n'
    [line 116]: '                kdc = kerberos1.utoronto.ca\n'
    [line 117]: '                kdc = kerberos2.utoronto.ca\n'
    [line 118]: '                kdc = kerberos3.utoronto.ca\n'
    [line 119]: '                admin_server = kerberos1.utoronto.ca\n'
    [line 120]: '                default_domain = utoronto.ca\n'
    [line 121]: '\t}\n'
    [line 124]: '\t.mit.edu = ATHENA.MIT.EDU\n'
    [line 125]: '\tmit.edu = ATHENA.MIT.EDU\n'
    [line 126]: '\t.media.mit.edu = MEDIA-LAB.MIT.EDU\n'
    [line 127]: '\tmedia.mit.edu = MEDIA-LAB.MIT.EDU\n'
    [line 128]: '\t.csail.mit.edu = CSAIL.MIT.EDU\n'
    [line 129]: '\tcsail.mit.edu = CSAIL.MIT.EDU\n'
    [line 130]: '\t.whoi.edu = ATHENA.MIT.EDU\n'
    [line 131]: '\twhoi.edu = ATHENA.MIT.EDU\n'
    [line 132]: '\t.stanford.edu = stanford.edu\n'
    [line 133]: '\t.slac.stanford.edu = SLAC.STANFORD.EDU\n'
    [line 134]: '        .toronto.edu = UTORONTO.CA\n'
    [line 135]: '        .utoronto.ca = UTORONTO.CA\n'
    [line 138]: '\tkrb4_convert = true\n'
    [line 139]: '\tkrb4_get_tickets = false\n'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
```

I'm guessing the issue is the indented lines, and I think ansible should be able to handle this.

**Comment by dch** [comment]
without being a python guru, I _think_ this comes from ConfigParser.py on my system:

``` python
   def _read(self, fp, fpname):
        """Parse a sectioned setup file.

        The sections in setup file contains a title line at the top,
        indicated by a name in square brackets (`[]'), plus key/value
        options lines, indicated by `name: value' format lines.
        Continuations are represented by an embedded newline then
        leading whitespace.  Blank lines, lines beginning with a '#',
        and just about everything else are ignored.
        """
        cursect = None                        # None, or a dictionary
        optname = None
        lineno = 0
        e = None                              # None, or an exception
        while True:
            line = fp.readline()
            if not line:
                break
            lineno = lineno + 1
            # comment or blank line?
            if line.strip() == '' or line[0] in '#;':
                continue
            if line.split(None, 1)[0].lower() == 'rem' and line[0] in "rR":
                # no leading whitespace
                continue
            # continuation line?
            if line[0].isspace() and cursect is not None and optname:
                value = line.strip()
                if value:
                    cursect[optname].append(value)
            # a section header or option header?
            else:
                # is it a section header?
                mo = self.SECTCRE.match(line)
                if mo:
                    sectname = mo.group('header')
                    if sectname in self._sections:
                        cursect = self._sections[sectname]
                    elif sectname == DEFAULTSECT:
                        cursect = self._defaults
                    else:
                        cursect = self._dict()
                        cursect['__name__'] = sectname
                        self._sections[sectname] = cursect
                    # So sections can't start with a continuation line
                    optname = None
                # no section header in the file?
                elif cursect is None:
                    raise MissingSectionHeaderError(fpname, lineno, line)
                # an option line?
                else:
                    mo = self._optcre.match(line)
                    if mo:
                        optname, vi, optval = mo.group('option', 'vi', 'value')
                        optname = self.optionxform(optname.rstrip())
                        # This check is fine because the OPTCRE cannot
                        # match if it would set optval to None
                        if optval is not None:
                            if vi in ('=', ':') and ';' in optval:
                                # ';' is a comment delimiter only if it follows
                                # a spacing character
                                pos = optval.find(';')
                                if pos != -1 and optval[pos-1].isspace():
                                    optval = optval[:pos]
                            optval = optval.strip()
                            # allow empty values
                            if optval == '""':
                                optval = ''
                            cursect[optname] = [optval]
                        else:
                            # valueless option handling
                            cursect[optname] = optval
                    else:
                        # a non-fatal parsing error occurred.  set up the
                        # exception but keep going. the exception will be
                        # raised at the end of the file and will contain a
                        # list of all bogus lines
                        if not e:
                            e = ParsingError(fpname)
                        e.append(lineno, repr(line))
        # if any parsing errors occurred, raise an exception
        if e:
            raise e
```

**Comment by mpdehaan** [comment]
I'm not sure it's the intended lines at all, but perhaps something else.

Can you whittle it down to a more minimal example by removing pieces of the
file until this occurs?

I should also add, I'm very partial to using the template module for things
like this, and generally believe, when possible, configurations should be
absolutely and centrally managed.
ini_file exists for those when you need to allow some partial control to a
user, outside of what the sysadmin might do.

Kerberos is not one of those things, generally speaking :)

**Comment by mpdehaan** [comment]
Also, just looked, krb5.conf is not an INI file :)

**Comment by mpdehaan** [comment]
take a look here for an example

http://www.fnal.gov/docs/strongauth/krb5conf.html

compare with this:

http://en.wikipedia.org/wiki/INI_file

**Comment by dch** [comment]
Sorry, the [realms] section is what's non-compliant with its { ..\n ... } sections; I can't believe I missed this last night!
