### ISSUE TITLE
maven_artifact Python3 Support

### ISSUE THREAD

**Issue by lowjoel** [ansible/ansible#33761]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/joellow/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

Generated by Packer. Nothing specific, except specifying `ansible_python_interpreter=/usr/bin/python3` as required.

##### OS / ENVIRONMENT

macOS El Capitan, managing Ubuntu 16.04 with default Python3 runtime (3.5.2)

##### SUMMARY

Cannot use `maven_artifact` with python3 on managed host.

##### STEPS TO REPRODUCE

```yaml
  maven_artifact:
    group_id: "{{ item.group_id }}"
    artifact_id: "{{ item.artifact_id }}"
    version: "{{ item.version }}"
    repository_url: <url>
    extension: hpi
    dest: "/path/to/dir/{{ item.group_id }}.{{ item.artifact_id }}-{{ item.version }}.hpi"
    group: root
    owner: root
    mode: 0644
```

##### EXPECTED RESULTS

Should succeed.

##### ACTUAL RESULTS

Error running the command on the remote. I got one error:

```
failed: [default] (item={u'group_id': u'<group_id>', u'artifact_id': u'<artifact>', u'version': u'<version>'}) => {"changed": false, "item": {"artifact_id": "<artifact>", "group_id": "<group_id>", "version": "<version>"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 499, in <module>\n    main()\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 481, in main\n    if downloader.download(artifact, b_dest):\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 350, in download\n    self._write_chunks(response, f, report_hook=self.chunk_report)\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 368, in _write_chunks\n    total_size = response.info().getheader('Content-Length').strip()\nAttributeError: 'HTTPMessage' object has no attribute 'getheader'\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

Replacing `getheader` with `get` on line 368 in the Ansible source yields:

```
failed: [default] (item={u'group_id': u'<group_id>', u'artifact_id': u'<artifact>', u'version': u'<version>'}) => {"changed": false, "item": {"artifact_id": "<artifact>", "group_id": "<group_id>", "version": "<version>"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 499, in <module>\n    main()\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 481, in main\n    if downloader.download(artifact, b_dest):\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 350, in download\n    self._write_chunks(response, f, report_hook=self.chunk_report)\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 379, in _write_chunks\n    file.write(chunk)\nTypeError: write() argument must be str, not bytes\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

Replacing `open(..., 'w')` with `open(..., 'wb')` on line 348 seems to fix it.

**Comment by alikins** [comment]
(just pasting a formatted version of the errors mentioned above for slightly easier reading)

```
failed: [default] (item={u'group_id': u'<group_id>', u'artifact_id': u'<artifact>', u'version': u'<version>'}) => {"changed": false, "item": {"artifact_id": "<artifact>", "group_id": "<group_id>", "version": "<version>"}, "module_stderr": 
"Traceback (most recent call last):
  File "/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py", line 499, in <module>
    main()
  File "/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py", line 481, in main
    if downloader.download(artifact, b_dest):
  File "/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py", line 350, in download
    self._write_chunks(response, f, report_hook=self.chunk_report)
  File "/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py", line 368, in _write_chunks
    total_size = response.info().getheader('Content-Length').strip()
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
Shared connection to 127.0.0.1 closed.
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

Replacing `getheader` with `get` on line 368 in the Ansible source yields:



```

failed: [default] (item={u'group_id': u'<group_id>', u'artifact_id': u'<artifact>', u'version': u'<version>'}) => {"changed": false, "item": {"artifact_id": "<artifact>", "group_id": "<group_id>", "version": "<version>"}, "module_stderr": 
"Traceback (most recent call last):
  File "/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py", line 499, in <module>
    main()
  File "/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py", line 481, in main
    if downloader.download(artifact, b_dest):
  File "/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py", line 350, in download
    self._write_chunks(response, f, report_hook=self.chunk_report)
  File "/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py", line 379, in _write_chunks
    file.write(chunk)
TypeError: write() argument must be str, not bytes
Shared connection to 127.0.0.1 closed.
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by alikins** [comment]
pinging @abadger

**Comment by abadger** [comment]
Looks like get() was added as an alias of getheader in python 2.2.  So +1
to making that change.

Looks like we will always write bytes in that function so +1 to that change
as well.

**Comment by lowjoel** [comment]
Sorry about that @alikins -- forgot to add the newlines back after pasting it in.

**Comment by alikins** [comment]
@lowjoel Not a problem it wasn't your fault. The stdout output from ansible in that case has the embedded "\n"'s which looks weird everywhere and I find hard to read so I fix it sometimes ;->

**Comment by akashgangil** [comment]
Seeing this issue as well.
