### ISSUE TITLE
Larger inventory can cause maximum recursion depth Exception

### ISSUE THREAD

**Issue by mdelagrange** [ansible/ansible#33922]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/mdelagrange/src/github/ansible_include_role_bug_2/ansible.cfg
  configured module search path = [u'/Users/mdelagrange/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible
  executable location = ./env/bin/ansible
  python version = 2.7.12 (default, Jun 29 2016, 14:05:02) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/Users/mdelagrange/src/github/ansible_include_role_bug_2/ansible.cfg) = [u'/Users/mdelagrange/src/github/ansible_include_role_bug_2/inventory']

##### OS / ENVIRONMENT

N/A

##### SUMMARY

There can be a recursion Exception when using the include_role task in conjunction with a large Ansible inventory.

##### STEPS TO REPRODUCE

1. Clone https://github.com/mdelagrange/ansible_include_role_bug
2. Run make test_2_4_2_0

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: test_role
```

##### EXPECTED RESULTS

`test_role` is executed successfully.

##### ACTUAL RESULTS

```
/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/bin/ansible-playbook test-playbook.yml -vvvv
ansible-playbook 2.4.2.0
  config file = /Users/mdelagrange/src/github/ansible_include_role_bug_2/ansible.cfg
  configured module search path = [u'/Users/mdelagrange/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible
  executable location = /Users/mdelagrange/src/github/ansible_include_role_bug_2/env/bin/ansible-playbook
  python version = 2.7.12 (default, Jun 29 2016, 14:05:02) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Using /Users/mdelagrange/src/github/ansible_include_role_bug_2/ansible.cfg as config file
setting up inventory plugins
Parsed /Users/mdelagrange/src/github/ansible_include_role_bug_2/inventory/dynamic inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test-playbook.yml ****************************************************
1 plays in test-playbook.yml

PLAY [localhost] ***************************************************************
META: ran handlers

TASK [include_role] ************************************************************
task path: /Users/mdelagrange/src/github/ansible_include_role_bug_2/test-playbook.yml:4
the full traceback was:

Traceback (most recent call last):
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 290, in run
    play_return = strategy.run(iterator, play_context)
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 292, in run
    results += self._wait_on_pending_results(iterator)
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 586, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 548, in _process_pending_results
    self._tqm.send_callback('v2_runner_on_ok', task_result)
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 367, in send_callback
    new_args.append(arg.clean_copy())
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/executor/task_result.py", line 109, in clean_copy
    result._result = deepcopy(self._result)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)

  [~2000 lines omitted]

  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/inventory/host.py", line 34, in __getstate__
    return self.serialize()
  File "/Users/mdelagrange/src/github/ansible_include_role_bug_2/env/lib/python2.7/site-packages/ansible/inventory/host.py", line 59, in serialize
    groups.append(group.serialize())
RuntimeError: maximum recursion depth exceeded
```

**Comment by mdelagrange** [comment]
This report is a more detailed version of #33600.  See https://github.com/mdelagrange/ansible_include_role_bug for more detail on the test case.

**Comment by sivel** [comment]
I've bisected the offending commit to b61bfc87b85776a633ba27198a1587048079d60e

cc @bcoca

**Comment by kiorky** [comment]
I think #32565 may fix your bug which seems related to #21890, particulary this one commit https://github.com/ansible/ansible/pull/32565/commits/9891f83d936692b8e6b9b42eadf53a360ec27d19

On my fork, you have two branchs for you:

Pristine 2.5+the PR #32565 commits: https://github.com/corpusops/ansible/tree/devel
Pristine 2.4+the PR #32565 commits: https://github.com/corpusops/ansible/tree/a2.4

**Comment by mdelagrange** [comment]
I can confirm that https://github.com/corpusops/ansible/tree/a2.4 fixes the recursion error both in with the sample data I provided and with my actual production inventory.

**Comment by mkrizek** [comment]
This should be fixed with https://github.com/ansible/ansible/pull/33595 which has been merged in `devel`. I am going to close this issue, please re-open if the issue persists. Thanks!

**Comment by mdelagrange** [comment]
It seems that ad94a3a6a264b1ed9b9ccb8f1e61ebfe33c57a51 fixed this issue.

**Comment by kiorky** [comment]
For me, https://github.com/ansible/ansible/commit/ad94a3a6a264b1ed9b9ccb8f1e61ebfe33c57a51 caused a big and dangerous regression, @jimi-c , @mdelagrange , @mkrizek chained "become" (include_role -> include_tasks -> a task file with a block containing a become: true) are not fulfilled  ...

**Comment by kiorky** [comment]
And what is the way for my PR on include_role to be discussed... it is now hanging on github for monthes :'(

**Comment by jimi-c** [comment]
@kiorky can you create a new issue showing the become problem with a reproducer please?

**Comment by kiorky** [comment]
@jimi-c yeah that's indeed on my todo, but as triggered that bug on top of ansible 2.4 + my PR with include role, so i dont know yet if it's with "pristine" 2.4 of if it is related to my "include_role" related changes that the bug occurs...
(My include_role's PR doesnt exhibit the problem rebased on ansible code from 2 weeks and this commit seem to be the best candidate that causes the interaction, i ll keep you all tuned...)

**Comment by kiorky** [comment]
@jimi-c 
done: https://github.com/ansible/ansible/issues/35065
test case: https://github.com/kiorky/ansible_test_cases/tree/35065
