### ISSUE TITLE
Conditional Executions are not evaluated properly when declared in an external included task

### ISSUE THREAD

**Issue by dcoutu** [ansible/ansible#340]
Defining the same task in the top level playbook works as expected, but when the task is defined in an external tasklist, i.e. - include: tasks/deploy-tasks.yml, the conditional execution is not evaluated properly.

Traceback (most recent call last):
  File "/home/me/git/ansible/bin/ansible-playbook", line 109, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/me/git/ansible/bin/ansible-playbook", line 86, in main
    extra_vars=extra_vars
  File "/home/me/git/ansible/lib/ansible/playbook.py", line 122, in **init**
    self.playbook         = self._parse_playbook(playbook)
  File "/home/me/git/ansible/lib/ansible/playbook.py", line 206, in _parse_playbook
    self._include_tasks(play, task, dirname, new_tasks)
  File "/home/me/git/ansible/lib/ansible/playbook.py", line 172, in _include_tasks
    included = utils.parse_yaml(included)
  File "/home/me/git/ansible/lib/ansible/utils.py", line 255, in parse_yaml
    return yaml.load(data)
  File "/usr/lib64/python2.6/site-packages/yaml/__init__.py", line 58, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 42, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 93, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 434, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<string>", line 11, column 5:
      - name: deploy servercode
        ^
expected <block end>, but found '<scalar>'
  in "<string>", line 13, column 16:
        only_if: ''$class' == 'backend''

**Comment by mpdehaan** [comment]
merging this with the other conditional bug report
