### ISSUE TITLE
ansible-inventory script does not work with encrypted values embedded in yaml

### ISSUE THREAD

**Issue by kudrevatykh** [ansible/ansible#34149]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-inventory

##### ANSIBLE VERSION

```
2.4.1.0-2.4.3.0
```

##### OS / ENVIRONMENT

redhat linux
##### SUMMARY

ansible-inventory script cannot output inventory when it have yaml files with embedded ecnrypted variables
##### STEPS TO REPRODUCE

setup simple inventory with yaml file containing embedded encrypted value
run ansible-inventory --list

https://gist.github.com/kudrevatykh/39875c9939d7248cd91f7bd1155a22ae

##### EXPECTED RESULTS

correct json that can be used as inventory
##### ACTUAL RESULTS

exception when output is json and not valid output when yaml (with values &id001, *id001 instead of real value)

```
ERROR! Unexpected Exception, this is probably a bug: u'111' is not JSON serializable
the full traceback was:

Traceback (most recent call last):
  File "/home/kudrale/ansible-2.4.1.0/bin/ansible-inventory", line 106, in <module>
    exit_code = cli.run()
  File "/home/kudrale/ansible-2.4.1.0/lib/ansible/cli/inventory.py", line 157, in run
    results = self.dump(results)
  File "/home/kudrale/ansible-2.4.1.0/lib/ansible/cli/inventory.py", line 174, in dump
    results = json.dumps(stuff, sort_keys=True, indent=4)
  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib64/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: u'111' is not JSON serializable

```

**Comment by kudrevatykh** [comment]
error was added in #16274 `AnsibleVaultEncryptedUnicode` not encoded as json or yaml

**Comment by mkrizek** [comment]
duplicate_of 31141
