### ISSUE TITLE
Ansible doesn't handle missing editor gracefully

### ISSUE THREAD

**Issue by zmyrgel** [ansible/ansible#34295]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/tmy/.ansible.cfg
  configured module search path = [u'/home/tmy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 22 2017, 11:31:09) [GCC 7.2.0]
```

##### CONFIGURATION
ESC[0;33mANSIBLE_SSH_ARGS(/home/tmy/.ansible.cfg) = -C -o ControlMaster=no -o PreferredAuthentications=publickeyESC[0m
ESC[0;33mDEFAULT_BECOME(/home/tmy/.ansible.cfg) = TrueESC[0m
ESC[0;33mDEFAULT_BECOME_METHOD(/home/tmy/.ansible.cfg) = sudoESC[0m
ESC[0;33mDEFAULT_BECOME_USER(/home/tmy/.ansible.cfg) = rootESC[0m
ESC[0;33mDEFAULT_FORKS(/home/tmy/.ansible.cfg) = 10ESC[0m
ESC[0;33mDEFAULT_REMOTE_USER(/home/tmy/.ansible.cfg) = nmadminESC[0m
ESC[0;33mDEFAULT_ROLES_PATH(/home/tmy/.ansible.cfg) = [u'/home/tmy/git/ansible/roles']ESC[0m
ESC[0;33mDEFAULT_VAULT_PASSWORD_FILE(/home/tmy/.ansible.cfg) = /home/tmy/.vault_pass.txtESC[0m
ESC[0;33mDIFF_ALWAYS(/home/tmy/.ansible.cfg) = TrueESC[0m

##### OS / ENVIRONMENT
Slackware64-current x86_64

##### SUMMARY
Ansible doesn't tell meaningful error message when no editor is found. I got following when I tried to edit vault file on my new Slackware installation:
```
$ VISUAL=vi EDITOR=vi ansible-vault edit --vault-password-file=~/.vault_pass.txt testing/group_vars/db/vault 
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory
```
The above error resulted a lot of time wasted on finding the real issue. Problem is that I don't have vi installed so ansible doesn't find any editor to edit the vault file. The error it gives just doesn't point to the real issue. After adding existing editor to either VISUAL or EDITOR env variable the edit action works just fine.

##### STEPS TO REPRODUCE
Set EDITOR and VISUAL to non-existing editor and try to run ansible-vault edit action.

##### EXPECTED RESULTS
I'd expect some better error message like "unable to open <file>: no suitable editor found"

##### ACTUAL RESULTS
```
$ VISUAL=vi EDITOR=vi ansible-vault -vvv edit --vault-password-file=~/.vault_pass.txt testing/group_vars/db/vault 
ansible-vault 2.4.2.0
  config file = /home/tmy/.ansible.cfg
  configured module search path = [u'/home/tmy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-vault
  python version = 2.7.14 (default, Sep 22 2017, 11:31:09) [GCC 7.2.0]
Using /home/tmy/.ansible.cfg as config file
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-vault", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib64/python2.7/site-packages/ansible/cli/vault.py", line 228, in run
    self.execute()
  File "/usr/lib64/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib64/python2.7/site-packages/ansible/cli/vault.py", line 419, in execute_edit
    self.editor.edit_file(f)
  File "/usr/lib64/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 868, in edit_file
    self._edit_file_helper(filename, secret, existing_data=plaintext, force_save=False, vault_id=vault_id)
  File "/usr/lib64/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 756, in _edit_file_helper
    subprocess.call(self._editor_shell_command(tmp_path))
  File "/usr/lib64/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by zmyrgel** [comment]
Just tested this with latest ansible and this seems to be fixed so I'm closing this:
ERROR! Unable to execute the command "nano /tmp/tmpmMkeNc": [Errno 2] No such file or directory
