### ISSUE TITLE
rabbitmq_user throws "ValueError: need more than 1 value to unpack"

### ISSUE THREAD

**Issue by RushPu** [ansible/ansible#34863]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/rushpu/Program/Devops/Ansible/ansible.cfg
  configured module search path = [u'/Users/rushpu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rushpu/.pyenv/versions/2.7.12/envs/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/rushpu/.pyenv/versions/ansible/bin/ansible
  python version = 2.7.12 (default, Jul 26 2017, 16:16:30) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
ANSIBLE_SSH_RETRIES(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = 2
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = [u'/Users/rushpu/Program/Devops/Ansible/plugins/human_log.py']
DEFAULT_LOG_PATH(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = /Users/rushpu/Program/Devops/Ansible/log
DEFAULT_PRIVATE_KEY_FILE(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = /Users/rushpu/.ssh/id_rsa
DEFAULT_ROLES_PATH(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = [u'/Users/rushpu/Program/Devops/Ansible/roles']
DEFAULT_TIMEOUT(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = 20
HOST_KEY_CHECKING(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/rushpu/Program/Devops/Ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
System Version: macOS 10.12.6 (16G1114)
Kernel Version: Darwin 16.7.0
```

##### STEPS TO REPRODUCE

```yaml
- name: add rabbitmq user
  rabbitmq_user:
    user: "user"
    password: "password"
    vhost: /
    tags: monitoring
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
```

##### EXPECTED RESULTS

```
add a rabbitmq user
```

##### ACTUAL RESULTS

```
TASK [beoprabbitmq : add rabbitmq user] *******************************************************************************************************
task path: /Users/rushpu/Program/Devops/Ansible/roles/beoprabbitmq/tasks/main.yml:25
Using module file /Users/rushpu/.pyenv/versions/2.7.12/envs/ansible/lib/python2.7/site-packages/ansible/modules/messaging/rabbitmq_user.py
<hostip> ESTABLISH SSH CONNECTION FOR USER: root
<hostip> SSH: EXEC sshpass -d59 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/Users/rushpu/.ssh/id_rsa"' -o User=root -o ConnectTimeout=20 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r hostip '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<hostip> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 307, in <module>\n    main()\n  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 280, in main\n    if rabbitmq_user.get():\n  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 176, in get\n    self._permissions = self._get_permissions()\n  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 185, in _get_permissions\n    vhost, configure_priv, write_priv, read_priv = perm.split(\'\\t\')\nValueError: need more than 1 value to unpack\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 307, in <module>
    main()
  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 280, in main
    if rabbitmq_user.get():
  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 176, in get
    self._permissions = self._get_permissions()
  File "/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py", line 185, in _get_permissions
    vhost, configure_priv, write_priv, read_priv = perm.split('\t')
ValueError: need more than 1 value to unpack

fatal: [rabbitmq]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py\", line 307, in <module>\n    main()\n  File \"/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py\", line 280, in main\n    if rabbitmq_user.get():\n  File \"/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py\", line 176, in get\n    self._permissions = self._get_permissions()\n  File \"/tmp/ansible_PxsyvA/ansible_module_rabbitmq_user.py\", line 185, in _get_permissions\n    vhost, configure_priv, write_priv, read_priv = perm.split('\\t')\nValueError: need more than 1 value to unpack\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by Anbcorp** [comment]
Hi,

Just tested the proposed fix against v2.4.3.0 and as far as I can tell, the bug seems fixed.

We tested users with empty permissions and normal ones without any issue.

**Comment by shanemcd** [comment]
I'm able to reproduce this consistently:

```
root@rhel:~
 $ rabbitmqctl -q add_vhost test
root@rhel:~
 $ ansible -c local -i localhost, all -m rabbitmq_user -a 'user=test password="password" vhost="test" configure_priv=.* read_priv=.* write_priv=.* state=present force=yes'
localhost | SUCCESS => {
    "changed": true,
    "state": "present",
    "user": "test"
}
root@rhel:~
 $ rabbitmqctl -q list_user_permissions -p test test
test  .*  .*  .*
root@rhel:~
 $ ansible -c local -i localhost, all -m rabbitmq_user -a 'user=test password="password" vhost="test" configure_priv=.* read_priv=.* write_priv=.* state=present force=yes'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: need more than 1 value to unpack
localhost | FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lvMxKm/ansible_module_rabbitmq_user.py\", line 307, in <module>\n    main()\n  File \"/tmp/ansible_lvMxKm/ansible_module_rabbitmq_user.py\", line 288, in main\n    rabbitmq_user.get()\n  File \"/tmp/ansible_lvMxKm/ansible_module_rabbitmq_user.py\", line 176, in get\n    self._permissions = self._get_permissions()\n  File \"/tmp/ansible_lvMxKm/ansible_module_rabbitmq_user.py\", line 185, in _get_permissions\n    vhost, configure_priv, write_priv, read_priv = perm.split('\\t')\nValueError: need more than 1 value to unpack\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
root@rhel:~
 $ rabbitmqctl -q list_user_permissions -p test test

root@rhel:~
 $
```

In summary:

- Run `rabbitmq_user` once
  - Successful
- Check permissions
  - Looks ok
- Run `rabbitmq_user` again
  - Fails
- Check permissions again
  - Gone?

RabbitMQ 3.7.4 on RHEL 7.5. Ansible 2.5.1.

**Comment by shanemcd** [comment]
I've tested the patch at https://github.com/ansible/ansible/pull/35598 and it resolves my issue too.

**Comment by stevenscg** [comment]
I just ran into this issue on RabbitMQ 3.7.5 on RHEL 7.5. Ansible 2.5.4.

**Comment by nirsv** [comment]
I just ran into this issue on RabbitMQ 3.7.5 on CentOS Linux 7 Ansible 2.5.4.

**Comment by avanov** [comment]
Same issue, Ansible 2.5.4, RabbitMQ 3.7.6, OSX

**Comment by Akasurde** [comment]
resolved_by_pr #35598
