### ISSUE TITLE
Module 'service' error on Debian Lenny with svc_cmd

### ISSUE THREAD

**Issue by psvo** [ansible/ansible#3533]
Module service dies with exception - see below. Problem is caused probably by commit bcca609bc6693aec600e17db26c7c77f32ceb8d7 which references 
'svc_cmd' object attribute that can be None.

Error is triggered at least on Debian Lenny but probably other distributions could be affected too. Debian Squeeze works OK.

```
Traceback (most recent call last):
  File "service", line 2031, in <module>
    main()
  File "service", line 1075, in main
    service.get_service_status()
  File "service", line 450, in get_service_status
    rc, status_stdout, status_stderr = self.service_control()
  File "service", line 629, in service_control
    if self.svc_cmd.endswith('rc-service') and self.action == 'start' and self.crashed:
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Same problem also on another places:

```
 Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1373895034.66-231531890981472/service", line 2031, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1373895034.66-231531890981472/service", line 1075, in main
    service.get_service_status()
  File "/root/.ansible/tmp/ansible-1373895034.66-231531890981472/service", line 461, in get_service_status
    if self.svc_cmd.endswith("rc-service") and self.running is None:
AttributeError: 'NoneType' object has no attribute 'endswith'
```

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1373895217.93-217326251263220/service", line 2031, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1373895217.93-217326251263220/service", line 1081, in main
    (rc, out, err) = service.modify_service_state()
  File "/root/.ansible/tmp/ansible-1373895217.93-217326251263220/service", line 299, in modify_service_state
    return self.service_control()
  File "/root/.ansible/tmp/ansible-1373895217.93-217326251263220/service", line 639, in service_control
    elif self.svc_cmd.endswith('rc-service'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by mpdehaan** [comment]
First I've heard of this one so I'm a little unsure whether this is across
the board, or perhaps not many people are running Lenny?

Will take a look, thanks.

**Comment by mpdehaan** [comment]
Can you share the line from your ansible playbook you were using?

**Comment by psvo** [comment]
> Can you share the line from your ansible playbook you were using?

Following is enough to trigger this error (but happens with ansible-playbook too):

```
# cat hosts
webserver

# ansible webserver -u root -i hosts -m service -a 'name=apache2 state=started'
```

**Comment by mpdehaan** [comment]
Interesting.

Haven't heard this reported before and am quite surprised why that would be.

**Comment by psvo** [comment]
I looked at it in more detail...

Actual status on Lenny is:

```
self.svc_cmd is None
self.svc_initscript is /etc/init.d/apache2
```

And on Squeeze:

```
self.svc_cmd is /usr/sbin/service
self.svc_initscript is None
```

And that seems correct, because on Lenny none of searched binaries exists (except for update-rc.d, but that is irrelevant here). In Lenny "service" binary is installed by "admin/sysvconfig" or "admin/chkconfig" but none  of them is installed on our systems.

AFAIK native binary used by Debian systems is (or at least was) "invoke-rc.d", but it is not detected at all.

**Comment by jcbagneris** [comment]
I can confirm the problem, it happened to me recently on a Lenny host. Younger debians (squeeze etc.) are not affected
