### ISSUE TITLE
lvol: UnboundLocalError when removing a logical volume

### ISSUE THREAD

**Issue by fgtham** [ansible/ansible#3586]
When trying to remove a logical volume, I get the following exception:

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1374218591.54-6068069089969/lvol", line 1115, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1374218591.54-6068069089969/lvol", line 137, in main
    if size_opt == 'l':
UnboundLocalError: local variable 'size_opt' referenced before assignment
```

The problem seems to have been introduced with commit f000dcd.

This patch might fix the issue:

```
diff --git a/library/system/lvol b/library/system/lvol
index f3bc05d..b020101 100644
--- a/library/system/lvol
+++ b/library/system/lvol
@@ -96,6 +96,8 @@ def main():
     lv = module.params['lv']
     size = module.params['size']
     state = module.params['state']
+    size_opt = 'L'
+    size_unit = 'm'

     if state=='present' and not size:
         module.fail_json(msg="No size given.")
@@ -128,9 +130,7 @@ def main():
                 module.fail_json(msg="Size unit should be one of [bBsSkKmMgGtTpPeE]")
         # when no unit, megabytes by default
         elif size.isdigit():
-            size_unit = 'm'
             size = int(size)
-            size_opt = 'L'
         else:
             module.fail_json(msg="Bad size specification")
```

**Comment by srgvg** [comment]
@fgtham, can you propose your patch as a pull request, so we can test it?

**Comment by fgtham** [comment]
See issue #3590. Sorry for not sending a pull request in the first place :-/

**Comment by mpdehaan** [comment]
Since we have the pull request I am going to close this ticket just to keep the tracker orderly and we have the other ticket open (pull requests are tickets).

Thanks!
