### ISSUE TITLE
check_conditional fails with cannot concatenate 'str' and 'bool' error

### ISSUE THREAD

**Issue by electroniceagle** [ansible/ansible#3672]
When the conditional is an actual bool type, you get the following failure:

``` python

fatal: [omaha.nimbis.net] => Traceback (most recent call last):
  File "/Users/bschott/Source/ansible/lib/ansible/runner/__init__.py", line 367, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/bschott/Source/ansible/lib/ansible/runner/__init__.py", line 451, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/bschott/Source/ansible/lib/ansible/runner/__init__.py", line 532, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/Users/bschott/Source/ansible/lib/ansible/utils/__init__.py", line 167, in check_conditional
    presented = "{% if " + conditional + " %} True {% else %} False {% endif %}"
TypeError: cannot concatenate 'str' and 'bool' objects

```

Not sure if a str() around conditional generates the correct behavior, but I think it will if I understand what jinja2 compare does with the string.

``` bash
> /Users/bschott/Source/ansible/lib/ansible/utils/__init__.py(169)check_conditional()
-> presented = "{% if " + conditional + " %} True {% else %} False {% endif %}"
(Pdb) type(conditional)
<type 'bool'>
(Pdb) p conditional
True
(Pdb) str(conditional)
'True'
```

**Comment by electroniceagle** [comment]
This was the task that was failing.

```
- name: install passlib library
  pip: name=passlib
  when: password_protected
```

I will attach a pull request with the str() fix shortly.

**Comment by mpdehaan** [comment]
We actually already have a pull request to review, so I am going to close this duplicate ticket.

Thanks for reporting!

(I had proposed some unicode testing in addition.)
