### ISSUE TITLE
fact gathering: make things at least return partial facts on EL4

### ISSUE THREAD

**Issue by ethanzhan** [ansible/ansible#3680]
It looks like "-m setup" failed on some legacy boxes on RHEL 4 OS , the following error occurred. ( ansible version: 1.1/1.2 )

$ ansible -m setup all -i test.list -u root -c ssh
x.x.x.x | FAILED => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1374817839.87-128978320837516/setup", line 2419, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1374817839.87-128978320837516/setup", line 1581, in main
    data = run_setup(module)
  File "/root/.ansible/tmp/ansible-1374817839.87-128978320837516/setup", line 1526, in run_setup
    facts = ansible_facts()
  File "/root/.ansible/tmp/ansible-1374817839.87-128978320837516/setup", line 1516, in ansible_facts
    facts.update(Hardware().populate())
  File "/root/.ansible/tmp/ansible-1374817839.87-128978320837516/setup", line 421, in populate
    self.get_device_facts()
  File "/root/.ansible/tmp/ansible-1374817839.87-128978320837516/setup", line 548, in get_device_facts
    m = re.match("._?([(._)])", scheduler)
  File "/usr/local/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

test.list.example:
x.x.x.x  ansible_python_interpreter=/usr/local/bin/python  ( test on python 2.7)

**Comment by mpdehaan** [comment]
As per the mailing list, this is an end of life'd OS, but I think the fact modules should gather at least partial fact data here, so you don't have to turn off fact gathering.

This change will likely be applied only to 1.3 devel as I'm not planning a 1.2.3 point release.

**Comment by jctanner** [comment]
I was able to reproduce the error with all1.2.x branches.The issue appears to have been resolved in 1.3.x.
