### ISSUE TITLE
ansible stacktrace

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#3730]
simple ansible facts now stack trace:

```
ansible -m setup -c local -i ~/hosts 127.0.0.1
```

127.0.0.1 | FAILED => Traceback (most recent call last):
  File "/home/bcoca/work/ansible/lib/ansible/runner/**init**.py", line 367, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 389, in _executor_internal
    host_variables = self.inventory.get_variables(host)
  File "/home/bcoca/work/ansible/lib/ansible/inventory/__init__.py", line 284, in get_variables
    self._vars_per_host[hostname] = self._get_variables(hostname)
  File "/home/bcoca/work/ansible/lib/ansible/inventory/__init__.py", line 294, in _get_variables
    vars_results = [ plugin.run(host) for plugin in self._vars_plugins ]
  File "/home/bcoca/work/ansible/lib/ansible/inventory/vars_plugins/group_vars.py", line 43, in run
    self.pb_basedir = os.path.abspath(inventory.playbook_basedir())
  File "/usr/lib/python2.7/posixpath.py", line 343, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 53, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

bisect showed 16efb45735899737aacc106f89014ee9551fd625 as culprit

**Comment by bcoca** [comment]
fixed by 0335d05f437eb59bcb77a58ef7819562f298ba79
