### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by rylach** [ansible/ansible#389]
Hi.

After action

template src=templates/etc/postgresql/8.3/master/pg_hba.conf.j2 dest=/etc/postgresql/8.3/master/pg_hba.conf owner=postgres group=postgres mode=0640

I get a traceback:

TASK: [Generate pg_hba.conf from template - 8.3/master] ********\*                                                                                                                               

ok: [exxxxxxxx] => template src=/var/tmp/ansible.QuLkMY/source dest=/etc/postgresql/8.3/master/pg_hba.conf                                                                                      

Traceback (most recent call last):  
  File "/home/ansible/ansible-src/bin/ansible-playbook", line 104, in <module>  
    sys.exit(main(sys.argv[1:]))  
  File "/home/ansible/ansible-src/bin/ansible-playbook", line 85, in main  
    pb.run()  
  File "/home/ansible/ansible-src/lib/ansible/playbook.py", line 246, in run  
    self._run_play(pattern)  
  File "/home/ansible/ansible-src/lib/ansible/playbook.py", line 556, in _run_play  
    triggered_by = task.get('run', None)  
AttributeError: 'str' object has no attribute 'get'

(it seems not onle me get this error, see http://pastebin.com/y5c7FMaF)

**Comment by rylach** [comment]
My mistake, sorry (doubled 'handlers:') line.
