### ISSUE TITLE
ec2 module returns with index out of range

### ISSUE THREAD

**Issue by electroniceagle** [ansible/ansible#3980]
This task worked cleanly 10 previous times, but I suspect that EC2 returned zero instances on my request.

```
tasks:
    - name: Launch an instance
      local_action: 
          module: ec2
          keypair: ${keypair}
          aws_access_key: ${nimbis_dev_aws_access_key}
          aws_secret_key: ${nimbis_dev_aws_secret_key}
          region: 'us-east-1'
          group: ${security_group}
          instance_type: ${instance_type}
          image: ${ami.stdout}
          wait: yes
          count: 1
      register: ec2
```

Here is the traceback:

```
TASK: [Launch an instance] **************************************************** 
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/bschott/.ansible/tmp/ansible-1377965270.64-163256394061380/ec2", line 1549, in <module>
    main()
  File "/Users/bschott/.ansible/tmp/ansible-1377965270.64-163256394061380/ec2", line 612, in main
    (instance_dict_array, new_instance_ids, changed) = create_instances(module, ec2)
  File "/Users/bschott/.ansible/tmp/ansible-1377965270.64-163256394061380/ec2", line 461, in create_instances
    this_res = res_list[0]
IndexError: list index out of range

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Can you share on how you managed to reproduce this?

(Does it occur again repeatedly, etc?)

**Comment by electroniceagle** [comment]
It has only happened once for me so far out of 10 or 12 attempts, but looking at the code it is possible that get_all_instances returns an empty list.  I have seen similar race conditions with boto before if you get unlucky and hit a stale cache on the amazon side.

```
# wait here until the instances are up
        res_list = res.connection.get_all_instances(instids)
        this_res = res_list[0]  <--- the list is empty because instance still in early setup
        num_running = 0
        wait_timeout = time.time() + wait_timeout
        while wait and wait_timeout > time.time() and num_running < len(instids):
            res_list = res.connection.get_all_instances(instids)
            this_res = res_list[0]
            num_running = len([ i for i in this_res.instances if i.state=='running' ])
            time.sleep(5)
```

I think a little refactoring and checking for an empty list as part of the while wait loop would make this robust.  Basically, if the instance is missing and you have an id it should appear at some point, otherwise you should time out and assume ec2 lost it.

Also noticed that get_all_instances is deprecated.  

```
get_all_instances(instance_ids=None, filters=None)
Retrieve all the instance reservations associated with your account.

This method’s current behavior is deprecated in favor of get_all_reservations(). A future major release will change get_all_instances() to return a list of boto.ec2.instance.Instance objects as its name suggests. To obtain that behavior today, use get_only_instances().

Parameters: 
instance_ids (list) – A list of strings of instance IDs
filters (dict) – Optional filters that can be used to limit the results returned. Filters are provided in the form of a dictionary consisting of filter names as the key and filter values as the value. The set of allowable filter names/values is dependent on the request being performed. Check the EC2 API guide for details.
Return type:    
list
Returns:    
A list of boto.ec2.instance.Reservation
```
- http://boto.readthedocs.org/en/latest/ref/ec2.html

**Comment by jimi-c** [comment]
Could you send us a pull request with the above fixes? Thanks!
