### ISSUE TITLE
ImportError: cannot import name display

### ISSUE THREAD

**Issue by lsemel** [ansible/ansible#4066]
I just installed Ansible via pip into a fresh virtualenv on OS X, which contains the following:
Jinja2==2.7.1
MarkupSafe==0.18
PyYAML==3.10
ansible==1.2.3
paramiko==1.11.0
pycrypto==2.6
wsgiref==0.1.2

When I run ansible-playbook with no arguments, I get this error:

Traceback (most recent call last):
  File "/var/www/virtualenvs/myvirtualenv/bin/ansible-playbook", line 31, in <module>
    from ansible.callbacks import display
ImportError: cannot import name display

'ansible' fails similarly:

Traceback (most recent call last):
  File "/var/www/virtualenvs/myvirtualenv/bin/ansible", line 149, in <module>
    callbacks.display("", log_only=True)
AttributeError: 'module' object has no attribute 'display'

**Comment by lsemel** [comment]
Error on my end - I had run the hacking env setup script from another version of ansible in the same terminal beforehand.
