### ISSUE TITLE
cloudfront_origin_access_identity error when CloudFrontOriginAccessIdentityList is empty

### ISSUE THREAD

**Issue by adrianrise** [ansible/ansible#40668]
##### SUMMARY
We were trying to create an OAI with the module "cloudfront_origin_access_identity" and found a problem when there are no OAI's created yet.

When the list is empty ot returns an error, but we tried creating an OAI manually and rerunning again the module and it works.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

cloudfront_origin_access_identity

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /Users/username/repos/bigfinite/Ansibilyzer/ansible.cfg
  configured module search path = [u'/Users/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/Users/username/repos/ansible.cfg) = [u'/Users/username/repos/inventory/hosts']
```
##### OS / ENVIRONMENT

MAC OS High Sierra 10.13.4

##### STEPS TO REPRODUCE

```
  - name: create an origin access identity
    cloudfront_origin_access_identity:
      state: present
      caller_reference: this is an example reference
      comment: this is an example comment
      profile: "{{ variables.profile }}"
      region: "{{ variables.region }}"
    register: origin_access_identity
```

##### EXPECTED RESULTS

We expect to create an OAI with the given values.

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_module_cloudfront_origin_access_identity.py", line 284, in <module>
    main()
  File "/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_module_cloudfront_origin_access_identity.py", line 262, in main
    origin_access_identity_id = validation_mgr.validate_origin_access_identity_id_from_caller_reference(caller_reference)
  File "/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_module_cloudfront_origin_access_identity.py", line 221, in validate_origin_access_identity_id_from_caller_reference
    origin_access_identities = self.__cloudfront_facts_mgr.list_origin_access_identities()
  File "/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_modlib.zip/ansible/module_utils/aws/cloudfront_facts.py", line 96, in list_origin_access_identities
KeyError: 'CloudFrontOriginAccessIdentityList'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_module_cloudfront_origin_access_identity.py\", line 284, in <module>\n  main()\n  File \"/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_module_cloudfront_origin_access_identity.py\", line 262, in main\n    origin_access_identity_id = validation_mgr.validate_origin_access_identity_id_from_caller_reference(caller_reference)\n  File \"/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_module_cloudfront_origin_access_identity.py\", line 221, in validate_origin_access_identity_id_from_caller_reference\n    origin_access_identities = self.__cloudfront_facts_mgr.list_origin_access_identities()\n  File \"/var/folders/w2/9tfn65155qxfkh2d8r_hhq5c0000gn/T/ansible_MCbyGf/ansible_modlib.zip/ansible/module_utils/aws/cloudfront_facts.py\", line 96, in list_origin_access_identities\nKeyError: 'CloudFrontOriginAccessIdentityList'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by adrianrise** [comment]
@wilvk Does this error sounds to you?

**Comment by jonatcorus** [comment]
This happens when there are no AOIs in the account.

changing the offending line 96, to this fixes it:
`
            result = paginator.paginate().build_full_result().get('CloudFrontOriginAccessIdentityList', {})
`

**Comment by wilvk** [comment]
thanks for the report @jonathan-willis , that seems odd. cc @willthames

**Comment by texdc** [comment]
@wilvk @willthames What is the progress on this issue?

**Comment by texdc** [comment]
I still have this error on 2.7.10:
```
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1554844509.52-18757333838917/AnsiballZ_cloudfront_origin_access_identity.py", line 113, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1554844509.52-18757333838917/AnsiballZ_cloudfront_origin_access_identity.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1554844509.52-18757333838917/AnsiballZ_cloudfront_origin_access_identity.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/__main__.py", line 284, in <module>
  File "/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/__main__.py", line 262, in main
  File "/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/__main__.py", line 221, in validate_origin_access_identity_id_from_caller_reference
  File "/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/ansible_cloudfront_origin_access_identity_payload.zip/ansible/module_utils/aws/cloudfront_facts.py", line 96, in list_origin_access_identities
KeyError: 'CloudFrontOriginAccessIdentityList'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1554844509.52-18757333838917/AnsiballZ_cloudfront_origin_access_identity.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1554844509.52-18757333838917/AnsiballZ_cloudfront_origin_access_identity.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1554844509.52-18757333838917/AnsiballZ_cloudfront_origin_access_identity.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/__main__.py\", line 284, in <module>\n  File \"/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/__main__.py\", line 262, in main\n  File \"/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/__main__.py\", line 221, in validate_origin_access_identity_id_from_caller_reference\n  File \"/tmp/ansible_cloudfront_origin_access_identity_payload_a6f9Sl/ansible_cloudfront_origin_access_identity_payload.zip/ansible/module_utils/aws/cloudfront_facts.py\", line 96, in list_origin_access_identities\nKeyError: 'CloudFrontOriginAccessIdentityList'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by willthames** [comment]
git blame suggests:

```
93cd0502505 (Jonathan    2018-09-01 22:17:25 -0400  96)             result = paginator.paginate().build_full_result().get('CloudFrontOriginAccessIdentityList', {})
```

so that line hasn't changed in over a year and a half (the `KeyError` is impossible with that change)

I can only surmise that you're somehow using an older ansible than you think, or that you're somehow picking up an older version of cloudfront_facts

Can you run `python_requirements_facts` module just before the failing task?

**Comment by texdc** [comment]
@willthames I believe the error was due to not having _any_ OAIs in the account.  After adding one manually, the module behaved as expected.  Yes, I am using  Ansible `2.7.10`.  Here's the output from `python_requirements_facts`:
```
Wednesday 10 April 2019  13:45:52 +0000 (0:00:00.129)       0:00:03.793 ******* 
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: socouser
<localhost> EXEC sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1554903952.31-125791182437206 `" && echo ansible-tmp-1554903952.31-125791182437206="` echo /tmp/ansible-tmp-1554903952.31-125791182437206 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/python_requirements_facts.py
<localhost> PUT /tmp/ansible-local-1xAhVYc/tmpxhn_AQ TO /tmp/ansible-tmp-1554903952.31-125791182437206/AnsiballZ_python_requirements_facts.py
<localhost> EXEC sh -c 'chmod u+x /tmp/ansible-tmp-1554903952.31-125791182437206/ /tmp/ansible-tmp-1554903952.31-125791182437206/AnsiballZ_python_requirements_facts.py && sleep 0'
<localhost> EXEC sh -c '/usr/bin/python /tmp/ansible-tmp-1554903952.31-125791182437206/AnsiballZ_python_requirements_facts.py && sleep 0'
<localhost> EXEC sh -c 'rm -f -r /tmp/ansible-tmp-1554903952.31-125791182437206/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "dependencies": [
                "boto3", 
                "botocore"
            ]
        }
    }, 
    "mismatched": {}, 
    "not_found": [], 
    "python": "/usr/bin/python", 
    "python_system_path": [
        "/tmp/ansible_python_requirements_facts_payload_12jb1Y/ansible_python_requirements_facts_payload.zip", 
        "/usr/lib/python27.zip", 
        "/usr/lib/python2.7", 
        "/usr/lib/python2.7/plat-linux2", 
        "/usr/lib/python2.7/lib-tk", 
        "/usr/lib/python2.7/lib-old", 
        "/usr/lib/python2.7/lib-dynload", 
        "/usr/lib/python2.7/site-packages"
    ], 
    "python_version": "2.7.15 (default, Aug 22 2018, 13:24:18) \n[GCC 6.4.0]", 
    "valid": {
        "boto3": {
            "desired": null, 
            "installed": "1.4.8"
        }, 
        "botocore": {
            "desired": null, 
            "installed": "1.12.130"
        }
    }
}
```

**Comment by willthames** [comment]
But the bug fix was to address the lack of OAIs in an account. I don't understand how your ansible run hasn't picked up the bug fix!

Can you raise a new issue for this (that will ensure we get all the information from your system).

I'd like to see that task being run with `-vvv` so we get all the preceding python lines. The fact that you can even run `python_requirements_facts` suggests you're definitely on 2.7.

Do you have a `module_utils/aws/cloudfront_facts.py` in your local directory? 

Can you also do `tail -n +96 /usr/lib/python2.7/site-packages/ansible/module_utils/aws/cloudfront_facts.py | head -1`

**Comment by willthames** [comment]
Please add the required information and the usual issue template information to the new ticket, not this one :)

**Comment by texdc** [comment]
> But the bug fix was to address the lack of OAIs in an account. I don't understand how your ansible run hasn't picked up the bug fix!

Yeah, I don't either.  That's why I've reached out for assistance.  I'll add the new issue and all the data you've requested asap.  Thanks.
