### ISSUE TITLE
[rpm_key] NameError: global name 'is_keyid' is not defined

### ISSUE THREAD

**Issue by hnakamur** [ansible/ansible#4068]
I got an error when I ran the rpm_key module.
I am using the latest commit 150dd230cc9364fa93799116c4b478bc01271b03.

```
$ ansible-playbook cent64.yml 

PLAY [cent64] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [cent64]

TASK: [check epel repository is installed] ************************************ 
ok: [cent64]

TASK: [install epel repository] *********************************************** 
skipping: [cent64]

TASK: [install epel key] ****************************************************** 
failed: [cent64] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1378747647.04-60165225372001/rpm_key", line 1130, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1378747647.04-60165225372001/rpm_key", line 195, in main
    RpmKey(module)
  File "/home/vagrant/.ansible/tmp/ansible-1378747647.04-60165225372001/rpm_key", line 89, in __init__
    elif is_keyid(key):
NameError: global name 'is_keyid' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/hnakamur/cent64.retry

cent64                     : ok=2    changed=0    unreachable=0    failed=1   

```

Here is my role task file. roles/epel/tasks/main.yml

``` yaml

---

- name: check epel repository is installed
  shell: >
    rpm -q epel-release > /dev/null; echo $?
  register: result
  changed_when: False

- name: install epel repository
  yum: >
    name=http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
    state=present
  when: result.stdout != "0"

- name: install epel key
  rpm_key: >
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
    state=present
```

You can use the below command as a workaround at the moment.

```
- name: install epel key
  command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
```

I'm using Python version is 2.7.5 installed with homebrew.

**Comment by jimi-c** [comment]
The above patch should resolve this issue for you. Let me know if it doesn't.

Thanks!

**Comment by hnakamur** [comment]
It works now.
@jimi1283 Thanks!
