### ISSUE TITLE
pip install ansible errors SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kandulaziot** [ansible/ansible#40836]
##### SUMMARY
I am trying to install Ansible by compiling the Python code on a Vagrant cloud image as below.
Image details:
config.vm.define "db1" do |db|
    db.vm.box = "nrel/CentOS-6.6-x86_64"
    db.vm.box_version = "1.0.0"
    db.vm.hostname = "db1"

what has been done so far:
yum install gcc
yum install python-setuptools
easy_install pip
yum install python-devel

when using _sudo pip install ansible_ i get a SyntaxError: invalid syntax.
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/pip-10.0.1-py2.6.egg/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/lib/python2.6/site-packages/pip-10.0.1-py2.6.egg/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/lib/python2.6/site-packages/pip-10.0.1-py2.6.egg/pip/_internal/index.py", line 526
    {str(c.version) for c in all_candidates},
                      ^
SyntaxError: invalid syntax
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.5.2
```

##### OS / ENVIRONMENT

Using nrel/CentOS-6.6-x86_64 from Vagrant cloud
##### STEPS TO REPRODUCE

yum install gcc
yum install python-setuptools
easy_install pip
yum install python-devel

```yaml

```

##### ACTUAL RESULTS

````
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/pip-10.0.1-py2.6.egg/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/lib/python2.6/site-packages/pip-10.0.1-py2.6.egg/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/lib/python2.6/site-packages/pip-10.0.1-py2.6.egg/pip/_internal/index.py", line 526
    {str(c.version) for c in all_candidates},
                      ^
SyntaxError: invalid syntax

```

**Comment by Akasurde** [comment]
@kandulaziot Thanks for reporting this issue. Python 2.6 support is dropped for pip 10. Please refer - https://pip.pypa.io/en/stable/news/#deprecations-and-removals. Also, https://github.com/pypa/pip/issues/5152

Make sure you do `pip==9.0.3` on CentOS/RHEL 6.

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
