### ISSUE TITLE
regression with local temp locations in 2.5.4

### ISSUE THREAD

**Issue by mwhahaha** [ansible/ansible#41808]
##### SUMMARY
local temp directory not properly evaluated if the user does not have an existent home directory. In 2.4.2, the HOME environment variable could be used to override the location of the home directory for the user. In 2.5.4+, neither HOME nor ANSIBLE_LOCAL_TEMP work.

Might be related to https://github.com/ansible/ansible/commit/864fd7c53e45703554bb6de608fe13a2200b6aa0

Use Case: we're calling ansible-playbook via a service and the service user is configured with /sbin/nologin and the home directory doesn't exist/have permissions for the user.

##### ISSUE TYPE
 Bug Report / Regression

##### ANSIBLE VERSION

```
2.5.4
```

##### CONFIGURATION

```
 [root@undercloud-0 tmp]# su - foobar -c "ansible-config dump --only-changed"
su: warning: cannot change directory to /home/nope: No such file or directory
 [WARNING]: Unable to set correct type for configuration entry: DEFAULT_LOCAL_TMP

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

RHEL 7.5

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  name: Gather facts from undercloud
  gather_facts: yes
  become: false
  tags:
    - facts
```

useradd -r -d /home/DOESNOTEXIST -s /bin/bash foobar
su - foobar -c "HOME=/tmp/foobaz ansible-playbook /tmp/foo.yaml"

##### EXPECTED RESULTS

Should run without a permissions error because it should honor HOME for temp directory.  Using ANSIBLE_LOCAL_TEMP would also be acceptable, but currently neither work.

Example with 2.4.2
```
 [root@undercloud-0 tmp]# su - foobar -c "HOME=/tmp/foobaz ansible-playbook -vvv /tmp/foo.yaml"
su: warning: cannot change directory to /home/nope: No such file or directory
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/tmp/foobaz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: foo.yaml **************************************************************************************************************************************************************************************************
1 plays in /tmp/foo.yaml

PLAY [Gather facts from undercloud] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: foobar
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105 `" && echo ansible-tmp-1529605061.24-53817194095105="` echo /tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpV6ZZ48 TO /tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105/ /tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105/setup.py; rm -rf "/tmp/foobaz/.ansible/tmp/ansible-tmp-1529605061.24-53817194095105/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

```
 [root@undercloud-0 tmp]# su - foobar -c "HOME=/tmp/foobaz ansible-playbook -vvv /tmp/foo.yaml"
su: warning: cannot change directory to /home/nope: No such file or directory
ansible-playbook 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/tmp/foobaz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: foo.yaml **************************************************************************************************************************************************************************************************
1 plays in /tmp/foo.yaml

PLAY [Gather facts from undercloud] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************
task path: /tmp/foo.yaml:1
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: foobar
<127.0.0.1> EXEC /bin/sh -c 'echo ~foobar && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/nope/.ansible/tmp/ansible-tmp-1529605123.57-209450258881066 `" && echo ansible-tmp-1529605123.57-209450258881066="` echo /home/nope/.ansible/tmp/ansible-tmp-1529605123.57-209450258881066 `" ) && sleep 0'
fatal: [localhost]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/nope/.ansible/tmp/ansible-tmp-1529605123.57-209450258881066 `\" && echo ansible-tmp-1529605123.57-209450258881066=\"` echo /home/nope/.ansible/tmp/ansible-tmp-1529605123.57-209450258881066 `\" ), exited with result 1", 
    "unreachable": true
}
	to retry, use: --limit @/tmp/foo.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0  
```

**Comment by wknapik** [comment]
Just wasted an hour trying to figure this out (ansible 2.5.5).
This matters when calling ansible from a container.

**Comment by sivel** [comment]
With a local connection, `ANSIBLE_REMOTE_TMP` is the value used for determining the tempdir of where files will land when copied through the connection plugin.

`ANSIBLE_LOCAL_TEMP` is only used for the files that the controller itself creates.

So with the example of `ANSIBLE_LOCAL_TEMP=/tmp` and `ANSIBLE_REMOTE_TMP=/var/tmp`, ansible would build the ansiballz file in `/tmp`, but copy it to `/var/tmp` before execution.

Effectively the change that was made that impacts this was from https://github.com/ansible/ansible/pull/36755

In that PR we changed using `echo ~` to `echo ~remote_user`.  Because of this change, the `HOME` env var no longer impacts that evaluation.

I do not believe use of `HOME` to impact tmp dir location was ever recommended.  As mentioned above using `ANSIBLE_LOCAL_TEMP` and `ANSIBLE_REMOTE_TMP` are recommended.

**Comment by mwhahaha** [comment]
Yea I tried setting ANSIBLE_LOCAL_TEMP and it's not working either. ANSIBLE_REMOTE_TMP does work but impacts the other tasks which is not what I want. I'm ok if we have to set ANSIBLE_LOCAL_TEMP but it doesn't appear to work

**Comment by mwhahaha** [comment]
The use case is that the local system (where the service is running) needs a different path than the remote systems (which have valid users, etc)

**Comment by sivel** [comment]
You can set `ansible_remote_tmp` (lowercase variable from inventory or other vars) on a per host basis.

As described local_tmp is only used for the location of where the controller places files.  remote_tmp dictates where the connection plugin copies files to.

**Comment by mwhahaha** [comment]
So in our case the inventory is generated in a different external place to the invoking script so it's more painful to set this on the inventory than via en environmental var. I'll see if we can work around that, but this is not ideal.

**Comment by sivel** [comment]
It is also possible that you could set `ANSIBLE_REMOTE_TMP` to `$HOME/.ansible/tmp` instead of the default `~/.ansible/tmp`. I have not tested this specific scenario, but in theory should work.

We made these changes to remove dependence on environments that may not be available such as with cloud-init or solaris, where `echo ~` fails in those environments, and produces a literal `~`

**Comment by mwhahaha** [comment]
ANSIBLE_REMOTE_TMP isn't working either.

```
# su - foobar -c "ANSIBLE_REMOTE_TMP='/tmp/foobar' ansible-playbook -vvv /tmp/foo.yaml"
su: warning: cannot change directory to /home/nope: No such file or directory
ansible-playbook 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nope/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Unable to set correct type for configuration entry: DEFAULT_LOCAL_TMP

Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: foo.yaml **************************************************************************************************************************************************************************************************
1 plays in /tmp/foo.yaml

PLAY [Gather facts from undercloud] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************
task path: /tmp/foo.yaml:1
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 561, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 709, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 165, in _configure_module
    environment=final_environment)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 910, in modify_module
    environment=environment)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 712, in _find_module_utils
    os.makedirs(lookup_path)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '~/.ansible/tmp'

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/tmp/foo.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin (<ansible.plugins.callback.json_error.CallbackModule object at 0x7f3f3d227050>): [Errno 13] Permission denied: 'ansible-errors.json'

Callback Exception: 
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 374, in send_callback
    method(*new_args, **kwargs)
   File "/usr/share/ansible/plugins/callback/json_error.py", line 56, in v2_playbook_on_stats
    with open(self.log_file, 'w') as f:
```

**Comment by sivel** [comment]
I notice the following in your output:

```
[WARNING]: Unable to set correct type for configuration entry: DEFAULT_LOCAL_TMP
```

So it seems like your config for `ANSIBLE_LOCAL_TEMP` is not being applied.

**Comment by mwhahaha** [comment]
So ignore the ANSIBLE_REMOTE_TMP comment, it does work. I must have had something else in the environment loaded. I reran it and it works. The DEFAULT_LOCAL_TMP doesn't affect this. If i set ANSIBLE_LOCAL_TEMP that goes away but you still hit the home dir problems.  IMHO ANSIBLE_LOCAL_TEMP should be used for local connections and not the remote_tmp, that's the confusing part

**Comment by sivel** [comment]
I will note that I actually tried to make that change for the 2.6 release, and forcing the local connection to use `ANSIBLE_LOCAL_TEMP` caused a number of test failures in our test cases, which indicates that it would impact a significant portion of our users, so no further attempt was made.

**Comment by samdoran** [comment]
I submitted [Change 577550](https://review.openstack.org/#/c/577550/) to fix the original issue.

**Comment by samdoran** [comment]
[Change 577544](https://review.openstack.org/#/c/577544) also fixes this
