### ISSUE TITLE
Error when sending Jabber message to a specific user, message does get send (v1.3.2)

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4183]
When sending a message to a Jabber user I get an error and an exception is thrown in the Jabber task, yet the message does get delivered succesfully.
- Ansible version: 1.3.2
- xmpppy version: 0.5.0 rc1
## Steps to reproduce
1. Run a jabber task, mine is the following: `[jabber user=ansible@jabber.example.tld password=<hidden> to=xeross@jabber.example.tld msg="[{{ansible_hostname}}] DNS Updated"]`
2. Exception gets thrown and task is set as failed but message does get sent
## Actual Exception

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1379669192.66-81486148042822/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
```
## Full Log

```
TASK: [jabber user=ansible@jabber.example.tld password=<hidden> to=xeross@jabber.example.tld msg="[{{ansible_hostname}}] DNS Updated"] *** 
fatal: [aragorn] => failed to parse: Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /usr/lib/python2.7/site-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x1a6d7a0> into <xmpp.client.Client instance at 0x1a6d6c8>
DEBUG: socket       warn  An error occurred while looking up _xmpp-client._tcp.jabber.example.tld
DEBUG: socket       start Successfully connected to remote host ('jabber.example.tld', 5222)
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x1a6d7e8> into <xmpp.client.Client instance at 0x1a6d6c8>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x1a6d7e8>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.tld" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='4131806919' from='jabber.example.tld' version='1.0' xml:lang='en'>
DEBUG: socket       got   <stream:features>
  <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  <mechanism>DIGEST-MD5</mechanism>
  <mechanism>PLAIN</mechanism>
  <mechanism>SCRAM-SHA-1</mechanism>
  </mechanisms>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='yy7di5kE0syuCXOQTXNBTclpNTo='/>
  <register xmlns='http://jabber.org/features/iq-register'/>
  </stream:features>
DEBUG: dispatcher   warn  Unknown stanza: features
DEBUG: dispatcher   ok    Dispatching unknown stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-sasl', u'http://jabber.org/protocol/caps', u'http://jabber.org/features/iq-register'] id->None
DEBUG: tls          start Plugging <xmpp.transports.TLS instance at 0x1aa7710> into <xmpp.client.Client instance at 0x1a6d6c8>
DEBUG: tls          warn  TLS unsupported by remote server.
DEBUG: sasl         start Plugging <xmpp.auth.SASL instance at 0x1aa7758> into <xmpp.client.Client instance at 0x1a6d6c8>
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x1aa7758>> for "challenge" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering namespace "urn:ietf:params:xml:ns:xmpp-sasl"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "challenge" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x1aa7758>> for "failure" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "failure" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x1aa7758>> for "success" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "success" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: socket       sent  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="DIGEST-MD5" />
DEBUG: socket       got   <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>bm9uY2U9IjUyOTk3MDE4OCIscW9wPSJhdXRoIixjaGFyc2V0PXV0Zi04LGFsZ29yaXRobT1tZDUtc2Vzcw==</challenge>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/challenge stanza
DEBUG: dispatcher   ok    Dispatching challenge stanza with type-> props->[] id->None
DEBUG: sasl         ok    Got challenge:nonce="529970188",qop="auth",charset=utf-8,algorithm=md5-sess
DEBUG: socket       sent  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Y2hhcnNldD11dGYtOCx1c2VybmFtZT0iYW5zaWJsZSIscmVhbG09ImphYmJlci50Y2ZuZXQub3JnIixub25jZT0iNTI5OTcwMTg4IixuYz0wMDAwMDAwMSxjbm9uY2U9ImQ1MGY0MDE3MzlkZGQyMzIyY2Y5MDU3OWVkMDU2ZGE5NjcyOTdmMzE2ZWJlYWM0MGEiLGRpZ2VzdC11cmk9InhtcHAvamFiYmVyLnRjZm5ldC5vcmciLHJlc3BvbnNlPTY0YTMyYTM0YTA1NDViMmQ1NDU1MjYyMDhlZWM0ZGVjLHFvcD1hdXRo</response>
DEBUG: socket       got   <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cnNwYXV0aD1mMjdiNDBkNTE2ODY5YTgzNWJkZTRhOGU2YTA4NTk3Yw==</challenge>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/challenge stanza
DEBUG: dispatcher   ok    Dispatching challenge stanza with type-> props->[] id->None
DEBUG: sasl         ok    Got challenge:rspauth=f27b40d516869a835bde4a8e6a08597c
DEBUG: socket       sent  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl" />
DEBUG: socket       got   <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/success stanza
DEBUG: dispatcher   ok    Dispatching success stanza with type-> props->[] id->None
DEBUG: sasl         ok    Successfully authenticated with remote server.
DEBUG: dispatcher   stop  Plugging <xmpp.dispatcher.Dispatcher instance at 0x1a6d7e8> out of <xmpp.client.Client instance at 0x1a6d6c8>.
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x1aa7cf8> into <xmpp.client.Client instance at 0x1a6d6c8>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x1aa7cf8>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.tld" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: bind         start Plugging <xmpp.auth.Bind instance at 0x1aa7b48> into <xmpp.client.Client instance at 0x1a6d6c8>
DEBUG: dispatcher   info  Registering handler <bound method Bind.FeaturesHandler of <xmpp.auth.Bind instance at 0x1aa7b48>> for "features" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "features" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='2350727640' from='jabber.example.tld' version='1.0' xml:lang='en'>
DEBUG: socket       got   <stream:features>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>
  <session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='yy7di5kE0syuCXOQTXNBTclpNTo='/>
  <register xmlns='http://jabber.org/features/iq-register'/>
  </stream:features>
DEBUG: dispatcher   ok    Got http://etherx.jabber.org/streams/features stanza
DEBUG: dispatcher   ok    Dispatching features stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-bind', u'urn:ietf:params:xml:ns:xmpp-session', u'http://jabber.org/protocol/caps', u'http://jabber.org/features/iq-register'] id->None
DEBUG: socket       sent  <iq type="set" id="1">
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind">
  <resource>Ansible</resource>
  </bind>
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:1 with timeout 25...
DEBUG: socket       got   <iq id='1' type='result'>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'>
  <jid>ansible@jabber.example.tld/Ansible</jid>
  </bind>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[u'urn:ietf:params:xml:ns:xmpp-bind'] id->1
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully bound ansible@jabber.example.tld/Ansible.
DEBUG: socket       sent  <iq type="set" id="2">
  <session xmlns="urn:ietf:params:xml:ns:xmpp-session" />
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:2 with timeout 25...
DEBUG: socket       got   <iq type='result' id='2'>
  <session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[u'urn:ietf:params:xml:ns:xmpp-session'] id->2
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully opened session.
DEBUG: socket       sent  <presence id="3" />
DEBUG: socket       sent  <message to="xeross@jabber.example.tld" type="chat" id="4">
  <body>[aragorn] DNS Updated</body>
  </message>
DEBUG: socket       sent  </stream:stream>
DEBUG: socket       got   <presence from='ansible@jabber.example.tld/Ansible' to='ansible@jabber.example.tld/Ansible' id='3'/>
DEBUG: dispatcher   ok    Got jabber:client/presence stanza
DEBUG: dispatcher   ok    Dispatching presence stanza with type-> props->[] id->3
DEBUG: socket       got   </stream:stream>
DEBUG: socket       error Socket error while receiving data
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1379669192.66-81486148042822/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
DEBUG: client       stop  Disconnect detected
DEBUG: socket       error Socket operation failed
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1379669192.66-81486148042822/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
{"msg": "[aragorn] DNS Updated", "to": "xeross@jabber.example.tld", "changed": false, "user": "ansible"}

fatal: [server01] => failed to parse: Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /usr/lib/python2.7/site-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x993de8c> into <xmpp.client.Client instance at 0x993d4cc>
DEBUG: socket       warn  An error occurred while looking up _xmpp-client._tcp.jabber.example.tld
DEBUG: socket       start Successfully connected to remote host ('jabber.example.tld', 5222)
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x9942a8c> into <xmpp.client.Client instance at 0x993d4cc>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x9942a8c>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.tld" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='1162008467' from='jabber.example.tld' version='1.0' xml:lang='en'>
DEBUG: socket       got   <stream:features>
  <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  <mechanism>DIGEST-MD5</mechanism>
  <mechanism>PLAIN</mechanism>
  <mechanism>SCRAM-SHA-1</mechanism>
  </mechanisms>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='yy7di5kE0syuCXOQTXNBTclpNTo='/>
  <register xmlns='http://jabber.org/features/iq-register'/>
  </stream:features>
DEBUG: dispatcher   warn  Unknown stanza: features
DEBUG: dispatcher   ok    Dispatching unknown stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-sasl', u'http://jabber.org/protocol/caps', u'http://jabber.org/features/iq-register'] id->None
DEBUG: tls          start Plugging <xmpp.transports.TLS instance at 0x999530c> into <xmpp.client.Client instance at 0x993d4cc>
DEBUG: tls          warn  TLS unsupported by remote server.
DEBUG: sasl         start Plugging <xmpp.auth.SASL instance at 0x999538c> into <xmpp.client.Client instance at 0x993d4cc>
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x999538c>> for "challenge" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering namespace "urn:ietf:params:xml:ns:xmpp-sasl"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "challenge" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x999538c>> for "failure" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "failure" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x999538c>> for "success" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "success" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: socket       sent  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="DIGEST-MD5" />
DEBUG: socket       got   <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>bm9uY2U9IjQxNzg2MDkxMCIscW9wPSJhdXRoIixjaGFyc2V0PXV0Zi04LGFsZ29yaXRobT1tZDUtc2Vzcw==</challenge>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/challenge stanza
DEBUG: dispatcher   ok    Dispatching challenge stanza with type-> props->[] id->None
DEBUG: sasl         ok    Got challenge:nonce="417860910",qop="auth",charset=utf-8,algorithm=md5-sess
DEBUG: socket       sent  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Y2hhcnNldD11dGYtOCx1c2VybmFtZT0iYW5zaWJsZSIscmVhbG09ImphYmJlci50Y2ZuZXQub3JnIixub25jZT0iNDE3ODYwOTEwIixuYz0wMDAwMDAwMSxjbm9uY2U9IjY1M2Y0NjQ3MDMzYjRkNzE2MzZhMjgwM2ZkNzg1YzQzYWYxZjkwMTdmOTk5OGRkZTQiLGRpZ2VzdC11cmk9InhtcHAvamFiYmVyLnRjZm5ldC5vcmciLHJlc3BvbnNlPTJkODQwNzc4YTIwZWZkOTk2YTk3Y2M3M2ZiZTc4ZWQ5LHFvcD1hdXRo</response>
DEBUG: socket       got   <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cnNwYXV0aD1kZDYzNTUzOTRkMjE4OTA5ZjA1NjQ5NzYyZDc3YWE4YQ==</challenge>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/challenge stanza
DEBUG: dispatcher   ok    Dispatching challenge stanza with type-> props->[] id->None
DEBUG: sasl         ok    Got challenge:rspauth=dd6355394d218909f05649762d77aa8a
DEBUG: socket       sent  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl" />
DEBUG: socket       got   <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/success stanza
DEBUG: dispatcher   ok    Dispatching success stanza with type-> props->[] id->None
DEBUG: sasl         ok    Successfully authenticated with remote server.
DEBUG: dispatcher   stop  Plugging <xmpp.dispatcher.Dispatcher instance at 0x9942a8c> out of <xmpp.client.Client instance at 0x993d4cc>.
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x9995a2c> into <xmpp.client.Client instance at 0x993d4cc>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x9995a2c>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.tld" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: bind         start Plugging <xmpp.auth.Bind instance at 0x999594c> into <xmpp.client.Client instance at 0x993d4cc>
DEBUG: dispatcher   info  Registering handler <bound method Bind.FeaturesHandler of <xmpp.auth.Bind instance at 0x999594c>> for "features" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "features" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='2831548752' from='jabber.example.tld' version='1.0' xml:lang='en'>
DEBUG: socket       got   <stream:features>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>
  <session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='yy7di5kE0syuCXOQTXNBTclpNTo='/>
  <register xmlns='http://jabber.org/features/iq-register'/>
  </stream:features>
DEBUG: dispatcher   ok    Got http://etherx.jabber.org/streams/features stanza
DEBUG: dispatcher   ok    Dispatching features stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-bind', u'urn:ietf:params:xml:ns:xmpp-session', u'http://jabber.org/protocol/caps', u'http://jabber.org/features/iq-register'] id->None
DEBUG: socket       sent  <iq type="set" id="1">
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind">
  <resource>Ansible</resource>
  </bind>
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:1 with timeout 25...
DEBUG: socket       got   <iq id='1' type='result'>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'>
  <jid>ansible@jabber.example.tld/Ansible</jid>
  </bind>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[u'urn:ietf:params:xml:ns:xmpp-bind'] id->1
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully bound ansible@jabber.example.tld/Ansible.
DEBUG: socket       sent  <iq type="set" id="2">
  <session xmlns="urn:ietf:params:xml:ns:xmpp-session" />
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:2 with timeout 25...
DEBUG: socket       got   <iq type='result' id='2'>
  <session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[u'urn:ietf:params:xml:ns:xmpp-session'] id->2
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully opened session.
DEBUG: socket       sent  <presence id="3" />
DEBUG: socket       sent  <message to="xeross@jabber.example.tld" type="chat" id="4">
  <body>[server01] DNS Updated</body>
  </message>
DEBUG: socket       sent  </stream:stream>
DEBUG: socket       got   <presence from='ansible@jabber.example.tld/Ansible' to='ansible@jabber.example.tld/Ansible' id='3'/>
DEBUG: dispatcher   ok    Got jabber:client/presence stanza
DEBUG: dispatcher   ok    Dispatching presence stanza with type-> props->[] id->3
DEBUG: socket       got   </stream:stream>
DEBUG: socket       error Socket error while receiving data
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1379669192.67-215466096639757/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
DEBUG: client       stop  Disconnect detected
DEBUG: socket       error Socket operation failed
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1379669192.67-215466096639757/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
{"msg": "[server01] DNS Updated", "to": "xeross@jabber.example.tld", "changed": false, "user": "ansible"}
```

**Comment by bcoca** [comment]
which version of ansible? there is a try: catch: ValueError on that line in
latest from github.

**Comment by ghost** [comment]
@bcoca As mentioned in the body of the report and the title, Ansible 1.3.2

I could wrap that line in a try...catch statement, but that really sounds like bypassing a bug. As far as I can tell it's trying to split the `to` parameter which in the case of a conference room has a / in it.

Sounds more like you'd have to detect whether it has an @ or a / and handle accordingly (If my speculation is correct).

**Comment by bcoca** [comment]
the code 'kinda' does that but using exceptions instead of testing, not how
i would have done it but it should work w/o showing errors. (unless i'm
missing something obvious, which is perfectly possible).

try:
    to, nick = module.params['to'].split('/', 1)
except ValueError:
     to, nick = module.params['to'], None

I'm surprised no one else had an issue as this was changed on july 24th
from my original optimistic:
  to, nick = re.split( r'/', module.params['to'])

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jctanner** [comment]
@xeross if you see the same issue with 1.3.3 or above, please open a new issue.

Relevant commit in 1.3.3: https://github.com/ansible/ansible/commit/38d60636
