### ISSUE TITLE
azure_rm_functionapp is failing

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#41935]
##### SUMMARY
With previously working scripts, now I can no longer create a functionapp through ansible.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = ['/home/otp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Windows 10, running Linux/Ubuntu subsystem.

##### STEPS TO REPRODUCE

```yaml
- name: for SQL server test
  hosts: localhost
  vars:
    resource_group: myRG01d
    function_app: fredapp001d
    location: westeurope
    storage_name: myst0rage001d
    storage_type: Standard_LRS


  tasks:
    - name: create resource groupo
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

   # create a storage account:
    - name: "Create storage account {{ storage_name }}"
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_name }}"
        account_type: "{{ storage_type }}"

    - name: "Create azure function app {{ function_app }}"
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app }}"
        storage_account: "{{ storage_name }}"
        app_settings:
             VAR1: abc
             VAR2: bcd

```

##### EXPECTED RESULTS

The functionapp should be created.

##### ACTUAL RESULTS

Everything up to the functionapp gets created, but the functionapp returns an error, as  shown below.

```
ansible-playbook 2.5.3
  config file = None
  configured module search path = ['/home/otp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
No config file found; using defaults
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: pb2.yaml **********************************************************************************************************************************************************************************************************************************
1 plays in pb2.yaml

PLAY [for SQL server test] **************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************
task path: /mnt/c/tmp/pb2.yaml:1
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: otp
<127.0.0.1> EXEC /bin/sh -c 'echo ~otp && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128 `" && echo ansible-tmp-1529964459.3369524-3102997152128="` echo /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128 `" ) && sleep 0'
<127.0.0.1> PUT /home/otp/.ansible/tmp/ansible-local-223799y2x5brl/tmps5b6izwt TO /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128/ /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/otp/.ansible/tmp/ansible-tmp-1529964459.3369524-3102997152128/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [create resource groupo] ***********************************************************************************************************************************************************************************************************************
task path: /mnt/c/tmp/pb2.yaml:12
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/cloud/azure/azure_rm_resourcegroup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: otp
<127.0.0.1> EXEC /bin/sh -c 'echo ~otp && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457 `" && echo ansible-tmp-1529964461.7341068-2217392087457="` echo /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457 `" ) && sleep 0'
<127.0.0.1> PUT /home/otp/.ansible/tmp/ansible-local-223799y2x5brl/tmptgcwg07q TO /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457/azure_rm_resourcegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457/ /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457/azure_rm_resourcegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457/azure_rm_resourcegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/otp/.ansible/tmp/ansible-tmp-1529964461.7341068-2217392087457/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "contains_resources": true,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": null,
            "force": false,
            "location": "westeurope",
            "name": "myRG01d",
            "password": null,
            "profile": null,
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "state": {
        "id": "/subscriptions/0f2f4954-26bf-4aed-bc0c-24ffc80d1c18/resourceGroups/myRG01d",
        "location": "westeurope",
        "name": "myRG01d",
        "provisioning_state": "Succeeded",
        "tags": {}
    }
}

TASK [Create storage account myst0rage001d] *********************************************************************************************************************************************************************************************************
task path: /mnt/c/tmp/pb2.yaml:18
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/cloud/azure/azure_rm_storageaccount.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: otp
<127.0.0.1> EXEC /bin/sh -c 'echo ~otp && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730 `" && echo ansible-tmp-1529964464.6075077-140187726007730="` echo /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730 `" ) && sleep 0'
<127.0.0.1> PUT /home/otp/.ansible/tmp/ansible-local-223799y2x5brl/tmprfj04u70 TO /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730/azure_rm_storageaccount.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730/ /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730/azure_rm_storageaccount.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730/azure_rm_storageaccount.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/otp/.ansible/tmp/ansible-tmp-1529964464.6075077-140187726007730/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_tier": null,
            "account_type": "Standard_LRS",
            "ad_user": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": null,
            "custom_domain": null,
            "force": false,
            "kind": "Storage",
            "location": null,
            "name": "myst0rage001d",
            "password": null,
            "profile": null,
            "resource_group": "myRG01d",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "state": {
        "access_tier": null,
        "custom_domain": null,
        "id": "/subscriptions/0f2f4954-26bf-4aed-bc0c-24ffc80d1c18/resourceGroups/myRG01d/providers/Microsoft.Storage/storageAccounts/myst0rage001d",
        "location": "westeurope",
        "name": "myst0rage001d",
        "primary_endpoints": {
            "blob": "https://myst0rage001d.blob.core.windows.net/",
            "queue": "https://myst0rage001d.queue.core.windows.net/",
            "table": "https://myst0rage001d.table.core.windows.net/"
        },
        "primary_location": "westeurope",
        "provisioning_state": "Succeeded",
        "resource_group": "myRG01d",
        "secondary_endpoints": null,
        "secondary_location": null,
        "sku_name": "Standard_LRS",
        "sku_tier": "Standard",
        "status_of_primary": "available",
        "status_of_secondary": null,
        "tags": {},
        "type": "Microsoft.Storage/storageAccounts"
    }
}

TASK [Create azure function app fredapp001d] ********************************************************************************************************************************************************************************************************
task path: /mnt/c/tmp/pb2.yaml:24
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/cloud/azure/azure_rm_functionapp.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: otp
<127.0.0.1> EXEC /bin/sh -c 'echo ~otp && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903 `" && echo ansible-tmp-1529964467.6428182-101952895884903="` echo /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903 `" ) && sleep 0'
<127.0.0.1> PUT /home/otp/.ansible/tmp/ansible-local-223799y2x5brl/tmpp2yort4_ TO /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903/azure_rm_functionapp.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903/ /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903/azure_rm_functionapp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903/azure_rm_functionapp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/otp/.ansible/tmp/ansible-tmp-1529964467.6428182-101952895884903/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py", line 297, in <module>
    main()
  File "/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py", line 294, in main
    AzureRMFunctionApp()
  File "/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py", line 156, in __init__
    required_if=required_if
  File "/tmp/ansible_0g_ofwdn/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 345, in __init__
  File "/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py", line 209, in exec_module
    self.results['changed'], function_app = self.update(function_app)
  File "/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py", line 231, in update
    name=self.name
  File "/usr/local/lib/python3.5/dist-packages/azure/mgmt/web/operations/web_apps_operations.py", line 1385, in list_application_settings
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Web/sites/fredapp001d' under resource group 'myRG01d' was not found.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py\", line 297, in <module>\n    main()\n  File \"/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py\", line 294, in main\n    AzureRMFunctionApp()\n  File \"/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py\", line 156, in __init__\n    required_if=required_if\n  File \"/tmp/ansible_0g_ofwdn/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 345, in __init__\n  File \"/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py\", line 209, in exec_module\n    self.results['changed'], function_app = self.update(function_app)\n  File \"/tmp/ansible_0g_ofwdn/ansible_module_azure_rm_functionapp.py\", line 231, in update\n    name=self.name\n  File \"/usr/local/lib/python3.5/dist-packages/azure/mgmt/web/operations/web_apps_operations.py\", line 1385, in list_application_settings\n    raise exp\nmsrestazure.azure_exceptions.CloudError: Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Web/sites/fredapp001d' under resource group 'myRG01d' was not found.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
        to retry, use: --limit @/mnt/c/tmp/pb2.retry

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1
```

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/azure/azure_rm_functionapp.py

**Comment by zikalino** [comment]
I just retested the exact scenario and the behavior is correct.
I think something was fixed either in the service or python libraries in a meanwhile
I will close this issue, please reopen if still occurs.
