### ISSUE TITLE
aws_ssm_parameter_store Key error 'Description'

### ISSUE THREAD

**Issue by sunshine69** [ansible/ansible#42986]
##### SUMMARY

Ansibel module aws_ssm_parameter_store stop working with error 'Key Error Description'

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```
stevek@stevek-macbook 11:25 ~> ansible-config dump --only-changed
stevek@stevek-macbook 11:25 ~>
```
##### OS / ENVIRONMENT

Ubuntu 18.04
ansible installed using pip install -U ansible

##### STEPS TO REPRODUCE

```yaml
- name: test ssm
  hosts: localhost
  tasks:
    - name: Test aws_ssm_parameter_store
      aws_ssm_parameter_store:
        profile: "{{ profile }}"
        region: "{{ region }}"
        name: "Hello"
        description: "{{ desc|default(omit) }}"
        string_type: SecureString
        value: "World"
    - set_fact:
        out: "{{ lookup('aws_ssm', 'Hello', aws_profile=profile, region=region) }}"
```

##### EXPECTED RESULTS

Play passed

##### ACTUAL RESULTS

Play error see the output

```
TASK [Test aws_ssm_parameter_store] ******************************************************
task path: /home/stevek/deployments/act2-ansible/tests/test-ssm-parameter-store.yml:4
Thursday 19 July 2018  11:30:12 +1000 (0:00:00.639)       0:00:00.671 ********* 
Using module_utils file /home/stevek/deployments/act2-ansible/module_utils/ec2.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/aws/core.py
Using module_utils file /home/stevek/deployments/act2-ansible/module_utils/aws/__init__.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/cloud.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/pycompat24.py
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/aws_ssm_parameter_store.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: stevek
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_L5Bvi2/ansible_module_aws_ssm_parameter_store.py", line 253, in <module>
    main()
  File "/tmp/ansible_L5Bvi2/ansible_module_aws_ssm_parameter_store.py", line 248, in main
    (changed, response) = invocations[state](client, module)
  File "/tmp/ansible_L5Bvi2/ansible_module_aws_ssm_parameter_store.py", line 184, in create_update_parameter
    if args['Description']:
KeyError: 'Description'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_L5Bvi2/ansible_module_aws_ssm_parameter_store.py\", line 253, in <module>\n    main()\n  File \"/tmp/ansible_L5Bvi2/ansible_module_aws_ssm_parameter_store.py\", line 248, in main\n    (changed, response) = invocations[state](client, module)\n  File \"/tmp/ansible_L5Bvi2/ansible_module_aws_ssm_parameter_store.py\", line 184, in create_update_parameter\n    if args['Description']:\nKeyError: 'Description'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
	to retry, use: --limit @/home/stevek/.ansible-retry/test-ssm-parameter-store.retry

PLAY RECAP *******************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

=== NOTES

* If I supply the description as a text in the ansible module then it goes fine.
* If downgrade ansible to version 2.5.6 everything works again. 2.6.0 and 2.6.1 (lastest) has the same issues.

**Comment by ryansb** [comment]
Please try out https://github.com/ansible/ansible/pull/43020 and see if that resolves your issue
