### ISSUE TITLE
Including an empty file in roles/$role/tasks/main.yml causes "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by stintel** [ansible/ansible#4322]
When running my playbook (which works fine with 1.3 and git devel 314e1aafc1eee9ffdfcfb42c2d3567d8cf5d37ed) with git devel bff47df5ffd93b28a7da856882bc707d2f1a596a, I get this error:

```
sudo password:
Traceback (most recent call last):
  File "/home/stijn/Development/ansible/bin/ansible-playbook", line 268, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/stijn/Development/ansible/bin/ansible-playbook", line 208, in main
    pb.run()
  File "/home/stijn/Development/ansible/lib/ansible/playbook/__init__.py", line 228, in run
    play = Play(self, play_ds, play_basedir)
  File "/home/stijn/Development/ansible/lib/ansible/playbook/play.py", line 123, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/home/stijn/Development/ansible/lib/ansible/playbook/play.py", line 456, in _load_tasks
    results += self._load_tasks(data, mv, default_vars, included_sudo_vars, included_additional_conditions, original_file=include_filename, role_name=new_role)
  File "/home/stijn/Development/ansible/lib/ansible/playbook/play.py", line 453, in _load_tasks
    for x in data:
TypeError: 'NoneType' object is not iterable
```

Using "git bisect", I found that this error was introduced in 482cb721283a938f9553c33e2fced935be9e1776.

After doing some testing, I found that this happens when including an empty file, or a file with only header and commented lines in roles/$role/tasks/main.yml.

**Comment by jimi-c** [comment]
The above commit should fix that issue for you. Thanks for catching it and reporting it!
