### ISSUE TITLE
template module fails to change produced file attributes

### ISSUE THREAD

**Issue by jmatis** [ansible/ansible#43475]
##### SUMMARY
template module fails to change produced file attributes

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template module

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
# ansible-config dump --only-changed
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_ASK_SUDO_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = managed by ansible-001
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = beheer
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Controller: CentOS Linux release 7.5.1804 (Core)
Managed: CentOS release 6.10 (Final)

##### STEPS TO REPRODUCE
run following playbook against centos6 machine: 
```yaml
---
- name: postbode start script
  template:
    src: postbode_start.sh.j2
    dest: "/apps/modules/postbode_start.sh"
    owner: beheer
    group: beheer
    attributes: 0755
  tags: postbode
```

template postbode_start.sh.j2:
```
#! /bin/bash

cd /apps/modules/postbode

{% if postbode_enabled_glowroot %}
/apps/play/play start {{ glowroot_agent }} -Dglowroot.agent.id={{ server_group }}::{{ role_name }}:: {{ glowroot_collector }}
{% else %}
/apps/play/play start
{% endif %}
```

##### EXPECTED RESULTS
shell script created with correct attributes

##### ACTUAL RESULTS
shell script gets created with correct content but wrong attributes  as 
-rw-r--r--  1 beheer beheer  208 Jul 31 09:21 /apps/modules/postbode_start.sh

```
TASK [postbode : postbode start script] *******************************************************************************************************************************************
task path: /etc/ansible/inventories/roles/postbode/tasks/main.yml:2
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'echo ~beheer && sleep 0'"'"''
<app-a1> (0, '/home/beheer\n', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529 `" && echo ansible-tmp-1533023422.65-37010383173529="` echo /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529 `" ) && sleep 0'"'"''
<app-a1> (0, 'ansible-tmp-1533023422.65-37010383173529=/home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/stat.py
<app-a1> PUT /root/.ansible/tmp/ansible-local-18903ovyOR6/tmpKENQro TO /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/stat.py
<app-a1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab '[app-a1]'
<app-a1> (0, 'sftp> put /root/.ansible/tmp/ansible-local-18903ovyOR6/tmpKENQro /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/stat.py\n', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'chmod u+x /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/ /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/stat.py && sleep 0'"'"''
<app-a1> (0, '', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab -tt app-a1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-cmnsyhsnvpbklewhxbcmvquukwfhinks; /usr/bin/python /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/stat.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<app-a1> (0, '\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "follow": false, "checksum_algo": "sha1", "path": "/apps/modules/postbode_start.sh", "get_md5": null, "get_mime": true, "get_attributes": true}}, "stat": {"charset": "us-ascii", "uid": 500, "exists": true, "attr_flags": "", "woth": false, "isreg": true, "device_type": 0, "mtime": 1533021665.0, "block_size": 4096, "inode": 1040564, "isgid": false, "size": 208, "executable": true, "isuid": false, "readable": true, "version": "18446744073376449695", "pw_name": "beheer", "gid": 500, "ischr": false, "wusr": true, "writeable": true, "mimetype": "text/x-shellscript", "blocks": 8, "xoth": true, "islnk": false, "nlink": 1, "issock": false, "rgrp": true, "gr_name": "beheer", "path": "/apps/modules/postbode_start.sh", "xusr": true, "atime": 1533022291.0, "isdir": false, "ctime": 1533022370.0, "isblk": false, "wgrp": false, "checksum": "1b96938f7b6fdc1ef9376292c1e981815d76a86a", "dev": 2049, "roth": true, "isfifo": false, "mode": "0755", "xgrp": true, "rusr": true, "attributes": []}, "changed": false}\r\n', 'Shared connection to app-a1 closed.\r\n')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/file.py
<app-a1> PUT /root/.ansible/tmp/ansible-local-18903ovyOR6/tmpeBpHjj TO /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/file.py
<app-a1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab '[app-a1]'
<app-a1> (0, 'sftp> put /root/.ansible/tmp/ansible-local-18903ovyOR6/tmpeBpHjj /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/file.py\n', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'chmod u+x /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/ /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/file.py && sleep 0'"'"''
<app-a1> (0, '', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab -tt app-a1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-vywgirtsgnvwtwgogyflbyfoqqxvyhtk; /usr/bin/python /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/file.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<app-a1> (1, '\r\n{"exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_nj7L0D/ansible_modlib.zip/ansible/module_utils/basic.py\\", line 1380, in set_attributes_if_different\\n    raise Exception(\\"Error while setting attributes: %s\\" % (out + err))\\nException: Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...\\n\\n", "group": "beheer", "uid": 500, "mode": "0755", "failed": true, "state": "file", "gid": 500, "details": "Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...\\n", "invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "_original_basename": "postbode_start.sh.j2", "path": "/apps/modules/postbode_start.sh", "owner": "beheer", "follow": false, "group": "beheer", "unsafe_writes": null, "serole": null, "content": null, "state": "file", "setype": null, "dest": "/apps/modules/postbode_start.sh", "selevel": null, "regexp": null, "src": null, "seuser": null, "recurse": false, "_diff_peek": null, "delimiter": null, "mode": null, "attributes": "493", "backup": null}}, "owner": "beheer", "path": "/apps/modules/postbode_start.sh", "size": 208, "msg": "chattr failed"}\r\n', 'Shared connection to app-a1 closed.\r\n')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'rm -f -r /home/beheer/.ansible/tmp/ansible-tmp-1533023422.65-37010383173529/ > /dev/null 2>&1 && sleep 0'"'"''
<app-a1> (0, '', '')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_nj7L0D/ansible_modlib.zip/ansible/module_utils/basic.py", line 1380, in set_attributes_if_different
    raise Exception("Error while setting attributes: %s" % (out + err))
Exception: Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...


fatal: [app-a1]: FAILED! => {
    "changed": false,
    "checksum": "1b96938f7b6fdc1ef9376292c1e981815d76a86a",
    "details": "Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...\n",
    "diff": [],
    "gid": 500,
    "group": "beheer",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": "postbode_start.sh.j2",
            "attributes": "493",
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/apps/modules/postbode_start.sh",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": "beheer",
            "mode": null,
            "owner": "beheer",
            "path": "/apps/modules/postbode_start.sh",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "file",
            "unsafe_writes": null
        }
    },
    "mode": "0755",
    "msg": "chattr failed",
    "owner": "beheer",
    "path": "/apps/modules/postbode_start.sh",
    "size": 208,
    "state": "file",
    "uid": 500
}

```

**Comment by jmatis** [comment]
I have just also tested this with version: 
# ansible --version
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

with the same results : 
```
TASK [postbode : postbode start script] *******************************************************************************************************************************************
task path: /etc/ansible/inventories/roles/postbode/tasks/main.yml:2
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'echo ~beheer && sleep 0'"'"''
<app-a1> (0, '/home/beheer\n', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847 `" && echo ansible-tmp-1533024234.53-179503905654847="` echo /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847 `" ) && sleep 0'"'"''
<app-a1> (0, 'ansible-tmp-1533024234.53-179503905654847=/home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/stat.py
<app-a1> PUT /root/.ansible/tmp/ansible-local-19236GylXfG/tmpBD3tem TO /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/stat.py
<app-a1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab '[app-a1]'
<app-a1> (0, 'sftp> put /root/.ansible/tmp/ansible-local-19236GylXfG/tmpBD3tem /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/stat.py\n', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'chmod u+x /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/ /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/stat.py && sleep 0'"'"''
<app-a1> (0, '', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab -tt app-a1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rhaqugtvwhziaosypqllsaasjithlmtc; /usr/bin/python /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/stat.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<app-a1> (0, '\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "follow": false, "checksum_algo": "sha1", "path": "/apps/modules/postbode_start.sh", "get_md5": null, "get_mime": true, "get_attributes": true}}, "stat": {"charset": "us-ascii", "uid": 500, "exists": true, "attr_flags": "", "woth": false, "isreg": true, "device_type": 0, "mtime": 1533021665.0, "block_size": 4096, "inode": 1040564, "isgid": false, "size": 208, "executable": true, "isuid": false, "readable": true, "version": "18446744073376449695", "pw_name": "beheer", "gid": 500, "ischr": false, "wusr": true, "writeable": true, "mimetype": "text/x-shellscript", "blocks": 8, "xoth": true, "islnk": false, "nlink": 1, "issock": false, "rgrp": true, "gr_name": "beheer", "path": "/apps/modules/postbode_start.sh", "xusr": true, "atime": 1533023423.0, "isdir": false, "ctime": 1533022370.0, "isblk": false, "wgrp": false, "checksum": "1b96938f7b6fdc1ef9376292c1e981815d76a86a", "dev": 2049, "roth": true, "isfifo": false, "mode": "0755", "xgrp": true, "rusr": true, "attributes": []}, "changed": false}\r\n', 'Shared connection to app-a1 closed.\r\n')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/file.py
<app-a1> PUT /root/.ansible/tmp/ansible-local-19236GylXfG/tmp3XKEUM TO /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/file.py
<app-a1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab '[app-a1]'
<app-a1> (0, 'sftp> put /root/.ansible/tmp/ansible-local-19236GylXfG/tmp3XKEUM /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/file.py\n', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'chmod u+x /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/ /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/file.py && sleep 0'"'"''
<app-a1> (0, '', '')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab -tt app-a1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-kfoqpfkdtwgtqdpsyjkzmjuouczutodl; /usr/bin/python /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/file.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<app-a1> (1, '\r\n{"exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_B9yYzR/ansible_modlib.zip/ansible/module_utils/basic.py\\", line 1395, in set_attributes_if_different\\n    raise Exception(\\"Error while setting attributes: %s\\" % (out + err))\\nException: Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...\\n\\n", "group": "beheer", "uid": 500, "mode": "0755", "failed": true, "state": "file", "gid": 500, "details": "Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...\\n", "invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "_original_basename": "postbode_start.sh.j2", "path": "/apps/modules/postbode_start.sh", "owner": "beheer", "follow": false, "group": "beheer", "unsafe_writes": null, "serole": null, "content": null, "state": "file", "setype": null, "dest": "/apps/modules/postbode_start.sh", "selevel": null, "regexp": null, "src": null, "seuser": null, "recurse": false, "_diff_peek": null, "delimiter": null, "mode": null, "attributes": "493", "backup": null}}, "owner": "beheer", "path": "/apps/modules/postbode_start.sh", "size": 208, "msg": "chattr failed"}\r\n', 'Shared connection to app-a1 closed.\r\n')
<app-a1> ESTABLISH SSH CONNECTION FOR USER: beheer
<app-a1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=beheer -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6f096ed7ab app-a1 '/bin/sh -c '"'"'rm -f -r /home/beheer/.ansible/tmp/ansible-tmp-1533024234.53-179503905654847/ > /dev/null 2>&1 && sleep 0'"'"''
<app-a1> (0, '', '')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_B9yYzR/ansible_modlib.zip/ansible/module_utils/basic.py", line 1395, in set_attributes_if_different
    raise Exception("Error while setting attributes: %s" % (out + err))
Exception: Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...


fatal: [app-a1]: FAILED! => {
    "changed": false,
    "checksum": "1b96938f7b6fdc1ef9376292c1e981815d76a86a",
    "details": "Error while setting attributes: Usage: /usr/bin/chattr [-RVf] [-+=AacDdeijsSu] [-v version] files...\n",
    "diff": [],
    "gid": 500,
    "group": "beheer",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": "postbode_start.sh.j2",
            "attributes": "493",
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/apps/modules/postbode_start.sh",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": "beheer",
            "mode": null,
            "owner": "beheer",
            "path": "/apps/modules/postbode_start.sh",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "file",
            "unsafe_writes": null
        }
    },
    "mode": "0755",
    "msg": "chattr failed",
    "owner": "beheer",
    "path": "/apps/modules/postbode_start.sh",
    "size": 208,
    "state": "file",
    "uid": 500
}
```

**Comment by jmatis** [comment]
in role / playbook 
it should have been 
    mode: 0755
instead of: 
    attributes: 0755
