### ISSUE TITLE
usermod does not relocate home directories

### ISSUE THREAD

**Issue by mattwwarren** [ansible/ansible#4371]
Looking at [the user module](https://github.com/ansible/ansible/blob/39fe40bb60bafcac01e0611fcadf9553d976a6e2/library/system/user) I believe I see the missing bits.  Each call to usermod does not use -m to relocate the home directory when the home directory is changed.  Without this option, the new home directory location is not created and things like SSH authorized_keys creation fails.

``` bash
TASK: [common | Add jenkins user for deployments] *****************************
changed: [ftp] # This step changes the homedir from /home/jenkins to /var/lib/jenkins

TASK: [common | Add jenkins authorized_key] ***********************************
fatal: [ftp] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1380908811.04-166850235966093/authorized_key", line 1168, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1380908811.04-166850235966093/authorized_key", line 234, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1380908811.04-166850235966093/authorized_key", line 209, in enforce_state
    writekeys(module, keyfile(module, user, write, path, manage_dir), keys)
  File "/root/.ansible/tmp/ansible-1380908811.04-166850235966093/authorized_key", line 137, in keyfile
    os.mkdir(sshdir, 0700)
OSError: [Errno 2] No such file or directory: '/var/lib/jenkins/.ssh'
```

I do not have an environment configured just yet but here is a rough idea of where the changes should be made, if someone else wants to implement.

364:

``` python
        if self.home is not None and info[5] != self.home:
            cmd.append('-m')
            cmd.append('-d')
            cmd.append(self.home)
```

653:

``` python
        if self.home is not None and info[5] != self.home:
            cmd.append('-m')
            cmd.append('-d')
            cmd.append(self.home)
```

839:

``` python
        if self.home is not None and info[5] != self.home:
            cmd.append('-m')
            cmd.append('-d')
            cmd.append(self.home)
```

992:

``` python
        if self.home is not None and info[5] != self.home:
            cmd.append('-m')
            cmd.append('-d')
            cmd.append(self.home)
```

1151:

``` python
        if self.home is not None and info[5] != self.home:
            cmd.append('-m')
            cmd.append('-d')
            cmd.append(self.home)
```

1303:

``` python
        if self.home is not None and info[5] != self.home:
            cmd.append('-m')
            cmd.append('-d')
            cmd.append(self.home)
```

**Comment by mpdehaan** [comment]
How about sending a pull request?

**Comment by mattwwarren** [comment]
Will do, just getting a fork set up now.

**Comment by mattwwarren** [comment]
https://github.com/ansible/ansible/pull/4389 has been submitted.

**Comment by mpdehaan** [comment]
closing per the above, thanks!
