### ISSUE TITLE
ec2.py does not work in python3.7

### ISSUE THREAD

**Issue by Jackyjjc** [ansible/ansible#43909]
##### SUMMARY

When i run the ec2.py script, I get the following error:
```
$ python /Users/jchen/ec2.py
Traceback (most recent call last):
  File "/Users/jchen/ec2.py", line 1701, in <module>
    Ec2Inventory()
  File "/Users/jchen/ec2.py", line 260, in __init__
    self.read_settings()
  File "/Users/jchen/ec2.py", line 314, in read_settings
    config = configparser.ConfigParser(DEFAULTS)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```
The issue is due to a change in python3.7: https://github.com/python/cpython/commit/44e6ad87340d50f48daf53b6a61138377d0d0d10#diff-6b3852636536e78a60076fbaac229f63

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### STEPS TO REPRODUCE

```yaml
python3.7 ec2.py
```

**Comment by Jackyjjc** [comment]
found a related PR https://github.com/ansible/ansible/pull/43716

**Comment by sivel** [comment]
Closing since we have the associated PR open: https://github.com/ansible/ansible/pull/43716
