### ISSUE TITLE
Playbook with non-root user play after a root-user play fails with permissions errors

### ISSUE THREAD

**Issue by johncallender** [ansible/ansible#440]
Using ansible 0.4, I've noticed the following problem: If I use ansible-playbook to run a playbook that contains two plays, the first of which runs as root, but the second of which runs as a non-root user, the second play fails with a permissions error. If I create a playbook that only includes the second (non-root-user) play, it runs without error.

Here's a minimal playbook example:

```

---
# reproduce the bug I saw in install/setup_dev.yml

- hosts: dev
  user: root
  tasks:
    - name: ping as root
      action: ping

- hosts: dev
  user: jbcsys
  tasks:
    - name: ping as jbcsys
      action: ping
```

When I run that, I see the following:

```
[jbcsys@dev ~]$ ansible-playbook live/etc/ansible/test/test.yml 


PLAY [dev] ****************************

SETUP PHASE ****************************

ok: [dev]


TASK: [ping as root] *********

ok: [dev] => ping 

PLAY [dev] ****************************

SETUP PHASE ****************************

fatal: [dev] => failed to parse: Traceback (most recent call last):

  File "//home/jbcsys/.ansible/tmp/ansible.0eAKwE/setup", line 386, in <module>

    f = open(ansible_file, "w+")

IOError: [Errno 13] Permission denied: u'/etc/ansible/setup'
/Traceback (most recent call last):

  File "//home/jbcsys/.ansible/tmp/ansible.0eAKwE/setup", line 386, in <module>

    f = open(ansible_file, "w+")

IOError: [Errno 13] Permission denied: u'/etc/ansible/setup'
/setup {
    "branch": "master", 
    "db_host": "dev", 
    "group_names": [
        "ungrouped"
    ], 
    "inventory_hostname": "dev", 
    "ip_address": "209.151.236.32", 
    "jbcsysroot": "/home/jbcsys/live", 
    "metadata": "/etc/ansible/setup", 
    "package_state": "latest", 
    "www_hostname": "dev"
}
fatal: [dev] => failed to parse: Traceback (most recent call last):

  File "//home/jbcsys/.ansible/tmp/ansible.0eAKwE/setup", line 386, in <module>

    f = open(ansible_file, "w+")

IOError: [Errno 13] Permission denied: u'/etc/ansible/setup'
/Traceback (most recent call last):

  File "//home/jbcsys/.ansible/tmp/ansible.0eAKwE/setup", line 386, in <module>

    f = open(ansible_file, "w+")

IOError: [Errno 13] Permission denied: u'/etc/ansible/setup'
/setup {
    "branch": "master", 
    "db_host": "dev", 
    "group_names": [
        "ungrouped"
    ], 
    "inventory_hostname": "dev", 
    "ip_address": "209.151.236.32", 
    "jbcsysroot": "/home/jbcsys/live", 
    "metadata": "/etc/ansible/setup", 
    "package_state": "latest", 
    "www_hostname": "dev"
}

TASK: [ping as jbcsys] *********

no hosts matched or remaining



PLAY RECAP **********************


dev                            : ok=   2 changed=   0 unreachable=   1 failed=   0 
```

My interpretation of this is that ansible is trying to create a temporary file on the remote server at /etc/ansible/setup, even though it is running the play as the non-root user, who should get temporary files created in a different location on the remote host.

**Comment by mpdehaan** [comment]
fixed this on the development branch, the SETUP_CACHE variable was being shared between plays, which was causing the runner code to not recalculate the metadata parameter to the setup module, which determines where to place the setup file.

**Comment by johncallender** [comment]
Awesome! Thanks.
