### ISSUE TITLE
dnstxt raising a TypeError

### ISSUE THREAD

**Issue by caphrim007** [ansible/ansible#4402]
Using ansible-playbook 1.2 I am receiving the following exception when I try to use the dnstxt lookup plugin

http://pastebin.com/Lj86T16e

The task in question is this
- name: Check for MVP
  set_fact: has_mvp={{ lookup('dnstxt', 'google.com') }}

I'm not sure what class, type, or tuples of the aforementioned would be needed to make this work.

Thanks!

**Comment by mpdehaan** [comment]
pastebins can away so pasting here:

fatal: [459410] => Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/ansible/runner/**init**.py", line 344, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/local/lib/python2.6/dist-packages/ansible/runner/__init__.py", line 423, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.6/dist-packages/ansible/runner/__init__.py", line 574, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject)
  File "/usr/local/lib/python2.6/dist-packages/ansible/utils/template.py", line 308, in template
    varname = template_from_string(basedir, varname, vars)
  File "/usr/local/lib/python2.6/dist-packages/ansible/utils/template.py", line 497, in template_from_string
    res = jinja2.utils.concat(t.root_render_func(t.new_context(_jinja2_vars(basedir, vars, t.globals), shared=True)))
  File "<template>", line 11, in root
  File "/usr/local/lib/python2.6/dist-packages/jinja2/runtime.py", line 193, in call
    return __obj(_args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/ansible/utils/template.py", line 493, in my_lookup
    return lookup(_args, basedir=basedir, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/ansible/utils/template.py", line 86, in lookup
    ran = instance.run(_args, inject=vars, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/ansible/runner/lookup_plugins/dnstxt.py", line 47, in run
    if isinstance(basestring, terms):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

Can you please test this in the current released version (1.3) ?

**Comment by sivel** [comment]
It does look to me that the arguments for isinstance are backwards.

Right now it looks like:

`isinstance(basestring, terms)`

I believe it should be:

`isinstance(terms, basestring)`

**Comment by mpdehaan** [comment]
Thanks -- Could just be an error path that was never tested, or someone
made a code change and didn't test the dnstext module.

Easy enough!

**Comment by sivel** [comment]
It looks like there are no active tests for lookup plugins.  Looks like some of it was there, but they have been commented out:  https://github.com/ansible/ansible/blob/devel/test/TestPlayBook.py#L167-L191
