### ISSUE TITLE
ansible-vault traceback when configured EDITOR doesn't exist

### ISSUE THREAD

**Issue by the-noob** [ansible/ansible#44419]
##### SUMMARY

I have a vault file created with 2.5.1 on my laptop and I'm unable to decrypt it on another machine with 2.6.3

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-vault

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/the-noob/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

```DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

##### STEPS TO REPRODUCE

` ansible-vault edit vault -vvv`

```yaml

```

##### EXPECTED RESULTS

I can edit  the vault contents

##### ACTUAL RESULTS

Got an error

```
ansible-vault 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/the-noob/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-vault
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
Vault password: 
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-vault", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/vault.py", line 255, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/vault.py", line 446, in execute_edit
    self.editor.edit_file(f)
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 975, in edit_file
    force_save=False, vault_id=vault_id)
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 864, in _edit_file_helper
    subprocess.call(self._editor_shell_command(tmp_path))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by sivel** [comment]
The error is that ansible is unable to invoke an editor.  Ansible will look to see if you have an `EDITOR` env var exported, or fallback to attempting to execute `vi`.

It sounds as though either you have `EDITOR` configured to a value for an application that doesn't exist, or you do not have `vi` available.

Is this problem happening on a single machine?  Or is the 2.5 install on a different machine than the 2.6 install?

Can you check your `EDITOR` env var (`echo $EDITOR`)?

needs_info

**Comment by the-noob** [comment]
Indeed it was the `EDITOR`, first time having this issue.
Not sure if this is a common problem, tried searching a bit but couldn't find anything. 
Maybe the error message can be made more specific ?

Can be closed, thank you!

**Comment by sivel** [comment]
I agree.  Causing a traceback isn't the most friendly.

I'll still keep this open to address this.
