### ISSUE TITLE
mysql_user module cannot change root password on hosts with digits in {{ ansible_hostname }}

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#4467]
Tasks used to change root mysql password:

```
- name: MYSQL | Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - '{{ ansible_hostname }}'
    - 127.0.0.1
    - ::1
    - localhost

- name: MYSQL | Copy .my.cnf file with root password credentials
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
```

On first execution, password is set correctly for all hosts (DNS names: db0.aiua, db1.aiua, small.aiua) (.aiua is an internal test domain handled by dnsmasq). Upon changing `mysql_root_password` variable and re-running the tasks, there are errors on hosts with digits in their hostname:

```
TASK: [mysql | MYSQL | Update mysql root password for all root accounts] ****** 
changed: [small.aiua] => (item=small)
fatal: [db0.aiua] => failed to parse: Traceback (most recent call last):
  File "/home/drybjed/.ansible/tmp/ansible-1381521298.62-255197104731275/mysql_user", line 1369, in <module>
    main()
  File "/home/drybjed/.ansible/tmp/ansible-1381521298.62-255197104731275/mysql_user", line 421, in main
    changed = user_mod(cursor, user, host, password, priv, append_privs)
  File "/home/drybjed/.ansible/tmp/ansible-1381521298.62-255197104731275/mysql_user", line 170, in user_mod
    cursor.execute("SET PASSWORD FOR %s@%s = PASSWORD(%s)", (user,host,password))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1133, "Can't find any matching row in the user table")

fatal: [db1.aiua] => failed to parse: Traceback (most recent call last):
  File "/home/drybjed/.ansible/tmp/ansible-1381521298.62-137011729936459/mysql_user", line 1369, in <module>
    main()
  File "/home/drybjed/.ansible/tmp/ansible-1381521298.62-137011729936459/mysql_user", line 421, in main
    changed = user_mod(cursor, user, host, password, priv, append_privs)
  File "/home/drybjed/.ansible/tmp/ansible-1381521298.62-137011729936459/mysql_user", line 170, in user_mod
    cursor.execute("SET PASSWORD FOR %s@%s = PASSWORD(%s)", (user,host,password))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1133, "Can't find any matching row in the user table")

changed: [small.aiua] => (item=127.0.0.1)
changed: [small.aiua] => (item=::1)
changed: [small.aiua] => (item=localhost)
```

**Comment by mpdehaan** [comment]
I suspect you need to do 

{{ password | quote }}

but am not positive.

Can you check?

**Comment by mpdehaan** [comment]
Actually I suspect this might just be because it's not double evaluating the variable here.

**Comment by drybjed** [comment]
@mpdehaan With `{{ password | quote }}` error is the same.

**Comment by drybjed** [comment]
Issue has been resolved in recent version. Thanks!
