### ISSUE TITLE
Stack trace in YAML Validation Code

### ISSUE THREAD

**Issue by phillipuniverse** [ansible/ansible#4518]
From the ansible-project list, the stack trace is as follows:

``` console
Traceback (most recent call last):
  File "/usr/local/share/python/ansible-playbook", line 268, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/share/python/ansible-playbook", line 208, in main
    pb.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 228, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 80, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 288, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 178, in _build_role_dependencies
    defaults_data = utils.parse_yaml_from_file(defaults)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 419, in parse_yaml_from_file
    process_yaml_error(exc, data, path)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 397, in process_yaml_error
    msg = process_common_errors(msg, probline, mark.column)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 358, in process_common_errors
    elif len(probline) and probline[column] == ":" and probline.find("=") != -1:
IndexError: string index out of range
```

The issue ended up being that I missed a ':' between a variable key and value. I assume that this can be reproduced by leaving off a colon anywhere in a variable definition (or maybe even tasks). I specifically created this  it by creating a vars section and putting:

``` yaml

---
variable value
```

I fixed it by instead doing:

``` yaml

---
variable: value
```

@mpdehaan mentioned that this would be a pretty quick fix.

**Comment by mpdehaan** [comment]
Can you please include a gist of how the file that reproduced this problem and the output of "ansible --version"

Thanks!

**Comment by phillipuniverse** [comment]
Specific use case:
1. Playbook includes role
2. Role has a defaults/main.yml
3. defaults/main.yml has invalid YAML

playbook.yml:

``` yaml
---
- hosts: 127.0.0.1
  roles:
    - some_role
```

roles/some_role/defaults/main.yml

``` yaml
---
variable_name value
```

Execute with:

``` console
>> ansible-playbook --connection local -i 127.0.0.1 playbook.yml
```

The above example should produce the stack trace. Hopefully that's enough information.

**Comment by mpdehaan** [comment]
I could not reproduce this on the latest development branch, so I'm going to mark this as closed.

The error message this produces for me is currently:

```
 ERROR: /tmp/break/defaults/main.yml must be stored as dictonary/hash: <type 'str'>
```

It's not perfect, but it's not a traceback!

**Comment by phillipuniverse** [comment]
Great, looks like it was resolved. This was on development from a couple of weeks ago. Thanks!

**Comment by phillipuniverse** [comment]
Just updated to the latest from devel, can confirm no more stack trace. Thanks!
