### ISSUE TITLE
Unable to install ansible (devel) into virtualenv using pip

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#4523]
This may be my lack of understanding about virtualenv+pip (and `.pth` and `.egg-link` files), but it appears that installing ansible devel into a virtualenv using pip fails to setup the environment properly.  Suggestions appreciated if I am doing something incorrectly.
## Steps to reproduce
1. Create the virtual env

```
# virtualenv ~/.env
```
1. Activate virtualenv

```
# source ~/.env/bin/activate.sh
```
1. Install ansible development branch

```
(.env)# pip install -vvvv -U -e git+https://github.com/ansible/ansible.git@devel#egg=ansible
Obtaining ansible from git+https://github.com/ansible/ansible.git@devel#egg=ansible
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git config remote.origin.url
  https://github.com/ansible/ansible.git
  Clone in ./.env/src/ansible exists, and has correct URL (https://github.com/ansible/ansible.git)
  Updating ./.env/src/ansible clone (to devel)
  Running command /usr/bin/git fetch -q
  Running command /usr/bin/git show-ref
  ebbf845e099ea08d14d64f65767a0b06f06b5ca9 refs/heads/devel
  ebbf845e099ea08d14d64f65767a0b06f06b5ca9 refs/remotes/origin/HEAD
  ebbf845e099ea08d14d64f65767a0b06f06b5ca9 refs/remotes/origin/devel
  53c927ff264a5f03638322ff5f682012d01104eb refs/remotes/origin/release-0.6
  6bb9814b9fef197ff252514d788b9653b9da4981 refs/remotes/origin/release-0.7
  2bdad2c393afabb8670c3a2162938414caec3019 refs/remotes/origin/release-0.8
  0115d4b44263ad6dbeeccb2f22635654c7fc03cb refs/remotes/origin/release0.9
  8d1bea4ed0d5c19ba867fd421a9a123ddc5e6dc2 refs/remotes/origin/release1.0
  2f944d87f694593cf1b8838b91bc9b87cad05068 refs/remotes/origin/release1.1
  8584a945d689a02d8b1fb3ede9043433d364c23c refs/remotes/origin/release1.2
  715f25efbc04fe0f42c0e1cf1ebf4269001f3ded refs/remotes/origin/release1.2.1
  863b88ba44ac9bb41401d634a2374c7b4d01ff89 refs/remotes/origin/release1.2.2
  7249d649320659f42f68fd354faecd50f27721d3 refs/remotes/origin/release1.2.3
  272bdebd25c4ea46d77e32dea815b0a38f44ff6c refs/remotes/origin/release1.3.0
  cac9e02aead564aece043d43a8aee4fa3bfe3faa refs/remotes/origin/release1.3.1
  9d5d88b59fa3fdbbec4f4cb269c446c666e3abbb refs/remotes/origin/release1.3.2
  291649c15d3fc9989152f6d2360c80db63004af7 refs/remotes/origin/release1.3.3
  2e1b59a9d2440be500cbb73117ffcf60a5bc137b refs/tags/0.0.1
  09e690fd7c303466179cdf417f50de64875a9657 refs/tags/0.0.2
  695d8fe31ebaa4f21e43d55888c8e94486146575 refs/tags/0.3
  65c47c0778665770897c2b4d36ffa202796fbc16 refs/tags/0.3.1
  ce9356486e0bcd25af933e0227142c02de171339 refs/tags/0.4
  777908a72fb6c410e180442ea0da7ad738a1504e refs/tags/0.4.1
  08ad7a4e3382f6117ccf6e5de339bbda6c22aebe refs/tags/0.5
  047e17b7ec7a8128981cc3c9be989ac01779dfa2 refs/tags/0.6
  e7a03888fa971b766a9b0a751229fa77205760d5 refs/tags/0.7
  e63f401ec65edfd9be0966ea157669f3134a6531 refs/tags/0.7.1
  b6d5e0d1ed1f2d18d2d8ae1cae7b4a31af64bdfe refs/tags/0.7.2
  ce616234df1cb4d2c10208ffcc74cffb9bedb8f7 refs/tags/0.8
  0115d4b44263ad6dbeeccb2f22635654c7fc03cb refs/tags/v0.9
  d14f215b640c620c7ef2ec05b1828f57f96d148a refs/tags/v1.0
  58014ee0d7e5454104a883ccb08dbba950787dd2 refs/tags/v1.1
  8053386fb6168af0b0b4df20f8af79633f5113f3 refs/tags/v1.2
  3dcdc1e7fea0a1ee948f4bff789f6e4dc071bd1a refs/tags/v1.2.1
  17cef26a5325bdaa2ce95936dc484465590e37ec refs/tags/v1.2.2
  24c7be04e1b1aeb31a97f212319680aa1f367d99 refs/tags/v1.2.3
  a21d66083581e016cb375f9c4fd0204aee5349bd refs/tags/v1.3.0
  1d831306aecbfb53a25f973d3d578c316c244741 refs/tags/v1.3.1
  ebbbb9814df8431d179ee3165b6f2c0f27f4aa67 refs/tags/v1.3.2
  2bde1a3e8611940be26157745248c76b6c6e2102 refs/tags/v1.3.3
  Running command /usr/bin/git reset --hard -q ebbf845e099ea08d14d64f65767a0b06f06b5ca9
  Running setup.py egg_info for package ansible
    Running command python setup.py egg_info
    running egg_info
    writing requirements to ansible.egg-info/requires.txt
    writing ansible.egg-info/PKG-INFO
    writing top-level names to ansible.egg-info/top_level.txt
    writing dependency_links to ansible.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    reading manifest file 'ansible.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'packaging/distutils/setup.py'
    writing manifest file 'ansible.egg-info/SOURCES.txt'
Installing collected packages: ansible
  Running setup.py develop for ansible
    Running command /root/.env/bin/python -c "import setuptools; __file__='/root/.env/src/ansible/setup.py'; exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps
    running develop
    running egg_info
    writing requirements to ansible.egg-info/requires.txt
    writing ansible.egg-info/PKG-INFO
    writing top-level names to ansible.egg-info/top_level.txt
    writing dependency_links to ansible.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    reading manifest file 'ansible.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'packaging/distutils/setup.py'
    writing manifest file 'ansible.egg-info/SOURCES.txt'
    running build_ext
    Creating /root/.env/lib/python2.6/site-packages/ansible.egg-link (link to .)
    ansible 1.4 is already the active version in easy-install.pth
    Installing ansible script to /root/.env/bin
    Installing ansible-playbook script to /root/.env/bin
    Installing ansible-pull script to /root/.env/bin
    Installing ansible-doc script to /root/.env/bin

    Installed /root/.env/src/ansible
Successfully installed ansible
Cleaning up...
  Removing temporary dir /root/.env/build...
```
1. Verify version of ansible

```
(.env)# ansible --version
```
## Actual Result

``` python
Traceback (most recent call last):
  File "/root/.env/bin/ansible", line 8, in <module>
    execfile(__file__)
  File "/root/.env/src/ansible/bin/ansible", line 24, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
```
## Expected Result

```
ansible 1.4
```
## Other Information
- In the output pasted above, it strikes me that pip warned about a missing distutils/setup.py file:

```
    warning: no files found matching 'packaging/distutils/setup.py'
```
- Seems this may not be unique to ansible, or a bug at all.  
  - https://github.com/pypa/pip/issues/435
  - http://svn.python.org/projects/sandbox/trunk/setuptools/doc/formats.txt#egg-links
- Pip installs the ansible.egg-link file

```
# cat /root/.env/lib/python2.6/site-packages/ansible.egg-link
/root/.env/src/ansible
```
- Pip installs a easy-install.pth file

```
# cat /root/.env/lib/python2.6/site-packages/easy-install.pth
import sys; sys.__plen = len(sys.path)
/root/.env/src/ansible
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
```

**Comment by jlaska** [comment]
Note, changing the easy-install.pth file that pip installed as noted below makes things magically work.  However, I doubt this is the proper way to resolve this issue.

``` diff
--- /root/.env/lib/python2.6/site-packages/easy-install.pth 2013-10-15 16:26:04.000000000 +0000
+++ /root/.env/lib/python2.6/site-packages/easy-install.pth 2013-10-15 16:26:12.000000000 +0000
@@ -1,3 +1,3 @@
 import sys; sys.__plen = len(sys.path)
-/root/.env/src/ansible
+/root/.env/src/ansible/lib
 import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)

```

``` bash
# python -c 'import ansible; print ansible.__version__'
1.4
```

Could this be a matter of how setup.py is used, or how the ansible repository is structured?

**Comment by mpdehaan** [comment]
AFAIK, this only happens when doing it via pip+git blarg and does not happen with regular pip

Solution is to just do a checkout and do "source ./hacking/env-setup"

This is also nice because it presumes no knowledge of virtualenv and doesn't require anything to be installed either.

**Comment by jlaska** [comment]
For my use case, virtualenv is a requirement.  I've worked around the issue now by doing ...

```
source ~/.env/bin/activate.sh
git clone https://github.com/ansible/ansible.git && cd ansible
python setup.py sdist
pip install dist/ansible-1.4.tar.gz
```

If anyone understands why virtualenv+pip+ansible.git don't play nicely together, don't hesitate to share.

**Comment by hmalphettes** [comment]
My colleagues and myself are reproducing this without virtualenv on macosx:

```
sudo pip install -e git+https://github.com/ansible/ansible.git@devel#egg=ansible --upgrade
```

The workaround provided from @jlaska works for us:

```
sed -i 's~/src/ansible.*~/src/ansible/lib~g' /usr/local/lib/python2.7/site-packages/easy-install.pth
```
