### ISSUE TITLE
Passing an array of tags to role dependencies causes a traceback

### ISSUE THREAD

**Issue by briceburg** [ansible/ansible#4524]
A non handled exception occurs when passing tags as an array to a role dependency.

I'm personally unsure if tags should be allowed to be passed in role dependency files in the first place (it seemingly can lead to an incosistent / hard to debug state)... but it does allow to pass a tag as a string. Perhaps a warning message or proper implementation would be better.

Example:

[applications/test_app/meta/main.yml]

```

---
dependencies:
  - { role: application, namespace: 'test_app' }
  - { role: '../services/test_service', namespace: 'test_service', tags: ['deploy','prepare'] }
```

Output:

```
nesta@cicayda:~/git/SysOps/automation$ ansible-playbook -i hosts/chi.inventory application.yml --extra-vars="host_group=blubot namespace=test_app git_branch=aaa" --tags="prepare"
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 268, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 208, in main
    pb.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 228, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 81, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 300, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 249, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 249, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 217, in _build_role_dependencies
    included_dep_vars["tags"] = passed_vars["tags"].copy()
AttributeError: 'list' object has no attribute 'copy'
```

**Comment by jctanner** [comment]
@briceburg I can not reproduce this with the latest devel or 84a57b75450fa513ccf9e4132d66c0a67cd08c59 ...

```
jtanner@u1304:~/issues/4524-tag_array_roles$ tree .
.
├── inventory
├── roles
│   ├── common
│   │   ├── files
│   │   ├── handlers
│   │   ├── tasks
│   │   │   └── main.yml
│   │   ├── templates
│   │   └── vars
│   └── foo
│       ├── files
│       ├── handlers
│       ├── meta
│       │   └── main.yml
│       ├── tasks
│       │   └── main.yml
│       ├── templates
│       └── vars
└── site.yml

14 directories, 5 files
jtanner@u1304:~/issues/4524-tag_array_roles$ cat roles/foo/meta/main.yml 
---
dependencies:
    - { role: common, param1: foobar, param2: [1,2,3], tags: ['a', 'b'] }

jtanner@u1304:~/issues/4524-tag_array_roles$ ansible-playbook -i inventory site.yml --tags="c"
ERROR: tag(s) not found in playbook: c.  possible values: a,b

jtanner@u1304:~/issues/4524-tag_array_roles$ ansible-playbook -i inventory site.yml --tags="a"

PLAY [localhost] ************************************************************** 

TASK: [common | debug msg="common task 1"] ************************************ 
ok: [localhost] => {
    "item": "", 
    "msg": "common task 1"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```

Could you specify what version/commit you are using, and if possible retest with the latest devel?

**Comment by jctanner** [comment]
Tests still pass with d154bf87812209409a673fd7f9848d75701e2f32

@briceburg If you are able to reproduce this with a fresh checkout, please open a new ticket.

**Comment by eigood** [comment]
Ah, I see how to replicate this now.  A role that has a dep on another role, will cause this issue.  If a playbook references a role, and tags it, ansible will apply those tags to the role.  But when the top-level role has a meta/main.yml, with dependencies, then the tags will not be copied, and the exception will be thrown.

I verified against e3e6f02835b1bdf16716c28ada8692149109fda8, after converting to a deb.

**Comment by eigood** [comment]
And you can work around it by adding "tags: []" to the interior role.

**Comment by joshuaconner** [comment]
Just ran into this – will this be reopened? Is there a new issue? Should I/@elgood open one?

**Comment by jimi-c** [comment]
@eigood or @joshuaconner could you provide a sample playbook/set of roles that reproduces this against devel? If so, we'll reopen it.

**Comment by geerlingguy** [comment]
Here's an example:

Let's say I have a role `php` that defines a dependency on the role `apache`. If I do this in my main playbook, I'll get the error described above:

```
roles:
  - apache
  - { role: php, tags: ["php"] }
```

I have to also give apache at least an empty tags list in order for Ansible to run the playbook without exceptions, so I could do:

```
  - { role: apache, tags: [] }
  - { role: php, tags: ["php"] }
```

(or, of course, I could add a tag to the apache role if I so desired). The point is, if you add a tag to a role, all that role's dependencies must also have tags defined, or I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 307, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 247, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 247, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 85, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 344, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 293, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 240, in _build_role_dependencies
    included_dep_vars["tags"] = passed_vars["tags"].copy()
AttributeError: 'list' object has no attribute 'copy'
```

**Comment by sivel** [comment]
@geerlingguy This was recently fixed in #6248

**Comment by geerlingguy** [comment]
Oh, nice!

**Comment by drybjed** [comment]
Comfirming the issue on latest devel branch:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 307, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 247, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 248, in run
    play = Play(self, play_ds, play_basedir, included_roles=included_roles, vault_password=self.vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 85, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 358, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 307, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 241, in _build_role_dependencies
    passed_vars['tags'] = __merge_tags(role_vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 239, in __merge_tags
    return list(set(old_tags + new_tags))
TypeError: cannot concatenate 'str' and 'list' objects
```
