### ISSUE TITLE
TypeError: connect() takes at most 3 arguments (7 given) when creating a user

### ISSUE THREAD

**Issue by dckc** [ansible/ansible#4574]
What I did:
1. Installed Ansible from git:
   $ ansible --version
   ansible 1.4 (devel 242f20c297) last updated 2013/10/17 18:08:02 (GMT -500)

on an Ubuntu 12.04 machine
1. Created a simple playbook to create a user
   https://gist.github.com/dckc/7033952
2. $ ansible-playbook -i ../ssh_mgmt/ssh_hosts jenkins_acct.yml

Expected: a jenkins account on bmidev2
Actual:

```
PLAY [bmidev2] **************************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [bmidev2] => Traceback (most recent call last):
  File "/home/dconnolly/src/ansible/lib/ansible/runner/__init__.py", line 389, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/dconnolly/src/ansible/lib/ansible/runner/__init__.py", line 474, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/dconnolly/src/ansible/lib/ansible/runner/__init__.py", line 643, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
TypeError: connect() takes at most 3 arguments (7 given)


TASK: [user name=jenkins comment="Jenkins CI Service"] ************************ 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/dconnolly/jenkins_acct.retry

bmidev2                    : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by dckc** [comment]
once more, with feeling...

```
dconnolly@bid-bse01:~/src/ansible$ git describe
v1.2-1723-g242f20c
dconnolly@bid-bse01:~/src/ansible$ type ansible
ansible is hashed (/usr/local/src/ansible/bin/ansible)
dconnolly@bid-bse01:~/src/ansible$ ansible -m setup -i localhost, -c local all
localhost | FAILED => Traceback (most recent call last):
  File "/usr/local/src/ansible/lib/ansible/runner/__init__.py", line 389, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/src/ansible/lib/ansible/runner/__init__.py", line 474, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/src/ansible/lib/ansible/runner/__init__.py", line 643, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
TypeError: connect() takes at most 3 arguments (7 given)
```

**Comment by dckc** [comment]
Problem went away with a clean check-out. Wierd.
