### ISSUE TITLE
authorized_keys bug traceback

### ISSUE THREAD

**Issue by Daemoen** [ansible/ansible#4599]
<pre>
ok: [shd9.quantifind.com] => (item={'comment': 'Ruoke Yang, Intern', 'shell': '/bin/bash', 'name':
'ruoke', 'home': '/home/ruoke', 'password': u'$6$qFindR0x$KHFkjjDgTaSbTCDROJ1cmPiPP9/heZaNtfPy8ROYF
CIrjqUezDTZYS9ic2u89R6Cl6AgCNb4ETkasZwbI2t7C.', 'id': 2035})
fatal: [shd6.quantifind.com] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1382148491.98-47941295244299/authorized_key", line 1303, in <mod
ule>
    main()
  File "/root/.ansible/tmp/ansible-1382148491.98-47941295244299/authorized_key", line 364, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1382148491.98-47941295244299/authorized_key", line 335, in enfor
ce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str

fatal: [shd7.quantifind.com] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1382148491.98-84956261098277/authorized_key", line 1303, in <mod
ule>
    main()
  File "/root/.ansible/tmp/ansible-1382148491.98-84956261098277/authorized_key", line 364, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1382148491.98-84956261098277/authorized_key", line 335, in enfor
ce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str

changed: [shm0.quantifind.com] => (item={'comment': 'ItOps - Primary Operations Shared User', 'shel
l': '/bin/zsh', 'name': 'itops', 'home': '/home/itops', 'password': u'$6$jwVKWtNiBrQs$6bYNYuC5Qmrdv
SKGIRqSx/9C8.yOucK1qt.cktZlCPQEAzzvL8sTCkWj0Y2EU0nsxHkLBmngQPlR7VfmhG6MI/', 'id': 1500})
ok: [shd9.quantifind.com] => (item={'comment': 'Jason Sobel, VP Engineering', 'shell': '/bin/bash',
 'name': 'jason', 'home': '/home/jason', 'password': u'$6$mUG.17HloQ0AsJO$nP6fpdiH.CwBqpZQ5/6CNAseM
vVQ6kptG74bxkSWtqrsesomkQT88YvtDxBzqA/HDlNiq4Nj1kCLZLrGwI6.o1', 'id': 2036})
</pre>

**Comment by mpdehaan** [comment]
cc @jimi-c

**Comment by jimi-c** [comment]
@Daemoen I believe @jctanner fixed this in the original issue, can you confirm if the patch he posted works for you?
