### ISSUE TITLE
Traceback in `parsing/splitter.py`

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#46379]
##### SUMMARY

Recent changes to `parsing/splitter.py` in https://github.com/ansible/ansible/pull/45853 are causing a traceback in the `win_psmodule` integration tests:

https://app.shippable.com/github/ansible/ansible/runs/86369/14/console

This issue went undetected in the original PR because the `win_psmodule` integration tests are not included in the Windows smoke tests.

##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

parsing/splitter.py

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (detached HEAD b72e989e18) last updated 2018/10/01 17:07:58 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/PRODUCTION/ansible/lib/ansible
  executable location = /Users/mclay/code/PRODUCTION/ansible/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 11:39:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

`ansible-test windows-integration win_psmodule --docker --windows 2016 -vvv`

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests fail with a traceback:

```
Traceback (most recent call last):
  File "/root/ansible/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/root/ansible/lib/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/root/ansible/lib/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/root/ansible/lib/ansible/playbook/__init__.py", line 106, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader, vars=vars)
  File "/root/ansible/lib/ansible/playbook/play.py", line 112, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/root/ansible/lib/ansible/playbook/base.py", line 227, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/root/ansible/lib/ansible/playbook/play.py", line 197, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/root/ansible/lib/ansible/playbook/role/__init__.py", line 161, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/root/ansible/lib/ansible/playbook/role/__init__.py", line 228, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader, variable_manager=self._variable_manager)
  File "/root/ansible/lib/ansible/playbook/helpers.py", line 80, in load_list_of_blocks
    loader=loader,
  File "/root/ansible/lib/ansible/playbook/block.py", line 93, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/root/ansible/lib/ansible/playbook/base.py", line 227, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/root/ansible/lib/ansible/playbook/block.py", line 129, in _load_block
    use_handlers=self._use_handlers,
  File "/root/ansible/lib/ansible/playbook/helpers.py", line 278, in load_list_of_tasks
    variable_manager=variable_manager,
  File "/root/ansible/lib/ansible/playbook/helpers.py", line 80, in load_list_of_blocks
    loader=loader,
  File "/root/ansible/lib/ansible/playbook/block.py", line 93, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/root/ansible/lib/ansible/playbook/base.py", line 227, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/root/ansible/lib/ansible/playbook/block.py", line 129, in _load_block
    use_handlers=self._use_handlers,
  File "/root/ansible/lib/ansible/playbook/helpers.py", line 125, in load_list_of_tasks
    (action, args, delegate_to) = args_parser.parse()
  File "/root/ansible/lib/ansible/parsing/mod_args.py", line 295, in parse
    action, args = self._normalize_parameters(thing, action=action, additional_args=additional_args)
  File "/root/ansible/lib/ansible/parsing/mod_args.py", line 160, in _normalize_parameters
    args = self._normalize_new_style_args(thing, action)
  File "/root/ansible/lib/ansible/parsing/mod_args.py", line 205, in _normalize_new_style_args
    args = parse_kv(thing, check_raw=check_raw)
  File "/root/ansible/lib/ansible/parsing/splitter.py", line 62, in parse_kv
    vargs = split_args(args)
  File "/root/ansible/lib/ansible/parsing/splitter.py", line 275, in split_args
    params[-1] += '\n'
IndexError: list index out of range
```

**Comment by mattclay** [comment]
cc @dagwieers @jborean93

**Comment by mattclay** [comment]
PR to work around the issue in the failing test: https://github.com/ansible/ansible/pull/46378

**Comment by mattclay** [comment]
The test that uncovered this this should provide a good basis for an integration test to prevent this regression in the future once the underlying issue has been fixed.

**Comment by dagwieers** [comment]
I'll look into it.

**Comment by jborean93** [comment]
Looks like it's not comments that are the cause but the newline in the beginning.

**Comment by dagwieers** [comment]
I was hunting ghost for a short while there :-P

**Comment by Akasurde** [comment]
resolved_by_pr #46380

**Comment by ps-jay** [comment]
Hi all,

FYI this bug also effects if `--extra-vars` is provided on the CLI with a leading new-line.

For example:
```
root@a7c2d2b0d17a:/ansible# /usr/local/bin/ansible-playbook -vvvv rds_db.yml --extra-vars '
> stage=delete
> '

ansible-playbook 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.16 (default, Jul 13 2019, 16:04:25) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Set default localhost to localhost
Parsed /etc/ansible/hosts inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 104, in run
    loader, inventory, variable_manager = self._play_prereqs()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 484, in _play_prereqs
    variable_manager = VariableManager(loader=loader, inventory=inventory, version_info=CLI.version_info(gitinfo=False))
  File "/usr/local/lib/python2.7/site-packages/ansible/vars/manager.py", line 99, in __init__
    self._extra_vars = load_extra_vars(loader=self._loader)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/vars.py", line 136, in load_extra_vars
    data = parse_kv(extra_vars_opt)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/splitter.py", line 62, in parse_kv
    vargs = split_args(args)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/splitter.py", line 275, in split_args
    params[-1] += '\n'
IndexError: list index out of range
```

**Comment by ppoetz** [comment]
This also occures by cli calls as @ps-jay already mentioned.

For example in my Jenkinsfile:
`sh """
                    ansible-playbook inventory/someapp/${env.ENVIRONMENT_NAME}/playbooks/deploy.yml \
                    -i inventory/someapp/${env.ENVIRONMENT_NAME}/inventory.yml \
                    -e " \
                    app_version=${params.VERSION} \
                    catalog_user=${CATALOG_USER} \
                    catalog_password=${CATALOG_PASSWORD} \
                    env_path=../env/ \
                    hostnames=apps \
                    slack_token=${SLACK_TOKEN} \
                    " \
                    --key-file "${KEY_FILE}" \
                    --extra-vars "@inventory/wastebox/extra.yml" \
                    -vv
                   """`

I just upgraded from 2.7.8 to 2.8.3 and this issue is new.

Output:
`
[2019-08-06T10:01:26.803Z] ERROR! Unexpected Exception, this is probably a bug: list index out of range
[2019-08-06T10:01:26.803Z] the full traceback was:
[2019-08-06T10:01:26.803Z] 
[2019-08-06T10:01:26.803Z] Traceback (most recent call last):
[2019-08-06T10:01:26.803Z]   File "/usr/local/bin/ansible-playbook", line 110, in <module>
[2019-08-06T10:01:26.803Z]     exit_code = cli.run()
[2019-08-06T10:01:26.803Z]   File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 104, in run
[2019-08-06T10:01:26.803Z]     loader, inventory, variable_manager = self._play_prereqs()
[2019-08-06T10:01:26.803Z]   File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 484, in _play_prereqs
[2019-08-06T10:01:26.803Z]     variable_manager = VariableManager(loader=loader, inventory=inventory, version_info=CLI.version_info(gitinfo=False))
[2019-08-06T10:01:26.803Z]   File "/usr/local/lib/python2.7/site-packages/ansible/vars/manager.py", line 98, in __init__
[2019-08-06T10:01:26.803Z]     self._extra_vars = load_extra_vars(loader=self._loader)
[2019-08-06T10:01:26.803Z]   File "/usr/local/lib/python2.7/site-packages/ansible/utils/vars.py", line 136, in load_extra_vars
[2019-08-06T10:01:26.803Z]     data = parse_kv(extra_vars_opt)
[2019-08-06T10:01:26.803Z]   File "/usr/local/lib/python2.7/site-packages/ansible/parsing/splitter.py", line 62, in parse_kv
[2019-08-06T10:01:26.803Z]     vargs = split_args(args)
[2019-08-06T10:01:26.803Z]   File "/usr/local/lib/python2.7/site-packages/ansible/parsing/splitter.py", line 206, in split_args
[2019-08-06T10:01:26.803Z]     params[-1] += ' '
[2019-08-06T10:01:26.803Z] IndexError: list index out of range
`

**Comment by georgej-github** [comment]
I can confirm the same issue by ppoetz and ps-jay for 2.8.3, any update on this? Thanks.

**Comment by eightlimbed** [comment]
I was battling with this for a couple days, and I'm still not exactly sure what was causing the IndexError, but I narrowed it down to a task in my playbook that looked like this:
```
- name: "foo"
  when: foo.rc == 0 or bar is defined
  ignore_errors: yes
  become: true
  shell: |

    # get the three most recent falcon debug logs
    logs=$(ls -Art /var/log/foo/*.log | tail -n 3 2>/dev/null)

    if [ -z "$logs" ]; then
      echo 'Found no logs found. Searched for /var/log/foo/*.log'
      exit 0
    fi

    # transmit $logs 
    host='foo.bar.com'
    port='123'
    placeholder=$(mktemp)
    remote_syslog -d $host -p $port $placeholder
    for log in $(echo "$logs"); do cat $log >> $placeholder; sleep 1; done
    rm -rf $placeholder

    # give a few seconds to transmit logs before killing remote_syslog
    sleep 10
    pkill remote_syslog || true
  register: shell_task

```

I thought, maybe its the `|| true` messing with the yaml `|` character used for a multiline script, but that wasn't it.

My solution was to take this script and put it in `roles/foo/files/foo.sh` and replace the `shell` module with 
```
script: "{{ role_path }}/files/foo.sh"
```
No more IndexError

**Comment by boweevil** [comment]
I get the same error on any version >= 2.8.0 when using new lines in the extra vars argument.

```
the full traceback was:

Traceback (most recent call last):
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/lib/python3.7/site-packages/ansible/cli/playbook.py", line 104, in run
    loader, inventory, variable_manager = self._play_prereqs()
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/lib/python3.7/site-packages/ansible/cli/__init__.py", line 482, in _play_prereqs
    variable_manager = VariableManager(loader=loader, inventory=inventory, version_info=CLI.version_info(gitinfo=False))
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/lib/python3.7/site-packages/ansible/vars/manager.py", line 99, in __init__
    self._extra_vars = load_extra_vars(loader=self._loader)
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/lib/python3.7/site-packages/ansible/utils/vars.py", line 136, in load_extra_vars
    data = parse_kv(extra_vars_opt)
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/lib/python3.7/site-packages/ansible/parsing/splitter.py", line 62, in parse_kv
    vargs = split_args(args)
  File "/home/boweevil/.local/share/virtualenvs/ansible_version-Yf50F4xc/lib/python3.7/site-packages/ansible/parsing/splitter.py", line 275, in split_args
    params[-1] += '\n'
IndexError: list index out of range
```

Example:
```
ansible-playbook -vvv -i localhost, \
    --extra-vars "
        var1=$var1
        var2=$var2
    " \
    test.yml
```

I'm able to work around the issue with declaring each variable in a separate -e argument like so:
```
ansible-playbook -vvv -i localhost, \
    -e "var1=$var1" \
    -e "var2=$var2" \
    test.yml
```

**Comment by panzerfahrer** [comment]
I encountered this with `include_tasks`:

```
- name: Run more tasks
   include_tasks: more.yml
```

The first task started with:

```
---
- name: First task
  shell: |
    echo "do something"
```

I _fixed_ it by adding a line comment behind the pipe:

```
---
- name: First task
  shell: | # fixing comment
    echo "do something"
```
