### ISSUE TITLE
ansible-galaxy install from large requirements.yml file results in 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#46650]
##### SUMMARY

When installing a number of roles from Ansible Galaxy using the attached requirements.yml file (see gist linked later in this issue), I get an error message `'NoneType' object is not iterable`

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`ansible-galaxy`

##### ANSIBLE VERSION

```paste below
ansible 2.6.3
  config file = /Users/jeff.geerling/Downloads/testing/ansible.cfg
  configured module search path = [u'/Users/jeff.geerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/jeff.geerling/Downloads/testing/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/Users/jeff.geerling/Downloads/testing/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_ROLES_PATH(/Users/jeff.geerling/Downloads/testing/ansible.cfg) = [u'/Users/jeff.geerling/Downloads/testing/roles
```

##### OS / ENVIRONMENT

macOS Mojave

##### STEPS TO REPRODUCE

```yaml
ansible-galaxy install --force -r requirements.yml
```

Using the following files in any directory:

* [`ansible.cfg`](https://gist.github.com/geerlingguy/b2fa14c6408895c114d5591c0c0a6b1e)
* [`requirements.yml`](https://gist.github.com/geerlingguy/5432da61993d130819b60e3812a0cabd)

(This requirements file is taken directly from [Drupal VM](https://github.com/geerlingguy/drupal-vm), in the provisioning folder.)

##### EXPECTED RESULTS

* All the roles specified in the requirements file should be installed.

##### ACTUAL RESULTS

* Once it reaches `- downloading role 'nodejs', owned by geerlingguy`, it fails:

```
...
- geerlingguy.nginx (2.6.0) was installed successfully
- changing role geerlingguy.nodejs from 4.2.2 to 4.2.2
- downloading role 'nodejs', owned by geerlingguy
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable
to see the full traceback, use -vvv
```

Note that this affects both 2.6.3 and 2.7.0 (those are the two versions I've tested so far.)

**Comment by geerlingguy** [comment]
Running the test again now (after repeating the result 3x on both 2.6.3 and 2.7.0), with higher verbosity (`-vvv`); results from that run:

```
Processing role geerlingguy.nodejs 
Opened /Users/jeff.geerling/.ansible_galaxy
- downloading role 'nodejs', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=nodejs
https://galaxy.ansible.com/api/v1/roles/465/versions/?page_size=50
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 152, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 395, in execute_install
    installed = role.install()
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/role.py", line 246, in install
    for role_version in role_versions:
TypeError: 'NoneType' object is not iterable
```

**Comment by geerlingguy** [comment]
There are only 26 releases for the node.js project, so I'm not sure why it's not working correctly, at least at a glance.

**Comment by geerlingguy** [comment]
If I comment out the `nodejs` role, it then fails on the `php` role. And if I comment out the `php` role, then it fails on the `php-memcached` role, etc.

I'm going to downgrade to Ansible 2.5 and see if the bug exists in that version too.

**Comment by geerlingguy** [comment]
So after trying a dozen or so different permutations, I started getting something like:

```
Processing role geerlingguy.php-tideways 
Opened /Users/jeff.geerling/.ansible_galaxy
- downloading role 'php-tideways', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php-tideways
ERROR! Unexpected Exception, this is probably a bug: Failed to connect to galaxy.ansible.com at port 443: [Errno 8] nodename nor servname provided, or not known
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 162, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 398, in execute_install
    installed = role.install()
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/role.py", line 209, in install
    role_data = api.lookup_role_by_name(self.src)
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 193, in lookup_role_by_name
    data = self.__call_galaxy(url)
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 93, in __call_galaxy
    timeout=20)
  File "/usr/local/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 1162, in open_url
    client_cert=client_cert, client_key=client_key, cookies=cookies)
  File "/usr/local/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 1070, in open
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 427, in open
    req = meth(req)
  File "/usr/local/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 781, in http_request
    raise ConnectionError('Failed to connect to %s at port %s: %s' % (self.hostname, self.port, to_native(e)))
ConnectionError: Failed to connect to galaxy.ansible.com at port 443: [Errno 8] nodename nor servname provided, or not known
```

Then I realized a pattern; the installation would always seem to fail after about 20 roles.

So... maybe the Galaxy API starts killing connections after 20 roles are installed? Not sure exactly what's happening, but there was no single role or version that seemed to cause the problem to be reproducible, only the total number of roles in the requirements file.

If I kept the total number of roles 20 or fewer, the install command worked every time.

If I added one more role—any role—it would fail.

**Comment by webknjaz** [comment]
That's interesting.. Do we need some exponential backoff to better manage hitting galaxy?

**Comment by geerlingguy** [comment]
Not sure, but one thing I'm wondering is if this is something client-side or some kind of rate limiting on the Galaxy servers or some sort of firewall prior to the servers?

**Comment by webknjaz** [comment]
cc @cutwater do you know anything about Galaxy's rate limiting?

**Comment by markdorison** [comment]
I am experiencing this issue as well.

**Comment by kentr** [comment]
I'm getting this also.

* Ansible 2.7
* MacOS High Sierra

However, when I increase the `page_size` query parameter in `GalaxyAPI.fetch_role_related()`, I get a different error:

```
Processing role geerlingguy.nodejs 
- changing role geerlingguy.nodejs from 4.2.2 to 4.2.2
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'nodejs', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=nodejs
https://galaxy.ansible.com/api/v1/roles/465/versions/?page_size=100
- downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/4.2.2.tar.gz
- extracting geerlingguy.nodejs to /Users/Work/eclipse-workspace/rd/cgs/provisioning/roles/geerlingguy.nodejs
- geerlingguy.nodejs (4.2.2) was installed successfully
Processing role geerlingguy.php 
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=100
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.7.0.tar.gz
 [ERROR]: failed to download the file: Failed to connect to github.com at port 443: [Errno 8] nodename nor servname provided, or not known
```

Which makes me wonder if something *else* is throttling all connections, exactly at that point.  The GitHub fetch for `nodejs` is successful, but the GitHub fetch for `php` fails.

**Comment by kentr** [comment]
Hmm.

I put the `page_size` back to `50`, and added an exception handler to `fetch_role_related()`.

It looks like the GalaxyAPI query for the second page of results is getting blocked in the same way as the GitHub fetches:

```
Processing role geerlingguy.php 
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=50
 [ERROR]: failed to download the file: Failed to connect to galaxy.ansible.com at port 443: [Errno 8] nodename nor servname provided, or not known
```

**Comment by kentr** [comment]
I think this is related to #12259

I'm getting the `too many open files` error after upping `page_size`:

```
Processing role geerlingguy.php 
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=100
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.7.0.tar.gz
 [ERROR]: failed to download the file: Failed to connect to github.com at port 443: [Errno 8] nodename nor servname provided, or not known

 [WARNING]: - geerlingguy.php was NOT installed successfully.

Processing role geerlingguy.php-memcached 
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
 [WARNING]: - geerlingguy.php-memcached was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): [Errno 24] Too many open files: '/etc/ssl/certs'

Processing role geerlingguy.php-mysql 
Opened /Users/Work/.ansible_galaxy
ERROR! Unexpected Exception, this is probably a bug: [Errno 24] Too many open files: '/Users/Work/.ansible_galaxy'
the full traceback was:

Traceback (most recent call last):
  File "/Users/Work/Library/Python/2.7/bin/ansible-galaxy", line 118, in <module>
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/cli/galaxy.py", line 162, in run
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/cli/__init__.py", line 155, in execute
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/cli/galaxy.py", line 398, in execute_install
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/galaxy/role.py", line 209, in install
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/galaxy/api.py", line 67, in __init__
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/galaxy/token.py", line 41, in __init__
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/galaxy/token.py", line 48, in __open_config_for_read
IOError: [Errno 24] Too many open files: '/Users/Work/.ansible_galaxy'
```

It appears that whatever the very next request is, it's failing because of the open file limits.

This resolves the problem for me:

```
# Set soft open files limit to 1024
ulimit -S -n 1024
ansible-galaxy install --force -r requirements.yml
```

**Comment by webknjaz** [comment]
Hey @geerlingguy, can you confirm the ulimit suggestion?

**Comment by bcoca** [comment]
dmesg should show if you are hitting any resource limits

**Comment by bcoca** [comment]
it seems the rest of the code assumes role_versions can be none or empty, this specific code was added but does not keep the same assumption in mind, quick fix is just adding an `if`
