### ISSUE TITLE
playbook fails if there is "{{" in any modules Documentation section 

### ISSUE THREAD

**Issue by bennojoy** [ansible/ansible#4694]
The commit 3722bebb1d81864b481aa4626ced6df205829f33 causes the playbook to fail, if module that is executing has "{{" in it's Documentation section. Following is the traceback. The reason being the t.render(vars_input) function in module_common.py tries to substitute the "{{" in module's doc section. 

fatal: [localhost] => Traceback (most recent call last):
  File "/root/ansible/lib/ansible/runner/**init**.py", line 377, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/root/ansible/lib/ansible/runner/__init__.py", line 464, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/root/ansible/lib/ansible/runner/__init__.py", line 655, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/root/ansible/lib/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/root/ansible/lib/ansible/runner/__init__.py", line 289, in _execute_module
    (remote_module_path, module_style, shebang) = self._copy_module(conn, tmp, module_name, args, inject, complex_args)
  File "/root/ansible/lib/ansible/runner/__init__.py", line 838, in _copy_module
    in_path, complex_args, module_args, inject
  File "/root/ansible/lib/ansible/module_common.py", line 140, in modify_module
    module_data = self._template_imports(module_data)
  File "/root/ansible/lib/ansible/module_common.py", line 124, in _template_imports
    return t.render(vars_input)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render
    return self.environment.handle_exception(exc_info, True)
  File "<template>", line 280, in top-level template code
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 350, in getattr
    return getattr(obj, attribute)
UndefinedError: 'ec2' is undefined

**Comment by mpdehaan** [comment]
This is now fixed on the devel branch
