### ISSUE TITLE
NameError: global name 'item' is not defined

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#4737]
Task

```
    - yum: name={{ item }}
      with_items:
        - dos2unix
        - strace
      when: item != 'dos2unix'
      tags: conditional_list
```

Result

```
TASK: [yum name={{item}}] ***************************************************** 
fatal: [el6.lab.net] => Traceback (most recent call last):
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 389, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 466, in _executor_internal
    use_these_items.append(item)
NameError: global name 'item' is not defined


FATAL: all hosts have already failed -- aborting
```

**Comment by jctanner** [comment]
Resolved by 7b331ef6edb17b718e724033eb470f02592e0059
