### ISSUE TITLE
rpm_key doesn't import remote key

### ISSUE THREAD

**Issue by przemolb** [ansible/ansible#4743]
Example playbook:
- name: import HP SPP GPG key
  
  action: rpm_key state=present key=http://downloads.linux.hp.com/repo/spp/GPG-KEY-SPP

When I run:
ansible-playbook install-spp.yml ...
I get the following message:

fatal: [node1] => failed to parse: Traceback (most recent call last):
  File "/tmp/ansible-1383222123.08-223059426643390/rpm_key", line 1135, in ?
    main()
  File "/tmp/ansible-1383222123.08-223059426643390/rpm_key", line 195, in main
    RpmKey(module)
  File "/tmp/ansible-1383222123.08-223059426643390/rpm_key", line 87, in **init**
    keyid = self.getkeyid(keyfile)
  File "/tmp/ansible-1383222123.08-223059426643390/rpm_key", line 148, in getkeyid
    self.json_fail(msg="Unexpected gpg output")
AttributeError: RpmKey instance has no attribute 'json_fail'

This is ansible 1.4

Native command:
rpm --import http://downloads.linux.hp.com/repo/spp/GPG-KEY-SPP
just works.

**Comment by jctanner** [comment]
@przemolb I can not reproduce this as 4a3e828b8387ca386d6ac51d07302d08ceb95c14

Please indicate what version or hash of ansible you are using: "ansible --version"

**Comment by mpdehaan** [comment]
Closing this as fixed in latest.

**Comment by przemolb** [comment]
Which version of ansible was it fixed in ? I have used 1.4 cloned a few days ago.

**Comment by groks** [comment]
Same problem.

```
ansible --verison
ansible 1.4.3
```

Error:

```
fatal: [localhost] => failed to parse: SUDO-SUCCESS-krulqezflerwxgckedaupjamucpxtpdf
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 1225, in <module>
    main()
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 195, in main
    RpmKey(module)
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 87, in __init__
    keyid = self.getkeyid(keyfile)
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 148, in getkeyid
    self.json_fail(msg="Unexpected gpg output")
AttributeError: RpmKey instance has no attribute 'json_fail'
```

**Comment by jctanner** [comment]
@groks please open a new bug with an example of the task syntax and the key url.
