### ISSUE TITLE
jinja2 errors do not report line number in template

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4747]
ansible 1.3.3

Output from ansible with an erroneous template:

```
TASK: [build ISPn.cfg] ********************************************************
fatal: [localhost] => {'msg': "unexpected '}'", 'failed': True}
fatal: [localhost] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "unexpected '}'", 'failed': True}]}
```

This does not show the line number. But jinja2 _does_ report the line number in its exception traceback:

```
>>> import jinja2
>>> jinja2.Template(open("templates/ISP.cfg").read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
  File "<unknown>", line 131, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
>>>
```

The error is in fact in line 131.

**Comment by jctanner** [comment]
@candlerb Can you share an example playbook and template file that reproduces the issue?

**Comment by candlerb** [comment]
```
==> bug.inv <==
localhost ansible_ssh_connection=local

==> bug.yml <==
- hosts: localhost
  tasks:
    - template: src=bug.j2 dest=/tmp/foo

==> bug.j2 <==
One
Two
Three
This is an {{error}
Five
Six
```

Giving:

```
$ ansible-playbook bug.yml -i bug.inv

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [template src=bug.j2 dest=/tmp/foo] *************************************
fatal: [localhost] => {'msg': "unexpected '}'", 'failed': True}
fatal: [localhost] => {'msg': "unexpected '}'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

The error is shown, but the line number in the template is not. This seems to apply to all other template errors too, e.g. if a variable is undefined, or you try to access a non-existent attribute of an object.

```
==> bug.j2 <==
One
Two
Three
This is an {{error}}
Five
Six
```

Result:

```
fatal: [localhost] => {'msg': "One or more undefined variables: 'error' is undefined", 'failed': True}
fatal: [localhost] => {'msg': "One or more undefined variables: 'error' is undefined", 'failed': True}
```

I now use a little script to identify where the error is in a badly-formed template:

```
#!/usr/bin/python
import sys
import jinja2
jinja2.Template(open(sys.argv[1]).read())
```

It doesn't help for mis-spelled variables/attributes though.

**Comment by mpdehaan** [comment]
1.4 should already report line numbers of template error, so this is available in the pending release towards the end of this month.

Undefined variables will be unable to report line numers as we are templating the whole file.
