### ISSUE TITLE
apt module does not work for old version of python-apt

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#4869]
I've just been trying to trigger the simple command on remote Debian Lenny box:

``` yaml
- name: remove extra packages
  apt: pkg={{ item }} state=absent
  with_items:
  - nano
```

When run ansible produced the following error:

```
failed: [domain.com] => (item=nano) => {"failed": true, "item": "nano", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1384076413.61-29385143645352/apt", line 1342, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1384076413.61-29385143645352/apt", line 400, in main
    remove(module, packages, cache, p['purge'])
  File "/root/.ansible/tmp/ansible-1384076413.61-29385143645352/apt", line 250, in remove
    installed, upgradable, has_files = package_status(m, name, version, cache, state='remove')
  File "/root/.ansible/tmp/ansible-1384076413.61-29385143645352/apt", line 184, in package_status
    return ll_pkg.current_state == apt_pkg.CURSTATE_INSTALLED, pkg.isUpgradable, has_files
AttributeError: current_state
```

While doing some research on that it seems that `apt.Cache()._cache['foobar']` does not have attribute `current_state`:

```
m:~# python
Python 2.5.2 (r252:60911, Jan 24 2010, 14:53:14) 
[GCC 4.3.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
/usr/lib/python2.5/site-packages/apt/__init__.py:18: FutureWarning: apt API not stable yet
  warnings.warn("apt API not stable yet", FutureWarning)
>>> import apt_pkg
>>> x = apt.Cache()
>>> x
<apt.cache.Cache object at 0xb7f21a4c>
>>> cache['nano']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cache' is not defined
>>> nano='nano'
>>> x[nano]
<apt.package.Package object at 0xb711126c>
>>> x._cache[nano]
<pkgCache::Package object: Name:'nano' Section: 'editors' ID:803 Flags:0x0>
>>> y = x._cache[nano]
>>> pkg.current_state
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pkg' is not defined
>>> y.current_state
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: current_state
>>> y = x._cache['apt']
>>> y.current_state
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: current_state
>>> 
```

I'm running `ansible 1.4 (devel aa0577c211) last updated 2013/10/25 13:57:26 (GMT +400)`.

More info on versions for reference:
Facts for managed box:

``` json
{
        "ansible_distribution": "Debian", 
        "ansible_distribution_release": "NA", 
        "ansible_distribution_version": "5.0.10", 
        "ansible_kernel": "2.6.21.7-2.fc8xen", 
        "ansible_lsb": {
            "codename": "lenny", 
            "description": "Debian GNU/Linux 5.0.10 (lenny)", 
            "id": "Debian", 
            "major_release": "5", 
            "release": "5.0.10"
        }, 
        "ansible_machine": "i686", 
        "ansible_python_version": "2.5.2", 

}
```

Packages installed on the managed box:

```
m:~# dpkg-query -l apt python-apt aptitude apt-utils python
+++-===========================-===========================-======================================================================
ii  apt                         0.7.20.2+lenny2             Advanced front-end for dpkg
ii  apt-utils                   0.7.20.2+lenny2             APT utility programs
ii  aptitude                    0.4.11.11-1~lenny2          terminal-based package manager
ii  python                      2.5.2-3                     An interactive high-level object-oriented language (default version)
ii  python-apt                  0.7.7.1+nmu1                Python interface to libapt-pkg
```

**Comment by srgvg** [comment]
FYI - Debian 5 (Lenny) is an "old" and (by Debian) unsupported distribution, current stable being Debian 7

**Comment by timurb** [comment]
Yes, I know that. There is a single server left with Lenny in our setup.

**Comment by mpdehaan** [comment]
You probably are going to want to use the 'shell' module in this case.

I am ok with this being unsupported as it's a 2009 release, and security updates have been unavailable for over a year.

http://www.debian.org/releases/lenny/

"Security updates have been discontinued as of February 6th, 2012"

If this is painful and makes folks think about upgrading, it's probably a good thing.

That being said, patches to magically make this work that are clean will be considered, but I'm not going to leave this ticket open.

**Comment by timurb** [comment]
This was introduced in https://github.com/ansible/ansible/commit/0d408ff29565d7c9814b5fc70ecea82db37c8e00, I've filed pull request #4869 to fix that.
