### ISSUE TITLE
Tagging EC2 instances

### ISSUE THREAD

**Issue by brandonhilkert** [ansible/ansible#4942]
I have a playbook that tags ec2 instances. I get errors from boto, but the task does actually complete. Am I doing something wrong to cause these errors?

```
- name: update instance tags
  gather_facts: false
  hosts:
    - tag_role_{{ role }}

  tasks:
    - name: get info about servers
      action: ec2_facts

    - name: update instance role
      local_action: ec2_tag resource={{ hostvars[item].ansible_ec2_instance_id }}
                    state=present region=us-east-1
      with_items: groups['tag_role_{{ role }}']
      args:
        tags:
          role: "{{ tag }}"
```

```
TASK: [update instance role] **************************************************
failed: [ec2-107-20-99-183.compute-1.amazonaws.com] => (item=ec2-54-226-221-189.compute-1.amazonaws.com) => {"failed": true, "item": "ec2-54-226-221-189.compute-1.amazonaws.com", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/bhilkert/.ansible/tmp/ansible-1384790842.9-122971899563425/ec2_tag", line 1144, in <module>
    main()
  File "/Users/bhilkert/.ansible/tmp/ansible-1384790842.9-122971899563425/ec2_tag", line 190, in main
    tagger = ec2.create_tags(resource, dictadd)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 3392, in create_tags
    return self.get_status('CreateTags', params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1115, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>ConcurrentTagAccess</Code><Message>The Tags for this Resource cannot be modified as they are currently being modified by another request. Please retry the request.</Message></Error></Errors><RequestID>58333a35-a278-49fa-9ac0-e350c2f83b97</RequestID></Response>

changed: [ec2-54-226-221-189.compute-1.amazonaws.com] => (item=ec2-54-226-221-189.compute-1.amazonaws.com)
failed: [ec2-54-226-221-189.compute-1.amazonaws.com] => (item=ec2-107-20-99-183.compute-1.amazonaws.com) => {"failed": true, "item": "ec2-107-20-99-183.compute-1.amazonaws.com", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/bhilkert/.ansible/tmp/ansible-1384790843.58-153571170149277/ec2_tag", line 1144, in <module>
    main()
  File "/Users/bhilkert/.ansible/tmp/ansible-1384790843.58-153571170149277/ec2_tag", line 190, in main
    tagger = ec2.create_tags(resource, dictadd)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 3392, in create_tags
    return self.get_status('CreateTags', params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1115, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>ConcurrentTagAccess</Code><Message>The Tags for this Resource cannot be modified as they are currently being modified by another request. Please retry the request.</Message></Error></Errors><RequestID>a5e4f7a2-0df5-4184-9954-d10eab361940</RequestID></Response>

changed: [ec2-107-20-99-183.compute-1.amazonaws.com] => (item=ec2-107-20-99-183.compute-1.amazonaws.com)

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
ansible --version ?

boto version ?

**Comment by brandonhilkert** [comment]
```
ubuntu@ip-10-60-50-56:~$ ansible --version
ansible 1.3.4

boto==2.17.0
```

**Comment by mpdehaan** [comment]
Can you please test and see if this occurs on 1.4.X? 

Thanks!

**Comment by brandonhilkert** [comment]
Still not working :(

```
ubuntu@ip-10-147-227-145:~/pipelinedeals$ ansible --version
ansible 1.5 (devel 3b469f81d3) last updated 2013/12/02 09:25:47 (GMT -400)
```

```
TASK: [update instance role] **************************************************
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1385998898.37-163658768933925 && chmod a+rx $HOME/.ansible/tmp/ansible-1385998898.37-163658768933925 && echo $HOME/.ansible/tmp/ansible-1385998898.37-163658768933925']
<127.0.0.1> REMOTE_MODULE ec2_tag resource=i-d5ffc7b0 state=present region=us-east-1
<127.0.0.1> PUT /tmp/tmpqzrFW_ TO /home/ubuntu/.ansible/tmp/ansible-1385998898.37-163658768933925/ec2_tag
<127.0.0.1> PUT /tmp/tmpmh3Nsg TO /home/ubuntu/.ansible/tmp/ansible-1385998898.37-163658768933925/arguments
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/local/bin/python /home/ubuntu/.ansible/tmp/ansible-1385998898.37-163658768933925/ec2_tag /home/ubuntu/.ansible/tmp/ansible-1385998898.37-163658768933925/arguments; rm -rf /home/ubuntu/.ansible/tmp/ansible-1385998898.37-163658768933925/ >/dev/null 2>&1']
ok: [ec2-54-234-196-20.compute-1.amazonaws.com] => (item=ec2-54-234-196-20.compute-1.amazonaws.com) => {"changed": false, "item": "ec2-54-234-196-20.compute-1.amazonaws.com", "msg": "Tags already exists in i-d5ffc7b0."}
```

**Comment by willthames** [comment]
That's the correct behaviour.

Your with_items section is basically saying: give me a list of all instances with the role tag set to `{{role}}`
You then say: tag all those instances with the tag `{{role}}`

The tag module says 'this instance is already tagged `{{role}}` and does nothing but returns ok (because the tags are already as requested - @mpdehaan, I have avoided the I word)

What do you expect to happen differently?

**Comment by brandonhilkert** [comment]
I expect it to update the tag with the new value. The updated PR was already merged. We could debate the intended behavior, but my point was more so that the behavior changed from 1.3.x to 1.4.x without warning. I think it's pretty common for people to update the value of a Tag, and the module no longer allowed that.

**Comment by willthames** [comment]
I understand now that you were trying to change a tag and that that was failing (as your variables aren't expanded it's not obvious from the original or most recent report that the tags differ)

It's working as expected now though? I was just trying to work out what was going wrong but if it's fixed then this should be closed.

**Comment by willthames** [comment]
Would also be handy to link this to the PR that fixed this.

**Comment by brandonhilkert** [comment]
It is working now, yes. Here's the PR: https://github.com/ansible/ansible/pull/5078
