### ISSUE TITLE
gce_test.py may have incorrect key export instructions

### ISSUE THREAD

**Issue by dch** [ansible/ansible#4955]
Method for exporting key in required format in [gce_tests.py](https://github.com/ansible/ansible/blob/devel/test/gce_tests.py#L24-L27) doesn't seem to be accepted by crypto/RSA function. This issue is edging towards support but I currently think this syntax isn't correct - apologies if wrong :/.

cc @erjohnso again for illumination

``` shell
$ /gce.py --list

Traceback (most recent call last):
  File "./gce.py", line 220, in <module>
    GceInventory()
  File "./gce.py", line 101, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 129, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 520, in __init__
    self.zone_list = self.ex_list_zones()
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 1014, in ex_list_zones
    response = self.connection.request(request, method='GET').object
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/common/google.py", line 557, in request
    *args, **kwargs)
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/common/base.py", line 608, in request
    params, headers = self.pre_connect_hook(params, headers)
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/common/google.py", line 533, in pre_connect_hook
    self.token_info = self.auth_conn.refresh_token(self.token_info)
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/common/google.py", line 441, in refresh_token
    return self.get_new_token()
  File "/repos/pytools/lib/python2.7/site-packages/libcloud/common/google.py", line 415, in get_new_token
    key = RSA.importKey(self.key)
  File "/repos/pytools/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 682, in importKey
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
```

Key seems a very sensible format, obv not real one:

``` shell
cabc21367freghj312casc67asc56das7c5ads679c6ds7a9c67895ds67f5ds6
cabc21367freghj312casc67asc56das7c5ads679c6ds7a9c67895ds67f5ds6
cabc21367freghj312casc67asc56...
```

**Comment by mpdehaan** [comment]
I'd ask this one on the development list.

When filing tickets, also always please include the output of "ansible --version" and the steps to reproduce the problem.

As you said, "this syntax isn't correct", it's unclear what you mean without seeing your config file that it's picking up.

**Comment by dch** [comment]
Thanks Mark, will do. I'm making progress, I think the parsing of options for the various configs doesn't fall through correctly.  I'll close this & open a new one with better info tomorrow.
