### ISSUE TITLE
inventory_hostnames lookup plugin crashes with KeyError: 'runner'

### ISSUE THREAD

**Issue by neh** [ansible/ansible#4979]
I'm running the dev version of ansible ( b4c0526 ) and getting this error:

```
Traceback (most recent call last):
  File "/home/nathan/Projects/ansible/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/nathan/Projects/ansible/bin/ansible-playbook", line 209, in main
    pb.run()
  File "/home/nathan/Projects/ansible/lib/ansible/playbook/__init__.py", line 229, in run
    play = Play(self, play_ds, play_basedir)
  File "/home/nathan/Projects/ansible/lib/ansible/playbook/play.py", line 96, in __init__
    ds = template(basedir, ds, self.vars)
  File "/home/nathan/Projects/ansible/lib/ansible/utils/template.py", line 347, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined)
  File "/home/nathan/Projects/ansible/lib/ansible/utils/template.py", line 347, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined)
  File "/home/nathan/Projects/ansible/lib/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/home/nathan/Projects/ansible/lib/ansible/utils/template.py", line 541, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 8, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 180, in call
    return __obj(*args, **kwargs)
  File "/home/nathan/Projects/ansible/lib/ansible/utils/template.py", line 532, in my_lookup
    return lookup(*args, basedir=basedir, **kwargs)
  File "/home/nathan/Projects/ansible/lib/ansible/utils/template.py", line 85, in lookup
    instance = utils.plugins.lookup_loader.get(name.lower(), basedir=kwargs.get('basedir',None))
  File "/home/nathan/Projects/ansible/lib/ansible/utils/plugins.py", line 177, in get
    return getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
  File "/home/nathan/Projects/ansible/lib/ansible/runner/lookup_plugins/inventory_hostnames.py", line 37, in __init__
    self.host_list = kwargs['runner'].inventory.host_list
KeyError: 'runner'
```

with this playbook:

```
- hosts: local
  gather_facts: no
  vars:
    uri: "{{ lookup('inventory_hostnames', 'all') }}"
  tasks:
    - debug: var=uri
```

I get the same error when using the plugin in a 'with_items'.

**Comment by mpdehaan** [comment]
here is the use case for which this was intended BTW:

```
tasks:
   - shell: var={{ item }}
     with_inventory_hostnames: 'all'
```

I've confirmed this works ok.

I'm going to make it raise an appropriate error in the other context.

**Comment by neh** [comment]
Using it that way works for me too, but I don't think it works for what I want to do. Is there no way to make it work the other way as well? What I want to do is look up a hostname that will then be used later in other plays. The hostname I need will be the only one that is in two groups ('group1:&group2'). Using with_inventory_hostnames gets me the correct result, but doesn't give me a way to keep the value around for later plays, unless I'm missing something or approaching this in a less than optimal way, which is certainly possible. What I'm now doing is using with_inventory_hostnames to find the hosts I want and add them to groups that I can look at later. Possibly this is the sort of thing I should be looking at etcd or zookeeper or something like that to handle.

**Comment by jctanner** [comment]
@neh please open a feature request for calling inventory_hostnames with "lookup". The commit above is only to make sure users are aware of how the plugin is currently designed and to stop the traceback.
