### ISSUE TITLE
authorized_keys module traceback when quote present in comment

### ISSUE THREAD

**Issue by josephtate** [ansible/ansible#5021]
Using a git checkout, and using this playbook:

```
#file sshkeys.yaml
- hosts:
    - other
  #sudo: yes
  tasks:
    - name: Add authorized keys
      authorized_key: key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwkgav3IMA1BdcM3QFFp5DfBakQlpwqxGujObR9okU32qmNbOdDn8kYGhK7UAdUm1Kn+Jb+eVjy2db34s3Pyoym6/3ihGPSGaWA+n5SDeiMs6rzn2wBq+zhz83qzVpMs/NUl1kFSbFLSXYXJ/u/hrnsIaoghQyRLT0eBWY3ja8ZsI0g4tTrAtDez+ovcn0d/50K3k+Y1QJxFuys8cvNh7YC3WHCgU0jm32HZa3EHTEYqmsbS0dhLrmDl05b8sNTfWHKTcDOVo6wAHwee0I+eb1SMOFt2RmMS6y+R0bCqy32F4Ix7xVKRI2KOc1XKctu2Nl9yLadCM9TeGGCMpP90Dnw== jtate@laputa" state=present user=root
      tags: [deploy,ssh]
```

I'm getting the following error:

```
$ ansible-playbook -i inventories/other2 -vvvv sshkeys.yml 

PLAY [other] ****************************************************************** 

GATHERING FACTS *************************************************************** 
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> ESTABLISH CONNECTION FOR USER: root
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'ec2-54-245-205-210.us-west-2.compute.amazonaws.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1385152217.14-277861042071907 && chmod a+rx $HOME/.ansible/tmp/ansible-1385152217.14-277861042071907 && echo $HOME/.ansible/tmp/ansible-1385152217.14-277861042071907'"]
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> REMOTE_MODULE setup 
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> PUT /tmp/tmptXH14h TO /root/.ansible/tmp/ansible-1385152217.14-277861042071907/setup
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'ec2-54-245-205-210.us-west-2.compute.amazonaws.com', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1385152217.14-277861042071907/setup; rm -rf /root/.ansible/tmp/ansible-1385152217.14-277861042071907/ >/dev/null 2>&1'"]
ok: [ec2-54-245-205-210.us-west-2.compute.amazonaws.com]

TASK: [Add authorized keys] *************************************************** 
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> ESTABLISH CONNECTION FOR USER: root
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'ec2-54-245-205-210.us-west-2.compute.amazonaws.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1385152224.84-190783874081238 && chmod a+rx $HOME/.ansible/tmp/ansible-1385152224.84-190783874081238 && echo $HOME/.ansible/tmp/ansible-1385152224.84-190783874081238'"]
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> REMOTE_MODULE authorized_key key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwkgav3IMA1BdcM3QFFp5DfBakQlpwqxGujObR9okU32qmNbOdDn8kYGhK7UAdUm1Kn+Jb+eVjy2db34s3Pyoym6/3ihGPSGaWA+n5SDeiMs6rzn2wBq+zhz83qzVpMs/NUl1kFSbFLSXYXJ/u/hrnsIaoghQyRLT0eBWY3ja8ZsI0g4tTrAtDez+ovcn0d/50K3k+Y1QJxFuys8cvNh7YC3WHCgU0jm32HZa3EHTEYqmsbS0dhLrmDl05b8sNTfWHKTcDOVo6wAHwee0I+eb1SMOFt2RmMS6y+R0bCqy32F4Ix7xVKRI2KOc1XKctu2Nl9yLadCM9TeGGCMpP90Dnw== jtate@laputa" state=present user=root
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> PUT /tmp/tmp4ACNxZ TO /root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key
<ec2-54-245-205-210.us-west-2.compute.amazonaws.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'ec2-54-245-205-210.us-west-2.compute.amazonaws.com', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key; rm -rf /root/.ansible/tmp/ansible-1385152224.84-190783874081238/ >/dev/null 2>&1'"]
fatal: [ec2-54-245-205-210.us-west-2.compute.amazonaws.com] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key", line 1397, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key", line 368, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key", line 302, in enforce_state
    existing_keys = readkeys(params["keyfile"])
  File "/root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key", line 246, in readkeys
    key_data = parsekey(line)
  File "/root/.ansible/tmp/ansible-1385152224.84-190783874081238/authorized_key", line 212, in parsekey
    key_parts = shlex.split(raw_key)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jtate/sshkeys.retry

ec2-54-245-205-210.us-west-2.compute.amazonaws.com : ok=1    changed=0    unreachable=1    failed=0   

```

**Comment by josephtate** [comment]
1.4 fails too. 1.3 works though.

**Comment by jctanner** [comment]
@josephtate I am not able to reproduce with your example ...

```
- hosts: el6.lab.net
  gather_facts: False
  tasks:
     - name: Add authorized keys
       authorized_key: key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwkgav3IMA1BdcM3QFFp5DfBakQlpwqxGujObR9okU32qmNbOdDn8kYGhK7UAdUm1Kn+Jb+eVjy2db34s3Pyoym6/3ihGPSGaWA+n5SDeiMs6rzn2wBq+zhz83qzVpMs/NUl1kFSbFLSXYXJ/u/hrnsIaoghQyRLT0eBWY3ja8ZsI0g4tTrAtDez+ovcn0d/50K3k+Y1QJxFuys8cvNh7YC3WHCgU0jm32HZa3EHTEYqmsbS0dhLrmDl05b8sNTfWHKTcDOVo6wAHwee0I+eb1SMOFt2RmMS6y+R0bCqy32F4Ix7xVKRI2KOc1XKctu2Nl9yLadCM9TeGGCMpP90Dnw== jtate@laputa" state=present user=root
```

This makes me suspect maybe you have an unclosed quote in the remote authorized keys file.

**Comment by jctanner** [comment]
Verified that an unclosed quote in the remote key file can cause this ...

```
TASK: [Add authorized keys] *************************************************** 
fatal: [el6.lab.net] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1385153445.03-176666175419353/authorized_key", line 1397, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1385153445.03-176666175419353/authorized_key", line 368, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1385153445.03-176666175419353/authorized_key", line 302, in enforce_state
    existing_keys = readkeys(params["keyfile"])
  File "/root/.ansible/tmp/ansible-1385153445.03-176666175419353/authorized_key", line 246, in readkeys
    key_data = parsekey(line)
  File "/root/.ansible/tmp/ansible-1385153445.03-176666175419353/authorized_key", line 212, in parsekey
    key_parts = shlex.split(raw_key)
  File "/usr/lib64/python2.6/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.6/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.6/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by josephtate** [comment]
Git bisect tells me that it stopped working on
49130c688da3f5f9e0b118d83184754dc8de2722 is the first bad commit
commit 49130c688da3f5f9e0b118d83184754dc8de2722
Author: James Cammarata jimi@sngx.net
Date:   Fri Oct 11 14:14:07 2013 -0500

```
Adding 'unique' option to authorized_key module and cleanup

A small refactoring of the authorized_key module to accomodate these
changes, plus fixing some things like not rewriting the file on every
new key. These changes bring the original feature for ssh options in-
line with the comments in #3798

Fixes #3785
```

:040000 040000 2917bb23a4dff480dd7d8a6d94fed5e46f3355d2 ce712bc63981b952c4760dbb39efaed187e841b3 M      library

Ahh. My EC2 key has a single ' in it:

ssh-rsa AAAAB.....== jtate's key

**Comment by jctanner** [comment]
@josephtate here's testpatch ...

```
diff --git a/library/system/authorized_key b/library/system/authorized_key
index 5c40e7d..db0425d 100644
--- a/library/system/authorized_key
+++ b/library/system/authorized_key
@@ -209,7 +209,12 @@ def parsekey(raw_key):
     key_type   = None   # type of ssh key
     type_index = None   # index of keytype in key string|list

-    key_parts = shlex.split(raw_key)
+    # split key safely
+    lex = shlex.shlex(raw_key)
+    lex.quotes = ["'", '"']
+    lex.whitespace_split = True
+    key_parts = list(lex)
+
     for i in range(0, len(key_parts)):
         if key_parts[i] in VALID_SSH2_KEY_TYPES:
             type_index = i
```

**Comment by mpdehaan** [comment]
Flagged as priority for next dot release, FWIW... maybe we drop this a week from Monday

**Comment by josephtate** [comment]
I tested the patch, and it works on my systems.
