### ISSUE TITLE
ansible_ssh_user problem in playbook?

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#5030]
It seems that using ansible_ssh_user with "sudo: yes" in a playbook doesn't work anymore since this commit : https://github.com/ansible/ansible/commit/5bd52796ec71852beb5846127b14093661ec0075

/etc/hosts:

``` yaml
192.168.33.10 ansible_ssh_user=vagrant
```

pbook.yml:

``` yaml
- hosts: all
  sudo: yes

  tasks:
    - name: Creates destination directory
      file: state=directory mode=0700 dest=/root/.ssh/
```

Running the playbook:

```
ansible-playbook -c paramiko -i step-00/hosts step-00/setup.yml -l 192.168.33.10 --ask-pass --sudo -vvv
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385218557.77-255921977020654 && echo /tmp/ansible-1385218557.77-255921977020654'
<192.168.33.10> REMOTE_MODULE setup 
<192.168.33.10> PUT /tmp/tmpk0efUs TO /tmp/ansible-1385218557.77-255921977020654/setup
<192.168.33.10> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-1385218557.77-255921977020654/setup; rm -rf /tmp/ansible-1385218557.77-255921977020654/ >/dev/null 2>&1'
ok: [192.168.33.10]

TASK: [Creates destination directory] ***************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385218561.04-280297281004008 && echo /tmp/ansible-1385218561.04-280297281004008'
<192.168.33.10> REMOTE_MODULE file state=directory mode=0700 dest=/root/.ssh/
<192.168.33.10> PUT /tmp/tmp1urXsh TO /tmp/ansible-1385218561.04-280297281004008/file
<192.168.33.10> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-1385218561.04-280297281004008/file; rm -rf /tmp/ansible-1385218561.04-280297281004008/ >/dev/null 2>&1'
failed: [192.168.33.10] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/ansible-1385218561.04-280297281004008/file", line 1378, in <module>
    main()
  File "/tmp/ansible-1385218561.04-280297281004008/file", line 266, in main
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.ssh/'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/leucos/setup.retry

192.168.33.10              : ok=1    changed=0    unreachable=0    fa
```

This used to work pre 1.4 (I bisected the problem down to 5bd5279). 

However, using adding `remote_user: vagrant` in the playbook fixes the problem. 
Is this the intented behaviour ?

**Comment by mpdehaan** [comment]
Hmm,

Given

(A) 
There is no reason to sudo if you aren't changing the user account.

(B)
The default sudo user is root

It may be that this code doesn't account for ansible_ssh_user.

In queue for investigation.

**Comment by jctanner** [comment]
@leucos 

I am unable to reproduce your error. What are the permissions on /root and /root/.ssh on the remote host?

Are you able to create a directory elsewhere?

```
file: state=directory mode=0700 dest=/tmp/anewdir
```

**Comment by leucos** [comment]
@jctanner, here is the output when run with a previous ansible version (d21a028) :

```
$ ansible-playbook -c paramiko -i step-00/hosts step-00/setup.yml -l 192.168.33.10 --ask-pass --sudo -vvv
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385396947.71-72895673469119 && echo /tmp/ansible-1385396947.71-72895673469119'
<192.168.33.10> REMOTE_MODULE setup 
<192.168.33.10> PUT /tmp/tmpI7KbPU TO /tmp/ansible-1385396947.71-72895673469119/setup
<192.168.33.10> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=pogtekvwoknkjmnkgjtazzjguevgljgj] password: " -u root /bin/sh -c '"'"'/usr/bin/python /tmp/ansible-1385396947.71-72895673469119/setup; rm -rf /tmp/ansible-1385396947.71-72895673469119/ >/dev/null 2>&1'"'"''
ok: [192.168.33.10]

TASK: [Creates destination directory] ***************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385396950.94-220121058520759 && echo /tmp/ansible-1385396950.94-220121058520759'
<192.168.33.10> REMOTE_MODULE file state=directory mode=0700 dest=/root/.ssh/
<192.168.33.10> PUT /tmp/tmpjcOHgB TO /tmp/ansible-1385396950.94-220121058520759/file
<192.168.33.10> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=uqeluisdcgcejitzbqflycfxsrmneukv] password: " -u root /bin/sh -c '"'"'/usr/bin/python /tmp/ansible-1385396950.94-220121058520759/file; rm -rf /tmp/ansible-1385396950.94-220121058520759/ >/dev/null 2>&1'"'"''
ok: [192.168.33.10] => {"changed": false, "gid": 0, "group": "root", "mode": "0700", "owner": "root", "path": "/root/.ssh/", "size": 4096, "state": "directory", "uid": 0}
```

You can clearly see in the line `EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible...` that  ansible is doing sudo. This line is not present in the run provider in the first comment.

If you have vagrant and want to reproduce in the same environment, you can try :

```
git clone https://github.com/leucos/ansible-tuto.git
cd ansible-tuto
git checkout 85ddb4d
vagrant up
ansible-playbook -c paramiko -i step-00/hosts step-00/setup.yml -l 192.168.33.10 --ask-pass --sudo -vvv
```

As for the directory creation test, I inserted it before the failing task and it works fine :

```
$ ansible-playbook -c paramiko -i step-00/hosts step-00/setup.yml -l 192.168.33.10 --ask-pass --sudo -vvv 
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385397373.9-39513970273311 && echo /tmp/ansible-1385397373.9-39513970273311'
<192.168.33.10> REMOTE_MODULE setup 
<192.168.33.10> PUT /tmp/tmp4RUpn0 TO /tmp/ansible-1385397373.9-39513970273311/setup
<192.168.33.10> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-1385397373.9-39513970273311/setup; rm -rf /tmp/ansible-1385397373.9-39513970273311/ >/dev/null 2>&1'
ok: [192.168.33.10]

TASK: [Test for @jctanner] **************************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385397377.13-73597115348521 && echo /tmp/ansible-1385397377.13-73597115348521'
<192.168.33.10> REMOTE_MODULE file state=directory mode=0700 dest=/tmp/anewdir
<192.168.33.10> PUT /tmp/tmpJWaeP4 TO /tmp/ansible-1385397377.13-73597115348521/file
<192.168.33.10> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-1385397377.13-73597115348521/file; rm -rf /tmp/ansible-1385397377.13-73597115348521/ >/dev/null 2>&1'
changed: [192.168.33.10] => {"changed": true, "gid": 1000, "group": "vagrant", "mode": "0700", "owner": "vagrant", "path": "/tmp/anewdir", "size": 4096, "state": "directory", "uid": 1000}

TASK: [Creates destination directory] ***************************************** 
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant on PORT 22 TO 192.168.33.10
<192.168.33.10> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1385397380.09-154230207353473 && echo /tmp/ansible-1385397380.09-154230207353473'
<192.168.33.10> REMOTE_MODULE file state=directory mode=0700 dest=/root/.ssh/
<192.168.33.10> PUT /tmp/tmp3r_V5p TO /tmp/ansible-1385397380.09-154230207353473/file
<192.168.33.10> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-1385397380.09-154230207353473/file; rm -rf /tmp/ansible-1385397380.09-154230207353473/ >/dev/null 2>&1'
failed: [192.168.33.10] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/ansible-1385397380.09-154230207353473/file", line 1378, in <module>
    main()
  File "/tmp/ansible-1385397380.09-154230207353473/file", line 266, in main
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.ssh/'


FATAL: all hosts have already failed -- aborting
```

Thanks for reading.

**Comment by jctanner** [comment]
@leucos are you running ansible-playbook as the root user?

**Comment by leucos** [comment]
Nope.

**Comment by jctanner** [comment]
@leucos I'm still having trouble reproducing the behavior. If you comment out the two lines added by 5bd52796ec71852beb5846127b14093661ec0075 does it invoke sudo?

**Comment by jctanner** [comment]
@leucos Here's a testpatch that I think might solve your issue, but it's still unclear how to reproduce ...

```
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index aafb07b..83dde80 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -763,7 +763,8 @@ class Runner(object):

         sudo_user = self.sudo_user

-        if self.remote_user == sudo_user:
+        #if self.remote_user == sudo_user:
+        if conn.user == sudo_user:
             sudoable = False

         rc, stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable, executable=executable)
```

**Comment by leucos** [comment]
@jctanner you patch solves the problem. Did you try to clone the vagrant based tutorial ? Note that you have to check out a specific commit (85ddb4d) since I introduced a workaround in later commits.

**Comment by jctanner** [comment]
@leucos thanks for testing. I need to do some more code analysis to understand the implications of changing that line before committing it.
