### ISSUE TITLE
script: chdir on Windows does not work

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#50585]
##### SUMMARY
Using the `chdir` module option for `script` on Windows does not work due to various issues. We don't have any integration tests and it looks like this has been broken for a few releases now.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
script

##### ANSIBLE VERSION
```paste below
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Windows as a remote host

##### STEPS TO REPRODUCE
```yaml
---
- hosts: windows
  gather_facts: no

  tasks:
  - copy:
      content: '$pwd'
      dest: test.ps1
    delegate_to: localhost

  - script: test.ps1
    args:
      chdir: C:\Windows
```

##### EXPECTED RESULTS
The script to execute and the output being `C:\Windows`.

```
TASK [script] ******************************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:11
<server2016.domain.local> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO server2016.domain.local                                                                                                  
EXEC (via pipeline wrapper)
<server2016.domain.local> PUT "/Users/jborean/dev/module-tester/test.ps1" TO "C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1546807144.946774-18271179278802\test.ps1"                                        
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
changed: [2016] => {
    "changed": true,
    "rc": 0,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "C:\\Windows\r\n",
    "stdout_lines": [
        "C:\\Windows"
    ]
}
```

##### ACTUAL RESULTS
Before https://github.com/ansible/ansible/pull/50365

```
TASK [script] ******************************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:11
<server2016.domain.local> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO server2016.domain.local                                                                                                  
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/Users/jborean/dev/ansible/lib/ansible/executor/task_executor.py", line 142, in run
    res = self._execute()
  File "/Users/jborean/dev/ansible/lib/ansible/executor/task_executor.py", line 644, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/jborean/dev/ansible/lib/ansible/plugins/action/script.py", line 69, in run
    not self.windows_absolute_path_detection.matches(chdir):
AttributeError: 're.Pattern' object has no attribute 'matches'

fatal: [2016]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

After https://github.com/ansible/ansible/pull/50365

```
TASK [script] ******************************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:11
<server2016.domain.local> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO server2016.domain.local                                                                                                  
EXEC (via pipeline wrapper)
<server2016.domain.local> PUT "/Users/jborean/dev/module-tester/test.ps1" TO "C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1546807259.5340679-129273677441460\test.ps1"                                      
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/Users/jborean/dev/ansible/lib/ansible/executor/task_executor.py", line 142, in run
    res = self._execute()
  File "/Users/jborean/dev/ansible/lib/ansible/executor/task_executor.py", line 644, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/jborean/dev/ansible/lib/ansible/plugins/action/script.py", line 142, in run
    result.update(self._low_level_execute_command(cmd=script_cmd, in_data=exec_data, sudoable=True, chdir=chdir))                                                                                               
  File "/Users/jborean/dev/ansible/lib/ansible/plugins/action/__init__.py", line 961, in _low_level_execute_command                                                                                             
    cmd = self._connection._shell.append_command('cd %s' % chdir, cmd)
  File "/Users/jborean/dev/ansible/lib/ansible/plugins/shell/__init__.py", line 210, in append_command
    if self._SHELL_AND:
AttributeError: 'ShellModule' object has no attribute '_SHELL_AND'

fatal: [2016]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by jborean93** [comment]
First issue has been fixes with https://github.com/ansible/ansible/pull/50365.

**Comment by ShachafGoldstein** [comment]
Not seeing this issue on my end.

**Comment by edonadei** [comment]
Having the issue with a windows host with chdir arg

```yaml
tasks:
    - name: Start Something
      script: start_something.bat
      args:
        chdir: C:\\Windows
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 603, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/script.py", line 69, in run
    not self.windows_absolute_path_detection.matches(chdir):
AttributeError: '_sre.SRE_Pattern' object has no attribute 'matches'

fatal: [user]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by ShachafGoldstein** [comment]
@edonadei - What version are you running?

in devel it seems OK 
https://github.com/ansible/ansible/blob/16d6fcf5148e2a527f5c6e2603490a2e79500a91/lib/ansible/plugins/action/script.py#L69

**Comment by edonadei** [comment]
I'm running version 7.1 Ansible

````
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

**Comment by ShachafGoldstein** [comment]
Please try 2.8+

**Comment by jborean93** [comment]
Newer versions of 2.7 and 2.8 will not traceback like you see now but setting `chdir` for `script` on Windows still does not do anything for now.
