### ISSUE TITLE
process_common_errors throws IndexError, hides real YAML error

### ISSUE THREAD

**Issue by mss** [ansible/ansible#5064]
I just got this:

```
root@vagrant-php:~# ansible-playbook /vagrant/ansible/vagrant.yml -v -c local -i /etc/hostname -vvv
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 209, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 229, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 130, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 532, in _load_tasks
    data = utils.parse_yaml_from_file(include_filename)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 483, in parse_yaml_from_file
    process_yaml_error(exc, data, path)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 461, in process_yaml_error
    msg = process_common_errors(msg, probline, mark.column)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 406, in process_common_errors
    if middle[0] in [ '"', "'" ] and middle[-1] in [ '"', "'" ] and probline.count("'") > 2 or probline.count("'") > 2:
IndexError: string index out of range
```

Which was caused by this snippet:

```
- name: Create site admin files and directories
  file:
    state={{ item.type | default("touch") }}
    path={{ site_dir }}/{{ item.path | mandatory }}
    mode={{ item.mode | mandatory }}
    owner={{ site_adm_user }}
    group={{ site_adm_user }}
    with_items:
    - { path: ".git",          mode: "0700", type: directory }
    - { path: ".ssh",          mode: "0700", type: directory }
    - { path: ".subversion",   mode: "0700", type: directory }
    - { path: ".bash_history", mode: "0600" }
    - { path: ".bashrc",       mode: "0600" }
    - { path: ".bash_aliases", mode: "0600" }
    - { path: ".profile",      mode: "0600" }
```

Look at the indentation of the with_items clause...

**Comment by mss** [comment]
Forgot to write that this is version 1.4

**Comment by mpdehaan** [comment]
Yep, looks like we should fix this w/o losing any of the previous YAML hints.

And maybe report on this one too, if we can (optional)

**Comment by jimi-c** [comment]
@mss tested with your sample from above, so this should be resolved. Please let us know if you continue to run into this bug. Thanks!
