### ISSUE TITLE
Trying to run ansible from within a multistage docker build to reduce the size

### ISSUE THREAD

**Issue by sean-abbott** [ansible/ansible#50670]
##### SUMMARY
I'm trying to use ansible in a multistage docker build to save on space. I really just want to copy the successful ansible build into /usr/local and have it work...but it does not. I get 

```
# ansible --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 40, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named 'ansible'
```

##### ISSUE TYPE
- Bug Report / help request

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
(output below, but it's 2.7.5)

```# ansible --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 40, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named 'ansible'

```

##### CONFIGURATION
Also gets a module error

##### OS / ENVIRONMENT
docker.

My docker file looks like:

```
FROM bitnami/minideb:stretch as base

FROM base as builder

RUN mkdir -p /install/requirements
WORKDIR /install

COPY requirements/ansible.txt /install/requirements/

RUN install_packages python3-pip python3-dev libssl-dev libffi-dev build-essential
RUN pip3 install setuptools \
    && pip3 install --install-option="--prefix=/install" -r requirements/ansible.txt

FROM base
COPY --from=builder /install /usr/local/

RUN install_packages python3

ENV PYTHONPATH /usr/local/lib/python3.5
ENV ANSIBLE_LIBRARY /usr/local/lib/python3.5/site-packages/ansible/library
```

##### STEPS TO REPRODUCE
(save the above as Dockerfile, add 
```
boto
jinja2
PyYAML
ansible
```
as requirements/ansible.txt, 

then `docker build -t testansible .`
then `docker run --rm -it testansible /bin/bash`
then `ansible --version`
##### EXPECTED RESULTS
I can run ansible

##### ACTUAL RESULTS
I get a module import error.

**Comment by sean-abbott** [comment]
I"m quite sure that if I found the right combination of environment variables, this would run
but I can't get it
I can't quite understand the way that 
```
# ansible --version
ansible 2.7.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```
The ansible python module location, configured module search path, and executable locations are set,

**Comment by sean-abbott** [comment]
Nevermind, I found it.

I wasn't setting PYTHONPATH correctly. sys.path only included dist-packages.

When I explicitly set PYTHONPATH=/usr/local/lib/python3.5/site-packages it worked.
