### ISSUE TITLE
Traceback using accelerate mode in 1.4 -- OverflowError

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#5080]
I'm getting this from 100% of my hosts (that can run accelerated mode)

```
fatal: [10.23.246.128] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 514, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 668, in _executor_internal_inner
    tmp = self._make_tmp_path(conn)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 825, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 759, in _low_level_exec_command
    rc, stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable, executable=executable)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/connection_plugins/accelerate.py", line 187, in exec_command
    response = self.recv_data()
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/connection_plugins/accelerate.py", line 151, in recv_data
    d = self.conn.recv(data_len - len(data))
OverflowError: signed integer is greater than maximum
```

Host running ansible is Debian Wheezy. Client machines are Debian Squeeze.

**Comment by omgjlk** [comment]
This appears to have been a fun mixmatch of starting accelerated mode using ansible 1.3.4 code, and then switching the ansible host to 1.4 and trying to run again. I believe the mismatch in code was causing the issue. Once I killed the running accelerate modules on the clients and started over with 1.4 everything was happy again.
