### ISSUE TITLE
Accelerated connection crashed

### ISSUE THREAD

**Issue by renaudguerin** [ansible/ansible#5096]
Hi,

Just got this in 1.4.1. Killing the accelerate process on the server fixed it.

```
fatal: [w4] => Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 675, in _executor_internal_inner
    tmp = self._make_tmp_path(conn)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 837, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 771, in _low_level_exec_command
    rc, stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable, executable=executable)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/connection_plugins/accelerate.py", line 187, in exec_command
    response = self.recv_data()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/connection_plugins/accelerate.py", line 151, in recv_data
    d = self.conn.recv(data_len - len(data))
OverflowError: signed integer is greater than maximum
```

**Comment by jimi-c** [comment]
Did you happen to launch the accelerate connection previously with a 1.3.x version? We had some reports of people having issues after immediately upgrading, or when hopping between git branches.

**Comment by renaudguerin** [comment]
I don't believe so,  the daemon is short-lived right ?
I had been running 1.4.0 for several days and only saw this after upgrading to 1.4.1 today

**Comment by renaudguerin** [comment]
Actually @jimi-c your 1.3 theory is likely, looks like a colleague had not upgraded to 1.4 yet.
I'll update the issue if we see this again now that everyone is on 1.4

**Comment by jimi-c** [comment]
Great, this traceback was originally reported in #5080, so I'm going to go ahead and close this. If you run into this again let us know and we can re-open #5080. Thanks!
