### ISSUE TITLE
DigitalOcean Plugin causes Ansible to throw ValueError: No closing quotation (?)

### ISSUE THREAD

**Issue by elbuo8** [ansible/ansible#5111]
On Ansible 1.4.1 I'm running the following command

`ansible -m ping -u root -i do.py all`

[do.py contents](https://raw.github.com/ansible/ansible/devel/plugins/inventory/digital_ocean.py) 

It used to work flawlessly in the past. But for some reason now I'm getting the following error:

```
Traceback (most recent call last):
 File "/usr/local/bin/ansible", line 157, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/local/bin/ansible", line 79, in run
    inventory_manager = inventory.Inventory(options.inventory)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 105, in __init__
    self.parser = InventoryParser(filename=host_list)
  File "/Library/Python/2.7/site-packages/ansible/inventory/ini.py", line 41, in __init__
    self._parse()
  File "/Library/Python/2.7/site-packages/ansible/inventory/ini.py", line 45, in _parse
    self._parse_base_groups()
  File "/Library/Python/2.7/site-packages/ansible/inventory/ini.py", line 83, in _parse_base_groups
    tokens = shlex.split(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
```

Happening in both OS X and CentOS.

If I check the directory again, I can find the ansible-digital_ocean.cache file. It has everything and it's valid JSON. 

Any clues on how to fix it?

**Comment by mpdehaan** [comment]
Are you sure you have this module chmod +x'd so it's executable?

**Comment by elbuo8** [comment]
Oh crap. That fixed it. Totally forgot.

Thanks

**Comment by mpdehaan** [comment]
excellent.

I'm guessing we can probably make that error more automatic if we detect a shebang line at the top of the file.

I'll file a feature idea.

**Comment by mpdehaan** [comment]
Ideas added about error detection in https://github.com/ansible/ansible/issues/5113
