### ISSUE TITLE
Copy module error when src is directory

### ISSUE THREAD

**Issue by devoncrouse** [ansible/ansible#5150]
According to the module documentation:

src: Local path to a file to copy to the remote server; can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination...

```
copy: src=diamond_collectors/ dest=/etc/diamond/collectors owner=diamond group=diamond mode=0644
```

```
fatal: [hostname] => Traceback (most recent call last):
  File "/usr/local/python_venvs/ansible/ansible/lib/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/python_venvs/ansible/ansible/lib/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/python_venvs/ansible/ansible/lib/ansible/runner/__init__.py", line 678, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/python_venvs/ansible/ansible/lib/ansible/runner/action_plugins/copy.py", line 98, in run
    local_md5 = utils.md5(source)
  File "/usr/local/python_venvs/ansible/ansible/lib/ansible/utils/__init__.py", line 535, in md5
    infile = open(filename, 'rb')
IOError: [Errno 21] Is a directory: u'.../roles/common/files/diamond_collectors'
```

**Comment by devoncrouse** [comment]
This community works quickly; I wasn't far behind devel, but I pulled latest anyways and it now works.
