### ISSUE TITLE
Sudo copy permission denied

### ISSUE THREAD

**Issue by patrickheeney** [ansible/ansible#5155]
I am using copy command to back up a php.ini file but getting permission denied errors on the second task.

```
- name: main | make backup of test.ini
  sudo: yes
  sudo_user: root
  remote_user: root
  copy: >
    src=/etc/php5/apache2/test.ini 
    dest=/etc/php5/apache2/test.ini.bak
    force=yes

- name: main | make backup of php.ini
  sudo: yes
  sudo_user: root
  remote_user: root
  copy: >
    src=/etc/php5/apache2/php.ini 
    dest=/etc/php5/apache2/php.ini.bak
    force=yes
```

files:

```
-rw------- 1 root    root    4.2K Dec  4 07:42 php.ini
-rw-r--r-- 1 root    root       0 Dec  4 07:39 test.ini
```

outputs:

```
TASK: [php | main | make backup of test.ini] **********************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386143737.43-6703040937043 && chmod a+rx $HOME/.ansible/tmp/ansible-1386143737.43-6703040937043 && echo $HOME/.ansible/tmp/ansible-1386143737.43-6703040937043']
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386143737.44-193217302058238 && chmod a+rx $HOME/.ansible/tmp/ansible-1386143737.44-193217302058238 && echo $HOME/.ansible/tmp/ansible-1386143737.44-193217302058238']
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=shnmynhnpblvlrdoedlgvasoxrdafmuz] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-shnmynhnpblvlrdoedlgvasoxrdafmuz; rc=0; [ -r "/etc/php5/apache2/test.ini.bak" ] || rc=2; [ -f "/etc/php5/apache2/test.ini.bak" ] || rc=1; [ -d "/etc/php5/apache2/test.ini.bak" ] && rc=3; (/usr/bin/md5sum /etc/php5/apache2/test.ini.bak 2>/dev/null) || (/sbin/md5sum -q /etc/php5/apache2/test.ini.bak 2>/dev/null) || (/usr/bin/digest -a md5 /etc/php5/apache2/test.ini.bak 2>/dev/null) || (/sbin/md5 -q /etc/php5/apache2/test.ini.bak 2>/dev/null) || (/usr/bin/md5 -n /etc/php5/apache2/test.ini.bak 2>/dev/null) || (/bin/md5 -q /etc/php5/apache2/test.ini.bak 2>/dev/null) || (/usr/bin/csum -h MD5 /etc/php5/apache2/test.ini.bak 2>/dev/null) || (echo "${rc}  /etc/php5/apache2/test.ini.bak")'"'"''
<localhost> PUT /tmp/tmpL5aX0V TO /home/vagrant/.ansible/tmp/ansible-1386143737.44-193217302058238/file
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=qbfgskogekcmnfyjbkydmwhnicazqbqu] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-qbfgskogekcmnfyjbkydmwhnicazqbqu; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-1386143737.44-193217302058238/file; rm -rf /home/vagrant/.ansible/tmp/ansible-1386143737.44-193217302058238/ >/dev/null 2>&1'"'"''
ok: [localhost] => {"changed": false, "gid": 1000, "group": "vagrant", "item": "", "mode": "0664", "owner": "vagrant", "path": "/etc/php5/apache2/test.ini.bak", "size": 0, "state": "file", "uid": 1000}

TASK: [php | main | make backup of php.ini] ***********************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386143737.51-185408843236058 && chmod a+rx $HOME/.ansible/tmp/ansible-1386143737.51-185408843236058 && echo $HOME/.ansible/tmp/ansible-1386143737.51-185408843236058']
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386143737.52-202461058855291 && chmod a+rx $HOME/.ansible/tmp/ansible-1386143737.52-202461058855291 && echo $HOME/.ansible/tmp/ansible-1386143737.52-202461058855291']
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 678, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/copy.py", line 129, in run
    local_md5 = utils.md5(source_full)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 535, in md5
    infile = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/etc/php5/apache2/php.ini'


FATAL: all hosts have already failed -- aborting
```

So it works for files with chmod 644 but not 600. I tried all different variables of `sudo`, `sudo_user`, `remote_user` but originally tried with just `sudo`.

**Comment by bcoca** [comment]
2 things:
- sudo/sudo_user root is useless if remote_user is already root
- the permission denied is to the LOCAL file /etc/php5/apache2/php.ini
  which is not readable by your user on the machine you execute ansible from.

**Comment by patrickheeney** [comment]
I am running this with vagrant so the default user is vagrant. When adding `sudo: yes` to any other tasks it works.

I tried every combination of the 3 options and none resolve the issue. Locally I tried `sudo cp /etc/php5/apache2/php.ini /etc/php5/apache2/php.ini.bak` and it also works so the user has permission. 

I am not sure why ansible is getting permission denied to it.

**Comment by bcoca** [comment]
because ansible runs as YOU, you need to:

sudo ansible, so ansible can read the local /etc/php5/apache2/php.ini

**Comment by jctanner** [comment]
@patrickheeney I think you believed that the copy module was going to copy the file from and to the remote machine?

As stated on IRC, that is not what the copy module does. It is meant for copying a file from your "control" machine to the remote system. It's basically a call to sftp/scp from localhost to remote.
