### ISSUE TITLE
ec2_elb module: Bugfix: error in ec2_elb, initial_state not set before use

### ISSUE THREAD

**Issue by schrock-meteor** [ansible/ansible#5253]
Version 1.5

Getting an error in ec2_elb:144: If wait isn't set, initial_state is not declared before it's used:

invalid output was: Traceback (most recent call last):
File "/home/rawr/.ansible/tmp/ansible-1386807871.34-9619501383113/ec2_elb", line 1411, in 
main()
File "/home/rawr/.ansible/tmp/ansible-1386807871.34-9619501383113/ec2_elb", line 336, in main
elb_man.deregister(wait)
File "/home/rawr/.ansible/tmp/ansible-1386807871.34-9619501383113/ec2_elb", line 144, in deregister
if initial_state and initial_state.state == 'InService':
UnboundLocalError: local variable 'initial_state' referenced before assignment

**Comment by mpdehaan** [comment]
Can you please paste the section of the playbook where you are invoking this module?

Thanks!

**Comment by mpdehaan** [comment]
Closing due to lack of info.
