### ISSUE TITLE
 No module named 'ansible.parsing.ajson'

### ISSUE THREAD

**Issue by axiqia** [ansible/ansible#54392]
##### SUMMARY

I installed ansible by pip, but got a `ModuleNotFoundError` error.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version                           
ansible 2.5.2
  config file = /home/sxue/openwhisk/ansible/ansible.cfg
  configured module search path = ['/home/sxue/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxue/anaconda3/lib/python3.6/site-packages/ansible
  executable location = /home/sxue/anaconda3/bin/ansible
  python version = 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_PLUGIN_PATH(/home/sxue/openwhisk/ansible/ansible.cfg) = ['/home/sxue/openwhisk/ansible/callbacks']
DEFAULT_CALLBACK_WHITELIST(/home/sxue/openwhisk/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_HASH_BEHAVIOUR(/home/sxue/openwhisk/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/sxue/openwhisk/ansible/ansible.cfg) = ['/home/sxue/openwhisk/ansible/environments/local']
DEFAULT_SCP_IF_SSH(/home/sxue/openwhisk/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/sxue/openwhisk/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/sxue/openwhisk/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

```
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i environments/local setup.yml -vvv
ansible-playbook 2.5.2
  config file = /home/sxue/openwhisk/ansible/ansible.cfg
  configured module search path = ['/home/sxue/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxue/anaconda3/lib/python3.6/site-packages/ansible
  executable location = /home/sxue/anaconda3/bin/ansible-playbook
  python version = 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
Using /home/sxue/openwhisk/ansible/ansible.cfg as config file
Parsed /home/sxue/openwhisk/ansible/environments/local/hosts inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: No module named 'ansible.parsing.ajson'
the full traceback was:

Traceback (most recent call last):
  File "/home/sxue/anaconda3/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/home/sxue/anaconda3/lib/python3.6/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/home/sxue/anaconda3/lib/python3.6/site-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/home/sxue/anaconda3/lib/python3.6/site-packages/ansible/executor/task_queue_manager.py", line 190, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/home/sxue/anaconda3/lib/python3.6/site-packages/ansible/plugins/loader.py", line 435, in all
    module = self._load_module_source(name, path)
  File "/home/sxue/anaconda3/lib/python3.6/site-packages/ansible/plugins/loader.py", line 345, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/home/sxue/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sxue/anaconda3/lib/python3.6/site-packages/ansible/plugins/callback/logdna.py", line 63, in <module>
    from ansible.parsing.ajson import AnsibleJSONEncoder
ModuleNotFoundError: No module named 'ansible.parsing.ajson'

```

Thanks you!

**Comment by mkrizek** [comment]
```
$ ansible --version
ansible 2.5.15 (stable-2.5 7376ca5688) last updated 2019/03/26 13:34:19 (GMT +200)
  config file = /home/mkrizek/src/ansible/ansible.cfg
  configured module search path = [u'/home/mkrizek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mkrizek/src/ansible/lib/ansible
  executable location = /home/mkrizek/src/ansible/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]

$ ls lib/ansible/plugins/callback/logdna.py
ls: cannot access 'lib/ansible/plugins/callback/logdna.py': No such file or directory
```

`logdna` callback plugin was added in Ansible 2.7, see https://docs.ansible.com/ansible/latest/plugins/callback/logdna.html. `logdna` uses a python module `ansible.parsing.ajson` which is not present in Ansible 2.5 (was added later) and so that's why you get that error, `logdna` is not compatible with Ansible 2.5.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by axiqia** [comment]
@mkrizek Thanks for your quick reply, I update Ansible to 2.7 and the issue resolved.
