### ISSUE TITLE
rpm_key module: doesn't import (particular) remote key

### ISSUE THREAD

**Issue by groks** [ansible/ansible#5452]
This doesn't work:

```
- name: google linux signing key
  rpm_key:
    state: present
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub
```

Error:

```
fatal: [localhost] => failed to parse: SUDO-SUCCESS-krulqezflerwxgckedaupjamucpxtpdf
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 1225, in <module>
    main()
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 195, in main
    RpmKey(module)
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 87, in __init__
    keyid = self.getkeyid(keyfile)
  File "/home/admin/.ansible/tmp/ansible-1388355649.73-167402462263223/rpm_key", line 148, in getkeyid
    self.json_fail(msg="Unexpected gpg output")
AttributeError: RpmKey instance has no attribute 'json_fail'
```

Looks similar to #4743 

This is with ansible 1.4.3 from Fedora testing repo.

**Comment by mpdehaan** [comment]
This should be "fail_json" and not "json_fail" and I would suspect it would be resolved, if you want to take a look at sending in a patch.

If not, we'll do it.

That being said, I think the underlying detail is that it doesn't support remote keys, and you would need to download them first.

**Comment by groks** [comment]
The documentation shows an example with a remote key. And it seems to be implemented.

Looks like the output of gpg on my machine (Fedora 20, gnupg-1.4.15-1.fc20.x86_64) is different than the original developers:

```
$ gpg --no-tty --batch --with-colons --fixed-list-mode --list-packets linux_signing_key.pub | grep keyid
:signature packet: algo 17, keyid A040830F7FAC5991
:signature packet: algo 17, keyid A040830F7FAC5991
```

This isn't going to work:

```
def getkeyid(self, keyfile):
    gpg = self.module.get_bin_path('gpg', True)
    stdout, stderr = self.execute_command([gpg, '--no-tty', '--batch', '--with-colons', '--fixed-list-mode', '--list-packets', keyfile])
    for line in stdout.splitlines():
        line = line.strip()
        if line.startswith('keyid:'):
            # We want just the last 8 characters of the keyid
            keyid = line.split(':')[1].strip()[8:]
            return keyid
    self.fail_json(msg="Unexpected gpg output")
```

I wonder what the other output alternatives are...

**Comment by mpdehaan** [comment]
yep, I could be wrong about that :)  Hard to remember everything :)

**Comment by jcalonso** [comment]
Im having similar issue with this:

```
- name: Get Remi GPG key
  rpm_key: state=present key=http://rpms.famillecollet.com/RPM-GPG-KEY-remi
```

Log:

```
TASK: [common | Get Remi GPG key] ********************************************* 
<10.50.1.80> ESTABLISH CONNECTION FOR USER: root
<10.50.1.80> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/jcalonso/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '10.50.1.80', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1389004965.66-243208615184912 && chmod a+rx $HOME/.ansible/tmp/ansible-1389004965.66-243208615184912 && echo $HOME/.ansible/tmp/ansible-1389004965.66-243208615184912'"]
<10.50.1.80> REMOTE_MODULE rpm_key state=present key=http://rpms.famillecollet.com/RPM-GPG-KEY-remi
<10.50.1.80> PUT /var/folders/7w/jdf3x4wx7pv9qfp8hrn35hb00000gn/T/tmpzc5_Wi TO /root/.ansible/tmp/ansible-1389004965.66-243208615184912/rpm_key
<10.50.1.80> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/jcalonso/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '10.50.1.80', "/bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-1389004965.66-243208615184912/rpm_key; rm -rf /root/.ansible/tmp/ansible-1389004965.66-243208615184912/ >/dev/null 2>&1'"]
failed: [10.50.1.80] => {"failed": true, "item": ""}

FATAL: all hosts have already failed -- aborting
```

**Comment by stevenscg** [comment]
I am having the same problem as @jcalonso with same key (and also the nginx signing key).

ansible 1.5 (devel 6ed48b5ad7)

**Comment by juge2** [comment]
I have the same issue as @jcalonso on a CentOS machine.
Following seems to fix it: adding a "a" to "rpm -q gpg-pubkey " when querying the existance of the key: 

```
     def is_key_imported(self, keyid):
        stdout, stderr = self.execute_command([self.rpm, '-qa', 'gpg-pubkey'])
```

**Comment by jimi-c** [comment]
It appears that this has already been addressed in the devel branch, so I'm going to go ahead and close this. Please let us know if you continue seeing this problem. Thanks!
