### ISSUE TITLE
ansible-test unicodeerror

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#55296]
##### SUMMARY

UnicodeError when running anible-test

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

test/runner/lib/util.py

##### ANSIBLE VERSION

```paste below
stable-2.8
```

##### CONFIGURATION

```paste below
Running in shippable
```

##### STEPS TO REPRODUCE

Unsure but we can probably fix the UnicodeError by normalizing types someplace.

```yaml

```

##### EXPECTED RESULTS

tests either pass or an error occurs in ansible code itself ;-)

##### ACTUAL RESULTS

From: https://app.shippable.com/github/ansible/ansible/runs/119280/29/console

```paste below
38:19 Stopped running windows/2008 instance ************************************.
38:19 Traceback (most recent call last):
38:19   File "/root/ansible/bin/ansible-test", line 15, in <module>
38:19     lib.cli.main()
38:19   File "/root/ansible/test/runner/lib/cli.py", line 108, in main
38:19     args.func(config)
38:19   File "/root/ansible/test/runner/lib/executor.py", line 614, in command_windows_integration
38:19     post_target=post_target)
38:19   File "/root/ansible/test/runner/lib/executor.py", line 888, in command_integration_filtered
38:19     command_integration_role(args, target, start_at_task, test_dir, inventory_path, common_temp_path)
38:19   File "/root/ansible/test/runner/lib/executor.py", line 1239, in command_integration_role
38:19     with integration_test_environment(args, target, inventory_path) as test_env:
38:19   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
38:19     return self.gen.next()
38:19   File "/root/ansible/test/runner/lib/integration/__init__.py", line 155, in integration_test_environment
38:19     display.info('Preparing temporary directory: %s' % temp_dir, verbosity=2)
38:19   File "/root/ansible/test/runner/lib/util.py", line 714, in info
38:19     self.print_message(message, color=color, fd=sys.stderr if self.info_stderr else sys.stdout, truncate=truncate)
38:19   File "/root/ansible/test/runner/lib/util.py", line 725, in print_message
38:19     message = message.replace(item, '*' * len(item))
38:19 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 74: ordinal not in range(128)
```

**Comment by abadger** [comment]
@mattclay

**Comment by Akasurde** [comment]
resolved_by_pr #55328
