### ISSUE TITLE
can't create a category tag 

### ISSUE THREAD

**Issue by landerhm** [ansible/ansible#55374]
SUMMARY
I try to create a category in vsphere but have a giant error

**this is mi YAML:**
---
- hosts: host1
  gather_facts: false
  connection: local

  tasks:
    - name: create category
      vmware_category:
        hostname: '{{ hostname }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: no
        category_name: Sample_Cat_0001
        category_description: Sample Description
        category_cardinality: 'multiple'
...

**And the result whit -vvv is:**
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1555347583.8-120459565020543/AnsiballZ_vmware_category.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1555347583.8-120459565020543/AnsiballZ_vmware_category.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1555347583.8-120459565020543/AnsiballZ_vmware_category.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_vmware_category_payload_2tawJJ/__main__.py", line 258, in <module>
  File "/tmp/ansible_vmware_category_payload_2tawJJ/__main__.py", line 253, in main
  File "/tmp/ansible_vmware_category_payload_2tawJJ/__main__.py", line 129, in __init__
  File "/tmp/ansible_vmware_category_payload_2tawJJ/ansible_vmware_category_payload.zip/ansible/module_utils/vmware_rest_client.py", line 51, in __init__
  File "/tmp/ansible_vmware_category_payload_2tawJJ/ansible_vmware_category_payload.zip/ansible/module_utils/vmware_rest_client.py", line 101, in connect_to_rest
  File "/usr/lib/python2.7/site-packages/com/vmware/cis_client.py", line 197, in create
    return self._invoke('create', None)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 243, in native_invoke
    method_result = self.invoke(ctx, method_id, data_val)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 179, in invoke
    ctx)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/security/client/security_context_filter.py", line 99, in invoke
    self, service_id, operation_id, input_value, new_ctx)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/provider/filter.py", line 76, in invoke
    service_id, operation_id, input_value, ctx)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 79, in invoke
    response = self._do_request(VAPI_INVOKE, params)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 120, in _do_request
    headers=request_headers, body=request_body))
  File "/usr/lib/python2.7/site-packages/vmware/vapi/protocol/client/rpc/requests_provider.py", line 98, in do_request
    cookies=http_request.cookies, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='194.140.50.11', port=443): Max retries exceeded with url: /api (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))

fatal: [host1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1555347583.8-120459565020543/AnsiballZ_vmware_category.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1555347583.8-120459565020543/AnsiballZ_vmware_category.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1555347583.8-120459565020543/AnsiballZ_vmware_category.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_vmware_category_payload_2tawJJ/__main__.py\", line 258, in <module>\n  File \"/tmp/ansible_vmware_category_payload_2tawJJ/__main__.py\", line 253, in main\n  File \"/tmp/ansible_vmware_category_payload_2tawJJ/__main__.py\", line 129, in __init__\n  File \"/tmp/ansible_vmware_category_payload_2tawJJ/ansible_vmware_category_payload.zip/ansible/module_utils/vmware_rest_client.py\", line 51, in __init__\n  File \"/tmp/ansible_vmware_category_payload_2tawJJ/ansible_vmware_category_payload.zip/ansible/module_utils/vmware_rest_client.py\", line 101, in connect_to_rest\n  File \"/usr/lib/python2.7/site-packages/com/vmware/cis_client.py\", line 197, in create\n    return self._invoke('create', None)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py\", line 317, in _invoke\n    return self._api_interface.native_invoke(ctx, _method_name, kwargs)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py\", line 243, in native_invoke\n    method_result = self.invoke(ctx, method_id, data_val)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py\", line 179, in invoke\n    ctx)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/security/client/security_context_filter.py\", line 99, in invoke\n    self, service_id, operation_id, input_value, new_ctx)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/provider/filter.py\", line 76, in invoke\n    service_id, operation_id, input_value, ctx)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py\", line 79, in invoke\n    response = self._do_request(VAPI_INVOKE, params)\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py\", line 120, in _do_request\n    headers=request_headers, body=request_body))\n  File \"/usr/lib/python2.7/site-packages/vmware/vapi/protocol/client/rpc/requests_provider.py\", line 98, in do_request\n    cookies=http_request.cookies, timeout=timeout)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/adapters.py\", line 510, in send\n    raise ProxyError(e, request=request)\nrequests.exceptions.ProxyError: HTTPSConnectionPool(host='194.140.50.11', port=443): Max retries exceeded with url: /api (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

ISSUE TYPE
- Bug Report

ANSIBLE VERSION
2.7.10

OS / ENVIRONMENT
Centos7

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
