### ISSUE TITLE
Escaping issue when parsing errors that contain quotes

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#556]
When I caused an error because of a typo in a path (_/etc/xinet.d/tftp_ instead of _/etc/xinetd.d/tftp_) I got a python stacktrace because there's an escaping issue because my error output contained a single quote.

```
TASK: [create /etc/xinetd.d/tftp] *********************

failed to parse json: cp: cannot create regular file `/etc/xinet.d/tftp': No such file or directory

dest='/etc/xinet.d/tftp' src='/var/tmp/ansible-1341829870.07-197508277564784/tftp' changed='md5sum=83e8ec83ff9cae3c9fe085aad78678d7 changed=True'

fatal: [sctl0004] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 626, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 670, in _executor_internal
    result = self._execute_copy(conn, tmp)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 444, in _execute_copy
    exec_rc = self._execute_module(conn, tmp, module, args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 315, in _execute_module
    return ReturnData(host=conn.host, result=res, executed_str=executed_str)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 83, in __init__
    self.result = utils.parse_json(self.result)
  File "/usr/lib/python2.6/site-packages/ansible/utils.py", line 186, in parse_json
    tokens = shlex.split(data)
  File "/usr/lib64/python2.6/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.6/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.6/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation`
```

**Comment by dagwieers** [comment]
Ok, seems to be fixed in the proper 0.5 release ! Never mind...
