### ISSUE TITLE
ec2.py --list can timeout and/or be blocked on 'all' region call

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#5565]
From chat in irc

```
22:23:57 < llakey> i get an error "Looks like AWS is down again" when using  
                ec2.py --list   with ec2.ini   regions = all   but when i 
                change   regions = us-west-1   the error goes away
```

I was curious and had a look into this

I modified ec2.ini to use the full list of regions (as given by print self.regions) and added a print statement to see which region it was stopping on, found in this case it was freezing on 'cn-north-1'

i.e. this would block: 

```
regions = ap-southeast-1,ap-southeast-2,us-west-2,us-east-1,us-west-1,cn-north-1,sa-east-1,ap-northeast-1,eu-west-1
```

this worked:

```
regions = ap-southeast-1,ap-southeast-2,us-west-2,us-east-1,us-west-1,sa-east-1,ap-northeast-1,eu-west-1
```

run output

```
~/Repos/ansible_cfg/plugins/inventory $ python ec2.py --list
ap-southeast-1
ap-southeast-2
us-west-2
us-east-1
us-west-1
cn-north-1
^CTraceback (most recent call last):
  File "ec2.py", line 609, in <module>
    Ec2Inventory()
  File "ec2.py", line 155, in __init__
    self.do_api_calls_update_cache()
  File "ec2.py", line 256, in do_api_calls_update_cache
    self.get_instances_by_region(region)
  File "ec2.py", line 281, in get_instances_by_region
    reservations = conn.get_all_instances()
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 574, in get_all_instances
    max_results=max_results)
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 655, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1117, in get_list
     response = self.make_request(action, params, path, verb)
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1063, in make_request
    return self._mexe(http_request)
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 901, in _mexe
    request.body, request.headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/Library/Python/2.7/site-packages/boto/https_connection.py", line 111, in connect
    sock.connect((self.host, self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

and with cn-north-1 removed

```
~/Repos/ansible_cfg/plugins/inventory $ python ec2.py --list
ap-southeast-1
ap-southeast-2
us-west-2
us-east-1
us-west-1
sa-east-1
ap-northeast-1
eu-west-1
{
  "_meta": {
  ...
```

Didn't see any boto exceptions.

Sorry my python foo is not good enough for me to submit a fix, guessing some sort of Timeout class wrapper except handler thingy would be in order.

**Comment by halberom** [comment]
This may no longer be required, looks like someone's added a 'regions_exclude' option, with (oddly enough) cn-north-1 as one of the excluded options.

**Comment by mpdehaan** [comment]
Yep, this should take care of the above.    Thanks for pointing this out!
