### ISSUE TITLE
'ascii' codec can't encode character u'\u2019'

### ISSUE THREAD

**Issue by nizsheanez** [ansible/ansible#5568]
```
<192.168.56.10> ESTABLISH CONNECTION FOR USER: root
<192.168.56.10> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/nizsheanez/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.56.10', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1389339974.9-162239878520991 && chmod a+rx $HOME/.ansible/tmp/ansible-1389339974.9-162239878520991 && echo $HOME/.ansible/tmp/ansible-1389339974.9-162239878520991'"]
fatal: [192.168.56.10] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 514, in _executor_internal
    complex_args=complex_args
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 679, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/Library/Python/2.7/site-packages/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/Library/Python/2.7/site-packages/ansible/utils/template.py", line 521, in template_from_string
    data = data.decode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 47: ordinal not in range(128)


FATAL: all hosts have already failed -- aborting
```

My os - Os X 10.9.1
Try to  do `apt-get install` on Ubuntu 12.04.3 LTS (Setup on VirtualBox)

**Comment by nizsheanez** [comment]
sorry, it was wrong quotes in playbook, after copypaste
