### ISSUE TITLE
Can't install directly from github using pip -e

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#558]
I wanted to install ansible directly from github, using pip -e. Unfortunately, it fails to install properly:

```
$ pip install -e git://github.com/ansible/ansible.git#egg=ansible
Obtaining ansible from git+git://github.com/ansible/ansible.git#egg=ansible
  Cloning git://github.com/ansible/ansible.git to ./.virtualenvs/ansible/src/ansible
  Running setup.py egg_info for package ansible

    warning: no files found matching 'packaging/distutils/setup.py'
Requirement already satisfied (use --upgrade to upgrade): paramiko in ./.virtualenvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in ./.virtualenvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in ./.virtualenvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.1 in ./.virtualenvs/ansible/lib/python2.7/site-packages (from paramiko->ansible)
Installing collected packages: ansible
  Running setup.py develop for ansible

    warning: no files found matching 'packaging/distutils/setup.py'
    Creating /Users/lorin/.virtualenvs/ansible/lib/python2.7/site-packages/ansible.egg-link (link to .)
    Adding ansible 0.6 to easy-install.pth file
    Installing ansible script to /Users/lorin/.virtualenvs/ansible/bin
    Installing ansible-playbook script to /Users/lorin/.virtualenvs/ansible/bin

    Installed /Users/lorin/.virtualenvs/ansible/src/ansible
Successfully installed ansible
```

When I try to run, it fails:

```
$ ansible
Traceback (most recent call last):
  File "/Users/lorin/.virtualenvs/ansible/bin/ansible", line 7, in <module>
    execfile(__file__)
  File "/Users/lorin/.virtualenvs/ansible/src/ansible/bin/ansible", line 25, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
```

Installing version 0.5 from the tarball works fine:

```
pip install https://github.com/downloads/ansible/ansible/ansible-0.5.tar.gz
```

**Comment by mpdehaan** [comment]
most people will be using source or RPM.

pip isn't really a concern as long as make install works.

patches to fix this that do not break other distro packaging can be considered
