### ISSUE TITLE
gce modules need a better way to handle invalid key files

### ISSUE THREAD

**Issue by erjohnso** [ansible/ansible#5583]
If the user specifies an unsupported Service Account private key, the cloud/gce\* modules do not catch the error and produce a traceback like:

failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1389289770.6-124236068572659/gce", line 1446, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1389289770.6-124236068572659/gce", line 376, in main
    module.fail_json(msg=unexpected_error_msg(e), changed=False)
  File "/root/.ansible/tmp/ansible-1389289770.6-124236068572659/gce", line 190, in unexpected_error_msg
    error.http_code, error.code, str(error.value))
AttributeError: 'exceptions.ValueError' object has no attribute 'http_code'

@erjohnso will work on a fix and submit a pull-request.

**Comment by erjohnso** [comment]
Perhaps related, https://groups.google.com/forum/#!msg/ansible-project/WTef9t1TyA0/8YOuZNs9EwAJ
