### ISSUE TITLE
ansible-doc does not like git submdules for custom modules

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5612]
# Problem:

If you add a custom module using git submodules, ansible-doc prints traceback.
## setup in ansible.cfg

we set up a path for custom modules:

```
[default]
library = /usr/share/ansible:library
```
## custom modules added with submodules

we added a module named openvz using `git submodule add <module> library/openvz

```
library$ find
.
./openvz
./openvz/.git
./openvz/openvz
```
## content of .git

```
$ cat ./openvz/.git
 gitdir: ../../../.git/modules/playbooks/library/openvz
```
## error in run command ansible-doc

```
$ ansible-doc -l 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/module_docs.py", line 44, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    gitdir: ../../../.git/modules/playbooks/library/openvz
          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/local/bin/ansible-doc", line 174, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
...
```
## ansible version

```
$ ansible --version
ansible 1.5
```
# Expected

ansible-doc should ignore "hidden" directories.

**Comment by mpdehaan** [comment]
Probably should, is this something you would like to work on?

**Comment by resmo** [comment]
yes, will have a look the next few days.

**Comment by bcoca** [comment]
closing as these were fixed in passing with ansible-doc fixes for the repo separation of modules
