### ISSUE TITLE
ec2_group fails on repeated run (?)

### ISSUE THREAD

**Issue by dbrgn** [ansible/ansible#5643]
I want to assert that certain EC2 security groups are present.

```
- name: Create EC2 SSH security group.
  ec2_group:
    name: SSH
    description: Allows SSH access.
    state: present
    region: "{{ aws_region }}"
    rules:
      - proto: tcp 
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
```

It works the first time:

```
$ ansible-playbook -i hosts provision.yml 

PLAY [localhost] ************************************************************** 

TASK: [ec2 | Create EC2 SSH security group.] ********************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

But when running it again, it fails:

```
$ ansible-playbook -i hosts provision.yml 

PLAY [localhost] ************************************************************** 

TASK: [ec2 | Create EC2 SSH security group.] ********************************** 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/danilo/.ansible/tmp/ansible-1389865891.33-218682145301746/ec2_group", line 1313, in <module>
    main()
  File "/home/danilo/.ansible/tmp/ansible-1389865891.33-218682145301746/ec2_group", line 192, in main
    group = ec2.create_security_group(name, description, vpc_id=vpc_id)
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 2948, in create_security_group
    SecurityGroup, verb='POST')
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1151, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.Duplicate</Code><Message>The security group 'SSH' already exists for VPC 'vpc-ab1e15c9'</Message></Error></Errors><RequestID>76a8ffae-6e58-4ab4-aacb-fff220476816</RequestID></Response>


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/danilo/provision.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

Is there a way to make this module idempotent? When a rule with the same name already exists, the rules should be compared. If they're the same, it should set the status to "not changed". (Otherwise an error could be thrown.)

**Comment by jamesmoriarty** [comment]
+1 @jlaska makes me wonder whats going on here: https://github.com/ansible/ansible/pull/4338/files

**Comment by jctanner** [comment]
@dbrgn I'm not seeing a traceback for this behavior as of ...

```
ansible 1.6 (devel 8fce4ed7bf) last updated 2014/03/24 10:31:14 (GMT -400)
```

```
jtanner@u1204:~/issues/5643-ec2_group-idempotent$ ansible-playbook -v -i inventory site.yml

PLAY [localhost] **************************************************************

TASK: [ec2_group ] ************************************************************
changed: [localhost] => {"changed": true, "group_id": "sg-8d28d2e8"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

jtanner@u1204:~/issues/5643-ec2_group-idempotent$ ansible-playbook -v -i inventory site.yml

PLAY [localhost] **************************************************************

TASK: [ec2_group ] ************************************************************
changed: [localhost] => {"changed": true, "group_id": "sg-8d28d2e8"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

I will try to figure out why the result is always "changed" though

**Comment by jctanner** [comment]
It seems like this is a bug in boto where the rules for a group are always empty:

```
group.rules: []
```

EDIT:

It actually appears to be an issue where the appended rules aren't being saved.

```
(Epdb) pp [(x.name, x.rules) for x in ec2.get_all_security_groups() if x.name == 'integration_test_group' ]
[(u'integration_test_group', [])]
(Epdb) group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
True
(Epdb) pp [(x.name, x.rules) for x in ec2.get_all_security_groups() if x.name == 'integration_test_group' ]
[(u'integration_test_group', [])]
```

EDIT:

Had a typo in my complex args: cidr_op instead of cidr_ip

**Comment by xenithorb** [comment]
Hi, sorry to pry but what is the closed status for this issue?

This is currently affecting me with:

ansible (1.9.0.1)
boto (2.36.0)

**Comment by calpeyser** [comment]
Is there a workaround here? I also can't get idempotence with ec2_group on ansible 1.9.1.

**Comment by Russell-IO** [comment]
@jctanner - Also happening here on every checkout of 1.8.X & 1.9.X & devel

**Comment by tudvari** [comment]
Hi Guys,

 do we have any update about this issue? I have the same issue. :-(

Ansible version is: ansible 2.1.0.0

Thanks in advance.

BR,
Tibor

**Comment by Blackbaud-FrankKurzawa** [comment]
I have just begun having this issue as well. Did not see it before upgrading to 2.1.0.0.
