### ISSUE TITLE
Bug report: commit broke something in sysctl module

### ISSUE THREAD

**Issue by dekked** [ansible/ansible#5656]
Commit ca05584495 broke something in sysctl module.

Before, this worked like a charm:

```
- sysctl: name=net.ipv4.ip_local_port_range value="10240 65535"
```

But now it fails:

```
fatal: [vagrantdev] => failed to parse: SUDO-SUCCESS-hjtblpteduzsyjzliewtuykkqvvrflvc
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1389902636.55-170849899960565/sysctl", line 1316, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1389902636.55-170849899960565/sysctl", line 276, in main
    result = SysctlModule(module)    
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1389902636.55-170849899960565/sysctl", line 113, in __init__
    self.process()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1389902636.55-170849899960565/sysctl", line 159, in process
    self.set_token_value(self.args['name'], self.args['value'])
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1389902636.55-170849899960565/sysctl", line 179, in set_token_value
    self.module.fail_json(msg='setting %s failed: %s' (token, out + err))
TypeError: 'str' object is not callable
```

**Comment by jctanner** [comment]
@dekked thanks for the report. I forgot to make sysctl_set to False by default in my refactor, so it was calling the sysctl command in your case when it should not have. It then also hit another bug by not quoting the multi column value.

**Comment by dekked** [comment]
Glad it got fixed this fast, thanks!
