### ISSUE TITLE
unquoted "*" (invalid YAML) results in stack trace

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#5773]
If I have a role with the following:

``` yaml

---
my_variable: *
```

I get the follow stack trace on run:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.4.4/libexec/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.4.4/libexec/bin/ansible-playbook", line 209, in main
    pb.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 229, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 83, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 327, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 196, in _build_role_dependencies
    defaults_data = utils.parse_yaml_from_file(defaults)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 483, in parse_yaml_from_file
    process_yaml_error(exc, data, path)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 461, in process_yaml_error
    msg = process_common_errors(msg, probline, mark.column)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 374, in process_common_errors
    elif len(probline) and len(probline) >= column and probline[column] == ":" and probline.count(':') > 1:
IndexError: string index out of range
```

Enclosing the \* in quotes fixes this. 

``` yaml
my_variable: "*"
```

Rather than a stack trace, an informative error is expected.

**Comment by mpdehaan** [comment]
Per contributing.md, please share the version of ansible you are using.

**Comment by mattwillsher** [comment]
Sorry. It's 1.4.4

**Comment by mpdehaan** [comment]
Thanks.

**Comment by bcoca** [comment]
- is a special character in yaml, used for defining aliases

**Comment by risaacson** [comment]
This is related to GH-5116 which was fixed with GH-6197.

The problem here is in the process_common_errors where if len(probline) is equal to column you are out of bounds as probline goes from 0 to len(probline) - 1 not 0 to len(probline).

Fix forthcoming.
