### ISSUE TITLE
apt_repository module does not work for old version of python-apt

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5853]
This is a followup for #4869 and depends on #5852 

When I try to use `apt_repository` on Lenny I get an error:

```
fatal: [foobar.com] => failed to parse: /usr/lib/python2.5/site-packages/apt/__init__.py:18: FutureWarning: apt API not stable yet
  warnings.warn("apt API not stable yet", FutureWarning)
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1391367475.03-203168204750413/apt_repository", line 1430, in <module>
    main()
  File "/tmp/ansible-tmp-1391367475.03-203168204750413/apt_repository", line 359, in main
    sourceslist = SourcesList()
  File "/tmp/ansible-tmp-1391367475.03-203168204750413/apt_repository", line 114, in __init__
    self.default_file = apt_pkg.config.find_file('Dir::Etc::sourcelist')
AttributeError: 'module' object has no attribute 'config'
```

If I use `default_release` param I receive the following error:

```
fatal: [foobar.com] => failed to parse: Traceback (most recent call last):
  File "/tmp/ansible-tmp-1391364842.19-229111251307739/apt", line 1495, in <module>
    main()
  File "/tmp/ansible-tmp-1391364842.19-229111251307739/apt", line 387, in main
    apt_pkg.config['APT::Default-Release'] = p['default_release']
AttributeError: 'module' object has no attribute 'config'
```

I'll send pull request for that in a several moments.

**Comment by jimi-c** [comment]
Merged the above, so closing this issue. Thanks!
