### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable on npm output

### ISSUE THREAD

**Issue by bobrik** [ansible/ansible#6030]
##### Issue Type:

Bug report.
##### Ansible Version:

`ansible 1.4.5`
##### Environment:

Running ansible from OS X Mavericks, trying to manage ubuntu 12.04 and Gentoo.
##### Summary:

Task that runs `npm install` cannot complete successfully, firing `IOError: [Errno 11] Resource temporarily unavailable`.
##### Steps To Reproduce:

Here's minimal playbook:

``` yaml

---
-
  hosts: all
  sudo: yes
  tasks:
    - name: Clear target dir
      file: path=/tmp/kibana state=absent recurse=yes
    - name: Check out kibana from git
      git: repo=https://github.com/elasticsearch/kibana.git
           dest=/tmp/kibana
           version=master
           force=yes
           update=yes
    - name: Install npm dependencies
      command: chdir=/tmp/kibana npm install
```

It clones kibana and runs `npm install` to install build dependencies.
##### Expected Results:

npm install should complete successfully and ansible should get results instead of dying on io.
##### Actual Results:

```
bobrik@hyperion ~/temp % ansible-playbook ansible-bug.yml -i inventory -u root

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [web229]

TASK: [Clear target dir] ******************************************************
ok: [web229]

TASK: [Check out kibana from git] *********************************************
changed: [web229]

TASK: [Install npm dependencies] **********************************************
failed to parse json: {"changed": true, "end": "2014-02-16 19:14:39.271439", "stdout": "\n> phantomjs@1.9.7-1 install /tmp/kibana/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs\n> node install.js\n\nDownloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2\nSaving to /tmp/kibana/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2\n\n> phantomjs@1.9.7-1 install /tmp/kibana/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs\n> node install.js\n\nReceiving...\nDownloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2\nSaving to /tmp/kibana/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2\nReceiving...\nReceived 787K...\nReceived 1571K...\nReceived 2360K...\nReceived 783K...\nReceived 3144K...\nReceived 3932K...\nReceived 4715K...\nReceived 5497K...\nReceived 1571K...\nReceived 6289K...\nReceived 7086K...\nReceived 7868K...\nReceived 8667K...\nReceived 2361K...\nReceived 9474K...\nReceived 10256K...\nReceived 11041K...\nReceived 11848K...\nReceived 3204K...\nReceived 12684K...\nReceived 12852K total.\nExtracting tar contents (via spawned process)\nReceived 3993K...\nReceived 4795K...\nReceived 5620K...\nReceived 6404K...\nReceived 7186K...\nReceived 7969K...\nReceived 8773K...\nReceived 9558K...\nReceived 10340K...\nReceived 11125K...\nReceived 11911K...\nReceived 12694K...\nReceived 12852K total.\nExtracting tar contents (via spawned process)\nCopying extracted folder /tmp/kibana/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2-extract-1392563671012/phantomjs-1.9.7-linux-x86_64 -> /tmp/kibana/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom\nWriting location.js file\nDone. Phantomjs binary available at /tmp/kibana/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs\nCopying extracted folder /tmp/kibana/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2-extract-1392563671225/phantomjs-1.9.7-linux-x86_64 -> /tmp/kibana/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom\nWriting location.js file\nDone. Phantomjs binary available at /tmp/kibana/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs\n\n> optipng-bin@0.3.1 postinstall /tmp/kibana/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin\n> node lib/check.js\n\n\n> gifsicle@0.1.4 postinstall /tmp/kibana/node_modules/grunt-contrib-imagemin/node_modules/gifsicle\n> node lib/check.js\n\n\n> pngquant-bin@0.1.6 postinstall /tmp/kibana/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin\n> node lib/check.js\n\n\n\n\n\u2713 pre-build test passed successfully\n\n> jpegtran-bin@0.2.3 postinstall /tmp/kibana/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin\n> node lib/check.js\n\n\n\n\n\u2713 pre-build test passed successfully\n\n\n\n\u2717 pre-build test failed, compiling from source...\n\n\n\n\u2713 pre-build test passed successfully\n\n\n\n\u2713 pngquant rebuilt successfully\nexpect.js@0.2.0 node_modules/expect.js\n\ngrunt-contrib-copy@0.4.1 node_modules/grunt-contrib-copy\n\ngrunt-string-replace@0.2.7 node_modules/grunt-string-replace\n\u2514\u2500\u2500 async@0.2.10\n\nrjs-build-analysis@0.0.3 node_modules/rjs-build-analysis\n\u251c\u2500\u2500 pegjs@0.7.0\n\u2514\u2500\u2500 lodash@1.2.1\n\ngrunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean\n\u2514\u2500\u2500 rimraf@2.2.6\n\ngrunt-angular-templates@0.3.12 node_modules/grunt-angular-templates\n\u2514\u2500\u2500 html-minifier@0.5.5\n\ngrunt-contrib-requirejs@0.4.1 node_modules/grunt-contrib-requirejs\n\u2514\u2500\u2500 requirejs@2.1.10\n\ngrunt-git-describe@2.3.2 node_modules/grunt-git-describe\n\u251c\u2500\u2500 grunt-util-process@0.0.1\n\u251c\u2500\u2500 grunt-util-args@0.0.3\n\u251c\u2500\u2500 grunt-util-spawn@0.0.2\n\u2514\u2500\u2500 grunt-util-options@0.0.2 (grunt-util-property@0.0.1)\n\ngrunt-contrib-htmlmin@0.1.3 node_modules/grunt-contrib-htmlmin\n\u251c\u2500\u2500 html-minifier@0.5.5\n\u2514\u2500\u2500 grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)\n\ngrunt-contrib-cssmin@0.6.2 node_modules/grunt-contrib-cssmin\n\u251c\u2500\u2500 clean-css@1.1.7 (commander@2.0.0)\n\u2514\u2500\u2500 grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)\n\nkat@0.2.2 node_modules/kat\n\u251c\u2500\u2500 queue2@0.1.0\n\u2514\u2500\u2500 readable-stream@1.0.25 (string_decoder@0.10.25-1)\n\nglob@3.2.8 node_modules/glob\n\u251c\u2500\u2500 inherits@2.0.1\n\u2514\u2500\u2500 minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)\n\ngrunt-contrib-connect@0.5.0 node_modules/grunt-contrib-connect\n\u251c\u2500\u2500 connect-livereload@0.2.0\n\u251c\u2500\u2500 open@0.0.4\n\u2514\u2500\u2500 connect@2.7.11 (fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, debug@0.7.4, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.0.5, formidable@1.0.14, send@0.1.1)\n\ngrunt-scratchy@0.5.0 node_modules/grunt-scratchy\n\u2514\u2500\u2500 scratchy@3.0.0-pre-milestone5 (underscore@1.5.2, mkdirp@0.3.5, optimist@0.6.1, underscore.string@2.3.3)\n\ngrunt-contrib-compress@0.5.3 node_modules/grunt-contrib-compress\n\u251c\u2500\u2500 prettysize@0.0.3\n\u251c\u2500\u2500 lazystream@0.1.0 (readable-stream@1.0.25)\n\u2514\u2500\u2500 archiver@0.4.10 (readable-stream@1.0.25, iconv-lite@0.2.11)\n\nload-grunt-tasks@0.2.1 node_modules/load-grunt-tasks\n\u251c\u2500\u2500 globule@0.1.0 (lodash@1.0.1, glob@3.1.21, minimatch@0.2.14)\n\u2514\u2500\u2500 findup-sync@0.1.2 (lodash@1.0.1, glob@3.1.21)\n\ngrunt-contrib-jshint@0.6.5 node_modules/grunt-contrib-jshint\n\u2514\u2500\u2500 jshint@2.1.11 (console-browserify@0.1.6, cli@0.4.5, underscore@1.4.4, shelljs@0.1.4, minimatch@0.2.14)\n\ngrunt-s3@0.2.0-alpha.3 node_modules/grunt-s3\n\u251c\u2500\u2500 mime@1.2.11\n\u251c\u2500\u2500 underscore.deferred@0.1.5\n\u251c\u2500\u2500 temporary@0.0.5 (package@1.0.1)\n\u2514\u2500\u2500 knox@0.8.9 (debug@0.7.4, stream-counter@0.1.0, xml2js@0.2.8)\n\ngrunt-ngmin@0.0.3 node_modules/grunt-ngmin\n\u2514\u2500\u2500 ngmin@0.4.1 (astral@0.1.0, clone@0.1.11, commander@1.1.1, astral-angular-annotate@0.0.2, esprima@1.0.4, escodegen@0.0.28)\n\ngrunt@0.4.2 node_modules/grunt\n\u251c\u2500\u2500 which@1.0.5\n\u251c\u2500\u2500 dateformat@1.0.2-1.2.3\n\u251c\u2500\u2500 eventemitter2@0.4.13\n\u251c\u2500\u2500 getobject@0.1.0\n\u251c\u2500\u2500 colors@0.6.2\n\u251c\u2500\u2500 hooker@0.2.3\n\u251c\u2500\u2500 async@0.1.22\n\u251c\u2500\u2500 exit@0.1.2\n\u251c\u2500\u2500 glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)\n\u251c\u2500\u2500 lodash@0.9.2\n\u251c\u2500\u2500 coffee-script@1.3.3\n\u251c\u2500\u2500 underscore.string@2.2.1\n\u251c\u2500\u2500 findup-sync@0.1.2 (lodash@1.0.1)\n\u251c\u2500\u2500 iconv-lite@0.2.11\n\u251c\u2500\u2500 rimraf@2.0.3 (graceful-fs@1.1.14)\n\u251c\u2500\u2500 nopt@1.0.10 (abbrev@1.0.4)\n\u251c\u2500\u2500 minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)\n\u2514\u2500\u2500 js-yaml@2.0.5 (argparse@0.1.15, esprima@1.0.4)\n\ngrunt-contrib-uglify@0.2.7 node_modules/grunt-contrib-uglify\n\u251c\u2500\u2500 grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)\n\u2514\u2500\u2500 uglify-js@2.4.12 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.32)\n\ngrunt-contrib-less@0.7.0 node_modules/grunt-contrib-less\n\u251c\u2500\u2500 grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)\n\u2514\u2500\u2500 less@1.4.2 (mime@1.2.11, mkdirp@0.3.5, ycssmin@1.0.1, request@2.33.0)\n\ngrunt-contrib-concat@0.3.0 node_modules/grunt-contrib-concat\n\ngrunt-contrib-compass@0.6.0 node_modules/grunt-contrib-compass\n\u251c\u2500\u2500 dargs@0.1.0\n\u251c\u2500\u2500 tmp@0.0.21\n\u2514\u2500\u2500 async@0.2.10\n\ngrunt-contrib-sass@0.5.1 node_modules/grunt-contrib-sass\n\u251c\u2500\u2500 dargs@0.1.0\n\u2514\u2500\u2500 async@0.2.10\n\ngrunt-contrib-csslint@0.1.2 node_modules/grunt-contrib-csslint\n\u2514\u2500\u2500 csslint@0.9.10\n\ngrunt-contrib-coffee@0.7.0 node_modules/grunt-contrib-coffee\n\u2514\u2500\u2500 coffee-script@1.6.3\n\ngrunt-contrib-jst@0.5.1 node_modules/grunt-contrib-jst\n\u251c\u2500\u2500 grunt-lib-contrib@0.5.3 (zlib-browserify@0.0.1)\n\u2514\u2500\u2500 lodash@1.0.1\n\ngrunt-contrib-watch@0.5.3 node_modules/grunt-contrib-watch\n\u251c\u2500\u2500 gaze@0.4.3 (globule@0.1.0)\n\u2514\u2500\u2500 tiny-lr@0.0.4 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)\n\ngrunt-contrib-handlebars@0.5.12 node_modules/grunt-contrib-handlebars\n\u251c\u2500\u2500 grunt-lib-contrib@0.5.3 (zlib-browserify@0.0.1)\n\u2514\u2500\u2500 handlebars@1.0.12 (optimist@0.3.7, uglify-js@2.3.6)\n\ngrunt-contrib-stylus@0.8.0 node_modules/grunt-contrib-stylus\n\u251c\u2500\u2500 nib@1.0.2\n\u2514\u2500\u2500 stylus@0.37.0 (debug@0.7.4, mkdirp@0.3.5, cssom@0.2.5, sax@0.5.8)\n\ngrunt-contrib-qunit@0.3.0 node_modules/grunt-contrib-qunit\n\u2514\u2500\u2500 grunt-lib-phantomjs@0.4.0 (eventemitter2@0.4.13, semver@1.0.14, temporary@0.0.8, phantomjs@1.9.7-1)\n\ngrunt-contrib-jasmine@0.5.2 node_modules/grunt-contrib-jasmine\n\u251c\u2500\u2500 rimraf@2.1.4 (graceful-fs@1.2.3)\n\u2514\u2500\u2500 grunt-lib-phantomjs@0.4.0 (eventemitter2@0.4.13, semver@1.0.14, temporary@0.0.8, phantomjs@1.9.7-1)\n\ngrunt-contrib-jade@0.8.0 node_modules/grunt-contrib-jade\n\u251c\u2500\u2500 grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)\n\u2514\u2500\u2500 jade@0.34.1 (character-parser@1.0.2, mkdirp@0.3.5, commander@1.3.2, transformers@2.1.0, monocle@0.1.50, constantinople@1.0.2, with@1.1.1)\n\ngrunt-contrib-nodeunit@0.2.2 node_modules/grunt-contrib-nodeunit\n\u2514\u2500\u2500 nodeunit@0.8.5 (tap@0.4.8)\n\ngrunt-contrib-yuidoc@0.5.0 node_modules/grunt-contrib-yuidoc\n\u2514\u2500\u2500 yuidocjs@0.3.47 (graceful-fs@2.0.1, marked@0.2.10, rimraf@2.0.3, minimatch@0.2.14, express@3.1.2, yui@3.9.1)\n\ngrunt-contrib-imagemin@0.3.0 node_modules/grunt-contrib-imagemin\n\u251c\u2500\u2500 filesize@1.10.0\n\u251c\u2500\u2500 chalk@0.2.1 (ansi-styles@0.2.0, has-color@0.1.4)\n\u251c\u2500\u2500 optipng-bin@0.3.1 (bin-wrapper@0.1.9)\n\u251c\u2500\u2500 gifsicle@0.1.4 (bin-wrapper@0.1.9)\n\u251c\u2500\u2500 jpegtran-bin@0.2.3 (bin-wrapper@0.1.9)\n\u2514\u2500\u2500 pngquant-bin@0.1.6 (bin-wrapper@0.1.9)\n\ngrunt-contrib@0.8.0 node_modules/grunt-contrib\n\u2514\u2500\u2500 matchdep@0.3.0 (stack-trace@0.0.7, resolve@0.5.1, globule@0.1.0, findup-sync@0.1.2)", "cmd": ["npm", "install"], "start": "2014-02-16 19:14:20.622081", "delta": "0:00:18.649358", "stderr": "npm http GET https://registry.npmjs.org/rjs-build-analysis/0.0.3\nnpm http GET https://registry.npmjs.org/grunt-s3\nnpm http GET https://registry.npmjs.org/grunt-ngmin/0.0.3\nnpm http GET https://registry.npmjs.org/grunt\nnpm http GET https://registry.npmjs.org/grunt-contrib-less\nnpm http GET https://registry.npmjs.org/grunt-contrib\nnpm http GET https://registry.npmjs.org/kat\nnpm http GET https://registry.npmjs.org/grunt-git-describe\nnpm http GET https://registry.npmjs.org/grunt-contrib-clean\nnpm http GET https://registry.npmjs.org/grunt-contrib-copy\nnpm http GET https://registry.npmjs.org/grunt-contrib-cssmin\nnpm http GET https://registry.npmjs.org/grunt-contrib-jshint\nnpm http GET https://registry.npmjs.org/expect.js\nnpm http GET https://registry.npmjs.org/grunt-string-replace\nnpm http GET https://registry.npmjs.org/grunt-contrib-requirejs\nnpm http GET https://registry.npmjs.org/grunt-contrib-htmlmin\nnpm http GET https://registry.npmjs.org/grunt-angular-templates\nnpm http GET https://registry.npmjs.org/grunt-contrib-compress\nnpm http GET https://registry.npmjs.org/grunt-contrTraceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1392563661.83-132917433521452/command", line 1233, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1392563661.83-132917433521452/command", line 156, in main
    changed = True
  File "/root/.ansible/tmp/ansible-1392563661.83-132917433521452/command", line 993, in exit_json
    print self.jsonify(kwargs)
IOError: [Errno 11] Resource temporarily unavailable

fatal: [web229] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 685, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 369, in _execute_module
    data = utils.parse_json(res['stdout'])
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 311, in parse_json
    tokens = shlex.split(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/bobrik/ansible-bug.retry

web229                     : ok=3    changed=1    unreachable=1    failed=0
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
