### ISSUE TITLE
NETWORK_GROUP_MODULES in executor/task_executor.py doesn't support FQCN for local connection

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible#60419]
##### SUMMARY
When trying to run a network collection, vyos in this case, using connection local. Ansible will not properly load the tasks.  This is because we parse the module name to get the platform and look it up in NETWORK_GROUP_MODULES.

Ansible collection: https://github.com/ansible-network/ansible_collections.vyos.vyos/pull/12

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/executor/task_executor.py

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

https://logs.zuul.ansible.com/12/12/416dc67d6cf20f89e5f9e9450db1cee503df39aa/check/ansible-test-network-integration-vyos-python35/3f1681e/zuul-info/inventory.yaml

##### STEPS TO REPRODUCE

```yaml
We've created our first network collection at https://github.com/ansible-network/ansible_collections.vyos.vyos/pull/12

git clone locally, run ansible-test network-integration
```

##### EXPECTED RESULTS

Testing to work

##### ACTUAL RESULTS

https://logs.zuul.ansible.com/12/12/416dc67d6cf20f89e5f9e9450db1cee503df39aa/check/ansible-test-network-integration-vyos-python35/3f1681e/job-output.html#l3860

```paste below
2019-08-10 01:16:08.274050 | ubuntu-xenial | TASK [vyos_facts : get host name] **********************************************
2019-08-10 01:16:08.274431 | ubuntu-xenial | task path: /home/zuul/.ansible/collection/ansible_collections/vyos/vyos/test/integration/targets/vyos_facts/tests/cli/basic_facts.yaml:1
2019-08-10 01:16:08.353237 | ubuntu-xenial | <38.108.68.198> ESTABLISH LOCAL CONNECTION FOR USER: zuul
2019-08-10 01:16:08.354547 | ubuntu-xenial | <38.108.68.198> EXEC /bin/sh -c 'echo ~zuul && sleep 0'
2019-08-10 01:16:08.365488 | ubuntu-xenial | <38.108.68.198> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654 `" && echo ansible-tmp-1565399768.351818-246593410746654="` echo /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654 `" ) && sleep 0'
2019-08-10 01:16:08.375009 | ubuntu-xenial | Using module file /home/zuul/.ansible/collection/ansible_collections/vyos/vyos/plugins/modules/vyos_command.py
2019-08-10 01:16:08.376602 | ubuntu-xenial | <38.108.68.198> PUT /home/zuul/.ansible/tmp/ansible-local-4181hnoxzrf7/tmpxfphx3t8 TO /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py
2019-08-10 01:16:08.378338 | ubuntu-xenial | <38.108.68.198> EXEC /bin/sh -c 'chmod u+x /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/ /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py && sleep 0'
2019-08-10 01:16:08.385415 | ubuntu-xenial | <38.108.68.198> EXEC /bin/sh -c 'python /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py && sleep 0'
2019-08-10 01:16:08.678158 | ubuntu-xenial | <38.108.68.198> EXEC /bin/sh -c 'rm -f -r /home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/ > /dev/null 2>&1 && sleep 0'
2019-08-10 01:16:08.691989 | ubuntu-xenial | The full traceback is:
2019-08-10 01:16:08.692095 | ubuntu-xenial | Traceback (most recent call last):
2019-08-10 01:16:08.692209 | ubuntu-xenial |   File "/home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py", line 139, in <module>
2019-08-10 01:16:08.692245 | ubuntu-xenial |     _ansiballz_main()
2019-08-10 01:16:08.692341 | ubuntu-xenial |   File "/home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py", line 131, in _ansiballz_main
2019-08-10 01:16:08.692394 | ubuntu-xenial |     invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
2019-08-10 01:16:08.692487 | ubuntu-xenial |   File "/home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py", line 65, in invoke_module
2019-08-10 01:16:08.692526 | ubuntu-xenial |     spec.loader.exec_module(module)
2019-08-10 01:16:08.692586 | ubuntu-xenial |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
2019-08-10 01:16:08.692670 | ubuntu-xenial |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2019-08-10 01:16:08.692759 | ubuntu-xenial |   File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/__main__.py", line 229, in <module>
2019-08-10 01:16:08.692848 | ubuntu-xenial |   File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/__main__.py", line 202, in main
2019-08-10 01:16:08.693007 | ubuntu-xenial |   File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 111, in run_commands
2019-08-10 01:16:08.693170 | ubuntu-xenial |   File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 70, in get_connection
2019-08-10 01:16:08.693371 | ubuntu-xenial |   File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 85, in get_capabilities
2019-08-10 01:16:08.693495 | ubuntu-xenial |   File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible/module_utils/connection.py", line 122, in __init__
2019-08-10 01:16:08.693556 | ubuntu-xenial | AssertionError: socket_path must be a value
2019-08-10 01:16:08.700993 | ubuntu-xenial | fatal: [vyos-1.1.8]: FAILED! => changed=false
2019-08-10 01:16:08.701085 | ubuntu-xenial |   module_stderr: |-
2019-08-10 01:16:08.701133 | ubuntu-xenial |     Traceback (most recent call last):
2019-08-10 01:16:08.701229 | ubuntu-xenial |       File "/home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py", line 139, in <module>
2019-08-10 01:16:08.701302 | ubuntu-xenial |         _ansiballz_main()
2019-08-10 01:16:08.701410 | ubuntu-xenial |       File "/home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py", line 131, in _ansiballz_main
2019-08-10 01:16:08.701467 | ubuntu-xenial |         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
2019-08-10 01:16:08.701562 | ubuntu-xenial |       File "/home/zuul/.ansible/tmp/ansible-tmp-1565399768.351818-246593410746654/AnsiballZ_vyos_command.py", line 65, in invoke_module
2019-08-10 01:16:08.701603 | ubuntu-xenial |         spec.loader.exec_module(module)
2019-08-10 01:16:08.701691 | ubuntu-xenial |       File "<frozen importlib._bootstrap_external>", line 665, in exec_module
2019-08-10 01:16:08.701771 | ubuntu-xenial |       File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2019-08-10 01:16:08.701878 | ubuntu-xenial |       File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/__main__.py", line 229, in <module>
2019-08-10 01:16:08.701958 | ubuntu-xenial |       File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/__main__.py", line 202, in main
2019-08-10 01:16:08.702096 | ubuntu-xenial |       File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 111, in run_commands
2019-08-10 01:16:08.702251 | ubuntu-xenial |       File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 70, in get_connection
2019-08-10 01:16:08.702396 | ubuntu-xenial |       File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 85, in get_capabilities
2019-08-10 01:16:08.702536 | ubuntu-xenial |       File "/tmp/ansible_vyos.vyos.vyos_command_payload_rfml1g01/ansible_vyos.vyos.vyos_command_payload.zip/ansible/module_utils/connection.py", line 122, in __init__
2019-08-10 01:16:08.702603 | ubuntu-xenial |     AssertionError: socket_path must be a value
2019-08-10 01:16:08.702637 | ubuntu-xenial |   module_stdout: ''
2019-08-10 01:16:08.702691 | ubuntu-xenial |   msg: |-
2019-08-10 01:16:08.702737 | ubuntu-xenial |     MODULE FAILURE
2019-08-10 01:16:08.702780 | ubuntu-xenial |     See stdout/stderr for the exact error
2019-08-10 01:16:08.702804 | ubuntu-xenial |   rc: 1
```

**Comment by cidrblock** [comment]
Note: This is an issue when the user uses the full name of the module, ie cisco.ios.ios_vlan
