### ISSUE TITLE
sumologic callback not referencing SUMOLOGIC_URL on OSX

### ISSUE THREAD

**Issue by gabrielhesposito** [ansible/ansible#60543]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.10
  config file = /Users/gabrielesposito/repos/devops-ami/ecs/packer/ansible.cfg
  configured module search path = ['/Users/gabrielesposito/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
$ uname -v
Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
```

##### STEPS TO REPRODUCE

```yaml
$ cat ansible.cfg
[defaults]
inventory = inventory
callback_whitelist = sumologic

$ ansible-playbook  -vvv   plays/publishAMI.yml
ansible-playbook 2.7.10
  config file = /Users/gabrielesposito/repos/devops-ami/ecs/packer/ansible.cfg
  configured module search path = ['/Users/gabrielesposito/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
Using /Users/gabrielesposito/repos/devops-ami/ecs/packer/ansible.cfg as config file
/Users/gabrielesposito/repos/devops-ami/ecs/packer/inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/Users/gabrielesposito/repos/devops-ami/ecs/packer/inventory did not meet script requirements, check plugin documentation if this is unexpected
Parsed /Users/gabrielesposito/repos/devops-ami/ecs/packer/inventory inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: [Errno 8] nodename nor servname provided, or not known
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 209, in load_callbacks
    callback_obj = callback_plugin()
  File "/usr/local/lib/python3.7/site-packages/ansible/plugins/callback/sumologic.py", line 131, in __init__
    self.sumologic = SumologicHTTPCollectorSource()
  File "/usr/local/lib/python3.7/site-packages/ansible/plugins/callback/sumologic.py", line 76, in __init__
    self.ip_address = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

$printenv | grep "SUMOLOGIC"
SUMOLOGIC_URL=https://endpoint3.collection.us2.sumologic.com/<redacted>
```

##### EXPECTED RESULTS

playbook should work per 
https://docs.ansible.com/ansible/latest/plugins/callback/sumologic.html
when `env:SUMOLOGIC_URL`
is defined

##### ACTUAL RESULTS

the playbook works when the `ansible.cfg` looks like;
```
$ cat ansible.cfg
[defaults]
inventory = inventory
callback_whitelist = sumologic

[callback_sumologic]
url = <redacted>
```
 
if I had to guess something is wrong the ansible setup on OSX, rather than the module/callback having a bug.

**Comment by gabrielhesposito** [comment]
@ryancurrah  any thoughts why I can't get the `SUMOLOGIC_URL` env variable to work ?

**Comment by Akasurde** [comment]
@gabrielhesposito Thanks for reporting this issue. Could you please check Ansible controller is resolvable ? 

```
$ python -c "import socket;print(socket.gethostbyname(socket.gethostname()))"
```

Hint: Adding a hostname entry with resolvable IP in /etc/hosts might solve the issue.

needs_info

**Comment by Akasurde** [comment]
!component =lib/ansible/plugins/callback/sumologic.py

**Comment by gabrielhesposito** [comment]
@Akasurde thanks that looks like it might be the issue
```
$ python -c "import socket;print(socket.gethostbyname(socket.gethostname()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by gabrielhesposito** [comment]
@Akasurde it works now after host modification
```
$ python -c "import socket;print(socket.gethostbyname(socket.gethostname()))"
127.0.0.1
```
additionally the sumologic callback works with the `env` var where as before it required a hardcoded config entry. 
entry in `/etc/hosts`
```
127.0.0.1 $HOSTNAME
```
