### ISSUE TITLE
New XenAPI on pypi seems to break xenserver_guest module in ansible

### ISSUE THREAD

**Issue by jthompson333** [ansible/ansible#60977]
##### SUMMARY
New XenAPI on pypi seems to break xenserver_guest module in ansible

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xenserver_guest
https://docs.ansible.com/ansible/latest/modules/xenserver_guest_module.html

##### ANSIBLE VERSION
ansible 2.8.3
  config file = /home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg
  configured module search path = ['/home/johntho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/ansible
  executable location = /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/bin/ansible
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

##### CONFIGURATION
CACHE_PLUGIN(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = 127.0.0.1:6379
CACHE_PLUGIN_TIMEOUT(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = ['yaml']
DEFAULT_FORKS(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = 20
DEFAULT_GATHERING(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = smart
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = yaml
INVENTORY_ENABLED(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = ['host_list', 'script', 'yaml', 'ini', 'auto', 'nmap', 'azure_rm']

##### OS / ENVIRONMENT
xenserver 8
centos 7 running ansible 2.8

##### STEPS TO REPRODUCE
Just run a simple playbook and try to create a couple of machines.

##### EXPECTED RESULTS
You should get created machines.

##### ACTUAL RESULTS
```
ansible-playbook 2.8.3
  config file = /home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg
  configured module search path = ['/home/johntho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/ansible
  executable location = /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/bin/ansible-playbook
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg as config file
host_list declined parsing /home/johntho/ansible-stable/cqe/ansible_goodies/inventories/inventory-cloudXL.yml as it did not pass it's verify_file() method
script declined parsing /home/johntho/ansible-stable/cqe/ansible_goodies/inventories/inventory-cloudXL.yml as it did not pass it's verify_file() method
Parsed /home/johntho/ansible-stable/cqe/ansible_goodies/inventories/inventory-cloudXL.yml inventory source with yaml plugin

PLAYBOOK: XenserverVMs.yml *************************************************************************************************************************************************
1 plays in XenserverVMs.yml

PLAY [camr2] ***************************************************************************************************************************************************************
META: ran handlers

TASK [Provision Xen VMs] ***************************************************************************************************************************************************
task path: /home/johntho/ansible-stable/cqe/ansible_goodies/XenserverVMs.yml:11
statically imported: /home/johntho/ansible-stable/cqe/ansible_goodies/roles/ProvisionXenVMs/tasks/ProvisionXenserverVMs.yml
statically imported: /home/johntho/ansible-stable/cqe/ansible_goodies/roles/ProvisionXenVMs/tasks/DetermineXenVMPowerstate.yml
statically imported: /home/johntho/ansible-stable/cqe/ansible_goodies/roles/ProvisionXenVMs/tasks/GatherXenVMFacts.yml
statically imported: /home/johntho/ansible-stable/cqe/ansible_goodies/roles/ProvisionXenVMs/tasks/BuildIPInventory.yml

TASK [ProvisionXenVMs : Provision VMs from a template] *********************************************************************************************************************
task path: /home/johntho/ansible-stable/cqe/ansible_goodies/roles/ProvisionXenVMs/tasks/ProvisionXenserverVMs.yml:8
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: johntho
<localhost> EXEC /bin/sh -c 'echo ~johntho && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087 `" && echo ansible-tmp-1566329081.166826-26477351890087="` echo /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087 `" ) && sleep 0'
Using module file /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/ansible/modules/cloud/xenserver/xenserver_guest.py
<localhost> PUT /home/johntho/.ansible/tmp/ansible-local-103688txikuozs/tmpt4t7zidx TO /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/ /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/bin/python3 /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py", line 114, in <module>
    _ansiballz_main()
  File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_xenserver_guest_payload_162e_ghk/__main__.py", line 435, in <module>
  File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/XenAPI.py", line 64
    except Exception, exn:
                    ^
SyntaxError: invalid syntax
failed: [10.70.156.143 -> localhost] (item={'key': 'Connector0', 'value': {'hostname': 'bfxConn0', 'machine_group': 'Connectors', 'memory_mb': 6144, 'num_cpu_cores_per_socket': 2, 'num_cpus': 4, 'template': 'Win2016Template_Ansible'}}) => changed=false
  ansible_loop_var: item
  item:
    key: Connector0
    value:
      hostname: bfxConn0
      machine_group: Connectors
      memory_mb: 6144
      num_cpu_cores_per_socket: 2
      num_cpus: 4
      template: Win2016Template_Ansible
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py", line 114, in <module>
        _ansiballz_main()
      File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.166826-26477351890087/AnsiballZ_xenserver_guest.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 170, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 618, in _exec
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_xenserver_guest_payload_162e_ghk/__main__.py", line 435, in <module>
      File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/XenAPI.py", line 64
        except Exception, exn:
                        ^
    SyntaxError: invalid syntax
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
<localhost> EXEC /bin/sh -c 'echo ~johntho && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451 `" && echo ansible-tmp-1566329081.8043423-46113777858451="` echo /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451 `" ) && sleep 0'
Using module file /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/ansible/modules/cloud/xenserver/xenserver_guest.py
<localhost> PUT /home/johntho/.ansible/tmp/ansible-local-103688txikuozs/tmp87fb6899 TO /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/ /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/bin/python3 /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py", line 114, in <module>
    _ansiballz_main()
  File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_xenserver_guest_payload_jc0b1evn/__main__.py", line 435, in <module>
  File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/XenAPI.py", line 64
    except Exception, exn:
                    ^
SyntaxError: invalid syntax
failed: [10.70.156.143 -> localhost] (item={'key': 'Connector1', 'value': {'hostname': 'bfxConn1', 'machine_group': 'Connectors', 'memory_mb': 6144, 'num_cpu_cores_per_socket': 2, 'num_cpus': 4, 'template': 'Win2016Template_Ansible'}}) => changed=false
  ansible_loop_var: item
  item:
    key: Connector1
    value:
      hostname: bfxConn1
      machine_group: Connectors
      memory_mb: 6144
      num_cpu_cores_per_socket: 2
      num_cpus: 4
      template: Win2016Template_Ansible
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py", line 114, in <module>
        _ansiballz_main()
      File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/johntho/.ansible/tmp/ansible-tmp-1566329081.8043423-46113777858451/AnsiballZ_xenserver_guest.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib64/python3.6/imp.py", line 170, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 618, in _exec
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_xenserver_guest_payload_jc0b1evn/__main__.py", line 435, in <module>
      File "/home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/XenAPI.py", line 64
        except Exception, exn:
                        ^
    SyntaxError: invalid syntax
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *****************************************************************************************************************************************************************
10.70.156.143              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by jthompson333** [comment]
FYI. @bvitnik or maintainers.  When you have time.
I will role back to my master branch xen api that I had backed up.

**Comment by jthompson333** [comment]
One other thought... I used pipenv to install the XenAPI.  How can I tell if its the newest version?

**Comment by jthompson333** [comment]
Bah.  Nevermind.  I had the wrong version.  The old version was in my Pipfile from before.  Canceling.
