### ISSUE TITLE
ansible-playbook python errors with latest dev

### ISSUE THREAD

**Issue by chrisblossom** [ansible/ansible#6115]
##### Actual Results:

```
ansible-playbook -vvvv -i stage.yml site.yml
Traceback (most recent call last):
  File "/Users/chris/.bin/ansible/bin/ansible-playbook", line 287, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/chris/.bin/ansible/bin/ansible-playbook", line 227, in main
    pb.run()
  File "/Users/chris/.bin/ansible/lib/ansible/playbook/__init__.py", line 247, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Users/chris/.bin/ansible/lib/ansible/playbook/play.py", line 142, in __init__
    self._handlers   = self._load_tasks(self._ds.get('handlers', []), load_vars)
  File "/Users/chris/.bin/ansible/lib/ansible/playbook/play.py", line 546, in _load_tasks
    data = utils.parse_yaml_from_file(include_filename, vault_password=self.vault_password)
  File "/Users/chris/.bin/ansible/lib/ansible/utils/__init__.py", line 505, in parse_yaml_from_file
    if vault.is_encrypted(path):
  File "/Users/chris/.bin/ansible/lib/ansible/utils/vault.py", line 54, in is_encrypted
    head = f.next()
StopIteration
```

This error starts with commit 3fc87e011b44db815204d11337526de580f2aa83. Does not happen with any prior.

**Comment by mpdehaan** [comment]
@jctanner - I'm guessing the encrypted content (or file) here is very tiny (maybe blank) and we need to upgrade vault content to just read a minimum number of bytes, i.e. file.read(HEADER_LENGTH) and have some try except logic.

Can you take care of this?

**Comment by mpdehaan** [comment]
@jctanner - I should be able to take a look at this tonight, disregard

**Comment by chrisblossom** [comment]
To cause the issue:
Inside a role I had a handlers directory with main.yml inside with just "---" as the contents. Deleting this directory and file fixed the issue.

**Comment by mpdehaan** [comment]
I couldn't reproduce this with a "---" file, but I could with an empty file.   Now the system catches StopIteration and assumes a non-encrypted file, which is valid, because a file without a newline can't have an encryption header and a data element.

Thanks for the report, should be good to go now in 9686695170bd1cec9866e39cdedc8c54f23e1d6b
