### ISSUE TITLE
cron module cannot open crontab file

### ISSUE THREAD

**Issue by ReinerNippes** [ansible/ansible#61330]
##### SUMMARY
cron module doesn't work with python 3.7.4 (on Fedora 30)

```
  module_stderr: |-
    /home/ec2-user/.ansible/tmp/ansible-tmp-1566838857.75-209703594971152/AnsiballZ_cron.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
``` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /home/ec2-user/nextcloud-git/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]
```
The playbbok runs with -e ansible_python_interpreter=/usr/bin/python3 
```
/usr/bin/python3 --version
Python 3.7.4
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/ec2-user/nextcloud-git/ansible.cfg) = [u'profile_tasks']
DEFAULT_HOST_LIST(/home/ec2-user/nextcloud-git/ansible.cfg) = [u'/home/ec2-user/nextcloud-git/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/ec2-user/nextcloud-git/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/ec2-user/nextcloud-git/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/ec2-user/nextcloud-git/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ec2-user/nextcloud-git/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Fedora 30

##### STEPS TO REPRODUCE
```
curl -s https://raw.githubusercontent.com/ReinerNippes/nextcloud/master/prepare_system.sh | /bin/bash
cd nextcloud
sudo systemctl unmask tmp.mount
./nextcloud.yml -e 'ansible_python_interpreter=/usr/bin/python3'
```
Task that fails:

https://github.com/ReinerNippes/nextcloud/blob/ad8daf53188c0399fbf8d53cd42a6f13390cb86f/roles/prep_nextcloud/tasks/main.yml#L174

##### EXPECTED RESULTS
cronjob added to OS

##### ACTUAL RESULTS

```paste below
TASK [prep_nextcloud : nextcloud cronjob] ***************************************************************************************************************
Monday 26 August 2019  17:00:57 +0000 (0:00:02.283)       0:03:53.552 *********
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    /home/ec2-user/.ansible/tmp/ansible-tmp-1566838857.75-209703594971152/AnsiballZ_cron.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    Traceback (most recent call last):
      File "/home/ec2-user/.ansible/tmp/ansible-tmp-1566838857.75-209703594971152/AnsiballZ_cron.py", line 114, in <module>
        _ansiballz_main()
      File "/home/ec2-user/.ansible/tmp/ansible-tmp-1566838857.75-209703594971152/AnsiballZ_cron.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ec2-user/.ansible/tmp/ansible-tmp-1566838857.75-209703594971152/AnsiballZ_cron.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/usr/lib64/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib64/python3.7/imp.py", line 169, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_cron_payload_ae9n7kbv/__main__.py", line 770, in <module>
      File "/tmp/ansible_cron_payload_ae9n7kbv/__main__.py", line 624, in main
      File "/tmp/ansible_cron_payload_ae9n7kbv/__main__.py", line 250, in __init__
      File "/tmp/ansible_cron_payload_ae9n7kbv/__main__.py", line 272, in read
    __main__.CronTabError: Unable to read crontab
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```

**Comment by ReinerNippes** [comment]
well. thanks for your answer.

somehow the fedora image i'm using at aws has no cronie installed. and therefore there is no crontab of any user. :-(

so no ansible problem here.
