### ISSUE TITLE
Can't get info from router with routeros_facts 

### ISSUE THREAD

**Issue by ekzkgz** [ansible/ansible#61374]
##### SUMMARY
Cann't get info from router with routeros_facts 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
routeros_facts 

##### ANSIBLE VERSION

```paste below
  ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml

---
- name: Backup Conf
  hosts: tst-routers
  gather_facts: no
  tasks:
    - name: Get Facts
      routeros_facts:
        gather_subset: all
    - name: Get Identity
      routeros_command:
        commands:
          - /system identity print
      register: system_print
    - name: debug print
      debug:
        var: system_print.stdout
```

##### EXPECTED RESULTS

Information about router

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Not replacing invalid character(s) "{'-'}" in group name (office-routers)
Not replacing invalid character(s) "{'-'}" in group name (office-routers)
Not replacing invalid character(s) "{'-'}" in group name (tst-routers)
Not replacing invalid character(s) "{'-'}" in group name (tst-routers)
Not replacing invalid character(s) "{'-'}" in group name (tst-routers)
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.5/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: bkp-conf.yml ************************************************************************************
Positional arguments: bkp-conf.yml
forks: 5
tags: ('all',)
verbosity: 4
timeout: 10
become_method: sudo
inventory: ('/etc/ansible/hosts',)
connection: smart
1 plays in bkp-conf.yml

PLAY [Backup Conf] ****************************************************************************************
META: ran handlers

TASK [Get Facts] ******************************************************************************************
task path: /root/scripts/ansible/mikrotik/bkp-conf.yml:7
<10.100.101.2> attempting to start connection
<10.100.101.2> using connection plugin network_cli
<10.100.101.2> local domain socket does not exist, starting it
<10.100.101.2> control socket path is /root/.ansible/pc/53f274ad03
<10.100.101.2> <10.100.101.2> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: admin on PORT 22 TO 10.100.101.2
<10.100.101.2> connection to remote device started successfully
<10.100.101.2> local domain socket listeners started successfully
<10.100.101.2> loaded cliconf plugin for network_os routeros
<10.100.101.2> ssh connection done, setting terminal
<10.100.101.2> loaded terminal plugin for network_os routeros
<10.100.101.2> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<10.100.101.2> firing event: on_open_shell()
<10.100.101.2> firing event: on_become
<10.100.101.2> ssh connection has completed successfully
<10.100.101.2> 
<10.100.101.2> local domain socket path is /root/.ansible/pc/53f274ad03
<10.100.101.2> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.100.101.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216 `" && echo ansible-tmp-1566914422.6618824-209583593969216="` echo /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216 `" ) && sleep 0'
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/network/routeros/routeros_facts.py
<10.100.101.2> PUT /root/.ansible/tmp/ansible-local-653609c8_9ue/tmpttbexxm2 TO /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py
<10.100.101.2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/ /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py && sleep 0'
<10.100.101.2> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py && sleep 0'
<10.100.101.2> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py", line 434, in <module>
  File "/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py", line 422, in main
  File "/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py", line 266, in populate
  File "/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py", line 283, in populate_ipv4_interfaces
KeyError: 'homeline'
fatal: [10.100.101.2]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-653609c8_9ue/ansible-tmp-1566914422.6618824-209583593969216/AnsiballZ_routeros_facts.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.5/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.5/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 626, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 673, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py\", line 434, in <module>\n  File \"/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py\", line 422, in main\n  File \"/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py\", line 266, in populate\n  File \"/tmp/ansible_routeros_facts_payload_yp00drnn/__main__.py\", line 283, in populate_ipv4_interfaces\nKeyError: 'homeline'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ************************************************************************************************
10.100.101.2               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by heuels** [comment]
@ekzkgz, thanks for taking the time to report this! I've put together a pull request, can you please verify that the issue no longer occurs with those changes applied?
