### ISSUE TITLE
AttributeError: 'ShellModule' object has no attribute 'ECHO'

### ISSUE THREAD

**Issue by Cherishty** [ansible/ansible#61478]
##### SUMMARY

same issue as [this](https://github.com/ansible/ansible/issues/59173) when gathering info in controlling windows machine
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /root/kubernetes-engine/output/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/root/kubernetes-engine/output/ansible/ansible.cfg) = debug
HOST_KEY_CHECKING(/root/kubernetes-engine/output/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

ansible 2.8.4
  config file = /root/kubernetes-engine/output/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /root/kubernetes-engine/output/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /root/kubernetes-engine/output/ansible/hosts-win as it did not pass it's verify_file() method
script declined parsing /root/kubernetes-engine/output/ansible/hosts-win as it did not pass it's verify_file() method
auto declined parsing /root/kubernetes-engine/output/ansible/hosts-win as it did not pass it's verify_file() method
Parsed /root/kubernetes-engine/output/ansible/hosts-win inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
<stcvl-060> ESTABLISH SSH CONNECTION FOR USER: None
<stcvl-060> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/68b534393d stcvl-060 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_ping.ps1
Pipelining is enabled.
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 917, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 1044, in _low_level_execute_command
    cmd = self._connection.become.build_become_command(cmd, self._connection._shell)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/become/sudo.py", line 104, in build_become_command
    return ' '.join([becomecmd, flags, prompt, user, self._build_success_command(cmd, shell)])
  File "/usr/lib/python2.7/site-packages/ansible/plugins/become/__init__.py", line 52, in _build_success_command
    cmd = shlex_quote('%s %s %s %s' % (shell.ECHO, self.success, shell.COMMAND_SEP, cmd))
AttributeError: 'ShellModule' object has no attribute 'ECHO'

stcvm-L92 | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Cherishty** [comment]
@jborean93 what's your solution provided in [here](https://github.com/ansible/ansible/issues/59173), may you give some details?

**Comment by Cherishty** [comment]
Hi @sivel , following your advice, I update add the `become_method: runas` in **group/all**, as well as b`ecome_method = runas ` in **ansible.cfg** but still not work, do you have any hint?

Thanks a lot!
