### ISSUE TITLE
Module "assemble" does not expand pathes correctly

### ISSUE THREAD

**Issue by muffl0n** [ansible/ansible#6209]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel c11e2100e0) last updated 2014/02/27 12:27:01 (GMT -400)
##### Environment:

Ubuntu 12.04.4 LTS
##### Summary:

local: user "test" with homedir: /tmp/test
remote: user "test" with homedir: /tmp/testuser

test-assemble.yml:

```
- hosts: remote
  tasks:
    - assemble: src=/tmp/test/assemble dest=~test/assemble.conf remote_src=false
    - assemble: src=~test/assemble dest=~test/assemble.conf remote_src=false
```

output:

```
$ ansible-playbook -i test test-assemble.yml -vv

PLAY [remote] *****************************************************************

GATHERING FACTS ***************************************************************
<remote> REMOTE_MODULE setup
ok: [remote]

TASK: [assemble src=/tmp/test/assemble dest=~test/assemble.conf remote_src=false] ***
ok: [remote] => {"changed": false, "dest": "/tmp/testuser/assemble.conf", "gid": 0, "group": "root", "md5sum": "6ddb4095eb719e2a9f0a3f95677d24e0", "mode": "0600", "owner": "root", "size": 4, "src": "/root/.ansible/tmp/ansible-tmp-1393525796.51-273998890826736/src", "state": "file", "uid": 0}

TASK: [assemble src=~test/assemble dest=~test/assemble.conf remote_src=false] ***
fatal: [remote] => Traceback (most recent call last):
  File "/root/ansible/lib/ansible/runner/__init__.py", line 527, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/root/ansible/lib/ansible/runner/__init__.py", line 618, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/root/ansible/lib/ansible/runner/__init__.py", line 804, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/root/ansible/lib/ansible/runner/action_plugins/assemble.py", line 72, in run
    path = self._assemble_from_fragments(src, delimiter)
  File "/root/ansible/lib/ansible/runner/action_plugins/assemble.py", line 39, in _assemble_from_fragments
    for f in sorted(os.listdir(src_path)):
OSError: [Errno 2] No such file or directory: '~test/assemble'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/test-assemble.retry

remote                     : ok=2    changed=0    unreachable=1    failed=0

```

assemble doesn't expand the source homedir at all, for dest it seems correct.

**Comment by muffl0n** [comment]
Followup for #6061

**Comment by jimi-c** [comment]
Can you give this patch a try?

<pre>
diff --git a/lib/ansible/runner/action_plugins/assemble.py b/lib/ansible/runner/action_plugins/assemble.py
index cc4c4bd..eb6faf5 100644
--- a/lib/ansible/runner/action_plugins/assemble.py
+++ b/lib/ansible/runner/action_plugins/assemble.py
@@ -67,6 +67,9 @@ class ActionModule(object):
             return self.runner._execute_module(conn, tmp, 'assemble', module_args, inject=inject, complex_args=complex_args)
         elif '_original_file' in inject:
             src = utils.path_dwim_relative(inject['_original_file'], 'files', src, self.runner.basedir)
+        else:
+            # the source is local, so expand it here
+            src = os.path.expanduser(src)
 
         # Does all work assembling the file
         path = self._assemble_from_fragments(src, delimiter)
</pre>

**Comment by muffl0n** [comment]
Looks great! :+1: 

```
TASK: [assemble src=~test/assemble dest=~test/assemble.conf remote_src=false] ***
ok: [remote] => {"changed": false, "dest": "/tmp/testuser/assemble.conf", "gid": 0, "group": "root", "md5sum": "6ddb4095eb719e2a9f0a3f95677d24e0", "mode": "0600", "owner": "root", "size": 4, "src": "/root/.ansible/tmp/ansible-tmp-1393528028.43-255864014814911/src", "state": "file", "uid": 0}
```

**Comment by jimi-c** [comment]
Great, merged! Thanks!
