### ISSUE TITLE
k8s - AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by alexeyt820** [ansible/ansible#62236]
##### SUMMARY
Deploying NGINX Ingress Controller for Kubernetes (https://github.com/kubernetes/ingress-nginx/blob/master/deploy/static/mandatory.yaml) using k8s results in AttributeError

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = None
  configured module search path = [u'/Users/alexeyt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alexeyt/projects/environments/venv-ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/alexeyt/projects/environments/venv-ansible/bin/ansible
  python version = 2.7.16 (default, Apr  1 2019, 14:50:41) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/Users/alexeyt/projects/environments/hosts']
```

##### OS / ENVIRONMENT
- control station 
```
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

- target
```
Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml
    - name: deploy nginx-ingress (Mandatory)
      k8s:
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml' ) | from_yaml_all | type_debug | list }}"
```

##### EXPECTED RESULTS
The file to be applied successfully. Running 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
```
works fine.

##### ACTUAL RESULTS

```paste below
TASK [deploy nginx-ingress (Mandatory)] ******************************************************************************************
task path: /Users/alexeyt/projects/environments/k8s.yml:150
url lookup connecting to https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
<target.int.com> ESTABLISH SSH CONNECTION FOR USER: root
<target.int.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/alexeyt/.ansible/cp/3c50f078cf target.int.com '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<target.int.com> (0, '/root\n', 'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<target.int.com> ESTABLISH SSH CONNECTION FOR USER: root
<target.int.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/alexeyt/.ansible/cp/3c50f078cf target.int.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185 `" && echo ansible-tmp-1568338403.52-211609101627185="` echo /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185 `" ) && sleep 0'"'"''
<target.int.com> (0, 'ansible-tmp-1568338403.52-211609101627185=/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185\n', 'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
Using module file /Users/alexeyt/projects/environments/venv-ansible/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<target.int.com> PUT /Users/alexeyt/.ansible/tmp/ansible-local-39476jQSZSH/tmpBuLw_0 TO /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py
<target.int.com> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/alexeyt/.ansible/cp/3c50f078cf '[target.int.com]'
<target.int.com> (0, 'sftp> put /Users/alexeyt/.ansible/tmp/ansible-local-39476jQSZSH/tmpBuLw_0 /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py\n', 'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 8 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /root size 0\r\ndebug3: Looking up /Users/alexeyt/.ansible/tmp/ansible-local-39476jQSZSH/tmpBuLw_0\r\ndebug3: Sent message fd 8 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:15918\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 15918 bytes at 65536\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<target.int.com> ESTABLISH SSH CONNECTION FOR USER: root
<target.int.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/alexeyt/.ansible/cp/3c50f078cf target.int.com '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/ /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py && sleep 0'"'"''
<target.int.com> (0, '', 'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<target.int.com> ESTABLISH SSH CONNECTION FOR USER: root
<target.int.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/alexeyt/.ansible/cp/3c50f078cf -tt target.int.com '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py && sleep 0'"'"''
<target.int.com> (1, '/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.2.1) doesn\'t match a supported version!\r\n  RequestsDependencyWarning)\r\nTraceback (most recent call last):\r\n  File "/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py", line 113, in <module>\r\n    _ansiballz_main()\r\n  File "/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py", line 48, in invoke_module\r\n    imp.load_module(\'__main__\', mod, module, MOD_DESC)\r\n  File "/tmp/ansible_k8s_payload_LHsRYN/__main__.py", line 171, in <module>\r\n  File "/tmp/ansible_k8s_payload_LHsRYN/__main__.py", line 167, in main\r\n  File "/tmp/ansible_k8s_payload_LHsRYN/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py", line 91, in execute_module\r\nAttributeError: \'str\' object has no attribute \'get\'\r\n', 'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to target.int.com closed.\r\n')
<target.int.com> Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/alexeyt/.ssh/config
debug1: /Users/alexeyt/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 39486
debug3: mux_client_request_session: session request sent
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
Shared connection to target.int.com closed.
<target.int.com> ESTABLISH SSH CONNECTION FOR USER: root
<target.int.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/alexeyt/.ansible/cp/3c50f078cf target.int.com '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/ > /dev/null 2>&1 && sleep 0'"'"''
<target.int.com> (0, '', 'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
fatal: [gimci-vm18]: FAILED! => {
    "changed": false, 
    "module_stderr": "OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/alexeyt/.ssh/config\r\ndebug1: /Users/alexeyt/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39486\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to target.int.com closed.\r\n", 
    "module_stdout": "/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.2.1) doesn't match a supported version!\r\n  RequestsDependencyWarning)\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1568338403.52-211609101627185/AnsiballZ_k8s.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_k8s_payload_LHsRYN/__main__.py\", line 171, in <module>\r\n  File \"/tmp/ansible_k8s_payload_LHsRYN/__main__.py\", line 167, in main\r\n  File \"/tmp/ansible_k8s_payload_LHsRYN/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 91, in execute_module\r\nAttributeError: 'str' object has no attribute 'get'\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by alexeyt820** [comment]
@willthames, thank you. Is separate issue for handling empty trailing blocks?

**Comment by willthames** [comment]
@alexeyt820  Please raise a separate issue for handling empty trailing blocks
