### ISSUE TITLE
/library/system/setup: path problem ('NoneType' has no attribute 'split')

### ISSUE THREAD

**Issue by voidzero** [ansible/ansible#6236]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

Funtoo
##### Summary:

Distribution not recognised by /library/system/setup, assumes Debian
##### Steps To Reproduce:

Install ansible on a funtoo system and run `ansible hostname -m setup`
##### Expected Results:

yada yada this is annoying, sorry hehe
##### Actual Results:

I'm getting the following error when running `ansible hostname -m setup` on a Funtoo installation. Funtoo is a Gentoo fork.

<pre>
hostname | FAILED => failed to parse: Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 3409, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 2338, in main
    data = run_setup(module)
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 2279, in run_setup
    facts = ansible_facts()
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 2268, in ansible_facts
    facts.update(Facts().populate())
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 143, in __init__
    self.get_platform_facts()
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 185, in get_platform_facts
    self.get_distribution_facts()
  File "/home/user/.ansible/tmp/ansible-tmp-1393719714.41-32866695741365/setup", line 333, in get_distribution_facts
    data = get_file_content(path).split('\n')[0]
AttributeError: 'NoneType' object has no attribute 'split'
</pre>

I suspect that this is due to line 290 and further in library/system/setup. I am not sure though, because the strange thing is that `get_file_content(path).split('\n')[0]` should only be called when `name` is either Solaris or Debian. On my system, well I'm not sure if it's Gentoo or Funtoo but it shouldn't be anything else.

_Edit_ It seems that Ansible considers this to be a Debian installation; there is an empty /etc/os-release file.

Perhaps the easy way is to check for the existence _and contents_ of `/etc/gentoo-release` first. With Funtoo, this file contains `Funtoo Linux - baselayout 2.2.0`.

**Comment by voidzero** [comment]
I hope my edit made @ansibot happy.

**Comment by voidzero** [comment]
With regards to my edit of the original ticket - I got it to work by cheating - I disabled the check for /etc/os-release and added a check for /etc/gentoo-release. If we could make Funtoo and Gentoo distinct that would be even nicer.

**Comment by bcoca** [comment]
Checked on gentoo, no issues there as it does populate os-release.

**Comment by jctanner** [comment]
Should be fixed by #6237
