### ISSUE TITLE
firewalld integration test fails on RHEL 8.1b

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#63254]
##### SUMMARY

The firewalld integration test fails on RHEL 8.1b and has been disabled on that platform.

##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

firewalld

##### ANSIBLE VERSION

devel

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

RHEL 8.1b

##### STEPS TO REPRODUCE

Remove the `skip/rhel8.1b` from the aliases file for the firewalld integration test.

`ansible-test integration firewalld --remote rhel/8.1b -vvv`

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests fail:

```
TASK [firewalld : firewalld service test permanent enabled] ****************************************************************************************************************************************************************************************************************
task path: /root/ansible/test/results/.tmp/integration/firewalld-zk3r9o31-ÅÑŚÌβŁÈ/test/integration/targets/firewalld/tasks/service_test_cases.yml:19
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<testhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852 `" && echo ansible-tmp-1570565885.9766176-16765328511852="` echo /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852 `" ) && sleep 0'
Using module file /root/ansible/lib/ansible/modules/system/firewalld.py
<testhost> PUT /root/.ansible/tmp/ansible-local-14404e73ziu9f/tmp8mb1nkjc TO /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py
<testhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/ /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py && sleep 0'
<testhost> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py", line 116, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py", line 108, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py", line 54, in invoke_module
    runpy.run_module(mod_name='ansible.modules.system.firewalld', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/modules/system/firewalld.py", line 871, in <module>
  File "/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/modules/system/firewalld.py", line 761, in main
  File "/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/modules/system/firewalld.py", line 278, in __init__
  File "/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/module_utils/firewalld.py", line 73, in __init__
AttributeError: 'FirewallClient' object has no attribute 'get_default_zone'

fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py\", line 116, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py\", line 108, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1570565885.9766176-16765328511852/AnsiballZ_firewalld.py\", line 54, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.system.firewalld', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib64/python3.6/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/modules/system/firewalld.py\", line 871, in <module>\n  File \"/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/modules/system/firewalld.py\", line 761, in main\n  File \"/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/modules/system/firewalld.py\", line 278, in __init__\n  File \"/tmp/ansible_firewalld_payload_yay_9865/ansible_firewalld_payload.zip/ansible/module_utils/firewalld.py\", line 73, in __init__\nAttributeError: 'FirewallClient' object has no attribute 'get_default_zone'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by mattclay** [comment]
The PRs to enable the RHEL 8.1b tests and disable the firewalld test are:

* https://github.com/ansible/ansible/pull/63141 - devel
* https://github.com/ansible/ansible/pull/63252 - stable-2.9
* https://github.com/ansible/ansible/pull/63253 - stable-2.8
