### ISSUE TITLE
vmware_host_firewall_manager: Fails with backtrace if allowed_hosts not define in rules

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#63515]
##### SUMMARY

`vmware_host_firewall_manager` cannot apply rule with no `allowed_hosts` key. It was working with 2.8.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host_firewall_manager

##### ANSIBLE VERSION

```paste below
devel and 2.9
```

##### STEPS TO REPRODUCE

Use the following task:

```yaml
    - name: Disable the Firewall vvold rule on the ESXi
      vmware_host_firewall_manager:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        cluster_name: '{{ ccr1 }}'
        validate_certs: no
        rules:
            - name: vvold
              enabled: False
```
The rule does not have any `allowed_hosts` key.

##### EXPECTED RESULTS

The rule should be accepted

##### ACTUAL RESULTS

```

TASK [vmware_host_firewall_manager : Disable the Firewall vvold rule on the ESXi] ***
task path: /home/goneri/git_repos/ansible_projects/b/test/results/.tmp/integration/vmware_host_firewall_manager-4i5k83h9-ÅÑŚÌβŁÈ/test/integration/targets/vmware_host_firewall_manager/tasks/main.yml:11
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: goneri
<testhost> EXEC /bin/sh -c 'echo ~goneri && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342 `" && echo ansible-tmp-1571152412.6546543-35475077352342="` echo /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342 `" ) && sleep 0'
Using module file /home/goneri/git_repos/ansible_projects/b/lib/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py
<testhost> PUT /home/goneri/.ansible/tmp/ansible-local-66854zvkqnvm/tmp_ne7wmcy TO /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py
<testhost> EXEC /bin/sh -c 'chmod u+x /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/ /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py && sleep 0'
<testhost> EXEC /bin/sh -c 'ESXI1_HOSTNAME=esxi1.test ESXI1_PASSWORD='"'"'!234AaAa56'"'"' ESXI1_USERNAME=root ESXI2_HOSTNAME=test2.test ESXI2_PASSWORD='"'"'!234AaAa56'"'"' ESXI2_USERNAME=root VCENTER_HOSTNAME=vcenter.test VCENTER_PASSWORD='"'"'!234AaAa56'"'"' VCENTER_USERNAME=administrator@vsphere.local VMWARE_VALIDATE_CERTS=false /home/goneri/git_repos/ansible_projects/b/.virtualenv/py37/bin/python3.7 /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py", line 116, in <module>
    _ansiballz_main()
  File "/home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py", line 108, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py", line 54, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vmware_host_firewall_manager', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/lib64/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vmware_host_firewall_manager_payload_jqfgbov8/ansible_vmware_host_firewall_manager_payload.zip/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py", line 367, in <module>
  File "/tmp/ansible_vmware_host_firewall_manager_payload_jqfgbov8/ansible_vmware_host_firewall_manager_payload.zip/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py", line 363, in main
  File "/tmp/ansible_vmware_host_firewall_manager_payload_jqfgbov8/ansible_vmware_host_firewall_manager_payload.zip/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py", line 238, in ensure
TypeError: 'NoneType' object is not subscriptable
fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py\", line 116, in <module>\n    _ansiballz_main()\n  File \"/home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py\", line 108, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/goneri/.ansible/tmp/ansible-tmp-1571152412.6546543-35475077352342/AnsiballZ_vmware_host_firewall_manager.py\", line 54, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vmware_host_firewall_manager', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib64/python3.7/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware_host_firewall_manager_payload_jqfgbov8/ansible_vmware_host_firewall_manager_payload.zip/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py\", line 367, in <module>\n  File \"/tmp/ansible_vmware_host_firewall_manager_payload_jqfgbov8/ansible_vmware_host_firewall_manager_payload.zip/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py\", line 363, in main\n  File \"/tmp/ansible_vmware_host_firewall_manager_payload_jqfgbov8/ansible_vmware_host_firewall_manager_payload.zip/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py\", line 238, in ensure\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

```paste below

```

The follow line is obviously wrong:
https://github.com/ansible/ansible/blob/6bea1597cc55345584ae773d40e4f5418081ff58/lib/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py#L236
The change was introduced by https://github.com/ansible/ansible/commit/045caaa40045a1d641d7fda56cc4202ce191d560 and so, is in 2.9.0 release.

**Comment by goneri** [comment]
Dup with https://github.com/ansible/ansible/issues/61332
