### ISSUE TITLE
traceback w/ lookup plugin

### ISSUE THREAD

**Issue by dominus-directus** [ansible/ansible#6354]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible --version
ansible 1.6
```
##### Environment:

Debian 7 (wheezy)
##### Summary:

{{item}} doesn't resolve when using file lookup plugin.
##### Steps To Reproduce:

```
- debug: msg="{{lookup('file', '/home/il/src/ansible/roles/auth/files/file')}}"

- debug: msg="{{lookup('file', item)}}"
  with_items:
  - /home/il/src/ansible/roles/auth/files/file
```
##### Expected Results:

Results of this two commands should be identical.
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [muse]

TASK: [auth | debug msg="content of the file"] ******************************** 
ok: [muse] => {
    "item": "", 
    "msg": "content of the file"
}
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 307, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 247, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 281, in run
    if not self._run_play(play):
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 654, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 399, in _run_task
    self.callbacks.on_task_start(template(play.basedir, name, task.module_vars, lookup_fatal=False, filter_fatal=False), is_handler)
  File "/usr/lib/pymodules/python2.7/ansible/utils/template.py", line 108, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/lib/pymodules/python2.7/ansible/utils/template.py", line 332, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 10, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 180, in call
    return __obj(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ansible/utils/template.py", line 324, in my_lookup
    return lookup(*args, basedir=basedir, **kwargs)
  File "/usr/lib/pymodules/python2.7/ansible/utils/template.py", line 91, in lookup
    ran = instance.run(*args, inject=vars, **kwargs)
  File "/usr/lib/pymodules/python2.7/ansible/runner/lookup_plugins/file.py", line 42, in run
    ret.append(codecs.open(path, encoding="utf8").read().rstrip())
  File "/usr/lib/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 21] Is a directory: '/home/il/src/ansible/roles/auth/files'
```

reproducible from v1.4 to git head, didn't tried on earlier versions though

**Comment by mpdehaan** [comment]
This is not exactly the right caption here, the lookup plugin can work with "items", but you do have a traceback above for some reason.

It does seem that item is in scope, however.   (edited subject to reflect)

Thanks!

**Comment by dominus-directus** [comment]
seems 2a976ac solved the issue
