### ISSUE TITLE
include_vars missing Nonetype check

### ISSUE THREAD

**Issue by jhg03a** [ansible/ansible#64939]
##### SUMMARY

The include_vars action plugin now fatally breaks when given a NoneType object.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/b04940d2567fa5c4779e3bb6073f7388e619bcd9/lib/ansible/plugins/action/include_vars.py#L53

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /opt/ansible/local/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
It appears to have began breaking in the 2.9.0 release having been working in the 2.8.5 release.

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_PLUGIN_PATH(/opt/ansible/local/ansible.cfg) = [u'/opt/ansible/local/scripts/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/opt/ansible/local/ansible.cfg) = [u'summary_log', u'profile_tasks', u'timer', u'json_file']
PERSISTENT_CONNECT_TIMEOUT(/opt/ansible/local/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

CentOS

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Broken rstrip
      include_vars:
        file: "{{ lookup('first_found', possible_files, errors='ignore') }}"
      failed_when: false
      tags:
        - run_always
      vars:
        possible_files:
          - "doesnt.exist.yml"
          - "doesnt.exist.json"
```

##### EXPECTED RESULTS

An error which is in this case, ignored.

##### ACTUAL RESULTS

It fails fatally.

```paste below
$ sudo ansible-playbook -i 'localhost' tmp.yml -vvvv
ansible-playbook 2.9.1
  config file = /opt/ansible/local/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /opt/ansible/local/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /opt/ansible/local/localhost as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /opt/ansible/local/localhost as it did not pass its verify_file() method
auto declined parsing /opt/ansible/local/localhost as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /opt/ansible/local/localhost as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /opt/ansible/local/localhost as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /opt/ansible/local/localhost as it did not pass its verify_file() method
[WARNING]: Unable to parse /opt/ansible/local/localhost as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
Loading callback plugin json_file of type notification, v2.0 from /opt/ansible/local/scripts/plugins/callback/json_file.pyc
Loading callback plugin profile_tasks of type aggregate, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/profile_tasks.pyc
Loading callback plugin summary_log of type notification, v2.0 from /opt/ansible/local/scripts/plugins/callback/summary_log.pyc
Loading callback plugin timer of type aggregate, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/timer.pyc

PLAYBOOK: tmp.yml ***********************************************************************************************************************************************************************
Positional arguments: tmp.yml
become_method: sudo
inventory: (u'/opt/ansible/local/localhost',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in tmp.yml

PLAY [localhost] ************************************************************************************************************************************************************************
META: ran handlers

TASK [Broken rstrip] ********************************************************************************************************************************************************************
task path: /opt/ansible/local/tmp.yml:7
Sunday 17 November 2019  00:30:22 +0000 (0:00:00.050)       0:00:00.050 *******
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/include_vars.py", line 95, in run
    self._set_args()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/include_vars.py", line 53, in _set_args
    self.source_file = self._task.args.get('_raw_params').rstrip('\n')
AttributeError: 'NoneType' object has no attribute 'rstrip'

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP ******************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by jhg03a** [comment]
This appears to have come from https://github.com/ansible/ansible/pull/57605.

**Comment by jhg03a** [comment]
And may also have interaction with https://github.com/ansible/ansible/issues/56775

**Comment by Akasurde** [comment]
resolved_by_pr #64979

**Comment by Akasurde** [comment]
@jhg03a, Could you please check PR #64979 and let us know if it works for you ? <br><br>Please check [How to test a PR](https://docs.ansible.com/ansible/latest/dev_guide/testing.html#how-to-test-a-pr) for more help. <br><br> Thanks. <br><br> needs_info

**Comment by jhg03a** [comment]
Works for me! Tested on `Ansible 2.10.0.dev0` at commit `95bd92da0`.  I verified this on OSX.

**Comment by Akasurde** [comment]
Backport 2.9 #65301
