### ISSUE TITLE
assemble module: Traceback on hash contained in delimiter=

### ISSUE THREAD

**Issue by risaacson** [ansible/ansible#6532]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel c09e46517e) last updated 2014/03/17 14:53:17 (GMT -500)
##### Environment:

OS X 10.9.2 against Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.
##### Summary:

While testing out a PR I came across this traceback when just trying to duplicate the examples from the assemble module. It looks like this is related to the escaping of '#' when in a KEY=VAL when running a module. May relate to GH-6287
##### Steps To Reproduce:

Execute a task as such:

``` YAML

---
- name: Copy the files out to the remote.
  copy: src=test_config.d dest=/tmp/

- name: Assemble the test.conf file from local files.
  assemble: src=/tmp/test_config.d dest=/tmp/local_test.config

- name: Assemble the test.conf file with a delimiter from local files.
  assemble: src=/tmp/test_config.d dest=/tmp/local_test-w-del.config delimiter='### Fragment Boundry  ###'

- name: Assemble the test.conf file from remote files.
  assemble: remote_src=False src=test_config.d dest=/tmp/remote_test.config

- name: Assemble the test.conf file with a delimiter from remote files.
  assemble: remote_src=False src=test_config.d dest=/tmp/remote_test-w-del.config delimiter='### Fragment Boundry  ###'
```
##### Expected Results:

Files are assembled with "### Fragment Boundry  ###" marking the original boundaries.
##### Actual Results:

```
TASK: [test_assemble | Assemble the test.conf file.] ************************** 
fatal: [test-debian7] => Traceback (most recent call last):
  File "/Users/ri/repos/github.com/risaacson/ansible/lib/ansible/runner/__init__.py", line 516, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/ri/repos/github.com/risaacson/ansible/lib/ansible/runner/__init__.py", line 606, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/ri/repos/github.com/risaacson/ansible/lib/ansible/runner/__init__.py", line 801, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Users/ri/repos/github.com/risaacson/ansible/lib/ansible/runner/action_plugins/assemble.py", line 61, in run
    options.update(utils.parse_kv(module_args))
  File "/Users/ri/repos/github.com/risaacson/ansible/lib/ansible/utils/__init__.py", line 542, in parse_kv
    vargs = [x.decode('utf-8') for x in shlex.split(args, posix=True)]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by mpdehaan** [comment]
Looks like this has nothing to do with assemble but just relates to general shlex bits, and then inventroy code doesn't really apply 1:1.

The solution would be to come up with a clean function that wraps shlex for utils, most likely, which could easily be done by replacing "#" with some other sequence, splitting, and putting it back.

Since I did this last time, I'll take this.
