### ISSUE TITLE
test_get_diff (TestUtils.TestUtils) failing in devel

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#6539]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.6 (devel 9da26da335) last updated 2014/03/17 19:50:36 (GMT -400)
```
##### Environment:

Centos 6.5
##### Summary:

```
======================================================================
FAIL: test_get_diff (TestUtils.TestUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/ansible/test/units/TestUtils.py", line 669, in test_get_diff
    self.assertEqual(ansible.utils.get_diff(standard), standard_expected)
AssertionError: u'--- before: foo \n+++ after: bar \n@@ -1,1 +1,1 @@\n-fooo+foo' != '--- before: foo\n+++ after: bar\n@@ -1 +1 @@\n-fooo+foo'
>>  raise self.failureException, \
          (None or '%r != %r' % (u'--- before: foo \n+++ after: bar \n@@ -1,1 +1,1 @@\n-fooo+foo', '--- before: foo\n+++ after: bar\n@@ -1 +1 @@\n-fooo+foo'))
```

**Comment by mpdehaan** [comment]
I also see this on OS X (instead or earlier checkout)

```
======================================================================
FAIL: test_run_command_string_unsafe_with_pipe (TestModuleUtilsBasic.TestModuleUtilsBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/michaeldehaan/Dev/ansible/test/units/TestModuleUtilsBasic.py", line 100, in test_run_command_string_unsafe_with_pipe
    self.assertEqual(out, 'foo bar')
 AssertionError: '-n foo bar\n' != 'foo bar'
    "'-n foo bar\\n' != 'foo bar'" = '%s != %s' % (safe_repr('-n foo bar\n'), safe_repr('foo bar'))
    "'-n foo bar\\n' != 'foo bar'" = self._formatMessage("'-n foo bar\\n' != 'foo bar'", "'-n foo bar\\n' != 'foo bar'")
>>  raise self.failureException("'-n foo bar\\n' != 'foo bar'")
```

**Comment by jctanner** [comment]
```
[root@el6 ansible]# git bisect bad
5062f4962f8e7939c4656a059fc86e0fb4a3bf55 is the first bad commit
commit 5062f4962f8e7939c4656a059fc86e0fb4a3bf55
Author: Matt Martz <matt@sivel.net>
Date:   Fri Mar 7 21:51:12 2014 -0600

    Unit tests for ansible.utils

:040000 040000 d764ca89a1568620bb58ed1095512c039266498f ebe9028523b161c294848a13cdb91058a05a32f8 M  test
```

**Comment by jctanner** [comment]
@sivel it looks like test_get_diff doesn't work on my el6 machine. I'll setup a fresh machine to retest, but if you have any insight it would be appreciated.

**Comment by sivel** [comment]
@jctanner It appears to be working for me in my CI environment.  I'm not in a place where I can investigate further right now, but should be in about 30 minutes.

The output appears a difference in a space following the word 'bar'.

Here is the test status (which may be a few commits behind):  https://drone.io/github.com/sivel/ansible/63

That is some version of Ubuntu and is running through python 2.7

**Comment by sivel** [comment]
The other failure that @mpdehaan mentions, seems to be coming from another set of tests for module_utils/basic.py and I think there is another ticket around that mentions that run_command is returning the flags and whatnot on Mac OS X.

**Comment by jctanner** [comment]
@sivel reproduced on a fresh el6.5 host. I'll start debugging.

**Comment by jctanner** [comment]
py26

```
            yield '--- %s %s%s' % (fromfile, fromfiledate, lineterm)
            yield '+++ %s %s%s' % (tofile, tofiledate, lineterm)
```

py27

```
            yield '--- {}{}{}'.format(fromfile, fromdate, lineterm)
            yield '+++ {}{}{}'.format(tofile, todate, lineterm)
```
