### ISSUE TITLE
nohup isn't usable with ansible/ansible-playbook commands

### ISSUE THREAD

**Issue by leevs** [ansible/ansible#6657]
##### Issue Type:

Bug
##### Ansible Version:

ansible 1.5.1
ansible 1.5.3-1
##### Environment:

Centos 6.5 64bit
##### Summary:

Trying to use nohup together with ansible commands. (ansible & ansible-playbook).
This is to detach ansible run from a user. 
##### Steps To Reproduce:

w/o nohup :

$ ansible -i hosts.rackspace -m ping proxy
ukproxy | success >> {
"changed": false,
"ping": "pong"
}

with nohup:

$ nohup ansible -i hosts.rackspace -m ping proxy
nohup: ignoring input and appending output to `nohup.out'

$ cat nohup.out
Traceback (most recent call last):
File "/usr/bin/ansible", line 226, in 
(runner, results) = cli.run(options, args)
File "/usr/bin/ansible", line 200, in run
results = runner.run()
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 1181, in run
results = self.parallel_exec(hosts)
File "/usr/lib/python2.6/site-packages/ansible/runner/__init_.py", line 1092, in _parallel_exec
new_stdin = os.fdopen(os.dup(sys.stdin.fileno()))
OSError: [Errno 22] Invalid argument
##### Expected Results:

Just to run like normal but detached from the current session.
##### Actual Results:

Traceback (most recent call last):
File "/usr/bin/ansible", line 226, in 
(runner, results) = cli.run(options, args)
File "/usr/bin/ansible", line 200, in run
results = runner.run()
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 1181, in run
results = self.parallel_exec(hosts)
File "/usr/lib/python2.6/site-packages/ansible/runner/__init_.py", line 1092, in _parallel_exec
new_stdin = os.fdopen(os.dup(sys.stdin.fileno()))
OSError: [Errno 22] Invalid argument

**Comment by mpdehaan** [comment]
Yep this is basically the "don't dedup stdin when it's not a thing, thing".   Thanks for the report.

**Comment by jimi-c** [comment]
The above patch should resolve the issue, and will be included in the next release. If you continue having problems regarding this issue or if you have any other questions regarding this, please let us know. Thanks!

**Comment by leevs** [comment]
I can confirm this is indeed fixed for the new version of ansible 
ansible-1.6-1.el6.noarch

Thanks  !
