### ISSUE TITLE
Traceback using group_by and with_items

### ISSUE THREAD

**Issue by mcodd** [ansible/ansible#6660]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Running Ansible from CentOS5 and managing CentOS5 systems
##### Summary:

It looks like using group_by plus with_items results in a stacktrace.  See details below.  Also see https://groups.google.com/forum/#!msg/ansible-project/6icKbPeY8x4/YSWawDxtBywJ where it looks like I'm not the only one seeing this.
##### Steps To Reproduce:

playbook:

```

---
- hosts: waluat1
  user: ansible
  sudo: true
  vars:
    all_roles: [ 'web', 'webapp' ]
  roles:
    - { role: grouper, tags: [ "grouper" ] }
```

inventory:

```
waluat1
```

grouper role's main.yml:

```

---
- name: show all_roles
  debug: msg="{{ all_roles }}"

- name: generate role groups
  group_by:  key="{{ item }}"
  with_items: all_roles
```
##### Expected Results:

I would expect waluat1 to be added to the "web" and "webapp" groups
##### Actual Results:

```
PLAY [waluat1] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [waluat1]

TASK: [grouper | show all_roles] ********************************************** 
ok: [waluat1] => {
    "item": "", 
    "msg": "['web', 'webapp']"
}

TASK: [grouper | generate role groups] **************************************** 
changed: [waluat1] => (item=web)
fatal: [waluat1] => Traceback (most recent call last):
  File "/rbi/ansible/ansible/lib/ansible/runner/__init__.py", line 532, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/rbi/ansible/ansible/lib/ansible/runner/__init__.py", line 654, in _executor_internal
    complex_args=complex_args
  File "/rbi/ansible/ansible/lib/ansible/runner/__init__.py", line 809, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/rbi/ansible/ansible/lib/ansible/runner/action_plugins/group_by.py", line 86, in run
    del self.runner.inventory._vars_per_host[host]
KeyError: 'waluat1'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/mcoddington/bug.retry

waluat1                    : ok=2    changed=0    unreachable=0    failed=1   
```

**Comment by jimi-c** [comment]
The above patch should resolve the issue on the devel branch. If you continue seeing this this issue, please let us know. Thanks!
