### ISSUE TITLE
authorized_key modules fails on existing key which has some extra quoting

### ISSUE THREAD

**Issue by phgrau** [ansible/ansible#6700]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel 90bc9d4a4b) last updated 2014/02/03 10:21:04 (GMT +200)
##### Environment:

Ubuntu 13.10
##### Summary:

While trying to add a new key to ~root/.ssh/authorized_keys the module
stops with a backtrace

```
[...]
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

This is due to an offending key in the authorized_keys file:

```
command="echo bar 'foo bar'" ssh-dss user@foo
```

Some how shlex can't split the offending line in the authorized_keys file correct.
##### Steps To Reproduce:
- Add the following to an authorized_keys file on hostA for user root:

```
command="echo bar 'foo bar'" ssh-dss user@foo
```
- than add a key to that file with ansible

```
 ansible hostA -m authorized_key  -a 'user=root key="ssh-rsa asdasd user@hostB"'
```
##### Expected Results:

the authorized_keys file on hostA for user root should contain the "ssh-rsa asdasd user@hostB" along with existing keys:

``` sh
$ ansible import1 -m authorized_key  -a 'user=root key="ssh-rsa asdasd user@hostB"'                                                                              
import1 | success >> {
    "changed": true, 
    "key": "ssh-rsa asdasd user@hostB", 
    "key_options": null, 
    "keyfile": "/root/.ssh/authorized_keys", 
    "manage_dir": true, 
    "path": null, 
    "state": "present", 
    "unique": false, 
    "user": "root"
}
```
##### Actual Results:

``` sh
$ ansible hostA -m authorized_key  -a 'user=root key="ssh-rsa asdasd user@hostB"'
hostA | FAILED => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1395844493.48-111358824593095/authorized_key", line 1463, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1395844493.48-111358824593095/authorized_key", line 418, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-tmp-1395844493.48-111358824593095/authorized_key", line 351, in enforce_state
    existing_keys = readkeys(module, params["keyfile"])
  File "/root/.ansible/tmp/ansible-tmp-1395844493.48-111358824593095/authorized_key", line 293, in readkeys
    key_data = parsekey(module, line)
  File "/root/.ansible/tmp/ansible-tmp-1395844493.48-111358824593095/authorized_key", line 259, in parsekey
    key_parts = list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by jimi-c** [comment]
The above patch should resolve this issue, and will be included in the next major release. If you continue seeing problems related to this issue, or if you have any further questions, please let us know. Thanks!
