### ISSUE TITLE
jabber module failes - but message is sent

### ISSUE THREAD

**Issue by xshadow** [ansible/ansible#6704]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Debian 7
##### Summary:

When you try to send a jabber message to an existing user on the given host. The message is sent but the module fails. 
##### Steps To Reproduce:

roles/notify/main.yml

```
#send a message to a user
- name: send init message to user1
jabber:
user: user@jabber.example.net
password: XXX
to: user1@jabber.example.net
msg: "The server{{ ansible_hostname }}-{{ ansible_fqdn }} was provisioned"

#send a message to a user2
- name: send init message to user
jabber:
user: user@jabber.example.net
password: XXX
to: user1@jabber.example.net
msg: "The server{{ ansible_hostname }}-{{ ansible_fqdn }} was provisioned"
```
##### Expected Results:

Success and send the next message
##### Actual Results:

```
fatal: [192.168.1.105] => failed to parse: Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /usr/lib/python2.7/dist-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x29dad40> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: socket       start Successfully connected to remote host ('jabber.example.net.', 5222)
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x2a11680> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as xmpp.protocol.Iq(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as xmpp.protocol.Presence(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as xmpp.protocol.Message(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x2a11680>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.net" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='jabber.example.net' id='615bf8e4-08f7-47ab-9943-5e35c51a5015' xml:lang='en' xmlns='jabber:client'>
  <stream:features>
  <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>
  <required/>
  </starttls>
  </stream:features>
DEBUG: dispatcher   warn  Unknown stanza: features
DEBUG: dispatcher   ok    Dispatching unknown stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-tls'] id->None
DEBUG: tls          start Plugging <xmpp.transports.TLS instance at 0x2a11e18> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: tls          ok    TLS supported by remote server. Requesting TLS start.
DEBUG: dispatcher   info  Registering handler <bound method TLS.StartTLSHandler of <xmpp.transports.TLS instance at 0x2a11e18>> for "proceed" type-> ns->(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   warn  Registering namespace "urn:ietf:params:xml:ns:xmpp-tls"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   warn  Registering protocol "proceed" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   info  Registering handler <bound method TLS.StartTLSHandler of <xmpp.transports.TLS instance at 0x2a11e18>> for "failure" type-> ns->(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   warn  Registering protocol "failure" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: socket       sent  <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
DEBUG: socket       got   <proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-tls/proceed stanza
DEBUG: dispatcher   ok    Dispatching proceed stanza with type-> props->[] id->None
DEBUG: tls          ok    Got starttls proceed response. Switching to TLS/SSL...
DEBUG: dispatcher   stop  Plugging <xmpp.dispatcher.Dispatcher instance at 0x2a11680> out of <xmpp.client.Client instance at 0x29dac68>.
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x2a19e18> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as xmpp.protocol.Iq(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as xmpp.protocol.Presence(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as xmpp.protocol.Message(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x2a19e18>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.net" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='jabber.example.net' id='f716b20c-12fb-495c-b7e4-3edbe9d452b9' xml:lang='en' xmlns='jabber:client'>
  <stream:features>
  <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  <mechanism>SCRAM-SHA-1</mechanism>
  <mechanism>PLAIN</mechanism>
  </mechanisms>
  </stream:features>
DEBUG: dispatcher   warn  Unknown stanza: features
DEBUG: dispatcher   ok    Dispatching unknown stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-sasl'] id->None
DEBUG: sasl         start Plugging <xmpp.auth.SASL instance at 0x2a20c20> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x2a20c20>> for "challenge" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering namespace "urn:ietf:params:xml:ns:xmpp-sasl"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "challenge" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x2a20c20>> for "failure" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "failure" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL instance at 0x2a20c20>> for "success" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "success" as xmpp.protocol.Protocol(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: socket       sent  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">YW5zaWJsZUBqYWJiZXIuc3lzdGVtbGkub3JnAGFuc2libGUARV9TNW1seENHWFNSSjF4LTUzZ0Vx\nXzNSLThKZk5y\n</auth>
DEBUG: socket       got   <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  </success>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/success stanza
DEBUG: dispatcher   ok    Dispatching success stanza with type-> props->[] id->None
DEBUG: sasl         ok    Successfully authenticated with remote server.
DEBUG: dispatcher   stop  Plugging <xmpp.dispatcher.Dispatcher instance at 0x2a19e18> out of <xmpp.client.Client instance at 0x29dac68>.
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher instance at 0x2a22cf8> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as xmpp.protocol.Protocol(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as xmpp.protocol.Protocol(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as xmpp.protocol.Iq(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as xmpp.protocol.Presence(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as xmpp.protocol.Message(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher instance at 0x2a22cf8>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" to="jabber.example.net" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" >
DEBUG: bind         start Plugging <xmpp.auth.Bind instance at 0x2a22e18> into <xmpp.client.Client instance at 0x29dac68>
DEBUG: dispatcher   info  Registering handler <bound method Bind.FeaturesHandler of <xmpp.auth.Bind instance at 0x2a22e18>> for "features" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "features" as xmpp.protocol.Protocol(http://etherx.jabber.org/streams)
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='jabber.example.net' id='731df385-ab5b-4614-a7cf-2f68ed6404ac' xml:lang='en' xmlns='jabber:client'>
  <stream:features>
  <compression xmlns='http://jabber.org/features/compress'>
  <method>zlib</method>
  </compression>
  <c hash='sha-1' ver='oxBiiFkjfIU4zAle9Gk8+Qn8Fhk=' node='http://prosody.im' xmlns='http://jabber.org/protocol/caps'/>
  <sm xmlns='urn:xmpp:sm:2'>
  <optional/>
  </sm>
  <sm xmlns='urn:xmpp:sm:3'>
  <optional/>
  </sm>
  <ver xmlns='urn:xmpp:features:rosterver'/>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'>
  <required/>
  </bind>
  <session xmlns='urn:ietf:params:xml:ns:xmpp-session'>
  <optional/>
  </session>
  </stream:features>
DEBUG: dispatcher   ok    Got http://etherx.jabber.org/streams/features stanza
DEBUG: dispatcher   ok    Dispatching features stanza with type-> props->[u'http://jabber.org/features/compress', u'http://jabber.org/protocol/caps', u'urn:xmpp:sm:2', u'urn:xmpp:sm:3', u'urn:xmpp:features:rosterver', u'urn:ietf:params:xml:ns:xmpp-bind', u'urn:ietf:params:xml:ns:xmpp-session'] id->None
DEBUG: socket       sent  <iq type="set" id="1">
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind">
  <resource>Ansible</resource>
  </bind>
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:1 with timeout 25...
DEBUG: socket       got   <iq id='1' type='result'>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'>
  <jid>ansible@jabber.example.net/Ansible</jid>
  </bind>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[u'urn:ietf:params:xml:ns:xmpp-bind'] id->1
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully bound ansible@jabber.example.net/Ansible.
DEBUG: socket       sent  <iq type="set" id="2">
  <session xmlns="urn:ietf:params:xml:ns:xmpp-session" />
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:2 with timeout 25...
DEBUG: socket       got   <iq id='2' type='result' to='ansible@jabber.example.net/Ansible'/>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[] id->2
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully opened session.
DEBUG: socket       sent  <presence id="3" />
DEBUG: socket       sent  <message to="user1@jabber.example.net" type="chat" id="4">
  <body>Der Server debian7-debian7 wurde initialisiert. Bitte aendere dein Passwort und teile das Crypt-Passwort</body>
  </message>
DEBUG: socket       sent  </stream:stream>
DEBUG: socket       got   <presence id='3' from='ansible@jabber.example.net/Ansible'/>
  <presence to='ansible@jabber.example.net/Ansible' from='ansible@jabber.example.net/a4d13498-a7a0-411c-986b-0094a2fa903b'>
  <show>away</show>
  <c ver='AcN1/PEN8nq7AHD+9jpxMV4U6YM=' ext='voice-v1 camera-v1 video-v1' hash='sha-1' node='http://pidgin.im/' xmlns='http://jabber.org/protocol/caps'/>
  <x xmlns='vcard-temp:x:update'>
  <photo>eb9709ea28f5fb87ce4c91dc950ebb68fa43b696</photo>
  </x>
  <delay from='jabber.example.net' stamp='2014-03-26T15:07:19Z' xmlns='urn:xmpp:delay'/>
  </presence>
DEBUG: dispatcher   ok    Got jabber:client/presence stanza
DEBUG: dispatcher   ok    Dispatching presence stanza with type-> props->[] id->3
DEBUG: dispatcher   ok    Got jabber:client/presence stanza
DEBUG: dispatcher   ok    Dispatching presence stanza with type-> props->[u'jabber:client', u'http://jabber.org/protocol/caps', u'vcard-temp:x:update', u'urn:xmpp:delay'] id->None
DEBUG: socket       got   </stream:stream>
DEBUG: socket       error Socket error while receiving data
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1395848533.21-190274966573761/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
DEBUG: client       stop  Disconnect detected
DEBUG: socket       error Socket operation failed
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1395848533.21-190274966573761/jabber", line 104, in main
    to, nick = module.params['to'].split('/', 1)
ValueError: need more than 1 value to unpack
{"msg": "The server debian7-debian7 was provisioned", "to": "user1@jabber.example.net", "changed": false, "user": "ansible"}


FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
weird, the exception should be caught, as per actual code:

```
try:
    to, nick = module.params['to'].split('/', 1)
except ValueError:
    to, nick = module.params['to'], None
```

are you sure you are not using an old version of the library?

**Comment by xshadow** [comment]
I use the python-xmpp package from the debian repository.

(0.4.1-cvs20080505.2)

**Comment by bcoca** [comment]
i meant the jabber module itself

**Comment by xshadow** [comment]
Can I have an old version when I use ansible 1.5.3, installed via pip install ansible --upgrade

**Comment by bcoca** [comment]
I don't know, I always run from checkout. What is clear is that the current code should trap that error but that does not happen in your case.

**Comment by xshadow** [comment]
On ansible 1.5.4 it's still the same issue

**Comment by bcoca** [comment]
I believe you are somehow using a old version of the library, left behind from some previous install

**Comment by xshadow** [comment]
bcoca, thank you that was indeed the trick. 

I did a sudo pip uninstall ansible && sudo pip install ansible  

and now it works. Thanks for your help
