### ISSUE TITLE
ansible-doc -l broken on mac

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible#67430]
##### SUMMARY
ansible-doc -l
ERROR! Unexpected Exception, this is probably a bug: invalid character in identifier (<unknown>, line 1)
to see the full traceback, use -vvv

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-doc

##### ANSIBLE VERSION
```
ansible 2.9.5
  config file = /Users/pgriffit/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.7/site-packages']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
CACHE_PLUGIN(/Users/pgriffit/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/pgriffit/ansible.cfg) = /Users/pgriffit/ansible/cachedir
CACHE_PLUGIN_TIMEOUT(/Users/pgriffit/ansible.cfg) = 8640
DEFAULT_GATHERING(/Users/pgriffit/ansible.cfg) = smart
DEFAULT_LOG_PATH(/Users/pgriffit/ansible.cfg) = /Users/pgriffit/ansible.log
DEFAULT_MANAGED_STR(/Users/pgriffit/ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}
host: {host}
DEFAULT_MODULE_PATH(/Users/pgriffit/ansible.cfg) = ['/usr/local/lib/python3.7/site-packages']
INVENTORY_ENABLED(/Users/pgriffit/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
```

##### OS / ENVIRONMENT
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

##### STEPS TO REPRODUCE

Either pip install ansible --upgrade, or uninstall/install has the same issue
I had this on a previous minor release update. same bug crept back in?

##### EXPECTED RESULTS
Should just work!

##### ACTUAL RESULTS

```
ansible-doc -l -vvv
ansible-doc 2.9.5
  config file = /Users/pgriffit/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.7/site-packages']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-doc
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
Using /Users/pgriffit/ansible.cfg as config file
ERROR! Unexpected Exception, this is probably a bug: invalid character in identifier (<unknown>, line 1)
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-doc", line 123, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/doc.py", line 149, in run
    descs = self._get_plugin_list_descriptions(loader)
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/doc.py", line 411, in _get_plugin_list_descriptions
    metadata = extract_metadata(module_data=f.read())
  File "/usr/local/lib/python3.7/site-packages/ansible/parsing/metadata.py", line 189, in extract_metadata
    module_ast = ast.parse(module_data)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    #------------------------------------------------------------------------------
    ^
SyntaxError: invalid character in identifier
```

**Comment by sivel** [comment]
I cannot duplicate this issue.  I've checked within the 2.9.5 sources, and there are no python files that include the line:

```
#------------------------------------------------------------------------------
```

Without more research on your side, to determine what file is causing that issue, I'm not sure we can realistically help.

Perhaps you have some custom module that is causing this issue?

needs_info

**Comment by ffirg** [comment]
if I :

```
cd /usr/local/lib/python3.7/site-packages/ansible/modules/windows
ansible-doc -l | wc -l
    3681
```

if I go back to my home directory:
```
cd
ansible-doc -l | wc -l
ERROR! Unexpected Exception, this is probably a bug: invalid character in identifier (<unknown>, line 1)
       1
```

Any ideas?

**Comment by ffirg** [comment]
ok it's something in my $HOME ansible.cfg file:

```
[defaults]
library = /usr/local/lib/python3.7/site-packages
ansible_python_interpreter = /usr/local/bin/python

gathering = smart
fact_caching = jsonfile
fact_caching_connection = /Users/pgriffit/ansible/cachedir
fact_caching_timeout = 8640

log_path = ./ansible.log

ansible_managed = This file is managed by Ansible.%n
  template: {file}
  date: %Y-%m-%d %H:%M:%S
  user: {uid}
  host: {host}

[inventory]
enable_plugins = host_list, script, auto, yaml, ini, toml
```

**Comment by sivel** [comment]
I'd say this is potentially the problem:

```
library = /usr/local/lib/python3.7/site-packages
```

That would attempt to use every python file in that dir as a module, and I believe subdirs too.

**Comment by ffirg** [comment]
Thanks @sivel that's the culprit!
