### ISSUE TITLE
KeyError: 'orange'

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#681]
Got this error when running a playbook:

```
Traceback (most recent call last):
  File "/Users/lorin/ansible/bin/ansible-playbook", line 134, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/lorin/ansible/bin/ansible-playbook", line 111, in main
    pb.run()
  File "/Users/lorin/ansible/lib/ansible/playbook/__init__.py", line 152, in run
    self._run_play(Play(self,play_ds))
  File "/Users/lorin/ansible/lib/ansible/playbook/__init__.py", line 315, in _run_play
    self._run_task(play, task, False)
  File "/Users/lorin/ansible/lib/ansible/playbook/__init__.py", line 217, in _run_task
    results = self._run_task_internal(task)
  File "/Users/lorin/ansible/lib/ansible/playbook/__init__.py", line 198, in _run_task_internal
    results = runner.run()
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 752, in run
    self.callbacks.on_no_hosts()
  File "/Users/lorin/ansible/lib/ansible/callbacks.py", line 322, in on_no_hosts
    print stringc("no hosts matched or remaining\n", 'orange')
  File "/Users/lorin/ansible/lib/ansible/color.py", line 54, in stringc
    return "\033["+codeCodes[color]+"m"+text+"\033[0m"
KeyError: 'orange'
```

**Comment by mpdehaan** [comment]
ugh, it's clear I didn't find all the corner cases.  Looking.

**Comment by mpdehaan** [comment]
changed it to red, not sure this is always an error sort of thing, but it should probably get someone's attention as that is what happens when all the hosts fail or the host group didn't match anything at all.

Thanks for catching this.
