### ISSUE TITLE
get_url 'url' parameter should be marked required

### ISSUE THREAD

**Issue by rasputnik** [ansible/ansible#6857]
##### Issue Type:

Bug Report
##### Ansible Version:

:$ ansible --version

```
       ansible 1.6 (devel f6db60cbce) last updated 2014/04/03 15:50:16 (GMT +100)
```
##### Environment:

:$ vagrant ssh mslave1 -c 'cat /etc/redhat-release; python --version'

```
    CentOS release 6.5 (Final)
    Python 2.6.6
    Connection to 127.0.0.1 closed.
```
##### Summary:

I fat finger get_url to have a src= field rather than a url= field.
Rather than a usage error, i got a python stack trace (see below).
##### Steps To Reproduce:

:$ cat bug.hosts

```
    mslave1 ansible_ssh_host=10.10.10.101 ansible_ssh_user=vagrant ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
```

:$ cat bug.yml

```
    - hosts: mslave1
      sudo: yes
      tasks:
        - get_url:     src=http://downloads.mesosphere.io/master/centos/6/mesos_0.17.0_x86_64.rpm
           dest=/tmp/foo
```
##### Expected Results:

Some error along the lines of : get_url is missing a required field "url".
##### Actual Results:

:$ ansible-playbook -i bug.hosts -vv bug.yml

```
PLAY [mslave1] ****************************************************************

GATHERING FACTS ***************************************************************
<10.10.10.101> REMOTE_MODULE setup
ok: [mslave1]

TASK: [get_url src=http://downloads.mesosphere.io/master/centos/6/mesos_0.17.0_x86_64.rpm dest=/tmp/foo] ***
<10.10.10.101> REMOTE_MODULE get_url src=http://downloads.mesosphere.io/master/centos/6/mesos_0.17.0_x86_64.rpm dest=/tmp/foo
fatal: [mslave1] => failed to parse: SUDO-SUCCESS-ivyegnykbngswzwjvrsrpxnxbcujcysp
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396609075.72-267618737653381/get_url", line 1770, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396609075.72-267618737653381/get_url", line 209, in main
    tmpsrc, info = url_get(module, url, dest, use_proxy, last_mod_time, force)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396609075.72-267618737653381/get_url", line 134, in url_get
    rsp, info = fetch_url(module, url, use_proxy=use_proxy, force=force, last_mod_time=last_mod_time)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396609075.72-267618737653381/get_url", line 1676, in fetch_url
    parsed = urlparse.urlparse(url)
  File "/usr/lib64/python2.6/urlparse.py", line 132, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.6/urlparse.py", line 171, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/sisred/bug.retry

mslave1                    : ok=1    changed=0    unreachable=1    failed=0
```

:$

**Comment by sivel** [comment]
I see 2 things here:
1. `src` is not the correct attribute to use for specifying the URL.  The correct attribute is `url`.
2. For some reason `AnsibleModule` isn't reporting that `src` is an invalid attribute.

**Comment by rasputnik** [comment]
Thanks, have updated title to reflect pilot error.

**Comment by mpdehaan** [comment]
@sivel, src is accepted because it supports the common arguments of the file module, of which this is one.

This seems ridiculously easy to fix just by adding "url" to the argument_spec as a required argument.

**Comment by sivel** [comment]
Just as a heads up, and I think making `url` required is a good idea, that a change may need to happen in both, `ec2_facts` and `nexmo` which use url_argument_spec and don't require a 'url' attribute to function.

**Comment by AlanCoding** [comment]
I hit an error that resulted in

```
  File "/usr/lib64/python2.6/urlparse.py", line 171, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```

I believe that this constitutes some bad error handling, will look into filing an issue.
