### ISSUE TITLE
AssertionError in module docstrings

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#6894]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.6 (devel 26ce8dac27) last updated 2014/04/08 11:45:50 (GMT -400)
```
##### Environment:

NA
##### Summary:

The code in https://github.com/ansible/ansible/commit/1fa19e29 is causing parsing errors for template, file, copy and cron modules with ansible-doc -l

```
Traceback (most recent call last):
  File "/home/jtanner/ansible/lib/ansible/utils/module_docs.py", line 69, in get_docstring
    assert fragment_class is not None
AssertionError
```
##### Steps To Reproduce:
- ansible-doc -l

**Comment by jctanner** [comment]
```
rendering: rds
rendering: rds_param_group
rendering: rds_subnet_group
rendering: redhat_subscription
rendering: redis
rendering: replace
rendering: rhTraceback (most recent call last):
  File "/var/lib/jenkins/workspace/Build_Ansible_Docs/lib/ansible/utils/module_docs.py", line 69, in get_docstring
    assert fragment_class is not None
AssertionError

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Build_Ansible_Docs/lib/ansible/utils/module_docs.py", line 69, in get_docstring
    assert fragment_class is not None
AssertionError
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Build_Ansible_Docs/lib/ansible/utils/module_docs.py", line 69, in get_docstring
    assert fragment_class is not None
AssertionError

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Build_Ansible_Docs/lib/ansible/utils/module_docs.py", line 69, in get_docstring
    assert fragment_class is not None
AssertionError
n_channel
rendering: rhn_register
rendering: riak
rendering: rollbar_deployment
rendering: route53
rendering: rpm_key
rendering: s3
```
