### ISSUE TITLE
Module gitlab_runner cannot create runners

### ISSUE THREAD

**Issue by nachootal** [ansible/ansible#68993]
I'm using current version of ansible installed via brew:
```
  ansible 2.9.6
  config file = None
  configured module search path = ['/Users/nacho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:29:50) [Clang 11.0.0 (clang-1100.0.33.17)]
```

and am creating gitlab runners based on CentOS VMs
```
---
  - hosts: all
    tasks:
    - name: "Install python"
      yum:
        name: python3
        state: latest
      become: yes
    - name: "Install dependencies"
      pip:
        name: python-gitlab
      become: yes
    - name: "Register runner"
      gitlab_runner:
        api_url: https://gitlab.com/api/v4
        api_token: <edited_an_owner_user_token>
        registration_token: <edited_a_registration_token_for_runners_from_gitlab>
        description: Test Gitlab Runner Machine t1
        state: present
        active: True
        tag_list: [ 'test']
        run_untagged: False
        locked: False
```
I installed python3 and the python-gitlab module on the host out of the documentation of the module requesting this.
I get the following error:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1587107312.127886-166774589825079/AnsiballZ_gitlab_runner.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1587107312.127886-166774589825079/AnsiballZ_gitlab_runner.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1587107312.127886-166774589825079/AnsiballZ_gitlab_runner.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.source_control.gitlab_runner', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_gitlab_runner_payload_srkquubc/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 392, in <module>
  File "/tmp/ansible_gitlab_runner_payload_srkquubc/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 357, in main
TypeError: __init__() got an unexpected keyword argument 'email'
fatal: [default]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1587107312.127886-166774589825079/AnsiballZ_gitlab_runner.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1587107312.127886-166774589825079/AnsiballZ_gitlab_runner.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1587107312.127886-166774589825079/AnsiballZ_gitlab_runner.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.source_control.gitlab_runner', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_gitlab_runner_payload_srkquubc/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 392, in <module>\r\n  File \"/tmp/ansible_gitlab_runner_payload_srkquubc/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 357, in main\r\nTypeError: __init__() got an unexpected keyword argument 'email'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

I'm using python-gitlab because this is what is recommended on the official documentation but I've read an issue [here](https://github.com/ansible/ansible/issues/40154) that recommends using pyapi-gitlab.
Using pyapi-gitlab I get the following output:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_gitlab_runner_payload_pyas03cw/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 357, in main
TypeError: __init__() got an unexpected keyword argument 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1587108308.389817-48103762829493/AnsiballZ_gitlab_runner.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1587108308.389817-48103762829493/AnsiballZ_gitlab_runner.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1587108308.389817-48103762829493/AnsiballZ_gitlab_runner.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.source_control.gitlab_runner', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_gitlab_runner_payload_pyas03cw/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 392, in <module>
  File "/tmp/ansible_gitlab_runner_payload_pyas03cw/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 359, in main
AttributeError: module 'gitlab.exceptions' has no attribute 'GitlabAuthenticationError'
fatal: [default]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_gitlab_runner_payload_pyas03cw/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 357, in main\r\nTypeError: __init__() got an unexpected keyword argument 'url'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1587108308.389817-48103762829493/AnsiballZ_gitlab_runner.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1587108308.389817-48103762829493/AnsiballZ_gitlab_runner.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1587108308.389817-48103762829493/AnsiballZ_gitlab_runner.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.source_control.gitlab_runner', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_gitlab_runner_payload_pyas03cw/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 392, in <module>\r\n  File \"/tmp/ansible_gitlab_runner_payload_pyas03cw/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 359, in main\r\nAttributeError: module 'gitlab.exceptions' has no attribute 'GitlabAuthenticationError'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Shall I start debugging any of the pyapi-gitlab or python-gitlab modules or am I having an issue with configuration here?.

**Comment by jctanner** [comment]
!component =lib/ansible/modules/source_control/gitlab_runner.py

**Comment by nachootal** [comment]
> !component =lib/ansible/modules/source_control/gitlab_runner.py

@jctanner Sorry, I'm not really an expert in Python. Could you elaborate a bit on this?.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
