### ISSUE TITLE
Cannot use ansible filters with ansible-galaxy

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#69104]
##### SUMMARY

I am trying to use ansible filters to template some files in my role skeleton, but ansible-galaxy cannot find them. Only jinja2 filters work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
none
```

##### STEPS TO REPRODUCE

Create a file like the one below in your role skeleton:

```yaml
{{ role_name | replace('-', '_') }}_flags:
  - name: {{ role_name | replace('-', '_') }}_flag
    id: {{ role_name | to_uuid | truncate(6, True, '', 0) }}
...
```

##### EXPECTED RESULTS

I would expect `to_uuid` to run fine.

##### ACTUAL RESULTS

```paste below
ERROR! Unexpected Exception, this is probably a bug: no filter named 'to_uuid'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 479, in run
    context.CLIARGS['func']()
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 882, in execute_init
    template_env.get_template(src_template).stream(inject_data).dump(dest_file, encoding='utf-8')
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3.8/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/nikos/Projects/ethical-hacking/EN2720/resources/skeletons/vulnerability-role/defaults/flags.yml.j2", line 8, in template
    id: {{ role_name | to_uuid | truncate(6, True, '', 0) }}
jinja2.exceptions.TemplateAssertionError: no filter named 'to_uuid'
```

`replace` runs fine.

**Comment by sivel** [comment]
It seems that we use default jinja2, and not our own templating engine.  I'm not sure why, but this would require switching over and I'm unsure how complex that would be.
