### ISSUE TITLE
FirewallD Module Fails with backtrace when firewalld cannot be contacted

### ISSUE THREAD

**Issue by rrix** [ansible/ansible#6911]
##### Ansible Version:

`
{0}% ansible --version                                                             rrix@kusanagi
ansible 1.5
`
##### Environment:

Fedora 20 bastion managing Fedora 20 clients
##### Summary:

At some point I disabled firewalld on one of my hosts to debug an issue. Later down the path, I went and added a firewalld command to my playbook, and a fairly useless backtrace was raised.
##### Steps To Reproduce:

`
ansible -m service -a "name=firewalld state=stopped" host1
ansible -m firewalld -a "port=80/tcp state=enabled permanent=true" host1
`
##### Expected Results:

some sort of useful error along the lines of what firewall-cmd spits out:

`
{0}% firewall-cmd --list-interfaces                  rrix@kusanagi
FirewallD is not running
`
##### Actual Results:

`
fatal: [cloud01.ftkickass.dn42] => failed to parse: SUDO-SUCCESS-kjlsjbbqyjptmlynpwklexmuuuyfevqn
Traceback (most recent call last):                                                               
  File "/tmp/ansible-tmp-1397027486.02-206431140016175/firewalld", line 1462, in <module>        
    main()                                                                                       
  File "/tmp/ansible-tmp-1397027486.02-206431140016175/firewalld", line 235, in main             
    zone = fw.getDefaultZone()                                                                   
  File "<string>", line 2, in getDefaultZone                                                     
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 121, in _enable_proxy        
    return func(*p, **k)                                                                         
  File "<string>", line 2, in getDefaultZone                                                     
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 51, in handle_exceptions      
    return func(*args, **kwargs)                                                                 
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1256, in getDefaultZone       
    return dbus_to_python(self.fw.getDefaultZone())                                              
AttributeError: 'NoneType' object has no attribute 'getDefaultZone'                              
`

**Comment by jimi-c** [comment]
The above commit should resolve this issue for you, and will be included in the next major release. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Comment by rrix-storehouse** [comment]
:+1: thanks

**Comment by lightblu** [comment]
Can someone reopen this issue? This patch somehow got lost and when firewalld is not running on the target system even with -vvv you get a rather uninformative exception:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 2366, in <module>
  File "<stdin>", line 278, in main
  File "<string>", line 2, in getDefaultZone
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 103, in _enable_proxy
    return func(*p, **k)
  File "<string>", line 2, in getDefaultZone
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1917, in getDefaultZone
    return dbus_to_python(self.fw.getDefaultZone())
AttributeError: 'NoneType' object has no attribute 'getDefaultZone'

fatal: [host]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

**Comment by jimi-c** [comment]
@lightblu please open a new issue for this in ansible/ansible-modules-extras, if there is a problem.

Thanks!

**Comment by lightblu** [comment]
Ok, will do. Just to make sure because I was not clear enough: 
This is exactly the same issue as described above. And the solution is also exactly the same as you jimi-c provided in April 2014 (https://github.com/ansible/ansible/commit/f547733b1f2136a531432ba652edebaec6873baf):
check for fw.connected. It is just not present anymore on the latest dev branch and thus shows the same problematic behaviour as described in this original issue above, so I will do an almost copy&paste of this issue?!

**Comment by jimi-c** [comment]
Sure, that'd be sufficient. I'm wondering if some later change just broke this.
