### ISSUE TITLE
fileglob plugin fails in 2.9.8 with non-existent subdirectory

### ISSUE THREAD

**Issue by markgoddard** [ansible/ansible#69450]
##### SUMMARY
We started seeing an issue in our OpenStack CI today, where a task using with_fileglob fails. The path passed contains a non-existent subdirectory. Reproduced the issue on my laptop.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

fileglob plugin

##### ANSIBLE VERSION

```paste below
ansible 2.9.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mark/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mark/src/ansible-playground/venv-2.9/local/lib/python2.7/site-packages/ansible
  executable location = venv-2.9/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Seen on Ubuntu 16.04 and 18.04.

##### STEPS TO REPRODUCE

Run the following playbook via `ansible-playbook glob.yml -e path=<path>`, to test different paths.

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: hi
      with_fileglob: "{{ path }}"
```

I tried the following paths:
`/`
`/foo` (does not exist)
`/foo/bar` (does not exist)

##### EXPECTED RESULTS

The module should not fail.

##### ACTUAL RESULTS

`/`: ok
`/foo` (does not exist): ok
`/foo/bar` (does not exist): fails

```paste below
PLAY [localhost] *******************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug] ***********************************************************************************************************************************************************************************************
task path: /home/mark/src/ansible-playground/glob.yml:5
[WARNING]: Unable to find '/foo' in expected paths (use -vvvvv to see paths)
The full traceback is:
Traceback (most recent call last):
  File "/home/mark/src/ansible-playground/venv-2.9/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 104, in run
    items = self._get_loop_items()
  File "/home/mark/src/ansible-playground/venv-2.9/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 245, in _get_loop_items
    items = wrap_var(mylookup.run(terms=loop_terms, variables=self._job_vars, wantlist=True))
  File "/home/mark/src/ansible-playground/venv-2.9/local/lib/python2.7/site-packages/ansible/plugins/lookup/fileglob.py", line 75, in run
    globbed = glob.glob(to_bytes(os.path.join(dwimmed_path, term_file), errors='surrogate_or_strict'))
  File "/home/mark/src/ansible-playground/venv-2.9/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution."
}
```

The failure I saw originally in CI was slightly different, probably because it uses Python 3.6.

https://1e03df7e49d16b52a381-065293745cdcc6ecb6052ade0199e5ba.ssl.cf2.rackcdn.com/719037/11/check/kolla-ansible-ubuntu-binary-barbican/fe5e35b/primary/logs/ansible/deploy

```yaml
TASK [haproxy : Copying over custom haproxy services configuration] ************
task path: /home/zuul/src/opendev.org/openstack/kolla-ansible/ansible/roles/haproxy/tasks/config.yml:60
[WARNING]: Unable to find '/etc/kolla/config/haproxy/services.d' in expected
paths (use -vvvvv to see paths)
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 104, in run
    items = self._get_loop_items()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 245, in _get_loop_items
    items = wrap_var(mylookup.run(terms=loop_terms, variables=self._job_vars, wantlist=True))
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/lookup/fileglob.py", line 75, in run
    globbed = glob.glob(to_bytes(os.path.join(dwimmed_path, term_file), errors='surrogate_or_strict'))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
fatal: [primary]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

Edit: reproduced the above failure using a local python 3.6 environment and the same test playbook.

**Comment by markgoddard** [comment]
I looked at recent changes to the plugin, and found https://github.com/ansible/ansible/commit/f8a5377cc6233e12c57770bd2efbc00ab7212429#diff-4feaf690e4329444ac345ba6b37d84c4. I have verified that reverting this change fixes this issue.

**Comment by markgoddard** [comment]
Proposed solution: https://github.com/ansible/ansible/commit/f8a5377cc6233e12c57770bd2efbc00ab7212429#r39113855
