### ISSUE TITLE
ldap_attr does not allow creation of group with empty member: attribute

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#69453]
##### SUMMARY
I want to perform the equivalent of this in ansible:

```
dn: cn=developers,ou=Group,dc=test,dc=local
cn: developers
objectClass: top
objectclass: groupOfNames
member:
```
I consider the equivalent as:
```
- name: create ldap groups
  ldap_entry:
    dn: cn=developers,ou=Group,dc=test,dc=local
    objectClass: 
      - top
      - groupOfNames
    attributes:
      cn: "developers"
      member: Null
```
I tried setting `member: ""` or leaving it empty `member: ` resulting in `  - details: {'info': u'member: value #0 invalid per syntax', 'desc': u'Invalid syntax'}`

Omitting the value is also not possible as it is mandatory for `groupOfNames` resulting in `'groupOfNames' requires attribute 'member'`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ldap_attr

##### ANSIBLE VERSION
```ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bernhard/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION
```paste below
<empty>
```

##### OS / ENVIRONMENT
ubuntu 18.04 (client and server)

##### STEPS TO REPRODUCE

On an system with running slapd (and python-ldap) execute the following playbook:

```
- name: create ldap groups
  ldap_entry:
    dn: cn=developers,ou=Group,dc=test,dc=local
    objectClass: 
      - top
      - groupOfNames
    attributes:
      cn: "developers"
      member: Null
```

##### EXPECTED RESULTS
ldap_attr creating the group with no members

##### ACTUAL RESULTS
Ansible fails with invalid syntax.

```
{
  - msg: Entry action failed.
  - exception: Traceback (most recent call last):
  File "/tmp/ansible_ldap_entry_payload_91GEJf/ansible_ldap_entry_payload.zip/ansible/modules/net_tools/ldap/ldap_entry.py", line 256, in main
  File "/tmp/ansible_ldap_entry_payload_91GEJf/ansible_ldap_entry_payload.zip/ansible/modules/net_tools/ldap/ldap_entry.py", line 160, in _add
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 428, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 414, in add_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 749, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 756, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 329, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
INVALID_SYNTAX: {'info': u'member: value #0 invalid per syntax', 'desc': u'Invalid syntax'}

  - changed: False
  - details: {'info': u'member: value #0 invalid per syntax', 'desc': u'Invalid syntax'}
}
```

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by BernhardCW** [comment]
thx for the info

https://github.com/ansible-collections/community.general/issues/325
