### ISSUE TITLE
docker_network module: can't create a network with a dash in the name

### ISSUE THREAD

**Issue by oliverlj** [ansible/ansible#69481]
##### SUMMARY

create a network with docker network with a name including a dash will fail

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_network

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /home/oliver/git/fritzy/infra/fz-infra-swarm/ansible.cfg
  configured module search path = ['/home/oliver/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  remote_user: ansible
  become: true
  tasks:
    - name: Create a network
      docker_network:
        appends: true
        name: "infra-public"
        driver: overlay
        driver_options:
          encrypted: true
      run_once: true

```

##### EXPECTED RESULTS

TASK [Create a network] ****************************************************************************************************************************************************************************************************************************************************************
ok: [fz-manager-1]

##### ACTUAL RESULTS

```paste below
Traceback (most recent call last):
  File "/tmp/ansible_docker_network_payload_6dl1a2gr/ansible_docker_network_payload.zip/ansible/modules/cloud/docker/docker_network.py", line 720, in main
  File "/tmp/ansible_docker_network_payload_6dl1a2gr/ansible_docker_network_payload.zip/ansible/modules/cloud/docker/docker_network.py", line 425, in __init__
  File "/tmp/ansible_docker_network_payload_6dl1a2gr/ansible_docker_network_payload.zip/ansible/modules/cloud/docker/docker_network.py", line 643, in present
  File "/tmp/ansible_docker_network_payload_6dl1a2gr/ansible_docker_network_payload.zip/ansible/modules/cloud/docker/docker_network.py", line 586, in remove_network
  File "/tmp/ansible_docker_network_payload_6dl1a2gr/ansible_docker_network_payload.zip/ansible/modules/cloud/docker/docker_network.py", line 624, in disconnect_all_containers
  File "/tmp/ansible_docker_network_payload_6dl1a2gr/ansible_docker_network_payload.zip/ansible/modules/cloud/docker/docker_network.py", line 628, in disconnect_container
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/network.py", line 273, in disconnect_container_from_network
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: infra-public-endpoint")
```

**Comment by Shrews** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
