### ISSUE TITLE
aws_secret fails if no secret version exists

### ISSUE THREAD

**Issue by pyranja** [ansible/ansible#69710]
##### SUMMARY

When using `aws_secret` to ensure that a secret is set, the module fails if the secret resource exists, but no secret version with stage label `AWSCURRENT` exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_secret

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /home/py/ws/infra/kafka/ansible.cfg
  configured module search path = ['/home/py/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/py/.local/share/virtualenvs/kafka-1pu8kRVe/lib/python3.6/site-packages/ansible
  executable location = /home/py/.local/share/virtualenvs/kafka-1pu8kRVe/bin/ansible
  python version = 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/home/py/ws/infra/kafka/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/py/ws/infra/kafka/ansible.cfg) = ['/home/py/ws/infra/kafka/aws_ec2.yml']
DEFAULT_ROLES_PATH(/home/py/ws/infra/kafka/ansible.cfg) = ['/home/py/ws/infra/kafka/vendor', '/home/py/ws/infra/kafka/roles']
HOST_KEY_CHECKING(/home/py/ws/infra/kafka/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/py/ws/infra/kafka/ansible.cfg) = False
```

##### OS / ENVIRONMENT
not relevant

##### STEPS TO REPRODUCE

Create a new secret via api `aws secretsmanager create-secret --name my-secret`.

:exclamation: The AWS console will set an implicit initial secret version and hides the bug this way.

```yaml
# save the credentials to AWS secrets manager
- name: save credentials to secrets manager
  aws_secret:
    name: "my-secret"
    state: present
    secret_type: 'string'
    secret: "secret-thing"
```

##### EXPECTED RESULTS

A new secret version with label AWSCURRENT is created, the value is set as defined in ansible.

##### ACTUAL RESULTS

Execution fails with a boto error, because there is no secret version, that can be compared to the desired value.

```paste below
Using module file /home/tiberiu/.local/share/virtualenvs/kafka-eBQlScuA/lib/python3.6/site-packages/ansible/modules/cloud/amazon/aws_secret.py
Pipelining is enabled.
<xchg-market-reports> ESTABLISH LOCAL CONNECTION FOR USER: tiberiu
<xchg-market-reports> EXEC /bin/sh -c '/home/tiberiu/.local/share/virtualenvs/kafka-eBQlScuA/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aws_secret_payload_7i4vvcf3/ansible_aws_secret_payload.zip/ansible/modules/cloud/amazon/aws_secret.py", line 394, in <module>
  File "/tmp/ansible_aws_secret_payload_7i4vvcf3/ansible_aws_secret_payload.zip/ansible/modules/cloud/amazon/aws_secret.py", line 374, in main
  File "/tmp/ansible_aws_secret_payload_7i4vvcf3/ansible_aws_secret_payload.zip/ansible/modules/cloud/amazon/aws_secret.py", line 293, in secrets_match
  File "/home/tiberiu/.local/share/virtualenvs/kafka-eBQlScuA/lib/python3.6/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/tiberiu/.local/share/virtualenvs/kafka-eBQlScuA/lib/python3.6/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret value for staging label: AWSCURRENT

fatal: [xchg-market-reports]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aws_secret_payload_7i4vvcf3/ansible_aws_secret_payload.zip/ansible/modules/cloud/amazon/aws_secret.py\", line 394, in <module>\n  File \"/tmp/ansible_aws_secret_payload_7i4vvcf3/ansible_aws_secret_payload.zip/ansible/modules/cloud/amazon/aws_secret.py\", line 374, in main\n  File \"/tmp/ansible_aws_secret_payload_7i4vvcf3/ansible_aws_secret_payload.zip/ansible/modules/cloud/amazon/aws_secret.py\", line 293, in secrets_match\n  File \"/home/tiberiu/.local/share/virtualenvs/kafka-eBQlScuA/lib/python3.6/site-packages/botocore/client.py\", line 276, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/home/tiberiu/.local/share/virtualenvs/kafka-eBQlScuA/lib/python3.6/site-packages/botocore/client.py\", line 586, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret value for staging label: AWSCURRENT\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by pyranja** [comment]
Why is this relevant to us?
We are using terraform to manage our AWS infrastructure, but do not want to let terraform manage passwords. Therefore we create the secretsmanager resource with terraform, without setting any values.
We then use an ansible role to generate a password if it is not present, save it to secrets manager and configure credentials in a target system. If a secret version exists in secrets manager, the role synchronizes the passwords in secretsmanager and the target system.

Due to this bug, the bootstrapping of a new secret does not work.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
