### ISSUE TITLE
import_tasks within import_role not working

### ISSUE THREAD

**Issue by ffgomez** [ansible/ansible#69882]
##### SUMMARY
import/include_tasks from within an import/include_role not working.

Looks like: https://github.com/ansible/ansible/issues/27345

Trying to import/include_role:
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup

fails because the two import_tasks at the beginning
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/pre_checks/002_validate_hostname_tasks.yml

Due to the import on
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/full_execution.yml

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
import_role
include_role

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /root/huertasv10/ansible/ansible.cfg
  configured module search path = [u'/root/huertasv10/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
and
```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/root/huertasv10/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/root/huertasv10/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=30m
ANSIBLE_SSH_CONTROL_PATH(/root/huertasv10/ansible/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/root/huertasv10/ansible/ansible.cfg) = /root/cp
DEFAULT_MODULE_PATH(/root/huertasv10/ansible/ansible.cfg) = [u'/root/huertasv10/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/root/huertasv10/ansible/ansible.cfg) = [u'/root/huertasv10/ansible/plugins/module_utils']
DEFAULT_ROLES_PATH(/root/huertasv10/ansible/ansible.cfg) = [u'/root/huertasv10/ansible/roles', u'/root/huertasv10/ansible/roles_
HOST_KEY_CHECKING(/root/huertasv10/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)
ovirt-node-ng-installer-4.3.4-2019061016.el7

##### STEPS TO REPRODUCE

```
- name: Deploy ovirt hosted engine over a physical host
  include_role:
    name: ovirt.hosted_engine_setup

```
or
```
- name: Deploy ovirt hosted engine over a physical host
  import_role:
    name: ovirt.hosted_engine_setup

```

##### EXPECTED RESULTS

import/include_role should work as regular role invocation

##### ACTUAL RESULTS

```paste below
TASK [ovirt.hosted_engine_setup : System configuration validations] ************************************************************
task path: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/full_execution.yml:7
META: noop
META: noop
META: noop
META: noop
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/files/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles/ovirt.he.iscsi.deploy/files/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles/ovirt.he.iscsi.deploy/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/files/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks"
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_network_test.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_memory_size.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/define_variables.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_data_center_name.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_gateway.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_mac_address.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_services_status.yml for fenix1
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'rfind'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 355, in run
    new_blocks = self._load_included_file(included_file, iterator=iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 807, in _load_included_file
    variable_manager=self._variable_manager,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 77, in load_list_of_blocks
    loader=loader,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/block.py", line 95, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 240, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/usr/lib/python2.7/site-packages/ansible/playbook/block.py", line 131, in _load_block
    use_handlers=self._use_handlers,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 193, in load_list_of_tasks
    parent_include_dir = os.path.dirname(templar.template(parent_include.args.get('_raw_params')))
  File "/usr/lib64/python2.7/posixpath.py", line 129, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by imjoseangel** [comment]
Hi @ffgomez thanks for reporting.

This is weird, because is bug closed time ago:

https://github.com/ansible/ansible/issues/26525

Unfortunately , I cannot reproduce the problem using 2.9.9 and Python 2 and 3.

**Comment by ffgomez** [comment]
Many thanks Jose,

As far as I understood, adding  _raw_params may solve my issue, however it doesn't work. :

```
---
- name: Deploy ovirt hosted engine over a physical host
  include_role:
    name: ovirt.hosted_engine_setup
    _raw_params: ovirt.hosted_engine_setup
...
```
```
ERROR! Invalid options for include_role: _raw_params

The error appears to be in '/root/huertasv10/ansible/tasks/ovirt/hosted_engine_deploy.yaml': line 37, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Deploy ovirt hosted engine over a physical host
  ^ here

```
Am I missing something?

**Comment by imjoseangel** [comment]
`_raw_params` is not part of the include_role input parameters. Could you do a quick test with the configuration example in the issue?

## CONFIGURATION

File organization

```sh
.
├── playbook.yml
├── roles
│   └── foo
│       ├── tasks
│       │   └── main.yml
│       └── tests
│           └── basic.yml
└── temp.yml
```

playbook.yml

```yaml
---
- include: temp.yml
```

temp.yml

```yaml
- hosts: localhost
  tasks:
    - include_role:
        name: foo
```

roles/foo/tasks/main.yml

```yaml
---
- include: tests/basic.yml
```

roles/foo/tests/basic.yml

```yaml
- command: echo 'test'
```

**Comment by ffgomez** [comment]
Aha, I see. Again thanks for the support.

This is how I have set my dir tree, 

Ansible file tree:
```
├── ansible.cfg
├── inventories
├── plugins
├── roles_lib
│   ├── ovirt.he.iscsi.deploy
├── roles
│   ├── ovirt.engine-setup
├── tasks
│   ├── ovirt
│   │   ├── hosted_engine_deploy.yaml
└── test.yaml    (playbook)

```

test.yaml
```
- name: Deploy docker swarm in ovirt
  hosts: ovirt_hosts
  roles:
    - ovirt.he.iscsi.deploy
```

ovirt.he.iscsi.deploy (main.yaml)
```
- import_tasks: tasks/ovirt/hosted_engine_deploy.yaml
  run_once:     true
```  

tasks/ovirt/hosted_engine_deploy.yaml
```
---
- name: Deploy ovirt hosted engine over a physical host
  include_role:
    name: ovirt.hosted_engine_setup
    _raw_params: ovirt.hosted_engine_setup
...
```

I also tried to reproduce the same structure, :
```
.
├── playbook.yml
├── roles
│   └── foo
│       ├── tasks
│       │   └── main.yml
│       └── test
│           └── basic.yml
└── temp.yml
```

but can´t check relative route
```
TASK [foo : include] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "Could not find or access '/root/huertasv10/ansitest/tests/basic.yml' on the Ansible Controller."}
```

Should I fix this, or is this what you were expecting to see?

Thanks and regards,

**Comment by sivel** [comment]
I'm not sure how to actually reproduce this.  We'll need you to provide a complete, minimal reproducer.  Reproducers should not use any modules or plugins that require specific environments, and should not make changes to a system.

With everything provided above, I have no idea what tasks are triggering errors, or how to set up a reproducer.

**Comment by imjoseangel** [comment]
> but can´t check relative route
> 
> ```
> TASK [foo : include] ***********************************************************************************************************
> fatal: [localhost]: FAILED! => {"reason": "Could not find or access '/root/huertasv10/ansitest/tests/basic.yml' on the Ansible Controller."}
> ```

@ffgomez, for your tests keep a simple `ansible.cfg` too. As @sivel refers, try to reproduce the issue in a simple escenario:

```ini
[defaults]
roles_path       = roles
```

Thank you!

**Comment by ffgomez** [comment]
Thanks both, really appreciated,

My main issue is that I have absolutely no clue where the error is. It hangs listing the last element of a with_fileglob loop due to two imports in one of those loop's elements. Everything else tested is working as expected. So I can't really isolate it and prepare a reproducer. 


If you will, the most simplified and aseptic way to reproduce the issue is by the following. My apologies.
```
git clone https://github.com/oVirt/ovirt-ansible-hosted-engine-setup roles/
```

After commenting the package installation, it won't go much further as it will fail trying to validate the non-existent-vars, but long enough to see how import/include_role deviates from role invocation. So no modifications will be done in you system

I guess this role should be working for any Linux
```
vi  roles/ovirt.hosted_engine_setup/tasks/full_execution.yml
```
```
---
- name: Install packages and bootstrap local engine VM
  block:
#    - name: Install required packages for oVirt Hosted Engine deployment
#      import_tasks: install_packages.yml
```

playbook_not_working.yaml
```
---
- name: Deploy ovirt
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy ovirt hosted engine over a physical host
      include_role:
        name: ovirt.hosted_engine_setup
...

```

playbook_working.yaml
```
---
- name: Deploy ovirt
  hosts: localhost
  gather_facts: false
  roles:
    - ovirt.hosted_engine_setup
...
```

**Comment by ffgomez** [comment]
Dear all,

I managed to workaround the issue by replacing import_tasks with include_tasks. But I am still unable to find the least common denominator to reproduce the deviation in import/include_role.

So, in: [https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/pre_checks/002_validate_hostname_tasks.yml](url)  
replace

```
---
- name: Choose IPv4, IPv6 or auto
  import_tasks: ipv_switch.yml
- name: Define he_host_address and he_host_ip
  import_tasks: fetch_host_ip.yml
  when: he_host_ip is none or he_host_address is none
```
with
```
---
- name: Choose IPv4, IPv6 or auto
  include_tasks: ipv_switch.yml
- name: Define he_host_address and he_host_ip
  include_tasks: fetch_host_ip.yml
  when: he_host_ip is none or he_host_address is none
```

And playbook_not_working.yaml will work.

**Comment by mkrizek** [comment]
I was able to infer a simple reproducer from the `ovirt.hosted_engine_setup` role:

#### playbook.yml
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: ovirt-fake
```

#### roles/ovirt-fake/tasks/main.yml
```yaml
- import_tasks: full_execution.yml
```

#### roles/ovirt-fake/tasks/full_execution.yml
```yaml
- include_tasks: 002_validate_hostname_tasks.yml
```

#### roles/ovirt-fake/tasks/002_validate_hostname_tasks.yml
```yaml
- import_tasks: does-not-exist.yml
```

It appears that in:
```python
parent_include_dir = os.path.dirname(templar.template(parent_include.args.get('_raw_params')))
```

`parent_include.args.get('_raw_params')` evaluates to `None` when `parent_include` is of type `IncludeRole`:

```
(Epdb) pp parent_include
TASK: include_role : ovirt-fake
(Epdb) pp type(parent_include)
<class 'ansible.playbook.role_include.IncludeRole'>
(Epdb) pp parent_include.args
{u'name': u'ovirt-fake'}
```

This diff supports the above:

```diff
diff --git a/lib/ansible/playbook/helpers.py b/lib/ansible/playbook/helpers.py
index 45ff837f83..fd968cfcb2 100644
--- a/lib/ansible/playbook/helpers.py
+++ b/lib/ansible/playbook/helpers.py
@@ -184,7 +184,7 @@ def load_list_of_tasks(ds, play, block=None, role=None, task_include=None, use_h
                     if use_handlers:
                         subdir = 'handlers'
                     while parent_include is not None:
-                        if not isinstance(parent_include, TaskInclude):
+                        if not isinstance(parent_include, TaskInclude) or isinstance(parent_include, IncludeRole):
                             parent_include = parent_include._parent
                             continue
                         try:
```

I'll leave the root cause identification and the real fix for @sivel and @jimi-c ;-)

**Comment by mkrizek** [comment]
Looking into this a bit more and with the current understanding, I think the following diff should be closer to "the real fix" (tm):
```diff
diff --git a/lib/ansible/playbook/helpers.py b/lib/ansible/playbook/helpers.py
index 45ff837f83..bc22c3d14a 100644
--- a/lib/ansible/playbook/helpers.py
+++ b/lib/ansible/playbook/helpers.py
@@ -188,7 +188,11 @@ def load_list_of_tasks(ds, play, block=None, role=None, task_include=None, use_h
                             parent_include = parent_include._parent
                             continue
                         try:
-                            parent_include_dir = os.path.dirname(templar.template(parent_include.args.get('_raw_params')))
+                            if isinstance(parent_include, IncludeRole):
+                                task_path = os.path.join(parent_include._role_path, 'tasks')
+                            else:
+                                task_path = parent_include.args.get('_raw_params')
+                            parent_include_dir = os.path.dirname(templar.template(task_path))
                         except AnsibleUndefinedVariable as e:
                             if not parent_include.statically_loaded:
                                 raise AnsibleParserError(
```

**Comment by McSim85** [comment]
Hey @mkrizek 

I appreciate it for the patch.
I have submitted a duplicated issue seems like: https://github.com/ansible/ansible/issues/83852 

I tried to apply your patch https://github.com/ansible/ansible/issues/69882#issuecomment-642564666 and it seems to be working.
I was able to run my repo without the exception.

Are there any plans to add this to the release? 🙏

**Comment by McSim85** [comment]
I have submitted the PR ^^^ for your review, guys 🙏
