### ISSUE TITLE
ansible tries run custom module on python3 while being on pyhton2

### ISSUE THREAD

**Issue by giedriusramas** [ansible/ansible#69900]
##### SUMMARY
Seems like ansible still tries to run custom module in python3 event though ansible is set to use pyhton2 as interpreter and installed via pip on python2. It tries to run custom module by /usr/lib64/python3.6/runpy.py. 
ConfigParser module exists on python2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
custom module 
```
from ConfigParser import RawConfigParser
from ansible.module_utils.basic import *

module = AnsibleModule()
res = {}
res['changed'] = True
module.exit_json(**res)
```

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.17 (default, Oct 30 2019, 17:37:16) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 20
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/opt/ansible/ansible.log
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = paramiko
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False


cat /etc/ansible/ansible.cfg
[defaults]
log_path = /var/opt/ansible/ansible.log
host_key_checking = False
transport = paramiko
forks = 50
gather_timeout = 20
gathering = smart
callback_whitelist = profile_tasks
python_interpreter = /usr/bin/python2.7
[callback_profile_tasks]
task_output_limit = 50
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.2 (Ootpa)
uname -r
4.18.0-193.el8.x86_64

##### STEPS TO REPRODUCE
ansible-playbook -c local -vvv -i /playbooks/inventory /playbooks/test.yml

```
cat  /playbooks/test.yml
- hosts: all
  tasks:
   - name: testing
     testing:

cat /playbooks/library/testing.py
#!/usr/bin/env python2
"""Ansible module for specifying storage requirements and determining a set of
storage allocations to meet those requirements.
"""
from ConfigParser import RawConfigParser
from ansible.module_utils.basic import *

module = AnsibleModule()
res = {}
res['changed'] = True
module.exit_json(**res)

```

##### EXPECTED RESULTS
changed": true,

##### ACTUAL RESULTS

```
the full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1591334149.75-44187-235432566856743/AnsiballZ_testing.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1591334149.75-44187-235432566856743/AnsiballZ_testing.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1591334149.75-44187-235432566856743/AnsiballZ_testing.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.testing', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_testing_payload_1hun249s/ansible_testing_payload.zip/ansible/modules/testing.py", line 5, in <module>
ModuleNotFoundError: No module named 'ConfigParser'
fatal: [vp-xv-vm140001]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1591334149.75-44187-235432566856743/AnsiballZ_testing.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1591334149.75-44187-235432566856743/AnsiballZ_testing.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1591334149.75-44187-235432566856743/AnsiballZ_testing.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.testing', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_testing_payload_1hun249s/ansible_testing_payload.zip/ansible/modules/testing.py\", line 5, in <module>\nModuleNotFoundError: No module named 'ConfigParser'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by mkrizek** [comment]
Does that happen only for that custom module or any module?

In any case, `python_interpreter = /usr/bin/python2.7` should be `interpreter_python  = /usr/bin/python2.7` per https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html.

**Comment by giedriusramas** [comment]
> Does that happen only for that custom module or any module?
> 
> In any case, `python_interpreter = /usr/bin/python2.7` should be `interpreter_python = /usr/bin/python2.7` per https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html.

Thanks @mkrizek seems like it made a changes thanks.
