### ISSUE TITLE
Sudo'ing to non-root user causes permission denied error

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#700]
Play:

```
- hosts: django
  user: vagrant
  sudo: True
  sudo_user: postgres

  tasks:
  - name: try to ping
    action: ping
```

Output:

```
$ ansible-playbook -i vm_hosts postgresql/setup.yaml -e server_name=vagrant

PLAY [django] ********************* 

GATHERING FACTS ********************* 
failed to parse json: /usr/bin/python: can't open file '/home/vagrant/.ansible/tmp/ansible-1343325320.98-65346837707467/setup': [Errno 13] Permission denied

fatal: [192.168.108.100] => Traceback (most recent call last):
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 444, in _executor
    exec_rc = self._executor_internal(host)
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 484, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 565, in _executor_internal_inner
    result = self._execute_normal_module(conn, tmp, module_name, inject=inject)
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 250, in _execute_normal_module
    exec_rc = self._execute_module(conn, tmp, module_name, self.module_args, inject=inject)
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 230, in _execute_module
    return ReturnData(host=conn.host, result=res)
  File "/Users/lorin/ansible/lib/ansible/runner/__init__.py", line 82, in __init__
    self.result = utils.parse_json(self.result)
  File "/Users/lorin/ansible/lib/ansible/utils.py", line 118, in parse_json
    tokens = shlex.split(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by mpdehaan** [comment]
yep, this happens because we transfer the file as user1 and need to run it as user2.

try setting ANSIBLE_REMOTE_TMP (env variable) to a different directory as a workaround, one they can both read, like /tmp.    

Maybe the app if sudoing (to non root) could just always use /tmp  -- though I'm not sure how I feel about that security wise, thoughts?

**Comment by lorin** [comment]
Changing the temp directory alone, doesn't resolve the issue, because of the permissions on the temporary created file (it's executable but not readable):

```
PLAY [django] ********************* 

GATHERING FACTS ********************* 
failed to parse json: /usr/bin/python: can't open file '/tmp/ansible-1343329076.65-109489784242864/setup': [Errno 13]        Permission denied


vagrant@precise64:~$ ls -l /tmp/ansible-1343329076.65-109489784242864/setup
-rwx--x--x 1 vagrant vagrant 24729 Jul 26 18:57 /tmp/ansible-1343329076.65-109489784242864/setup
```

I think always using /tmp when sudoing to non-root is a reasonable approach, as long as the possible security hole is mentioned in the docs.

**Comment by mpdehaan** [comment]
Partial fix -- instead of chmod +x, we could also do chmod 700 prior to execution.

Though when we transfer, ideally we want to transfer with the proper modes.   sftp/paramiko might enable setting this.

(And also still only use /tmp when sudo_user != root)

**Comment by mpdehaan** [comment]
current thinking

for all users, replace +x with chmod 700

if sudoable and sudo and sudo_user != root

chmod 700 + chown before execution

need to happen both to paramiko AND ssh transports

**Comment by mpdehaan** [comment]
closing due to pending 701
