### ISSUE TITLE
Unicode in the task parameter raises exception

### ISSUE THREAD

**Issue by izidormatusov** [ansible/ansible#7084]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.5.5
##### Environment:

Running from Ubuntu 14.04

Provisioning vagrant box with Ubuntu 12.04
##### Summary:

Unicode in the task parameter raises exception
##### Steps To Reproduce:

Run the following task:

``` yaml
- name: Create user
  user:
    name: izidor
    comment: "Izidor Matušov"
    state: present
```
##### Expected Results:

Create user with comment `Izidor Matušov`
##### Actual Results:

```
TASK: [common | Create user] ************************************************** 
failed to parse json:     supports_check_mode=True
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1398021502.61-20564572926207/user", line 1786, in __init__
    self._log_invocation()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1398021502.61-20564572926207/user", line 2374, in _log_invocation
    msg = msg + arg + '=' + str(log_args[arg]) + ' '
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 11: ordinal not in range(128)

fatal: [default] => Traceback (most recent call last):
  File "/home/izidor/.virtualenvs/izidor/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 532, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/izidor/.virtualenvs/izidor/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 629, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/izidor/.virtualenvs/izidor/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 815, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/izidor/.virtualenvs/izidor/local/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/home/izidor/.virtualenvs/izidor/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 502, in _execute_module
    data = utils.parse_json(res['stdout'])
  File "/home/izidor/.virtualenvs/izidor/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 311, in parse_json
    tokens = shlex.split(data)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by jimi-c** [comment]
Thanks, I'll look into this today.

**Comment by jimi-c** [comment]
I was able to reproduce this, and the above patch corrects the issue in my testing. If you continue to have any problems with this issue, please let us know. Thanks!

**Comment by jimi-c** [comment]
Note, this will be included in the next major release, which will be released in the near future.
