### ISSUE TITLE
Traceback when "dst" is not provided to unarchive module

### ISSUE THREAD

**Issue by gmassen** [ansible/ansible#7107]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

OpenSuSE
##### Summary:

Ansible produces stacktrace an simple syntax error (e.g. dst= instead of dest=).
##### Steps To Reproduce:

Use the following playbook:

```

---
- hosts: <...>
  tasks:
  - name: Unpack archive
    tags: unpack
    unarchive: "src=/tmp/file.tar.gz dst=/usr/local/src"
```
- file.tar.gz exists.
- ansible-playbook --syntax-check test.yml is fine.
- ansible-playbook --check test.yml fails.
##### Expected Results:

A simple hint that there is a syntax error (e.g. 'unknown parameter: dst)
##### Actual Results:

```
PLAY [...] ****************************************************

GATHERING FACTS ***************************************************************
ok: [...]

TASK: [Unpack archive] ********************************************************
fatal: [...] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 530, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 621, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 807, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/unarchive.py", line 50, in run
    dest    = os.path.expanduser(options.get('dest', None))
  File "/usr/lib64/python2.7/posixpath.py", line 261, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @...

...        : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by mpdehaan** [comment]
The error here should probably just indicate the dst is required.

**Comment by jimi-c** [comment]
The above patch has been merged, which should resolve this issue. If you continue having problems regarding this, or if you have any further questions, please let us know. Thanks!
