### ISSUE TITLE
grafana_dashboard not creating

### ISSUE THREAD

**Issue by ccathal** [ansible/ansible#71182]
##### SUMMARY
grafana_dashboard not creating. Potential issue with message parameter. Tried variations of message parameter such as commit_message and notification_message. I believe it could be a similar issue to [#60051](https://github.com/ansible/ansible/pull/60051).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_dashboard

##### ANSIBLE VERSION
```
ansible 2.9.1
  config file = /home/cathal/Documents/cathal/ansible/ansible.cfg
  configured module search path = ['/home/cathal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cathal/.local/lib/python3.8/site-packages/ansible
  executable location = /home/cathal/.local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### CONFIGURATION
```
- name: 'Import Grafana dashboard'
  grafana_dashboard:
    grafana_url: 'http://localhost:3000'
    grafana_user: 'admin'
    grafana_password: 'admin'
    path: 'files/dashboards/grafana.json'
    notification_message: 'Update by Ansible'
    state: present
    overwrite: true
```

##### OS / ENVIRONMENT
Ubuntu 20.04
Using grafana version 7.1.3

##### STEPS TO REPRODUCE
Full ansible script located here @ https://gitlab.com/surfprace/cathal/-/tree/ansible_deployment_2/ansible

Run the below playbook.yml of the grafana role with 'ansible-playbook -K playbook.yml --tags grafana'
```
- hosts: 127.0.0.1
  connection: local
  become: true
  roles:
  - role: grafana
    tags: grafana          

```

##### EXPECTED RESULTS
dashboard created

##### ACTUAL RESULTS
Running with message parameter
```
TASK [grafana : Import Grafana dashboard] *****************************************************************************************************************************************************************
task path: /home/cathal/Documents/cathal/ansible/roles/grafana/tasks/main.yml:34
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: cathal
<127.0.0.1> EXEC /bin/sh -c 'echo ~cathal && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/cathal/.ansible/tmp `"&& mkdir /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887 && echo ansible-tmp-1597066239.9266064-20361-170759125121887="` echo /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887 `" ) && sleep 0'
Using module file /home/cathal/.local/lib/python3.8/site-packages/ansible/modules/monitoring/grafana_dashboard.py
<127.0.0.1> PUT /home/cathal/.ansible/tmp/ansible-local-19994mfjg0pmx/tmp3_gs80tc TO /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/ /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=rvswrwbovrvqlffdiopbfxysqmdjclhs] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-rvswrwbovrvqlffdiopbfxysqmdjclhs ; /usr/bin/python3 /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py", line 102, in <module>
    _ansiballz_main()
  File "/home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.monitoring.grafana_dashboard', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/modules/monitoring/grafana_dashboard.py", line 450, in <module>
  File "/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/modules/monitoring/grafana_dashboard.py", line 403, in main
  File "/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/module_utils/basic.py", line 696, in __init__
  File "/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/module_utils/basic.py", line 1970, in _log_invocation
  File "/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/module_utils/basic.py", line 1927, in log
TypeError: send() got multiple values for keyword argument 'MESSAGE'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/cathal/.ansible/tmp/ansible-tmp-1597066239.9266064-20361-170759125121887/AnsiballZ_grafana_dashboard.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.monitoring.grafana_dashboard', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/modules/monitoring/grafana_dashboard.py\", line 450, in <module>\n  File \"/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/modules/monitoring/grafana_dashboard.py\", line 403, in main\n  File \"/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/module_utils/basic.py\", line 696, in __init__\n  File \"/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/module_utils/basic.py\", line 1970, in _log_invocation\n  File \"/tmp/ansible_grafana_dashboard_payload_8i5iehpr/ansible_grafana_dashboard_payload.zip/ansible/module_utils/basic.py\", line 1927, in log\nTypeError: send() got multiple values for keyword argument 'MESSAGE'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=6    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  

```

Running with commit_message parameter
```
ASK [grafana : Import Grafana dashboard] *****************************************************************************************************************************************************************
task path: /home/cathal/Documents/cathal/ansible/roles/grafana/tasks/main.yml:34
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: cathal
<127.0.0.1> EXEC /bin/sh -c 'echo ~cathal && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/cathal/.ansible/tmp `"&& mkdir /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330 && echo ansible-tmp-1597066529.3230932-20786-239862316296330="` echo /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330 `" ) && sleep 0'
Using module file /home/cathal/.local/lib/python3.8/site-packages/ansible/modules/monitoring/grafana_dashboard.py
<127.0.0.1> PUT /home/cathal/.ansible/tmp/ansible-local-20482rprkes19/tmp6_givsuh TO /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330/AnsiballZ_grafana_dashboard.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330/ /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330/AnsiballZ_grafana_dashboard.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=dzkjcrukiewoohpnpcpuxskjeyoukxcd] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-dzkjcrukiewoohpnpcpuxskjeyoukxcd ; /usr/bin/python3 /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330/AnsiballZ_grafana_dashboard.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/cathal/.ansible/tmp/ansible-tmp-1597066529.3230932-20786-239862316296330/ > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commit_message": "Update by Ansible",
            "grafana_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "grafana_url": "http://localhost:3000",
            "grafana_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "overwrite": true,
            "path": "files/dashboards/grafana.json",
            "state": "present",
            "url": "http://localhost:3000",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Unsupported parameters for (grafana_dashboard) module: commit_message Supported parameters include: client_cert, client_key, grafana_api_key, message, org_id, overwrite, path, slug, state, uid, url, url_password, url_username, use_proxy, validate_certs"
}

PLAY RECAP ************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=6    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.grafana.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
