### ISSUE TITLE
Issues installing 1.5.5 (latest) on Ubuntu 13

### ISSUE THREAD

**Issue by AntelopeSalad** [ansible/ansible#7207]
##### Issue Type:

Documentation Report
##### Ansible Version:

N/A
##### Environment:

Ubuntu 13.10
##### Summary:

The installation instructions on http://docs.ansible.com/intro_installation.html are not accurate. I could not install 1.5.5 through the apt ppa because it only had 1.5.4 after 1.5.5 has been released for over 11 days at the time of this ticket.
##### Steps To Reproduce:

`sudo pip install ansible`
##### Expected Results:

`expected ansible to be installed`
##### Actual Results:

```
$ sudo pip install ansible
Downloading/unpacking ansible
  Downloading ansible-1.5.5.tar.gz (543kB): 543kB downloaded
  Running setup.py (path:/tmp/pip_build_root/ansible/setup.py) egg_info for package ansible
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/ansible/setup.py", line 12, in <module>
        from ansible.constants import DEFAULT_MODULE_PATH
      File "/tmp/pip_build_root/ansible/lib/ansible/constants.py", line 21, in <module>
        import ConfigParser
    ImportError: No module named 'ConfigParser'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/ansible/setup.py", line 12, in <module>

    from ansible.constants import DEFAULT_MODULE_PATH

  File "/tmp/pip_build_root/ansible/lib/ansible/constants.py", line 21, in <module>

    import ConfigParser

ImportError: No module named 'ConfigParser'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/ansible
Storing debug log for failure in /home/nick/.pip/pip.log






$ cat ~/.pip/pip.log 
------------------------------------------------------------
/usr/local/bin/pip run on Tue Apr 29 08:15:23 2014
Downloading/unpacking ansible
  Getting page https://pypi.python.org/simple/ansible/
  URLs to search for versions for ansible:
  * https://pypi.python.org/simple/ansible/
  Analyzing links from page https://pypi.python.org/simple/ansible/
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.0.tar.gz#md5=03d9ebc5a830642bd25f0eef6382a27c (from https://pypi.python.org/simple/ansible/), version: 1.0
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.1.tar.gz#md5=29059e7738212392d7c23db8c8f91019 (from https://pypi.python.org/simple/ansible/), version: 1.1
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.2.1.tar.gz#md5=486537f718b778cf36a8dba8e7a8c8a8 (from https://pypi.python.org/simple/ansible/), version: 1.2.1
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.2.2.tar.gz#md5=f5dce3d4bf61cbcd2b097c5874431f29 (from https://pypi.python.org/simple/ansible/), version: 1.2.2
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.2.3.tar.gz#md5=61aef50c636bb1b4d356a32ddae30884 (from https://pypi.python.org/simple/ansible/), version: 1.2.3
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.2.tar.gz#md5=e1924c5f75a06dc49664e0e9b8f81fa0 (from https://pypi.python.org/simple/ansible/), version: 1.2
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.3.0.tar.gz#md5=0a36fe36226fa2c2bd86dc831990bcd4 (from https://pypi.python.org/simple/ansible/), version: 1.3.0
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.3.1.tar.gz#md5=e054d28fa75372e9b26a6c3b265811fb (from https://pypi.python.org/simple/ansible/), version: 1.3.1
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.3.2.tar.gz#md5=da7b37227e69884db4ae3304e47dbab0 (from https://pypi.python.org/simple/ansible/), version: 1.3.2
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.3.3.tar.gz#md5=cbbc7818a89076e8ece54be1650008f0 (from https://pypi.python.org/simple/ansible/), version: 1.3.3
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.3.4.tar.gz#md5=d3cb1bfcaf685f5de14a57c113d769c3 (from https://pypi.python.org/simple/ansible/), version: 1.3.4
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.4.1.tar.gz#md5=f6773403ab29ae5e7f4049abc4aea1d2 (from https://pypi.python.org/simple/ansible/), version: 1.4.1
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.4.2.tar.gz#md5=874ca10061568821652a3a5f7c462ee8 (from https://pypi.python.org/simple/ansible/), version: 1.4.2
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.4.3.tar.gz#md5=e9c78a97204607e09d199e7259060938 (from https://pypi.python.org/simple/ansible/), version: 1.4.3
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.4.4.tar.gz#md5=305fefa24fa4f6c5a1d69287060b9b3d (from https://pypi.python.org/simple/ansible/), version: 1.4.4
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.4.5.tar.gz#md5=87d3d679e695d10cee35a204e04eb6a8 (from https://pypi.python.org/simple/ansible/), version: 1.4.5
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.4.tar.gz#md5=2e4112c568ed219462ec806c92d1e12c (from https://pypi.python.org/simple/ansible/), version: 1.4
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.5.1.tar.gz#md5=9bc644193eb4000986666835e98257a9 (from https://pypi.python.org/simple/ansible/), version: 1.5.1
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.5.2.tar.gz#md5=26c402f9cf84de72fb314b7869e0ba8d (from https://pypi.python.org/simple/ansible/), version: 1.5.2
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.5.3.tar.gz#md5=9fe87a1f16da6732d9c24eb817f1ec18 (from https://pypi.python.org/simple/ansible/), version: 1.5.3
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.5.4.tar.gz#md5=03e8c198ca599f636573fa39f2dad7e9 (from https://pypi.python.org/simple/ansible/), version: 1.5.4
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.5.5.tar.gz#md5=de02d1109d8b1d04a74f082b7ea2cb15 (from https://pypi.python.org/simple/ansible/), version: 1.5.5
    Found link https://pypi.python.org/packages/source/a/ansible/ansible-1.5.tar.gz#md5=cbdd30fdb93326bd3227de6f303f0d6c (from https://pypi.python.org/simple/ansible/), version: 1.5
  Using version 1.5.5 (newest of versions: 1.5.5, 1.5.4, 1.5.3, 1.5.2, 1.5.1, 1.5, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1, 1.0)
  Downloading from URL https://pypi.python.org/packages/source/a/ansible/ansible-1.5.5.tar.gz#md5=de02d1109d8b1d04a74f082b7ea2cb15 (from https://pypi.python.org/simple/ansible/)
  Running setup.py (path:/tmp/pip_build_root/ansible/setup.py) egg_info for package ansible
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/ansible/setup.py", line 12, in <module>
        from ansible.constants import DEFAULT_MODULE_PATH
      File "/tmp/pip_build_root/ansible/lib/ansible/constants.py", line 21, in <module>
        import ConfigParser
    ImportError: No module named 'ConfigParser'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/ansible/setup.py", line 12, in <module>

    from ansible.constants import DEFAULT_MODULE_PATH

  File "/tmp/pip_build_root/ansible/lib/ansible/constants.py", line 21, in <module>

    import ConfigParser

ImportError: No module named 'ConfigParser'

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/ansible
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.3/dist-packages/pip/commands/install.py", line 274, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python3.3/dist-packages/pip/req.py", line 1215, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/local/lib/python3.3/dist-packages/pip/req.py", line 321, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.3/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/ansible
```
##### Eventual solution that is not listed anywhere on the official site

I asked on IRC and someone pointed me to:
https://github.com/ginas/ginas/blob/master/contrib/bootstrap-ansible.sh

After `chmod +x`ing the file and running it I was able to install any version of ansible I wanted without issues.

**Comment by mpdehaan** [comment]
Nobody needs that bootstrapping script.  Totally not needed.

Not sure what happened to you about Config Parser -- your system python seems damaged to me.  Were you trying python 3 or something?

Ansible runs on Python 2.x.

(The PPA itself is community maintained, which we need to host our own soon.   You can definitely get the latest in pip though)

**Comment by AntelopeSalad** [comment]
It seems like I was using python 3, that's the version that was on my system and associated to pip which I later verified with `pip --version`, it was pointing to python 3.3. `python --version` reports 2.7.5+ tho.

**Comment by mpdehaan** [comment]
PPA is not maintained by us, but now contains 1.6.

We are going to be starting our own PPA in the near future.
