### ISSUE TITLE
pkg_resources.DistributionNotFound: ansible

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#7219]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 3416c33026b728fe87050be982c548e82a890756)
##### Environment:

Debian jessie/sid
##### Summary:

Ansible does not load dependencies properly.
##### Steps To Reproduce:

Run ansible-playbook
##### Expected Results:

Ansible works.
##### Actual Results:

```
Traceback (most recent call last):
  File "/usr/local/ansible/bin/ansible-playbook", line 22, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ansible
```

**Comment by jimi-c** [comment]
I have corrected this already, so a re-pull of your repo should get you past this now. Thanks!

**Comment by ghost** [comment]
similar error here, installed from ubuntu aptt-get after failing with source code installation at the pip stage
