### ISSUE TITLE
recursive copy fails when setting directory attributes

### ISSUE THREAD

**Issue by tksmd** [ansible/ansible#7244]
I'll send a pull request later on.
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.5 or later  ( affected by cf4a6b39ccec3108d501897a7fd8fd1b943c82d9 )
##### Environment:

local: OS X 10.9, remote: Amazon Linux
##### Summary:

Copying directory recursively with setting some directory attributes fails with "No such file or directory" error when the directory has multi-level subdirectory hierarchy and one of its children only contains subdirectory.
##### Steps To Reproduce:

Suppose that the following directory structure.

```
$ tree 
.
├── foo.txt
└── subdir
    ├── bar.txt
    └── subdir2
        ├── baz.txt
        └── subdir3
            └── subdir4
                └── qux.txt
```

Then try to copy subdir to the target directory like this.

```
copy: src=subdir dest={{output_subdir}} directory_mode=0700
```
##### Expected Results:

"subdir" will be successfully copied to the target.
##### Actual Results:

The task fails with the error like this:

```
failed: [testhost] => {"failed": true, "item": "", "md5sum": "d85b1213473c2fd7c2045020a6b9c62b", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/someda/.ansible/tmp/ansible-tmp-1398961268.91-150413139399017/copy", line 1405, in <module>
    main()
  File "/Users/someda/.ansible/tmp/ansible-tmp-1398961268.91-150413139399017/copy", line 179, in main
    adjust_recursive_directory_permissions(pre_existing_dir, new_directory_list, module, directory_args, changed)
  File "/Users/someda/.ansible/tmp/ansible-tmp-1398961268.91-150413139399017/copy", line 127, in adjust_recursive_directory_permissions
    changed = module.set_directory_attributes_if_different(directory_args, changed)
  File "/Users/someda/.ansible/tmp/ansible-tmp-1398961268.91-150413139399017/copy", line 750, in set_directory_attributes_if_different
    return self.set_fs_attributes_if_different(file_args, changed)
  File "/Users/someda/.ansible/tmp/ansible-tmp-1398961268.91-150413139399017/copy", line 745, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/Users/someda/.ansible/tmp/ansible-tmp-1398961268.91-150413139399017/copy", line 703, in set_mode_if_different
    st = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/Users/someda/ansible_testing/sub/subdir/subdir2/subdir4'
```

**Comment by tksmd** [comment]
I've created a pull request #7245.

**Comment by jimi-c** [comment]
Thanks!
