### ISSUE TITLE
Yum/DNF module does not capture and return transaction failure

### ISSUE THREAD

**Issue by ebarrere** [ansible/ansible#72651]
##### SUMMARY
Running the playbook below returns "changed" though the Yum/DNF transaction failed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Yum

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.10.post0
  config file = None
  configured module search path = [u'/opt/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/source/lib/ansible
  executable location = /opt/ansible/source/bin/ansible
  python version = 2.7.9 (default, Nov 18 2015, 13:07:23) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```
The issue also occurs with the latest development build at the time of this posting.

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=10
CACHE_PLUGIN(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = ./cache
CACHE_PLUGIN_TIMEOUT(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = [u'/home/elliott.barrere-a/dv-ansible/inventory/production']
DEFAULT_LOG_PATH(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = Ansible managed from {host}
DEFAULT_MODULE_PATH(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = [u'/home/elliott.barrere-a/dv-ansible/library']
DEFAULT_POLL_INTERVAL(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 7
DEFAULT_ROLES_PATH(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = [u'/home/elliott.barrere-a/dv-ansible/roles']
DEFAULT_TIMEOUT(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = /home/elliott.barrere-a/dv-ansible/open_the_vault.sh
DISPLAY_SKIPPED_HOSTS(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = 100
RETRY_FILES_SAVE_PATH(/home/elliott.barrere-a/dv-ansible/ansible.cfg) = /home/elliott.barrere-a/.ansible-retry
```

##### OS / ENVIRONMENT

CentOS Linux release 8.2.2004 (Core) 

##### STEPS TO REPRODUCE

```yaml
- hosts: linux

  tasks:
    - name: install pbis
      yum: name='pbis-open-9.1.0-551'
      become: yes
```

The above returns no error, though the package is not installed due to a missing dependency found during script execution.

##### EXPECTED RESULTS

The above should FAIL if the package is not installed

##### ACTUAL RESULTS

The module returns "changed" as if everything was okay.

```paste below

ansible-playbook playbooks/linux/test_pbis.yaml -l test -e 'ansible_user="{{linux_default_root_user}}" ansible_password="{{linux_default_root_password}}"'
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source
of code and can become unstable at any point.

PLAY [linux, vagrant_linux, test_web, centos_templates] ***********************************************************************************************************************************************************************

TASK [install pbis] ***********************************************************************************************************************************************************************************************************
changed: [den3jmisc02]

PLAY RECAP ********************************************************************************************************************************************************************************************************************
test                : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
Testing if the package was truly installed:
```
$ ansible -m shell -e 'ansible_user="{{linux_default_root_user}}" ansible_password="{{linux_default_root_password}}"' -a 'rpm -qa pbis-open' test
[WARNING]: Consider using the yum, dnf or zypper module rather than running 'rpm'.  If you need to use command because yum, dnf or zypper is insufficient you can add 'warn: false' to this command task or set
'command_warnings=False' in ansible.cfg to get rid of this message.
test | CHANGED | rc=0 >>
```

Here is the command output when run locally on the host:

```
[root@test ~]# dnf install -y pbis-open-9.1.0-551
Last metadata expiration check: 0:04:21 ago on Tue 17 Nov 2020 02:05:58 PM MST.
Dependencies resolved.
===============================================================================================================================================================================================================================
 Package                                                Architecture                                        Version                                                   Repository                                          Size
===============================================================================================================================================================================================================================
Installing:
 pbis-open                                              x86_64                                              9.1.0-551                                                 pbiso                                               14 M

Transaction Summary
===============================================================================================================================================================================================================================
Install  1 Package

Total size: 14 M
Installed size: 40 M
Downloading Packages:
[SKIPPED] pbis-open-9.1.0-551.x86_64.rpm: Already downloaded                                                                                                                                                                  
warning: /var/cache/dnf/pbiso-7802c5d179dc88d5/packages/pbis-open-9.1.0-551.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID c9ceecef: NOKEY
PBISO- local packages for x86_64                                                                                                                                                                11 kB/s | 1.4 kB     00:00    
Importing GPG key 0xC9CEECEF:
 Userid     : "BeyondTrust (PowerBroker Identity Services Open Project) <openproject@beyondtrust.com>"
 Fingerprint: BE7F F72A 6B7C 8A9F AE06 1F4F 2E52 CD89 C9CE ECEF
 From       : https://repo.pbis.beyondtrust.com/yum/RPM-GPG-KEY-pbis-1024
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                       1/1 
  Running scriptlet: pbis-open-9.1.0-551.x86_64                                                                                                                                                                            1/1 
BeyondTrust AD Bridge Open requires library libnsl.so.1; please install libnsl.so.1 before installing AD Bridge.

error: %prein(pbis-open-9.1.0-551.x86_64) scriptlet failed, exit status 1

Error in PREIN scriptlet in rpm package pbis-open
  Verifying        : pbis-open-9.1.0-551.x86_64                                                                                                                                                                            1/1 

Failed:
  pbis-open-9.1.0-551.x86_64                                                                                                                                                                                                   

Error: Transaction failed
[root@test ~]# echo $?
1
```

The command fails and the correct RC is set.

**Comment by ebarrere** [comment]
Oh, here are the relevant portions of the dnf log. Through ansible:

```
2020-11-17T21:36:34Z INFO --- logging initialized ---
2020-11-17T21:36:34Z DEBUG Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
2020-11-17T21:36:34Z DEBUG User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
2020-11-17T21:36:34Z DEBUG repo: using cache for: AppStream
2020-11-17T21:36:34Z DEBUG AppStream: using metadata from Fri 30 Oct 2020 11:58:38 AM MDT.
2020-11-17T21:36:34Z DEBUG repo: using cache for: BaseOS
2020-11-17T21:36:34Z DEBUG BaseOS: using metadata from Fri 30 Oct 2020 11:58:33 AM MDT.
2020-11-17T21:36:34Z DEBUG repo: using cache for: extras
2020-11-17T21:36:34Z DEBUG extras: using metadata from Thu 12 Nov 2020 06:42:22 AM MST.
2020-11-17T21:36:34Z DEBUG repo: using cache for: dv-localextras
2020-11-17T21:36:34Z DEBUG dv-localextras: using metadata from Fri 13 Nov 2020 04:30:26 PM MST.
2020-11-17T21:36:34Z DEBUG repo: using cache for: pbiso
2020-11-17T21:36:34Z DEBUG pbiso: using metadata from Wed 19 Aug 2020 11:39:26 AM MDT.
2020-11-17T21:36:34Z INFO Last metadata expiration check: 0:17:59 ago on Tue 17 Nov 2020 02:18:35 PM MST.
2020-11-17T21:36:34Z DDEBUG timer: sack setup: 501 ms
2020-11-17T21:36:34Z DEBUG Completion plugin: Generating completion cache...
2020-11-17T21:36:34Z DDEBUG timer: depsolve: 95 ms
2020-11-17T21:36:34Z INFO Running transaction check
2020-11-17T21:36:34Z INFO Transaction check succeeded.
2020-11-17T21:36:34Z INFO Running transaction test
2020-11-17T21:36:35Z INFO Transaction test succeeded.
2020-11-17T21:36:35Z DDEBUG timer: transaction test: 108 ms
2020-11-17T21:36:35Z INFO Running transaction
2020-11-17T21:36:35Z DDEBUG RPM transaction start.
2020-11-17T21:36:35Z DDEBUG RPM transaction over.
2020-11-17T21:36:35Z DEBUG Errors occurred during transaction.
2020-11-17T21:36:35Z DDEBUG timer: verify transaction: 184 ms
2020-11-17T21:36:35Z DDEBUG timer: transaction: 336 ms
2020-11-17T21:36:35Z DEBUG Completion plugin: Generating completion cache...
```

Run directly with `dnf`:

```
2020-11-17T21:16:39Z INFO --- logging initialized ---
2020-11-17T21:16:39Z DDEBUG timer: config: 3 ms
2020-11-17T21:16:39Z DEBUG Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
2020-11-17T21:16:39Z DEBUG YUM version: 4.2.17
2020-11-17T21:16:39Z DDEBUG Command: dnf install -y pbis-open-9.1.0-551 
2020-11-17T21:16:39Z DDEBUG Installroot: /
2020-11-17T21:16:39Z DDEBUG Releasever: 8
2020-11-17T21:16:39Z DEBUG cachedir: /var/cache/dnf
2020-11-17T21:16:39Z DDEBUG Base command: install
2020-11-17T21:16:39Z DDEBUG Extra commands: ['install', '-y', 'pbis-open-9.1.0-551']
2020-11-17T21:16:39Z DEBUG User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
2020-11-17T21:16:39Z DEBUG repo: using cache for: AppStream
2020-11-17T21:16:39Z DEBUG AppStream: using metadata from Fri 30 Oct 2020 11:58:38 AM MDT.
2020-11-17T21:16:39Z DEBUG repo: using cache for: BaseOS
2020-11-17T21:16:39Z DEBUG BaseOS: using metadata from Fri 30 Oct 2020 11:58:33 AM MDT.
2020-11-17T21:16:39Z DEBUG repo: using cache for: extras
2020-11-17T21:16:39Z DEBUG extras: using metadata from Thu 12 Nov 2020 06:42:22 AM MST.
2020-11-17T21:16:39Z DEBUG repo: using cache for: dv-localextras
2020-11-17T21:16:39Z DEBUG dv-localextras: using metadata from Fri 13 Nov 2020 04:30:26 PM MST.
2020-11-17T21:16:39Z DEBUG repo: using cache for: pbiso
2020-11-17T21:16:39Z DEBUG pbiso: using metadata from Wed 19 Aug 2020 11:39:26 AM MDT.
2020-11-17T21:16:39Z INFO Last metadata expiration check: 0:03:23 ago on Tue 17 Nov 2020 02:13:16 PM MST.
2020-11-17T21:16:39Z DDEBUG timer: sack setup: 531 ms
2020-11-17T21:16:39Z DEBUG Completion plugin: Generating completion cache...
2020-11-17T21:16:40Z DEBUG --> Starting dependency resolution
2020-11-17T21:16:40Z DEBUG ---> Package pbis-open.x86_64 9.1.0-551 will be installed
2020-11-17T21:16:40Z DEBUG --> Finished dependency resolution
2020-11-17T21:16:40Z DDEBUG timer: depsolve: 100 ms
2020-11-17T21:16:40Z INFO Dependencies resolved.
2020-11-17T21:16:40Z INFO ===============================================================================================================================================================================================================================
 Package                                                Architecture                                        Version                                                   Repository                                          Size
===============================================================================================================================================================================================================================
Installing:
 pbis-open                                              x86_64                                              9.1.0-551                                                 pbiso                                               14 M

Transaction Summary
===============================================================================================================================================================================================================================
Install  1 Package

2020-11-17T21:16:40Z INFO Total size: 14 M
2020-11-17T21:16:40Z INFO Installed size: 40 M
2020-11-17T21:16:40Z INFO Downloading Packages:
2020-11-17T21:16:40Z INFO Running transaction check
2020-11-17T21:16:40Z INFO Transaction check succeeded.
2020-11-17T21:16:40Z INFO Running transaction test
2020-11-17T21:16:40Z INFO Transaction test succeeded.
2020-11-17T21:16:40Z DDEBUG timer: transaction test: 109 ms
2020-11-17T21:16:40Z INFO Running transaction
2020-11-17T21:16:40Z DDEBUG RPM transaction start.
2020-11-17T21:16:40Z DDEBUG RPM transaction over.
2020-11-17T21:16:40Z DEBUG Errors occurred during transaction.
2020-11-17T21:16:40Z DDEBUG timer: verify transaction: 181 ms
2020-11-17T21:16:40Z DDEBUG timer: transaction: 332 ms
2020-11-17T21:16:40Z DEBUG Completion plugin: Generating completion cache...
2020-11-17T21:16:40Z INFO 
Failed:
  pbis-open-9.1.0-551.x86_64                                                                                                                                                                                                   

2020-11-17T21:16:40Z DDEBUG Cleaning up.
2020-11-17T21:16:40Z DDEBUG /var/cache/dnf/pbiso-7802c5d179dc88d5/packages/pbis-open-9.1.0-551.x86_64.rpm removed
2020-11-17T21:16:40Z SUBDEBUG 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 65, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 98, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 122, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 166, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.6/site-packages/dnf/cli/cli.py", line 257, in do_transaction
    raise dnf.exceptions.Error(_('Transaction failed'))
dnf.exceptions.Error: Transaction failed
2020-11-17T21:16:40Z CRITICAL Error: Transaction failed
```
