### ISSUE TITLE
SyntaxError when try to install ansible

### ISSUE THREAD

**Issue by Jorayala** [ansible/ansible#73407]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

Hi, could you please help me with this:

XXXX@XXXX-M-JFTV ~ % sudo easy_install pip
Password:
Searching for pip
Best match: pip 21.0
Processing pip-21.0-py2.7.egg
pip 21.0 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /Library/Python/2.7/site-packages/pip-21.0-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip

XXXX@XXXX-M-JFTV ~ % sudo pip install ansible
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.0', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
XXXX@XXXX-M-JFTV ~ % python3 --version       
Python 3.8.2

Thanks

**Comment by sivel** [comment]
The `pip` you are using is installed with python2.7, and `pip` recently dropped Python 2 support.

The traceback you are getting is a result of that.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
