### ISSUE TITLE
Git module fails to clone repository if sudo_user and key_file are used together.

### ISSUE THREAD

**Issue by alanwj** [ansible/ansible#7375]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 14.04 LTS  (on both ends)
##### Summary:

When using the sudo, sudo_user, and key_file parameters together, the git module cannot clone a repository.
##### Steps To Reproduce:
1. Create a private github git  repository and configure a deploy key.
2. Create a user 'testuser' on one of your hosts, and put the deploy key in his home directory.
3. Run a playbook like the following (substitue the correct repository):

```

---
- hosts: all
  gather_facts: false
  tasks:
  - name: Clone project from github
    sudo: yes
    sudo_user: testuser
    git: repo=git@github.com:myuser/myrepo.git
         depth=1
         dest=/home/testuser/myrepo
         accept_hostkey=yes
         key_file=/home/testuser/deploy_key
```
##### Expected Results:

The git repository should be successfully cloned.
##### Actual Results:

Ansible fails with an error like (some host names redacted):

```
<redacted-host> ESTABLISH CONNECTION FOR USER: ubuntu
<redacted-host> REMOTE_MODULE git repo=repo-redacted depth=1 dest=/home/testuser/myrepo accept_hostkey=yes key_file=/home/testuser/deploy_key
<redacted-host> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/awj/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', 'redacted-host', "/bin/sh -c 'mkdir -p /tmp/ansible-tmp-1399962156.25-157957786275211 && chmod a+rx /tmp/ansible-tmp-1399962156.25-157957786275211 && echo /tmp/ansible-tmp-1399962156.25-157957786275211'"]
<redacted-host> PUT /tmp/tmph8fYKy TO /tmp/ansible-tmp-1399962156.25-157957786275211/git
<redacted-host> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/awj/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', 'redacted-host', "/bin/sh -c 'chmod a+r /tmp/ansible-tmp-1399962156.25-157957786275211/git'"]
<redacted-host> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/awj/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', 'redacted-host', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=owhnxdylojloiebvvqtllhnstyfmryjb] password: " -u testuser /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-owhnxdylojloiebvvqtllhnstyfmryjb; LC_CTYPE=C LANG=C /usr/bin/python /tmp/ansible-tmp-1399962156.25-157957786275211/git\'"\'"\'\'']
<redacted-host> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/awj/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', 'redacted-host', "/bin/sh -c 'rm -rf /tmp/ansible-tmp-1399962156.25-157957786275211/ >/dev/null 2>&1'"]
fatal: [redacted-host] => failed to parse: SUDO-SUCCESS-owhnxdylojloiebvvqtllhnstyfmryjb
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1399962156.25-157957786275211/git", line 1911, in <module>
    main()
  File "/tmp/ansible-tmp-1399962156.25-157957786275211/git", line 503, in main
    ssh_wrapper = write_ssh_wrapper()
  File "/tmp/ansible-tmp-1399962156.25-157957786275211/git", line 184, in write_ssh_wrapper
    fd, wrapper_path = tempfile.mkstemp(prefix=module_dir + '/')
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/tmp/ansible-tmp-1399962156.25-157957786275211/NYliMM
```

**Comment by jimi-c** [comment]
I have a preliminary patch to address this, the one downside is that currently the ssh_wrapper script is not cleaned up if the module execution fails:

<pre>
diff --git a/library/source_control/git b/library/source_control/git
index 6af4bd7..d51d86f 100644
--- a/library/source_control/git
+++ b/library/source_control/git
@@ -180,8 +180,7 @@ def get_submodule_update_params(module, git_path, cwd):
     return params
 
 def write_ssh_wrapper():
-    module_dir = get_module_path()
-    fd, wrapper_path = tempfile.mkstemp(prefix=module_dir + '/')
+    fd, wrapper_path = tempfile.mkstemp()
     fh = os.fdopen(fd, 'w+b')
     template = """#!/bin/sh
 if [ -z "$GIT_SSH_OPTS" ]; then
</pre>

**Comment by jimi-c** [comment]
I've committed the above fix, which should resolve this issue for you. If you continue having problems related to this issue, please let us know. Thanks!
