### ISSUE TITLE
Implement compatibility with `resolvelib` v0.7.0+

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible#74569]
### Summary

A new release of `resolvelib` has been published about 3 weeks ago. It contains breaking changes to the provider interface.
We need to make the necessary changes to be able to increase the upper boundary of the runtime dependency version.

Refs:
* https://github.com/sarugaku/resolvelib/blob/master/CHANGELOG.rst#070-2021-04-13
* https://github.com/sarugaku/resolvelib/issues/74

### Issue Type

Bug Report

### Component Name

galaxy

### Ansible Version

devel

### Configuration

N/A

### OS / Environment

N/A

### Steps to Reproduce

Bump the `resolvelib` dependency to `>=0.7.0`

### Expected Results

It should work seamlessly.

### Actual Results

It wouldn't work because of a changed interface.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by webknjaz** [comment]
@s-hertel @jborean93 FYI

**Comment by janesmae** [comment]
Freshly installed macbook, receiving errors now.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ansible-core 2.11.3 requires resolvelib<0.6.0,>=0.5.3, but you have resolvelib 0.7.1 which is incompatible.
```

**Comment by Riccardo1976** [comment]
Only ever found this as a problem when using ansible galaxy to install collections.
Often we use virtualenv to install and _update_ ansible.
Bij running `pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U` , you will end up updating resolvelib.
Notably, when just installing/updating ansible it now specifies which resolvelib it wants:
```
  Downloading ansible-4.8.0.tar.gz (36.1 MB)
 Requirement already satisfied: resolvelib<0.6.0,>=0.5.3 in  #<------
```

But afterwards pip will update resolvelib.
Using:
```
pip uninstall resolvelib
pip install resolvelib==0.5.5
```
Will resolve the issue.

But it would be better to just have galaxy work better with the newer resolvelib versions.

**Comment by ssbarnea** [comment]
The fact that ansible-core keeps down the version of resolve-lib is becoming a more pressing issue as it will soon cause major impossibilities without other tools that might require newer ons.

Any chance to get some attention of this?

**Comment by Xuxe** [comment]
I guess it's the point where people installing it by pip getting issues, i can't install ansible-5.6.0 on Debian 11 with Python 3.9 (venv): 

Not sure if it's really related to resolvelib, but i think so based on the stack traces. Otherwise i will rise a new issue. 

Python 3.9.2
pip 22.0.4 from /tmp/venv/lib/python3.9/site-packages/pip (python 3.9)

Pip 20.3.4:
```
Collecting ansible
  Using cached ansible-5.6.0.tar.gz (35.5 MB)
Collecting ansible-core~=2.12.4
  Using cached ansible-core-2.12.4.tar.gz (7.8 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'ansible-core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 346, in run
    requirement_set = resolver.resolve(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    self._result = resolver.resolve(
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 199, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in __bool__
    return any(self)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 239, in iter_index_candidates
    candidate = self._make_candidate_from_link(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 296, in __init__
    super(LinkCandidate, self).__init__(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 307, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 503, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 263, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py", line 270, in unpack_file
    untar_file(filename, location)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py", line 233, in untar_file
    with open(path, 'wb') as destfp:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 137-140: ordinal not in range(256)
```

Pip 22.0.4:
```
Collecting ansible
  Using cached ansible-5.6.0.tar.gz (35.5 MB)
  Preparing metadata (setup.py) ... done
Collecting ansible-core~=2.12.4
  Using cached ansible-core-2.12.4.tar.gz (7.8 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/tmp/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    super().__init__(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 224, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py", line 247, in unpack_file
    untar_file(filename, location)
  File "/tmp/venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py", line 218, in untar_file
    with open(path, "wb") as destfp:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 137-140: ordinal not in range(256)
```

**Comment by MarkusTeufelberger** [comment]
The workaround to get an actually working installation is btw to run `apt install --no-install-recommends ansible-core python3-resolvelib=0.5.4-1ppa~jammy`
