### ISSUE TITLE
hostname module (devel) - KeyError: 'DebianStrategy' with `use: debian`

### ISSUE THREAD

**Issue by relrod** [ansible/ansible#76124]
### Summary

The documentation says that `debian` is a valid use for the hostname module `use` parameter, but when attempting to use it, a `KeyError` is thrown.

Likely introduced in 502270c804c33d3bc963930dc85e0f4ca359674d and possibly just needs a docs fix.

```
Traceback (most recent call last):
  File "/home/pi/.ansible/tmp/ansible-tmp-1634987643.6837337-31154-42761744967868/AnsiballZ_hostname.py", line 107, in <module>
    _ansiballz_main()
  File "/home/pi/.ansible/tmp/ansible-tmp-1634987643.6837337-31154-42761744967868/AnsiballZ_hostname.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/pi/.ansible/tmp/ansible-tmp-1634987643.6837337-31154-42761744967868/AnsiballZ_hostname.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hostname_payload_1ou9ee4b/ansible_hostname_payload.zip/ansible/modules/hostname.py", line 983, in <module>
  File "/tmp/ansible_hostname_payload_1ou9ee4b/ansible_hostname_payload.zip/ansible/modules/hostname.py", line 952, in main
  File "/tmp/ansible_hostname_payload_1ou9ee4b/ansible_hostname_payload.zip/ansible/modules/hostname.py", line 162, in __init__
KeyError: 'DebianStrategy'
```

### Issue Type

Bug Report

### Component Name

hostname

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0.dev0] (devel b4cbe1adcf) last updated 2021/10/23 06:13:48 (GMT -500)
  config file = None
  configured module search path = ['/nvme/gentoo/rick/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nvme/gentoo/rick/dev/ansible/ansible/lib/ansible
  ansible collection location = /nvme/gentoo/rick/.ansible/collections:/usr/share/ansible/collections
  executable location = /nvme/gentoo/rick/dev/ansible/ansible/bin/ansible
  python version = 3.8.9 (default, May 27 2021, 19:05:33) [GCC 10.2.0]
  jinja version = 2.11.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

ansible devel, gentoo controller, raspberry pi OS remote node

### Steps to Reproduce

```yaml (paste below)
- name: Set hostname
  hostname:
    use: debian
    name: foo
```

### Expected Results

No traceback

### Actual Results

```console
Traceback as above.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by byque** [comment]
I confirm the same problem. Got the same traceback in a Raspberry Pi with Raspberry Pi OS (Debian Buster based).

**Comment by silveraignacio** [comment]
Hi! I have the same problem using WSL2, and ansible 2.12.1

**Comment by CoolHandLuki** [comment]
I can confirm the same issue. Same setup as @byque Raspberry Pi with Raspberry Pi OS (Debian Buster based)

**Comment by jkrcma** [comment]
I can also confirm, provisioned a Rapsberry Pi with Debian Bullseye amd64.
