### ISSUE TITLE
Documented install instructions for Ubuntu does not work

### ISSUE THREAD

**Issue by dhughesbc** [ansible/ansible#76134]
### Summary

Followed the instructions at https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu installing on Ubuntu 20.4. Ran these commands per the documentation:
```
$ sudo apt update
$ sudo apt install software-properties-common
$ sudo add-apt-repository --yes --update ppa:ansible/ansible
$ sudo apt install ansible
```
When I try to run any ansible command I get this error:
```
$ ansible --version
ERROR! Unexpected Exception: No module named yaml
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 88, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 28, in <module>
    import yaml
ImportError: No module named yaml
```

### Issue Type

Documentation Report

### Component Name

ansible?

### Ansible Version

```console
$ ansible --version

$ ansible --version
ERROR! Unexpected Exception: No module named yaml
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 88, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 28, in <module>
    import yaml
ImportError: No module named yaml
```
```


### Configuration

```console
$ ansible-config dump --only-changed
 
No output
```

### OS / Environment

Ubuntu 20.4

### Additional Information

Need to improve documentation for Ubuntu 20.4

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ariordan-redhat** [comment]
I couldn't reproduce the original issue on an Ubuntu VM, but confirmed that `sudo apt remove --purge ansible` does not fully uninstall Ansible. You have to run `sudo apt autoremove` or `sudo apt remove --purge ansible-core`.

```
$ sudo apt remove --purge ansible
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  ansible-core linux-hwe-5.8-headers-5.8.0-63 python3-jinja2 python3-packaging
  python3-pyparsing python3-resolvelib sshpass
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  ansible*
```

```
$ ansible --version
ansible [core 2.11.6] 
```

```
$ sudo apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  ansible-core python3-jinja2 python3-packaging python3-pyparsing python3-resolvelib sshpass
0 upgraded, 0 newly installed, 6 to remove and 29 not upgraded.
After this operation, 6,762 kB disk space will be freed.
```

```
$ ansible --version
bash: /usr/bin/ansible: No such file or directory
```

**Comment by amott-rh** [comment]
Just looking into this, and it appears that 'apt remove ansible' removes only the ansible package, with a note that other packages were installed along with it but will not be removed:

```
# apt remove ansible
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  ansible-core python3-bcrypt python3-jmespath python3-kerberos python3-ntlm-auth python3-packaging
  python3-paramiko python3-pyparsing python3-requests-kerberos python3-requests-ntlm python3-resolvelib
  python3-winrm python3-xmltodict sshpass
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ansible
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
```

Issuing 'apt autoremove ansible' uninstalls ansible and all other unused packages that go along with it.

```
# apt autoremove ansible
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  ansible ansible-core python3-bcrypt python3-jmespath python3-kerberos python3-ntlm-auth python3-packaging
  python3-paramiko python3-pyparsing python3-requests-kerberos python3-requests-ntlm python3-resolvelib
  python3-winrm python3-xmltodict sshpass
0 upgraded, 0 newly installed, 15 to remove and 0 not upgraded.
```

This is an apt thing rather than Ansible, but perhaps a note in the install doc would help?

**Comment by samccann** [comment]
Thanks @amott-rh for the analysis and verification of the fix!

**Comment by ariordan-redhat** [comment]
Thanks, @dhughesbc, for creating the issue.
