### ISSUE TITLE
user problem with template and ioctl message (needs info)

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#7613]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
2014-05-31
##### Environment:

Mac OSX 10.9.3 managing Slackware64-14.1
##### Summary:

I'm getting errors copying templates to the destination.
##### Steps To Reproduce:

Run a simple template task, for example:

```
- name: jcc copy templates for the build
  template: >
    src=etc/profile.d/{{ item }}.j2
    dest={{ jcc_build_dir }}/{{ item }}
    owner='root' group='root' mode='0755'
    backup=no
  with_items:
    - 'JCC.csh'
    - 'JCC.sh'
```
##### Expected Results:

Expected a parsed template copy to happen.
##### Actual Results:

```
TASK: [build | jcc copy templates for the build] ****************************** 
failed: [work1] => (item=JCC.csh) => {"failed": true, "item": "JCC.csh", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1439, in <module>
  File "<stdin>", line 212, in main
  File "<stdin>", line 1254, in atomic_move
OSError: [Errno 25] Inappropriate ioctl for device

failed: [work1] => (item=JCC.sh) => {"failed": true, "item": "JCC.sh", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1439, in <module>
  File "<stdin>", line 212, in main
  File "<stdin>", line 1254, in atomic_move
OSError: [Errno 25] Inappropriate ioctl for device

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
If templates were universally damaged, I'd suspect the entirity of the internet to be arriving with pitchforks.

If you can share a complete playbook that reproduces the problem you are having, we'll look into it.

We could absolutely use more information about your environment and what is unusual about it.

**Comment by edrozenberg** [comment]
site.yaml:

```
--- 
- hosts: work
  roles:
    - build
```

roles/build/tasks/main.yaml:

```
---
- include: jcc-debug-templates.yaml
```

roles/build/tasks/jcc-debug-templates.yaml:

```
---
- name: jcc copy templates for the build
  template: >
    src=etc/profile.d/JCC.sh.j2
    dest=/usr/local/src/JCC/JCC.sh
```

templates/etc/profile.d/JCC.csh.j2:

```
#!/bin/csh
setenv JCC_JDK {{ java_home_dir }}
```

templates/etc/profile.d/JCC.sh.j2:

```
#!/bin/sh
export JCC_JDK={{ java_home_dir }}
```

**Comment by edrozenberg** [comment]
ansible-playbook site.yaml -vvvv:

```
PLAY [work] ******************************************************************* 

GATHERING FACTS *************************************************************** 
<work1> ESTABLISH CONNECTION FOR USER: root
<work1> REMOTE_MODULE setup
<work1> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/eduardr/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'work1', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python'"]
ok: [work1]

TASK: [build | jcc copy templates for the build] ****************************** 
<work1> ESTABLISH CONNECTION FOR USER: root
<work1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/eduardr/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'work1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1401554531.67-179354815039710 && echo $HOME/.ansible/tmp/ansible-tmp-1401554531.67-179354815039710'"]
<work1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/eduardr/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'work1', u'/bin/sh -c \'rc=0; [ -r "/usr/local/src/JCC/JCC.sh" ] || rc=2; [ -f "/usr/local/src/JCC/JCC.sh" ] || rc=1; [ -d "/usr/local/src/JCC/JCC.sh" ] && echo 3 && exit 0; (/usr/bin/md5sum /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/sbin/md5sum -q /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/usr/bin/digest -a md5 /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/sbin/md5 -q /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/usr/bin/md5 -n /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/bin/md5 -q /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/usr/bin/csum -h MD5 /usr/local/src/JCC/JCC.sh 2>/dev/null) || (/bin/csum -h MD5 /usr/local/src/JCC/JCC.sh 2>/dev/null) || (echo "${rc} /usr/local/src/JCC/JCC.sh")\'']
<work1> PUT /var/folders/56/gf9h271j2dq2jlrbn86rkdkc0000gp/T/tmpLvPcIp TO /root/.ansible/tmp/ansible-tmp-1401554531.67-179354815039710/source
<work1> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/eduardr/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'work1', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python; rm -rf /root/.ansible/tmp/ansible-tmp-1401554531.67-179354815039710/ >/dev/null 2>&1'"]
failed: [work1] => {"failed": true, "item": "", "parsed": false}
invalid output was: OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 31733
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 1439, in <module>
  File "<stdin>", line 212, in main
  File "<stdin>", line 1254, in atomic_move
OSError: [Errno 25] Inappropriate ioctl for device
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
```

**Comment by mpdehaan** [comment]
You will want to indent each line of YAML by four spaces so it formats ok in the GitHub editor.  Sorry about this, that's just the way it works :)

**Comment by mpdehaan** [comment]
This appears related to:

http://superuser.com/questions/698653/shared-connection-frequently-closes-when-opening-a-new-connection

In which case, it seems your control connection is being closed.

Any interesting firewall thingies in the way?   (What do you have ssh_args set to in ansible.cfg if any, and are there any settings in your SSH config?

**Comment by edrozenberg** [comment]
ansible.cfg:

```
[defaults]

# Hosts inventory file
hostfile    = hosts/hosts.ini

# User for SSH connections
remote_user = root

# Make sure not to use the cows cutesy messages
nocows=0

[ssh_connection]

# Pipelining - performance tweak
# NOTE: if set to "True" then when using “sudo:” operations you must first
# disable ‘requiretty’ in /etc/sudoers on all managed hosts.
pipelining = True
```

**Comment by edrozenberg** [comment]
Setting -

```
'pipelining = False' 
```

works fine! It's good to know it's some kind of network issue at least. I'm connecting remotely back to our office where we're running a pfSense firewall, nothing strange about the configuration as far as I know. I'll see if there are any other ssh related things I can try. It's interesting that templates are failing but not other modules, maybe something about the amount of data transmitted with templates and some of it perhaps gets cut off.

**Comment by edrozenberg** [comment]
Various keepalive tweaks on server and client side (http://www.noah.org/wiki/SSH_config) didn't make a difference. I made sure I'm not running fail2ban :). My interactive ssh login shells don't show any obvious problems typing and sending commands to the remote host. I'll try from another machine here, also a Mac, to see if I can reproduce the problem.

**Comment by edrozenberg** [comment]
Also tried a few other ansible cfg settings but they make no difference:

```
[defaults]

transport = paramiko
timeout = 30

[ssh_connection]

scp_if_ssh = True
```

The only thing that makes things work is still -

```
pipelining = False
```

**Comment by edrozenberg** [comment]
Don't know if it's related but I saw another report of a 'mux_client_read_packet' ssh error in the post 'Error after sucessful copy with sudo' - https://groups.google.com/forum/#!msg/ansible-project/a8wZfBCYsC4/_zBu0m-sHpUJ

**Comment by edrozenberg** [comment]
Attaching the verbose output for pipelining = False and pipelining = True:
https://gist.github.com/edrozenberg/a5ba8d7e49b22d5aef48

**Comment by edrozenberg** [comment]
I'm actually seeing the same issues controlling a local VM so hope to be able to narrow it down further.

**Comment by edrozenberg** [comment]
I'm not seeing the issue anymore. Don't know if it was a recent ansible 1.7 update, or the latest home-brew Python upgrade on my Macs but in any case works fine again on 1.7 latest git.

**Comment by momandine** [comment]
For the record I got a similar issue when I wrote my own ansible module and failed to include an exit message in a corner case. Somehow SSH is timing out and emitting that message, which ansible is not happy with because it only likes stdout and stderr in JSON format.
