### ISSUE TITLE
delegate_to issue with changing target

### ISSUE THREAD

**Issue by Joshi425** [ansible/ansible#76244]
### Summary

when trying to delegate a task selected by a filter from a list ansible breaks with:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: '78.47.37.115'
fatal: [78.47.145.43 -> 78.47.37.115]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
working:
```
    - name: delegate bug
      shell: echo "bla"
      delegate_to: "78.47.37.115"
```
not working:
```
    - name: delegate bug
      shell: echo "bla"
      delegate_to: "{{ groups['group'] | shuffle | difference(inventory_hostname) | first }}"
```

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 10.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/.vault_password
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = False
```

### OS / Environment
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```
### Steps to Reproduce

```yaml (paste below)
---
- hosts: group
  tasks:
    - name: delegate bug
      shell: echo "bla"
      delegate_to: "{{ groups['group'] | shuffle | difference(inventory_hostname) | first }}"
```

Inventory:
```yaml 
---
group:
  hosts:
   78.47.145.43:
   78.47.37.115:
   88.198.192.3:
```

### Expected Results

should delegate the task to a selected host

### Actual Results

```console
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 582, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/shell.py", line 25, in run
    result = command_action.run(task_vars=task_vars)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/command.py", line 26, in run
    results = merge_hash(results, self._execute_module(module_name='ansible.legacy.command', task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 1005, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 163, in _configure_module
    use_vars = task_vars.get('ansible_delegated_vars')[self._task.delegate_to]
KeyError: '88.198.192.3'
fatal: [78.47.145.43 -> 88.198.192.3]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nitzmahone** [comment]
@bcoca thinks this is working in 2.12 or 2.13, can you verify?

**Comment by Joshi425** [comment]
it looks likes its working with 2.13 thanks 🙇‍♂️
