### ISSUE TITLE
ec2_vpc module: Error when not specifying any route_tables

### ISSUE THREAD

**Issue by crashdump** [ansible/ansible#7712]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 68da542)  Date: Fri Jun 6 10:57:00 2014 +0200
##### Environment:

Running from OSX 10.9
##### Summary:

Error in module ec2_vpn when not specifying any route_tables (Required: no).
##### Steps To Reproduce:

```
- name: Create the VPC
  local_action:
    module: ec2_vpc
    state: present
    cidr_block: "10.10.0.0/16"
    internet_gateway: true
    subnets: 
       - cidr: "10.10.0.0/24"
    wait: yes
  register: vpc
```
##### Expected Results:

Creation of the VPC
##### Actual Results:

```
invalid output was: Traceback (most recent call last):
  File “(...)/ec2_vpc", line 2013, in <module>
    main()
  File "(...)/ec2_vpc", line 599, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "(...)/ec2_vpc", line 413, in create_vpc
    for rt in route_tables:
TypeError: 'NoneType' object is not iterable
```

**Comment by crashdump** [comment]
I added the following line in the module and it seems to do the job, need more testing though.

```
library/cloud/ec2_vpc:
412a413
>     if route_tables:
```

**Comment by jimi-c** [comment]
As mentioned on #7905, I believe this patch should address the issue:

<pre>
diff --git a/library/cloud/ec2_vpc b/library/cloud/ec2_vpc
index 5383f38..e161ff0 100644
--- a/library/cloud/ec2_vpc
+++ b/library/cloud/ec2_vpc
@@ -408,7 +408,7 @@ def create_vpc(module, vpc_conn):
     if route_tables and not isinstance(route_tables, list):
         module.fail_json(msg='route tables need to be a list of dictionaries')
     
-# Work through each route table and update/create to match dictionary array
+    # Work through each route table and update/create to match dictionary array
     all_route_tables = []
     for rt in route_tables:
         try:
@@ -561,11 +561,11 @@ def main():
             wait_timeout = dict(default=300),
             dns_support = dict(type='bool', default=True),
             dns_hostnames = dict(type='bool', default=True),
-            subnets = dict(type='list'),
+            subnets = dict(type='list', default=[]),
             vpc_id = dict(),
             internet_gateway = dict(type='bool', default=False),
             resource_tags = dict(type='dict'),
-            route_tables = dict(type='list'),
+            route_tables = dict(type='list', default=[]),
             state = dict(choices=['present', 'absent'], default='present'),
         )
     )
</pre>

Please let me know if this works for you.

**Comment by herbygillot** [comment]
Just ran into the exact same problem. @jimi-c: this patch works, can we get it merged?

**Comment by crashdump** [comment]
Didn't fix the issue here. I am still running into the "TypeError: 'NoneType' object is not iterable"

**Comment by crashdump** [comment]
The following does work: (add a "if route_tables:" in front of "for rt in route_tables")

```
--- ec2_vpc 2014-07-02 12:24:13.000000000 +0100
+++ /usr/local/Cellar/ansible/HEAD/share/ansible/cloud/ec2_vpc  2014-07-02 12:25:32.000000000 +0100
@@ -410,74 +410,75 @@

 # Work through each route table and update/create to match dictionary array
     all_route_tables = []
-    for rt in route_tables:
-        try:
-            new_rt = vpc_conn.create_route_table(vpc.id)
-            for route in rt['routes']:
-                route_kwargs = {}
-                if route['gw'] == 'igw':
-                    if not internet_gateway:
+    if route_tables:
+        for rt in route_tables:
+            try:
+                new_rt = vpc_conn.create_route_table(vpc.id)
+                for route in rt['routes']:
+                    route_kwargs = {}
+                    if route['gw'] == 'igw':
+                        if not internet_gateway:
+                            module.fail_json(
+                                msg='You asked for an Internet Gateway ' \
+                                '(igw) route, but you have no Internet Gateway'
+                            )
+                        route_kwargs['gateway_id'] = igw.id
+                    else:
+                        route_kwargs['instance_id'] = route['gw']
+                    vpc_conn.create_route(new_rt.id, route['dest'], **route_kwargs)
+
+                # Associate with subnets
+                for sn in rt['subnets']:
+                    rsn = vpc_conn.get_all_subnets(filters={'cidr': sn, 'vpc_id': vpc.id })
+                    if len(rsn) != 1:
                         module.fail_json(
-                            msg='You asked for an Internet Gateway ' \
-                            '(igw) route, but you have no Internet Gateway'
+                            msg='The subnet {0} to associate with route_table {1} ' \
+                            'does not exist, aborting'.format(sn, rt)
                         )
-                    route_kwargs['gateway_id'] = igw.id
-                else:
-                    route_kwargs['instance_id'] = route['gw']
-                vpc_conn.create_route(new_rt.id, route['dest'], **route_kwargs)
-
-            # Associate with subnets
-            for sn in rt['subnets']:
-                rsn = vpc_conn.get_all_subnets(filters={'cidr': sn, 'vpc_id': vpc.id })
-                if len(rsn) != 1:
-                    module.fail_json(
-                        msg='The subnet {0} to associate with route_table {1} ' \
-                        'does not exist, aborting'.format(sn, rt)
+                    rsn = rsn[0]
+
+                    # Disassociate then associate since we don't have replace
+                    old_rt = vpc_conn.get_all_route_tables(
+                        filters={'association.subnet_id': rsn.id, 'vpc_id': vpc.id}
                     )
-                rsn = rsn[0]
+                    if len(old_rt) == 1:
+                        old_rt = old_rt[0]
+                        association_id = None
+                        for a in old_rt.associations:
+                            if a.subnet_id == rsn.id:
+                                association_id = a.id
+                        vpc_conn.disassociate_route_table(association_id)

-                # Disassociate then associate since we don't have replace
-                old_rt = vpc_conn.get_all_route_tables(
-                    filters={'association.subnet_id': rsn.id, 'vpc_id': vpc.id}
+                    vpc_conn.associate_route_table(new_rt.id, rsn.id)
+
+                all_route_tables.append(new_rt)
+            except EC2ResponseError, e:
+                module.fail_json(
+                    msg='Unable to create and associate route table {0}, error: ' \
+                    '{1}'.format(rt, e)
                 )
-                if len(old_rt) == 1:
-                    old_rt = old_rt[0]
-                    association_id = None
-                    for a in old_rt.associations:
-                        if a.subnet_id == rsn.id:
-                            association_id = a.id
-                    vpc_conn.disassociate_route_table(association_id)
-
-                vpc_conn.associate_route_table(new_rt.id, rsn.id)
-
-            all_route_tables.append(new_rt)
-        except EC2ResponseError, e:
-            module.fail_json(
-                msg='Unable to create and associate route table {0}, error: ' \
-                '{1}'.format(rt, e)
-            )


-    # Now that we are good to go on our new route tables, delete the
-    # old ones except the 'main' route table as boto can't set the main
-    # table yet.
-    all_rts = vpc_conn.get_all_route_tables(filters={'vpc-id': vpc.id})
-    for rt in all_rts:
-        delete_rt = True
-        for newrt in all_route_tables:
-            if newrt.id == rt.id:
-                delete_rt = False
-        if delete_rt:
-            rta = rt.associations
-            is_main = False
-            for a in rta:
-                if a.main:
-                    is_main = True
-            try:
-                if not is_main:
-                    vpc_conn.delete_route_table(rt.id)
-            except EC2ResponseError, e:
-                module.fail_json(msg='Unable to delete old route table {0}, error: {1}'.format(rt.id, e))
+        # Now that we are good to go on our new route tables, delete the
+        # old ones except the 'main' route table as boto can't set the main
+        # table yet.
+        all_rts = vpc_conn.get_all_route_tables(filters={'vpc-id': vpc.id})
+        for rt in all_rts:
+            delete_rt = True
+            for newrt in all_route_tables:
+                if newrt.id == rt.id:
+                    delete_rt = False
+            if delete_rt:
+                rta = rt.associations
+                is_main = False
+                for a in rta:
+                    if a.main:
+                        is_main = True
+                try:
+                    if not is_main:
+                        vpc_conn.delete_route_table(rt.id)
+                except EC2ResponseError, e:
+                    module.fail_json(msg='Unable to delete old route table {0}, error: {1}'.format(rt.id, e))

     vpc_dict = get_vpc_info(vpc)
     created_vpc_id = vpc.id
```

**Comment by jimi-c** [comment]
@crashdump that's odd, with my patch above that variable should never be `None`.

**Comment by jimi-c** [comment]
An easier and less invasive fix would be:

<pre>
if subnets is None:
    subnets = []
if route_tables is None:
    route_tables = []
</pre>

**Comment by jimi-c** [comment]
Also odd is the fact that there's a specific check for the route_tables being a list before that line:

<pre>
    if route_tables and not isinstance(route_tables, list):
        module.fail_json(msg='route tables need to be a list of dictionaries')
</pre>

So I'll add in my fix above to the original patch and merge this in now.

**Comment by jimi-c** [comment]
I have merged in the above patch to resolve this. If you continue seeing any problems related to this issue, please let us know. Thanks!

**Comment by analytically** [comment]
Ansible's AWS modules are so broken it's getting ridiculous. And the unwillingness to accept patches is beyond belief.

**Comment by abadger** [comment]
@analytically Perhaps you meant to make that comment on a different ticket?  This one was closed in July of last year, 4 weeks after the initial problem report but only a few hours after the proposed fix was tested by the reporter and revised to fix what they were seeing.
