### ISSUE TITLE
ansible -t (tree output) is broken

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#773]
```
$ ansible all -i hosts -a date -t foo-out
192.168.56.254 | success | rc=0 >>
Thu Aug  2 06:25:34 BST 2012

192.168.56.254 | FAILED => Traceback (most recent call last):
  File "/home/brian/ansible/lib/ansible/runner/__init__.py", line 448, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/brian/ansible/lib/ansible/runner/__init__.py", line 488, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/home/brian/ansible/lib/ansible/runner/__init__.py", line 607, in _executor_internal_inner
    self.callbacks.on_ok(result.host, data)
  File "/home/brian/ansible/lib/ansible/callbacks.py", line 194, in on_ok
    self._on_any(host,res)
  File "/home/brian/ansible/lib/ansible/callbacks.py", line 238, in _on_any
    utils.write_tree_file(self.options.tree, host, utils.json(result,format=True))
TypeError: 'module' object is not callable
```

This seems to fix it:

```
--- a/lib/ansible/callbacks.py
+++ b/lib/ansible/callbacks.py
@@ -235,7 +235,7 @@ class CliRunnerCallbacks(DefaultRunnerCallbacks):

         print host_report_msg(host, self.options.module_name, result, self.options.one_line)
         if self.options.tree:
-            utils.write_tree_file(self.options.tree, host, utils.json(result,format=True))
+            utils.write_tree_file(self.options.tree, host, utils.jsonify(result,format=True))

 ########################################################################

```

**Comment by mpdehaan** [comment]
sounds good, send me a pull request?

**Comment by mpdehaan** [comment]
fix pushed
