### ISSUE TITLE
ansible-galaxy - inconsistent behaviour with optional arguments

### ISSUE THREAD

**Issue by kamszp** [ansible/ansible#78204]
### Summary

Ansible accept optional arguments in an inconsistent manner:

For **-r REQUIREMENTS, --role-file REQUIREMENTS**  it works fine only **without** equal sign before value.
For **-p ROLES_PATH, --roles-path ROLES_PATH** it works fine only **with** equal sign before value.

Putting values in apostrophes is optional (does not change behaviour).

**Before ansible-core 2.13** it was working with equal sign for both of arguments.

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections
  executable location = /home/vagrant/.local/bin/ansible
  python version = 3.9.6 (default, Aug 11 2021, 06:39:25) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.1
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CALLBACKS_ENABLED(/vagrant/ansible/ansible.cfg) = ['timer', 'profile_tasks']
COLLECTIONS_PATHS(/vagrant/ansible/ansible.cfg) = ['/home/vagrant/.ansible/collections']
DEFAULT_HOST_LIST(/vagrant/ansible/ansible.cfg) = ['/vagrant/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/vagrant/ansible/ansible.cfg) = ['/home/vagrant/.ansible/roles']
DEFAULT_STDOUT_CALLBACK(/vagrant/ansible/ansible.cfg) = debug
ERROR_ON_MISSING_HANDLER(/vagrant/ansible/ansible.cfg) = True
GALAXY_SERVER_LIST(/vagrant/ansible/ansible.cfg) = ['community']
HOST_KEY_CHECKING(/vagrant/ansible/ansible.cfg) = False
STRING_CONVERSION_ACTION(/vagrant/ansible/ansible.cfg) = ignore

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/vagrant/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/vagrant/ansible/ansible.cfg) = False
pipelining(/vagrant/ansible/ansible.cfg) = True
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
# for 'disable_gpg_verify' bug
ansible-galaxy install --role-file='requirements_galaxy.yml' –force

# for 'no requirements found'
ansible-galaxy install -r requirements_galaxy.yml -p roles --force
```

### Expected Results

```yaml
ansible-galaxy install --role-file requirements_galaxy.yml --roles-path roles --force
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/community-general-5.2.0.tar.gz to /home/vagrant/.ansible/tmp/ansible-local-11112gvz6l6js/tmp91i_3inq/community-general-5.2.0-blae3lbr
Installing 'community.general:5.2.0' to '/home/vagrant/.ansible/collections/ansible_collections/community/general'
community.general:5.2.0 was installed successfully
```

### Actual Results

```console
# disable_gpg_verify (with = sign for --role-file)
ansible-galaxy install --role-file=/vagrant/ansible/requirements_galaxy.yml  --force
Starting galaxy collection install process
ERROR! Unexpected Exception, this is probably a bug: 'disable_gpg_verify'
to see the full traceback, use -vvv

# disable_gpg_verify (with = sign for --role-file) with -vvv
ansible-galaxy install --role-file=/vagrant/ansible/requirements_galaxy.yml  --force -vvv
ansible-galaxy [core 2.13.1]
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections
  executable location = /home/vagrant/.local/bin/ansible-galaxy
  python version = 3.9.6 (default, Aug 11 2021, 06:39:25) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.1
  libyaml = True
Using /vagrant/ansible/ansible.cfg as config file
Reading requirement file at '/vagrant/ansible/requirements_galaxy.yml'
Starting galaxy collection install process
ERROR! Unexpected Exception, this is probably a bug: 'disable_gpg_verify'
the full traceback was:

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.9/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/home/vagrant/.local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 647, in run
    return context.CLIARGS['func']()
  File "/home/vagrant/.local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 102, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1297, in execute_install
    self._execute_install_collection(
  File "/home/vagrant/.local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1309, in _execute_install_collection
    disable_gpg_verify = context.CLIARGS['disable_gpg_verify']
  File "/home/vagrant/.local/lib/python3.9/site-packages/ansible/module_utils/common/collections.py", line 20, in __getitem__
    return self._store[key]
KeyError: 'disable_gpg_verify'

# no requirements found (without = sign for --roles-path)
ansible-galaxy install --role-file requirements_galaxy.yml --roles-path 'roles' --force
[WARNING]: The requirements file '/vagrant/ansible/requirements_galaxy.yml' contains collections which will be ignored. To install these collections run
'ansible-galaxy collection install -r' or to install both at the same time run 'ansible-galaxy install -r' without a custom install path.
Skipping install, no requirements found
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by salderma** [comment]
I started having this issue as well - 

```
[me@localhost windows-dc-lab:deploy±]$ ANSIBLE_CONFIG='ansible/ansible.cfg' ansible-galaxy install --role-file='ansible/requirements.yml' --roles-path='ansible/roles' --force-with-deps -vvv
ansible-galaxy [core 2.13.2]
  config file = /home/me/git/windows-dc-lab/ansible/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/me/git/windows-dc-lab/ansible
  executable location = /home/me/.local/bin/ansible-galaxy
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
Using /home/me/git/windows-dc-lab/ansible/ansible.cfg as config file
Reading requirement file at '/home/me/git/windows-dc-lab/ansible/requirements.yml'
Starting galaxy collection install process
ERROR! Unexpected Exception, this is probably a bug: 'disable_gpg_verify'
the full traceback was:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/home/me/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 647, in run
    return context.CLIARGS['func']()
  File "/home/me/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 102, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/home/me/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 1297, in execute_install
    self._execute_install_collection(
  File "/home/me/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 1309, in _execute_install_collection
    disable_gpg_verify = context.CLIARGS['disable_gpg_verify']
  File "/home/me/.local/lib/python3.8/site-packages/ansible/module_utils/common/collections.py", line 20, in __getitem__
    return self._store[key]
KeyError: 'disable_gpg_verify'
```

**Comment by sivel** [comment]
I've looked back into this in a little more depth, and this is the cause:

https://github.com/ansible/ansible/blob/05608b20e8f875d51866a184f8c579fe60498e05/lib/ansible/cli/galaxy.py#L504

Effectively when you use `=`, `sys.argv` looks like:

```
[..., "--role-file='requirements_galaxy.yml'", ...]
```

as opposed to:

```
[..., "--role-file", "requirements_galaxy.yml", ...]
```

As such, that logic linked above does not detect `--role-file` in args.

To address this, would require something like this:

```diff
diff --git a/lib/ansible/cli/galaxy.py b/lib/ansible/cli/galaxy.py
index 6118efee7c..6e976c8b42 100755
--- a/lib/ansible/cli/galaxy.py
+++ b/lib/ansible/cli/galaxy.py
@@ -487,7 +487,9 @@ class GalaxyCLI(CLI):
         else:
             install_parser.add_argument('-r', '--role-file', dest='requirements',
                                         help='A file containing a list of roles to be installed.')
-            if self._implicit_role and ('-r' in self._raw_args or '--role-file' in self._raw_args):
+            role_file_re = re.compile(r'--role-file($|=)')
+            contains_role_file = bool([a for a in self._raw_args if role_file_re.match(a)])
+            if self._implicit_role and ('-r' in self._raw_args or contains_role_file):
                 # Any collections in the requirements files will also be installed
                 install_parser.add_argument('--keyring', dest='keyring', default=C.GALAXY_GPG_KEYRING,
                                             help='The keyring used during collection signature verification')
```

Ultimately, I think what needs to happen is that we deprecate the backwards compatible `ansible-galaxy role` shim, where you can call `ansible-galaxy` without `role` or `collection`, and have it perform `role` actions.

Instead, we should just leave require all `role` specific operations to use `ansible-galaxy role ...`.  But add a subparser for `install` that can still handle both roles and collections without specifying `ansible-galaxy role|collection install`

**Comment by salderma** [comment]
@sivel  Thanks for looking into this. I am a little confused as to how this just seemed to come up all of a sudden.  It as effectively broken most of my Vagrant/Ansible based IaC projects where I use a `requirements.yml` file to pull collections and roles (which avoids having to store them in my repos).

I admit, my local/user python3 libraries is probably a mess and in need to be seriously cleaned up, but it seems like 2-3 weeks ago I was not having this issue. I do try to keep library versions reasonably up-to-date with pip, including ansible.  Was there a change introducing this behavior in the past couple of months that updating ansible would have introduced this issue?  If, so I can revert to a previous pip package version and keep working :)

Thanks again for taking a look!

**Comment by sivel** [comment]
It was a result of adding collection signature verification in 2.13.0.
