### ISSUE TITLE
unsupported operand type(s) for |=: 'bool' and 'AnsibleUnsafeText'

### ISSUE THREAD

**Issue by TheMysteriousX** [ansible/ansible#78341]
### Summary

I'm trying to use  'replace' and 'endswith' within `failed_when` - this works in python:

```pycon
>>> "foobarbaz".replace("baz", "bar").endswith("bar")
True
```

But in ansible this:

```yaml
  failed_when:
    - not item.msg.replace(acceptable_error).endswith(valid_ending)
```

Results in a stack trace and a message saying it's 'probably a bug'.

### Background/Usecase

I'm attempting to parse the output of a previous task - it has warnings that are generated that are expressed inside the main body of the response, so they need to be stripped out before evaluating the result.

The task has a debug statement as a noop, then evaluates the response with failed_when - the task should be considered failed when the failed flag is true, AND there are additional errors beyond the one allowed.

### Issue Type

Bug Report

### Component Name

executor

### Ansible Version

```console
ansible [core 2.13.2]
  config file = /builds/operations/network/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Mar  2 2022, 04:23:34) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
DEFAULT_FILTER_PLUGIN_PATH(/builds/operations/network/ansible.cfg) = ['/root/.ansible/plugins/filter', '/builds/operations/network/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_HOST_LIST(/builds/operations/network/ansible.cfg) = ['/builds/operations/network/inventory/hosts.yaml']
DEFAULT_JINJA2_EXTENSIONS(/builds/operations/network/ansible.cfg) = jinja2.ext.do
DEFAULT_JINJA2_NATIVE(/builds/operations/network/ansible.cfg) = True
DEFAULT_ROLES_PATH(/builds/operations/network/ansible.cfg) = ['/builds/operations/network/roles']
DUPLICATE_YAML_DICT_KEY(/builds/operations/network/ansible.cfg) = ignore
INTERPRETER_PYTHON(/builds/operations/network/ansible.cfg) = python
PERSISTENT_CONTROL_PATH_DIR(/builds/operations/network/ansible.cfg) = /root/.ansible/cp
```

### OS / Environment

python:3.9.10-bullseye container

### Steps to Reproduce

The task is: 

```yaml (paste below)
- name: "Evaluate results: Loading"
  ansible.builtin.debug:
    msg: "Checking configuration load RPC responses"
  failed_when:
    - item.failed
    - not item.msg.replace(acceptable_error).endswith(valid_ending) # replace(acceptable_error).
  loop:
    - "{{ response.results[1] }}"
  when: compare or check
  vars:
    acceptable_error: ' Error: RpcError(severity: None, bad_element: None, message: warning: Delete all fabric member interfaces on node0/node1 will cause session state sync failure/traffic black hole\nwarning: Delete all fabric member interfaces on node0/node1 will cause session state sync failure/traffic black hole)'
    valid_ending: "</configuration-text>\\n</load-configuration>\\n'."
```

'response.results[1]' looks like this:
```
{ 
    msg: "giant block of text ending in </configuration-text>\\n</load-configuration>\\n'. Error: RpcError(severity: None, bad_element: None, message: warning: Delete all fabric member interfaces on node0/node1 will cause session state sync failure/traffic black hole\nwarning: Delete all fabric member interfaces on node0/node1 will cause session state sync failure/traffic black hole)",
    failure: True
    changed: False
}
```

### Expected Results

I don't feel like I'm doing anything weird, so I'm expecting the condition to evaluate the same way it does in plain python.
At the very least, ansible should return a useful error, rather than throwing a stack trace.

### Actual Results

```python-traceback
ERROR! Unexpected Exception, this is probably a bug: unsupported operand type(s) for |=: 'bool' and 'AnsibleUnsafeText'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/playbook.py", line 143, in run
    results = pbex.run()
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/playbook_executor.py", line 190, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_queue_manager.py", line 321, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/strategy/linear.py", line 329, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/strategy/__init__.py", line 865, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/strategy/__init__.py", line 157, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes, do_handlers=do_handlers)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/strategy/__init__.py", line 586, in _process_pending_results
    if task_result.is_failed():
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_result.py", line 68, in is_failed
    return self._check_key('failed_when_result')
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_result.py", line 105, in _check_key
    flag |= res.get(key, False)
TypeError: unsupported operand type(s) for |=: 'bool' and 'AnsibleUnsafeText'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by TheMysteriousX** [comment]
And in the instant I submit the ticket, I spot that the replace is missing a parameter!

**Comment by webknjaz** [comment]
I've just started to hit this issue consistently on several versions of `ansible-core` including `devel`. So I'm reopening this.

While this is indeed caused by a user error, `ansible-playbook` shouldn't spit out a traceback but display a useful hint instead.

**Comment by webknjaz** [comment]
I discovered this via https://github.com/ansible/ansible-core-ci/pull/610.

**Comment by webknjaz** [comment]
Repro for the future exploration:
```python-traceback
$ cat repro-78341.yml 
- name: Repro
  hosts: all
  become: no
  gather_facts: no
  force_handlers: no

  tasks:
  - set_fact:
      dct:
        key1: val1
  - debug:
      msg: eh
    register: v
    # when: no
    failed_when: >-
      'No such file or directory' not in v.mesg.thing
    # ignore_errors: true
    loop:  # NOTE: loop is triggering a traceback
    - dev
  - debug:
      var: v
  - name: Touch a file
    become: no
    file:
      # NOTE: The value doesn't matter; devnull is used to prevent accidental
      # NOTE: side-effects in the reproducer.
      path: /dev/null
      state: touch
    register: file_touch_result
    failed_when: >-
      'No such file or directory' not in file_touch_result.msg
    # ignore_errors: true
    loop:  # NOTE: loop is triggering a traceback
    - dev
  - debug:
      var: file_touch_result

$ ansible-playbook repro-78341.yml --inventory=localhost, --connection=local -vvvvv         
ansible-playbook [core 2.18.0]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.local/bin/ansible-playbook
  python version = 3.12.7 (main, Oct 27 2024, 17:48:33) [GCC 13.3.1 20240614] (~/.local/share/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.4
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Loading collection ansible.builtin from 
Set default localhost to localhost
Parsed localhost, inventory source with host_list plugin
Loading callback plugin default of type stdout, v2.0 from ~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/plugins/callback/default.py
Attempting to use 'default' callback.
Skipping callback 'default', as we already have a stdout callback.
Attempting to use 'junit' callback.
Attempting to use 'minimal' callback.
Skipping callback 'minimal', as we already have a stdout callback.
Attempting to use 'oneline' callback.
Skipping callback 'oneline', as we already have a stdout callback.
Attempting to use 'tree' callback.

PLAYBOOK: repro-78341.yml *********************************************************************************
Positional arguments: repro-78341.yml
verbosity: 5
connection: local
become_method: sudo
tags: ('all',)
inventory: ('localhost,',)
forks: 5
1 plays in repro-78341.yml

PLAY [Repro] **********************************************************************************************

TASK [set_fact] *******************************************************************************************
task path: ~/src/github/ansible/ansible/repro-78341.yml:8
ok: [localhost] => {
    "ansible_facts": {
        "dct": {
            "key1": "val1"
        }
    },
    "changed": false
}

TASK [debug] **********************************************************************************************
task path: ~/src/github/ansible/ansible/repro-78341.yml:11
failed: [localhost] (item=dev) => {
    "msg": "eh"
}
ERROR! Unexpected Exception, this is probably a bug: unsupported operand type(s) for |=: 'bool' and 'AnsibleUnsafeText'
the full traceback was:

Traceback (most recent call last):
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/cli/__init__.py", line 646, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/cli/playbook.py", line 155, in run
    results = pbex.run()
              ^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/executor/playbook_executor.py", line 188, in run
    result = self._tqm.run(play=play)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/executor/task_queue_manager.py", line 346, in run
    play_return = strategy.run(iterator, play_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/plugins/strategy/linear.py", line 216, in run
    results.extend(self._wait_on_pending_results(iterator))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/plugins/strategy/__init__.py", line 813, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/plugins/strategy/__init__.py", line 170, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/plugins/strategy/__init__.py", line 582, in _process_pending_results
    if task_result.is_failed():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/executor/task_result.py", line 67, in is_failed
    return self._check_key('failed_when_result')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/executor/task_result.py", line 104, in _check_key
    flag |= res.get(key, False)
TypeError: unsupported operand type(s) for |=: 'bool' and 'AnsibleUnsafeText'
```

This seems to be triggered by a combination of a loop and an error during the `failed_when` evaluation (like accessing an undefined attribute in the result object). I think I saw some other weirdness that I can't remember of now (hence those commented out `ignore_errors` lines).
