### ISSUE TITLE
Failed ping attempt traceback

### ISSUE THREAD

**Issue by myusuf3** [ansible/ansible#785]
Failed attempt to connect to server results in the following stack trace. 

``` python
 | FAILED => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 448, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 494, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 576, in _executor_internal_inner
    result = self._execute_normal_module(conn, tmp, module_name, inject=inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 254, in _execute_normal_module
    exec_rc = self._execute_module(conn, tmp, module_name, self.module_args, inject=inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 212, in _execute_module
    (remote_module_path, is_new_style) = self._copy_module(conn, tmp, module_name, inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 714, in _copy_module
    self._transfer_str(conn, tmp, module, module_data)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 197, in _transfer_str
    conn.put_file(afile, remote)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/connection/paramiko_ssh.py", line 125, in put_file
    sftp = self.ssh.open_sftp()
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 399, in open_sftp
    return self._transport.open_sftp_client()
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 828, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/usr/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 106, in from_transport
    return cls(chan)
  File "/usr/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 87, in __init__
    server_version = self._send_version()
  File "/usr/lib/python2.7/dist-packages/paramiko/sftp.py", line 108, in _send_version
    t, data = self._read_packet()
  File "/usr/lib/python2.7/dist-packages/paramiko/sftp.py", line 179, in _read_packet
    raise SFTPError('Garbage packet received')
SFTPError: Garbage packet received

```

**Comment by mpdehaan** [comment]
SFTP support is required on the remote server.  I'm guessing you have it turned off, or are speaking to some relatively ancient distribution or version of openssh.

**Comment by myusuf3** [comment]
Yep that did it the needed to have sftp support turned on.

**Comment by myusuf3** [comment]
It would also be nice for the error to be caught gracefully and inform the user of the issue.

**Comment by mpdehaan** [comment]
patches accepted
