### ISSUE TITLE
windows: auth errors aren't properly propagated

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#7875]
winrm attempts to connect via ssl, falling back to plaintext (or the reverse, depending on the port.)

However, this fallback means that if connecting fails due to an auth error (bad user/pw), it could then fallback to trying SSL on an non-SSL port, which yield this OpenSSL error:

fatal: [x.y.z.a] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/**init**.py", line 526, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 628, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 799, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/usr/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/connection.py", line 34, in connect
    self.active = conn.connect()
  File "/usr/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 134, in connect
    self.protocol = self._winrm_connect()
  File "/usr/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 106, in _winrm_connect
    raise exc
WinRMTransportError: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

It should catch the auth error and bail instead of falling back.

**Comment by mpdehaan** [comment]
Tracebacks in ansible are always bugs, so I'd except a friendly message for humans here, though maybe keep the windows-goo in parens in case it's not always caught correctly.

**Comment by mpdehaan** [comment]
Authentication failed (WinRMTransport Error: <blah>, <foo>) or somesuch

**Comment by jimi-c** [comment]
Hi!

The above commits have been merged in, and should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
