### ISSUE TITLE
Gathering facts fails on Funtoo Linux

### ISSUE THREAD

**Issue by s0x** [ansible/ansible#7885]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.7 (devel 122fff970f) last updated 2014/06/22 00:10:25 (GMT +200)
##### Environment:

Funtoo Linux
##### Summary:

When gathering facts about a system running Funtoo Linux, ansible stumbles over an existing but empty /etc/os-release and tries to receive Debian release informations from it. For this purpose, ansible tries to split the content (None) leading to the following exception:

```
invalid output was: Traceback (most recent call last):
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 3748, in <module>
    main()
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 137, in main
    data = run_setup(module)
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 81, in run_setup
    facts = ansible_facts(module)
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 3686, in ansible_facts
    facts.update(Facts().populate())
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 1493, in __init__
    self.get_platform_facts()
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 1536, in get_platform_facts
    self.get_distribution_facts()
  File "/home/s0x/.ansible/tmp/ansible-tmp-1403389585.69-111007185005190/setup", line 1687, in get_distribution_facts
    data = get_file_content(path).split('\n')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```
##### Steps To Reproduce:

Actually, I tested it on a local playbook only so far, though it shouldn't make any difference on a remote machine.
- Create a playbook using local connection

```
- name: Run some local tasks
  hosts: localhost
  connection: local
  tasks:
  - name: Some task
    action: debug
```
- Run it: `ansible-playbook local.yaml`
##### Expected Results:

The playbook should be executed without any error.
##### Actual Results:

Gathering facts will fail with the error shown above.

**Comment by mpdehaan** [comment]
Closing this as we can track the bugfix PR instead.  Thanks!
