### ISSUE TITLE
Cannot clone git repository using sudo_user

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#7897]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.7 (devel)
##### Environment:

Ubuntu, Debian
##### Summary:

`git` module cannot clone repository as another user using `sudo_user` option.
##### Steps To Reproduce:

```

---

- hosts: all
  sudo: True

  vars:
    testuser: 'test_user'
    project: 'https://github.com/ansible/ansible.git'

  tasks:
    - name: Create test user
      user: name={{ testuser }} state=present

    - name: Clone project as root
      git: repo={{ project }} dest=/tmp/root_testproject update=yes

    - name: Clone project as test user
      git: repo={{ project }} dest=/tmp/user_testproject update=yes
      sudo_user: '{{ testuser }}'
```
##### Expected Results:

Repository is cloned to both directories.
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [winterfell]

TASK: [Create test user] ****************************************************** 
ok: [winterfell]

TASK: [Clone project as root] ************************************************* 
ok: [winterfell]

TASK: [Clone project as test user] ******************************************** 
fatal: [winterfell] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 526, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 628, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 833, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 427, in _execute_module
    self._remote_chmod(conn, 'a+r', remote_module_path)
TypeError: _remote_chmod() takes at least 5 arguments (4 given)


FATAL: all hosts have already failed -- aborting
```

**Comment by leucos** [comment]
Very painful.
Bissected this to 5dcaa30476b03f3ea150053a13eb2864cce0ce45
Indeed _remote_chmod takes 4+self arguments (https://github.com/ansible/ansible/commit/5dcaa30476b03f3ea150053a13eb2864cce0ce45#diff-af869caf5f6f46706dbf35970e39c686R994) while most of the calls in the same file only provides 3+1.

**Comment by leucos** [comment]
Fixed by #7900

**Comment by leucos** [comment]
Fix WorksForMe. How about you @drybjed ?

**Comment by drybjed** [comment]
@leucos git works correctly now. Thanks! :-)
