### ISSUE TITLE
not using a valid encoding return an exception for mysql_db

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8075]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

1.7
##### Environment:

Centos 6.5. 
##### Summary:

Running module mysql_db with an invalid encoding return with a python exception
##### Steps To Reproduce:

Running the following:

```
- name: test mysql_db not using valid encoding 
  mysql_db: name=dataencode state=present encoding=notvalid 
  register: result
```
##### Expected Results:

Catch Traceback and display a friendly error message.
##### Actual Results:

```
ok: [testhost] => {
    "result": {
        "failed": true, 
        "invocation": {
            "module_args": "name=dataencode state=present encoding=notvalid", 
            "module_name": "mysql_db"
        }, 
        "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1404790966.78-108278846360662/mysql_db\", line 1647, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1404790966.78-108278846360662/mysql_db\", line 341, in main\n    changed = db_create(cursor, db, encoding, collation)\n  File \"/root/.ansible/tmp/ansible-tmp-1404790966.78-108278846360662/mysql_db\", line 198, in db_create\n    res = cursor.execute(query)\n  File \"/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py\", line 173, in execute\n    self.errorhandler(self, exc, value)\n  File \"/usr/lib64/python2.6/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\n_mysql_exceptions.OperationalError: (1115, \"Unknown character set: 'notvalid'\")\n", 
        "parsed": false
    }
}
```

**Comment by wrosario** [comment]
I am seeing the similar exception when using an invalid collation

```
- name: test mysql_db using invalid collation 
  mysql_db: name=datainvalidcollation state=present collation=invalid
  register: result
```

Results:

```
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1404805850.51-263175744256374/mysql_db", line 1647, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1404805850.51-263175744256374/mysql_db", line 341, in main
    changed = db_create(cursor, db, encoding, collation)
  File "/root/.ansible/tmp/ansible-tmp-1404805850.51-263175744256374/mysql_db", line 198, in db_create
    res = cursor.execute(query)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1273, "Unknown collation: 'invalid'")
```

**Comment by jimi-c** [comment]
The above PR has been merged in and should address this. Thanks!
