### ISSUE TITLE
OSError: [Errno 95] Operation not supported - ansible-galaxy fails to install collection to path mounted via CIFS

### ISSUE THREAD

**Issue by Tronde** [ansible/ansible#81085]
### Summary

When I try to install a collection using `ansible-galaxy` to a directory that is mounted via CIFS the installation fails with the error: `OSError: [Errno 95] Operation not supported`

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible-galaxy --version
ansible-galaxy [core 2.14.2]
  config file = /home/tronde/.ansible.cfg
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/tronde/.ansible.cfg
DEFAULT_PRIVATE_KEY_FILE(/home/tronde/.ansible.cfg) = /home/tronde/.ssh/ansible_id_rsa
DEFAULT_ROLES_PATH(/home/tronde/.ansible.cfg) = ['/home/tronde/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/home/tronde/diskstation/home/ansible/roles']

CONNECTION:
==========

ssh:
___
private_key_file(/home/tronde/.ansible.cfg) = /home/tronde/.ssh/ansible_id_rsa
```

### OS / Environment

Reproduced on Debian 11 as well as Fedora 38

### Steps to Reproduce

```bash
[tronde@host ~]$ sudo mount -t cifs -o uid=1000,gid=1000,credentials=/home/tronde/.smbcredentials,noserverino //192.0.2.1/homes/tronde /mnt
[sudo] password for tronde: 
[tronde@host ~]$ mount | grep mnt
//192.0.2.1/homes/tronde on /mnt type cifs (rw,relatime,vers=default,cache=strict,username=tronde,uid=1000,noforceuid,gid=1000,noforcegid,addr=192.0.2.1,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=1)
[tronde@host ~]$ ansible-galaxy collection install community.general -p /mnt -vvv
ansible-galaxy [core 2.14.2]
  config file = /home/tronde/.ansible.cfg
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
Using /home/tronde/.ansible.cfg as config file
Starting galaxy collection install process
[WARNING]: The specified collections path '/mnt' is not part of the configured Ansible collections paths '/home/tronde/.ansible/collections:/usr/share/ansible/collections'. The installed collection will not be picked up in an Ansible run, unless within a playbook-adjacent collections directory.
Process install dependency map
Opened /home/tronde/.ansible/galaxy_token
Starting collection install process
Downloading https://galaxy.ansible.com/download/community-general-7.0.1.tar.gz to /home/tronde/.ansible/tmp/ansible-local-24239rqvf2zui/tmp3t1aru78/community-general-7.0.1-gfk54hgf
Collection 'community.general:7.0.1' obtained from server default https://galaxy.ansible.com/api/
Installing 'community.general:7.0.1' to '/mnt/ansible_collections/community/general'
ERROR! Unexpected Exception, this is probably a bug: [Errno 95] Operation not supported: b'../COPYING' -> b'/mnt/ansible_collections/community/general/LICENSES/GPL-3.0-or-later.txt'
the full traceback was:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/cli/__init__.py", line 647, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 714, in run
    return context.CLIARGS['func']()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 115, in method_wrapper
    return wrapped_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1363, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1400, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 771, in install_collections
    install(concrete_coll_pin, output_path, artifacts_manager)
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1448, in install
    install_artifact(
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1535, in install_artifact
    _extract_tar_file(collection_tar, file_name, b_collection_path, b_temp_path,
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1664, in _extract_tar_file
    os.symlink(b_link_path, b_dest_filepath)
OSError: [Errno 95] Operation not supported: b'../COPYING' -> b'/mnt/ansible_collections/community/general/LICENSES/GPL-3.0-or-later.txt'
```

I tried the collection `community.libvirt` as well which failed too.

### Expected Results

I expected the collection `community.general` to be installed in `/mnt`.

### Actual Results

```console
$ ansible-galaxy collection install community.general -p /mnt -vvvv
ansible-galaxy [core 2.14.2]
  config file = /home/tronde/.ansible.cfg
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
Using /home/tronde/.ansible.cfg as config file
Starting galaxy collection install process
[WARNING]: The specified collections path '/mnt' is not part of the configured Ansible collections paths '/home/tronde/.ansible/collections:/usr/share/ansible/collections'. The installed collection will not be picked up in an Ansible run, unless within a playbook-adjacent collections directory.
Process install dependency map
Initial connection to galaxy_server: https://galaxy.ansible.com
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Opened /home/tronde/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/community/general/
Starting collection install process
Fetching a collection tarball for 'community.general:7.0.1' from Ansible Galaxy
Downloading https://galaxy.ansible.com/download/community-general-7.0.1.tar.gz to /home/tronde/.ansible/tmp/ansible-local-24300o0bnzq13/tmpii0643bs/community-general-7.0.1-knuk3rpw
Validating downloaded file hash c6c697c4aac5dd547a5c6380f048fd3cc81cb75a51db4fe4f9c337b19177f02d with expected hash c6c697c4aac5dd547a5c6380f048fd3cc81cb75a51db4fe4f9c337b19177f02d
Collection 'community.general:7.0.1' obtained from server default https://galaxy.ansible.com/api/
Installing 'community.general:7.0.1' to '/mnt/ansible_collections/community/general'
ERROR! Unexpected Exception, this is probably a bug: [Errno 95] Operation not supported: b'../COPYING' -> b'/mnt/ansible_collections/community/general/LICENSES/GPL-3.0-or-later.txt'
the full traceback was:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/cli/__init__.py", line 647, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 714, in run
    return context.CLIARGS['func']()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 115, in method_wrapper
    return wrapped_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1363, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1400, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 771, in install_collections
    install(concrete_coll_pin, output_path, artifacts_manager)
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1448, in install
    install_artifact(
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1535, in install_artifact
    _extract_tar_file(collection_tar, file_name, b_collection_path, b_temp_path,
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1664, in _extract_tar_file
    os.symlink(b_link_path, b_dest_filepath)
OSError: [Errno 95] Operation not supported: b'../COPYING' -> b'/mnt/ansible_collections/community/general/LICENSES/GPL-3.0-or-later.txt'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Akasurde** [comment]
@Tronde Thanks for reporting this issue. I think you need to mount the CIFS path using `mfsymlinks` parameter. Please refer https://github.com/ansible/ansible/issues/76351#issuecomment-982751161. 

Let me know if it works for you. Thanks,

needs_info

**Comment by Tronde** [comment]
> @Tronde Thanks for reporting this issue. I think you need to mount the CIFS path using `mfsymlinks` parameter. Please refer [#76351 (comment)](https://github.com/ansible/ansible/issues/76351#issuecomment-982751161).
> 
> Let me know if it works for you. Thanks,

Hi @Akasurde,  
Using `mfsymlinks` as a mount option solved the issue. See the following example as a reference.

~~~
[tronde@host ~]$ sudo mount -t cifs -o uid=1000,gid=1000,credentials=/home/tronde/.smbcredentials,noserverino,mfsymlinks //192.0.2.1/homes/tronde /mnt
~~~

-needs_info

**Comment by Tronde** [comment]
One question before this issue might be closed. Could you explain to me why the option `mfsymlinks` is necessary? What symlinks are being set when installing a collection so you would need this?

**Comment by jborean93** [comment]
If a collection contains symlinks we will attempt to preserve them. If it does not contain a symlink then `ansible-galaxy` shouldn't be creating any.

**Comment by Tronde** [comment]
So the correct solution to solve this issue is to use mount option `mfsymlinks`.
Thanks for the clarification. :+1:
