### ISSUE TITLE
Unexpected exception while installing ansible galaxy collections using Python 3.7

### ISSUE THREAD

**Issue by jesperes** [ansible/ansible#81830]
### Summary

Recently (this started happening a few days ago), we are getting API errors when installing collections using `ansible-galaxy`:
```
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an unexpected error when
getting available versions of collection community.general:
'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
```

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 20.04 running official `python:3.7` docker image.

### Steps to Reproduce

This can be reproduced with the official Python docker images:
```shell
$ x docker run --rm -it python:3.7 bash -c 'python3 -m pip install ansible && ansible --version && ansible-config dump --only-changed && ansible-galaxy -vvv collection install community.general'

```

### Expected Results

I expected the `community.general` collection to be installed without errors.

### Actual Results

```console
$ x docker run --rm -it python:3.7 bash -c 'python3 -m pip install ansible && ansible --version && ansible-config dump --only-changed && ansible-galaxy -vvv collection install community.general'
Collecting ansible
  Downloading ansible-4.10.0.tar.gz (36.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.8/36.8 MB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ansible-core~=2.11.7
  Downloading ansible-core-2.11.12.tar.gz (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 7.2 MB/s eta 0:00:00
Collecting PyYAML
  Downloading PyYAML-6.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (670 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.1/670.1 kB 5.5 MB/s eta 0:00:00
Collecting cryptography
  Downloading cryptography-41.0.4-cp37-abi3-manylinux_2_28_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 4.9 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 10.0 MB/s eta 0:00:00
Collecting resolvelib<0.6.0,>=0.5.3
  Downloading resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.9/427.9 kB 5.2 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 9.8 MB/s eta 0:00:00
Building wheels for collected packages: ansible, ansible-core
  Building wheel for ansible (setup.py) ... done
  Created wheel for ansible: filename=ansible-4.10.0-py3-none-any.whl size=60568522 sha256=aa4f286ee5f01000abf60fe0f22149cdca804554c949388f97a9f1a97569e490
  Stored in directory: /root/.cache/pip/wheels/63/73/49/abc8cc94c80bbc9ffa3d4dad9e860562e7d2929312a7977463
  Building wheel for ansible-core (setup.py) ... done
  Created wheel for ansible-core: filename=ansible_core-2.11.12-py3-none-any.whl size=1960972 sha256=79d3d7d4a884f2a61f1daebed0d9e67cfc7890f9439e6ea5dfeed08909a584a5
  Stored in directory: /root/.cache/pip/wheels/cc/01/76/7e9834e0dd51992e45d7995e174c128121d83b7c19b8bcf47a
Successfully built ansible ansible-core
Installing collected packages: resolvelib, PyYAML, pycparser, packaging, MarkupSafe, jinja2, cffi, cryptography, ansible-core, ansible
Successfully installed MarkupSafe-2.1.3 PyYAML-6.0.1 ansible-4.10.0 ansible-core-2.11.12 cffi-1.15.1 cryptography-41.0.4 jinja2-3.1.2 packaging-23.2 pycparser-2.21 resolvelib-0.5.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.17 (default, Sep 20 2023, 11:53:41) [GCC 12.2.0]. This feature will be removed from ansible-core in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.7.17 (default, Sep 20 2023, 11:53:41) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.17 (default, Sep 20 2023, 11:53:41) [GCC 12.2.0]. This feature will be removed from ansible-core in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.17 (default, Sep 20 2023, 11:53:41) [GCC 12.2.0]. This feature will be removed from ansible-core in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Setting verbosity before the arg sub command is deprecated, set the verbosity after the sub command. This feature will be removed from ansible-core in version 2.13. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ansible-galaxy [core 2.11.12] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.7.17 (default, Sep 20 2023, 11:53:41) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
Starting galaxy collection install process
Process install dependency map
Created /root/.ansible/galaxy_token
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an unexpected error when getting available versions of collection community.general:
'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'community.general'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 135, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 552, in run
    return context.CLIARGS['func']()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 75, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 1188, in execute_install
    artifacts_manager=artifacts_manager,
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 1217, in _execute_install_collection
    artifacts_manager=artifacts_manager,
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection/__init__.py", line 554, in install_collections
    upgrade=upgrade,
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection/__init__.py", line 1365, in _resolve_depenency_map
    max_rounds=2000000,  # NOTE: same constant pip uses
  File "/usr/local/lib/python3.7/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/lib/python3.7/site-packages/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/local/lib/python3.7/site-packages/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/dependency_resolution/providers.py", line 214, in find_matches
    coll_versions = self._api_proxy.get_collection_versions(first_req)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 104, in get_collection_versions
    requirement,
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 102, in <genexpr>
    (version, api)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 82, in _get_collection_versions
    raise last_error
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 61, in _get_collection_versions
    versions = api.get_collection_versions(requirement.namespace, requirement.name)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/api.py", line 126, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/api.py", line 870, in get_collection_versions
    error_context_msg=error_context_msg, cache=True)
  File "/usr/local/lib/python3.7/site-packages/ansible/module_utils/api.py", line 157, in run_function
    return call_retryable_function()
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/api.py", line 396, in _call_galaxy
    path_cache = self._cache[cache_id][url_info.path]
KeyError: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
The version of ansible-core you are using is unsupported at this time.  This issue has been resolved in the following versions of ansible-core:

v2.12.8
v2.13.3
v2.14.0 (and all newer versions)

* https://github.com/ansible/ansible/issues/77911
* https://github.com/ansible/ansible/pull/78325

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jesperes** [comment]
_inserting sad panda emoji_

Thanks for the fast reply.
