### ISSUE TITLE
paramiko transport log issue

### ISSUE THREAD

**Issue by goozbach** [ansible/ansible#820]
fatal: [HOSTNAME.EXAMPLE>COM] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/**init**.py", line 451, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 497, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 598, in _executor_internal_inner
    self._delete_remote_files(conn, tmp)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 178, in _delete_remote_files
    self._low_level_exec_command(conn, "rm -rf %s" % filename, None)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 631, in _low_level_exec_command
    stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable)
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection/paramiko_ssh.py", line 84, in exec_command
    chan = self.ssh.get_transport().open_session()
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 648, in open_session
    return self.open_channel('session')
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 738, in open_channel
    raise e
error: [Errno 104] Connection reset by peer

**Comment by mpdehaan** [comment]
temporary network issue?
