### ISSUE TITLE
Async task with poll:0 traceback with skipped task.

### ISSUE THREAD

**Issue by tom--** [ansible/ansible#8293]
##### Issue Type:

Bug Report
##### Ansible Version:
- devel 4a8e0688555e7dcccb84732962d00af0b8274431
- ansible 1.6.8
- ansible 1.6.6
- ansible 1.6.1
##### Environment:
- Probably N/A
- Control: OS X 10.9.4
- Target: Ubuntu 14.04
##### Summary:

A "fire and forget" async task (i.e. with `poll: 0`) in an include file crashes Ansible if the task that includes that file is skipped because its `when:` evaluates false.
##### Steps To Reproduce:

bar.yml:

```
- command: nc -l 4567
  async: 30
  poll: 0
```

In main playbook:

```
- include: bar.yml
  when: False
```
##### Expected Results:

Ansible skips everything in `bar.yml`
##### Actual Results:

Ansible crashes when skipping the async task, apparently looking for a job it didn't create.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.6.6/libexec/bin/ansible-playbook", line 5, in <module>
    pkg_resources.run_script('ansible==1.6.6', 'ansible-playbook')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1207, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/Cellar/ansible/1.6.6/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 317, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.6.6/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 257, in main
    pb.run()
  File "/usr/local/Cellar/ansible/1.6.6/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/playbook/__init__.py", line 323, in run
    if not self._run_play(play):
  File "/usr/local/Cellar/ansible/1.6.6/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/playbook/__init__.py", line 677, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/local/Cellar/ansible/1.6.6/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/playbook/__init__.py", line 453, in _run_task
    results = self._run_task_internal(task)
  File "/usr/local/Cellar/ansible/1.6.6/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/playbook/__init__.py", line 417, in _run_task_internal
    self.runner_callbacks.on_async_ok(host, res, poller.runner.vars_cache[host]['ansible_job_id'])
KeyError: 'ansible_job_id'
```

**Comment by mpdehaan** [comment]
Not sure this has anything to do with the include but just a skipped async task in general.

**Comment by tom--** [comment]
Duplicate
