### ISSUE TITLE
Ansible crashing on Yosemite (edit: OS X 10.10, problem with markupsafe upstream)

### ISSUE THREAD

**Issue by coryfklein** [ansible/ansible#8361]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 5, in <module>
    pkg_resources.run_script('ansible==1.7', 'ansible')
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 534, in run_script
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 1434, in run_script
  File "/usr/local/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/EGG-INFO/scripts/ansible", line 25, in <module>
    from ansible.runner import Runner
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/**init**.py", line 32, in <module>
    import jinja2
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/**init**.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/utils.py", line 520, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "/Library/Python/2.7/site-packages/markupsafe/**init**.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ImportError: No module named _compat
##### Environment:

Mac OS X 10.10 Yosemite
##### Summary:

When I run `ansible` on OS X 10.10 it crashes immediately, complaining `No module named _compat`.
##### Steps To Reproduce:

```
git clone https://github.com/ansible/ansible.git
cd ansible
python ./setup.py build
sudo python ./setup.py install
ansible
```
##### Expected Results:

I would expect ansible to run and not crash.
##### Actual Results:

Instead, ansible crashes and I get this output

```
$ ansible
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 5, in <module>
    pkg_resources.run_script('ansible==1.7', 'ansible')
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 534, in run_script
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 1434, in run_script
  File "/usr/local/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/EGG-INFO/scripts/ansible", line 25, in <module>
    from ansible.runner import Runner
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 32, in <module>
    import jinja2
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/utils.py", line 520, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "/Library/Python/2.7/site-packages/markupsafe/__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ImportError: No module named _compat
```

**Comment by mpdehaan** [comment]
Sounds like your version of markupsafe might _not_ be up to date from http://stackoverflow.com/questions/8108741/google-app-engine-jinja2-importerror-no-module-named-markupsafe ?

**Comment by mpdehaan** [comment]
Ok that's about "_compat".   I'm taking a look through markupsafe's bug tracker/history now.

**Comment by mpdehaan** [comment]
Upstream seems to indicate this is a problem with brew.  I recall I think from your tweet that you may have installed with brew, could it have got markupsafe from there?

https://github.com/mitsuhiko/markupsafe/issues/35

Can you try removing markupsafe and trying to install just from the one source, like pip?

**Comment by coryfklein** [comment]
Turns out somehow my instance of `markupsafe` was missing a file. Copying `_compat` from the `markupsafe` github repo into `/Library/Python/2.7/site-packages/markupsafe/` resolved the problem.

I later ran into other issues with bad packages in that directory, and just did this:

`mv /Library/Python/2.7 /Library/Python/2.7.bak`

This caused python to look elsewhere (maybe to `homebrew`?) for dependencies, and resolved my problems.
