### ISSUE TITLE
ImportError: cannot import name atomic_move

### ISSUE THREAD

**Issue by alozovskoy** [ansible/ansible#8433]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.7

$ git log --pretty=oneline -n1
b40f1ddc1910557bd3facd720b40c56c66177343 Require python-crypto >= 2.6 for debian package builds
##### Environment:

RHEL 5, Debian 7.6
##### Summary:

WhenAnsible use paramiko i've ImportError.
##### Steps To Reproduce:

Use paramiko connection type, run any module\playbook.
##### Expected Results:

$ ansible 127.0.0.1 -m ping
localhost | success >> {
    "changed": false, 
    "ping": "pong"
}
##### Actual Results:

$ ansible 127.0.0.1 -m ping

localhost | FAILED => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/**init**.py", line 557, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 662, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 833, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/connection.py", line 31, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/utils/plugins.py", line 180, in get
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/paramiko_ssh.py", line 42, in <module>
    from ansible.module_utils.basic import atomic_move
ImportError: cannot import name atomic_move

**Comment by mpdehaan** [comment]
This has already been reverted on devel, so should be good to go!  Thanks for the report.

**Comment by alozovskoy** [comment]
Yes, now it work well!

```
$ ansible 127.0.0.1 -m ping --connection=paramiko
127.0.0.1 | success >> {
    "changed": false, 
    "ping": "pong"
}
```

Thanks a lot!!
