### ISSUE TITLE
ansible requires that LC_ALL is set on Linux

### ISSUE THREAD

**Issue by red-lichtie** [ansible/ansible#84408]
### Summary

All ansible commands fail with an error message regarding "unsupported locale setting".

```sh
$ ansible --version
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

I am forced to prefix the commands with LC_ALL
```sh
$ LC_ALL=en_GB.UTF-8 ansible --version
...
```

### Issue Type

Bug Report

### Component Name

ansible

### Ansible Version

```console
$ LC_ALL=en_GB.UTF-8 ansible --version
ansible [core 2.18.0]
  config file = /home/bm/.ansible.cfg
  configured module search path = ['/home/bm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/bm/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ LC_ALL=en_GB.UTF-8 ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/bm/.ansible.cfg
DEFAULT_HOST_LIST(/home/bm/.ansible.cfg) = ['/home/bm/.ansible/inventory.ini']
DEFAULT_ROLES_PATH(/home/bm/.ansible.cfg) = ['/home/bm/.ansible/roles', '/home/bm/code/personal', '/home/bm/code/personal/ansible-roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/bm/.ansible.cfg) = /home/bm/.ansible/vault-password
INTERPRETER_PYTHON(/home/bm/.ansible.cfg) = auto_silent
```

### OS / Environment

Arch Linux

Locale Configuration
```sh
$ cat /etc/locale.conf 
LANG=en_GB.UTF-8
```

```sh
$ grep -v "#" /etc/locale.gen
de_DE.UTF-8 UTF-8  
en_GB.UTF-8 UTF-8  
en_GB ISO-8859-1  
en_US.UTF-8 UTF-8 
```

```sh
$ locale -a
C
C.utf8
de_DE.utf8
en_GB
en_GB.iso88591
en_GB.utf8
en_US.utf8
POSIX
```

```sh
$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME=en_DE.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

### Steps to Reproduce

Run **any** ansible command without explicitly setting LC_ALL

### Expected Results

Ansible to work with the configuration that every other application uses.

### Actual Results

```console
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
You have an invalid setting for LC_TIME, which `locale` does not like. You can see this error in the output you provided:
```
$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
[...]
LC_TIME=en_DE.UTF-8
```

A similar error occurs when Python tries to use the default locale; the locale library finds that your settings are invalid, and fails. There's no requirement that `LC_ALL` be set, but anything that you *do* set needs to be valid.

```
$ echo $LC_ALL

$ python3 -c 'import locale; locale.setlocale(locale.LC_ALL, "")'

$ LC_TIME=en_DE.UTF-8 python3 -c 'import locale; locale.setlocale(locale.LC_ALL, "")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

$ LC_TIME=en_NZ.UTF-8 python3 -c 'import locale; locale.setlocale(locale.LC_ALL, "")'
```

**Comment by red-lichtie** [comment]
Hi flowerysong,

I looked at that so many times and didn't spot that, thanks.

```sh
$ LC_TIME=en_GB.UTF-8 ansible --version
bash: warning: setlocale: LC_TIME: cannot change locale (en_DE.UTF-8): No such file or directory
ansible [core 2.18.0]
  config file = /home/bm/.ansible.cfg
  configured module search path = ['/home/bm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/bm/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

Now I have to figure out where that is being set.

**Comment by red-lichtie** [comment]
KDE Plasma was messing with it. The offending file was: `$HOME/.config/plasma-localerc`
