### ISSUE TITLE
NoneType object is not iterable exception in acl module's normalize_permissions()

### ISSUE THREAD

**Issue by rsyring** [ansible/ansible#8502]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.0

This error is not present in 1.6.8 but is present in 1.7.0.
##### Environment:

Running from & managing: Ubuntu 14.04
##### Summary:

ACL module is throwing a NoneType exception.
##### Steps To Reproduce:

The task that causes this error:

```
acl: name={{ home_path }} entry="user:www-data:r-x" state=present
```

Where {{home_path}} resolves to something like "/home/someuser"
##### Expected Results:

```
TASK: [webapp-users | give Apache read access to {{home_path}}] *************** 
ok: [my.host.com]
```
##### Actual Results:

```
failed: [my.host.com] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-gbtlhahijqlpowtqtacnnsocenaxcrmf
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1407442919.75-109025318695049/acl", line 1635, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1407442919.75-109025318695049/acl", line 214, in main
    permissions = normalize_permissions(module.params.get('permissions'))
  File "/home/ansible/.ansible/tmp/ansible-tmp-1407442919.75-109025318695049/acl", line 107, in normalize_permissions
    for char in p:
TypeError: 'NoneType' object is not iterable
```

**Comment by rsyring** [comment]
updated description with template
