### ISSUE TITLE
set_fact cannot overwrite registered variables

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#8758]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.8 (devel)
##### Environment:

Debian, Ubuntu
##### Summary:

It seems that newly implemented fact caching prevents `set_fact` to overwrite registered variables. Test below has been run without fact caching enabled. I tried to `git bisect` exact commit, but i cannot run the test because ansible exits with a traceback about missing cache:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 28, in <module>
    import ansible.playbook
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 20, in <module>
    import ansible.runner
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 50, in <module>
    from ansible.cache import FactCache
ImportError: No module named cache
```

The commits that are not tested:
- https://github.com/ansible/ansible/commit/56f9328f9319086a2f5b84d6b7625ba5c70607c8
- https://github.com/ansible/ansible/commit/fb5a1403dd16c132280ecaa649ac74dcecf4d0df
- https://github.com/ansible/ansible/commit/aa419044c45e5227710b95fc5ddaaf3abb018f03
##### Steps To Reproduce:

This playbook is part of [backporter role](https://github.com/ginas/ginas/tree/master/playbooks/roles/ginas.backporter) which automatically backports Debian packages from Testing to Stable. In this particular code, I check if a specified package is installed, and if not, I replace the contents of `backporter_register_package_dpkg_version` with a fake version `0.0` which tells the other tasks in the role to create a backport.

```

---
- hosts: all
  vars:
    backporter_package: 'rubygems-integration'
  tasks:
    - name: Check installed package version
      shell: dpkg-query -W -f='${Version}\n' {{ backporter_package }} 2>/dev/null | sed -e 's/^.*://' || true
      register: backporter_register_package_dpkg_version
      when: backporter_package is defined and backporter_package
      changed_when: False

    - debug: var=backporter_register_package_dpkg_version

    - name: Force fake installed version if set and not found
      set_fact:
        backporter_register_package_dpkg_version:
          stdout: '0.0'

    - debug: var=backporter_register_package_dpkg_version
```
##### Expected Results:

In case that required package is not installed and cannot be found, next task overwrites the variable with `0.0` which lets other tasks know that they need to create a backport.

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [winterfell]

TASK: [Check installed package version] *************************************** 
ok: [winterfell]

TASK: [debug var=backporter_register_package_dpkg_version] ******************** 
ok: [winterfell] => {
    "backporter_register_package_dpkg_version": {
        "changed": false, 
        "cmd": "dpkg-query -W -f='${Version}\\n' rubygems-integration 2>/dev/null | sed -e 's/^.*://' || true", 
        "delta": "0:00:00.030281", 
        "end": "2014-08-26 16:12:37.354206", 
        "invocation": {
            "module_args": "dpkg-query -W -f='${Version}\\n' rubygems-integration 2>/dev/null | sed -e 's/^.*://' || true", 
            "module_name": "shell"
        }, 
        "rc": 0, 
        "start": "2014-08-26 16:12:37.323925", 
        "stderr": "", 
        "stdout": "", 
        "stdout_lines": []
    }
}

TASK: [Force fake installed version if set and not found] ********************* 
ok: [winterfell]

TASK: [debug var=backporter_register_package_dpkg_version] ******************** 
ok: [winterfell] => {
    "backporter_register_package_dpkg_version": {
        "stdout": "0.0"
    }
}

PLAY RECAP ******************************************************************** 
winterfell                 : ok=5    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

In the actual results, variable is not replaced which makes the subsequent tasks to not be executed:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [winterfell]

TASK: [Check installed package version] *************************************** 
ok: [winterfell]

TASK: [debug var=backporter_register_package_dpkg_version] ******************** 
ok: [winterfell] => {
    "backporter_register_package_dpkg_version": {
        "changed": false, 
        "cmd": "dpkg-query -W -f='${Version}\\n' rubygems-integration 2>/dev/null | sed -e 's/^.*://' || true", 
        "delta": "0:00:00.052531", 
        "end": "2014-08-26 16:07:13.386642", 
        "invocation": {
            "module_args": "dpkg-query -W -f='${Version}\\n' rubygems-integration 2>/dev/null | sed -e 's/^.*://' || true", 
            "module_name": "shell"
        }, 
        "rc": 0, 
        "start": "2014-08-26 16:07:13.334111", 
        "stderr": "", 
        "stdout": "", 
        "stdout_lines": []
    }
}

TASK: [Force fake installed version if set and not found] ********************* 
ok: [winterfell]

TASK: [debug var=backporter_register_package_dpkg_version] ******************** 
ok: [winterfell] => {
    "backporter_register_package_dpkg_version": {
        "changed": false, 
        "cmd": "dpkg-query -W -f='${Version}\\n' rubygems-integration 2>/dev/null | sed -e 's/^.*://' || true", 
        "delta": "0:00:00.052531", 
        "end": "2014-08-26 16:07:13.386642", 
        "invocation": {
            "module_args": "dpkg-query -W -f='${Version}\\n' rubygems-integration 2>/dev/null | sed -e 's/^.*://' || true", 
            "module_name": "shell"
        }, 
        "rc": 0, 
        "start": "2014-08-26 16:07:13.334111", 
        "stderr": "", 
        "stdout": "", 
        "stdout_lines": []
    }
}

PLAY RECAP ******************************************************************** 
winterfell                 : ok=5    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
set_fact variables are inventory scope at the same level as registered ones, so this is likely just a simple bug in the cache logic, it's definitely something we should allow without error.

**Comment by drybjed** [comment]
Here's a simplier playbook which reproduces this issue, tesed on 893f15b:

```
---
- hosts: all
  tasks:
    - name: Check stats of /etc/fstab
      command: ls -l /etc/fstab
      register: fstab_stats

    - name: Show stats
      debug: var=fstab_stats

    - name: Change the stats
      set_fact:
        fstab_stats: 'NO STATS!'

    - name: Show stats again
      debug: var=fstab_stats
```

**Comment by jimi-c** [comment]
Bisected to aa419044c45e5227710b95fc5ddaaf3abb018f03

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
