### ISSUE TITLE
Accelerated mode traceback

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#8799]
##### Issue Type:

Bug Report (From Mailing List User)
##### Ansible Version:

1.7.1
##### Environment:

Debian Testing
##### Summary:

Traceback from accelerated mode
##### Steps To Reproduce:

ansible-playbook reports.yml -vvvv --check --user=root --connection=ssh
##### Expected Results:

no traceback
##### Actual Results:

```
PLAY [lab2] ******************************************************************* 

GATHERING FACTS *************************************************************** 
attempting connection to 172.16.8.191 via the accelerated port 5099
connection to 172.16.8.191 failed, retrying...
connection to 172.16.8.191 failed, retrying...
connection to 172.16.8.191 failed, retrying...
Could not connect via the accelerated connection, exceeded # of tries
Falling back to ssh to startup accelerated mode
attempting to start up the accelerate daemon...
<172.16.8.191> ESTABLISH CONNECTION FOR USER: root
fatal: [172.16.8.191] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 528, in _executor                                                                                  
    exec_rc = self._executor_internal(host, new_stdin)                                               
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 630, in _executor_internal                                                                         
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)                                                                               
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 801, in _executor_internal_inner                                                                   
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)                                                                          
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/connection.py", line 34, in connect                                                                                   
    self.active = conn.connect()                                                                     
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/accelerate.py", line 146, in connect                                                               
    res = self._execute_accelerate_module()                                                          
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/accelerate.py", line 104, in _execute_accelerate_module                                            
    tmp_path = self.runner._make_tmp_path(self.ssh)                                                  
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 1036, in _make_tmp_path                                                                            
    cmd = conn.shell.mkdtemp(basefile, use_system_tmp, tmp_mode)                                     
AttributeError: 'Connection' object has no attribute 'shell'
```

Proposed fix (which we may not want to tweak was):

```
> diff ./build/lib.linux-x86_64-2.7/ansible/runner/connection_plugins/accelerate.py /usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/accelerate.py
103a104,105
>         if not getattr(self.ssh, 'shell', None):
>             self.ssh.shell = utils.plugins.shell_loader.get('sh')
```

**Comment by jimi-c** [comment]
Merged in the above and pushed to devel.
