### ISSUE TITLE
Repeated nested role dependencies throw a traceback in ansible-galaxy

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#8890]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.8 (devel)
##### Environment:

Debian, Ubuntu
##### Summary:

Multiple roles in [DebOps](http://debops.org/) project have the same role dependencies; currently the most popular ones are `debops.ferm` and `debops.nginx` for firewall and webserver management, respectively.

At the moment `ansible-galaxy` throws a traceback error with at last one role, `debops.rails_deploy`, which uses a few other roles that use the same role dependencies.
##### Steps To Reproduce:

```
mkdir /tmp/test-galaxy && cd /tmp/test-galaxy
ansible-galaxy -p test install debops.rails_deploy
```
##### Expected Results:

All roles and their dependencies are installed without error.
##### Actual Results:

```
- downloading role 'rails_deploy', owned by debops
- downloading role from https://github.com/debops/ansible-rails_deploy/archive/master.tar.gz
- extracting debops.rails_deploy to test/debops.rails_deploy
- debops.rails_deploy was installed successfully
- adding dependency: debops.etc_services
- adding dependency: debops.nodejs
- adding dependency: debops.postgresql
- adding dependency: debops.mysql
- adding dependency: debops.nginx
- adding dependency: debops.monit
- adding dependency: debops.secret
- adding dependency: debops.ruby
- adding dependency: debops.redis
- downloading role 'etc_services', owned by debops
- downloading role from https://github.com/debops/ansible-etc_services/archive/master.tar.gz
- extracting debops.etc_services to test/debops.etc_services
- debops.etc_services was installed successfully
- downloading role 'nodejs', owned by debops
- downloading role from https://github.com/debops/ansible-nodejs/archive/master.tar.gz
- extracting debops.nodejs to test/debops.nodejs
- debops.nodejs was installed successfully
- downloading role 'postgresql', owned by debops
- downloading role from https://github.com/debops/ansible-postgresql/archive/master.tar.gz
- extracting debops.postgresql to test/debops.postgresql
- debops.postgresql was installed successfully
- dependency debops.etc_services is already installed, skipping.
- adding dependency: debops.ferm
- downloading role 'mysql', owned by debops
- downloading role from https://github.com/debops/ansible-mysql/archive/master.tar.gz
- extracting debops.mysql to test/debops.mysql
- debops.mysql was installed successfully
- adding dependency: debops.ferm
- downloading role 'nginx', owned by debops
- downloading role from https://github.com/debops/ansible-nginx/archive/master.tar.gz
- extracting debops.nginx to test/debops.nginx
- debops.nginx was installed successfully
- adding dependency: debops.apt_preferences
- adding dependency: debops.ferm
- downloading role 'monit', owned by debops
- downloading role from https://github.com/debops/ansible-monit/archive/master.tar.gz
- extracting debops.monit to test/debops.monit
- debops.monit was installed successfully
- adding dependency: debops.apt_preferences
- dependency debops.etc_services is already installed, skipping.
- downloading role 'secret', owned by debops
- downloading role from https://github.com/debops/ansible-secret/archive/master.tar.gz
- extracting debops.secret to test/debops.secret
- debops.secret was installed successfully
- downloading role 'ruby', owned by debops
- downloading role from https://github.com/debops/ansible-ruby/archive/master.tar.gz
- extracting debops.ruby to test/debops.ruby
- debops.ruby was installed successfully
- adding dependency: debops.backporter
- downloading role 'redis', owned by debops
- downloading role from https://github.com/debops/ansible-redis/archive/master.tar.gz
- extracting debops.redis to test/debops.redis
- debops.redis was installed successfully
- adding dependency: debops.apt_preferences
- dependency debops.etc_services is already installed, skipping.
- adding dependency: debops.ferm
- downloading role 'ferm', owned by debops
- downloading role from https://github.com/debops/ansible-ferm/archive/master.tar.gz
- extracting debops.ferm to test/debops.ferm
- debops.ferm was installed successfully
- downloading role 'ferm', owned by debops
- downloading role from https://github.com/debops/ansible-ferm/archive/master.tar.gz
- extracting debops.ferm to test/debops.ferm
- error: the specified role debops.ferm appears to already exist. Use --force to replace it.
Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 897, in <module>
    main()
  File "/usr/bin/ansible-galaxy", line 891, in main
    fn(args, options, parser)
  File "/usr/bin/ansible-galaxy", line 801, in execute_install
    os.unlink(tmp_file)
OSError: [Errno 2] No such file or directory: '/tmp/tmpcQLUX2'
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
