### ISSUE TITLE
ec2_asg: boto objects don't JSON stringify

### ISSUE THREAD

**Issue by tphummel** [ansible/ansible#9176]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.8 (devel 6af5455edc) last updated 2014/09/26 13:56:36 (GMT -700)
##### Environment:

running from osx 10.9.4. controlling ubuntu 14.04
##### Summary:

boto Tag objects do not JSON encode. 
##### Steps To Reproduce:

https://gist.github.com/tphummel/7206f1842e4b26d8d02b
##### Expected Results:

successful run of play and output json result without error
##### Actual Results:

LC, ASG action complete but play fails trying to encode `asg_properties` as JSON, specifically the `tags` list in this example. 

`TypeError: Tag(Name=my-custom-tag-value) is not JSON serializable`

here is a dump of the entire `asg_properties` prior to failure: 

```
{'availability_zones': [u'us-west-2c'],
 'default_cooldown': 300,
 'desired_capacity': 1,
 'health_check_period': 60,
 'health_check_type': u'ELB',
 'healthy_instances': 1,
 'in_service_instances': 1,
 'instance_facts': {u'i-87eb6a88': {'health_status': u'Healthy',
                                    'launch_config_name': u'lc-111111',
                                    'lifecycle_state': u'InService'}},
 'instances': [u'i-87eb6a88'],
 'launch_config_name': u'lc-111111',
 'load_balancers': [u'lb-test'],
 'max_size': 1,
 'min_size': 1,
 'name': u'health-server-group',
 'pending_instances': 0,
 'placement_group': None,
 'tags': [Tag(Name=test-server)],
 'terminating_instances': 0,
 'termination_policies': [u'Default'],
 'unhealthy_instances': 0,
 'viable_instances': 1,
 'vpc_zone_identifier': u'subnet-1111111'}
```

the `tags` key is type `<class 'boto.resultset.ResultSet'>`. and the value at index 0 is type `<class 'boto.ec2.autoscale.tag.Tag'>`

I can skirt the error by doing `asg_properties.pop('tags', None)` on the line prior to `module.exit_json` at the bottom of `library/cloud/ec2_asg`

**Comment by mpdehaan** [comment]
Can you please include the full traceback from ansible/boto if available?

Thanks!

**Comment by mpdehaan** [comment]
Also: can you share the ansible output in context so it's clear exactly what task failed?  (like the TASK header above the traceback)

Also also thanks!

**Comment by tphummel** [comment]
@mpdehaan for sure. thank you for looking at this.

```
➜  ops git:(master) ✗ ansible-playbook -i 127.0.0.1, rolling-deploy.yml -e ami_name=app-pkg.tar.gz -e ami_id=ami-xxx -vvvv

PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
<127.0.0.1> REMOTE_MODULE setup
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1411765111.87-140131684373457 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1411765111.87-140131684373457 && echo $HOME/.ansible/tmp/ansible-tmp-1411765111.87-140131684373457']
<127.0.0.1> PUT /var/folders/b0/wy4384qj3ddgd2s0b9ff0r780000gn/T/tmpNE8fJt TO /Users/tom/.ansible/tmp/ansible-tmp-1411765111.87-140131684373457/setup
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/tom/.ansible/tmp/ansible-tmp-1411765111.87-140131684373457/setup; rm -rf /Users/tom/.ansible/tmp/ansible-tmp-1411765111.87-140131684373457/ >/dev/null 2>&1']
ok: [127.0.0.1]

TASK: [create new launch config] ********************************************** 
<127.0.0.1> REMOTE_MODULE ec2_lc security_groups=sg-xxx image_id=ami-xxx region=us-west-2 key_name=colin-connecthq instance_type=t2.micro name=lc-app-pkg.tar.gz
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1411765113.65-92020214999138 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1411765113.65-92020214999138 && echo $HOME/.ansible/tmp/ansible-tmp-1411765113.65-92020214999138']
<127.0.0.1> PUT /var/folders/b0/wy4384qj3ddgd2s0b9ff0r780000gn/T/tmp2CKYMy TO /Users/tom/.ansible/tmp/ansible-tmp-1411765113.65-92020214999138/ec2_lc
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/tom/.ansible/tmp/ansible-tmp-1411765113.65-92020214999138/ec2_lc; rm -rf /Users/tom/.ansible/tmp/ansible-tmp-1411765113.65-92020214999138/ >/dev/null 2>&1']
ok: [127.0.0.1] => {"arn": "arn:aws:autoscaling:us-west-2:yyy:launchConfiguration:zzz:launchConfigurationName/lc-app-pkg.tar.gz", "changed": false, "created_time": "2014-09-24 22:17:16.999000", "image_id": "ami-xxx", "instance_type": "t2.micro", "name": "lc-app-pkg.tar.gz", "security_groups": ["sg-xxx"]}

TASK: [debug var=lc_result] *************************************************** 
ok: [127.0.0.1] => {
    "lc_result": {
        "arn": "arn:aws:autoscaling:us-west-2:yyy:launchConfiguration:zzz:launchConfigurationName/lc-app-pkg.tar.gz", 
        "changed": false, 
        "created_time": "2014-09-24 22:17:16.999000", 
        "image_id": "ami-xxx", 
        "instance_type": "t2.micro", 
        "invocation": {
            "module_args": "", 
            "module_name": "ec2_lc"
        }, 
        "name": "lc-app-pkg.tar.gz", 
        "security_groups": [
            "sg-xxx"
        ]
    }
}

TASK: [update autoscale group with new launch config] ************************* 
<127.0.0.1> REMOTE_MODULE ec2_asg replace_batch_size=1 vpc_zone_identifier=subnet-ea042bac load_balancers=health-server-test max_size=1 launch_config_name=lc-app-pkg.tar.gz health_check_type=ELB state=present desired_capacity=1 min_size=1 region=us-west-2 name=health-server-group availability_zones=us-west-2c
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805 && echo $HOME/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805']
<127.0.0.1> PUT /var/folders/b0/wy4384qj3ddgd2s0b9ff0r780000gn/T/tmpCy4eHu TO /Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ec2_asg
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ec2_asg; rm -rf /Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ >/dev/null 2>&1']
^[^[failed: [127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ec2_asg", line 2315, in <module>
    main()
  File "/Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ec2_asg", line 2313, in main
    module.exit_json( changed = changed, **asg_properties )
  File "/Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ec2_asg", line 1370, in exit_json
    print self.jsonify(kwargs)
  File "/Users/tom/.ansible/tmp/ansible-tmp-1411765113.99-182850459403805/ec2_asg", line 1348, in jsonify
    return json.dumps(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Tag(Name=health-server) is not JSON serializable


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/tom/rolling-deploy.retry

127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=1
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
