### ISSUE TITLE
skipped async task on 1.7.2 KeyError: 'ansible_job_id'. latest dev  'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by uncreative** [ansible/ansible#9180]
##### Issue Type:

skipped async tasks die with KeyError: 'ansible_job_id'
##### Ansible Version:

$ ansible-playbook --version
ansible-playbook 1.7.2
or
$ ansible --version
ansible 1.8 (devel ffee9a8fe0) last updated 2014/09/26 17:42:24 (GMT -700)
##### Environment:

OS X 10.9.5
##### Summary:

latest and 1.7.2 ansible are crashing with async tasks

Per: https://github.com/ansible/ansible/pull/7621 I thought it would be fixed for ansible 1.7.2
I did a fresh ansible install of OS X and ansible with v1.7.2 and it isn't working for a different reason
##### Steps To Reproduce:

sudo pip install git+https://github.com/ansible/ansible.git@v1.7.2

create playtest.yml:

```
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: do nothing
    command: "/bin/sleep"
    async: 45
    poll: 0
    when: False
```

run it: 

```
$ ansible-playbook playtest.yml

PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [open subl handler] ***************************************************** 
skipping: [127.0.0.1]
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 339, in run
    if not self._run_play(play):
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 695, in _run_play
    if not self._run_task(play, task, False):
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 471, in _run_task
    results = self._run_task_internal(task)
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 435, in _run_task_internal
    self.runner_callbacks.on_async_ok(host, res, poller.runner.vars_cache[host]['ansible_job_id'])
KeyError: 'ansible_job_id'
```

instead upgrade ansible to latest git version

```
$ ansible --version
ansible 1.8 (devel ffee9a8fe0) last updated 2014/09/26 17:42:24 (GMT -700)

$ ansible-playbook playtest.yml 
Traceback (most recent call last):
  File "/Users/agoldin/code/external/ansible/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/agoldin/code/external/ansible/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/Users/agoldin/code/external/ansible/lib/ansible/playbook/__init__.py", line 313, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Users/agoldin/code/external/ansible/lib/ansible/playbook/play.py", line 160, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Users/agoldin/code/external/ansible/lib/ansible/playbook/play.py", line 600, in _load_tasks
    role_name=role_name
  File "/Users/agoldin/code/external/ansible/lib/ansible/playbook/task.py", line 69, in __init__
    if x in utils.plugins.module_finder:
  File "/Users/agoldin/code/external/ansible/lib/ansible/utils/plugins.py", line 186, in has_plugin
    return self.find_plugin(name) is not None
  File "/Users/agoldin/code/external/ansible/lib/ansible/utils/plugins.py", line 175, in find_plugin
    for i in self._get_paths():
  File "/Users/agoldin/code/external/ansible/lib/ansible/utils/plugins.py", line 129, in _get_paths
    configured_paths = self.config.split(os.pathsep)
AttributeError: 'NoneType' object has no attribute 'split'
```
##### Expected Results:

task is skipped and nothing happens
##### Actual Results:

task is skipped followed by a crash for 1.7.2 and latest dev

**Comment by sivel** [comment]
I believe this was recently fixed in #7621

**Comment by sivel** [comment]
Looks like the 1.7.2 bug is fixed. The bug in devel appears to be completely different and likely related to moving the modules.

**Comment by uncreative** [comment]
I also noted https://github.com/ansible/ansible/pull/7621 but it seems to have been fixed 15 days ago and the 1.7.2 was released 2 days ago, so shouldn't the fix be inside?

**Comment by sivel** [comment]
Should it have been?  Maybe.  Was it?  No.

The message on #7621 indicates that it will be part of 1.8: "This has been merged in, and will also be included in the next major release".  Also see https://groups.google.com/forum/#!msg/ansible-project/7KSDd2V8DeQ/sgRL41Wc23wJ which reads:

> This fix was applied to the development branch (1.8), not 1.7.1,and did not happen to appear in the 1.7.2 dot release.

**Comment by uncreative** [comment]
Ah, I see. Sorry, I thought when it said next major release it meant 1.7.2. Didn't realized that was called a dot release. Thanks for the explanation.

**Comment by mpdehaan** [comment]
"and likely related to moving the modules."

I'm not sure about that.   But please link to that ticket.

async with poll: 0 was fixed on the devel branch, so I'm closing this ticket.

If there are different problems on the devel branch _please do_ open up a new bug.

Thanks!
