### ISSUE TITLE
Error when using URI module to send JSON body with variables - TypeError: must be string or buffer, not dict

### ISSUE THREAD

**Issue by lancehudson** [ansible/ansible#9472]
I am getting an error when attempt to send a JSON body in a URI POST that is using variables.

ansible 1.7.2
centos 7
python 2.7.5

playbook

``` yaml
- name: Run Facebook job
  hosts: all
  gather_facts: no

  vars:
    url: http://localhost:3001/job
    accounts:
      - 1
      - 2
    body:
      type: facebook
      data:
        title: "load"
        args:
          accountId: "{{item}}"
          facebookDatePreset: last_90_days

  tasks:
    - debug: var=body
      with_items: accounts

    - debug: msg="{{body | to_json}}"
      with_items: accounts

    - name: Call job for each account
      uri:
        method: POST
        HEADER_Content-Type: "application/json"
        url: "{{url}}"
        return_content: no
        body: "{{ body | to_json }}"
      with_items: accounts
```

error

```
-bash-4.2$ ansible-playbook -vvvv -i hosts job/facebook.yml --connection=local

PLAY [Run Facebook job] *******************************************************

TASK: [debug var=body] ********************************************************
ok: [127.0.0.1] => (item=1) => {
    "body": {
        "data": {
            "args": {
                "accountId": "1",
                "facebookDatePreset": "last_90_days"
            },
            "title": "load"
        },
        "type": "facebook"
    },
    "item": 1
}
ok: [127.0.0.1] => (item=2) => {
    "body": {
        "data": {
            "args": {
                "accountId": "2",
                "facebookDatePreset": "last_90_days"
            },
            "title": "load"
        },
        "type": "facebook"
    },
    "item": 2
}

TASK: [debug msg="{"data": {"args": {"facebookDatePreset": "last_90_days", "accountId": "{{item}}"}, "title": "load"}, "type": "facebook"}"] ***
ok: [127.0.0.1] => (item=1) => {
    "item": 1,
    "msg": "{\"type\": \"facebook\", \"data\": {\"args\": {\"accountId\": \"1\", \"facebookDatePreset\": \"last_90_days\"}, \"title\": \"load\"}}"
}
ok: [127.0.0.1] => (item=2) => {
    "item": 2,
    "msg": "{\"type\": \"facebook\", \"data\": {\"args\": {\"accountId\": \"2\", \"facebookDatePreset\": \"last_90_days\"}, \"title\": \"load\"}}"
}

TASK: [Call job for each account] ********************************************
<127.0.0.1> REMOTE_MODULE uri method=POST HEADER_Content-Type=application/json url=http://localhost:3000
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862 && echo $HOME/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862']
<127.0.0.1> PUT /tmp/tmpAAXWec TO /var/lib/awx/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862/uri
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862/uri; rm -rf /var/lib/awx/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862/ >/dev/null 2>&1']
failed: [127.0.0.1] => (item=1) => {"failed": true, "item": 1, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862/uri", line 1791, in <module>
    main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862/uri", line 403, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1415045002.95-30498840200862/uri", line 302, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1605, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1353, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1290, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: must be string or buffer, not dict

<127.0.0.1> REMOTE_MODULE uri method=POST HEADER_Content-Type=application/json url=http://localhost:3000
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607 && echo $HOME/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607']
<127.0.0.1> PUT /tmp/tmpJlkZy0 TO /var/lib/awx/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607/uri
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607/uri; rm -rf /var/lib/awx/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607/ >/dev/null 2>&1']
failed: [127.0.0.1] => (item=2) => {"failed": true, "item": 2, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607/uri", line 1791, in <module>
    main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607/uri", line 403, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1415045003.04-25850512266607/uri", line 302, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1605, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1353, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1290, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: must be string or buffer, not dict


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/var/lib/awx/facebook.retry

127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1
```

**Comment by lancehudson** [comment]
It works if I hard code the body like so:

``` yaml
- name: Run Facebook job
  hosts: all
  gather_facts: no

  vars:
    url: http://localhost:3001/job
    accounts:
      - 1
      - 2

  tasks:
    - name: Call job for each account
      uri:
        method: POST
        HEADER_Content-Type: "application/json"
        url: "{{url}}"
        return_content: yes
        body: "{\"type\": \"facebook\", \"data\": {\"args\": {\"accountId\": \"1\", \"facebookDatePreset\": \"last_90_days\"}, \"title\": \"load\"} }"
      with_items: accounts
```

as soon as I attempt to put the variable in I get the same error as above

``` yaml
- name: Run Facebook job
  hosts: all
  gather_facts: no

  vars:
    url: http://localhost:3001/job
    accounts:
      - 1
      - 2

  tasks:
    - name: Call job for each account
      uri:
        method: POST
        HEADER_Content-Type: "application/json"
        url: "{{url}}"
        return_content: yes
        body: "{\"type\": \"facebook\", \"data\": {\"args\": {\"accountId\": \"{{item}}\", \"facebookDatePreset\": \"last_90_days\"}, \"title\": \"load\"} }"
      with_items: accounts
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
