### ISSUE TITLE
apt update_cache explodes when it fails to get URL due to hash mismatch

### ISSUE THREAD

**Issue by ayush-sharma** [ansible/ansible#9483]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Vagrant 1.6.5 running ubuntu/trusty64
##### Summary:

Got an error running apt update_cache due to a URL hash mismatch. I did a manual `apt-get update` on the target machine and the error does in fact show up there, I guess it causes the entire playbook to stop.
##### Expected Results:

I think there should possibly be a separate flag dealing with this error condition, something like `skip-hash-mismatch-error`?
##### Actual Results:

Running the aforementioned task caused the playbook to exit abnormally with the following stacktrace:

`````` python
TASK: [update apt cache] ******************************************************
<192.168.68.136> ESTABLISH CONNECTION FOR USER: ubuntu
<192.168.68.136> REMOTE_MODULE apt update_cache=yes cache_valid_time=3600 CHECKMODE=True
<192.168.68.136> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-
o', 'ControlPath=/home/vagrant/.ansible/c
p/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostba
sed,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', '192.168.68.136', "/bin/sh -c 'mkdir -p $HOME/.ansi
ble/tmp/ansible-tmp-1415131830.58-175843052367358 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1415131830.58-175843052367358 && echo $HOME/.ansible/tm
p/ansible-tmp-1415131830.58-175843052367358'"]
<192.168.68.136> PUT /tmp/tmpE45LZy TO /home/ubuntu/.ansible/tmp/ansible-tmp-1415131830.58-175843052367358/apt
<192.168.68.136> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/vagrant/.ansible/c
p/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostba
sed,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', '192.168.68.136', u'/bin/sh -c \'sudo -k && sudo -H
 -S -p "[sudo via ansible, key=lfstckzacfxfyqlbsetmbzbwyaahjpcl] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-lfstckzacfxfyqlbsetmbzbwyaah
jpcl; LANG=C LC_CTYPE=C /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1415131830.58-175843052367358/apt; rm -rf /home/ubuntu/.ansible/tmp/ansi
ble-tmp-1415131830.58-175843052367358/ >/dev/null 2>&1\'"\'"\'\'']
failed: [192.168.68.136] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-lfstckzacfxfyqlbsetmbzbwyaahjpcl
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1415131830.58-175843052367358/apt", line 1907, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1415131830.58-175843052367358/apt", line 507, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/i18n/Translation-en  Hash Sum mismatch
, W:Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/universe/i18n/Translation-en  Hash Sum mismatch
, E:Some index files failed to download. They have been ignored, or old ones used instead.
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 1720
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 8
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to 192.168.68.136 closed.


FATAL: all hosts have already failed -- aborting```

##### Steps To Reproduce:

Execute the following task:
```yaml
- name: update apt cache
    apt: update_cache=yes cache_valid_time=3600```
``````

**Comment by keyurshah** [comment]
having the same issue. thanks.

**Comment by montague** [comment]
i just ran into this as well.

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
