### ISSUE TITLE
Callbacks.py error handling fails on unicode error messages

### ISSUE THREAD

**Issue by andrewvc** [ansible/ansible#9504]
I recently hit an issue where ansible erroneously spits out the following error: 

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 517: ordinal not in range(128);
```

This error is erroneous, it is a bug in callbacks.py 's handling of unicode, and masks the real error. This makes diagnosing errors very confusing, since it _looks_ like an individual task failed due to some error in python/module code, but in fact it was due, in this case, to a full disk on a server. 

```
Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415286883.75-104875145998684 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1415286883.75-104875145998684 && echo $HOME/.ansible/tmp/ansible-tmp-1415286883.75-104875145998684, exited with result 1: mkdir: cannot create directory ‘/home/ubuntu/.ansible/tmp/ansible-tmp-1415286883.75-104875145998684’: No space left on device
```

On a device w/ proper unicode it renders with fancy single quotes like:

![fullscreen_11_6_14__9_30_am](https://cloud.githubusercontent.com/assets/131427/4938234/f862f8aa-65c9-11e4-86d5-e145625f4b09.png)

Rendered as ASCII you can clearly see the issue in a hex editor

![foo](https://cloud.githubusercontent.com/assets/131427/4938171/730634a6-65c9-11e4-9573-d2e179c7d97c.png)

The code seems broken around here: https://github.com/ansible/ansible/blob/release1.7.2/lib/ansible/callbacks.py#L461
The stack trace for this bug is:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.7.2/libexec/bin/ansible-playbook", line 5, in <module>
    pkg_resources.run_script('ansible==1.7.2', 'ansible-playbook')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 249, in main
    pb.run()
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/playbook/__init__.py", line 339, in run
    if not self._run_play(play):
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/playbook/__init__.py", line 695, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/playbook/__init__.py", line 471, in _run_task
    results = self._run_task_internal(task)
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/playbook/__init__.py", line 426, in _run_task_internal
    results = runner.run()
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/runner/__init__.py", line 1281, in run
    results = [ self._executor(h, None) for h in hosts ]
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/runner/__init__.py", line 570, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/usr/local/Cellar/ansible/1.7.2/lib/python2.7/site-packages/ansible-1.7.2-py2.7.egg/ansible/callbacks.py", line 461, in on_unreachable
    msg = "fatal: [%s] => %s" % (host, results)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 517: ordinal not in range(128)
```

**Comment by jimi-c** [comment]
HI @andrewvc, going back through old issues to see if things have been corrected by the v2 (now devel) rewrite of certain parts of the code. One thing we've focused heavily on is proper unicode support from top to bottm, so I believe this issue should be resolved now. Could you please let us know if you've continued seeing this problem?

Thanks!

**Comment by andrewvc** [comment]
Don't use ansible anymore so I'll close this.

**Comment by abadger** [comment]
Also fixed this recently in https://github.com/ansible/ansible/issues/10960 for v1 although I still have to audit the v2 code and make sure it's fixed there.
