### ISSUE TITLE
'host not found' exception with host aliases

### ISSUE THREAD

**Issue by 0x44** [ansible/ansible#9528]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8 (devel 3ff8f01087) last updated 2014/11/10 16:58:15 (GMT +800)
  lib/ansible/modules/core: (devel 6317d3a988) last updated 2014/11/10 14:35:41 (GMT +800)
  lib/ansible/modules/extras: (devel 5a514ccdda) last updated 2014/11/10 14:35:58 (GMT +800)
  v2/ansible/modules/core: (devel 6317d3a988) last updated 2014/11/10 14:34:25 (GMT +800)
  v2/ansible/modules/extras: (devel 5a514ccdda) last updated 2014/11/10 14:35:10 (GMT +800)
  configured module search path = None
```
##### Environment:

N/A
##### Summary:

https://github.com/ansible/ansible/commit/f1267c0b053e5975dc08c151530c802015902242 causes 'host not found' exceptions when used with host aliases. I believe its due to https://github.com/ansible/ansible/commit/f1267c0b053e5975dc08c151530c802015902242#diff-af869caf5f6f46706dbf35970e39c686L1162.
##### Steps To Reproduce:

```
$ cat testhosts
testalias ansible_ssh_host=IP_ADDRESS testvar=testvalue

$ cat testplaybook.yml

---
- hosts: testalias
  gather_facts: False
  tasks:
    - copy:
        content="{{ testvar }}\n"
        dest=/tmp/testfile

$ ansible-playbook -i testhosts testplaybook.yml
```
##### Expected Results:

File '/tmp/testfile' with content 'testvalue' on host IP_ADDRESS.
##### Actual Results:

```
$ ansible-playbook -i testhosts testplaybook.yml

PLAY [testalias] **************************************************************

TASK: [copy content="{{ testvar }}\n" dest=/tmp/testfile] *********************
fatal: [testalias] => Traceback (most recent call last):
  File "/PATH/TO/ansible/lib/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/PATH/TO/ansible/lib/ansible/runner/__init__.py", line 755, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/PATH/TO/ansible/lib/ansible/runner/__init__.py", line 988, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/PATH/TO/ansible/lib/ansible/runner/action_plugins/copy.py", line 178, in run
    remote_checksum = self.runner._remote_checksum(conn, tmp_path, dest_file)
  File "/PATH/TO/ansible/lib/ansible/runner/__init__.py", line 1164, in _remote_checksum
    inject = self.get_inject_vars(conn.host)
  File "/PATH/TO/ansible/lib/ansible/runner/__init__.py", line 606, in get_inject_vars
    host_variables = self.inventory.get_variables(host, vault_password=self.vault_pass)
  File "/PATH/TO/ansible/lib/ansible/inventory/__init__.py", line 442, in get_variables
    raise Exception("host not found: %s" % hostname)
Exception: host not found: IP_ADDRESS


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/PATH/TO/testplaybook.retry

testalias                  : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by claco** [comment]
Pointed here by @sivel. Seeing this as well around any copy/template task using rax.py, which triggers this:

https://gist.github.com/claco/5aa788b12b07bc624433

**Comment by sivel** [comment]
I just double checked using git bisect, and arrived at the same commit: f1267c0b053e5975dc08c151530c802015902242

I'm thinking this should probably be a higher priority than P3.  We wouldn't want to see 1.8 pushed with this issue still present.

**Comment by abadger** [comment]
I thought this was one of the last things I fixed on Friday but it's quite possible that I got side tracked into another problem with this piece of code before committing.  I'll untangle my tree and make sure this gets fixed.

**Comment by abadger** [comment]
Okay, I think the fix is in this commit: https://github.com/ansible/ansible/commit/30c50020a1b6add9a461c94960dabfa4d73c08fd 

which I unfortunately didn't push until this morning.  Could you upgrade and give that a try?

**Comment by claco** [comment]
Fixes my issue. Thanks!

**Comment by 0x44** [comment]
Fixed. Thank you.
