### ISSUE TITLE
ssh + password auth + host key checking enabled = hangs [OSX]

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#9540]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8 (devel ffc2e5a627) last updated 2014/11/12 08:46:40 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 2970b339eb) last updated 2014/11/06 15:57:19 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ad181b7aa9) last updated 2014/11/06 15:57:33 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/06 15:57:45 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/06 15:57:58 (GMT +200)
  configured module search path = None
```
##### Environment:

OSX 10.9.5

```
$ pip list
duplicity (0.6.24)
ecdsa (0.11)
Jinja2 (2.7.2)
libvirt-python (1.2.9)
MarkupSafe (0.18)
mercurial (3.1.2)
msgpack-python (0.4.2)
paramiko (1.15.1)
pika (0.9.14)
pip (1.5.6)
py (1.4.25)
py-rrdtool (0.2.2)
pycrypto (2.6.1)
pytest (2.6.3)
PyYAML (3.10)
setuptools (5.4.2)
untangle (1.1.0)
vboxapi (1.0)
wsgiref (0.1.2)
xmltodict (0.9.0)
```
##### Summary:

ssh connection hangs when host key checking is enabled
##### Steps To Reproduce:

```
$ cat hosts
[vms]
trusty
$ ansible trusty -i hosts -k -m setup
SSH password:
<<< hangs here >>>
^C

$ (echo "[defaults]"; echo "host_key_checking = False") > ansible.cfg
$ ansible trusty -i hosts -k -m setup
SSH password:
trusty | success >> {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
... etc
```

Aside: the correct host key is already cached, at least for the command-line ssh client

```
$ ssh trusty hostname
brian@trusty's password:
trusty
```

But I know it's using paramiko because it gave an error about paramiko being required until I installed it (`sudo pip install paramiko`)
##### Expected Results:

Either would prompt to accept the host key, or would terminate with an error.
##### Actual Results:

Hangs as shown above, unless host key checking is turned off

**Comment by candlerb** [comment]
Additional note: when `^C` is pressed, here's the backtrace

```
$ ansible trusty -i hosts -k -m setup
SSH password:
^CTraceback (most recent call last):
  File "/Users/brian/git/ansible/bin/ansible", line 194, in <module>
    (runner, results) = cli.run(options, args)
  File "/Users/brian/git/ansible/bin/ansible", line 168, in run
    results = runner.run()
  File "/Users/brian/git/ansible/lib/ansible/runner/__init__.py", line 1418, in run
    results = [ self._executor(h, None) for h in hosts ]
  File "/Users/brian/git/ansible/lib/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/brian/git/ansible/lib/ansible/runner/__init__.py", line 755, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/brian/git/ansible/lib/ansible/runner/__init__.py", line 918, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/Users/brian/git/ansible/lib/ansible/runner/connection.py", line 51, in connect
    self.active = conn.connect()
  File "/Users/brian/git/ansible/lib/ansible/runner/connection_plugins/paramiko_ssh.py", line 136, in connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/Users/brian/git/ansible/lib/ansible/runner/connection_plugins/paramiko_ssh.py", line 152, in _connect_uncached
    ssh.load_system_host_keys()
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 98, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 103, in load
    if self.check(h, e.key):
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 198, in check
    k = self.lookup(hostname)
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 182, in lookup
    if h.startswith('|1|') and not hostname.startswith('|1|') and constant_time_bytes_eq(self.hash_host(hostname, h), h) or h == hostname:
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 274, in hash_host
    hmac = HMAC(salt, b(hostname), sha1).digest()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hmac.py", line 74, in __init__
    key = key + chr(0) * (blocksize - len(key))
KeyboardInterrupt
```

Also I have `HashKnownHosts no` in `/etc/ssh_config`, so here is the entry from the `known_hosts` file:

```
$ grep trusty ~/.ssh/known_hosts
trusty,192.168.56.13 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7VnS20dYEa6WFWVR/p6VyMzvitNW7cozh1jx9gmunamzUx0azlLoKq7nSa71Ao6uiLy11CFYRTkAsOuEUUBB8qErLH0lgSz3PfLyLjmPmAelKEyH4YGZ6BkZDrUlj+QZ+csLEUKe5khB89jGICtmty5Xdei1NeNwS3BOnlp5pJKc6mm1i8eO/Tu4yu4dk9zOlXrtH2up+uS+HGZq5MCC4oXB4lh1Mu8PdI+c6dzD6E/aNrf/FxZT4wBGSEfILo+fSPnDIKLt0kA71PMo+oZJ2lmd4RhUp3q0b53HnvD6D8pqR1xeyXFXAbLYn0ecX651XKQjID9tWv3cIYh2YDwfL
```

And the IP address is in `/etc/hosts`

```
$ grep trusty /etc/hosts
192.168.56.13   trusty
```

**Comment by candlerb** [comment]
I should also point out that I have python 2.7.8 from homebrew, which overrides python 2.7.5 from OSX, but I believe the former is being used consistently. Ansible uses `#!/usr/bin/env python` and this picks up the 2.7.8 version.

```
$ cat x.py
#!/usr/bin/env python
import sys
print sys.version

$ ./x.py
2.7.8 (default, Oct 19 2014, 16:03:53)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)]
$
```

**Comment by candlerb** [comment]
Turns out this is paramiko being ludicrously inefficient. My `~/.ssh/known_hosts` has 1158 entries, 556 of which are hashed.

```
>>> import paramiko.hostkeys
>>> hk = paramiko.hostkeys.HostKeys("/Users/brian/.ssh/known_hosts")
<< hangs here for 20 seconds >>
>>> 
```

So it works if you have enough patience.

```
$ time ansible trusty -i hosts -k -m setup
...
real    0m25.691s
user    0m22.818s
sys 0m0.184s
```
