### ISSUE TITLE
Ansible Connect windows : SSLError: [Errno 1] _ssl.c:1429: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error

### ISSUE THREAD

**Issue by geekwolf** [ansible/ansible#9577]
env:
Ansible control: Ubuntu 14.04.1 x64 Ansible1.8
client: windows server 2012 R2 x64

My Steps:

1.Control:
pip install http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm

cat /etc/ansible/hosts
[win2]
192.168.0.8
cat /etc/ansible/group_vars/win2.yml 
ansible_ssh_user: Administrator
ansible_ssh_pass: 3KRxuSezVdx5
ansible_ssh_port: 3389
ansible_connection: winrm
2.then I run the scripts on windows server 2012 R2:
upgrade_to_ps3.ps1
ConfigureRemotingForAnsible.ps1
https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 

3.the question:

root@instance-jb53h7st:~# ansible win2 -m win_ping

192.168.0.8 | FAILED => Traceback (most recent call last):
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/ansible-1.8-py2.7.egg/ansible/runner/**init**.py", line 588, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/ansible-1.8-py2.7.egg/ansible/runner/__init__.py", line 767, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/ansible-1.8-py2.7.egg/ansible/runner/__init__.py", line 930, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/ansible-1.8-py2.7.egg/ansible/runner/connection.py", line 51, in connect
    self.active = conn.connect()
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/ansible-1.8-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 132, in connect
    self.protocol = self._winrm_connect()
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/ansible-1.8-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 86, in _winrm_connect
    protocol.send_message('')
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message
    return self.transport.send_message(message)
  File "/usr/local/python2.7.8/lib/python2.7/site-packages/winrm/transport.py", line 82, in send_message
    response = urlopen(request, timeout=self.timeout)
  File "/usr/local/python2.7.8/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/python2.7.8/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/python2.7.8/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/python2.7.8/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/python2.7.8/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/local/python2.7.8/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python2.7.8/lib/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/usr/local/python2.7.8/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python2.7.8/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python2.7.8/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/python2.7.8/lib/python2.7/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/usr/local/python2.7.8/lib/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error
Can you help me ?

**Comment by cchurch** [comment]
This particular traceback has come up before, and we do want to make sure it is handled and generates a more useful error message.

However, in your case, try changing ansible_ssh_port to 5986 since you're connecting to WinRM over HTTPS (https://support.microsoft.com/kb/2019527) instead of remote desktop.

If you have further questions about getting started with Ansible for managing Windows hosts, please direct those to the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by nitzmahone** [comment]
closing for inactivity
