### ISSUE TITLE
blob/devel/plugins/inventory/ec2.py: no support for authentication via iam roles

### ISSUE THREAD

**Issue by bsdhsr** [ansible/ansible#9647]
Having followed AWS best practices, an Instance Profile with limited privileged was created, and the ansible instance (running on aws) was associated with it.

This way, no credentials need to be hardcoded in the instance itself.

I can confirm this works with awscli; below is a (very) trimmed down output from "aws ec2 describe-instances --region eu-west-1 --debug", running on the instance:

2014-11-27 07:09:43,934 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2014-11-27 07:09:43,934 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2014-11-27 07:09:43,934 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2014-11-27 07:09:43,935 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2014-11-27 07:09:43,935 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2014-11-27 07:09:43,935 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2014-11-27 07:09:43,935 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2014-11-27 07:09:43,946 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 169.254.169.254
2014-11-27 07:09:43,957 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 56
2014-11-27 07:09:43,959 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 169.254.169.254
2014-11-27 07:09:43,960 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /latest/meta-data/iam/security-credentials/XXXXXXXXX HTTP/1.1" 200 910
2014-11-27 07:09:43,961 - MainThread - botocore.credentials - INFO - Found credentials from IAM Role: XXXXXXXXX

Unfortunately, it is a very different story with ec2.py (renamed to just 'hosts' here):

Traceback (most recent call last):
  File "./hosts", line 738, in <module>
    Ec2Inventory()
  File "./hosts", line 166, in **init**
    self.do_api_calls_update_cache()
  File "./hosts", line 319, in do_api_calls_update_cache
    self.get_instances_by_region(region)
  File "./hosts", line 331, in get_instances_by_region
    conn = self.ec2_connect(region)
  File "./hosts", line 720, in ec2_connect
    conn = ec2.connect_to_region(region, **self.connect_args)
  File "/usr/lib/python2.7/dist-packages/boto/ec2/**init**.py", line 55, in connect_to_region
    for region in regions(**kw_params):
  File "/usr/lib/python2.7/dist-packages/boto/ec2/**init**.py", line 38, in regions
    c = EC2Connection(**kw_params)
  File "/usr/lib/python2.7/dist-packages/boto/ec2/connection.py", line 88, in **init**
    security_token)
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 852, in **init**
    security_token=security_token)
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 486, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.7/dist-packages/boto/auth.py", line 407, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials

There seems to be some work going on to address other forms of authentication (the above is already a patched ec2.py from https://github.com/ansible/ansible/pull/9505), but even then it won't work.

Perhaps I missed something?

**Comment by bsdhsr** [comment]
Maybe @RealSalmon can offer insight?

**Comment by RealSalmon** [comment]
@sersil - I can take a look at this, as I think the expected behavior should be that boto would use IAM roles as it would with anything else. Do you see this behavior regardless of whether or not you're using the changes in #9505 ? That is, do IAM roles work in the current stable version? I want to make sure those changes aren't breaking previously exising support.

Can you also please post the policy of the role that you are using when you get this exception?

**Comment by RealSalmon** [comment]
Testing the dynamic inventory ec2.py script in the current devel branch (using ec2.ini from the same), and also against #9505 works as expected for me using an IAM role with full read access.

boto==2.34.0
botocore==0.75.0

**Comment by bsdhsr** [comment]
@RealSalmon: To be clear:
- Had the same issues with standard ec2.py (that's what brought me to #9505)
- This is an IAM _role_ (a Role associated with an InstanceProfile associated with an Instance)   and not _user_, as in, I don't have AWS_\* or a .boto.cfg file at all -- just want to make sure we're on the same page on that one.
- The role policy is below (does it matter, though? I/awscli can get a temp. security token from the metadata server, and more to the point, awscli is working) 

{
"Statement":[{
  "Resource":["_"],
  "Action": 
["ec2:Describe_",
"elasticache:Describe_".
"rds:Describe_",
"rds:ListTagsForResource"],
"Effect":"Allow"}],
"Version":"2012-10-17"
}

And for completeness, the AssumeRolePolicyDocument:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}

**Comment by RealSalmon** [comment]
Yes, we are both talking about IAM Roles when we are talking about IAM Roles :-)

I suspect the issue has to do with the specific permissions in the role assigned to your instance. As I say, I have no problems using a role that grants full read access to the entire account (which is overkill). I would try that, and then step it down from there once it's confirmed to work if you wanted to get a full accounting of what permissions are absolutely neccessary.

**Comment by bsdhsr** [comment]
I have re-downloaded both files from #9505 just to be sure, as it's been a few days already.

The response (boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials) is immediate. I double checked with tcpdump, there is no traffic going out to query the metadata server either.

This is Debian GNU/Linux 7.6 (wheezy) 
 python-boto                        2.3.0-1
 ansible                            1.7.2+dfsg-2~bpo70+1

pip freeze:
 boto==2.3.0
 botocore==0.76.0

**Comment by bsdhsr** [comment]
Right, found it.

Everything works as expected when using boto 2.34.0 :)

**Comment by cchurch** [comment]
As indicated by the previous comments, IAM Roles are supported by [plugins/inventory/ec2.py](https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.py) when using [boto 2.5.0](http://boto.readthedocs.org/en/latest/releasenotes/v2.5.0.html) or higher.

When running on an EC2 instance that has an IAM Role assigned, and the role policy allows the `ec2:Describe*` action, `ec2.py --list` will work without the need to specify `aws_access_key_id` or `aws_secret_access_key`.

Additional actions will need to be allowed in the role policy if [ec2.ini](https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.ini) defines [route53 = True](https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.ini#L39) or [rds = True](https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.ini#L42).

**Comment by babatundebusari** [comment]
@cchurch 

as i type current version of boto is 2.48 So where did 2.5.0 (do you mean **2.50.0**???) so where does one get 2.50.0 from?
