### ISSUE TITLE
Host variable values may not contain spaces

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#973]
Latest devel code. Inventory file:

```
[local]
127.0.0.1 person="John Q"
```

produces:

```
Traceback (most recent call last):
  File "/Users/jpm/Auto/pubgit/ansible/ansible/bin/ansible-playbook", line 151, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/jpm/Auto/pubgit/ansible/ansible/bin/ansible-playbook", line 108, in main
    subset=options.subset,
  File "/Users/jpm/Auto/pubgit/ansible/ansible/lib/ansible/playbook/__init__.py", line 108, in __init__
    self.inventory        = ansible.inventory.Inventory(host_list)
  File "/Users/jpm/Auto/pubgit/ansible/ansible/lib/ansible/inventory/__init__.py", line 85, in __init__
    self.parser = InventoryParser(filename=host_list)
  File "/Users/jpm/Auto/pubgit/ansible/ansible/lib/ansible/inventory/ini.py", line 39, in __init__
    self._parse()
  File "/Users/jpm/Auto/pubgit/ansible/ansible/lib/ansible/inventory/ini.py", line 43, in _parse
    self._parse_base_groups()
  File "/Users/jpm/Auto/pubgit/ansible/ansible/lib/ansible/inventory/ini.py", line 111, in _parse_base_groups
    (k,v) = t.split("=")
ValueError: need more than 1 value to unpack
```

**Comment by mpdehaan** [comment]
Fixed in #f140332
