### ISSUE TITLE
Exception: host not found: {{ item }} when using templates and with_items

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#9763]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.8.2
  configured module search path = None
##### Environment:

Management node: Arch
Minions: Ubuntu 14.04
##### Summary:

Getting a backtrace using `with_items` and `template` module together
##### Steps To Reproduce:

With version 1.8.2, I get a backtrace using the following playbook:

``` yaml
- hosts: all
  tasks:
    - name: Deploys location configuration from application config
      template: >
        src="./nginx_location.conf.j2" 
        dest="/tmp/test.conf"
      with_items:
        - front0.example.org
        - front1.example.org
      delegate_to: "{{ item }}"
```
##### Expected Results:

Template should be deployed on frontends.
##### Actual Results:

Trying to run this, I get:

```
$ ansible-playbook test.yml -l some.host.org

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [some.host.org]

TASK: [Deploys location configuration from application config] **************** 
fatal: [some.host.org -> front0.example.org] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 818, in _executor_internal
    complex_args=complex_args
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1025, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/template.py", line 93, in run
    remote_checksum = self.runner._remote_checksum(conn, tmp, dest, inject)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1231, in _remote_checksum
    python_interp = inject['hostvars'][inject['delegate_to']].get('ansible_python_interpreter', 'python')
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 103, in __getitem__
    result = self.inventory.get_variables(host, vault_password=self.vault_password).copy()
  File "/usr/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 442, in get_variables
    raise Exception("host not found: %s" % hostname)
Exception: host not found: {{ item }}


FATAL: all hosts have already failed -- aborting
```

If I change `template: ...` to `command: /bin/hostname`, everything works as expected.
The template content is irrelevant (just static stuff, no vars inside).
##### Additionnal notes

I bissected this to commit e81a6da49b4bc142b4ec9a5d2c4e43d1a34aa408

**Comment by bcoca** [comment]
can you check against current development, there is a patch there that might have addressed this already

**Comment by leucos** [comment]
@bcoca you're right, it's fixed in devel. Sorry for the noise !
