### ISSUE TITLE
Error using gc_storage

### ISSUE THREAD

**Issue by Erouan50** [ansible/ansible#9794]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:
- Runing on Fedora 20 (kernel 3.17.4-200.fc20.x86_64)
- Managing on localhost
##### Summary:

I'm using the gc_storage to create new buckets with a directory object. Here the task :

``` yaml
- name: Create Bucket to store database wall
    gc_storage:
      gs_access_key: "{{gcs_access_key}}"
      gs_secret_key: "{{gcs_secret_key}}"
      bucket: "postgres-wall"
      object: "/{{client_name}}-{{client_env}}"
      mode: "create"
```

When I run the playbook I get this error :

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 1766, in <module>
    main()
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 395, in main
    handle_create(module, gs, bucket, obj)
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 333, in handle_create
    create_dirkey(module, gs, bucket, dirobj)
UnboundLocalError: local variable 'dirobj' referenced before assignment
```

But when I run again the playbook, the task succeed.
##### Steps To Reproduce:

Should succeed.
##### Actual Results:

The results:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 1766, in <module>
    main()
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 395, in main
    handle_create(module, gs, bucket, obj)
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 333, in handle_create
    create_dirkey(module, gs, bucket, dirobj)
UnboundLocalError: local variable 'dirobj' referenced before assignment
```

Thanks,
Antoine Rouaze

**Comment by abadger** [comment]
Most modules have moved to another repository.  This one has moved to https://github.com/ansible/ansible-modules-core so issues should be filed there.

I've copied it over there for you:
https://github.com/ansible/ansible-modules-core/issues/500

**Comment by Erouan50** [comment]
Oh sorry, thanks !

Antoine Rouaze
