### ISSUE TITLE
Runner._remote_checksum traceback when used with delegate_to containing var in it

### ISSUE THREAD

**Issue by redbaron** [ansible/ansible#9838]
##### Issue Type:

"Bug Report"
##### Ansible Version:

1.8.2
##### Environment:

Ubuntu 12.04
##### Summary:

Modules using `Runner._remote_checksum` (like template, copy, etc)  are broken when used with delegate_to  containing var in it
##### Steps To Reproduce:

Take following playbook and save as _delegat_test.yml_:

```
- hosts: all
  gather_facts: no
  vars:
    d: 127.0.0.1
  tasks:
    - copy:
        dest: /tmp/tmpl
        content: lalalala
      delegate_to: "{{ d }}"
```

Then run as following (note that "-c local" doesn't make any difference for the purpose of this ticket): 

```
ansible-playbook -c local -i '127.0.0.1,' delegate_test.yml
```
##### Expected Results:

Results from 1.7.2

```
PLAY [all] ******************************************************************** 

TASK: [copy ] ***************************************************************** 
changed: [127.0.0.1 -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [all] ******************************************************************** 

TASK: [copy ] ***************************************************************** 
fatal: [127.0.0.1 -> 127.0.0.1] => Traceback (most recent call last):
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1025, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/runner/action_plugins/copy.py", line 181, in run
    remote_checksum = self.runner._remote_checksum(conn, tmp_path, dest_file, inject)
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1231, in _remote_checksum
    python_interp = inject['hostvars'][inject['delegate_to']].get('ansible_python_interpreter', 'python')
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/runner/__init__.py", line 103, in __getitem__
    result = self.inventory.get_variables(host, vault_password=self.vault_password).copy()
  File "/home/rossmohax/repos/vdna/ansible/.pyenv/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 442, in get_variables
    raise Exception("host not found: %s" % hostname)
Exception: host not found: {{ d }}


FATAL: all hosts have already failed -- aborting
```

**Comment by abadger** [comment]
From what you describe, I think this was fixed in: https://github.com/ansible/ansible/commit/3269a349f32a2b5c1fc079a2d174e01c541f444b  If you'd like to try the patch  to lib/ansible/runner/**init**.py  I think that will solve this issue.

That fix will be included when we make our next ansible release.

**Comment by redbaron** [comment]
Tested 3269a349f32a2b5c1fc079a2d174e01c541f444b and it works as expected

**Comment by EronWright** [comment]
Since this is a regression from 1.8.1, would it make sense to backport this as 1.8.3 rather than coupling with 1.9?

**Comment by axos88** [comment]
+1 for backporting to 1.8.3

**Comment by abadger** [comment]
If there is a 1.8.3 this probably will go into it.  However, I don't yet know if there will be a 1.8.3 or if the next release will be 1.9.

**Comment by maspwr** [comment]
We just hit this bug in production, so a `1.8.3` release would be much appreciated.

**Comment by ndemengel** [comment]
+1 for backporting to 1.8.3

**Comment by Govinda-Fichtner** [comment]
We also just hit this bug in production, so a 1.8.3 release would be much appreciated.

**Comment by EronWright** [comment]
I see that this regression was not backported to 1.8.3 or 1.8.4.   Please consider doing so for 1.8.5.

**Comment by redbaron** [comment]
Ammount of bugs and problems with 1.8 goes over the roof, how is it even considered to be a release?
