### ISSUE TITLE
"ansible-galaxy list" fails with a traceback

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#9916]
See below (edited).

The original issue noted that on a clean install, the `/etc/ansible/roles` (the default path for roles in galaxy) does not exist leading to an error message.

**Comment by jimi-c** [comment]
@joaocc this behavior is expected,as that directory doesn't exist. However, on current devel, his actually fails in a much worse way (traceback):

<pre>
Traceback (most recent call last):
  File "/data/devel/ansible/bin/ansible-galaxy", line 66, in <module>
    sys.exit(cli.run())
  File "/data/devel/ansible/lib/ansible/cli/galaxy.py", line 134, in run
    self.execute()
  File "/data/devel/ansible/lib/ansible/cli/__init__.py", line 96, in execute
    fn()
  File "/data/devel/ansible/lib/ansible/cli/galaxy.py", line 483, in execute_list
    if gr.metadata:
UnboundLocalError: local variable 'gr' referenced before assignment
</pre>

So I'm going to update this issue to reflect the problem.

**Comment by bcoca** [comment]
fixed via 7215470c6fe561bbe9c4158bd3584b69b0917e68
